### ISSUE TITLE
Install on M1 Mac

### ISSUE THREAD

**Issue by rdlink** [koush/scrypted#100]
Been trying for 2+ days to install on an M1 Mac Mini running Monterey 12.1.  Even went as far as wiping the machine and installing before putting anything else on the machine.  After loading all of the prerequisites and running the installation script it keeps hanging while trying to start the server.  Screenshot of where it hangs:  https://imgur.com/a/bi0wLRt

**Comment by koush** [comment]
Is that a hang? It looks fine to me. What happens when you go to the web address?

**Comment by koush** [comment]
Yeah works fine on my M1. I think you need to just go to the web address shown in the log there. Scrypted won't launch the browser for you.

**Comment by rdlink** [comment]
Hmm.  You’re right.  I swear I couldn’t get the server to respond on the web interface last night.  Looks like I’m good now.  Thanks.  One more question.  Do you know of any harm in running two servers/hubs at the same time (temporarily)?  I want to verify this one is working before I rip out the old one.
