### ISSUE TITLE
rtsp Rebroadcast Inquiry

### ISSUE THREAD

**Issue by love10291029** [koush/scrypted#1010]
After the setup is complete, the following problems occur
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: Stream 1 prebuffer session starting
[Rebroadcast Plugin]: Stream 1 prebuffer session ended with error RPCResultError [TypeError]: Invalid URL
[Rebroadcast Plugin]:     at new NodeError (node:internal/errors:405:5)
[Rebroadcast Plugin]:     at Url.parse (node:url:445:17)
[Rebroadcast Plugin]:     at Object.url [as parse] (node:url:167:13)
[Rebroadcast Plugin]:     at g.createVideoStream (/src/rtsp.ts:63:27)
[Rebroadcast Plugin]:     at getVideoStream (/ffmpeg-camera/src/common.ts:81:21)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:37)
[Rebroadcast Plugin]: @scrypted/rtsp:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: test restarting prebuffer session in 5 seconds
<img width="2251" alt="截圖 2023-08-10 上午11 52 42" src="https://github.com/koush/scrypted/assets/23045374/5e77f247-6ba5-4a8b-b3c4-512f9dac7252">

author please help

**Comment by koush** [comment]
bad url. remove the [:554]

**Comment by love10291029** [comment]
Got this error
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: Stream 1 prebuffer session starting
stream url rtsp://192.168.31.155/live/profile.0
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e", uri="rtsp://192.168.31.155/live/profile.0", algorithm="MD5", response="1657d565ec0772c7183a974b7936efb9"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: Content-Base: rtsp://::ffff:192.168.31.155/live/profile.0/
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Content-Length: 806
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e", uri="rtsp://192.168.31.155/live/profile.0", algorithm="MD5", response="b23574ae62930a667efccb71d8b2927e"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: Stream 1 prebuffer session ended with error TypeError [ERR_INVALID_URL]: Invalid URL
[Rebroadcast Plugin]:     at new NodeError (node:internal/errors:405:5)
[Rebroadcast Plugin]:     at new URL (node:internal/url:611:13)
[Rebroadcast Plugin]:     at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143077)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async U.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:116729) {
[Rebroadcast Plugin]:   input: 'rtsp://::ffff:192.168.31.155/live/profile.0/',
[Rebroadcast Plugin]:   code: 'ERR_INVALID_URL'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: test restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:142830)
[Rebroadcast Plugin]:     at Socket.emit (node:events:514:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:323:12)
<img width="926" alt="截圖 2023-08-10 下午12 07 43" src="https://github.com/koush/scrypted/assets/23045374/fc760839-3a12-4efc-a73b-843f05f2fefc">

**Comment by love10291029** [comment]
> 錯誤的網址。刪除 [:554]

Got this error
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: Stream 1 prebuffer session starting
stream url rtsp://192.168.31.155/live/profile.0
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]: OPTIONS rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]: RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]: DESCRIBE rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]: RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e"
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]: DESCRIBE rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e", uri="rtsp://192.168.31.155/live/profile.0", algorithm="MD5", response="1657d565ec0772c7183a974b7936efb9"
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]: RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Aug 10 2023 04:06:46 GMT
[Rebroadcast Plugin]: Content-Base: rtsp://::ffff:192.168.31.155/live/profile.0/
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Content-Length: 806
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]: TEARDOWN rtsp://192.168.31.155/live/profile.0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="6e931c09e55cc5067f39081232cf4e4e", uri="rtsp://192.168.31.155/live/profile.0", algorithm="MD5", response="b23574ae62930a667efccb71d8b2927e"
[Rebroadcast Plugin]:
[Rebroadcast Plugin]: Stream 1 prebuffer session ended with error TypeError [ERR_INVALID_URL]: Invalid URL
[Rebroadcast Plugin]: at new NodeError (node:internal/errors:405:5)
[Rebroadcast Plugin]: at new URL (node:internal/url:611:13)
[Rebroadcast Plugin]: at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143077)
[Rebroadcast Plugin]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: at async U.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:116729) {
[Rebroadcast Plugin]: input: 'rtsp://::ffff:192.168.31.155/live/profile.0/',
[Rebroadcast Plugin]: code: 'ERR_INVALID_URL'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: test restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]: at Socket. (/@scrypted/prebuffer-mixin/main.nodejs.js:1:142830)
[Rebroadcast Plugin]: at Socket.emit (node:events:514:28)
[Rebroadcast Plugin]: at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]: at TCP. (node:net:323:12)
<img width="926" alt="截圖 2023-08-10 下午12 07 43" src="https://github.com/koush/scrypted/assets/23045374/f4a47de9-23b4-4a9a-850d-d51a7d296c1d">
