### ISSUE TITLE
Arlo: No cameras working

### ISSUE THREAD

**Issue by plingsi** [koush/scrypted#1016]
A couple of days ago all of my three Arlo cameras stopped working. Here is my log:

linux x64 #1 SMP PREEMPT_DYNAMIC Fri Jul 21 00:01:54 UTC 2023
server version: 0.41.0
plugin version: @scrypted/arlo 0.8.19
full
########################
8/12/2023, 8:57:12 PM
########################
python version: python3.10
python prefix: /data/scrypted_data/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230727
requirements.txt (up to date)
paho-mqtt==1.6.1
sseclient==0.0.22
aiohttp==3.8.4
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.4.0
cloudscraper==1.2.71
curl-cffi==0.5.7
async-timeout==4.0.2
beautifulsoup4==4.12.2
--extra-index-url=https://bjia56.github.io/armv7l-wheels/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
site-packages: /data/scrypted_data/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230727/local/lib/python3.10/dist-packages
Setting plugin verbosity to Verbose
Setting plugin transport to SSE
[Arlo Provider]: Trying connect to IMAP (attempt 1)
[Arlo Provider]: Connected to IMAP
[Arlo Provider]: Starting IMAP refresh loop 140465359936560
[Arlo Provider]: Performing IMAP login flow
[Arlo Provider]: Trying to initialize Arlo client...
[Arlo]: HTTP helper using curl_cffi
[Arlo]: Using primary authentication host
[Arlo Provider]: Initialized Arlo client, waiting for MFA code
[Arlo Provider]: Checking IMAP for MFA codes (attempt 1)
[Arlo Provider]: No new emails found, will sleep and retry
[Arlo Provider]: Scrypted requested to load device A5U112W000FFB
[Arlo Provider]: Cannot create device for nativeId A5U112W000FFB, maybe it hasn't been loaded yet?
[Arlo Provider]: Scrypted requested to load device A5JD267PD0357
[Arlo Provider]: Cannot create device for nativeId A5JD267PD0357, maybe it hasn't been loaded yet?
[Arlo Provider]: Scrypted requested to load device A5JD267RD025B
[Arlo Provider]: Cannot create device for nativeId A5JD267RD025B, maybe it hasn't been loaded yet?
[Arlo Provider]: Checking IMAP for MFA codes (attempt 2)
[Arlo Provider]: No new emails found, will sleep and retry
[Arlo Provider]: Checking IMAP for MFA codes (attempt 3)
[Arlo Provider]: Found MFA code
[Arlo Provider]: Completing Arlo MFA...
[Arlo]: HTTP helper using cloudscraper
[Arlo Provider]: Arlo MFA done
[Arlo Provider]: Discovering devices...
[Arlo Provider]: Discovered 0 basestations
[Arlo Provider]: Adding A5JD267PD0357
[Arlo Provider]: Interfaces for A5JD267PD0357 (VMC2030A parent A5JD267PD0357): ['DeviceProvider', 'VideoCamera', 'Camera', 'Intercom', 'MotionSensor', 'Settings', 'Charger', 'Battery', 'VideoClips']
[Arlo]: Received event: {"status":"connected"}
[Arlo]: SSE 140464370388944 connected
[Arlo A5JD267PD0357]: Started logging server at localhost:41567
[Arlo Provider]: Scrypted requested to load device A5JD267PD0357
[Arlo Provider]: Adding A5JD267RD025B
[Arlo Provider]: Interfaces for A5JD267RD025B (VMC2030A parent A5JD267RD025B): ['DeviceProvider', 'VideoCamera', 'Camera', 'Intercom', 'MotionSensor', 'Settings', 'Charger', 'Battery', 'VideoClips']
[Arlo A5JD267RD025B]: Started logging server at localhost:34291
[Arlo Provider]: Scrypted requested to load device A5JD267RD025B
[Arlo Provider]: Adding A5U112W000FFB
[Arlo Provider]: Interfaces for A5U112W000FFB (AVD2001A parent A5U112W000FFB): ['VideoCamera', 'Camera', 'Intercom', 'MotionSensor', 'Settings', 'Charger', 'Battery', 'BinarySensor']
[Arlo A5U112W000FFB]: Started logging server at localhost:38879
[Arlo Provider]: Discovered 3 cameras
[Arlo Provider]: Sending A5JD267PD0357 and children to scrypted server
[Arlo Provider]: Scrypted requested to load device A5U112W000FFB
[Arlo Provider]: Sending A5JD267PD0357.vss and children to scrypted server
[Arlo Provider]: Sending A5JD267RD025B and children to scrypted server
[Arlo Provider]: Sending A5JD267RD025B.vss and children to scrypted server
[Arlo Provider]: Sending top level devices to scrypted server
[Arlo Provider]: Done discovering devices
[Arlo]: Will send heartbeat to the following devices: []
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
########################
8/12/2023, 9:02:31 PM
########################
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
[Arlo]: Received event: {"status":"connected"}

**Comment by koush** [comment]
@bjia56

**Comment by bjia56** [comment]
Is the plugin still broken after a restart?

**Comment by plingsi** [comment]
No, after restart it works. Streaming in Homekit env is working, but unable to stream when using scrypted UI.

**Comment by bjia56** [comment]
I'll take a look at making this "connection broken" error less prevalent and self-correcting without a manual restart

**Comment by bjia56** [comment]
recent stable versions of the arlo plugin should make this situation much better. the event stream was reimplemented
