### ISSUE TITLE
Scrypted NVR Stuck on "Loading"

### ISSUE THREAD

**Issue by EverlyScott** [koush/scrypted#1029]
Hello, I just setup Scrypted NVR, but any time I try going back at all, it just shows a still frame and says "Loading..."
This is happening both on my self-hosted instance and on the demo site. I've also tried using safari on my phone, as well as chrome & firefox on my laptop.
Could this be an issue with my network?
Demo site:
<img width="901" alt="Demo site showing a loading screen" src="https://github.com/koush/scrypted/assets/31575858/379d7dbe-04c7-4c35-a86c-9a158b9c4147">

Local instance:
<img width="903" alt="Local instance showing a loading screen" src="https://github.com/koush/scrypted/assets/31575858/e18bfd35-01e8-48f4-ba55-2e5832512394">

**Comment by koush** [comment]
This is almost certainly a network issue, if demo site is not working. Please join Discord and I can help out further.

**Comment by koush** [comment]
Caused by time not set properly on host computer.
