### ISSUE TITLE
TAPO CAMERA SUPPORT

### ISSUE THREAD

**Issue by seduffes** [koush/scrypted#103]
Hi Koush,

I have just discovered SCRYPTED and it's impressive. I run it on my synology NAS and try to discover the different available features.

Unfortunately I can't find a plugin for my tapo cameras. That would be awesome if it could be integrated to your product.

Any plans to do this ?

Thanks a lot.

Best regards,
Sebastien

**Comment by koush** [comment]
if it is RTSP, follow that guide.

**Comment by koush** [comment]
also check onvif.
