### ISSUE TITLE
Trigger motion sense via webhook

### ISSUE THREAD

**Issue by andreibleortu** [koush/scrypted#1030]
Hello!

I'm running Scrypted under Home Assistant and I have a Cisco Meraki MV2 camera and I'd like to integrate it with HKSV. It has the ability to HTTP POST into a webhook, send an e-mail and send a SNMP trap when motion is detected. 

Unfortunately, I can't use the e-mail feature since an external Cisco server sends the e-mail and I can't seem to be able to send those messages to Scrypted. It would be great if I were able to use webhooks to trigger the motion sensing and offload the processing to Cisco, since it already does a whole lot of processing on the camera and in the cloud.

How can I do that using Scrypted? Is it even possible? I found the Webhook plugin but I can't seem to be able to trigger the motion detection indicator via any webhook at all.

Thank you
Andrei

**Comment by koush** [comment]
use dummy switch plugin. see docs.
