### ISSUE TITLE
RTSP cams on Unifi Protect #851 is unresolved. Please reopen and resolve or explain how this issue has been resolved.

### ISSUE THREAD

**Issue by davidew98** [koush/scrypted#1033]
I'm disappointed that you choose to lock the last issue instead of explaining how a UNresolved issue is deemed resolved!

Please explain!

_Originally posted by @davidew98 in https://github.com/koush/scrypted/issues/851#issuecomment-1687059968_

**Comment by mrMiimo** [comment]
> I'm disappointed that you choose to lock the last issue instead of explaining how a UNresolved issue is deemed resolved!
> 
> Please explain!
> 
> _Originally posted by @davidew98 in [#851 (comment)](https://github.com/koush/scrypted/issues/851#issuecomment-1687059968)_

to begin, you're in the wrong place.
In this menu (issues) operational errors, bugs or problems are reported.

If you want to propose a change, request a fetuare or if you have any questions, do so in the "discussions" menu.

Then, I assure you that I have read several times, what you asked and it is not possible to understand what you would like, explain yourself better
