### ISSUE TITLE
HomeKit:  "Never Wait For Snapshots" causes blank images in Home app

### ISSUE THREAD

**Issue by bbum** [koush/scrypted#104]
If "Never Wait for Snapshots" is turned on in the HomeKit plugin's Performance settings, it causes the Home app to display black images for the periodically updated, non-streaming, snapshots.

Turning it off restored the periodically updating images in the "Home" display.

**Comment by koush** [comment]
That's correct. It will eventually update with snapshots, but currently there's an iOS snapshot bug.
