### ISSUE TITLE
Reorder cameras in Cameras and Recordings does not work

### ISSUE THREAD

**Issue by cesarvoggithub** [koush/scrypted#1042]
Hide works, but reorder doesn't.

**Comment by koush** [comment]
Are you a home assistant user or is this a non admin user in scrypted

**Comment by koush** [comment]
Are you accessing local site, cloud, or via iOS app?

**Comment by cesarvoggithub** [comment]
Sorry I should have mentioned before. Current Scrypted NVR server is 0.41.0 running on a Mac mini M2.

**Comment by cesarvoggithub** [comment]
New information regarding this issue:

![Screenshot 2023-08-26 at 15 34 53](https://github.com/koush/scrypted/assets/96385801/b4ccfecf-10c3-4786-9465-4cd63b9c3c8a)

Actually, what does not seem to work to order (at least in the Mac app), is when trying to reorder using the above screen. I was able to reorder using the following screen in "NVR Preferences: <myuser>":

![Screenshot 2023-08-26 at 15 38 36](https://github.com/koush/scrypted/assets/96385801/a2e43e3b-20f8-4024-b3db-3035a8169d86)

**Comment by koush** [comment]
Can you try to reorder again in the browser, and get the output from the browser dev console? I'm not able to reproduce this issue.

**Comment by cesarvoggithub** [comment]
Darn, it's working now. I don't know if it's related, but there was a Scrypted Core update today...

**Comment by cesarvoggithub** [comment]
Originally, when I clicked over the up/down arrows, it would immediately hide the camera and I was not able to move the selection to the desired position... Tried in both the Mac App and via the <serverip>:10443...

**Comment by koush** [comment]
weird ok

**Comment by olinj** [comment]
I can not get my cameras to re order.  I go to the nvr app and it just hides them when i try to hit the up down arrows.  I tried this on my mac and on my phone.  Is there a way to change the code somehow?  i see when i hover over the camera on device tab in scrypted it has a number at the end of the link that shows up that coorilates to the order i see the cameras on scrypted.

**Comment by koush** [comment]
> I can not get my cameras to re order. I go to the nvr app and it just hides them when i try to hit the up down arrows. I tried this on my mac and on my phone. Is there a way to change the code somehow? i see when i hover over the camera on device tab in scrypted it has a number at the end of the link that shows up that coorilates to the order i see the cameras on scrypted.

which OS? iPhone or android?
