### ISSUE TITLE
What is the meaning of the dot to the right of the camera name?

### ISSUE THREAD

**Issue by cesarvoggithub** [koush/scrypted#1043]
I mean, I've seen it go Red, but hollow. Red, but full and Green and full. Most of the time all my cameras show the full red dot after the camera name. As far as I know, Scrypted seem to work as expected no matter the status of the dot.
I've searched the web and also read the Docs, but found no mention of the dot...

**Comment by koush** [comment]
Red is live. Blue is recording playback.

**Comment by cesarvoggithub** [comment]
![Screenshot 2023-08-24 at 18 05 06](https://github.com/koush/scrypted/assets/96385801/0527e082-fe4c-42c5-b86f-6bd9ea54c00f)
In the screen capture above, all dots show full red.

**Comment by cesarvoggithub** [comment]
Never seen blue. Only red full, hollow and full green.

**Comment by koush** [comment]
Red means recording in the grid
