### ISSUE TITLE
Google Home integration: "Could not reach Scrypted home automation"

### ISSUE THREAD

**Issue by jarrodCoombes** [koush/scrypted#1047]
When I try to connect Scrypted with Google home I get the error "Could not reach Scrypted home automation."

I have the Google Home plugin installed, and I am connected just fine to the Scrypted Cloud (as near as I can tell).

The plugin gives me the following log:
```
linux x64 #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023
server version: 0.41.0
plugin version: @scrypted/google-home 0.0.56
full
########################
8/27/2023, 1:35:19 AM
########################
node modules /server/volume/plugins/@scrypted/google-home/node18-linux-x64-20230727
plugin loaded
http://<IP>:11080/endpoint/@scrypted/google-home/public/
request sync result:
{"error":"Requested entity was not found."}
request failed due to invalid authorization TypeError: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:https:358:10)
    at y._performRequest (/node_modules/follow-redirects/index.js:279:24)
    at new y (/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/node_modules/follow-redirects/index.js:487:14)
    at /node_modules/axios/lib/adapters/http.js:202:25
    at new Promise (<anonymous>)
    at adapter (/node_modules/axios/lib/adapters/http.js:46:10)
    at e.exports (/node_modules/axios/lib/core/dispatchRequest.js:51:44) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```
My scrypted is behind a nginx reverse proxy, using the configuration I got [here](https://github.com/koush/scrypted/discussions/945)

It's probably worth mentioning that `https://<mydomain>` and `https://home.scrypted.app` work fine. Though viewing the public endpoint for the cloud plugin just spins and then times out (it tries to take me to (https://<mydomain>/endpoints/33/public`)

Any help would be greatly appreciated.

EDIT: 

Adding that my nginx server reponds with the following when google tries to request access:
```
 "POST /web/component/home/endpoint HTTP/1.1" 401 14 "-" "Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)"
```

So this has something to do with the the fact that the public endpoint for the Google plugin returns: ` Invalid value "undefined" for header "Authorization" `

So what I am doing wrong here? What have I not configured?

**Comment by koush** [comment]
your nginx configuration is using the wrong port. remove custom domain and reregister, or follow the instructions in the cloud plugin.
