### ISSUE TITLE
Python Codec fails to load - M1 Mac Mini w/ OS 13.5.1 -  Desktop install

### ISSUE THREAD

**Issue by jaredten** [koush/scrypted#1058]
darwin arm64 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
server version: 0.41.0
plugin version: @scrypted/python-codecs 0.1.84
########################
9/3/2023, 10:43:23 AM
########################
python version: python3.9
python prefix: /Users/jaredt/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-arm64
Removing old dependencies: /Users/jaredt/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-arm64
requirements.txt (outdated)
# needed by libav to_ndarray
numpy>=1.16.2

# gobject instrospection for gstreamer.
PyGObject>=3.30.4; sys_platform != 'win32'

# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'

# pyvips is not available on windows, and is preinstalled as part of the installer scripts on
# mac and linux.
pyvips; sys_platform != 'win32'

# in case pyvips fails to load, use a pillow fallback.
# pillow for anything not intel linux, pillow-simd is available on x64 linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'

Ignoring pillow-simd: markers 'sys_platform == "linux" and platform_machine == "x86_64"' don't match your environment
Collecting numpy>=1.16.2 (from -r /Users/jaredt/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-arm64/requirements.txt (line 2))
  Obtaining dependency information for numpy>=1.16.2 from https://files.pythonhosted.org/packages/0f/a8/5057b97c395a710999b5697ffedd648caee82c24a29595952d26bd750155/numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting PyGObject>=3.30.4 (from -r /Users/jaredt/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-arm64/requirements.txt (line 5))
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
        Using cached setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting pycairo
        Using cached pycairo-1.24.0.tar.gz (344 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [12 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.macosx-10.9-universal2-cpython-39
            creating build/lib.macosx-10.9-universal2-cpython-39/cairo
            copying cairo/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/cairo
            copying cairo/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-39/cairo
            copying cairo/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/cairo
            running build_ext
            'pkg-config' not found.
            Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/python/plugin_remote.py", line 634, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1

**Comment by koush** [comment]
Is this the Mac app? You don’t need Python codecs. Delete it, see migration guide in docs.

**Comment by koush** [comment]
https://docs.scrypted.app/migration.html#migrating-to-the-desktop-application
