### ISSUE TITLE
Due to a port conflict with Portainer, the default Scrypted URL has changed to 10443

### ISSUE THREAD

**Issue by cirrusflyer** [koush/scrypted#106]
I'm running the latest version on a Synology NAS.  Everything is working correctly.  Connecting to the WEBUI with port 9443.  But getting this message:

Due to a port conflict with Portainer, the default Scrypted URL has changed to https://****.*****:10443

 and not sure why it's still working on 9443.  Since the recommended network setting is to use the host network, there's no way to change the port.  In there an environmental variable that can be used?

**Comment by koush** [comment]
I’ll be disabling 9443 in a future update
 Both work for now.
