### ISSUE TITLE
Can't add camera via onvif

### ISSUE THREAD

**Issue by paulierco** [koush/scrypted#1060]
Hello,

I cannot add a camera via onvif. It's not a specifiv brand but I have no problem to add the camera to Synology Surveillance Station. I know I can add the camera via Synology plugin but I want to have scrypted standalone and not dependend on other system.

Error I received is: ONVIF SOAP Fault: Method 'GetVideoSources' not implemented: method name or namespace not recognized host:@scrypted/onvif engine.io-client:api

Thanks in advance.

**Comment by koush** [comment]
The camera may not support enumeration of all video streams, or only has 1 stream. You'll need to add manually with RTSP plugin
