### ISSUE TITLE
Excessive number of connections in ONVIF Camera Plugin

### ISSUE THREAD

**Issue by git-nerd** [koush/scrypted#1063]
Not sure this is a new problem or not, but the camera plugin makes too many concurrent connections to the camera at the same time (I’ve seen it go as much as 30K simultaneous connections). I noticed this because cameras and scrypted server are on different network subnets and go through my firewall.

This flood of connections are in FIN_WAIT or TIME_WAIT state, except for 2 3 connections which are in ESTABLISHED state. All these connections are outbound to either 1024 or 1025 ports.

I checked the debug logs, and I see a flood of SOAP messages related to motion events.

I’m surprised that this is not choking the poor camera. For now I have limited the range of outbound ports (net.ipv4.ip_local_port_range) of the scrypted server manually to 500 ports and it *seems* to be working fine.

Camera(s) are tapo C210 and C225 btw.

**Comment by kiler129** [comment]
TCP in `FIN_WAIT` and `TIME_WAIT` are closed from the endpoint's perspective. Your firewall may be misconfigured and doesn't allow for proper connection closure.
