### ISSUE TITLE
Memeory leak M2 MacOS?

### ISSUE THREAD

**Issue by jpettitt** [koush/scrypted#1074]
Running on MacOS on an M2 mini all updates applied and I'm seeing OOM crashes.  System is 6 reolink cameras (doorbell, 3 x 811a and 2 x duo 2.  The 811's are in 2k mode.  The Due is in full res withe ffmpeg transcoding.  The memory leak appears to be in `VTDecoderXPCService` which grows until OOM.

**Comment by koush** [comment]
Can you see if the OOM stops if you disable transcoding?

**Comment by koush** [comment]
The Decoder sessions that scrypted nvr uses are fairly short lived for object detection. I'm guessing the OOM is in that continual ffmpeg transcode which shells out to Video Toolbox maybe.

**Comment by jpettitt** [comment]
Will try that when I get home (I'm accessing from NY over tailscale at the moment)

**Comment by koush** [comment]
Screenshot of your transcode settings would be helpful too.
