### ISSUE TITLE
QNAP Container Station has changed with QTS 5.1; installation doc needs updates

### ISSUE THREAD

**Issue by JeffGoldner** [koush/scrypted#1082]
Container Station interfaces has undergone several major changes with QTS 5.1 and yet again in latest version. Docs/screenshots need to be updated.

I can attempt to update over the next few days.

**Comment by koush** [comment]
Wikis are no longer user editable, so you can submit the new contents in here. Issues supports markdown as well.

**Comment by JeffGoldner** [comment]
Attaching screenshots for QTS 5.1 or really Container Station latest version - probably best to add rather than replace.
<img width="1035" alt="Screenshot 2023-10-11 at 2 03 56 PM" src="https://github.com/koush/scrypted/assets/13804067/af9fb09d-224e-4849-b8d7-d2e17b0f7fa2">
<img width="1034" alt="Screenshot 2023-10-11 at 2 03 23 PM" src="https://github.com/koush/scrypted/assets/13804067/c8da4597-8639-470f-8d8f-9116a3f25397">
Change network to Host
<img width="1034" alt="Screenshot 2023-10-11 at 2 09 51 PM" src="https://github.com/koush/scrypted/assets/13804067/ba6af8f7-7f3e-4257-8065-9ed54320274f">
Map the previously created path to /server/volume so you can reuse settings when manually updating the image (new container)
<img width="1034" alt="Screenshot 2023-10-11 at 2 11 01 PM" src="https://github.com/koush/scrypted/assets/13804067/53c0d988-f733-4891-a0b4-b6d1ef576692">
<img width="1034" alt="Screenshot 2023-10-11 at 2 11 36 PM" src="https://github.com/koush/scrypted/assets/13804067/fb45c2ff-3cc7-42d2-a248-9048c430f6fa">
