### ISSUE TITLE
I 🤎 SCRYPTED [not bug, just extend support request]

### ISSUE THREAD

**Issue by mrMiimo** [koush/scrypted#11]
Hi @koush,
first of all: this is a fantastic, very useful job, which I loved.
I landed here because I tried to activate Homekit Secure Video and after installing "scrypted", I confess that I now use it for some automation.

Unfortunately I can't use HKSV because I have Hikvision cameras and the "_@scrypted/rtsp_" plugin doesn't support it.
Do you think it is possible for "_@scrypted/rtsp_" to support HKSV?

Thanks again for "scrypted"!

**Comment by JW-1000** [comment]
Yes please <3

**Comment by koush** [comment]
Hikvision camera support was just added.

**Comment by mrMiimo** [comment]
> Hikvision camera support was just added.

So you want to tell me that I can already use HKSV? 🤯🤯🤯🤯🤯
In case, I have to do a special configuration or just install the @scrypted/rtsp plugin?

**Comment by koush** [comment]
install the @scrypted/hikvision plugin.

**Comment by JW-1000** [comment]
May I request the same for Swann ? Shall I create  another issue ?

**Comment by mrMiimo** [comment]
> install the @scrypted/hikvision plugin.

almost done!!! man this is aaaaaaamazing 🤩

So, I installed the hikvision plugin, previously I activated the motion sensor etc etc, I know it works because I see it in the logs.

But I don't have any videos in Scrypted or Homekit, it's always loading... and I don't know why... 🤷🏻‍♂️
I have an NVR with 4 cams 🤦🏻‍♂️
![Schermata 2021-09-13 alle 22 00 47](https://user-images.githubusercontent.com/49750870/133148734-c6eef75a-275a-4b75-9e6d-42b2aa3c7637.png)
<img width="775" alt="Schermata 2021-09-13 alle 21 58 14" src="https://user-images.githubusercontent.com/49750870/133148739-e6f9b18b-8709-4e58-a9d4-66f6ca30318d.png">

**Comment by koush** [comment]
Please join the discord so I can diagnose this. Lot of variation in the HIKVision cameras.
