### ISSUE TITLE
OpenCV Failed to Load

### ISSUE THREAD

**Issue by barqers** [koush/scrypted#1101]
Looks like installing Scrypted in Home Assistant on an ARM device throws an error when using OpenCV:

`linux x64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2~bpo11+1 (2023-04-23)
server version: 0.55.0
plugin version: @scrypted/opencv 0.0.89
full
########################
9/27/2023, 9:10:28 PM
########################
python version: python3.10
python prefix: /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727
Removing old dependencies: /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727
requirements.txt (outdated)
# plugin
numpy>=1.16.2
# pillow for anything not intel linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'
imutils>=0.5.0
# opencv-python is not available on armhf
# locked to version because 4.8.0.76 is broken.
opencv-python==4.8.0.74; sys_platform != 'linux' or platform_machine == 'x86_64'

Ignoring Pillow: markers 'sys_platform != "linux" or platform_machine != "x86_64"' don't match your environment
Requirement already satisfied: numpy>=1.16.2 in /usr/lib/python3/dist-packages (from -r /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/requirements.txt (line 2)) (1.21.5)
Collecting pillow-simd (from -r /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/requirements.txt (line 5))
  Using cached Pillow_SIMD-9.0.0.post1-cp310-cp310-linux_x86_64.whl
Collecting imutils>=0.5.0 (from -r /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/requirements.txt (line 6))
  Using cached imutils-0.5.4-py3-none-any.whl
Collecting opencv-python==4.8.0.74 (from -r /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/requirements.txt (line 9))
  Obtaining dependency information for opencv-python==4.8.0.74 from https://files.pythonhosted.org/packages/34/7c/8a5043f362b0a55f07812a0db3f86092cdbd0fe41b933d7bc6fce3ab6c15/opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Using cached opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
Installing collected packages: imutils, pillow-simd, opencv-python
Successfully installed imutils-0.5.4 opencv-python-4.8.0.74 pillow-simd-9.0.0.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pip install result 0
site-packages: /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/local/lib/python3.10/dist-packages
plugin start/fork failed
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 743, in loadZipWrapped
    from main import create_scrypted_plugin  # type: ignore
  File "/data/scrypted_data/plugins/@scrypted/opencv/zip/1-82ebbf5244213bd00336ce8b05902ab1.zip/main.py", line 1, in <module>
    from opencv import OpenCVPlugin
  File "/data/scrypted_data/plugins/@scrypted/opencv/zip/1-82ebbf5244213bd00336ce8b05902ab1.zip/opencv/__init__.py", line 8, in <module>
    import cv2
  File "/data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /data/scrypted_data/plugins/@scrypted/opencv/python3.10-Linux-x86_64-20230727/local/lib/python3.10/dist-packages/cv2/cv2.abi3.so: failed to map segment from shared object
`

**Comment by AdamCoulterOz** [comment]
@koush - what was the fix here? I'm getting the same/similar error here:

```
linux arm #1529 SMP Tue Mar 8 12:24:00 GMT 2022
server version: 0.68.0
plugin version: @scrypted/opencv 0.0.89
full
########################
12/16/2023, 4:49:16 AM
########################
python version: python3.10
python prefix: /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727
Removing old dependencies: /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727
requirements.txt (outdated)
# plugin
numpy>=1.16.2
# pillow for anything not intel linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'
imutils>=0.5.0
# opencv-python is not available on armhf
# locked to version because 4.8.0.76 is broken.
opencv-python==4.8.0.74; sys_platform != 'linux' or platform_machine == 'x86_64'

Ignoring pillow-simd: markers 'sys_platform == "linux" and platform_machine == "x86_64"' don't match your environment
Ignoring opencv-python: markers 'sys_platform != "linux" or platform_machine == "x86_64"' don't match your environment
Requirement already satisfied: numpy>=1.16.2 in /usr/lib/python3/dist-packages (from -r /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727/requirements.txt (line 2)) (1.21.5)
Requirement already satisfied: Pillow>=5.4.1 in /usr/lib/python3/dist-packages (from -r /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727/requirements.txt (line 4)) (9.0.1)
Collecting imutils>=0.5.0 (from -r /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727/requirements.txt (line 6))
  Downloading imutils-0.5.4.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: imutils
  Building wheel for imutils (setup.py): started
  Building wheel for imutils (setup.py): finished with status 'done'
  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25858 sha256=d9fec1c99156e47b4727e3f2dee75b3b11900b456414235e20654c8bca4af90f
  Stored in directory: /root/.cache/pip/wheels/85/cf/3a/e265e975a1e7c7e54eb3692d6aa4e2e7d6a3945d29da46f2d7
Successfully built imutils
Installing collected packages: imutils
Successfully installed imutils-0.5.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pip install result 0
site-packages: /server/volume/plugins/@scrypted/opencv/python3.10-Linux-armv7l-20230727/local/lib/python3.10/dist-packages
########################
12/16/2023, 6:18:36 AM
########################
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.

... continues for pages
```

**Comment by koush** [comment]
get on arm 64
