### ISSUE TITLE
Snapshot URL missing

### ISSUE THREAD

**Issue by mchangsp** [koush/scrypted#1109]
I am using Scrypted + snapshot plugin with Eufy and Reolink camera's.
On all camera's the snapshot URL is missing. See screenshot. Where can I find teh snapshot URL for a specific camera in Scrypted?

![image](https://github.com/koush/scrypted/assets/13312076/ab9f3a99-2fc6-4069-a50f-fe44eec080b6)

**Comment by koush** [comment]
you don't need it.

**Comment by jericsmith504** [comment]
http://cam-ip/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=1234abc&user=USERNAME&password=PASSWORD worked for me for the Reolink plugin to get a snapshot (otherwise would fail)

**Comment by noobey** [comment]
I also need this URL from scrypted. Can anyone explain how to pull it from Scrypted?
