### ISSUE TITLE
Snapshot Aspect Ratio Incorrect

### ISSUE THREAD

**Issue by rawrmcrawrrawr** [koush/scrypted#1113]
Aspect Ratio for snapshots in Home App is incorrect for 4:3 Aspect Ratio cameras. Snapshot plugin downsizes all snapshots from cameras to 1280x720 regardless if camera is 16:9 or 4:3.

Snapshots from Prebuffer = Disable
Snapshot Resolution = Default

iOS 17.0.2

All snapshots work. Just the aspect ratio is incorrect for 4:3 cameras.

linux x64 #64570 SMP Tue Jun 13 21:39:55 CST 2023
server version: 0.55.0
plugin version: @scrypted/snapshot 0.0.63
full
########################
10/3/2023, 12:41:37 AM
########################
node modules /server/volume/plugins/@scrypted/snapshot/node18-linux-x64-20230727
plugin loaded
[Garage] Picture requested from camera undefined
[Patio] Picture requested from camera undefined
[Master] Picture requested from camera undefined
[Gate] Picture requested from camera undefined
[Doorbell] Picture requested from camera undefined
[Doorbell] Resizing picture from camera { width: 1280, height: 720 }
[Master] Resizing picture from camera { width: 1280, height: 720 }
[Patio] Resizing picture from camera { width: 1280, height: 720 }
[Gate] Resizing picture from camera { width: 1280, height: 720 }
[Garage] Resizing picture from camera { width: 1280, height: 720 }

**Comment by koush** [comment]
is this still happening?

**Comment by koush** [comment]
snapshot generation was completely rewritten, don't think this issue exists anymore.
