### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by the1maximus** [koush/scrypted#112]
Any chance there would be a windows version in the near future?  I don’t want to mess with my Homebridge instance on my Rasp Pi, and I would personally like to run this on my Dell PowerEdge r710 locally, since it has more then enough horsepower. 

Either way, thanks for the work you guys put into this, it’s great to see more options opening up for integrating all of our devices.

**Comment by koush** [comment]
I'd try WSL2 in host networking mode. Use docker inside WSL2.
