### ISSUE TITLE
Google Nest Doorbell (Battery) - 2 Way Audio

### ISSUE THREAD

**Issue by PhilTheNewbie** [koush/scrypted#1129]
Firstly, thank you for making a Scrypted plugin for Google Nest Doorbell to work inside of HomeKit. I have tried Homebridge, but could not make it work. The Scrypted installation process (with detailed instructions) were simple and effective.

Secondly, do you have any plans to add 2 way audio to the plugin? 

Thank you in advance! Phil.

**Comment by cirrusflyer** [comment]
I understand that 2 way audio is not supported by the Google/Nest API that's being use here.
