### ISSUE TITLE
RTSP Camera Plugin or FFmpeg Camera Plugin

### ISSUE THREAD

**Issue by cirrusflyer** [koush/scrypted#113]
For stability and performance, is there a preference using the RTSP Camera Plugin or FFmpeg Camera Plugin for Wyze cameras with the Wyze RTSP firmware?

**Comment by koush** [comment]
RTSP

**Comment by koush** [comment]
You can get help on discord. lol of wyze users. I am not one.

**Comment by pilot1981** [comment]
> Thanks! Are there any settings you recommend tweaking or enabling/disabling for use with Wyze cameras with the Wyze RTSP firmware?
> 
> Great work BTW. Amazing that I can use $30 Wyze cameras in HKSV.

Can you share webcam Wyze model are you using?

**Comment by cirrusflyer** [comment]
I have both v2 and v3 cams. Thanks
