### ISSUE TITLE
Unable to install on homeassistant

### ISSUE THREAD

**Issue by asosnovsky** [koush/scrypted#1139]
**Describe the bug**
Just added the repository to home assistant and tried installing for the first time and I have been getting this error for the past few days (possibly a misconfiguration or missing build?):

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: October 15, 2023 at 10:04:26 PM (3 occurrences) 
Last logged: 10:20:02 AM

Failed to to call /addons/09e60fb6_scrypted/install - Can't install ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0/json: Not Found ("No such image: ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0")

**To Reproduce**
1. Add repository to home assistant 
2. Press install
3. See logs in home assistant 

**Expected behavior**
Should be installed

**Desktop (please complete the following information):**
 - OS: Home assistant OS
 - running on home assistant yellow

**Comment by koush** [comment]
https://github.com/users/koush/packages/container/scrypted/137020793?tag=18-jammy-full.s6-v0.57.0

**Comment by koush** [comment]
it's there. not sure why you can't get it. probably not a scrypted issue.

**Comment by itaiperi** [comment]
Hi @koush, I'm getting a similar error:
`Can't install ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0/json: Not Found ("No such image: ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0")`

Not sure it's only this guy's problem.

Note: I'm running Home Assistant Supervised on a Linux VM on a Macbook M1 machine (virtualized, meaning aarch64 architecture, not emulated with x86_64 architecture)

**Comment by stibbzy** [comment]
Hi @koush Same problem for me here, never had issues with other versions in Home Assistant:
Error updating Scrypted: Can't install ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0/json: Not Found ("No such image: ghcr.io/koush/scrypted:18-jammy-full.s6-v0.57.0")
