### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by danielsza** [koush/scrypted#114]
Creating scrypted ... done
Attaching to scrypted
scrypted    | Node.js[8]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
scrypted    | Aborted (core dumped)
scrypted exited with code 134

**Comment by koush** [comment]
Upgrade your host os to bullseye. You are on buster and it’s quite old.
