### ISSUE TITLE
Rebroadcast Plugin Not Working for Reolink 

### ISSUE THREAD

**Issue by RayRein** [koush/scrypted#1146]
I haven't been able to get my Reolink RLC-810A to work with Home Assistant using the Scrypted Add-on and Reolink and Reolink Camera plugins. The camera is connected to a Reolink RLN8-410 NVR. I'm using the IP Address designated in the Reolink desktop app, which shows both the camera and the NVR. My problem comes after I've installed the Reolink Camera plugin. I get a snapshot view of the scene from the camera, but when I click on it, I only get a black box. Checking the Console, I find what appears to be errors with the Rebroadcast Plugin:

linux arm64 #1 SMP Fri Oct 13 13:05:19 UTC 2023
server version: 0.57.0
plugin version: @scrypted/reolink 0.0.46
full
########################
10/23/2023, 4:59:43 PM
########################
listen loop error, restarting listener. Error: new settings
    at /rtsp/src/rtsp.ts:234:49
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
listen loop error, restarting listener. Error: new settings
    at /rtsp/src/rtsp.ts:234:49
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
listen loop error, restarting listener. Error: new settings
    at /rtsp/src/rtsp.ts:234:49
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
listen loop error, restarting listener. Error: new settings
    at /rtsp/src/rtsp.ts:234:49
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: prebuffer sessions releasing if started
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: prebuffer sessions releasing if started
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: Error starting RTSP Rebroadcast Server. Retrying shortly. If this problem persists, consider assigning a different port. This warning can be ignored if the rebroadcast URL is not in use. Error: listen EADDRINUSE: address already in use :::35573
[Rebroadcast Plugin]:     at Server.setupListenHandle [as _listen2] (node:net:1751:16)
[Rebroadcast Plugin]:     at listenInCluster (node:net:1799:12)
[Rebroadcast Plugin]:     at Server.listen (node:net:1887:7)
[Rebroadcast Plugin]:     at U.startRtspServer (/@scrypted/prebuffer-mixin/main.nodejs.js:1:129028)
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:127301
[Rebroadcast Plugin]:     at new U (/@scrypted/prebuffer-mixin/main.nodejs.js:1:127586)
[Rebroadcast Plugin]:     at K.q [as newPrebufferMixin] (/@scrypted/prebuffer-mixin/main.nodejs.js:1:140148)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/dist/rpc.js:591:66)
[Rebroadcast Plugin]:     at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/dist/rpc.js:539:18)
[Rebroadcast Plugin]:     at MessagePort.<anonymous> (/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js:23:75) {
[Rebroadcast Plugin]:   code: 'EADDRINUSE',
[Rebroadcast Plugin]:   errno: -98,
[Rebroadcast Plugin]:   syscall: 'listen',
[Rebroadcast Plugin]:   address: '::',
[Rebroadcast Plugin]:   port: 35573
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTMP main.bcs exiting prebuffer session (released or restarted with new configuration)
[Rebroadcast Plugin]: stream RTMP ext.bcs is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTMP sub.bcs is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTSP h264Preview_01_main is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTSP h264Preview_01_sub is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
[Rebroadcast Plugin]: stream RTMP ext.bcs is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTMP sub.bcs is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTSP h264Preview_01_main is not enabled and will be rebroadcast on demand.
[Rebroadcast Plugin]: stream RTSP h264Preview_01_sub is not enabled and will be rebroadcast on demand.
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:42325/59f823916e167367
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
listen loop error, restarting listener. Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined',
  config: {
    url: 'http://undefined/api.cgi?cmd=GetMdState&channel=0&user=undefined&password=undefined',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 0,
    adapter: [Function (anonymous)],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api.cgi?cmd=GetMdState&channel=0&user=undefined&password=undefined',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'undefined',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api.cgi',
      search: '?cmd=GetMdState&channel=0&user=undefined&password=undefined'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api.cgi?cmd=GetMdState&channel=0&user=undefined&password=undefined HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: undefined\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api.cgi?cmd=GetMdState&channel=0&user=undefined&password=undefined',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'undefined',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://undefined/api.cgi?cmd=GetMdState&channel=0&user=undefined&password=undefined',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:34063/94e5a201c1a72ce5
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:44575/81fd99d9c7c14637
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:44235/02cac312aac997b1
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:33103/6f9dd9ea78304efe
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:38365/dfc7bb7063a0f944
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:36585/528e8e304d397acd
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:38763/cebb8f8916628124
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:35845/b00417bb09005c18
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:45225/001d0490273f9887
[Rebroadcast Plugin]: rtmp://rayrein74:HomeKit%2388@192.168.1.141:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=rayrein74&password=HomeKit%2388: Input/output error
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds

**Comment by koush** [comment]
use a simple password.

**Comment by RayRein** [comment]
Thank you so much -- I never would have guessed!
