### ISSUE TITLE
engine.io plugin error RPCResultError: device XX does not exist

### ISSUE THREAD

**Issue by haffi78** [koush/scrypted#1151]
**Describe the bug**
When I run the docker in Console I get a spam of 

engine.io plugin error RPCResultError: device "(Random numbers here repeating )"  does not exist

This is a new docker with no config. 
I.e. I am prompted on the web page to set the admin username and pass.

**To Reproduce**
New install 
run docker-compose up

**Expected behavior**
no spamming logs ?

**Desktop (please complete the following information):**
 - OS: Linux Redhat 8.8

**Comment by 24fpsDaVinci** [comment]
same issue on debian bookworm

**Comment by koush** [comment]
can be workaround w/ a server restart. something on the web client has cached a deleted plugin.

**Comment by haffi78** [comment]
I reinstalled the server, same result, ie i removed the docker and config, reinstalled and still same error even before i launched the web client.

**Comment by raelix** [comment]
I have the same issue, is there a way to know what's the device?

**Comment by koush** [comment]
54453112
