### ISSUE TITLE
Feature Request : Allow 90 degree video rotation

### ISSUE THREAD

**Issue by briangunderson** [koush/scrypted#1164]
Title says it all. I have a camera which is focused on an object that is roughly twice as tall as it is wide. Ideally I would flip the camera on its side so the image sensor's aspect ratio is more closely aligned with that of the object being recorded. This setting would be applied to all aspects of the stream, including all video streams, snapshots, etc.

**Comment by briangunderson** [comment]
I know this can be accomplished by passing arguments to ffmpeg, but I'm not familiar with Scrypted's internals when using the macOS Apple Silicon application. Does it even use ffmpeg? I have no idea. Thanks!

**Comment by bjia56** [comment]
If you use the Rebroadcast plugin, one of the possible stream parsers is FFmpeg. Select that and update the ffmpeg output parameters to add a rotation filter.

**Comment by briangunderson** [comment]
Thanks for the reply. I wasn't able to get it to work properly in my Apple Silicon setup. Anytime I tried to add any custom FFMpeg parameters to rebroadcast the video feed simply turned black no matter what settings I used (including transpose=1). Any suggestions? Thanks!

**Comment by bjia56** [comment]
Most likely ffmpeg exited due to invalid flags, since those output parameters are injected into the middle of an existing ffmpeg flag sequence. You can check the camera's logs for what ffmpeg arguments are being passed. Can also run ffmpeg locally and use the rebroadcast rtsp feed as the input to test different filters.

**Comment by briangunderson** [comment]
If you happen to have a working example of the required syntax it would be super appreciated!

**Comment by bjia56** [comment]
`-c:v libx264 -pix_fmt yuvj420p -preset ultrafast -bf 0 -vf transpose=1` works on my camera. Note that rotation is a very CPU-intensive operation as it is doing a transcode.

**Comment by bjia56** [comment]
tbh, it's probably better if you are able to physically rotate the camera and use the native stream than to rotate it in-software, it will use a lot of CPU and increase stream latency

**Comment by koush** [comment]
doing this on camera with their encoder or physically rotating it is preferred.

**Comment by briangunderson** [comment]
> `-c:v libx264 -pix_fmt yuvj420p -preset ultrafast -bf 0 -vf transpose=1` works on my camera. Note that rotation is a very CPU-intensive operation as it is doing a transcode.

That's exactly what I needed. I was just using the wrong syntax. I have plenty of transcode resources available so, for me, the pros outweigh the cons here. The aspect ratio of the object (a tall terrarium for tree frogs) is roughly 9:16 so being able to utilize the majority of the pixels on the camera's sensor is a huge boost. Even with this fairly high-end-ish camera (Unifi G5 Pro) the image gets pretty grainy when it has to be cropped down to fit. Thank you!

**Comment by oopuuu** [comment]
> > `-c:v libx264 -pix_fmt yuvj420p -preset ultrafast -bf 0 -vf transpose=1` works on my camera. Note that rotation is a very CPU-intensive operation as it is doing a transcode.
> 
> That's exactly what I needed. I was just using the wrong syntax. I have plenty of transcode resources available so, for me, the pros outweigh the cons here. The aspect ratio of the object (a tall terrarium for tree frogs) is roughly 9:16 so being able to utilize the majority of the pixels on the camera's sensor is a huge boost. Even with this fairly high-end-ish camera (Unifi G5 Pro) the image gets pretty grainy when it has to be cropped down to fit. Thank you!

By using these arguments ,the snapshot was also rotated?

**Comment by briangunderson** [comment]
Honestly I can’t remember. I ended up changing how that camera is mounted
and it’s been awhile now.
