### ISSUE TITLE
dazzling_bartik

### ISSUE THREAD

**Issue by arlogilbert** [koush/scrypted#117]
What purpose does the dazzling_bartik docker image serve? It appears to be running in addition to the scrypted image.

**Comment by koush** [comment]
not sure what you're talking about. that's probably a random container name. if you followed the wiki guide, it's probably watchtower?

**Comment by arlogilbert** [comment]
pi@REDACTED:~/scrypted $ docker ps -a
CONTAINER ID   IMAGE            COMMAND                  CREATED          STATUS                        PORTS     NAMES
7af12f319f02   koush/scrypted   "docker-entrypoint.s…"   17 minutes ago   Up 12 minutes                           scrypted
7ce4d4a1fc54   koush/scrypted   "docker-entrypoint.s…"   2 hours ago      Exited (137) 26 minutes ago             dazzling_bartik

**Comment by koush** [comment]
looks like a terminated instance. you ran it twice.
