### ISSUE TITLE
method SETUP failed: 461 Unsupported Transport

### ISSUE THREAD

**Issue by GravityRZ** [koush/scrypted#1172]
i am using the latest version of scrypted and the reolink plugin 
checking the log i see this
[Reolink Doorbell] method SETUP failed: 461 Unsupported Transport
this seems to be a common error when using FFMPEG(which seemed to be used by RTSP underneath)

is there a way to get rid of this error by perhaps adding an FFMPEG prefix option
Also it could be that this is caused by an old FFMPEG binary.

**Comment by koush** [comment]
not an error.

**Comment by GravityRZ** [comment]
ok. so this does not cause any problems right?
