### ISSUE TITLE
Docker image needs to optimized

### ISSUE THREAD

**Issue by agneevX** [koush/scrypted#118]
Currently, the Docker image is quite large, clocking around 2.5GB when _unzipped_.

This can be optimized by clubbing apt-get commands together for starters.

<img width="334" alt="Screen Shot 2022-01-16 at 12 50 15 PM" src="https://user-images.githubusercontent.com/19761269/149651052-6b9ca767-3764-43a0-920a-2782bf351973.png">

**Comment by koush** [comment]
> This can be optimized by clubbing apt-get commands together for starters.

I'm not super docker savvy. how would this help? Since the apt commands only add files, combining them may reduce layers, but I don't think it would reduce the size?

**Comment by agneevX** [comment]
Yes, I didn't elaborate, but APT's lists can be removed in the same layer.

**Comment by koush** [comment]
This Dockerfile is the bulk of it, it contains all the dependencies. Feel free to try to build it yourself to trim it down.

https://github.com/koush/scrypted/blob/main/docker/Dockerfile.common

Another way to to provide "light" builds for users that don't need opencv or gstreamer.

**Comment by koush** [comment]
collapsing the apt commands resulted in negligible gains.
