### ISSUE TITLE
Tapo Cameras producing Auth Failed response. (Firmware 1.3.9)

### ISSUE THREAD

**Issue by sdwhwk** [koush/scrypted#1184]
I’m getting Auth Failed with my Tapo C211’s with firmware 1.3.9 build 231019. For S@$! and giggles, I set the username:password for both to tester:123456 to no avail.
`[Rebroadcast Plugin]: mainStream prebuffer session started
[Rebroadcast Plugin]: mainStream prebuffer session starting
stream url rtsp://192.168.1.127:554/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.127:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Tue, Nov 14 2023 04:58:03 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, GET_PARAMETER, SET_PARAMETER
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.127:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Tue, Nov 14 2023 04:58:03 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="1c39b182a51ed9352996bf9a165a8009"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.127:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic c2R3aHdrOkRlYWRwb29saXN0aGVncmVhdGVzdCE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Tue, Nov 14 2023 04:58:04 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="43220239b49af551727fd0e855fcc1f0"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.1.127:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic c2R3aHdrOkRlYWRwb29saXN0aGVncmVhdGVzdCE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:91909)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:144136)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:117624)
[Rebroadcast Plugin]: Tapo C211 restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143950)
[Rebroadcast Plugin]:     at Socket.emit (node:events:514:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:323:12) `
They work fine in Homebridge and native app. I’m trying to offload as much as I can off of Homebridge to centralize my devices in one platform (Home Assistant).

**Comment by koush** [comment]
think you need to enable digest auth.

**Comment by koush** [comment]
please provide a properly formatted log.

**Comment by koush** [comment]
also maybe try a shorter password.

**Comment by sdwhwk** [comment]
Actually, without touching it, it just started working a few minutes ago. Bought another c211 and added it to Scrypted and it worked right off the bat, same user:pass. But the other two still produced the error. Then one by one after in a thirty min. Span they started working. The only thing I did was restart the Tapo app a few times. But to be honest, I don’t know what could be a simpler pass in my test than 123456.

**Comment by koush** [comment]
might have been temp account lockout

**Comment by heinsenberg82** [comment]
I'm having the same issue. And, as far as I know, the Tapo C210 camera (which is a recommended camera in Scrypted docs) does not have a option to set digest auth.
