### ISSUE TITLE
Error when adding Reolink camera: Request failed with status code 404

### ISSUE THREAD

**Issue by sylarevan** [koush/scrypted#1188]
**Describe the bug**
I would like to use the Reolink plugin to use my RLC-423 PTZ camera. I can add it with ONVIF plugin, while it does not work with the Reolink plugin : I get a **Request failed with status code 404 host:@scrypted/reolink engine.io-client:api**

**To Reproduce**
Simply add a new camera from the Reolink plugin.

**Screenshots**
<img width="645" alt="Capture d’écran 2023-11-18 à 08 17 21" src="https://github.com/koush/scrypted/assets/13417885/1c8893cf-4c70-452c-bdd4-136d6ba77045">

**Setup:**
 - OS: scryted is installed on a Debian 12 VM on proxmox
 - Accessed from Arc browser, or Firefox
 - Version: 0.57.0

**Console message:**
[reolink.txt](https://github.com/koush/scrypted/files/13399388/reolink.txt)

**Explications:**
As indicated in the console message, the plugin is trying the reach the following address for getting snapshot:
```
http://IP_ADDRESS/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=SOME_RANDOM_VALUE&user=myuser&password=mypassword
```
I can confirm this address does not work for some reolink cameras (404 error from any browser on my RLC-423 camera); this is surely a firmware bug I already spotted in [a former homeassistant Reolink integration bug report](https://github.com/fwestenberg/reolink_dev/issues/189)

The solution is simple: the width and height parameters must be added to the request, e.g. 
```
http://IP_ADDRESS/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=SOME_RANDOM_VALUE&user=myuser&password=mypassword&width=640&height=480
```
The problem is all width/height values do not seem supported, see again the previous bug report in homeassistant Reolink integration.

**Comment by koush** [comment]
I suggest using the Snapshot plugin's snapshot url for this. It will override attempting to use the reolink plugin snapshot. Trying to tackle this may result in other cameras breaking due to unknown width/height requirements.

**Comment by sylarevan** [comment]
Sorry, but I can not add the camera at all with the Reolink plugin, so I will not be able to change any Snapshot parameters in the camera settings. Or maybe I'm not understanding the solution?

**Comment by koush** [comment]
I'm fairly sure you can skip validation?

**Comment by sylarevan** [comment]
I have just tested when selecting "Skip validation" when adding the camera. I still get "Request failed with status code 404 host:@scrypted/reolink engine.io-client:api". In the console I still have:

```
Error adding Reolink camera Error: Request failed with status code 404
    at createError (/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    url: 'http://192.168.30.8/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=1700412328209&user=myuser&password=mypassword',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
...
```

**Comment by koush** [comment]
yeah use the snapshot url now.

**Comment by sylarevan** [comment]
Sorry, but what do you mean by "use the snapshot url now"? The camera is not added and I can not access any of its parameters. 
Sorry if this is obvious, I really do not understand how to add the camera.

**Comment by koush** [comment]
are you saying you can't add the camera with skip validation selected?

**Comment by sylarevan** [comment]
Exactly. I'm stuck on the "Add New" panel from the Reolink plugin, with the red message as shown on the screenshot. I can't go further and the camera is not added at all.

**Comment by koush** [comment]
k fixed

**Comment by sylarevan** [comment]
After updating the plugin I have been able to add my camera 👍
I still have to skip validation (otherwise I get the 404 error) ; strangely snapshot image is shown just after ? (with an odd delay)  😕 
Anyway, after overriding the snapshot URL, everything seems fine.

Thank you very much!

**Comment by ColdeZhang** [comment]
Same problem, until when I am trying to add camera to Homeassistant it say that "password should not contain #".
And I did that so, I think that might be the real problem.
