### ISSUE TITLE
UniFi Cameras Fail to Load Stream

### ISSUE THREAD

**Issue by francisschmaltz** [koush/scrypted#12]
UniFi Cameras in HomeKit fail to stream video but do record to HomeKit Secure Video for playback

```
    Last message repeated 1 times
[h264 @ 0x7fc67580c800] decode_slice_header error
[h264 @ 0x7fc67580c800] no frame!
[h264 @ 0x7fc67580c800] non-existing PPS 0 referenced

    Last message repeated 1 times
[h264 @ 0x7fc67580c800] decode_slice_header error
[h264 @ 0x7fc67580c800] no frame!

Input #0, mpegts, from 'tcp://127.0.0.1:23900':
  Duration: N/A, start: 238.642544, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : 
74ACB9013710_0
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn, 48 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, mono, fltp, 64 kb/s

Output #0, rtp, to 'srtp://10.0.0.200:56319?rtcpport=56319&pkt_size=564':
  Metadata:
    encoder         : Lavf58.45.100

video/audio detected, discarding further input
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
t=0 0
a=tool:libavformat 58.45.100
m=video 56319 RTP/AVP 99
c=IN IP4 10.0.0.200
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1; sprop-parameter-sets=`sanitized`; profile-level-id=4D4033
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:`sanitized`
m=audio 61438 RTP/AVP 110
c=IN IP4 10.0.0.200
b=AS:24
a=rtpmap:110 MPEG4-GENERIC/24000/1
a=fmtp:110 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=F8EC2126A000
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:`sanitized`


streaming request { sessionID: '`sanitized`', type: 'stop' }

```

**Comment by koush** [comment]
I've seen this issue on hosts with multiple interfaces. You can use the address override option in homekit to specify the RTP endpoint. Feel free to hop on discord to debug this with me.

**Comment by francisschmaltz** [comment]
Setting an address IP for the HomeKit Plugin resolved the issue. Thanks!

**Comment by dsargent3220** [comment]
Sorry to reopen this but I'm a bit confused about where I set this.  Do you mean the Homekit plugin in Scrypted?  If so, the only thing that looks like an IP address is under the "Network" tab --> "Bridge Address"  
And I'm assuming this is for the host that is running the Unifi Protect cameras, in which case I don't understand why I need to enter that in the Homekit config when that IP is entered in the Unifi plugin.  
I'm running Scrypted under docker on a Synology NAS with four 1 gig ports, two of which are plugged in.

**Comment by dsargent3220** [comment]
Nevermind, found it in another post
For those looking for this, set the "Bridge Address" under the Network tab of the Homekit plugin in Scrypted to the IP of the host that is running Scrypted, this is for when that host has more than one IP / network interface.  This fixed it for me.
Might want to add to instructions . . .
