### ISSUE TITLE
Custom SSL Certificate

### ISSUE THREAD

**Issue by thecreativeone91** [koush/scrypted#1206]
Currently the [Custom SSL](https://github.com/koush/scrypted/wiki/Custom-SSL-Certificate) supports putting the PEM contents directly in the json file, can we get it updated to support files like many node.js deployments. Similar to below, or is there another way of doing this that isn't documented that currently would work?

```
var fs = require('fs');

{
 
    "key": fs.readFileSync("/server/volume/privkey1.pem'"),
    "cert": fs.readFileSync("/server/volume/fullchain1.pem"),

}
```

**Comment by koush** [comment]
Sure, can submit a pull request. Should be a matter of changing the fs.readFileSync that reads the env var to a require instead.

**Comment by koush** [comment]
Probably needs to be:
```js
var fs = require('fs');

module.exports = {
 
    "key": fs.readFileSync("/server/volume/privkey1.pem'"),
    "cert": fs.readFileSync("/server/volume/fullchain1.pem"),

}
```

**Comment by koush** [comment]
not a high priority unless someone wants to submit a pull request

**Comment by TransRapid** [comment]
I see this was marked completed, but not sure how it was implemented. Is there a way to easily modify this port install, or does it need to be added as an environment variable during install? Don't see any current documentation.

**Comment by pashdown** [comment]
How would one apply this to the macOS app?

**Comment by koush** [comment]
> How would one apply this to the macOS app?

use a dedicated ssl terminator like cloudflare or nginx proxy manager or caddy. I dont recommend doing this in the app.
