### ISSUE TITLE
Unifi Protect Setup

### ISSUE THREAD

**Issue by narensankar0529** [koush/scrypted#1209]
**Describe the bug**
I had Unifi Protect working and connected via HomeKit. My protect application is running on a cloudkey gen2 with a local administrator account. But HomeKit stopped updating the cameras and I couldn't get scrypted to update the camera view as well. So I deleted the plugins and reinstalled and now the unifi protect plugin doesn't even connect and login anymore. I get the follow errors in the console -

g in 10 seconds: refresh failed
API access error: 429 - Too Many Requests
Event Listener reconnecting in 10 seconds: refresh failed

**To Reproduce**
Install unifi-protect plugin and setup IP address and username and password.

No cameras detected and get the following log - 

server version: 0.68.0
plugin version: @scrypted/unifi-protect 0.0.141
########################
12/3/2023, 9:34:02 PM
########################
node modules /root/.scrypted/volume/plugins/@scrypted/unifi-protect/node18-linux-x64
plugin loaded
API access error: 429 - Too Many Requests
Event Listener reconnecting in 10 seconds: refresh failed
API access error: 429 - Too Many Requests
Event Listener reconnecting in 10 seconds: refresh failed

**Comment by koush** [comment]
429 - Too Many Requests

try rebooting unifi

**Comment by imTHAI** [comment]
@koush @narensankar0529 Same here. I just installed and got this error. It still currently works with Homebridge ( for which Im trying alternatives) and it still works with Home Assistant (which I tried just before Scrypted).

Even so, I rebooted my unifi UDM but it does not change anything.

**Comment by OktaMen** [comment]
Yes. Same here. This is happening since a month or so.

**Comment by Jens-Wymeersch** [comment]
I've just started with scrypted and got the same problem. Not sure what to do ?

**Comment by OktaMen** [comment]
I have created a new user in the Unifi console and restricted it to local network traffic.
So far I haven't had any problems for 4 days.

**Comment by Jens-Wymeersch** [comment]
After setting up a new user a few times, it started to work
