### ISSUE TITLE
Google Device Access - Stops Working After 7 to 10 days

### ISSUE THREAD

**Issue by PhilTheNewbie** [koush/scrypted#1215]
Dear sirs,
Newbie here. None technical. Grateful for any advice.
I've successfully installed Scrypted on a Synology NAS, installed Google Device Access plugin and followed the detailed instructions. I have successfully added a Google Doorbell. However, the plug in stops working after 7 to 10 days. I no longer see my door camera view in the plugin. 
This has happened twice. I am unable to get the plugin to work beyond the 7 to 10 days.
The console feedback states "ERROR: The provided authorisation grant or refresh token is invalid"
I cannot see any reference to a "refresh token" in the detailed instructions.
Thank you for any help you can provide.

**Comment by koush** [comment]
set your oauth to production
