### ISSUE TITLE
Recover camera password from scrypted 

### ISSUE THREAD

**Issue by switey** [koush/scrypted#1216]
Hi! 
first of all - Scrypted is working great (or was until my gf decided to reset home router). 
Now I find myself in a bit of a pickle, I have forgotten my IP camera password which I know I had to provide in RTSP camera plugin settings. 
I bet that it’s possible to retrieve it from config files but I don’t really know where to look. Really looking forward to some clues on the subject. Otherwise I’m left with a useless camera. 
cheers!

**Comment by bjia56** [comment]
Go to the camera page in the scrypted management webpage and press the Storage icon under the camera picture, a few boxes should appear down at the bottom which contain the configs you previously put in.
