### ISSUE TITLE
Camera offline notification

### ISSUE THREAD

**Issue by SwizzVPN** [koush/scrypted#1221]
**Describe the bug**
I have a Tapo Cam integrated using ONVIF and enabled camera offline notification in HKSV. If I drop my internet connection, I receive the camera offline notification, as expected. If I unplug my camera, I don't receive that notification. So if someone outside cuts the power to the camera I won't get informed about it.

**To Reproduce**
1. Enable camera offline notification in HKSV
2. Unplug power to camera
3. Check notification center for no notification

**Expected behavior**
I expect to get a camera offline notification if the connection to the camera drops, after a timeout of 1-2 minutes.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 17.2
 - Browser: Safari

**Comment by koush** [comment]
This would require taking scrypted offline to mirror the accessory mode camera state for HomeKit. This was highly error prone when tested.
