### ISSUE TITLE
common/src/ffmpeg-hardware-acceleration.ts doesn't support freebsd

### ISSUE THREAD

**Issue by ascl00** [koush/scrypted#1222]
I'm not sure how good the defaults are, but I think ffmpeg needs arguments to make use of quicksync. Something like this:
```
diff --git a/common/src/ffmpeg-hardware-acceleration.ts b/common/src/ffmpeg-hardware-acceleration.ts
index 4b674f20..a3463830 100644
--- a/common/src/ffmpeg-hardware-acceleration.ts
+++ b/common/src/ffmpeg-hardware-acceleration.ts
@@ -77,6 +77,9 @@ export function getH264DecoderArgs(): CodecArgs {
     else if (os.platform() === 'linux') {
         ret[V4L2] = ['-c:v', 'h264_v4l2m2m'];
     }
+    else if (os.platform() === 'freebsd') {
+        ret['vaapi'] = ['-hwaccel', 'vaapi', '-hwaccel_device', '/dev/dri/renderD128' ];
+    }
     else if (os.platform() === 'win32') {
         ret['Intel QuickSync'] = ['-c:v', 'h264_qsv'];
     }
@@ -114,6 +117,9 @@ export function getH264EncoderArgs() {
         encoders['VAAPI'] = 'h264_vaapi';
         encoders['Nvidia'] = 'h264_nvenc';
     }
+    else if (os.platform() === 'freebsd') {
+        encoders['VAAPI'] = 'h264_vaapi';
+    }

     const encoderArgs: CodecArgs = {};
     for (const [name, encoder] of Object.entries(encoders)) {
```

But this will break people that don't have access to Intel GPU's quick sync, so I think I need to add something to detect.

I'll spend some more time on this and hopefully post a PR. But any suggestions on how best to detect support would be appreciated. Maybe parse ffmpeg -hide_banner -encoders, but that doesn't help with decoding.

**Comment by koush** [comment]
I'm not overly concerned about hw accelerated defaults, as transcoding is basically never used. The defaults should be safe. User can fiddle with them in the Transcoding device in rebroadcast plugin.

**Comment by ascl00** [comment]
Okay fair enough. I can always use the per stream settings for decoding anyway. Thanks!
