### ISSUE TITLE
Amcrest not forwarding IVS motion events to HKSV

### ISSUE THREAD

**Issue by sean-scott-lr** [koush/scrypted#1225]
When attempting to configure Amcrest AI cameras to only trigger on IVS events, the result is that the Amcrest camera records the event, but Scrypted does not forward to HKSV.

**To Reproduce**
1. Go to Amcrest camera detection settings Event->Motion Detection
2. Make sure the "Enable" checkbox is selected
3. Make sure the "Record" checkbox is not selected
4. Go to "Smart Plan" and make sure IVS is selected
5. Go to IVS and create an IVS rule that you can use to test with
6. Enable "Appears and Cross"
7. Enable Object Filter, and Human
8. Enable "Record"
9. Walk into the configured IVS zone
10. Go to "Playback" and note that the camera recorded you in the intrusion zone

**Expected behavior**
I expect that this video will be forwarded to HKSV and the human will also be detected.
However, Homekit does not have any recording of this event

**Additional context**
When just enabling "motion" and enabling "record" for all motion... the video is sent to HKSV.  However, snow triggers constant motion and the cameras fill up with recordings. ( And I presume all cameras send the snow falling videos to HKSV, but I have no evidence of this ).

**Comment by sean-scott-lr** [comment]
Here is what is generated in the debug console:

`debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 106

Code=NTPAdjustTime;action=Pulse;index=0;data={
   "Address" : "",
   "Before" : "",
   "result" : false
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 1273

Code=CrossRegionDetection;action=Start;index=0;data={
   "Action" : "Appear",
   "Class" : "Normal",
   "CountInGroup" : 1,
   "DetectRegion" : [
      [ 619, 6639 ],
      [ 2057, 7707 ],
      [ 6899, 7772 ],
      [ 7317, 3175 ],
      [ 5042, 973 ],
      [ 2403, 1135 ],
      [ 218, 3078 ],
      [ 237, 5991 ]
   ],
   "EventID" : 10537,
   "GroupID" : 478,
   "Name" : "IVS-1",
   "Object" : {
      "Action" : "Appear",
      "BelongID" : 0,
      "BoundingBox" : [ 712, 2368, 1016, 3712 ],
      "Center" : [ 864, 3040 ],
      "Confidence" : 0,
      "FusionInfo" : {
         "BelongID" : 0,
         "CartPosX" : 0.0,
         "CartPosY" : 0.0,
         "GpsPosValid" : 0,
         "GpsPostion" : {
            "Latitude" : 0.0,
            "Longitude" : 0.0
         },
         "ObjectSource" : 0,
         "RadarCoorXyValid" : 0,
         "Speed" : 0.0,
         "SpeedValid" : 0,
         "SpeedX" : 0.0,
         "SpeedY" : 0.0
      },
      "LowerBodyColor" : [ 0, 0, 0, 0 ],
      "MainColor" : [ 0, 0, 0, 0 ],
      "ObjectID" : 4028,
      "ObjectType" : "Human",
      "RelativeID" : 0,
      "Speed" : 0,
      "humanTripLineDirection" : 0
   },
   "PTS" : 44053828260.0,
   "RuleID" : 1,
   "Track" : [],
   "UTC" : 1702718085,
   "UTCMS" : 547
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 70

Code=IntelliFrame;action=Pulse;index=0;data={
   "Action" : "Start"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 214

Code=SmartMotionHuman;action=Start;index=0;data={
   "RegionName" : [ "Area1" ],
   "WindowId" : [ 0 ],
   "object" : [
      {
         "HumamID" : 4028,
         "Rect" : [ 832, 2344, 1128, 3696 ]
      }
   ]
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 77

Code=VideoMotion;action=Start;index=0;data={
   "SmartMotionEnable" : true
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 164

Code=NewFile;action=Pulse;index=0;data={
   "File" : "\/mnt\/sd\/2023-12-16\/001\/jpg\/09\/14.46[M][0@0][0].jpg",
   "Size" : 2468480,
   "StoragePoint" : "NULL"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 164

Code=NewFile;action=Pulse;index=0;data={
   "File" : "\/mnt\/sd\/2023-12-16\/001\/jpg\/09\/14.47[M][0@0][0].jpg",
   "Size" : 2468076,
   "StoragePoint" : "NULL"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 164

Code=NewFile;action=Pulse;index=0;data={
   "File" : "\/mnt\/sd\/2023-12-16\/001\/jpg\/09\/14.48[M][0@0][0].jpg",
   "Size" : 2472285,
   "StoragePoint" : "NULL"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 1272

Code=CrossRegionDetection;action=Stop;index=0;data={
   "Action" : "Appear",
   "Class" : "Normal",
   "CountInGroup" : 1,
   "DetectRegion" : [
      [ 619, 6639 ],
      [ 2057, 7707 ],
      [ 6899, 7772 ],
      [ 7317, 3175 ],
      [ 5042, 973 ],
      [ 2403, 1135 ],
      [ 218, 3078 ],
      [ 237, 5991 ]
   ],
   "EventID" : 10537,
   "GroupID" : 478,
   "Name" : "IVS-1",
   "Object" : {
      "Action" : "Appear",
      "BelongID" : 0,
      "BoundingBox" : [ 712, 2368, 1016, 3712 ],
      "Center" : [ 864, 3040 ],
      "Confidence" : 0,
      "FusionInfo" : {
         "BelongID" : 0,
         "CartPosX" : 0.0,
         "CartPosY" : 0.0,
         "GpsPosValid" : 0,
         "GpsPostion" : {
            "Latitude" : 0.0,
            "Longitude" : 0.0
         },
         "ObjectSource" : 0,
         "RadarCoorXyValid" : 0,
         "Speed" : 0.0,
         "SpeedValid" : 0,
         "SpeedX" : 0.0,
         "SpeedY" : 0.0
      },
      "LowerBodyColor" : [ 0, 0, 0, 0 ],
      "MainColor" : [ 0, 0, 0, 0 ],
      "ObjectID" : 4028,
      "ObjectType" : "Human",
      "RelativeID" : 0,
      "Speed" : 0,
      "humanTripLineDirection" : 0
   },
   "PTS" : 44053828260.0,
   "RuleID" : 1,
   "Track" : [],
   "UTC" : 1702718085,
   "UTCMS" : 547
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 69

Code=IntelliFrame;action=Pulse;index=0;data={
   "Action" : "Stop"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 1295

Code=CrossRegionDetection;action=Start;index=0;data={
   "Action" : "Cross",
   "Class" : "Normal",
   "CountInGroup" : 1,
   "DetectRegion" : [
      [ 619, 6639 ],
      [ 2057, 7707 ],
      [ 6899, 7772 ],
      [ 7317, 3175 ],
      [ 5042, 973 ],
      [ 2403, 1135 ],
      [ 218, 3078 ],
      [ 237, 5991 ]
   ],
   "Direction" : "Leave",
   "EventID" : 10539,
   "GroupID" : 480,
   "Name" : "IVS-1",
   "Object" : {
      "Action" : "Appear",
      "BelongID" : 0,
      "BoundingBox" : [ 0, 2904, 224, 4136 ],
      "Center" : [ 112, 3520 ],
      "Confidence" : 0,
      "FusionInfo" : {
         "BelongID" : 0,
         "CartPosX" : 0.0,
         "CartPosY" : 0.0,
         "GpsPosValid" : 0,
         "GpsPostion" : {
            "Latitude" : 0.0,
            "Longitude" : 0.0
         },
         "ObjectSource" : 0,
         "RadarCoorXyValid" : 0,
         "Speed" : 0.0,
         "SpeedValid" : 0,
         "SpeedX" : 0.0,
         "SpeedY" : 0.0
      },
      "LowerBodyColor" : [ 0, 0, 0, 0 ],
      "MainColor" : [ 0, 0, 0, 0 ],
      "ObjectID" : 4028,
      "ObjectType" : "Human",
      "RelativeID" : 0,
      "Speed" : 0,
      "humanTripLineDirection" : 0
   },
   "PTS" : 44053834110.0,
   "RuleID" : 1,
   "Track" : [],
   "UTC" : 1702718091,
   "UTCMS" : 395
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 70

Code=IntelliFrame;action=Pulse;index=0;data={
   "Action" : "Start"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 164

Code=NewFile;action=Pulse;index=0;data={
   "File" : "\/mnt\/sd\/2023-12-16\/001\/jpg\/09\/14.52[M][0@0][0].jpg",
   "Size" : 2483569,
   "StoragePoint" : "NULL"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 1294

Code=CrossRegionDetection;action=Stop;index=0;data={
   "Action" : "Cross",
   "Class" : "Normal",
   "CountInGroup" : 1,
   "DetectRegion" : [
      [ 619, 6639 ],
      [ 2057, 7707 ],
      [ 6899, 7772 ],
      [ 7317, 3175 ],
      [ 5042, 973 ],
      [ 2403, 1135 ],
      [ 218, 3078 ],
      [ 237, 5991 ]
   ],
   "Direction" : "Leave",
   "EventID" : 10539,
   "GroupID" : 480,
   "Name" : "IVS-1",
   "Object" : {
      "Action" : "Appear",
      "BelongID" : 0,
      "BoundingBox" : [ 0, 2904, 224, 4136 ],
      "Center" : [ 112, 3520 ],
      "Confidence" : 0,
      "FusionInfo" : {
         "BelongID" : 0,
         "CartPosX" : 0.0,
         "CartPosY" : 0.0,
         "GpsPosValid" : 0,
         "GpsPostion" : {
            "Latitude" : 0.0,
            "Longitude" : 0.0
         },
         "ObjectSource" : 0,
         "RadarCoorXyValid" : 0,
         "Speed" : 0.0,
         "SpeedValid" : 0,
         "SpeedX" : 0.0,
         "SpeedY" : 0.0
      },
      "LowerBodyColor" : [ 0, 0, 0, 0 ],
      "MainColor" : [ 0, 0, 0, 0 ],
      "ObjectID" : 4028,
      "ObjectType" : "Human",
      "RelativeID" : 0,
      "Speed" : 0,
      "humanTripLineDirection" : 0
   },
   "PTS" : 44053834110.0,
   "RuleID" : 1,
   "Track" : [],
   "UTC" : 1702718091,
   "UTCMS" : 395
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 69

Code=IntelliFrame;action=Pulse;index=0;data={
   "Action" : "Stop"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 177

Code=NewFile;action=Pulse;index=0;data={
   "File" : "\/mnt\/sd\/2023-12-16\/001\/dav\/09\/09.14.40-09.15.02[M][0@0][0].mp4",
   "Size" : 18052039,
   "StoragePoint" : "NULL"
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 210

Code=SmartMotionHuman;action=Stop;index=0;data={
   "RegionName" : [ "Area1" ],
   "WindowId" : [ 0 ],
   "object" : [
      {
         "HumamID" : 4028,
         "Rect" : [ 0, 3048, 144, 4136 ]
      }
   ]
}


debug event:
 --myboundary
Content-Type: text/plain
Content-Length: 76

Code=VideoMotion;action=Stop;index=0;data={
   "SmartMotionEnable" : true
}


`

**Comment by koush** [comment]
I see VideoMotion started which is all HKSV needs. The motion sensor is working properly. HKSV is probably receiving the video and deciding it is not worth. it Homekit doesn't use any camera smart motion events.
