### ISSUE TITLE
Object detection script error on mac

### ISSUE THREAD

**Issue by medomatto** [koush/scrypted#1227]
**Describe the bug**
I am trying to get a image saved on the drive of the detected object. Using the script template given, it seems that on Mac there is an error thrown out because it does not find a module.
I am using the last Mac version of Scrypted, 0.68.0, with paid NVR account.

**To Reproduce**
- Go to Script, create a new script with this code (give your username and pass) from this repository:
- packages/client/examples/detection.ts
- The error thrown in the console is:

> 
darwin x64 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
server version: 0.68.0
plugin version: @scrypted/core 0.1.150
Error: Cannot find module '/Users/matthias/.scrypted/volume/plugins/@scrypted/core/node18-darwin-x64/dist/packages/client/src'
Require stack:
- /Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /Applications/Scrypted.app/Contents/Resources/app/app_dist/main.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at params.require (/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/src/plugin/plugin-remote-worker.ts:251:28)
    at asyncFunction (script.js:8:15)
    at apiProxy (/common/src/eval/scrypted-eval.ts:102:29)
    at h.eval (/src/script.ts:105:39)
    at RpcPeer.handleMessageInternal (/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/src/rpc.ts:759:37) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/Applications/Scrypted.app/Contents/Resources/app/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/Applications/Scrypted.app/Contents/Resources/app/app_dist/main.js'
  ]
}

> 

**Expected behavior**
I suppose there would be no error and it finds the module in order to export the object recognition images.

**Desktop **
 - OS 12.5.1 Monterey
 - scrypted version: 0.68.0

**Comment by koush** [comment]
The code you're using there is intended to be used from outside of Scrypted *from other applications*. It's part of the SDK.

If you want to get detection images and save them (or rather, send them somewhere), this is certainly possible. That's how HA notifications work, for example. There are other plugins that make this easier too (slack, pushover). You should join Discord so I can get a better understanding of your use case and provide a proper solution.
