### ISSUE TITLE
Link in documentation does not work

### ISSUE THREAD

**Issue by EdwardMoyse** [koush/scrypted#1229]
**Describe the bug**
In this documentation:
https://github.com/koush/scrypted/blob/main/plugins/homekit/README.md

The link in the following text does not work

> You may have multiple network interfaces, such as wired and wireless, and HomeKit is preferring the wireless interface. Use the [Scrypted Server Address setting](https://github.com/koush/scrypted/blob/main/endpoint/@scrypted/core/public/#/component/settings), and set it to your wired IP address manually."

I get:
> 404: The main branch of scrypted does not contain the path endpoint/@scrypted/core/public.

**Comment by koush** [comment]
that link will work when viewing the readme from the homekit plugin.
