### ISSUE TITLE
Feature request: Switch to turn off notifications

### ISSUE THREAD

**Issue by onkelfarmor** [koush/scrypted#123]
Hi, an idea from another project: A home / not home switch to tell, if Scrypted should look for motion on the cameras. As for now you can only rely on Homekits home / not home, which doesn't work, when the children leave there phones at home. Instead I want to turn on HomeKit recordings all the time and then rely on the switch from Scrypted - which I can change myself In the Home app and make automation to turn on an off when last person leaves and first person gets home.

**Comment by pleaseemail** [comment]
which project does this?

**Comment by onkelfarmor** [comment]
Camera UI in Homebridge

**Comment by pleaseemail** [comment]
Their notifications do not appear to use native HomeKit notifications (and it doesn't sound like you want to use native HK notifications).  They use third parties such as Telegram, SMTP, MQTT, etc. Is that correct?  If that's the case, you can create a dummy switch and Scrypted has plugins for third party notifications such as MQTT, SMTP, and Twilio.  That is, if I understand correctly.  

As an aside, Native HomeKit Recording and Notifications are independent of each other.  You can keep your recordings 'on all motions detected' (HomeKit doesn't record/save 24x7 video) while having zero notifications. Or you can have all the notifications you want with zero recordings.

**Comment by onkelfarmor** [comment]
You misunderstand. In Camera ui I have at switch, and when I turn that off, Camera ui don’t send snapshots to HomeKit. 

Use case: I want a switch to turn notifications on and off. In HomeKit I set the camera to record and notifications on each movement and then I can manual control it. 

Without I can only rely on HomeKit home or not home. My children don’t always bring their phones with them, so this it not good enough.

**Comment by koush** [comment]
You can use a dummy switch and an automation with conditions linked to the actual motion sensor.

**Comment by onkelfarmor** [comment]
Please help how, which action and so …

**Comment by pleaseemail** [comment]
Hi - If you have not already, I suggest joining the active community on [Scrypted Discord](https://discord.com/invite/DcFzmBHYGq), searching and asking there.  In particular, the #dummy-switch plugin channel.  Hope that helps!

**Comment by cheme75** [comment]
maybe I misunderstand the need, but can't you just flip the notifications on/off in the home app?

**Comment by koush** [comment]
There is no way to control homekit notifications for activity (other than homekit's home/away status). Furthermore, disabling the motion which triggers the notifications would also disable recording.
