### ISSUE TITLE
How can I get rid of old recordings?

### ISSUE THREAD

**Issue by wbarber69** [koush/scrypted#1232]
I’ve enjoyed scrypted so far, but I’m using it as an add-on to HomeAssistant.  And while it performs okay, I have found that it gets full of recordings pretty quick.  And there is no way to delete them.  I’ve tried deleting the cameras themselves about their old recordings still haunt the drive.  There is no way to delete files from within HAOS itself and there is absolutely no way to delete files in scrypted.  I’ve tried hitting the little red trash can and the acknowledgment afterwards but the files persist.  And now I’m going to have to reinstall my entire HAOS build because I have no way to quell the bloated ssd.

**Comment by koush** [comment]
what recordings are you talking about? NVR?

**Comment by koush** [comment]
if you mean NVR, its likely your file system has a recycle bin or something similar. you'll need to empty that.
recordings are stored in /config/data/scrypted-vr or something? I can't recall where HA puts the add-on storage.

**Comment by wbarber69** [comment]
Which doesn’t help.  HAOS has no way of low level hard drive access.  And the scrypted server isn’t deleting its own files so obviously the add-on isn’t functional for everyday HA use.  How could assume that there is “a recycle bin or something…”.  We aren’t talking about windows here.

Sent from my iPhone

On Dec 25, 2023, at 10:28 AM, Koushik Dutta ***@***.***> wrote:

﻿

if you mean NVR, its likely your file system has a recycle bin or something similar. you'll need to empty that.
recordings are stored in /config/data/scrypted-vr or something? I can't recall where HA puts the add-on storage.

**Comment by koush** [comment]
There are file systems that have recycle bins. This is common on Sinology NAS which run Linux.

This could also be due to HA backing up the recordings.

**Comment by wbarber69** [comment]
Well it’s not common for HAOS.  Which is how about 80% of homeassistant users run HA.  If I were running pios or Debian or Ubuntu that may be the case, but there is absolutely no way to delete anything that isn’t in the configuration folder.
Sent from my iPhone

On Dec 26, 2023, at 12:37 AM, Koushik Dutta ***@***.***> wrote:

﻿

There are file systems that have recycle bins. This is common on Sinology NAS which run Linux.

This could also be due to HA backing up the recordings.

**Comment by meven3000** [comment]
I also seem to have issues with removing old recordings from NVR, single delete or full delete from camera in Scrpyted web console.

using VMWare ubuntu + docker container

Standard docker container install fails to delete video via web GUI.
Change to VM local disk redirection VM dick '/recordings', docker link '/nvr'  also fails to delete.

The only things that do seem to work are:

Deleting directly via VM console, if the files where in the docker container then the associated docker commands would be needed e.g. 'docker exec -it scripted rm -r /nvr'

Using the Scrpyted web console terminal function, 'rm -r /nvr/*' does work without issues, so this appears to be something with the GUI.

Over they break I left the 'default' video recycle and it failed to delete anything, eventually causing the partition to become read only. Maybe something with the API/Web command

**Comment by wbarber69** [comment]
Just use the recycle bin…

Sent from my iPhone

On Dec 28, 2023, at 5:20 PM, meven3000 ***@***.***> wrote:

﻿

I also seem to have issues with removing old recordings from NVR, single delete or full delete from camera in Scrpyted web console.

using VMWare ubuntu + docker container

Standard docker container install fails to delete video via web GUI.
Change to VM local disk redirection VM dick '/recordings', docker link '/nvr' also fails to delete.

The only things that do seem to work are:

Deleting directly via VM console, if the files where in the docker container then the associated docker commands would be needed e.g. 'docker exec -it scripted rm -r /nvr'

Using the Scrpyted web console terminal function, 'rm -r /nvr/*' does work without issues, so this appears to be something with the GUI.

Over they break I left the 'default' video recycle and it failed to delete anything, eventually causing the partition to become read only. Maybe something with the API/Web command

**Comment by meven3000** [comment]
recycle bin ? this is just raw storage on the same system. (this is ubuntu server)

**Comment by wbarber69** [comment]
That’s all I ever got as an answer.

So it must be the only solution.
Haven’t you seen that this issue is closed.  Remember all systems have a recycle bin.  Solution over.

Sent from my iPhone

On Dec 28, 2023, at 6:28 PM, meven3000 ***@***.***> wrote:

﻿

recycle bin ? this is just raw storage on the same system. (this is ubuntu server)

**Comment by koush** [comment]
please provide an nvr plugin log.

as mentioned, this is almost certainly a file system permission/reporting, recycling, or ha addon backup issue. none of these are a bug in the nvr retention mode. the nvr will try to delete at 90% disk utilization, or delete anything older than the requested retention period.

people report this "bug" occasionally, and it's never an actual issue with the nvr. it's always something specific to their setup. you'll need to investigate why and figure out why NVR is unable to reclaim the space.

**Comment by koush** [comment]
> Standard docker container install fails to delete video via web GUI.

Deletion via management console GUI isn't in yet, but you can do it via the NVR GUI. Select a time range:

<img width="480" alt="image" src="https://github.com/koush/scrypted/assets/73924/546b5060-76e1-43ec-aac6-be67f09e0b13">

**Comment by wbarber69** [comment]
There is no specific reason my install would be any different than any one else using HAOS.  There is nothing I can do to change the setup of anything related to my base install.  I am running pure HAOS on pi4 as intended, with the add-on version of scrypted.  Latest jammy.  And it’s been a problem for every version that has been installed/updated to date.  If we don’t have a functional way to actually delete files, then I’m sorry I will have to cancel my subscription.  I’ve already had to blast out my entire haos install to rid myself of these undeletable recordings.  I may try to run scrypted by itself once my ssd arrives for my pi5 and I can get everything moved over.  Until then I’ll have to stop using scrypted as it’s virtually unusable at this point.


Sent from my iPhone

On Dec 28, 2023, at 9:41 PM, Koushik Dutta ***@***.***> wrote:

﻿

please provide an nvr plugin log.

as mentioned, this is almost certainly a file system permission/reporting, recycling, or ha addon backup issue. none of these are a bug in the nvr retention mode. the nvr will try to delete at 90% disk utilization, or delete anything older than the requested retention period.

people report this "bug" occasionally, and it's never an actual issue with the nvr. it's always something specific to their setup. you'll need to investigate why and figure out why NVR is unable to reclaim the space.

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/1239
