### ISSUE TITLE
v0.79 "Black and White" Snapshots in Homekit

### ISSUE THREAD

**Issue by AndrStnz** [koush/scrypted#1242]
Since the Upgrade to v0.79 the Snapshots in Homekit are very high contrast and black and white.

Streams are working fine. Only the Snapshots are affected.

See: https://www.reddit.com/r/HomeKit/comments/18xtt2w/weird_black_white_camera_display/

Running as HA Addon. On Proxmox.

Maybe related to:
https://github.com/lovell/sharp/issues/3893

Console of Snapshot Plugin is spammed with:
WARNING: CPU supports 0x6000000000004000, software requires 0x4000000000005000

**Comment by koush** [comment]
@AndrStnz is correct. no plans to fix this as I don’t want to chase down shooter for virtual cpus in vips.
