### ISSUE TITLE
Git Submodule for ONVIF breaking the HA add-on process

### ISSUE THREAD

**Issue by tpagden** [koush/scrypted#1251]
**Describe the bug**
It looks like you may have introduced a bug with adding this as an HA plugin with the addition of the git submodule for onvif (specified with a ssh syntax vs. https git pull)

This is my first usage of the product, so I assume this is the problem, and it coincides with an update yesterday, however I may be off-base and would appreciate any assistance if that is the case.

**To Reproduce**
1. Go to HA add-ons
2. Click on repostories
3. Add the repository `https://github.com/koush/scrypted`

**Expected behavior**
The add-on is added

**Screenshots**
![image](https://github.com/koush/scrypted/assets/5873856/3e31f19c-bde1-4558-bc36-adcd4ec2f0ff)

**Desktop (please complete the following information):**
 - OS: HASS - latest
 - Browser [edge]

**Additional context**

**Comment by koush** [comment]
fixed https://github.com/koush/scrypted/commit/28c8b97c26e17a0590f5817057f7dc4d0507634b
