### ISSUE TITLE
Edge TPU Instructions Unclear

### ISSUE THREAD

**Issue by fabltd** [koush/scrypted#1254]
The documentation for adding an edge TPU to Proxmox appears to be unclear.

The docmentation does not mention if this is run on the Proxmox host or is it run inside the container.
One assumes its run on the proxmox host given the reference to the repositiory. 

The instruction then does not explain if any action is needed to get the TPU mounted into the container. Or does the contain come ready ?

**Comment by koush** [comment]
The install script is run on the host. The TPU script is also run on the host, and will manage everything needed to get the TPU into proxmox. Tested with PCI coral. USB probably won't work without additional fiddling (and is not recommended anyways).
