### ISSUE TITLE
scrypted/install/local /install-scrypted-proxmox.sh does not detect error status returned by pct command, causing misbehavior

### ISSUE THREAD

**Issue by jeffstearns** [koush/scrypted#1255]
**Describe the bug**
scrypted/install/local /install-scrypted-proxmox.sh (commit e7b6cb0) does not detect exit status returned by pct command.

**To Reproduce**
1. Note that line 39 of install-scrypted-proxmox.sh sets $? to the exit status of the pct command
2. Note that line 49 of install-scrypted-proxmox.sh tests the value of $?
3. Note that the value of $? has already been overwritten by lines 41-47 and is thus not usable as intended.

**Expected behavior**
install-scrypted-proxmox.sh detects the exit status of the pct command by saving $? for use when it is needed:

line 39: pct config $VMID; PCT_STATUS=$?
[...]
line 49: if [ "$PCT_STATUS" != "0" ]

**Comment by koush** [comment]
fixed
