### ISSUE TITLE
Live video won't display if main stream resolution is too high.

### ISSUE THREAD

**Issue by jeffstearns** [koush/scrypted#1257]
**Describe the bug**
Scrypted may not display live video when clicking on a camera snapshot.  This happens when the main stream resolution is set to certain values.

This contradicts the Scrypted documentation which recommends setting the resolution of the main stream as high as possible.  Some resolutions prevent Scrypted from displaying live video.

**To Reproduce**

1. Connect an Amcrest camera which offers resolution of 3840x2160.
2. Configure the camera in the usual way according to the Scrypted documentation.
3. Confirm that the Main Stream resolution is set to 3840x2160.
4. Open the Scrypted management console and navigate to the camera.
5. Note that an up-to-date snapshot is displayed.
6. Click on the snapshot to display live video.
7. Note that nothing happens.
8. Open the "Console" link to open the console pane.
9. Click on the garbage can icon to clear the console pane.
10. Click on the camera snapshot again to display live video.
11. Note that nothing happens.  Note that no new messages are displayed in the console pane.
12. Modify the camera configuration by reducing the resolution of the main stream.  In my case, I chose 3072x2048.
13. Note that Scrypted can now open a video pane and display live video.

**Expected behavior**
Clicking on the snapshot opens a live video pane.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6.  (But OS doesn't seem to be a factor here.)
 - Browser Chrome, Safari.  (But browser doesn't seem to be a factor here.)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 (But the device doesn't seem to be a factor; I tested with various devices.)
 - OS: iOS 16.7.2
 - Browser: Chrome, Safari.  (But the device doesn't seem to be a factor; I tested with various browsers.)

**Comment by koush** [comment]
You probably need to lower the bitrate to something more suitable for your network. You're likely getting packet loss.

**Comment by koush** [comment]
You may want to attach a camera log of the rebroadcast startup in case I'm misunderstanding something here.

**Comment by jeffstearns** [comment]
Thanks for your comments.

I'm completely new to Scrypted and still feeling my way around.  I had been focusing my attention on the Amcrest plugin; I never looked at the rebroadcast plugin.

After I reloaded the rebroadcast plugin, the bug disappeared.  Video now displays properly.  I can no longer reproduce the bug.  The live video pane now works properly regardless of the main stream resolution.

In my case, I'm confident that bit rate and packet loss were never an issue.  The camera and server are on a dedicated test net; video has always displayed perfectly in other apps like VLC, Amcrest Surveillance Pro, and within a browser.  The only problem was within Scrypted, and I'm no longer experiencing that bug.  If it returns, I will reopen this report with more information.

Thanks again for your interest and help.
