### ISSUE TITLE
Docker Latest (v0.83.0) ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by robbywraith** [koush/scrypted#1262]
**Describe the bug**
Latest: docker container errors and stops. Started happening right after v0.83.0 was released. Thinking watchtower updated and that's what broke it. Disabled watchtower and reverted to 18-jammy-full.s6-v0.81.0 and error is gone. Error below:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service setup: starting
SCRYPTED_DOCKER_AVAHI != true, won't manage dbus nor avahi-daemon
s6-rc: info: service setup successfully started
s6-rc: info: service dbus: starting
s6-rc: info: service dbus successfully started
s6-rc: info: service avahi: starting
SCRYPTED_DOCKER_AVAHI != true, not starting dbus-daemon
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service avahi successfully started
SCRYPTED_DOCKER_AVAHI != true, not starting avahi-daemon
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/server/node_modules/@scrypted/server/dist/http-interfaces.js:10
const mime = require('mime/lite');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /server/node_modules/mime/dist/src/index_lite.js from /server/node_modules/@scrypted/server/dist/http-interfaces.js not supported.
Instead change the require of index_lite.js in /server/node_modules/@scrypted/server/dist/http-interfaces.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/http-interfaces.js:10:14)
    at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/runtime.js:46:27)
    at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/scrypted-server-main.js:51:19)
    at start (/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js:52:23)
    at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
    at Object.<anonymous> (/server/node_modules/@scrypted/server/bin/scrypted-serve:4:1) {
  code: 'ERR_REQUIRE_ESM'
}

**To Reproduce**
Launch container which was installed via docker instructions. 

**Expected behavior**
Container works.

**Desktop (please complete the following information):**
- Scripted version v0.83.0 
- OS: ubuntu server 22.04
 - Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

**Comment by koush** [comment]
fixed already

**Comment by danklmn** [comment]
If anyone gets here and is still stuck (assuming Linux + docker compose) check that your docker-compose.yml points to the "new" `ghcr.io/koush/scrypted` image vs. the "old" `koush/scrypted`. For some reason I couldn't get this issue resolved until I updated the image string.

P.S.: Would appreciate it if someone could actually explain why switching the image string resolved the issue. The Docker Hub image `koush/scrypted` _seems_ to be updated to the latest bits from GitHub as well.

**Comment by koush** [comment]
ghcr and docker both have the same image. it's likely that you didn't pull the old image.

**Comment by koush** [comment]
There was an issue with docker hub not being updated with the new image. This was also resolved.
