### ISSUE TITLE
0.83.0 Release: CommonJS import causing endless crash / restart

### ISSUE THREAD

**Issue by devongermano** [koush/scrypted#1263]
Scrypted running using docker-compose w/ Watchtower. Latest 0.83.0 release was deployed automatically. Container endlessly loops like this forever. Latest Scrypted update presumeably contains a CommonJS import somewhere in lieu of the proper ESModule syntax.

### Logs:

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service setup: starting
> SCRYPTED_DOCKER_AVAHI != true, won't manage dbus nor avahi-daemon
> s6-rc: info: service setup successfully started
> s6-rc: info: service dbus: starting
> s6-rc: info: service dbus successfully started
> s6-rc: info: service avahi: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> SCRYPTED_DOCKER_AVAHI != true, not starting dbus-daemon
> s6-rc: info: service avahi successfully started
> SCRYPTED_DOCKER_AVAHI != true, not starting avahi-daemon
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> /server/node_modules/@scrypted/server/dist/http-interfaces.js:10
> const mime = require('mime/lite');
>              ^
> Error [ERR_REQUIRE_ESM]: require() of ES Module /server/node_modules/mime/dist/src/index_lite.js from /server/node_modules/@scrypted/server/dist/http-interfaces.js not supported.
> Instead change the require of index_lite.js in /server/node_modules/@scrypted/server/dist/http-interfaces.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/http-interfaces.js:10:14)
>     at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/runtime.js:46:27)
>     at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/scrypted-server-main.js:51:19)
>     at start (/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js:52:23)
>     at Object.<anonymous> (/server/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
>     at Object.<anonymous> (/server/node_modules/@scrypted/server/bin/scrypted-serve:4:1) {
>   code: 'ERR_REQUIRE_ESM'
> }
> Node.js v18.19.0
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service avahi: stopping
> s6-rc: info: service avahi successfully stopped
> s6-rc: info: service dbus: stopping
> s6-rc: info: service dbus successfully stopped
> s6-rc: info: service setup: stopping
> s6-rc: info: service setup successfully stopped
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Expected behavior**
Possibly revert container deployment using Watchtower on failed health check / timeout?

**Desktop:**
 - OS: Ubuntu 23.10
 - Browser: Chrome
 - 0.83.0

**Comment by koush** [comment]
already fixed. please dont open duplicates.
