### ISSUE TITLE
AppleTV 1 or 2 streams stop working randomly every day or so

### ISSUE THREAD

**Issue by lucasteligioridis** [koush/scrypted#1264]
**Describe the bug**
So maybe every 1 or 2 days I go to look at my Camera streams on my AppleTV 4k Ethernet edition and I might see 1 or 2 streams "stuck". Checking the logs with Scrypted to see whats going on and it looks like my AppleTV is not even querying the stream correctly because I don't see any logs with Scrypted when I open the "broken" stream on the AppleTV.

While this issue is occurring I tested the stream in HomeKit on both my iPhone and my MacBook to see if the entire stream was dead, but those work correctly and expected.

What resolves this is a reboot of the AppleTV 100% of the time.
So my first instinct is that this is potentially and more likely an AppleTV issue, perhaps some sort of memory leak or something on the stream stuck. I have 8 cameras on HomeKit, so not sure if there is something with a lot of cameras and issues with AppleTV HomeKit? 

I also find that the adaptive streaming seems to be kind of broken in this state as well? What I mean by that specifically is that I don't seem to get the cameras on the high quality stream. If I reboot the AppleTV it does what I expect, uses the lower quality stream and after a second or 2 it goes to the high quality stream.

Either way I'm actually just wondering if this is something you have heard of or if there is something on Scrypted thats perhaps causing it to get stuck (doubt it), but thought it wouldn't hurt to just raise this and see what thoughts you might have! Thank you :) 

**Expected behavior**
All streams to work consistently without having to reboot my AppleTV.

**Desktop (please complete the following information):**
 - OS: TvOS 17.2

**Additional context**
Running latest version of Scrypted at the time of writing this: 0.81.0 as well as latest HomeKit plugin 1.2.34

**Comment by koush** [comment]
I'd try disabling adaptive streaming to see if that fixes it. but given that the Apple TV seemingly works after a restart, this seems to be a issue on the Apple TV side.

**Comment by lucasteligioridis** [comment]
I think this issue was occurring before I had adaptive streaming on. So there are 2 issues, one where the adaptive streaming just doesn't seem to go to high quality and the other where the stream just doesn't load unless I restart the ATV.

I couldn't find anything online which makes me wonder if there is some sort of potential network related issue...

**Comment by koush** [comment]
What are the resolutions of the cameras? Adaptive stream prevents usage of > 2k streams on Apple TV because the TV crashes in grid mode.

**Comment by lucasteligioridis** [comment]
Ah! They are 4k cameras well 4 of them are anyway. Which are the ones I'm referring to with this issue.

So even when in direct mode (non grid) is it still limited to 2k?

**Comment by koush** [comment]
The issue is that AppleTV doesn't request a lower resolution stream when in grid mode, and just crashes. Adaptive bitrate detects grid mode usage via some request debouncing/heuristics.

**Comment by lucasteligioridis** [comment]
That actually makes sense, since going to adaptive the grid mode loads almost instantly for all cameras now.

But direct mode by your statement should allow into 4k? Or have I misunderstood?

**Comment by koush** [comment]
Apple TV will never receive 4k anymore with adaptive bitrate because any switch to grid mode or sliding through the cam list will crash it.

**Comment by lucasteligioridis** [comment]
Cool good to know! 
Is it a crash to the ATV or Scrypted?

In terms of those streams getting stuck, any idea or thought for debugging this? I am pretty confident it's an ATV thing but just haven't seen anything conclusive online.

**Comment by koush** [comment]
if its always the Apple TV and other iOS and macOS devices works fine, I'm going to chalk this up to an apple tv issue.
