### ISSUE TITLE
QEMU CPU detected. Set your CPU model to host.

### ISSUE THREAD

**Issue by vordenken** [koush/scrypted#1265]
**Describe the bug**
 I installed scrypted through HACS on my homeassistantOS VM.
I get the message "QEMU CPU detected. Set your CPU model to host." - but cannot find any information about this. Is this an error? Should I change something? What should I change?

**To Reproduce**
1. Install scrypted in homeassistantOS (VM)
2. Open scrypted

**Expected behavior**
This should not be an issue (?) or clearly state what to do?

**Screenshots**
<img width="1181" alt="image" src="https://github.com/koush/scrypted/assets/62395860/7dca0c83-42ad-43ae-82fb-aa72cce7fade">

**Desktop (please complete the following information):**
 - OS: HomeAssistantOS VM running in promos
 - Browser: Safari
 - Version:

**Comment by johntdyer** [comment]
@koush  any idea what caused this ?  I am running into the same issue now

**Comment by johntdyer** [comment]
@koush can we get this re-opened?

**Comment by koush** [comment]
vm needs to set cpu to host.
