### ISSUE TITLE
When Scrypted Docker container is getting updated, connection is lost with Synology Surveillance Station

### ISSUE THREAD

**Issue by jfhautenauven** [koush/scrypted#1266]
**Describe the bug**
Every time the Scrypted docker container is updated by watchtower, the synology plugin seems to be not able to reconnect by itself to Synology Surveillance Station.
The plugin indicates that the logon timeout of 10000 ms has been exceeded.

When I click on "reload plugin", everything goes back to normal again and Scrypted is able to connect without issue to Surveillance Station.

**To Reproduce**
Let watchtower update the docker container.
Upon container restart, Scrypted is unable to connect immediately to Surveillance Station.
Click on "Reload plugin" from the plugin page for Synology
All goes back to normal

**Expected behavior**
Reconnection after upgrade should be automatic and flawless

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
- OS : Synology DSM 7.2.1-69057 Update 3 (Latest to date)
- Running in docker container (official image) inside Synology Container Manager
- Scrypted versions that showed the defect (that I noticed) : 0.80;0.81;0.82;0.83

**Comment by koush** [comment]
I'm actually not sure on the purpose/usage on the Synology plugin. I think it's likely better to connect to the cameras directly? @bzoel is this plugin still necessary/maintained with ONVIF plugin?

**Comment by tayler-king** [comment]
If your camera supports multiple streams I would highly recommend just connecting directly to them with the RSTP / ONVIF plugins. I found the Surveillance Station plugin to cause me some issues when trying to connect cams through that.

The ONVIF plugin is currently pretty stable.

**Comment by tayler-king** [comment]
> I'm actually not sure on the purpose/usage on the Synology plugin. I think it's likely better to connect to the cameras directly? @bzoel is this plugin still necessary/maintained with ONVIF plugin?

The plugin allows you to connect to the rebroadcast streams that Surveillance Station creates for cams through RSTP. You can just manually copy the streaming path from Surveillance Station and connect the cams manually though, saving have to go through auth with Surveillance Station etc.

**Comment by DieterC1984** [comment]
Exactly same issue here. Following!
Not able to connect multiple streams to my cameras, they only allow one stream. So the only option is this problem to get solved.

**Comment by koush** [comment]
I think @IGx89 is the original author of this plugin. I believe there's some client reconnect issue happening here.

**Comment by IGx89** [comment]
Thanks for the bug report! It's been happening to me too actually, just hasn't annoyed me enough yet to spend the time to fix :). It didn't used to do this, but something in Scrypted or Synology apparently has changed that's causing the network request to time out in that scenario. I should be able to take a deeper look in the next week -- guessing adding a retry or two may do the trick.

**Comment by IGx89** [comment]
I've published v0.0.17 of the plugin with changes to make login more resilient. That should hopefully fix this issue.

**Comment by DieterC1984** [comment]
> I've published v0.0.17 of the plugin with changes to make login more resilient. That should hopefully fix this issue.

Will try it out!

**Comment by jfhautenauven** [comment]
I'll try it and report here if I see anything out of the ordinary, thanks for the fix @IGx89 :)

**Comment by DieterC1984** [comment]
> I've published v0.0.17 of the plugin with changes to make login more resilient. That should hopefully fix this issue.

Hi IGx89, just wanted to give you feedback on this matter because after all, you spent time and effort on this to fix this...
The adjustments are doing very well, the logon timeout issue is entirely gone now (at least for me). I believe one month of testing is sufficient enough to give reliable feedback :-)
Thanks a million!

**Comment by IGx89** [comment]
Great to hear, thanks for letting me know!
