### ISSUE TITLE
Username password after update

### ISSUE THREAD

**Issue by Iqbal198** [koush/scrypted#1268]
Updated to the latest Scrypted core after being notified by HAOS.

the cameras are working fine but cannnot access Scrypted add on because it is asking for username and password. I don’t remember creating a username and password and there is not an option to do a new username and password.

please help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pr0xyzer** [comment]
Username is "admin"

I can't log in, only get "TypeError: h is undefined".

**Comment by Iqbal198** [comment]
Thanks. I tried admin but don’t know password.

got the following error

typeerror: undefined is not an object(evaluating'h.request')

**Comment by BalooDK** [comment]
Same problem here

**Comment by Sup3rMario** [comment]
the same problem with Update 0.83.0 to 0.84.0:

no login possible over the icon in homeassistant menu (normal scrypted login - User Name - Password)
try with User Name "homeassistant" and no password - Message: "TypeError: h is undefined"
try with own scrypted User Name "xxxx" and password also Message: "TypeError: h is undefined"

also no login possible over direct UNC: https://ip-adrress:10443/endpoint/@scrypted/core/public/#/

HA OS: 11.4
HA Core: 2024.1.3
HA Supervisor: 2023.12.0
HA Frontend: 20240104.0
scrypted Current version: 18-jammy-full.s6-v0.84.0

**Comment by molotovkazic** [comment]
I too had the same issue after updating this morning.

Not working on Firefox, but working on Chrome as per @Sup3rMario stated above.

Firefox version: 121.0.1 (64-bit)
Chrome Version: Version 120.0.6099.216 (64-bit)

**Comment by devitus** [comment]
Same issue after updating to 18-jammy-full.s6-v0.84.0 Home Assistant Add-On today. Attempting reinstall and then a rollback via a backup to 18-jammy-full.s6-v0.80.0.

**Comment by devitus** [comment]
Restore to 18-jammy-full.s6-v0.80.0 fixed the issue.

**Comment by cirrusflyer** [comment]
I'm seeing the same, "TypeError: h is undefined" when attempting to login using Firefox.  Chrome based browser works fine.

**Comment by koush** [comment]
fixed!

**Comment by Rustymage** [comment]
v0.88.0 gave me this

<img width="356" alt="image" src="https://github.com/koush/scrypted/assets/19926955/c50b0b1e-a649-4d5c-9c8e-fae3da35a43a">

**Comment by koush** [comment]
Navigate back to the web root. it's a certificate error.

**Comment by Rustymage** [comment]
> Navigate back to the web root. it's a certificate error.

Hey - thanks. Tried it and the server doesn't respond - I can still ping the IP but otherwise, it's down.

<img width="660" alt="image" src="https://github.com/koush/scrypted/assets/19926955/e8f8ae67-8a78-4c14-86e7-1e478f789b54">

**Comment by Rustymage** [comment]
```
Jan 25 21:07:36 scrypted npx[325]: Starting scrypted main...
Jan 25 21:07:36 scrypted npx[325]: running npm --prefix /root/.scrypted exec scrypted-serve
Jan 25 21:07:37 scrypted npx[402]: /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58
Jan 25 21:07:37 scrypted npx[402]:     throw new Error('"node" version out of date. Please update node to v18 or higher.');
Jan 25 21:07:37 scrypted npx[402]:     ^
Jan 25 21:07:37 scrypted npx[402]: Error: "node" version out of date. Please update node to v18 or higher.
Jan 25 21:07:37 scrypted npx[402]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58:11)
Jan 25 21:07:37 scrypted npx[402]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:37 scrypted npx[402]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Jan 25 21:07:37 scrypted npx[402]:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Jan 25 21:07:37 scrypted npx[402]:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Jan 25 21:07:37 scrypted npx[402]:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Jan 25 21:07:37 scrypted npx[402]:     at require (node:internal/modules/cjs/helpers:119:18)
Jan 25 21:07:37 scrypted npx[402]:     at start (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main-exports.js:53:23)
Jan 25 21:07:37 scrypted npx[402]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
Jan 25 21:07:37 scrypted npx[402]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:37 scrypted npx[325]: Service exited. Restarting momentarily.
Jan 25 21:07:47 scrypted npx[325]: Starting scrypted main...
Jan 25 21:07:47 scrypted npx[325]: running npm --prefix /root/.scrypted exec scrypted-serve
Jan 25 21:07:47 scrypted npx[432]: /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58
Jan 25 21:07:47 scrypted npx[432]:     throw new Error('"node" version out of date. Please update node to v18 or higher.');
Jan 25 21:07:47 scrypted npx[432]:     ^
Jan 25 21:07:47 scrypted npx[432]: Error: "node" version out of date. Please update node to v18 or higher.
Jan 25 21:07:47 scrypted npx[432]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58:11)
Jan 25 21:07:47 scrypted npx[432]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:47 scrypted npx[432]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Jan 25 21:07:47 scrypted npx[432]:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Jan 25 21:07:47 scrypted npx[432]:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Jan 25 21:07:47 scrypted npx[432]:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Jan 25 21:07:47 scrypted npx[432]:     at require (node:internal/modules/cjs/helpers:119:18)
Jan 25 21:07:47 scrypted npx[432]:     at start (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main-exports.js:53:23)
Jan 25 21:07:47 scrypted npx[432]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
Jan 25 21:07:47 scrypted npx[432]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:47 scrypted npx[325]: Service exited. Restarting momentarily.
```

It isn't a cert error.
