### ISSUE TITLE
TypeError: h is undefined

### ISSUE THREAD

**Issue by navycow** [koush/scrypted#1269]
**Describe the bug**
I got logged out and am getting an error trying to log in "TypeError: h is undefined"

**To Reproduce**
1. Type in admin username
2. Type in password
3. Press enter
5. See error

**Expected behavior**
successful login

**Screenshots**

**Desktop (please complete the following information):**
 - OS: unraid
 - Browser firefox
 - Version 121.0.1

**Smartphone (please complete the following information):**

**Additional context**
i tried resetting the admin password using touch to create the reset password file, but that did not work.  i get the same error whether the username/password combo is correct or randomly typed.  no wrong password result.

**Comment by SlothCroissant** [comment]
+1 - Browser Console stack trace:

```
Uncaught (in promise) TypeError: h is undefined
    u https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    P https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    $connectScrypted https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    cd49 https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    use https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/chunk-vendors.b7f2772f.js:402
    cd49 https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    o https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    0 https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    o https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    n https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    <anonymous> https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
    <anonymous> https://hass.ff.lan:10443/endpoint/@scrypted/core/public/js/app.f89c908a.js:1
app.f89c908a.js:1:133033
```

**Comment by koush** [comment]
fixed, thanks!
