### ISSUE TITLE
Wyze API Key Failure - Blank space at beginning causes validation failure

### ISSUE THREAD

**Issue by GuyFromMars365** [koush/scrypted#1270]
Scrypted appears to put a blank space at beginning of API Key, causing header validation error.

1. Select 'Plugins.'
2. Input API key
3. Click 'Save'
4. Nothing happens. Reviewing console reflects the following:
File "/data/scrypted_data/plugins/@scrypted/wyze/python3.10-Linux-aarch64-20241303/local/lib/python3.10/dist-packages/requests/utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
/data/scrypted_data/plugins/@scrypted/wyze/files/v1/lib.arm64

**API key represented by X's for security.

**Expected behavior**
API key is saved without arbitrary space at beginning.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120.0.6099.225

**Comment by koush** [comment]
You’re probably pasting it in with a new line
