### ISSUE TITLE
TP-Link-IPC IPCamera Can't work

### ISSUE THREAD

**Issue by BlueBenson** [koush/scrypted#1271]
# Github Issues is not a Forum

**This issue tracker is not for hardware support or feature requests**. If you are troubleshooting adding a device for the first time, use Discord, Reddit, or Github Discussions. However, if something **was working**, and is now **no longer working**, you may create a Github issue.
Created issues that do not meet these requirements or are improperly filled out will be immediately closed.

# New Issue Instructions

My TPLINK IP CAMERA can't connect to Scryted. Both ONIVF or RTSP, but the VLC and Frigate can connect normally.
It looks like  can‘t pass the authorize (Log: RTSP/1.0 401 Unauthorized)

**Describe the bug**
My tplink IP Camer use onivf mode connect to the scryted, the camera can't show the picture(ALways Black)but the onivf PTZ works Good.

**Screenshots**
<img width="1333" alt="Screenshot 2024-01-18 at 19 33 43" src="https://github.com/koush/scrypted/assets/102408041/46eb294e-9a95-4d16-8a0c-59936feed6a4">

**Additional context**

[Rebroadcast Plugin]: mainStream prebuffer session started
[Rebroadcast Plugin]: mainStream prebuffer session starting
stream url rtsp://192.168.1.60:554/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:32 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER, MULTITRANS
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:32 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="ef44ef86a4b6c6c4164e456595aa7f75"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:32 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="3d800b9971ab9e08f3fbfd3859daa15d"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: TL-IPC642E-A4 restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:144860)
[Rebroadcast Plugin]:     at Socket.emit (node:events:517:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:350:12)
[Rebroadcast Plugin]: mainStream prebuffer session started
stream url rtsp://192.168.1.60:554/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:34 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER, MULTITRANS
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:34 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="8477e8ec31681cf5b0582ecc6cd0e416"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:34 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="7ce5af2b25975c1b261aea62ba46c3a3"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Snapshot Plugin]: creating error image with background Snapshot Failed false
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:144860)
[Rebroadcast Plugin]:     at Socket.emit (node:events:517:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:350:12)
[Video Analysis Plugin]: Video Analysis motion detection session eb845103 started.
[Video Analysis Plugin]: WebAssembly Decoder + WebAssembly Motion Detection
[Rebroadcast Plugin]: Selected stream minorStream
[Rebroadcast Plugin]: minorStream prebuffer session started
stream url rtsp://192.168.1.60:554/stream2
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.60:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER, MULTITRANS
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="cca5a5a8488cdad083b78b88adbb20af"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="5dd78d21edb5167c14dd25f8d754596a"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.1.60:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: minorStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Video Analysis Plugin]: Video Analysis ended with error RPCResultError: auth failed
[Video Analysis Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Video Analysis Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Video Analysis Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Video Analysis Plugin]: thread:main
[Video Analysis Plugin]: @scrypted/prebuffer-mixin:host
[Video Analysis Plugin]: host:@scrypted/nvr
[Video Analysis Plugin]: @scrypted/nvr:host
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: Video Analysis motion detection session eb845103 ended.
[Rebroadcast Plugin]: mainStream prebuffer session started
[Rebroadcast Plugin]: mainStream prebuffer session starting
stream url rtsp://192.168.1.60:554/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER, MULTITRANS
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="61cafce44a53ea6371775e17f57cf9e5"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Jan 18 2024 11:35:37 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="4bcfd1ca16c45d1a3b3e0ac944e15c89"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.1.60:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46a3lsZSU0MDA4MTE=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: TL-IPC642E-A4 restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:144860)
[Rebroadcast Plugin]:     at Socket.emit (node:events:517:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:350:12)
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:144860)
[Rebroadcast Plugin]:     at Socket.emit (node:events:517:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:350:12)

**Comment by BlueBenson** [comment]
It looks the camera only support upd RTSP.
this is my frigate config it works good, I add the "input_args: preset-rtsp-udp"
`  Gate:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.60:554/stream1#video=copy#audio=copy#audio=opus
          input_args: preset-rtsp-udp
          roles:
            - detect
            - record      
    objects:
      track:
        - person
    motion:
      mask: 411,103,558,101,556,45,413,51`

**Comment by koush** [comment]
dont use special chars in passwords.

**Comment by Ansen** [comment]
same error

Works on vlc

```
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://10.0.0.138:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46WktQbHdFU3NtNG94
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: TL-IPC55AE restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
[Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
```

**Comment by BlueBenson** [comment]
> > After some time it worked fine without me doing anything
> 
> same error
> 
> Works on vlc scrypted Version: 0.88.0 ONVIF Camera Plugin Version: 0.1.8
> 
> ```
> [Rebroadcast Plugin]: rtsp outgoing message
> [Rebroadcast Plugin]:  TEARDOWN rtsp://10.0.0.138:554/stream1 RTSP/1.0
> [Rebroadcast Plugin]: CSeq: 3
> [Rebroadcast Plugin]: User-Agent: Scrypted
> [Rebroadcast Plugin]: Authorization: Basic YWRtaW46WktQbHdFU3NtNG94
> [Rebroadcast Plugin]: 
> [Rebroadcast Plugin]: TL-IPC55AE restarting prebuffer session in 5 seconds
> [Rebroadcast Plugin]: mainStream prebuffer session ended with error Error: auth failed
> [Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92306)
> [Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145046)
> [Rebroadcast Plugin]:     at async V.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:118138)
> [Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
> ```

my problem is used the "@" char as the camera's password. I changed the password solved  the problem.
