### ISSUE TITLE
"Go to Live" button appears when it shouldn't (when already viewing stream(s) live)

### ISSUE THREAD

**Issue by briangunderson** [koush/scrypted#1272]
**Describe the bug**
When viewing cameras in grid view, sometimes (not always) the button to jump from playback to live stream is visible, creating confusion around whether or not the current view is actually live or just a recording.

**To Reproduce**
This happens occasionally when viewing cameras in grid view. I have not quite figured out the exact steps to reproduce yet, but this seems to happen every day or so.

**Expected behavior**
The button to jump to live stream should only be visible when user is not already viewing the live stream. (at least that's how I think it should work)

**Screenshots**
![2024-01-18 06_27_27-Clipboard](https://github.com/koush/scrypted/assets/1896394/8cf53ec8-e2c4-40a0-8d57-be010dde49bc)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version 120.0.6099.217 (Official Build) (64-bit)

**Additional context**
Happy to help gather logs etc.

**Comment by koush** [comment]
fixed on nvr.scrypted.app, will roll out to plugins next release.
