### ISSUE TITLE
http-auth-utils module not found

### ISSUE THREAD

**Issue by akeslo** [koush/scrypted#1277]
**To Reproduce**
1. run npx scrypted login IP from CLI

**Expected behavior**
Login to server

**Screenshots**
<img width="696" alt="image" src="https://github.com/koush/scrypted/assets/3003773/cd46257b-4b41-49f9-8ccf-34e5f9dbf08a">

**Desktop (please complete the following information):**
- Mac OSX M1

**Additional context**
I tried downgrading to node@18 and node@16.  With node@18 I get the same error. With node@16 I get a different error surrounding headers not found.

**Comment by koush** [comment]
fixed

**Comment by koush** [comment]
npx scrypted@latest to force an update

**Comment by koush** [comment]
err maybe not, one sec.

**Comment by akeslo** [comment]
Thank you!
