### ISSUE TITLE
Restore Not Working

### ISSUE THREAD

**Issue by tdashmike** [koush/scrypted#1280]
I tried updating with my own watchtower container and it failed after deleting the previous Scrypted v0.88.0 container. It had worked previously so I'm not sure what is going on, it may be because I updated docker yesterday. I recreated the contained with v0.89.0 but the backup file doesn't load and the website stops working until I restart the container. The container console doesn't appear to show any errors regarding the restore.

```
time="2024-01-23T01:54:46Z" level=info msg="Stopping /scrypted (7f7ad45bb55e) with SIGTERM"

time="2024-01-23T01:54:51Z" level=info msg="Creating /scrypted"

time="2024-01-23T01:54:51Z" level=error msg="Error response from daemon: invalid config for network host: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined networks"
```

**Comment by koush** [comment]
>  it may be because I updated docker yesterday

Probably that.

**Comment by tdashmike** [comment]
> > it may be because I updated docker yesterday
> 
> Probably that.

Sorry, maybe I wasn't being clear. The docker update probably caused watchtower to fail but the restore doesn't work for me on a new installation on docker. It seems to load the file and pops up a window asking to reconnect but the container log doesn't show anything.

**Comment by koush** [comment]
Did you rerun the docker compose install script
