### ISSUE TITLE
Start desktop app on boot

### ISSUE THREAD

**Issue by saltyautomation** [koush/scrypted#1284]
Feature Request not a bug! 

It would be great to be able to configure the desktop app running on a Mac to start at boot up. Mainly to address when the Mac reboots and no one has logged in. It would be even better if this was just an option to enable in the configuration after installation. 

**Expected behavior**
After installing Scripted there would be an option to enable running as a background service. This would allow scripted to automatically start back up after the Mac has been rebooted or if the user were to be logged out. This could be due to a power outage or software/system updates. 

**Desktop (please complete the following information):**
 - OS: MacOS Desktop App
 - Browser N/A 
 - Version Latest - N/A

**Additional context**
https://www.reddit.com/r/Scrypted/comments/18hp9te/allow_scrypted_for_macos_to_run_at_boot_as_a/

**Comment by koush** [comment]
Agreed 100% but I haven't found a decent way to do this, as the app requires a desktop session. The terminal version can handle this scenario, with the aforementioned reddit post. I am evaluating making that part of the terminal install script.

As for the app, I don't think this is possible. However, you can have the user that does autologin and then use a macro to to immediately lock the screen. 
<img width="529" alt="image" src="https://github.com/koush/scrypted/assets/73924/4652f3ba-5562-419e-a6c7-ec872707709d">

**Comment by saltyautomation** [comment]
Thanks for the quick response. Is the desktop session required to access the GPU/Neural engine? or is it for some other reason?

**Comment by koush** [comment]
GPU for decode via webgl, but the background service may have access to it too now using the wasm decoder. I haven't checked.

**Comment by JackCA** [comment]
I'm also hoping there can be a documented way to do this as having Scrypted launch on its own after a power loss would seem vital.

@koush thank you for your thoughts on this. Does your idea perhaps work? What script did you use if so?
