### ISSUE TITLE
MQTT plug-in port number can only be 1883 and cannot be changed

### ISSUE THREAD

**Issue by alikaylan** [koush/scrypted#1288]
My port  number is something other than 1883, and cannot manage to make the MQTT plug-in work without substantial rejigging. If the following did work, would resolve the issue:

mqtt://192.168.0.1/blah/blah:2888 for example, overriding the port.

**Comment by koush** [comment]
the host can contain the port.

**Comment by alikaylan** [comment]
The above example does not seem to work. Would you kindly give me a working example? Thanks, much appreciated.

**Comment by alikaylan** [comment]
This the console message with the above override, still going for the 1883 port:

mqtt client error Error: connect ECONNREFUSED 192.168.0.1:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.0.1,
  port: 1883
}

**Comment by alikaylan** [comment]
Never mind, syntax error on my part > 
mqtt://192.168.0.1:2888/blah/blah
works

Thanks. :-)
