### ISSUE TITLE
Costum Component Setup 

### ISSUE THREAD

**Issue by schorschi1981** [koush/scrypted#1292]
Scrypted Login Page ask in 2 different frames for credentials but doesnt say wich one.

I set up the custom Component for HA in the way the docu says.

1. turn off sidebar for Addon
2. add new admin User
3. Login

If i try to Login via custom component i get a frame where it says that the connection is not safe and i have to Log In again. 
![image](https://github.com/koush/scrypted/assets/62060020/2fa9f3c8-311a-4cf2-8584-83a0983bc874)

I tried every different Login i have in HA but no one works. I also tried another browser.

the docu says nothing more so i think there is something wrong

![image](https://github.com/koush/scrypted/assets/62060020/07a39bbc-6b39-4ece-bd56-c129e9b13745)

*Desktop (please complete the following information):**
 - OS: HA OS
 Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

 - Browser Chrome, Edge
 - Version Edge Version 121.0.2277.83/ Chrome Version 121.0.6167.85 (Offizieller Build) (64-Bit)

**Comment by koush** [comment]
Are you trying to set up nvr cards?

**Comment by schorschi1981** [comment]
i didnt reach that point because i could not Login via Sidebar. i didnt try more than that.

**Comment by koush** [comment]
you can log in via https://ip:10443

**Comment by koush** [comment]
please join discord if you need help setting up. this issue tracker is for bug reports, not support.

**Comment by schorschi1981** [comment]
dont get it but ok
