### ISSUE TITLE
@scrypted/snapshot exited null SIGILL

### ISSUE THREAD

**Issue by laczynskik** [koush/scrypted#1294]
scrypted can`t load snapshot plugin

in events:

21:16:14 | i | toMimeType: text/x-local-uri
21:16:14 | i | fromMimeType: x-scrypted/x-scrypted-scheme-scrypted-media;converter-weight=0
21:16:14 | e | plugin load error Error: plugin disconnected host:@scrypted/snapshot
21:16:14 | a | Plugin failed to load. View Console for more information.
21:16:14 | e | @scrypted/snapshot disconnected

in console of snapshot plugin:

linux x64 #1 SMP Debian 5.10.205-2 (2023-12-31)
server version: 0.93.0
plugin version: @scrypted/snapshot 0.2.34
full
starting plugin @scrypted/snapshot
node modules /data/scrypted_data/plugins/@scrypted/snapshot/node18-linux-x64-20241303
plugin loaded

all installed plugins:

![image](https://github.com/koush/scrypted/assets/27766505/0c5469b1-6826-435b-be50-e4424cf45629)

**Comment by koush** [comment]
cpu too old or using incorrect emulator cpu in a vm
