### ISSUE TITLE
Willing to help with Hikvision Camera

### ISSUE THREAD

**Issue by RaffoNin** [koush/scrypted#13]
Just tried out the Hikvision plug-in and the video does not play. Screenshots works though even though I only had to enter the RTSP link so it must be working. Motion Alerts don't work also. 

Both rtsp link and motion alerts (Hikvision integration) work on Home Assistant. 

I can submit logs or other things if needed. Appreciate the work you've done.

**Comment by koush** [comment]
Sure, hop into the discord.
