### ISSUE TITLE
Homekit HSV Doorbell 

### ISSUE THREAD

**Issue by fennec622** [koush/scrypted#130]
Hi
First thanks a lot for HSV Homekit very fast and very stable

I use with RTSP and MQTT motion 

Do you think it's possible to add doorbell to Homekit  ? 
I add doorbell MQTT but I can't associate with camera

I want to display video when someone push doorbell on appleTV 

Thanks a lot

**Comment by koush** [comment]
yes https://github.com/koush/scrypted/wiki/Do-It-Yourself-Doorbell
