### ISSUE TITLE
Scrypted NVR configuration issues

### ISSUE THREAD

**Issue by luvspud** [koush/scrypted#1309]
In NVR I'm unable to configure my Ring security camera for live viewing, it just always says "Loading":
![image](https://github.com/koush/scrypted/assets/18365511/e30218d0-a1b7-4eea-b0e8-a82e1fa6a210)

My Ring doorbell loads fine (in around 2 seconds) and shows as "Live" without issue:
![image](https://github.com/koush/scrypted/assets/18365511/0511b8d7-747d-4b28-98cf-4f066d2ae8e2)

In the Scrypted Ring Plugin, when I click on both, they display the live feed fine, it's only my Ring security camera in my garden that NVR doesnt want to show the live feed for.

Ring Plugin live shots:
Ring Doorbell (FrontDoor)
![image](https://github.com/koush/scrypted/assets/18365511/5b7996e3-3e28-4338-8a18-bea0eddddb4c)

Ring Security camera (Garden)
![image](https://github.com/koush/scrypted/assets/18365511/c8a43017-edcd-4de6-abc1-a49276dd0a21)

**Comment by koush** [comment]
You may want to disable Legacy RTSP mode in the Ring plugin, and then reload the plugin. This may resolve the issue.

Please note that Ring and other could cameras are noted as unsupported by Scrypted NVR. Cloud cameras do not use open standards to access the feed, and could be unreliable for any number of reasons unrelated to the NVR itself.

<img width="596" alt="image" src="https://github.com/koush/scrypted/assets/73924/bc92553f-191e-47da-a434-f74dd21b3562">

**Comment by luvspud** [comment]
Thanks Koush, that fixed the problem.
