### ISSUE TITLE
Wyze Cam v3 Firmware 4.36.11.8391 Breaks Wyze Plugin

### ISSUE THREAD

**Issue by Jgunde** [koush/scrypted#1312]
**Describe the bug**
After updating my Wyze Cam v3 to the latest 4.36.11.8391 firmware, the stream in Scrypted no longer works. I'm using the Wyze plugin to connect my Wyze cameras to Scrypted. I have other Wyze Cam v3s that are running older firmware that are still working in Scrypted.

An important note, all the Wyze cameras I'm testing with are outside of my local network. So this may be a problem that only affects remote cameras. (Scrypted still connects to my remote Wyze Cam v3s that are running older firmware.)

**To Reproduce**
1. Update Wyze Cam v3 to the 4.36.11.8391 firmware.
2. Enable the Wyze plugin within Scrypted.
3. The plugin will detect the camera using your Wyze account but the stream isn't viewable.

**Expected behavior**
A viewable stream of a Wyze Cam v3 running the 4.36.11.8391 firmware within the Scrypted WebUI.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: macOS Sonoma 14.3.1

**Smartphone (please complete the following information):**
N/A

----------

**UPDATE:** It appears this is a problem for remote streaming over the internet. Not local connections on the same network as Scrypted.

**Comment by koush** [comment]
https://github.com/mrlt8/docker-wyze-bridge/issues/1113

**Comment by koush** [comment]
Roll back firmware.

**Comment by khollis7** [comment]
This is also occurring on my local network
