### ISSUE TITLE
Remote stream issue on WiFi

### ISSUE THREAD

**Issue by Vicelow** [koush/scrypted#1313]
Hi there,

all of a sudden without having changed something, my Hikvision cameras are having issues when viewed remotely (but only in WiFi - 5G works). I'm quite sure it worked just fine before.
Viewing in local network also works flawlessly.

Any idea how to resolve this?

What I get is the following:

[Terrasse Garten] destination address 192.168.1.123 59644 56973
[Terrasse Garten] using address override 192.168.1.5
[Terrasse Garten] source address 192.168.1.5 49900 58793
[Terrasse Garten] handleStreamRequest {
  sessionID: '9c8631aa-e5f9-45f3-99c2-08d4d2082b41',
  type: 'start',
  video: {
    codec: 0,
    profile: 1,
    level: 2,
    packetizationMode: 0,
    cvoId: undefined,
    width: 1280,
    height: 720,
    fps: 30,
    pt: 99,
    ssrc: 257307846,
    max_bit_rate: 299,
    rtcp_interval: 0.5,
    mtu: 1378
  },
  audio: {
    codec: 'OPUS',
    channel: 1,
    bit_rate: 0,
    sample_rate: 24,
    packet_time: 20,
    pt: 110,
    ssrc: 1387046845,
    max_bit_rate: 24,
    rtcp_interval: 5,
    comfort_pt: 13,
    comfortNoiseEnabled: false
  }
}
[Terrasse Garten] Will wait for initial RTCP packet. { isHomeHub: false, isLowBandwidth: false, hasHomeHub: false }
[Terrasse Garten] { isLowBandwidth: false, isWatch: false, destination: 'local' }
[Terrasse Garten] { tool: 'scrypted', rtpSender: 'Scrypted' }
[Terrasse Garten] Waiting for video RTCP packet before sending video.
[Terrasse Garten] packet loss 1
[Terrasse Garten] Received first video RTCP packet.
[Terrasse Garten] rtsp/tcp h264
[Terrasse Garten] a/v h264 opus found h264 undefined
[Terrasse Garten] rtsp/tcp pcm_mulaw
[Terrasse Garten] -hide_banner -analyzeduration 0 -probesize 512 -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 13406757 -dn -sn -vn -f rtp rtp://127.0.0.1:56756?pkt_size=400 -sdp_file pipe:4
[Terrasse Garten] received first video packet
[Terrasse Garten] scanning for idr start found: 28 1
[Terrasse Garten] scanning for idr start found: 28 1 24 7 8
[Terrasse Garten] idr start found: 28 5
[Terrasse Garten] [rtsp @ 0x632bb00] method SETUP failed: 461 Unsupported Transport

[Terrasse Garten] Input #0, rtsp, from 'rtsp://127.0.0.1:42050':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s

[Terrasse Garten] Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> opus (libopus))
Press [q] to stop, [?] for help

[Terrasse Garten] Output #0, rtp, to 'rtp://127.0.0.1:56756?pkt_size=400':
  Metadata:
    title           : Media Presentation
    encoder         : Lavf60.3.100
  Stream #0:0: Audio: opus, 24000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc60.3.100 libopus

[Terrasse Garten] video/audio detected, discarding further input
[Terrasse Garten] received first audio packet
[Terrasse Garten] packet loss 156
[Terrasse Garten] packet loss 768
[Terrasse Garten] packet loss 4140
[Terrasse Garten] handleStreamRequest {
  sessionID: '9c8631aa-e5f9-45f3-99c2-08d4d2082b41',
  type: 'reconfigure',
  video: {
    width: 640,
    height: 360,
    fps: 30,
    max_bit_rate: 132,
    rtcp_interval: 0.5
  }
}
[Terrasse Garten] Media Stream reconfiguration was requested. Upgrade to Scrypted NVR for adaptive bitrate support.
[Terrasse Garten] packet loss 4142
[Terrasse Garten] packet loss 4660
[Terrasse Garten] packet loss 4661
[Terrasse Garten] packet loss 4662
[Terrasse Garten] packet loss 4663
[Terrasse Garten] packet loss 4963
[Terrasse Garten] packet loss 5162
[Terrasse Garten] packet loss 5312
[Terrasse Garten] packet loss 5554
[Terrasse Garten] packet loss 6186
[Terrasse Garten] packet loss 6187
[Terrasse Garten] packet loss 6188
[Terrasse Garten] packet loss 6521
[Terrasse Garten] packet loss 6702
[Terrasse Garten] packet loss 7064
[Terrasse Garten] packet loss 7178

**Comment by koush** [comment]
Packet loas

**Comment by Vicelow** [comment]
What does that mean? Or what should I do?
