### ISSUE TITLE
Scrypted Cloud Remote Access Stopped Working via Web, IOS and Android all at once. Login through plugin again fixed 1st time, now unable to reach scrypted server a day after.

### ISSUE THREAD

**Issue by 1823alex** [koush/scrypted#1315]
Scrypted 18-jammy-fulls6v0.93.0 running on HAOS  2023.11.2 Core, Supervisor 2024.0.1.1 operating sys 11.1, frontend 20231030.2

No longer able to access Scrypted cloud management console for recordings or management via the scrypted app on android or IOS. I've had scrypted working since like early November, port forwarded, logged into scrypted cloud plugin via email, have 3 local scrypted accounts behind that for viewing, all users had working access both at home on WiFi/LAN or away from home remotely on LTE or other networks.

**To Reproduce**
Unsure? I'm thinking an auto update caused this issue? Last night I fixed the error by just going to the scrypted cloud plugin in my local console, clicking login and just relogging in with my email as if the auth server forgot the association? That fixed it for a few hours, now today I can't login to the scrypted cloud plugin, I click login after entering my scrypted account email and password and then it takes a minute and says "Your server is not reachable by scrypted cloud" or something like that. I added port forwarding for ports; 10444, 10443, 41287 (previously worked with just 41287), and adding these didn't help.

Noticed the scrypted cloud plugin console throwing an odd error about port 4001 when I was doing these logins, so I opened 4001 to my scryted host running on HomeAssistantOS (note, scrypted has been kept up to date almost every other day, whereas my HAOS has't seen an update in a couple months, but I don't think that has any effect on this?)

**Expected behavior**

**Screenshots**

```
uncaughtException Error: connect ECONNREFUSED 50.219.188.186:4001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '50.219.188.186',

```
**Desktop (please complete the following information):**
Scrypted works via my externail IP address or custom domain name from phones, laptops, both on and off wifi, but the scrypted app itself won't work. On android I can get logged into the scrypted email account forthe server, but then it doesn't prompt me for my 2nd local scrypted user acccount credentials and doesn't load any cameras or settings etc.

**Smartphone (please complete the following information):**
Iphone 14 pro max latest ios
pixel 8 pro latest android os update for at&T
iphone 14 latest ios
Dell laptops

**Additional context**
It worked fine till a couple days ago, seemed to easily be fixed by relogin to the scrypted cloud plugin, but that hasn't worked this time and is for the first time saying your scrypted server is unreachable even though I have opened ports 10444, 10443, 41287, and even 4001 due to the console error pasted above I noticed around the time i tried to login to the cloud plugin again.

**Comment by koush** [comment]
fixed
