### ISSUE TITLE
Python Codecs error

### ISSUE THREAD

**Issue by recoi1er** [koush/scrypted#1325]
**Describe the bug**
Python Codecs keeps erroring 

**To Reproduce**
- Log into the portal management
- Look at notifications
- Click on Python error (View console for more info)
- Click on Console

**Expected behavior**
Not have Python error out

**Screenshots**
Console output:

darwin arm64 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
server version: 0.93.0
plugin version: @scrypted/python-codecs 0.1.92
########################
2/16/2024, 8:04:09 PM
########################
python version: python3.10
python prefix: /Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/python3.10-Darwin-arm64
requirements.txt (up to date)
# needed by libav to_ndarray
numpy>=1.16.2

# gobject instrospection for gstreamer.
PyGObject>=3.30.4; sys_platform != 'win32'

# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'

# pyvips is not available on windows, and is preinstalled as part of the installer scripts on
# mac and linux.
pyvips; sys_platform != 'win32'

# in case pyvips fails to load, use a pillow fallback.
# pillow for anything not intel linux, pillow-simd is available on x64 linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'

site-packages: /Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/python3.10-Darwin-arm64/lib/python3.10/site-packages
plugin start/fork failed
Traceback (most recent call last):
  File "/Users/komedia/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 381, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/Users/komedia/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 746, in loadZipWrapped
    from main import create_scrypted_plugin  # type: ignore
  File "/Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-4102f0c2114558b48fd277ce2ca12f4b.zip/main.py", line 6, in <module>
    import gstreamer
  File "/Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-4102f0c2114558b48fd277ce2ca12f4b.zip/gstreamer.py", line 9, in <module>
    import pilimage
  File "/Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-4102f0c2114558b48fd277ce2ca12f4b.zip/pilimage.py", line 13, in <module>
    class PILImage(scrypted_sdk.Image):
  File "/Users/komedia/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-4102f0c2114558b48fd277ce2ca12f4b.zip/pilimage.py", line 14, in PILImage
    def __init__(self, pilImage: Image.Image) -> None:
NameError: name 'Image' is not defined

**Server (please complete the following information):**
 - OS: MacOS 14.2.1
 - Installation Method: Local

**Hardware Model (please complete the following information):**
 - Device: Mac Mini M1

**Comment by koush** [comment]
rerun the local install script

**Comment by recoi1er** [comment]
> rerun the local install script

did that as per your suggestion, when I reload the python codec plugin it fires that error again

**Comment by koush** [comment]
> > rerun the local install script
> 
> did that as per your suggestion, when I reload the python codec plugin it fires that error again

try deleting and reinstalling the plugin. its missing Pillow for some reason, which is just a standard image processing library.

**Comment by recoi1er** [comment]
> > > rerun the local install script
> > 
> > 
> > did that as per your suggestion, when I reload the python codec plugin it fires that error again
> 
> try deleting and reinstalling the plugin. its missing Pillow for some reason, which is just a standard image processing library.

Yes! That fixed it, thank you!
