### ISSUE TITLE
Wyze Plugin Camera Quality

### ISSUE THREAD

**Issue by rmaes4** [koush/scrypted#1327]
Hello,

I was previously using docker-wyze-bridge and the RTSP camera plugin in Scrypted to get my wyze cameras into HKSV. I have now switched to using the Scrypted wyze plugin. I noticed that the video quality seems worse in HomeKit. I have attached some images for comparison. Is there some setting that I missed or a way to improve the video quality for the Scrypted wyze plugin?

docker-wyze-bridge
<img width="1536" alt="Screenshot 2024-02-17 at 4 40 08 PM" src="https://github.com/koush/scrypted/assets/941516/bae8b23d-6870-4f06-9357-587655d03fca">

Scrypted wyze plugin
<img width="1535" alt="Screenshot 2024-02-17 at 4 39 51 PM" src="https://github.com/koush/scrypted/assets/941516/ada7bd40-7e38-4b81-b562-c0e3a20bfb92">

docker-wyze-bridge
<img width="1536" alt="Screenshot 2024-02-17 at 4 37 30 PM" src="https://github.com/koush/scrypted/assets/941516/ef59dd7b-fa8f-4f13-951b-7a22af5f81eb">

Scrypted wyze plugin
<img width="1536" alt="Screenshot 2024-02-17 at 4 37 48 PM" src="https://github.com/koush/scrypted/assets/941516/18c7556e-61db-4361-86b5-b5405283c5d9">

The differences are more apparent if you view the pictures in full screen.

**Comment by koush** [comment]
Can use the bitrate setting
