### ISSUE TITLE
Scrypted Not Installing on Mac

### ISSUE THREAD

**Issue by Quinnod345** [koush/scrypted#133]
When I try to install scrypted on mac with the command, this happens.

<img width="568" alt="Untitled 2" src="https://user-images.githubusercontent.com/90010678/150461543-d31c3429-a28a-4f4e-802e-e362636a3159.png">

When I try it with npx scrypted install-serve this happens.

<img width="567" alt="Untitled" src="https://user-images.githubusercontent.com/90010678/150461725-7f2fb2d5-5cb8-4a1e-b67f-6c0965741920.png">
 It seems to me that npm cant find scrypted at all. I uninstalled and reinstalled both npm and scrypted on my computer. I cannot at the moment find a way to fix this.

**Comment by Quinnod345** [comment]
I also tried renaming the directory just as it says to do, but macOS just gives me an error.

**Comment by westerlund** [comment]
I installed Scrypted successfully the other day. Did you follow the Mac installation section?
https://github.com/koush/scrypted/wiki/Local-Installation#mac-installation

**Comment by koush** [comment]
delete `~/.scrypted`

something is already there, maybe you ran it as sudo. you should not do that
