### ISSUE TITLE
No Live Video for any Camera in Management Console

### ISSUE THREAD

**Issue by xpl01td** [koush/scrypted#1341]
When clicking on a camera's thumbnail, in the management console, I get a blank screen pop up and the below error message in the console for every camera I have. Also, in Cameras and Recording, in the NVR screen all cameras have a preview picture but when I click on one, the bottom left corner shows "Loading" and never goes to a live feed and no recordings play. RTSP streams work to my Frigate server, but WebRTC seems to have issues.

[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[WebRTC Plugin]: Error starting playback for WebRTC track. Error: peer connection closed
[WebRTC Plugin]:     at check (/src/peerconnection-util.ts:38:19)
[WebRTC Plugin]:     at Object.apply [as execute] (/src/peerconnection-util.ts:16:21)
[WebRTC Plugin]:     at execute (/external/werift/node_modules/rx.mini/lib/core/index.js:18:30)
[WebRTC Plugin]:     at I.setConnectionState (/external/werift/packages/webrtc/src/peerConnection.ts:1509:32)
[WebRTC Plugin]:     at I.close (/external/werift/packages/webrtc/src/peerConnection.ts:1399:10)
[WebRTC Plugin]:     at /src/ffmpeg-to-wrtc.ts:666:23
[WebRTC Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by koush** [comment]
not enough information here. need to know browser, and enable webrtc plugin debug logging. please join discord to resolve this issue.

**Comment by koush** [comment]
would also check demo site in browser. if it doest work on your system this is likely a codec or network issue.
