### ISSUE TITLE
Unable to view recording.

### ISSUE THREAD

**Issue by ghaisasadvait** [koush/scrypted#1344]
I have enabled Scrypted NVR for my camera. I have also purchased the required license. I was able to see the recordings earlier, but since the past 24 hrs, I am unable to see any recordings.

**Comment by koush** [comment]
can you join discord and provide more information? will need to see logs. guessing the storage directory isn't set up correctly.

**Comment by ghaisasadvait** [comment]
> can you join discord and provide more information? will need to see logs. guessing the storage directory isn't set up correctly.

Hello,

The storage is setup correctly and i can see files being created with .rtsp extension. But I'm not able to see those in scrypted. Nor did I find a way to open those files outside scrypted.

**Comment by koush** [comment]
Closing due to insufficient information.
