### ISSUE TITLE
two way audio can not use in DIY doorbell 

### ISSUE THREAD

**Issue by bmwcar** [koush/scrypted#1348]
dear author ,  i meet a problem with C210 , i buy a C210 .
1. Tapo C210 , it is perfect running  when use two way audio to talk in video camera , talking is perfect. 
2. But i do a DIY Doorbell ,  it only can camera talking and HSV received the voice , if i talking in HSV  then the camera dont have any voice. it look like only one way audio in DIY Doorbell.
3. So i wanna know how to make the DIY Doorbell can two way audio to talk
4.  DIY Doorbell setting
![11](https://github.com/koush/scrypted/assets/41981098/badcef12-d6f4-4837-ab97-f8e9812b76b0)
5. is there any setting i made wrong ?
6. Thanks!

**Comment by koush** [comment]
don't use the device group method anymore, use the custom doorbell extension in dummy switch plugin.

**Comment by bmwcar** [comment]
> don't use the device group method anymore, use the custom doorbell extension in dummy switch plugin.

![22](https://github.com/koush/scrypted/assets/41981098/19980b65-43bd-4178-a62d-253b64a99e82)
![33](https://github.com/koush/scrypted/assets/41981098/effa74e8-d4a3-4b9c-b482-71dda3bd5f02)

bro , i a button which called 'virtual_button' , and custom doorbell extension choose it . 
But i click 'virtual_button' in homekit , the HSV dont  ring .

**Comment by bmwcar** [comment]
i have finished the two way audio , according this to do ：https://github.com/koush/scrypted/issues/302

**Comment by SungwaYu** [comment]
> i have finished the two way audio , according this to do ：#302

Could you share how you got it working? I don't see anything about two way audio in #302
