### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by matthew-larner** [koush/scrypted#135]
Would be great to have release numbering for this project and propagate that through to docker hub tags. Without releases it's impossible to manage docker-compose updates without pulling the latest version each time.

**Comment by koush** [comment]
I'll take a look about adding that to GitHub. Right now the releases are on npm.

**Comment by miwagner1** [comment]
It’s still possible to manage docker compose versions, it’s just a bit more difficult as you need to use the hashes

**Comment by fdegier** [comment]
If you want I can help you setup the CICD for tagging the releases.

**Comment by koush** [comment]
> If you want I can help you setup the CICD for tagging the releases.

There's a GitHub action that you can look at.

**Comment by koush** [comment]
Ideally I'd like to trigger a build and tag when there's a new npm publish. That already has the tags and everything.

Though triggering an npm publish when there's a new tag works to.

**Comment by koush** [comment]
Yeah that sounds fine. At the end of the day, something is being done manually to trigger everything. Right now its the npm publish.

**Comment by aegjoyce** [comment]
I too would welcome this change as it would allow me to release sequential updates for the Home Assistant add-on without having to reinstall it completely! As it currently just pulls the image in its entirety, the version in the manifest has to match the version number of the docker image, which is always “latest” so I can’t release updates without completely reinstalling to fetch the new image

**Comment by koush** [comment]
done
