### ISSUE TITLE
Google Device Access + Homekit with latest Rebroadcast

### ISSUE THREAD

**Issue by nplourde** [koush/scrypted#1353]
Unable to view nest doorbell gen2 stream from IOS Home app. Motion/person notification are also broken.
*Restarting Scrypted resolved the issue of the stream being unavailable but just for a short time.

Workaround:
Reverting to Rebroadcast 0.10.13 resolved the issue.

Repro step:
- Update to rebroadcast 0.10.16
- open stream from Home App (stream will work)
- close Home App and wait a few minutes
- open stream from Home App (stream will not work)

**Server (please complete the following information):**
 - OS: Debian
 - Installation Method: Docker

**Client (please complete the following information, if applicable):**
 - Software: Home app

**Comment by cubbieblue16** [comment]
I also am having this issue. I am glad I found this post because I almost gave up. It was like every 4 hours I had to restart the rebroadcast extension.  So far, this solution is working for me.

**Comment by cubbieblue16** [comment]
This "workaround" actually didnt work for me. It was more stable throughout the day but at night, the feeds collapse still.

I have come to the realization that Google Cameras and Scrypted are just not good.

**Comment by nplourde** [comment]
No issues on my side since I downgraded. Did not had time yet to try investigating more the issue but it might be related to my docker / network config if there is no obvious issue in the software.

**Comment by koush** [comment]
did you try 0.10.14 and 0.10.15? I need a specific version to investigate

**Comment by nplourde** [comment]
Issue started with 0.10.14

**Comment by cubbieblue16** [comment]
I am on 0.10.13 I am also getting a lot of weird errors now with the snapshot plugin.  This was from this morning when I noticed that my cameras were down and had issues with rebroadcast as well.

These are all Google Cameras

[WebRTC Plugin]: fua packet missing. ski pping refragmentation. 1
[WebRTC Plugin]: jitter buffer purged pa cket: 15759
[WebRIC Plugin]: jitter buffer purged pa cket: 15760
########################
3/14/2024, 10:58:22 AM
#井井井井井井井井井井井##井井井#井#####
[WebRIC Plugin]: jitter buffer purged pa cket: 21228
[WebRTC Plugin]: jitter buffer purged pa cket: 36891
[Rebroadcast Plugin]: sending prebuffer
6000
[Rebroadcast Plugin]: WebRTC active rebr oadcast clients: 1
[Rebroadcast Plugin]: Unable to find syn c frame in Itsp prebuffer.
[Rebroadcast Plugin]: WebRTC active rebr oadcast clients: 0
[Snapshot Plugin]: creating error image with background Snapshot Failed false

[WebRTC Plugin]: jitter buffer purged pa cket: 21228
[WebRTC Plugin]: jitter buffer purged pa cket: 36891
[Rebroadcast Plugin]: sending prebuffer
6000
[Rebroadcast Plugin]: WebRTC active rebr oadcast clients: 1
[Rebroadcast Plugin]: Unable to find syn c frame in rtsp prebuffer.

**Comment by cubbieblue16** [comment]
> No issues on my side since I downgraded. Did not had time yet to try investigating more the issue but it might be related to my docker / network config if there is no obvious issue in the software. 

So I just realized it auto updated on its own. I didn't realize there was an auto update on the plugins. I'm back working pretty well again.

**Comment by koush** [comment]
need console log from camera

**Comment by cubbieblue16** [comment]
> need console log from camera

Attached are the logs from this morning when all my Google Cams were having issues.

[scrypted logs.txt](https://github.com/koush/scrypted/files/14637605/scrypted.logs.txt)

**Comment by cubbieblue16** [comment]
I am just having a shit ton of problems with the Snapshot plug. Mainly on my Google Cams but occasionally on my Wyze.

**Comment by mercnmash** [comment]
Any word on this? I have the same issue and trying o downgrade rebroadcast plugin to see if it works for me

**Comment by ceelo404** [comment]
I had to downgrade as well to 0.10.13 to get it to work.
