### ISSUE TITLE
can't build webhook

### ISSUE THREAD

**Issue by mjwood7** [koush/scrypted#1354]
https://github.com/koush/scrypted/blob/6766b354383edaa374563e5a69a55277a98b58fb/plugins/webhook/src/main.ts#L220-L230

Get the following error from line 224:

```
Type '{ [key: string]: any; }' is missing the following properties from type 'WritableDeviceState': setState, id, interfaces, mixins, and 2 more.
```

It appears this is a result of some changes to interfaces/base classes in the SDK.

I believe this is also happening in mqtt plugin

**Comment by koush** [comment]
fixed
