### ISSUE TITLE
Home Assistant - Basic Auth Popup

### ISSUE THREAD

**Issue by gorfreed** [koush/scrypted#1357]
I have installed the custom component for Scrypted via HACS on my HA (latest). When clicking the integration in the sidebar, I am getting a basic auth popup that doesn't accept any user/password (I tried all combinations in use for anything on the machine) which keeps me from using the platform on HA. I cannot identify what is causing this to occur, there is no popup when accessing my Scrypted install directly via its address on the server machine.

![image](https://github.com/koush/scrypted/assets/6634117/f2c07732-d1a7-4aca-ba69-5d27ca290d34)

**Comment by gorfreed** [comment]
It doesn't seem to be browser-related. I use Chrome, but I just verified the issue on Edge (no extensions) and on incognito tabs.

**Comment by koush** [comment]
Can you screenshot/paste your custom component configuration that you used to add scripted?

**Comment by gorfreed** [comment]
My HA is docker-based standalone, so I had to install Scrypted via docker compose. The Scrypted custom component was installed through HACS. I didnt change your customize anything and only used the UI for that.

**Comment by koush** [comment]
did this also get resolved with the fix from your other bug report?

**Comment by gorfreed** [comment]
No it didnt, as the cause for the other one was simply me not ready the appropriate docs. This one though I did by the book on a vanilla system. Is there any log readout from some of the systems that might be helpful?

**Comment by gorfreed** [comment]
Alternatively, is it possible to obtain the "Scrypted NVR Card Webpage URL" without the embedded Scrypted page on HA? Maybe ID and token can be taken from the main frontend as well? I could then simply use those to generate the code for the custom dashboard panels.

**Comment by gorfreed** [comment]
These errors are displayed in the Chrome console at the moment the popup is shown:

![image](https://github.com/koush/scrypted/assets/6634117/a0a469e4-c9ad-4401-8910-32c3bfe7d17a)

**Comment by koush** [comment]
does your HA http configuration use anything that might be intercepting 401s or basic autos? I think that's the underlying problem. Seeing the request and response headers would be useful.

**Comment by koush** [comment]
> Alternatively, is it possible to obtain the "Scrypted NVR Card Webpage URL" without the embedded Scrypted page on HA? Maybe ID and token can be taken from the main frontend as well? I could then simply use those to generate the code for the custom dashboard panels.

that's exactly what this process does, and something is intercepting the auth.

**Comment by koush** [comment]
it may also be worth restarting HA or scrypted to see if that resolves it.

**Comment by gorfreed** [comment]
> > Alternatively, is it possible to obtain the "Scrypted NVR Card Webpage URL" without the embedded Scrypted page on HA? Maybe ID and token can be taken from the main frontend as well? I could then simply use those to generate the code for the custom dashboard panels.
> 
> that's exactly what this process does, and something is intercepting the auth.

What I meant is if it is possible to manually generate the URL without the Scrypted NVR HA. Maybe the required token and ID are listed elsewhere?

How can I generate the request headers output you need?

**Comment by koush** [comment]
> These errors are displayed in the Chrome console at the moment the popup is shown:
> 
> ![image](https://private-user-images.githubusercontent.com/6634117/309878670-a0a469e4-c9ad-4401-8910-32c3bfe7d17a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDMxNTMsIm5iZiI6MTcwOTYwMjg1MywicGF0aCI6Ii82NjM0MTE3LzMwOTg3ODY3MC1hMGE0NjllNC1jOWFkLTQ0MDEtODkxMC0zMmMzYmZlN2QxN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM4NjFlMzczMjU2NzhlMDYzOTdkMjUzNzE3MTNiNTBlOTRmOTkyOTg2MzRlY2I2ODcxMzNmMjc4MmZmMmM2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2Qcqm_p1a2mPvaDn_J5-KilGcZpE57CFYB6l9Ra3KHw)

You can inspect the network tab in the browser to see why the headers for these failed requests. I'll add another week to your trial because I'd like to solve this mystery.

**Comment by koush** [comment]
> What I meant is if it is possible to manually generate the URL without the Scrypted NVR HA. Maybe the required token and ID are listed elsewhere?

the id you see is the same id when you browse to the sidebar and get the browser login prompt. If it fails there, it will fail also fail in the card. something is munging the auth in Home assistant.

**Comment by gorfreed** [comment]
I installed everything again from the scratch and now everything works. Who knows what has caused this.
Anyways, Scrypted is now doing its thing and I successfully embedded its entities on my dashboard. Its very cool!
You got a new subscriber :)

**Comment by koush** [comment]
@gorfreed when you say everything, does that mean you reinstalled HA as well?

**Comment by jevans10** [comment]
this is happening to me. i have uninstalled and reinstalled the integration and add-on yet the issue persists
