### ISSUE TITLE
Scrypted NVR card not available

### ISSUE THREAD

**Issue by gorfreed** [koush/scrypted#1358]
I would like to include Scrypted NVR on my HA dashboard. However, i cannot find a custom card in the dashboard editor UI nor does there seem to be any documentation on how the "Scrypted Custom Component for Home Assistant" (installed via HACS) allows for the "creation of Scrypted NVR cards". Being able to embed Scrypted into my main smart home dashboard would be a requirement for me to use the service long-term.

**Comment by koush** [comment]
https://docs.scrypted.app/home-assistant.html

**Comment by gorfreed** [comment]
I totally missed that. Beautiful!
