### ISSUE TITLE
Unifi Protect Doorbell Announces on Google Multiple times when pressed

### ISSUE THREAD

**Issue by zappy16** [koush/scrypted#1359]
**Describe the bug**
I have the Unifi Protect system connected to Scrypted using the plugin. I also have the Google Home plugin setup and configured and all camera entities are available inside Google Home app and I'm able to stream cameras to Home Hubs no issues. Everything seems to be working with Google Home well except "Voice Notifications" which can be enabled on doorbell type devices. This announces "Someone is at the Front Door" on all the Google homes throughout the house, but there seems to be a bug with it and Scrypted that is causing it to announce at least 3 times instead of just the once. 

**To Reproduce**
1. Go to to the G4 Doorbell and ring the doorbell button
2. Listen to all Google Homes throughout the house announce 3 times that "Someone is at the front door"

**Expected behavior**
I expect only one Voice Announcement when the doorbell is rung, not 3. 

**Screenshots**
![IMG_3F2E6F084CDE-1](https://github.com/koush/scrypted/assets/17417763/f7c905bc-e70a-44ca-a583-fc7382ab268c)
This is the doorbell configuration in Google Home with "Voice Notifications" turned on.

**Server (please complete the following information):**
 - OS: Ubuntu 22
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Unifi Protect Doorbell G4 Pro

**Client (please complete the following information, if applicable):**
 - Software: Google Homes

**Additional context**

**Comment by koush** [comment]
fixed

**Comment by zappy16** [comment]
Works great now!!
