### ISSUE TITLE
 Hikvision camera reports error when opening two way audio

### ISSUE THREAD

**Issue by Rivens7** [koush/scrypted#1365]
I have an eigenstone camera T1. Through the software, I can check that its main control is Hikvision V5.38 build 2301103 and encoding version V7.0 build 221229. The camera itself supports the intercom function, but now that I have added it to the onvif plugins, all other functions are normal. Only HomeKit cannot talk to each other, the audio encoding has been adjusted to G711_U, and the two way audio function cannot be used whether it is turned on or not.
**Turn on two way audio error code：**
[HomeKit]: intercom failed to start RPCResultError: ONVIF audio backchannel not found
[HomeKit]:     at t.OnvifIntercom.checkIntercom (/src/onvif-intercom.ts:40:19)
[HomeKit]:     at process.intercomClient (node:internal/process/task_queues:95:5)
[HomeKit]:     at t.OnvifIntercom.startIntercom (/src/onvif-intercom.ts:50:35)
[HomeKit]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:37)
[HomeKit]: @scrypted/onvif:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: handleStreamRequest { sessionID: 'c6998aa9-0376-49e3-84ee-d6383686bf84', type: 'stop' }
[HomeKit]: streaming session killed, duration: 14s
[Rebroadcast Plugin]: subStream active rebroadcast clients: 0
[HomeKit]: ffmpeg exited
[HomeKit]: two way audio failed y [Error]: timeout waiting for client
[HomeKit]:     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:995406)
[HomeKit]:     at listOnTimeout (node:internal/timers:569:17)
[HomeKit]:     at processTimers (node:internal/timers:512:7)
**Turn off two way audio error code：**
[HomeKit]: two way audio failed TypeError: r.startIntercom is not a function
[HomeKit]:     at Socket.<anonymous> (/@scrypted/homekit/main.nodejs.js:2:1080584)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: '0776bba2-fedb-4f5f-babf-1258c6e6ebd5',
[HomeKit]:   type: 'reconfigure',
[HomeKit]:   video: {
[HomeKit]:     width: 640,
[HomeKit]:     height: 360,
[HomeKit]:     fps: 30,
[HomeKit]:     max_bit_rate: 132,
[HomeKit]:     rtcp_interval: 0.5
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: Media Stream reconfiguration was requested. Upgrade to Scrypted NVR for adaptive bitrate support.

**Comment by Rivens7** [comment]
**I really need this function, please help analyze it, thank you, I wish you a happy day!**

**Comment by koush** [comment]
> ONVIF audio backchannel not found


try Hikvision two way maybe.

**Comment by koush** [comment]
this is not a bug in scrypted. this is also not a support forum, per the bug report template that you seemingly deleted and ignored.
