### ISSUE TITLE
Camera online but not available in Home App

### ISSUE THREAD

**Issue by skynan22** [koush/scrypted#1366]
Since yesterday evening one of four Hikvision cameras, connected to scrypted/homekit, was suddenly disconnected. Three cameras are still working, one is still offline. I can connect to the camera via IPv4 and on my synology surveillance station the camera is still online. The camera is working. After that I tried to reset connection within Hmekit Plugin in Scrypted an RESET Homekit pairing. Pairing does not work - a timeout occurs. There are no errors in any logs available in Scrypted whether at the Homekit Plugin nor in the specific camera device console entries. 

**To Reproduce**
RESET pairing information - looks good, no errors, but the camera can not be integrated in Home App
**Expected behavior**
Camera was connected as accessory device, not via bridge. Three cameras are still working in the same modus.

**Server (please complete the following information):**
 - OS: Ubuntu
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Hikvision DS-2CD2T85FWD-I5

**Client (please complete the following information, if applicable):**
 - Software: Chrome Browser @ MacOS

**Additional context**
log entries within homekit plugin - Gartenhaus camera is missing, at the end

This looks good:

adding Gartenhaus
[Gartenhaus] Device is in accessory mode and is online. HomeKit services are being published. 

But when adding to HomeKit, Gartenhaus is missing ... 

<img width="907" alt="Bildschirmfoto 2024-03-08 um 08 58 05" src="https://github.com/koush/scrypted/assets/6624641/7cb99eb7-6003-442a-b594-d17b6bf84c97">

**Comment by koush** [comment]
a change was made to make the default mdns provider avahi on systems that support it. you may want to switch to ciao or bonjour manually.
