### ISSUE TITLE
Rebroadcast Plugin - 0.10.17 gets 404 on stream 

### ISSUE THREAD

**Issue by jordancrawfordnz** [koush/scrypted#1391]
**Describe the bug**

After updating to Rebroadcast plugin 0.10.17 I noticed that my Homekit camera feed would only show a screenshot of the video but couldn't show the live camera feed. I confirmed that this also happened when viewing the stream within the Scrypted UI - it showed a preview but if I clicked into the feed it showed a black screen.

I looked into the logs and found a message about the stream 404'ing being repeated - see attached log.

I downgraded to version 0.10.16 and confirmed the feed works fine.
I see a23a73942d3c99e014a2d0a522b18da112d5bf2f changed how Scrypted builds the stream URL so I suspect it's now hitting an invalid URL and getting 404 errors? Though none of the log really makes sense to me and I don't have context on the codebase to diagnose it further.

[0-10-17-driveway-cam-failures.log](https://github.com/koush/scrypted/files/14734273/0-10-17-driveway-cam-failures.log)
In the logs, 192.168.1.20 is my NAS.

**To Reproduce**

Use version 0.10.17 on a camera configured with prebuffer and try to connect to the stream.
This might be specific to my camera running through Synology Surveillance Station - I don't have much context on how this works unfortunately.

**Expected behavior**
The stream loads successfully.

**Server:**

Running Scrypted in a Docker container on a Synology NAS

**Hardware Model:**

Synology DS920+ NAS - Wyze branded camera (but I believe the RTSP stream is being proxied through Surveillance Station).

**Client:**

Homekit and the Scrypted web UI

**Additional context**

I use Synology Surveillance Station on my Synology NAS for recording. I use the Synology Surveillance Station plugin to connect to Surveillance Station, then use the Rebroadcast Plugin to make it available for Homekit (to be honest I can't quite remember the full details of my setup as it was setup a while back).

Please let me know if there's anything else you'd like me to try to help diagnose the issue.

**Comment by koush** [comment]
use ffmpeg parser.

**Comment by jordancrawfordnz** [comment]
Apologies for my naivety - where do I set that - is that an option in the rebroadcast plugin?
To clarify, this was working fine on version rebroadcast plugin version 0.10.16, has parsing changed?

**Comment by koush** [comment]
under each stream you can set the parser. yes, the url construction changed to match the rfc spec, as it was not working with other cameras.
