### ISSUE TITLE
Raspberry pi: ffmpeg-linux-arm: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by andybyrne55** [koush/scrypted#1404]
This issue was raised previously and was closed as "**armv7 not supported**.", however my Raspberry PI (Raspberry Pi 4 Model B Rev 1.4) is armv8, not v7 and I still have the same problem. 
Scrypted has worked perfect for me for years and only with a recent update it is broken.

Any help is much appreciated, as I love this tool...

[Rebroadcast Plugin]: Porch restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP ext.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.68.153:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=andy&password=cortys-bYzkyf-1kejfi
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:32921/b5be03d2642c77d7
**[Rebroadcast Plugin]: /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: 8: Syntax error: newline unexpected**
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:71744)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: Porch restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: RTMP ext.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP ext.bcs prebuffer session starting
stream url rtmp://192.168.68.153:1935/bcs/channel0_ext.bcs?channel=0&stream=0&user=andy&password=cortys-bYzkyf-1kejfi
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:34063/04b50f2d69fa52b4
**[Rebroadcast Plugin]: /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: 8: Syntax error: newline unexpected**
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:71744)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: Porch restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP ext.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://192.168.68.153:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=andy&password=cortys-bYzkyf-1kejfi
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:40303/1e3b5899761eb564

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Installation Method: [e.g. Desktop App, Docker, Local]

**Hardware Model (please complete the following information):**
 - Device: [e.g. Amcrest]

**Client (please complete the following information, if applicable):**
 - Software: [e.g. Home app, NVR app, Alexa, Browser]

**Additional context**

**Comment by koush** [comment]
need 64bit pi os.
