### ISSUE TITLE
Unifi object detections don't appear in device group

### ISSUE THREAD

**Issue by doug-hoffman** [koush/scrypted#1407]
**Describe the bug**
Unifi object detections aren't shown in device groups.

**To Reproduce**
1. Create new device group
2. Add `Camera`, `Intercom`, `MotionSensor`, `ObjectDetector`, `VideoCamera`, `VideoCameraConfiguration`, `VideoCameraMask` interfaces from a Unifi Protect camera.
3. Walk in front of the camera
4. See only motion events

**Expected behavior**
Object detections should appear on both the Unifi camera device and the device group.

**Screenshots**

<img width="330" alt="image" src="https://github.com/koush/scrypted/assets/58886678/81a6b9ff-377b-445b-b584-a0709598e5d7">
<img width="326" alt="image" src="https://github.com/koush/scrypted/assets/58886678/2d04821a-a833-41b5-b972-bcea4a82ed7c">

**Server (please complete the following information):**
 - OS: Synology 
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Unifi G5 Dome

**Client (please complete the following information, if applicable):**
 - Software: Browser

**Comment by koush** [comment]
no plans to fix

**Comment by koush** [comment]
only basic event types are supported for groups. object detector is too complex.
