### ISSUE TITLE
Accessory Already Added

### ISSUE THREAD

**Issue by cirrusflyer** [koush/scrypted#141]
I've been testing Scrypted and Camera.UI for HSV.  Have been using Scrypted off and on for over a week.  Went to add the bridge back to my Homekit configuration, and now getting "Accessory Already Added, ...you'll need to reset it first.  I've rebooted my phone and rebooted my Apple TV and Homepod mini.  No luck.  I've been able to remove the bridge and add it with no issue until today.

**Comment by koush** [comment]
remove the old bridge from homekit. if that does not work, you can change the homekit plugin user id if you're running into this.

**Comment by cirrusflyer** [comment]
That's the thing - I already removed the bridge yesterday.  That's how I remove it when I test another solution.  The bridge is not there.  Or if it's there, it's now hidden.  You're saying, just change the userid code under the homekit plugin?

**Comment by koush** [comment]
> That's the thing - I already removed the bridge yesterday. That's how I remove it when I test another solution. The bridge is not there. Or if it's there, it's now hidden. You're saying, just change the userid code under the homekit plugin?

yep. I think this is a homekit bug, but thats a workaround.
