### ISSUE TITLE
Scrypted Alexa Not Linking

### ISSUE THREAD

**Issue by keysuresh** [koush/scrypted#1410]
request failed due to invalid authorization te [AggregateError]: 
    at Function.from (/node_modules/axios/dist/node/axios.cjs:837:14)
    at h.<anonymous> (/node_modules/axios/dist/node/axios.cjs:3083:25)
    at h.emit (node:events:518:28)
    at h.emit (node:domain:488:12)
    at ClientRequest.l.forEach.u.<computed> (/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:518:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:488:12) {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 50.219.188.186:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '50.219.188.186',
      port: 443
    },
    Error: connect ENETUNREACH 2001:559:800c:1900::92ae:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2001:559:800c:1900::92ae',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      Authorization: 'Bearer V2#a37-E2U7P-AHBLR4SjPpLnixlzi6VKoUXfMaxcFGg6F_fBaaqEHu4RKBfBIumFh6gKyozR3tUkBooJWF9JlAMShrZFtjDdUWyhF6JL2RQyTYKN998DLoibgNz--q9-XS5l6Q1zAQy6dbb6cOTJcqk5Y0mcRoYGjAx-P0G8_lPaqyyLpmKouGguSEwhnn07s3ydcq5Bc_Z7frWq_LeOga0wOOdeH6UBMRmoto8Xm-XveI_u2MRJEeSp-Wka3_U82m-HQd2RunK7AukFInf8vzVavd-_ExI1LAQ06MldCIod1UP34kqPuX3_VdjQONar1nJq3_JzfDtDm8bGvp4BFAdA!!#{"id":"VTGEELgzLMeS7P0gckggbzFySqa2","clientId":"amazon","serverId":"23c8499966b0a6d5","expiry":1712065993366}',
      'User-Agent': 'axios/1.6.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://home.scrypted.app/_punch/getcookie',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function (anonymous)],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function (anonymous)],
      socket: [Function (anonymous)]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/_punch/getcookie',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: ua],
      beforeRedirects: [Object],
      hostname: 'home.scrypted.app',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/_punch/getcookie'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /_punch/getcookie HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer V2#a37-E2U7P-AHBLR4SjPpLnixlzi6VKoUXfMaxcFGg6F_fBaaqEHu4RKBfBIumFh6gKyozR3tUkBooJWF9JlAMShrZFtjDdUWyhF6JL2RQyTYKN998DLoibgNz--q9-XS5l6Q1zAQy6dbb6cOTJcqk5Y0mcRoYGjAx-P0G8_lPaqyyLpmKouGguSEwhnn07s3ydcq5Bc_Z7frWq_LeOga0wOOdeH6UBMRmoto8Xm-XveI_u2MRJEeSp-Wka3_U82m-HQd2RunK7AukFInf8vzVavd-_ExI1LAQ06MldCIod1UP34kqPuX3_VdjQONar1nJq3_JzfDtDm8bGvp4BFAdA!!#{"id":"VTGEELgzLMeS7P0gckggbzFySqa2","clientId":"amazon","serverId":"23c8499966b0a6d5","expiry":1712065993366}\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: home.scrypted.app\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/_punch/getcookie',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'home.scrypted.app',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://home.scrypted.app/_punch/getcookie',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError: 
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
response error 500:

**Comment by koush** [comment]
your ipv6 is busted.

**Comment by keysuresh** [comment]
Thanks for the replay.i can’t understand.that means my router problem.?
