### ISSUE TITLE
Memory grows unbounded until the machine OOMs

### ISSUE THREAD

**Issue by mmichon** [koush/scrypted#1414]
**Describe the bug**
Memory grows unbounded until the machine OOMs.

**To Reproduce**
1. Start Scrypted
2. Wait a couple days
3. Container starts swapping, eventually OOMs

**Expected behavior**

**Screenshots**
<img width="2473" alt="image" src="https://github.com/koush/scrypted/assets/673622/5a317da3-1b1b-43fc-ab47-f68a9cea0426">

<img width="1210" alt="image" src="https://github.com/koush/scrypted/assets/673622/cbfd1287-5b54-43ea-bc84-4ce3ff71fdbd">

**Server (please complete the following information):**
 - OS: Scrypted 0.97.0 container on Proxmox VE 8.1.4 on bare metal

**Hardware Model (please complete the following information):**
 - Device: N100 with a 5th Gen i5, 4GB RAM
 - m.2 Coral Edge TPU

**Client (please complete the following information, if applicable):**
 - Software: Home App on iOS/MacOS

**Additional context**
I transferred my config from Docker on RPi en masse to this new machine (as shown on #965 and #778), so it's something to do with the config.

**Comment by koush** [comment]
4GB is probably insufficient. Also not sure what a N100 with a 5th gen i5 is?

**Comment by koush** [comment]
you also seem to be using pam diff and openvino. the latter is using a lot of memory.

**Comment by dalto12593** [comment]
I've started to have the same exact problem but haven't narrowed down the issue.
