### ISSUE TITLE
Dahua motion events not working anymore

### ISSUE THREAD

**Issue by JBosecker** [koush/scrypted#1417]
**Describe the bug**
Since 6fd66db896b30def12633a9fda403c2baefea698 the motion events are not working anymore.
I think the handling of the "ignore" start of the stream is not correct (at least for my setup).
The message I see in the console is
`preparing event listener http://REDACTED/cgi-bin/eventManager.cgi?action=attach&codes=[All]
expected boundary but found HTTP/1.1 200 OK
listen loop closed, restarting listener.`
So the HTTP header is leading to be an unexpected value and the stream is destroyed because of the exception is thrown.

**To Reproduce**
1. Install Dahua camera
2. Add the Amcrest plugin in Scrypted
3. Add device with the correct configuration
4. Try to trigger motion event

**Expected behavior**
Motion is detected correctly.

**Actual behavior**
Motion isn't detected.

**Server:**
 - OS: HaOS
 - Installation Method: Home Assistant addon

**Hardware Model:**
 - Device: e.g. Dahua IPC-HFW1320S-W

**Additional context**

**Comment by koush** [comment]
thanks, can you join discord. I need someone to share a camera with me to fix this.

**Comment by koush** [comment]
fixed
