### ISSUE TITLE
Unable to install Sensibo plugin from Plugins search

### ISSUE THREAD

**Issue by brandonb927** [koush/scrypted#1419]
**Describe the bug**
Attempting to install the Sensibo plugin results in nothing happening in the management console.

**To Reproduce**
1. Go to Plugins page and search "sensibo"
1. Click on Install in the plugin card that shows up
1. See error in the Developer Tools Console

**Expected behavior**
The Sensibo plugin is installed and I am taken to the plugin configuration page.

**Screenshots**
<img width="1118" alt="image" src="https://github.com/koush/scrypted/assets/1509352/1f778dd7-fd76-480e-b063-5d9e44c922c2">

**Server (please complete the following information):**
 - OS: unRAID
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: N/A

**Client (please complete the following information, if applicable):**
 - Software: Google Chrome, Version 123.0.6312.87 (Official Build) (arm64)

**Additional context**

**Comment by brandonb927** [comment]
I hate to argue with a maintainer about this, but according to the npm module it is. I understand, after googling, that it leads me to https://github.com/FiachAntaw/scrypted-sensibo as the source of the plugin however this is in no way illustrated _anywhere_.

**Comment by koush** [comment]
Yeah, the plugins are scoped into the scrypted org so I can publish to them should I need to, but the maintainers have their own repositories. The non core plugins are (slowly) being spun out of this mono repo.
