### ISSUE TITLE
Amcrest authentication issues

### ISSUE THREAD

**Issue by mrala** [koush/scrypted#1420]
**Describe the bug**
I'm receiving 401 errors using the Amcrest plugin on a `IPC-T2431T-AS S2` camera (no problems on the older non-S2 revision `IPC-T2431T-AS`). It's attempting to use digest auth but getting 401 responses. However, I'm able to successfully curl the camera endpoints with digest auth. The RTSP video feed is working correctly. I've configured security settings on the `S2` variant identically  as an older camera. This is breaking event/motion detection.

**To Reproduce**
1. Add a `IPC-T2431T-AS S2` camera using the Amcrest plugin
2. View the console for the Amcrest plugin
3. See example errors:
    ```
    error retrieving stream configurations Error: http response statusCode 401
        at checkStatus (C:\server\src\fetch\index.ts:43:15)
        at httpFetch (C:\server\src\fetch\http-fetch.ts:124:28)
        at processTicksAndRejections (/<snip>/plugins/amcrest/out/lib/internal/process/task_queues.js:95:5)
        at AmcrestCameraClient.request (C:\src\amcrest-api.ts:126:26)
        at C:\src\main.ts:422:41 {stack: 'Error: http response statusCode 401
        at ch…t-api.ts:126:26)
        at C:\src\main.ts:422:41', message: 'http response statusCode 401'}
    preparing event listener http://192.168.0.5:80/cgi-bin/eventManager.cgi?action=attach&codes=[All]
    listen loop connection failed, restarting listener. http response statusCode 401
    ```
    
    I'm able to use digest auth in a curl request. The camera reports a login failure.
    ```
    $ curl --user "<snip>:<snip>" "http://<snip>:80/cgi-bin/eventManager.cgi?action=attach&codes=\[All\]" --digest
    --myboundary
    Content-Type: text/plain
    Content-Length: 183
    
    Code=LoginFailure;action=Pulse;index=0;data={
            "Name": "admin",
            "Type": "Web3.0",
            "Address":      "<scrypted-ip-address>",
            "Error":        4,
            "LocaleTime":   "2024-04-04 22:41:04",
            "UTC":  1712284864
    }
    --myboundary
    Content-Type: text/plain
    Content-Length: 119
    
    Code=VideoMotion;action=Start;index=0;data={
            "LocaleTime":   "2024-04-04 22:41:47",
            "UTC":  1712284907,
            "Name": "IPC"
    }
    
    --myboundary
    Content-Type: text/plain
    Content-Length: 118
    
    Code=VideoMotion;action=Stop;index=0;data={
            "LocaleTime":   "2024-04-04 22:41:51",
            "UTC":  1712284911,
            "Name": "IPC"
    }
    ```
**Expected behavior**
We should be able to communicate with the camera without any 401 errors/authentication issues.

**Server (please complete the following information):**
 - OS: Windows
 - Installation Method: Local

**Hardware Model (please complete the following information):**
 - Device: Amcrest IPC-T2431T-AS S2

**Client (please complete the following information, if applicable):**
 - Software: n/a

**Additional context**
n/a

**Comment by koush** [comment]
can you run curl with verbose flags

**Comment by koush** [comment]
can you also roll back to the earliest available version to see if it resolves

**Comment by mrala** [comment]
I've tried rolling back to every available version of the Amcrest plugin with the same results each time.

Here is verbose curl output. Interestingly, it looks like there is a 401 at first but then authenticates correctly:

```
curl -v --user "<snip>:<snip>" "http://<cam-ip>/cgi-bin/eventManager.cgi?action=attach&codes=\[All\]" --digest
*   Trying <cam-ip>:80...
* Connected to <cam-ip> (<cam-ip>) port 80
* Server auth using Digest with user 'scrypted'
> GET /cgi-bin/eventManager.cgi?action=attach&codes=[All] HTTP/1.1
> Host: <cam-ip>
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Connection: close
< Content-Length: 0
< WWW-Authenticate: Digest realm="Login to D14<snip>", qop="auth", nonce="36b23460-<snip>", opaque=""
<
* Excess found: excess = 2 url = /cgi-bin/eventManager.cgi (zero-length body)
* Closing connection
* Issue another request to this URL: 'http://<cam-ip>/cgi-bin/eventManager.cgi?action=attach&codes=[All]'
* Hostname <cam-ip> was found in DNS cache
*   Trying <cam-ip>:80...
* Connected to <cam-ip> (<cam-ip>) port 80
* Server auth using Digest with user 'scrypted'
> GET /cgi-bin/eventManager.cgi?action=attach&codes=[All] HTTP/1.1
> Host: <cam-ip>
> Authorization: Digest username="scrypted", realm="Login to D14398D80B28EEBF", nonce="36b23460-<snip>>", uri="/cgi-bin/eventManager.cgi?action=attach&codes=[All]", cnonce="YTll<snip>>", nc=00000001, qop=auth, response="ec89<snip>>", opaque=""
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Connection: Keep-Alive
< Content-Type: multipart/x-mixed-replace; boundary=myboundary;charset=utf-8
< Expires: Thu, 01 Dec 2099 16:00:00 GMT
< Pragma: no-cache
* no chunk, no close, no size. Assume close to signal end
<
--myboundary
Content-Type: text/plain
Content-Length: 186

Code=LoginFailure;action=Pulse;index=0;data={
        "Name": "scrypted",
        "Type": "Web3.0",
        "Address":      "<scrypted ip>",
        "Error":        4,
        "LocaleTime":   "2024-04-08 18:41:59",
        "UTC":  1712616119
}
```

**Comment by koush** [comment]
do you think you can dm me on discord and port forward a camera for me. going to have a hard time fixing this otherwise.

**Comment by bgre033** [comment]
I believe this error is related to certain special characters in the password for logging into the camera. In my case it was a "^", with Scrypted v0.114.0.

Also reported as per https://www.reddit.com/r/Scrypted/comments/18pcslh/amcrest_401_error_when_adding_to_amcrest_plugin/.

**Comment by jparchem** [comment]
Seeing the exact same behavior on an Amcrest IP5M-1190EW with the latest firmware (V2.810.00AC004.0.R, Build Date: 2023-09-04).   If there are logs, etc. I can help capture, you have a willing participant!  😄

**Comment by koush** [comment]
does changing the stream parser to ffmpeg tcp on all streams fix this

**Comment by jdtoppin** [comment]
+1 on this issue. Same camera as OP.

**Comment by tkolik** [comment]
Hi, Same issue for Dahua:
Device Type: IPC-HFW1530S-0280B-S6
System Version: V2.840.0000000.15.R
Build Date: 2025-07-30
WEB Version: V3.2.1.2292781
ONVIF Version: 22.06 (V2.0.1.131727)

Any resolution expected?

**Comment by rice1204** [comment]
Same issue with another dahua cam (IPC-T2831T-ZS). Scrypted fails to add and returns 400 error, even with validation turned off. 
ONVIF plugin works. 

edit: sorry for the unformatted console output. code quotes aren't working


`root@scrypted:/var/log# curl -v --user "xxxxxx:xxxxxxxx" "http://192.168.5.59/cgi-bin/eventManager.cgi?action=attach&codes=\[All\]" --digest
*   Trying 192.168.5.59:80...
* Connected to 192.168.5.59 (192.168.5.59) port 80
* Server auth using Digest with user 'xxxxx'
> GET /cgi-bin/eventManager.cgi?action=attach&codes=[All] HTTP/1.1
> Host: 192.168.5.59
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Digest realm="Login to 369443cf268dbd476b151c4557b8218d", qop="auth", nonce="1864490077", opaque="d53ebdf29680ac5187d623844684d73879b44715"
< Connection: close
< Set-Cookie:secure; HttpOnly
< CONTENT-LENGTH: 0
< 
* Closing connection
* Issue another request to this URL: 'http://192.168.5.59/cgi-bin/eventManager.cgi?action=attach&codes=[All]'
* Hostname 192.168.5.59 was found in DNS cache
*   Trying 192.168.5.59:80...
* Connected to 192.168.5.59 (192.168.5.59) port 80
* Server auth using Digest with user 'xxxxx'
> GET /cgi-bin/eventManager.cgi?action=attach&codes=[All] HTTP/1.1
> Host: 192.168.5.59
> Authorization: Digest username="xxxxx", realm="Login to 369443cf268dbd476b151c4557b8218d", nonce="1864490077", uri="/cgi-bin/eventManager.cgi?action=attach&codes=[All]", cnonce="NTMxYmFjNGM0NzQ2N2JlYjkxNWI4ZDRlMjlmNDk4Yzc=", nc=00000001, qop=auth, response="476d1cfd37a898f90ea7b9c1c967a340", opaque="d53ebdf29680ac5187d623844684d73879b44715"
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-XSS-Protection: 1;mode=block
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'
< Strict-Transport-Security: max-age=604800; includeSubDomains
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: Thu, 01 Dec 2099 16:00:00 GMT
< Connection: Keep-Alive
< Set-Cookie:secure; HttpOnly
< Content-Type: multipart/x-mixed-replace; boundary=myboundary
* no chunk, no close, no size. Assume close to signal end
< 
--myboundary
Content-Type: text/plain
Content-Length:75

Code=InterVideoAccess;action=Pulse;index=0;data={
   "Type" : "WebLogin"
}


--myboundary
Content-Type: text/plain
Content-Length:132

Code=RtspSessionDisconnect;action=Stop;index=0;data={
   "Device" : "192.168.3.11",
   "StreamType" : "Main",
   "UserAgent" : ""
}

`

**Comment by Teruell** [comment]
Same issue on a IP5M-1190, firmware from 23/10/24 (latest). Not sure why this issue is closed?

**Comment by Teruell** [comment]
Also tried to roll back to previous camera firmware, same issue.

**Comment by carsontwilson** [comment]
I can add IPC-T24IR-AS-2.8mm-S2 to the list. Latest firmware in my case. Have tried even the simplest of passwords, and constant failed auth (web auth is ok). Note that IPC-T54IR-AS-2.8mm-S3 works fine, however.

**Comment by keith721** [comment]
I can add EmpireTech IPC-T221R-ZAS-S3 to this Amcrest 401 issue.  Just started with Scrypted, and thought this might be a firmware issue.  My camera has V.17 of the firmware, and supposedly it's at version 22 these days.  Andy at EmpireTech will be sending the correct latest firmware tomorrow.  If this firmwmare does not resolve the issue, it's definitely the Amcrest plug-in.  If anyone has a method for obtaining debugging output from the plugin, I'm listening.  I've already manually executed six of the CGI-BIN API calls using Firefox, and all six returned successfully.

**Comment by keith721** [comment]
Any hope of reopening this ticket for these two Dahua-rebranded EmpireTech cameras?  
- IPC-T24IR-AS-S2
- IPC-T221R-ZAS-S3

Apparently, there is still some lingering 401 Authorization issue causing the problem.  Without debug logging (I"m using the Home Assistant add-on) it's difficult to tell which CGI-BIN API call is causing the problem.
