### ISSUE TITLE
Rebraodcast - Syntax error

### ISSUE THREAD

**Issue by NebuNC2** [koush/scrypted#1423]
Hey there, 
Reolink streams dont work anymore. I get following error:
[Rebroadcast Plugin]: /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: 8: Syntax error: newline unexpected
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:71744)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:531:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:488:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[Rebroadcast Plugin]: Reolink Doorbell restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Can someone help?

Thanks

**Comment by koush** [comment]
arm v32 not supported

**Comment by NebuNC2** [comment]
What does it mean?

**Comment by bjia56** [comment]
Your pi was initially set up with a 32 bit raspbian OS, which is no longer supported. 32/64 bit mixed mode is also not supported. Upgrade to 64 bit by re-imaging and reinstalling the OS, if your hardware supports 64 bit
