### ISSUE TITLE
Dahua Motion not working after adding custom motion sensor

### ISSUE THREAD

**Issue by Trilis29** [koush/scrypted#1426]
**Describe the bug**
Added custom motion sensor and removed later, now not receiving motion from NVR.

**To Reproduce**
Add Armcrest plugin, add camera, add custom motion sensor, save, ,delete custom motion sensor.

**Expected behavior**
Motion events should be sent.

**Screenshots**
![image](https://github.com/koush/scrypted/assets/51697921/98203f7b-5c0c-45eb-9eba-50a315670cb2)

**Comment by koush** [comment]
custom motion sensor overrides all sensors.

**Comment by Trilis29** [comment]
@koush but that is a bug, why are you closing? If removing custom motion sensor default motion values from NVR should be set. Now only possible when deleting the camera and readding to get it working without custom motion sensor

**Comment by koush** [comment]
You may need to restart the camera plugin to make it register the original sensor?

**Comment by Trilis29** [comment]
Tried to restart camera plugin, homekit, even scrypted did not register original one. Only recreating camera helped
