### ISSUE TITLE
Google Device Access - no things

### ISSUE THREAD

**Issue by onkelfarmor** [koush/scrypted#143]
Followed the instructions and entered the GDA project id, GCP client id, and GCP secret in scrypted.app. Click login and I go through the OAuth flow with success. Am being redirected back to scrypted.app.

But, no things are created:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/7473641/151063046-5f1ea85c-93a3-4b1b-a9cd-18a566e98812.png">

Can go through the flow again and again but still no things.

What am I missing?

Edit: Console:
starting plugin @scrypted/google-device-access 0.0.66
plugin successfully loaded
user-id AVP...
user-id AVP...

**Comment by koush** [comment]
What sort of devices do you have? Currently thermostats and cameras are supported. I can dump more information into the log about everything that was found.

**Comment by onkelfarmor** [comment]
Nest Hub Max ... (camera)

**Comment by koush** [comment]
oh, probably just need to allow that type as a camera. I'll add it in a bit.

**Comment by koush** [comment]
released the beta plugin may sync that device type now, let me know. will take a few minutes to show up.

**Comment by koush** [comment]
beta plugins will not be prompted to update. version 0.0.67 will show up in the dropdown.

**Comment by onkelfarmor** [comment]
It works, didn't succeed in getting the motion sensor in the Nest Hub to work but just use Scrypted for that, thanks!

**Comment by koush** [comment]
Yes, these devices seem to meter their events. You're often better off running a software motion detector like opencv or the pam-diff plugin.
