### ISSUE TITLE
Previously selected IP address unable to be removed from setting "Scripted Server Address"

### ISSUE THREAD

**Issue by erikpendragon** [koush/scrypted#1430]
**Describe the bug**
While first setting up scripted I checked the box for my ip address, later one I confirmed it was working I set a static IP to my server and selected my new IP, but doesn't show my old IP to unselect, and I can't delete it.

**To Reproduce**
1 in your settings check the box to select your IP address
2 change your IP address of the server
3 try to uncheck you old IP address from settings

**Expected behavior**
allow my to remove an old check box if the option becomes unavailable

**Screenshots**
<img width="454" alt="Screenshot 2024-04-13 at 1 42 14 PM" src="https://github.com/koush/scrypted/assets/7390273/7d78f989-64b7-42f1-8f08-bc2ed128411a">

**Server (please complete the following information):**
 - OS: Proxmox Helper Script
 - Installation Method: CT

**Hardware Model (please complete the following information):**
 - Device: Scrypted

**Comment by koush** [comment]
use backspace

**Comment by erikpendragon** [comment]
> use backspace

I have tried back space it doesn't delete it, the old one stays there. It will only delete the bible of the one available in the drop down.

**Comment by koush** [comment]
yes this issue comes up often, its possible to delete with either backspace or delete.

**Comment by erikpendragon** [comment]
> yes this UX issue comes up often, its possible to delete with either backspace or delete.

Interesting, safari on my Mac won't let me delete it, but on iOS it did. 
Thank you.
