### ISSUE TITLE
From 098.5 to 0.99 cpu avg load increased

### ISSUE THREAD

**Issue by Jirik6** [koush/scrypted#1439]
# New Issue Instructions

**Describe the bug?**
Yesterday docker update from 0.98.5 to 0,99 version cpu avg load increased +4% All previous version was OK.

**Server (please complete the following information):**
 - OS: raspOS
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: rpi5

**Comment by koush** [comment]
Server has no effect on cpu load.

**Comment by Jirik6** [comment]
Ok mayby some plugin update :)Thx JiriOdesláno z iPhonu21. 4. 2024 v 9:12, Koushik Dutta ***@***.***>:﻿
Server has no effect on cpu load.
