### ISSUE TITLE
eufy cloud possibility?

### ISSUE THREAD

**Issue by paqpaqpaq** [koush/scrypted#144]
Do you think you would be able to add support for eufy devices which are not on their hub?
E.g. Solocams, and more particular: S40 solar cam?

**Comment by koush** [comment]
it's possible but I probably won't do it myself tbh

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/195

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/88
