### ISSUE TITLE
HA install yaml update needed again.  

### ISSUE THREAD

**Issue by monsieurlatte** [koush/scrypted#1442]
sorry to report this, just noticed missing the last 2 updates from .97 on.

**Comment by monsieurlatte** [comment]
Is there a reason this was marked as completed but the files aren't showing up in github as updated?   Am I missing something?

**Comment by Hopixel45** [comment]
For all to know Koush aka Koushik Dutta is a rude ill mannered person, so don't ask him anything for mostly he will reply, and will close the issue with no explanation at all, as if you all,are dirt.

**Comment by monsieurlatte** [comment]
well I hope that's not the case and certainly they have been pretty responsive to my posts, as well as being a fellow seattlite, I hoping that isn't true!
