### ISSUE TITLE
Live Video Feed via Notification on Apple TV with Scrypted Integration

### ISSUE THREAD

**Issue by fbnksr** [koush/scrypted#1447]
### Discussed in https://github.com/koush/scrypted/discussions/1445

<div type='discussions-op-text'>

<sup>Originally posted by **fbnksr** April 24, 2024</sup>
I transitioned my UniFi G4 Doorbell Pro from being integrated into HomeKit via Home Assistant's Configuration Yaml to using Scrypted**. With Scrypted, I'm enjoying many additional features, and I receive notifications smoothly on my Apple TV in Picture-in-Picture mode. However, the notification feed remains a static image; it doesn't transition to live view either in PiP or when I press the TV/Home button. Although it does switch the PiP to full-screen mode, the image remains static. The regular camera view on the Apple TV does function normal with the live view.

_****Side note:** I use Scrypted (v0.99.0) as an Add-on via Home Assistant._</div>

**Comment by fbnksr** [comment]
I'm puzzled as to why this is being dismissed so easily. It's a genuine problem as the live stream isn't functioning correctly. I've successfully integrated it through Home Assistant, and it operates smoothly. Therefore, it's not a problem with Apple or the hardware; rather, it seems to stem from the Scrypted logic for the live stream notification.

**Comment by Hopixel45** [comment]
For all to know Koush aka Koushik Dutta is a rude ill mannered person, so don't ask him anything for mostly he not will reply, and will close the issue with no explanation at all, as if you all,are dirt.

**Comment by herbi3** [comment]
@fbnksr Many things on this repo are dismissed without reason here
