### ISSUE TITLE
Cannot login after initial install

### ISSUE THREAD

**Issue by HanSooloo** [koush/scrypted#146]
Installed via Docker method.  Went to the HTTPS URL, and am greeted with this image:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/879582/151405976-c07444d7-ddbc-4a3a-a09a-5838523a6970.png">

When I put an arbitrary username and password to set them, e.g., `user` and `password, it gives me a "User doesn't exist" error message.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/879582/151406786-b11cf070-713e-494d-bfde-42ea9c0ecea8.png">

What am I doing wrong?

**Comment by koush** [comment]
Somehow a user was created? You can delete `~/.scrypted/volume` to reset everything.

**Comment by phis5533** [comment]
Hello,

I don't remember my user/pass too.... And deleting `~/.scrypted/volume`does not work for me....

**Comment by superpower10** [comment]
Same here. Why isn't there a description for the initial setup in Home Assistant?
