### ISSUE TITLE
Config.yaml not updated for 102 install

### ISSUE THREAD

**Issue by monsieurlatte** [koush/scrypted#1466]
just a heads up

**Comment by koush** [comment]
Do not open issues requesting version bumps.

**Comment by GSzabados** [comment]
> Versions will be bumped after testing.

Congratulations mate!  You just won the `dickhead developer `title!

Banning somebody for asking to follow basic steps when you do releases. You are a great person! A well motivated human being! 

https://github.com/koush/scrypted/commit/540b990a08500e2b44957b3faab7555dd01519e7

Updated the version number 7 hour ago, and did the release 3 days ago.

Don't you think that you are the one who is sitting backward on the horse?
