### ISSUE TITLE
homekit

### ISSUE THREAD

**Issue by filoor** [koush/scrypted#148]
Hi,

I having issues wit homekit. It will install but it wont run.
If i set mdns to CIAO i will get this error
`Starting to advertise 'Scrypted 8C05' using ciao backend!
uncaughtException AssertionError [ERR_ASSERTION]: Probe query packet exceeds the mtu size (2638>1440). Can't split probe queries at the moment!
    at Function.createDNSQueryPackets (/@scrypted/homekit/main.nodejs.js:2:67317)
    at MDNSServer.sendQueryBroadcast (/@scrypted/homekit/main.nodejs.js:2:22062)
    at Prober.sendProbeRequest (/@scrypted/homekit/main.nodejs.js:2:96129)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}`

and whin i chang mdns to bonjour it will stock on.
`Starting to advertise 'Scrypted 8C05' using bonjour-hap backend!`

i have a Docker running on a vm running linux 
this is my compose file:
`version: '3.5'

services:
    scrypted:
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        network_mode: host
        volumes:
            - ~/.scrypted/volume:/server/volume
        logging:
            driver: "json-file"
            options:
               max-size: "10m"
               max-file: "10"`

**Comment by koush** [comment]
can you not run docker on the host itself? why run on a vm in linux? not sure what your network environment is, but thats likely the issue.
