### ISSUE TITLE
Unable to log in after changing ip address of the Scrypted lxc

### ISSUE THREAD

**Issue by hasrt1206** [koush/scrypted#1501]
I have changed my scrypted lxc container to a different ip address. When I try to log in with my username and password nothing happens. How can I log back in?

Thank you.

**Comment by koush** [comment]
go to root https://ip:10443.

**Comment by hasrt1206** [comment]
> go to root https://ip:10443.

Pardon my ignorance. What do you mean by goin to root? I can get to Scrypted via https://<myipaddress>:10443. The problem comes when I try to log in with my default username and password, I cannot access it. The login popup stays the same and does not log me in.

**Comment by koush** [comment]
you can use the reset login instructions in the docs. I'd also verify that ip actually responds via curl. you may be seeing the browser cached pwa that works even when the site is offline.
