### ISSUE TITLE
homekit and ring

### ISSUE THREAD

**Issue by olivierjag2** [koush/scrypted#151]
hi

I have issue with ring doorbell and HomeKit, I cannot view the live stream on my home app

my setting:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/31319364/151661419-65d05f33-a39b-4245-961c-7acece61fa13.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31319364/151661423-fc5e97d4-3cbd-4469-a2a4-0305ceec3681.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31319364/151661424-da4e3cca-5087-4d7c-a753-fce1a6f38eb8.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31319364/151661431-fe65056b-3f0e-4aa4-b6c5-89ca668373c2.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31319364/151661434-a84decd4-a01d-45c6-96fb-4b39f06f6241.png">

**Comment by koush** [comment]
Please use discord, not accepting bug reports here really. just to hard to actually debug.
