### ISSUE TITLE
MAC OS Sonoma Installation failure

### ISSUE THREAD

**Issue by pmarcovici** [koush/scrypted#1529]
Running "bash ~/install-scrypted-dependencies-mac.sh" fails, it seems from the following command:   /usr/local/opt/node@20/bin/npx -y scrypted@latest install-server

This is the partial log from that command down:

Running: /usr/local/opt/node@20/bin/npx -y scrypted@latest install-server
install-server version: undefined
Node version mismatch, missing, or corrupt. Clearing node_modules.
running npm --prefix /Users/paulmarcovici/.scrypted install --production @scrypted/server@latest
npm warn config production Use `--omit=dev` instead.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm error code 1
npm error path /Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild
npm error prebuild-install warn install EACCES: permission denied, open '/Users/paulmarcovici/.npm/_prebuilds/e16aa9-node-pty-v1.0.18-node-v115-darwin-x64.tar.gz.90492-a7f53c2e9d33b.tmp'
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@20.15.1 | darwin | x64
npm error gyp info find Python using Python version 3.8.3 found at "/usr/local/bin/python3"
npm error gyp info spawn /usr/local/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/Users/paulmarcovici/.scrypted/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/paulmarcovici/.scrypted/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/paulmarcovici/Library/Caches/node-gyp/20.15.1/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/paulmarcovici/Library/Caches/node-gyp/20.15.1',
npm error gyp info spawn args '-Dnode_gyp_dir=/Users/paulmarcovici/.scrypted/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/paulmarcovici/Library/Caches/node-gyp/20.15.1/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'node-addon-api'
npm error Require stack:
npm error - /Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty/[eval]
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Module.require (node:internal/modules/cjs/loader:1233:19)
npm error     at require (node:internal/modules/helpers:179:18)
npm error     at [eval]:1:1
npm error     at runScriptInThisContext (node:internal/vm:209:10)
npm error     at node:internal/process/execution:118:14
npm error     at [eval]-wrapper:6:24
npm error     at runScript (node:internal/process/execution:101:62)
npm error     at evalScript (node:internal/process/execution:133:3) {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: [
npm error     '/Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty/[eval]'
npm error   ]
npm error }
npm error
npm error Node.js v20.15.1
npm error gyp: Call to 'node -p "require('node-addon-api').targets"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/paulmarcovici/.scrypted/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Darwin 23.5.0
npm error gyp ERR! command "/usr/local/Cellar/node@20/20.15.1/bin/node" "/Users/paulmarcovici/.scrypted/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /Users/paulmarcovici/.scrypted/node_modules/@scrypted/node-pty
npm error gyp ERR! node -v v20.15.1
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok

npm error A complete log of this run can be found in: /Users/paulmarcovici/.npm/_logs/2024-07-19T01_01_26_752Z-debug-0.log
/Users/paulmarcovici/.npm/_npx/0cd4c815eaa50473/node_modules/scrypted/dist/packages/cli/src/service.js:38
        throw new Error(`${command} exited with non zero result ${cp.exitCode}`);
              ^

Error: npm exited with non zero result 1
    at runCommand (/Users/paulmarcovici/.npm/_npx/0cd4c815eaa50473/node_modules/scrypted/dist/packages/cli/src/service.js:38:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installServe (/Users/paulmarcovici/.npm/_npx/0cd4c815eaa50473/node_modules/scrypted/dist/packages/cli/src/service.js:111:9)
    at async main (/Users/paulmarcovici/.npm/_npx/0cd4c815eaa50473/node_modules/scrypted/dist/packages/cli/src/main.js:123:28)

**Comment by koush** [comment]
Mac too old probably

**Comment by pmarcovici** [comment]
Mac mini 2018, 3 GHz 6-Core Intel Core i5, 8 GB 2667 MHz DDR4?
