### ISSUE TITLE
All cameras failed in Homekit.  Displays error "Snapshot failed" on a black screen.

### ISSUE THREAD

**Issue by dasbootbee** [koush/scrypted#1539]
# **All cameras failed in Homekit.  Displays error "Snapshot failed" on a black screen.**

### Error event in Homekit plugin:

`unhandledRejection Error: device "Unknown Device" is unavailable [id: 27] [mixin: undefined] @scrypted/prebuffer-mixin:host @scrypted/prebuffer-mixin:host main:thread host:@scrypted/prebuffer-mixin @scrypted/homekit:host`

### From the Homekit log:

```
[Driveway] Will wait for initial RTCP packet. { isHomeHub: undefined, isLowBandwidth: false, hasHomeHub: false }
[Driveway] { isLowBandwidth: false, isWatch: false, destination: 'local' }
unhandledRejection RPCResultError: device "Unknown Device" is unavailable [id: 27] [mixin: undefined]
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:377:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:37)
host:@scrypted/prebuffer-mixin
host:@scrypted/prebuffer-mixin
thread:main
@scrypted/prebuffer-mixin:host
host:@scrypted/homekit {
  cause: undefined
}
[Driveway] handleStreamRequest { sessionID: '22637fca-9829-47d3-b53f-7637d4054138', type: 'stop' }
[Driveway] streaming session killed, duration: 30s
```

### From the Snapshot Plugin Log:

```
}
[Driveway] creating error image with background Snapshot Failed false
[Patio] Snapshot failed RPCResultError: device "Unknown Device" is unavailable [id: 26] [mixin: undefined]
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:377:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:37)
host:@scrypted/prebuffer-mixin
host:@scrypted/prebuffer-mixin
thread:main
@scrypted/prebuffer-mixin:host
host:@scrypted/snapshot {
  cause: undefined
}
```

**To Reproduce**
Problem recurs approximately every 24 hours or so.

**Expected behavior**
Was working fine with no issues until the last couple of weeks.

**Server (please complete the following information):**
 - OS: Debian Bookworm
 - Docker

**Hardware Model (please complete the following information):**
 - Device: Amcrest cameras

**Client (please complete the following information, if applicable):**
 - Software: Homekit

**Additional context**
Restarting the Amcrest plugin restores functionality.

**Comment by koush** [comment]
what is device 26

**Comment by dasbootbee** [comment]
Sorry -- how do I find that?

**Comment by koush** [comment]
all devices have an id in the url bar, you can simply change the url to 26

**Comment by dasbootbee** [comment]
Device 26 is my Patio camera.

**Comment by koush** [comment]
sorry I meant device 27, can you check that

**Comment by koush** [comment]
err both devices actually

did you delete them? maybe just reboot the server. looks like something is stuck

**Comment by dasbootbee** [comment]
Thanks for the reply.  No — I haven’t changed/deleted anything.  It just started doing this within the last couple weeks.  I’ve updated my server and rebooted and it still happens.

**Comment by koush** [comment]
screenshot the extensions on a camera

**Comment by dasbootbee** [comment]
![IMG_3359](https://github.com/user-attachments/assets/76bb48fc-7922-43b1-b964-614c241933cb)

**Comment by koush** [comment]
need full camera and plugin logs.

**Comment by dasbootbee** [comment]
[amcrest-plugin.txt](https://github.com/user-attachments/files/16488700/amcrest-plugin.txt)
[camera.txt](https://github.com/user-attachments/files/16488701/camera.txt)

**Comment by dasbootbee** [comment]
I believe this was a hardware issue on the host.  For anyone running [Proxmox using an Intel NIC](https://forum.proxmox.com/threads/e1000-driver-hang.58284/page-11).

Sorry for wasting your time.  Closing for now.
