### ISSUE TITLE
Sometimes issues with livestream video

### ISSUE THREAD

**Issue by MSlawik** [koush/scrypted#154]
Somwtimes Live Video does not work and then I get these messages in the console log:
attempted to set receive buffer to size xyz but it only ended up as abc. 
It seems to be related to ffmpeg but I#m too stupid to fix it. 

its running on a raspi 4, 4 gb ram as a portainer container with ring camera. 

thx
schwiddy

**Comment by koush** [comment]
ok not taking bugs on ring right now, still work in progress.
