### ISSUE TITLE
Getting Coral USB to work

### ISSUE THREAD

**Issue by holman8a** [koush/scrypted#1548]
Hi there,

I've recently migrated from Frigate to Scrypted NVR.

On attempting to reallocate my USB Coral, I can't seem to get it to work with Tensorflow Plugin. It's showing 'Edge TPU not found'. My logs report the issue as "unable to use Coral Edge TPU Failed to load delegate from libedgetpu.so.1"

For reference, I used the guide here: https://docs.scrypted.app/installation.html#coral-drivers
I've also completed the steps on the Coral website for set up.
Coral have a walkthrough for this issue here: https://coral.ai/docs/notes/build-coral/#failed-to-load-delegate-from-libedgetpuso1
Both options seemed to work fine - however noting that after you've used the device the device ID changes to Google so the second step had a nuance.

Only other thing I can think of in my logs is the reference to /sys/bus/usb/devices/4-3 - my Coral is 004 BUS 002 DEVICE so wondering if that could be it.. but also then not sure how to fix that as I don't believe I gave that string to Scrypted.

EDIT: To add, I've attempted mounting the USB to the LXC (file and directory), and have also given the user access to plugdev. Neither have helped.

Welcome any thoughts on my next steps.. please see log below. Thanks in advance!

```
plugin version: @scrypted/tensorflow-lite 0.1.63
########################
8/11/2024, 1:52:20 PM
########################
python version: python3.9
interpreter: /usr/bin/python3.9
pip target: /root/.scrypted/volume/plugins/@scrypted/tensorflow-lite/python3.9-Linux-x86_64-20240317
requirements.txt (up to date)
--extra-index-url https://google-coral.github.io/py-repo/
# must ensure numpy is pinned to prevent dependencies with an unpinned numpy from pulling numpy>=2.0.
numpy==1.26.4
pycoral~=2.0
tflite-runtime==2.5.0.post1
Pillow==10.3.0

coral edge tpu library loaded successfully
edge tpus [{'type': 'usb', 'path': '/sys/bus/usb/devices/4-3'}]
model: ssdlite_mobiledet_coco_qat_postprocess
unable to use Coral Edge TPU Failed to load delegate from libedgetpu.so.1

model: efficientdet_lite0_320_ptq
/root/.scrypted/volume/plugins/@scrypted/tensorflow-lite/files/v13/efficientdet_lite0_320_ptq.tflite /root/.scrypted/volume/plugins/@scrypted/tensorflow-lite/files/v13/coco_labels.txt
```

**Comment by koush** [comment]
I recently did a clean install of proxmox. If you used the udev rules when prompted you don’t need to do anything further, it works out of the box. Did you add those rules during lxc install?
I’m assuming you used the inarall script from scrypted docs.

**Comment by koush** [comment]
please use discord for further help. this is the issue tracker not a support forum.
