### ISSUE TITLE
Update ring-client-api to keep up with upstream

### ISSUE THREAD

**Issue by DragonWork** [koush/scrypted#1549]
**Describe the bug**
Occasional push failures.

**To Reproduce**
Intermittently during normal operation. Might be heartbeat bug.

**Expected behavior**
Fast recovery from network outages.

**Suggestions**
Update ring-client-api to keep up with upstream or update @eneris/push-receiver to latest.

**Comment by koush** [comment]
updated push receiver. the fork is too diverged to merge with upstream and I dont really want to bother with it.
