### ISSUE TITLE
MQTT doorbell trigger

### ISSUE THREAD

**Issue by WouterJN** [koush/scrypted#156]
First of all thank you for this great project!

My smart doorbell (Ezviz DB1) doesn't have a ONVIF trigger for the doorbell. However I have the doorbell press available as status on my MQTT server. Would it be possible to trigger the doorbell signal from a MQTT status topic?

**Comment by WouterJN** [comment]
Sorry, found that this option is already available.

**Comment by fennec622** [comment]
> First of all thank you for this great project!
> 
> My smart doorbell (Ezviz DB1) doesn't have a ONVIF trigger for the doorbell. However I have the doorbell press available as status on my MQTT server. Would it be possible to trigger the doorbell signal from a MQTT status topic?

Hi I search doorbell that can use with Homekit 
HSV, button press, rtsp,  and Two way audio the more difficult I think

Ezviz DB1 can do all ?

Thanks

**Comment by WouterJN** [comment]
Ezviz DB1 doesn't have any information regarding the button press available.

**Comment by 602293544** [comment]
how do I add a mqtt doorbell?
Thanks

**Comment by fennec622** [comment]
> how do I add a mqtt doorbell?
> Thanks

https://github.com/koush/scrypted/wiki/Do-It-Yourself-Doorbell

**Comment by 602293544** [comment]
![image](https://user-images.githubusercontent.com/54359412/153711761-d277a398-42a9-4bd7-92cc-d17baf921429.png)
I'm not understand it,can you help me ?
how can I set an mqtt(BinarySensor)

**Comment by 602293544** [comment]
@WouterJN

**Comment by fennec622** [comment]
<img width="981" alt="Capture d’écran 2022-02-12 à 13 54 36" src="https://user-images.githubusercontent.com/24509422/153712222-8918b250-291f-4187-804c-fffcb9b61206.png">

**Comment by 602293544** [comment]
![O(}R3N$GO@K@HVXMJHMO4B0](https://user-images.githubusercontent.com/54359412/153734532-ae532942-5c27-4651-9ada-96790a95baba.jpg)
It's cool !
But I have another question, how to turn off after 2 seconds in code (scrypted)

![image](https://user-images.githubusercontent.com/54359412/153734630-0def81f5-8933-46ce-87bb-db2496052ebd.png)
It's nodered

**Comment by fennec622** [comment]
Just send off in Mqtt on channel doorbell

or use timeout like you want

**Comment by fennec622** [comment]
> ![image](https://user-images.githubusercontent.com/54359412/153752617-04b6f45d-9040-490a-a46e-fb1f4f5a2c01.png)
> I want to add the off's code here,but I don't know how to do
change to that 

createBinarySensor({
    topic: 'stat',
    when: ({text}) => text === '0',
    delay: 2,
})

**Comment by 602293544** [comment]
Words are powerless to express my gratitude.

👍  厉害

**Comment by latel** [comment]
> ![O(}R3N$GO@K@HVXMJHMO4B0](https://user-images.githubusercontent.com/54359412/153734532-ae532942-5c27-4651-9ada-96790a95baba.jpg) It's cool ! But I have another question, how to turn off after 2 seconds in code (scrypted)
> 
> ![image](https://user-images.githubusercontent.com/54359412/153734630-0def81f5-8933-46ce-87bb-db2496052ebd.png) It's nodered

门铃的通知里没有视频和预览图像怎么搞定呀
