### ISSUE TITLE
Scrypted produces empty backup files

### ISSUE THREAD

**Issue by darkalfx** [koush/scrypted#1560]
Describe the bug
Scrypted produces empty backup files

To Reproduce
Install the docker version of Scrypted navigate to the settings page on the web UI and make a backup

Expected behavior
The backups should contain the data.

**Comment by DMontgomery40** [comment]
i'm in proxmox with this problem as well, for quite a while, and while not the best permanent solution, for now:  just ssh in and `scp` out the `/.~scrypted/volume.db` to somewhere else, and you'll have a manual backup until this is fixed.

**Comment by koush** [comment]
This has been fixed in the upcoming release
