### ISSUE TITLE
ONVIF PTZ doesn't work for Hikvision cameras

### ISSUE THREAD

**Issue by maisun** [koush/scrypted#1567]
**Describe the bug**
ONVIF PTZ doesn't work for Hikvision PTZ cameras, it shows the PTZ control however the buttons don't work

**To Reproduce**
1. Add Hikvision camera as ONVIF camera
2. Enable PTZ
3. PTZ control is displayed with the camera view however no action when clicking on it

**Expected behavior**
PTZ button should be able to control the camera actions.

**Server (please complete the following information):**
 - OS: Docker on Linux
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Hikvision PTZ camera (DS-2CV3Q21FD-IW)

**Client (please complete the following information, if applicable):**
 - Software: Browser

**Additional context**
Hikvision doesn't seem to follow standard ONVIF PTZ protocol - I have tried the below API method which seems to work:
https://community.home-assistant.io/t/hikvision-camera-ptz-control-workaround-without-onvif/180366

It is sending HTTP Put with PTZ command:

`
rest_command:
  # pan: -100..100, tilt: -100..100, zoom: -100..100, duration: in msecs
  cam04_ptz_momentary:
    url: http://IP_OF_CAMERA/ISAPI/PTZCtrl/channels/1/Momentary
    method: PUT
    payload: '<PTZData>
              	<pan>{{ pan }}</pan>
              	<tilt>{{ tilt }}</tilt>
              	<zoom>{{ zoom }}</zoom>
              	<Momentary>
                  <duration>500</duration>
              	</Momentary>
              </PTZData>'
    username: PTZ_USER_NAME
    password: PTZ_PASSWORD
    content_type: 'application/xml'
    verify_ssl: false

  # azimuth: 0..3300, elevation: 0..900, absoluteZoom: 10..40
  cam04_ptz_absolute:
    url: http://IP_OF_CAMERA/ISAPI/PTZCtrl/channels/1/Absolute
    method: PUT
    payload: '<PTZData>
              	<AbsoluteHigh>
              	    <azimuth>{{ azimuth }}</azimuth>
              	    <elevation>{{ elevation }}</elevation>
              	    <absoluteZoom>{{ absoluteZoom }}</absoluteZoom>
              	</AbsoluteHigh>
              </PTZData>'
    username: PTZ_USER_NAME
    password: PTZ_PASSWORD
    content_type: 'application/xml'
    verify_ssl: false
`

**Comment by SunvidWong** [comment]
I also tried many ways to use PTZ, GPU, and it also cannot be used

**Comment by koush** [comment]
try using the new continuous move option

**Comment by maisun** [comment]
> try using the new continuous move option

Thanks but where can I find the new continuous move option? Just tried ONVIF PTZ and looks the same to me.

**Comment by La-te** [comment]
I'm having HiLook IPC-D640HA-LZU and the pan and tilt are not working even if configured as continuous move. Zoom works.

**Comment by cenakhoa** [comment]
After adding a camera using Hikvision plugin and configured additional PTZ. It's not working.

Then this works for me: Go to Hikvision web config interface, enable ONVIF Access, add username, password, wait for a while.
Add additional ONVIF camera using the same IP Address. Suddenly the ONVIF in the Hikvision Camera works. I delete the ONVIF camera and it's not working again. Then you can hide the ONVIF camera in your dashboard to prevent duplication, config the ONVIF camera to use less resource as possible.

cc: @koush
