### ISSUE TITLE
Fatal Syntax Error After 0.116.0 Update

### ISSUE THREAD

**Issue by benfpalmer** [koush/scrypted#1569]
**Describe the bug**
Running Scrypted as a Home Assistant Add-on for 6 months without issues, performing monthly updates alongside HA Core/OS in the last week of each month. After updating from 0.114.0 to 0.116.0 today, alongside an update from HA core 2024.7.4 to 2024.8.3, the Scrypted Add-on now fails to start with the following error in the log:

fatal error SyntaxError: Bad control character in string literal in JSON at position 5381442
    at JSON.parse (<anonymous>)
    at createLevelDocument (/server/node_modules/@scrypted/server/src/level.ts:14:29)
    at WrappedLevel.getAll (/server/node_modules/@scrypted/server/src/level.ts:54:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ScryptedRuntime.start (/server/node_modules/@scrypted/server/src/runtime.ts:975:26)
    at start (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:365:5)

/server/node_modules/@scrypted/server/src/level.ts:14
    Object.assign(doc, JSON.parse(json));

Have attempted re-starting the OS, System, etc. Next step would be to uninstall and re-install but posting issue here first in case there are other methods to resolve.

**To Reproduce**
Steps to reproduce the behaviour (*assumed; have not created a sandbox to verify just describing key environmental variables leading to issue):
1. Have Scrypted 0.114.0 installed on a system running HA Core 2024.7.4 running on a VirtualBox VM on a Windows 10 Server.
2. Update Scrypted Add-on to 0.116.0 using HA UI, then after reboot update HA Core to 2024.8.3.
3. Observe after reboot Scrypted will not start.

**Expected behaviour**
Scrypted 0.116.0 Add-on on HA Core 2024.8.3 boots and behaves the same as 0.114.0 on 2024.7.4.

**Screenshots**

**Server (please complete the following information):**
 - OS: HA Supervisor on VirtualBox VM on Windows 10 Server
 - Installation Method: Docker/HA Add-on

**Hardware Model (please complete the following information):**
 - Device: Intel i7 4790K on Asus Z87-A

**Comment by koush** [comment]
data corruption

**Comment by benfpalmer** [comment]
@koush thanks for the rapid reply. Recommending re-install in such instances?
