### ISSUE TITLE
Timezone docker container Synology

### ISSUE THREAD

**Issue by josdegroot** [koush/scrypted#157]
Is there a way to change the timezone within the docker container on a Synology NAS? I already tried to use the TZ environment variable with value Europe/Amsterdam, but in the terminal and log files the time is still one hour behind.

**Comment by koush** [comment]
Not sure, probably in the docker docs somewhere.

**Comment by josdegroot** [comment]
Here you can find the answer.. https://www.cloudsavvyit.com/12859/how-to-handle-timezones-in-docker-containers/

In all of the docker containers I use, I can simply set an TZ environment variable. Is it possible to add the tzdata file to your docker image? See the enclosed link for more information.

**Comment by koush** [comment]
this is a docker question
