### ISSUE TITLE
Cloudflare url doesn't update in Scrypted cloud

### ISSUE THREAD

**Issue by Ixian** [koush/scrypted#1576]
The url for the cloudflare tunnel changed but home.scrypted.app still uses the previous url and therefore doesn't connect. I can connect to the (new) url directly, it works, just not updated for the cloud. 

This affects browser logins as well as the mobile app. In the latter case, there's no option to change the url so the app is de facto broken for me right now. 

No amount of plugin restarts, container restarts, deleting and re-registering, or logging out and back in has solved this.

**Comment by koush** [comment]
Can you remove the server from home.scrypted.app and then reregister it?

**Comment by Ixian** [comment]
After removing it and re-registering it eventually updated the url but took about 30m, FYI

**Comment by Ixian** [comment]
The url changed and it happened again. If there is a function that updates Scrypted Cloud with cloud flare tunnel addresses it isn't working.

**Comment by Ixian** [comment]
Adding to this - if I go to settings>versions and manually tap reload it picks up the new url.

**Comment by koush** [comment]
I think there were some client caching issues causing this that may have resolved this. let me know if you can still repro.
