### ISSUE TITLE
Onvif Plugin: Version Upgrade to at least 0.7.1 where HTTPS is enabled

### ISSUE THREAD

**Issue by jviets** [koush/scrypted#1579]
For my scrypted setup I need the possibility to use HTTPS Onvif setup.
Please upgrade the Onvif node.js implementation to at least 0.7.1 in order to enable this functionality:
https://github.com/agsh/onvif/releases/tag/v0.7.1

Thank you so much!

**Comment by jviets** [comment]
I have already prepared the upgrade to 0.7.4 via PR:
https://github.com/koush/onvif/pull/1

**Comment by koush** [comment]
done

**Comment by jviets** [comment]
Thank you! :)
