### ISSUE TITLE
NVR - Multi-server breaks notifications

### ISSUE THREAD

**Issue by Ixian** [koush/scrypted#1583]
**Describe the bug**

When two or more servers are configured in Scrypted Cloud or the mobile app (I am using the ios version) notifications work and show the correct thumbnail, however clicking the thumbnail brings up an error message about missing recordings. This happens if the notification comes in from the server that was not selected last in the app/cloud.

**To Reproduce**
1. Configure two Scrypted NVR servers in the mobile app
2. Enable notifications
3. Trigger a notification on a specific server. On selecting the notification, if the server that generated it was the last picked in the app, it will work. If the app does not have that server selected it breaks.
**Expected behavior**
Since the notification itself comes from the correct server, with thumbnail, when opening the notification auto-switch the app to the correct server. 

Thank you!

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Installation Method: [e.g. Desktop App, Docker, Local]

**Hardware Model (please complete the following information):**
 - Device: [e.g. Amcrest]

**Client (please complete the following information, if applicable):**
 - Software: [e.g. Home app, NVR app, Alexa, Browser]

**Additional context**

**Comment by koush** [comment]
fixed with latest cloud and nvr releases.
