### ISSUE TITLE
Ring Doorbell stucks in ringing state forever

### ISSUE THREAD

**Issue by zek** [koush/scrypted#1584]
**Describe the bug**
When the Ring doorbell is pressed, it gets stuck in the ringing state for hours or even days. During this time, the doorbell cannot be rung again, and it does not detect any motion events

**To Reproduce**

1. Press the Ring doorbell to trigger a ring event.
2. Observe that the doorbell remains stuck in the "ringing" state indefinitely.
3. Try to ring the doorbell again, which does not work.
4. Notice that no motion events are detected while the doorbell is stuck.

**Expected behavior**
I expect the doorbell to return to its normal state after ringing (resetting its state after x seconds), allowing it to detect further rings and motion events without becoming unresponsive.

**Screenshots**

![image](https://github.com/user-attachments/assets/109e527b-8390-464c-9820-953c3fbc34c9)
![image](https://github.com/user-attachments/assets/ecac0841-2167-4023-a086-5754cffba281)
![image](https://github.com/user-attachments/assets/e2357df6-119b-41a2-9af1-d6c8268a108e)

**Server (please complete the following information):**
Synology Docker

**Hardware Model (please complete the following information):**
 - Device: Ring Doorbell pro 2

**Client (please complete the following information, if applicable):**
 - Software: Scrypted NVR

**Comment by tealtwo** [comment]
![IMG_0059](https://github.com/user-attachments/assets/595b400b-b4c9-45d4-a262-857647bfdc3d)
constructor(public api: RingBaseApi, nativeId: string, camera: RingCamera) {
        super(nativeId);
        this.camera = camera;
        this.motionDetected = false;
        this.binaryState = false;
        if (this.interfaces.includes(ScryptedInterface.Battery))
            this.batteryLevel = this.camera.batteryLevel;

        camera.onDoorbellPressed?.subscribe(async e => {
            this.console.log(camera.name, 'onDoorbellPressed', e);
            this.triggerBinaryState();
        });
        camera.onDoorbellPressedPolling.subscribe(async e => {
            this.console.log(camera.name, 'onDoorbellPressed', e);
            this.triggerBinaryState();
        });
        let motionTimeout: NodeJS.Timeout;
        const resetTimeout = () => {
            clearTimeout(motionTimeout);
            motionTimeout = setTimeout(() => this.motionDetected = false, 30000);
        };
        


Seems this bit of code isn’t timing out the doorbell press….

**Comment by zek** [comment]
I would expect restarting Scrypted to reset the state but that also not working. It has been 1d5h32m I couldn't reset it yet.

**Comment by koush** [comment]
ring plugin was updated with new push receiver. there's no support for cloud cameras in scrypted nvr as noted in the documentation and nvr plugin readme.
