### ISSUE TITLE
Error When Adding AXIS ONVIF Doorbell Camera

### ISSUE THREAD

**Issue by digitalentropy** [koush/scrypted#1585]
**Describe the bug**
Trying to add a new AXIS I8116-E Network Video Intercom using ONVIF plugin, and have had nothing but issues. It's unclear based on error messages if the issue is due to a camera configuration issue or a plugin issue.

**To Reproduce**
1. Factory-reset I8116-E Intercom (Running 11.11.79)
2. Create ONVIF User
3. Discover camera using ONVIF discovery OR add IP manually.
4. Enter ONVIF Username and Password
5. Click "Add"
6. Device add fails with the following error:
Error: Wrong `SetVideoEncoderConfiguration` responseError: Wrong `SetVideoEncoderConfiguration` responseError: Wrong `SetVideoEncoderConfiguration` response host:@scrypted/onvif engine.io-client:api

**Expected behavior**
I expect the camera to be successfully added but it just fails. Regular HA Axis plugin seems to connect to the camera and stream fine. HA ONVIF plugin seems to connect fine as well.

**Screenshots**
![image](https://github.com/user-attachments/assets/6fb31718-ec7a-40b0-8400-ae7c613d3e68)

**Server (please complete the following information):**
 - OS: HASSOS

**Hardware Model (please complete the following information):**
 - Device: HA Yellow
 - 
**Client (please complete the following information, if applicable):**
 - Software: Browser

**Additional context**
Currently running Scrypted v0.118.0

**Comment by DMontgomery40** [comment]
All Axis cams require you to set up your own streams; Axis calls the streams "ONVIF Media Profiles."  You will have a stream by default; it's likely called profile_1_h264 or something similar.  You also likely have an MJPEG stream.  Follow the docs to create three streams, and note that "GOP"/"GOV" is a bit different from "keyframe interval"/"IDR." For example, if your frame rate is 30, GOP should be set at 120. (`frame rate` X `4`)
