### ISSUE TITLE
RTSP Plugin Crash: Uncaught TypeError

### ISSUE THREAD

**Issue by wajonespress** [koush/scrypted#1590]
**Describe the bug**
I'm trying to stream four Dahua IP cameras via a Dahua NVR over RTSP, but after 10-30mins I am consistently getting simultaneous stream dropouts on all four devices. I am then unable to stream any camera, either inside Scrypted or through external clients like HomeKit, until I manually reload the RTSP Camera plugin. RTSP streams remain online and stable in VLC. These dropouts always coincide with an uncaught exception error in the Scrypted Core log, specifically a `TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')`.

**To Reproduce**
1. Stream four Dahua IP cameras via an NVR over RTSP in Scrypted.
2. Observe that, after some time, all four streams will drop simultaneously.
3. Review the Scrypted Core logs for the uncaught exception error `TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')`.

**Expected behavior**
RTSP streams should remain stable, and the RTSP plugin should successfully restart automatically.

**Server (please complete the following information):**
- OS: macOS 14.6 (M2 Mac mini)
- Installation Method: Terminal (via Homebrew)

**Hardware Model (please complete the following information):**
 - Device: Dahua NVR and IP cameras

**Client (please complete the following information, if applicable):**
 - Software: HomeKit, Dahua NVR

**Additional context**
The type error causes a crash-restart cycle, with each restart attempt resulting in the same TypeError, leaving all camera streams unavailable, both in Scrypted and external clients like HomeKit, until the RTSP plugin is manually reloaded.
```
########################
9/25/2024, 3:30:00 PM
########################
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
```

**Comment by koush** [comment]
You’re using a script that is causing this.

**Comment by wajonespress** [comment]
I've deleted the script but the dropouts continue.

The dropouts actually predate the bad script, which was designed to manually force the RTSP plugin to reload periodically to save me having to go in and manually restart the RTSP plugin every time there was a dropout.

Basically I've been unable to get Scrypted to function normally for longer than an hour since setting this up a week ago. Apologies for the bad issue report, but I'm at a total loss as to why this keeps happening.

`########################
9/25/2024, 5:00:00 PM
########################
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
uncaughtException TypeError: Cannot read properties of undefined (reading '@scrypted/rtsp')
    at Timeout.restartPlugin [as _onTimeout] (script.js:7:86)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)`

**Comment by wajonespress** [comment]
I'm so sorry @koush, I know I created this issue with incorrect information, but I really need help solving these dropouts without posting a new Issue for the RPC disconnect error.

I've been problem solving for over a week, and every time they cutout my insurance is voided.

And I can't find anything on the internet about people getting this undefined RPC error inside Scrypted, and I can't see anything in my setup that looks out of the ordinary. Please help.

**Comment by wajonespress** [comment]
Other possible causes of the dropouts:

1. `[Rebroadcast Plugin]: more than 100MB has been buffered, did downstream die? killing connection. Stream 2`

2. `[rtsp @ 0x123e04c20] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly`

Please forgive my ignorance.
