### ISSUE TITLE
malformed login result anytime I try and install a module

### ISSUE THREAD

**Issue by ybizeul** [koush/scrypted#1592]
**Describe the bug**
Brand new install of Scrypted, getting an error when installing plugins

**To Reproduce**
1. Log into Scrypted
2. Go To Plugins
3. Click on "Install"
4. Type Homekit
5. Click Install

**Expected behavior**
Module should install

**Screenshots**
![image](https://github.com/user-attachments/assets/3768456a-27e2-4076-944d-438375c76d0f)

**Server (please complete the following information):**
 - OS: Ubuntu bookworm/sid
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device:  Raspberry pi 4

**Comment by koush** [comment]
Network issue on your end.
