### ISSUE TITLE
Recurring dropouts and RPC disconnect errors

### ISSUE THREAD

**Issue by wajonespress** [koush/scrypted#1593]
**Describe the bug**
I'm have four IP cameras streaming RTSP via an NVR, but after about 30-90mins I am consistently getting simultaneous stream dropouts on all four devices. I am then unable to stream any camera, either inside Scrypted or through downstream clients like HomeKit, until I manually restart the RTSP Camera plugin inside Scrypted.

RTSP streams remain online and stable in VLC.

These dropouts always coincide with `RPCResultError: connection closed.`, `RpcPeer.kill`, `cause: undefined`. Unclear if these are a cause or symptom.

**To Reproduce**
1. Add RTSP streams from four Dahua IP cameras.
2. Configure into device group (Camera + MotionSensor + VideoCamera)
3. Bridge to HomeKit as Standalone Accessory
4. Observe that, after some time, all four streams will drop simultaneously.

**Expected behavior**
RTSP streams should remain stable

**Server:**
OS: macOS 14.6 (M2 Mac mini)
Installation Method: Terminal (via Homebrew)

**Hardware Model:**
> **Dahua NVR**
Device Model: DHI-NVR4104HS-P-4KS2-0TB
System Version: V4.000.0000001.4, Build Date: 2019-11-29
Onvif Server Version: 18.12(V2.4.5.752813)
Onvif Version: V2.4.1

> **Dahua IP cameras**
Device Model: IPC-HDW4631EM-ASE

**Client:**
HomeKit

**Additional context:**
```
########################
9/25/2024, 5:32:03 PM
########################
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:49285
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}
```
…And then again after restarting RTSP Camera plugin
```
########################
9/25/2024, 9:24:30 PM
########################
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:50210
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}
```
...And yet again after RTSP plugin restart
```
########################
9/25/2024, 11:48:24 PM
########################
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:51267
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}
```
All subsequent attempts by all plugins to access any RTSP streams fail, citing the RCP result error.
```
########################
9/26/2024, 9:48:19 AM
########################
[Video Analysis Plugin]: Video Analysis motion detection session f73a4d22 started.
[Video Analysis Plugin]: Gstreamer + OpenCV Motion Detection
[Rebroadcast Plugin]: Stream 2 active rebroadcast clients: 1
[Rebroadcast Plugin]: Stream 2 active rebroadcast clients: 0
[Video Analysis Plugin]: Video Analysis ended with error [Traceback (most recent call last):
[Video Analysis Plugin]:   File "/Users/warwickjones/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 448, in handleMessage
[Video Analysis Plugin]:     value = await maybe_await(invoke(*args))
[Video Analysis Plugin]:   File "/Users/warwickjones/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 20, in maybe_await
[Video Analysis Plugin]:     return await value
[Video Analysis Plugin]:   File "/Users/warwickjones/.scrypted/volume/plugins/@scrypted/opencv/zip/unzipped/detect/__init__.py", line 57, in generateObjectDetections
[Video Analysis Plugin]:     async for videoFrame in videoFrames:
[Video Analysis Plugin]:   File "/Users/warwickjones/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 77, in __anext__
[Video Analysis Plugin]:     return await RpcProxyMethod(self, self.__dict__[RpcPeer.PROPERTY_PROXY_PROPERTIES]['Symbol(Symbol.asyncIterator)']['next'])()
[Video Analysis Plugin]:   File "/Users/warwickjones/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 505, in createPendingResult
[Video Analysis Plugin]:     return await future
[Video Analysis Plugin]: rpc.RPCResultError: (None, 'peer was killed')
[Video Analysis Plugin]: 
[Video Analysis Plugin]: 127.0.0.1:49201:@scrypted/objectdetector] {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: Video Analysis motion detection session f73a4d22 ended.
```
Very occasionally, I also get these errors:

- `[Rebroadcast Plugin]: more than 100MB has been buffered, did downstream die? killing connection. Stream 2`
- `[rtsp @ 0x123e04c20] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly`
- `[Video Analysis Plugin]: [swscaler @ 0x1405b0000] deprecated pixel format used, make sure you did set range correctly`
- `[Rebroadcast Plugin]: rebroadcast parse error Error: RTSP Server expected frame magic but received: TEAR`
- `[HomeKit]: motion recording closed (error code: 6) /////// [HomeKit]: homekit secure video max duration reached`

**Troubleshooting so far:**

1. Set IP address manually
2. Reduced bitrate
3. Switched to FFmpeg (for RTSP parser, OpenCV, and HomeKit RTP Sender in varying combinations)
4. Increased -analyzeduration and -probesize (to varying levels)
5. Locked HomeKit Hub to single ATV with excellent connection
6. Updated all HomeHub firmware
7. Uninstalled and reinstalled RTSP plugin, and tried rolling back through multiple versions.
8. Rebooted server, router, and NVR.
9. Tried to automate RTSP Camera plugin restart using a script which did not work, as per [last issue report](https://github.com/koush/scrypted/issues/1590).

**Comment by koush** [comment]
Connect to cams directly

**Comment by wajonespress** [comment]
An electrician just told me it's going to be way too expensive to run an ethernet cable to my NVR.

Would using a PoE switch instead of the NVR solve the problem?
