### ISSUE TITLE
Google Device Access - Error retrieving Cloud Endpoint 

### ISSUE THREAD

**Issue by tanmaygarg** [koush/scrypted#1594]
**Describe the bug**

Google Device Access

After following the steps to configure the plugin, the PubSub address to enter in Google Cloud Project is not populated.

Error - "Error retrieving Cloud Endpoint". This is resulting in the events not getting pushed like doorbell or any motion event for the cameras.

Also, the snapshot stops working after a couple of hours with the error "Snapshot failed".

A clear and concise description of what the bug is. The issue tracker is only for reporting bugs in Scrypted, for general support check Discord. Hardrware support requests or assistance requests will be immediately closed.

Logs:

[Snapshot Plugin]: Snapshot failed RPCResultError: snapshot unavailable
[Snapshot Plugin]:     at O.takePicture (/src/main.ts:264:15)
[Snapshot Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:744:37)
[Snapshot Plugin]: @scrypted/google-device-access:host
[Snapshot Plugin]: host:@scrypted/snapshot {
[Snapshot Plugin]:   cause: undefined
[Snapshot Plugin]: }
[Snapshot Plugin]: creating error image with background Snapshot Failed true

**To Reproduce**
1. Go to 'Google Device Access'
2. Click on general section under settings
3. PubSub input field has the error for newly configured plugins

**Screenshots**
![image](https://github.com/user-attachments/assets/ff860261-9046-4b0c-9bac-c331dbeca312)

![image](https://github.com/user-attachments/assets/e74e166e-168b-4f7d-93b9-f550dfd29f2d)

**Server (please complete the following information):**
 - OS: Raspbian Lite 64 bit
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Raspberry Pi 4

**Comment by koush** [comment]
fixed

**Comment by tanmaygarg** [comment]
Thank you. The PubSub issue is fixed. However, I still get the Snapshot failed error after a couple of hours and have to restart the plugin for it to go away. 

I was thinking if you can help me with setting up an automation to restart on this error, that should fix this. 

Again, thank you for all the help.
