### ISSUE TITLE
Error adding Reolink Video Doorbell WiFi using ONVIF

### ISSUE THREAD

**Issue by drichfsu** [koush/scrypted#1599]
**Describe the bug**
When adding my Reolink Video Doorbell WiFi camera to Scrypted, I receive the following error...

> Error: Wrong `SetAudioEncoderConfiguration` responseError: Wrong `SetAudioEncoderConfiguration` response host:@scrypted/onvif engine.io-client:api

<img width="1343" alt="Screenshot 2024-10-05 at 9 54 15 AM" src="https://github.com/user-attachments/assets/910ceefa-d91c-40b2-b130-6cbb39b19d0d">

This functionality was working before, but I had to replace the camera due to a hardware issue on the previous camera. The camera network settings have been validated, see attachement. 

<img width="714" alt="Screenshot 2024-10-05 at 10 00 16 AM" src="https://github.com/user-attachments/assets/adce4b70-3b25-4ea0-a193-deff6d00a0b8">

**To Reproduce**
1. Go to 'Devices'
2. Click 'ADD DEVICE'
3. Under 'Device Type' scroll down to 'ONVIF Camera'
4. Complete the appropriate 'Username', 'Password', and 'IP Address'
5. Click 'ADD'
6. See error

> Error: Wrong `SetAudioEncoderConfiguration` responseError: Wrong `SetAudioEncoderConfiguration` response host:@scrypted/onvif engine.io-client:api

**Expected behavior**
In the past when I've gone through this setup method, the camera was added with no issue

**Screenshots**
Screenshots added above in the description

**Server (please complete the following information):**
 - OS: Home Assistant OS 
 - Core: 2024.10.1
 - Supervisor: 2024.09.1
 - Operating System: 13.1
 - Frontend: 20241002.2
 - Installation Method: Local
 - Scrypted Add On: v0.118.0

**Hardware Model (please complete the following information):**
 - Device: Raspberry Pi 4 - 4GB [rpi4-64]
 - Device: Reolink Video Doorbell WiFi 
 - Build No: build 2407315182
 - Hardware No: DB_566128M5MP_W
 - Config Version: v3.0.0.0
 - Firmware Version: v3.0.0.3308_2407315182

**Client (please complete the following information, if applicable):**
 - Software: Browser [Chrome]

**Additional context**
Just to do some additional testing, I attempted to add a separate working device (Reolink E1) again, and received the same error. This E1 camera is currently running with no issues in Scrypted currently. Lastly, I installed the Reolink plugin to add the camera this way, and everything apears to be working, but this isn't really my preferred installation method.

**Comment by koush** [comment]
Disable auto config.
