### ISSUE TITLE
No video from Amcrest Camera

### ISSUE THREAD

**Issue by mjakefranklin** [koush/scrypted#16]
I've installed Scrypted in a Docker container, and I can log in just fine.  Plugins for Amcrest, HomeKit, and prebuffer-mixin were installed.

After adding a camera to the Amcrest plugin, I get no image or video in Scrypted.  The camera is on the network and reachable, and I can connect to it using the credentials that I've provided to Scrypted.  I've also gotten it working successfully in Home Assistant, using both the Amcrest integration and Falcon.

This is the only error I see in the log:

`6:32:26 AM | e | Amcrest Camera Controller | uncaughtException TypeError: Cannot read properties of undefined (reading '1')Amcrest Camera Controller
`

Let me know what else I can provide, and thanks for the help!

**Comment by dibble9012** [comment]
I have this as well

**Comment by dibble9012** [comment]
I am running 16.9.1

**Comment by mjakefranklin** [comment]
> > I have this as well. I have video, but secure video does not work (the entire scrypted server crashes)
> 
> install node 16

This won't help me since I'm using the docker container right?  I could try a plain node install.  Interestingly, I also just tried the RTSP plugin, and it appears to work fine

**Comment by dibble9012** [comment]
Troubleshooting a bit more, it seems to start throwing errors when I just view the page that the camera is on in HomeKit (i.e. it's trying to get the screen grab for the camera in HomeKit).

event listener failure TypeError: Cannot read properties of undefined (reading '1')
    at t.default.request (/plugin/main.nodejs.js:6:13145)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.AmcrestCameraClient.listenEvents (/plugin/main.nodejs.js:6:11990)
    at createMotionStream (/plugin/main.nodejs.js:6:1645)
failure getData TypeError: Cannot read properties of undefined (reading '1')
    at t.default.request (/plugin/main.nodejs.js:6:13145)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.AmcrestCameraClient.jpegSnapshot (/plugin/main.nodejs.js:6:11815)
    at RpcPeer.handleMessage (/root/scrypted/server/src/rpc.ts:402:37)
failure getData RPCResultError [TypeError]: Cannot read properties of undefined (reading '1')
    at t.default.request (/plugin/main.nodejs.js:6:13145)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.AmcrestCameraClient.jpegSnapshot (/plugin/main.nodejs.js:6:11815)
    at RpcPeer.handleMessage (/root/scrypted/server/src/rpc.ts:402:37) {
  cause: undefined
}

**Comment by koush** [comment]
> > > I have this as well. I have video, but secure video does not work (the entire scrypted server crashes)
> > 
> > 
> > install node 16
> 
> This won't help me since I'm using the docker container right? I could try a plain node install. Interestingly, I also just tried the RTSP plugin, and it appears to work fine

ah you're correct. I've only seen crashes on pre node-16. get me a crash log please.

**Comment by mjakefranklin** [comment]
> > > > I have this as well. I have video, but secure video does not work (the entire scrypted server crashes)
> > > 
> > > 
> > > install node 16
> > 
> > 
> > This won't help me since I'm using the docker container right? I could try a plain node install. Interestingly, I also just tried the RTSP plugin, and it appears to work fine
> 
> ah you're correct. I've only seen crashes on pre node-16. get me a crash log please.

Is getting crash log documented?  Thanks again for the help

**Comment by koush** [comment]
You said that the whole scrypted server crashed, so I assume you have a crash dump in teh console you're running it in (docker, or via checkout)

**Comment by mjakefranklin** [comment]
No, unfortunately that was the other user that jumped on this issue thread.  It doesn't crash at all.  Video just doesn't show up

**Comment by koush** [comment]
This should be fixed in the latest plugin update, please confirm.

**Comment by mjakefranklin** [comment]
> This should be fixed in the latest plugin update, please confirm.

@koush it works amazingly well now, thanks so much.  HKSV works, as well as motion detection (tested person and car), recording works great, motion sensor works, notifications work.

Thanks again!
