### ISSUE TITLE
Cannot start Scypted on Docker Error 134 (core) 

### ISSUE THREAD

**Issue by brendan-Tas** [koush/scrypted#160]
I have scyrpted installed on docker on RP4b, but it fails on startup.  I'm getting the following being thrown at docker-compose-up.
Homebridge on the same docker config YAML, but that's running fine.
```

scrypted      | Node.js[8]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
scrypted      | Aborted (core dumped)
scrypted exited with code 134
```
Any advice appreciated. 
Thanks

**Comment by koush** [comment]
update to bullseye.

**Comment by koush** [comment]
and yes, I'm aware it's inside docker!

**Comment by brendan-Tas** [comment]
Thanks Koush. Have been avoiding doing that, but I'll bite the bullet!

**Comment by brendan-Tas** [comment]
That worked, thank you Koush. Sorry if I missed it in the documentation.  Awesome project, ta.
