### ISSUE TITLE
Packet Loss on Homekit - Google Home works fine

### ISSUE THREAD

**Issue by clw123456** [koush/scrypted#1612]
Hi,
Hope you're all good. Any tips for solving my packet loss issue for Unifi Cameras on Homekit? I include the logs below.

Been battling this one for a few hours now, I just get lots of packet loss when the stream tries to start. Google Home integration works fine however.

This is all local streaming for now.

Thanks :)

[HomeKit]: HomeKit Connection 192.168.1.30
[HomeKit]: HomeKit Connection 192.168.1.54
[HomeKit]: HomeKit Connection 192.168.1.54
[HomeKit]: Device is in accessory mode and is online. HomeKit services are being published.
[HomeKit]: HomeKit Connection 192.168.1.54
[HomeKit]: HomeKit Connection 192.168.1.88
[HomeKit]: HomeKit Connection 192.168.1.62
[HomeKit]: addresses {
[HomeKit]:   sourceAddress: '192.168.1.48',
[HomeKit]:   sourceVideoPort: 33946,
[HomeKit]:   sourceAudioPort: 42077,
[HomeKit]:   targetAddress: '192.168.1.54',
[HomeKit]:   targetVidioPort: 61511,
[HomeKit]:   targetAudioPort: 56404
[HomeKit]: }
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: '6fa9d623-3988-45d4-9f09-5068bf45d955',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 4026732591,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 2196774006,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: Will wait for initial RTCP packet. { isHomeHub: undefined, isLowBandwidth: false, hasHomeHub: false }
[HomeKit]: { isLowBandwidth: false, isWatch: false, destination: 'local' }
[HomeKit]: { tool: 'scrypted', rtpSender: 'Default' }
[HomeKit]: Waiting for video RTCP packet before sending video.
[HomeKit]: packet loss 1
[HomeKit]: Received first video RTCP packet.
[HomeKit]: a/v h264 opus found h264 opus
[Rebroadcast Plugin]: High active rebroadcast clients: 1
[Rebroadcast Plugin]: Unable to find sync frame in rtsp prebuffer.
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 28 1
[HomeKit]: received first audio packet
[HomeKit]: packet loss 28
[HomeKit]: packet loss 39
[HomeKit]: scanning for idr start found: 28 1 24 7 8
[HomeKit]: idr start found: 28 5
[HomeKit]: packet loss 45
[HomeKit]: packet loss 546
[HomeKit]: packet loss 664
[HomeKit]: packet loss 677
[HomeKit]: packet loss 680
[HomeKit]: packet loss 690
[HomeKit]: packet loss 698
[HomeKit]: packet loss 707
[HomeKit]: packet loss 727
[HomeKit]: packet loss 757
[HomeKit]: packet loss 786
[HomeKit]: packet loss 796
[HomeKit]: packet loss 819
[HomeKit]: packet loss 843
[HomeKit]: packet loss 850
[HomeKit]: packet loss 862
[HomeKit]: packet loss 885
[HomeKit]: packet loss 909
[HomeKit]: packet loss 915
[HomeKit]: packet loss 1701
[HomeKit]: packet loss 1720
[HomeKit]: packet loss 1751
[HomeKit]: packet loss 1768
[HomeKit]: packet loss 1778
[HomeKit]: packet loss 1817
[HomeKit]: packet loss 1850
[HomeKit]: handleStreamRequest { sessionID: '6fa9d623-3988-45d4-9f09-5068bf45d955', type: 'stop' }
[HomeKit]: streaming session killed, duration: 9s
[Rebroadcast Plugin]: High active rebroadcast clients: 0

**Comment by clw123456** [comment]
Cameras still don't load from other devices on the network however, nor on cellular.

**Comment by itatboy** [comment]
I also encountered a lot of [HomeKit]: packet loss


Who can tell me how this issue is progressing? I haven't seen any tracking information and don't think this issue needs to be closed
