### ISSUE TITLE
No HSV record when close and reopen RTSP camera 

### ISSUE THREAD

**Issue by fennec622** [koush/scrypted#162]
Hi

I use HSV record and all is ok

When I restart camera I close and I restart rtsp, in scrypted all is ok screenshot video except record for camera restarting 

I must restart Homekit scrypted for have record ok

I'm alone ? 

Thanks

**Comment by donavanbecker** [comment]
@fennec622 Motion is required for recording, just viewing the camera will not trigger recording.

**Comment by fennec622** [comment]
Yes I know I have MQTT motion

When I start scripted all is ok live record and snap

If i restart one camera1 rtsp stop and start 

On scrypted just for this camera1 live ok snap ok but never record
Another camera2 that not restart at the same time when motion record is ok 

I must restart HomeKit or wait several minute for camera1 can record

I thinks when scrypted lost rtsp for very short time, scrypted don't restart something and can't record

**Comment by koush** [comment]
> When I restart camera

You're saying it stops recording if you restart your camera? Like power cycle it?

**Comment by fennec622** [comment]
> > When I restart camera
> 
> You're saying it stops recording if you restart your camera? Like power cycle it?

I use Zoneminder to save and motion alert with opencv

Zoneminder have RTSPserver for reshare camera with fifo file

You have differents mode of analyse 
Record ( without motion alert ) or Mocord ( motion alert )

When i leave my home camera go in Mocord mode and when I come back go in record mode

Switch mode take less than 2s 

After each change mode I lost only record, live ok 

since yesterday I try to no change mode when I leave home  and all is ok live and record 

So I think Scrypted don't see the change mode

**Comment by fennec622** [comment]
> think this was fixed

Yes i think thanks
