### ISSUE TITLE
Snapshots failing for google cams. Works for some time when restarting the plugin

### ISSUE THREAD

**Issue by tanmaygarg** [koush/scrypted#1623]
Snapshots failing for google cams. Works for some time when restarting the plugin.

Logs:

[Snapshot Plugin]: Snapshot failed RPCResultError: snapshot unavailable
[Snapshot Plugin]:     at T.takePicture (/src/main.ts:264:15)
[Snapshot Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:744:37)
[Snapshot Plugin]: @scrypted/google-device-access:host
[Snapshot Plugin]: host:@scrypted/snapshot {
[Snapshot Plugin]:   cause: undefined
[Snapshot Plugin]: }
[Snapshot Plugin]: creating error image with background Snapshot Failed true
[Snapshot Plugin]: Snapshot failed RPCResultError: snapshot unavailable
[Snapshot Plugin]:     at T.takePicture (/src/main.ts:264:15)
[Snapshot Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:744:37)
[Snapshot Plugin]: @scrypted/google-device-access:host
[Snapshot Plugin]: host:@scrypted/snapshot {
[Snapshot Plugin]:   cause: undefined
[Snapshot Plugin]: }
[Snapshot Plugin]: creating error image with background Snapshot Failed true
########################
10/21/2024, 1:21:54 PM
########################
[HomeKit]: HomeKit Connection 192.168.1.69
[Snapshot Plugin]: Snapshot failed RPCResultError: snapshot unavailable

![image](https://github.com/user-attachments/assets/d34dc2fe-98d5-48b8-b3b8-d8fb554999ab)

**Comment by koush** [comment]
google cams dont provide snapshots without a pre buffer.
