### ISSUE TITLE
Black snapshots/thumbnails several times a day

### ISSUE THREAD

**Issue by kersten-lohmeyer** [koush/scrypted#1627]
- [X] I have searched the issue tracker for an existing issue.

**Describe the bug**
Several times a day I have black snapshot/thumbnails of motion events. Videos play back fine though.

**To Reproduce**
Walk by your camera and have a motion recorded.

**Expected behavior**
A picture of the motion event that is not black.

**Screenshots**
<img width="418" alt="Bildschirmfoto 2024-10-26 um 18 37 10" src="https://github.com/user-attachments/assets/876e08ba-19e9-430c-a3c9-1b60f053b1a3">
Btw. this also happens in daylight.

**Server (please complete the following information):**
 - OS: Your Proxmox container
 - Installation Method: Proxmox

**Hardware Model (please complete the following information):**
 - Device: Zotac CI669, UniFi G4 Instant

**Client (please complete the following information, if applicable):**
 - Software: These black snapshot/thumbnails show up in the HA component as well as in the NVR on port 10443.

**Additional context**
I got only one camera so far. The VM is boring itself to death considering RAM and CPU usage. Funny thing is there's an event picture and a timeline picture. It's just black in the HA component's last motion events and in the scrypted events on the dashboard. Is this a bug or can I tune something to get rid of this?

**Comment by kersten-lohmeyer** [comment]
I changed cam settings (prebuffered streams) from "High and Medium" to "Medium and Low" and now I did not have any black thumbnails for two days now. Does that have anything to do with it at all?

**Comment by koush** [comment]
That setting would have no effect. All streams are being recorded/prebuffered regardless.

**Comment by koush** [comment]
realized where/how event thumbnails are saved was changed a few days ago, and this may have resolved it,

**Comment by kersten-lohmeyer** [comment]
It's not happening anymore for a few days now. So it seems to be fixed.
Thanks a lot!

**Comment by kersten-lohmeyer** [comment]
Guess I was a bit too fast there, but this was the first time since a few
days.
