### ISSUE TITLE
Packet loss in Firefox but not in Chrome?

### ISSUE THREAD

**Issue by kersten-lohmeyer** [koush/scrypted#1634]
**Describe the bug**
When viewing motion recordings in the HA integration in (current) Firefox I have extreme packet loss and the videos won't start to play. But it works flawlessly on (current) Chrome on the same machine. Live video works in Firefox though.

**To Reproduce**
Watch motion recordings in Firefox and Chrome.

**Expected behavior**
Firefox to be able to play motion recordings without packet loss like Chrome does.

**Screenshots**
Firefox:
<img width="406" alt="grafik" src="https://github.com/user-attachments/assets/a543cab0-eded-432f-8c41-1f04c8012560">

Chrome:
<img width="482" alt="grafik" src="https://github.com/user-attachments/assets/f446f986-448c-4bf2-ae9f-87a52ec8acfe">

**Server (please complete the following information):**
 - OS: Official Proxmox container
 - Installation Method: Proxmox

**Hardware Model (please complete the following information):**
 - Device: Zotac I669, UniFi G4 Instant

**Client (please complete the following information, if applicable):**
 - Software: Home Assistant Integration

**Additional context**
When viewing recordings via xxx:10443 Firefox works, it's just not working via the HA integration. In Chrome both ways work.

**Comment by koush** [comment]
This is not a bug, this is an issue with your network and/or browser. You'll need to figure out what the issue is. No issues with Firefox here.
