### ISSUE TITLE
Dummy switch behavior on startup

### ISSUE THREAD

**Issue by victorlin** [koush/scrypted#1636]
I have a dummy switch that I would like to always report motion for a HomeKit Secure Video setup. Setting "Reset Sensor" to 0 accomplishes that for the most part. The only problem is, upon restart of Scrypted, the switch initializes to an "on" state without reporting motion until it is toggled off then on again.

Is there any way to have the dummy switch report motion upon startup?

Here is a screen capture after starting Scrypted:

https://github.com/user-attachments/assets/5def9f3e-1724-486e-899f-d9f9fea71125

**Comment by koush** [comment]
probably want to use an automation

**Comment by victorlin** [comment]
I found the source of this behavior: https://github.com/koush/scrypted/blob/49a567fb51c158803726f86da4e59f23ea3158ee/plugins/dummy-switch/src/main.ts#L14-L19

I downgraded Dummy Switch Plugin to v0.0.10 which sets `motionDetected` conditionally: https://github.com/koush/scrypted/blob/8c9a7a026df4773348a68d93c715e574ad4d61f6/plugins/dummy-switch/src/main.ts#L20-L22

It now works the way I want. Would you consider restoring the conditions on `motionDetected`, `binaryState`, and `occupied` instead of setting to `false` unconditionally in the constructor?
