### ISSUE TITLE
No live video feed after upgrading v0.122.0

### ISSUE THREAD

**Issue by lebence** [koush/scrypted#1637]
**Describe the bug**
I have 3 TP-Link cameras with ONVIF plugin. After upgrading to v0.122.0 (latest) 5 days before, the live feed from cameras went wrong. Scrypted gives me snapshots, but it hasn't live feed, and HKSV history. When I clicked onto cameras, my Home app showed, that my cameras are offline, and live video feed can't be loaded. 

When I refreshed Home app, cameras had snapshot.

After this issue, i downgraded my docker version to v0.118.0-jammy-full, and everything is working well again. I have live video feed, HKSV, history and snapshots...

**Server (please complete the following information):**
 - OS: Docker, Ubuntu 22.04
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: Acer Revo

**Client (please complete the following information, if applicable):**
 - Software: Home app

**Additional context**

**Comment by koush** [comment]
need camera log

**Comment by lebence** [comment]
Now after resintalled v0.122.0 to get logs, it works perfect. I don't know what was that, maybe nothing. Sorry for the issue. If it brokes again i will send logs immediately.
