### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by gh0sti** [koush/scrypted#1644]
**Describe the bug**
scrypted is not working after a new docker image was pushed
Portainer shows these logs.
s6-rc: info: service setup successfully started

s6-rc: info: service dbus: starting

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

SCRYPTED_DOCKER_AVAHI != true, not starting dbus-daemon

s6-rc: info: service dbus successfully started

s6-rc: info: service avahi: starting

SCRYPTED_DOCKER_AVAHI != true, not starting avahi-daemon

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service avahi successfully started

s6-rc: info: service legacy-services: starting

s6-rc: info: service legacy-services successfully started

s6-rc: info: service legacy-services: stopping

s6-rc: info: service legacy-services successfully stopped

s6-rc: info: service legacy-cont-init: stopping

s6-rc: info: service avahi: stopping

s6-rc: info: service legacy-cont-init successfully stopped

s6-rc: info: service fix-attrs: stopping

s6-rc: info: service avahi successfully stopped

s6-rc: info: service dbus: stopping 
**To Reproduce**
1. use watchtower to update images
2. scrypted was updated and now won't run

**Expected behavior**
scrypted is supposed to be running

**Server (please complete the following information):**
 - OS: Bookworm 12 Debian
 - Installation Method: Docker

**Hardware Model (please complete the following information):**
 - Device: RPi 5 8GB RAM

**Client (please complete the following information, if applicable):**
 - Software: Docker/Browser

**Additional context**
I tried using different networking setups and deploying the container several times.

**Comment by koush** [comment]
there was no new docker image.
