### ISSUE TITLE
Scrypted Offline for 5 Minutes Everyday

### ISSUE THREAD

**Issue by kylewhirl** [koush/scrypted#1645]
**Describe the bug**
I was previously running Scrypted on an M2 Mac Mini, no issues with cameras cutting out randomly throughout the night. I transfer everything from the computer to the new M4 Mac Mini, and now my Scrypted cameras go offline for a few minutes and come back on. All related power and display settings in Mac OS are set up to keep the display on and not lock the Mac, and not start a screensaver. My Unifi logs show nothing out of the ordinary at the same time. 

**To Reproduce**
Probably really hard to reproduce, but installing Scrypted on new Mac mini m4

**Expected behavior**
Cameras should not go offline randomly

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Installation Method: [e.g. Desktop App, Docker, Local]
 - Mac OS Scrypted App

**Hardware Model (please complete the following information):**
 - Device: [e.g. Amcrest]
 - Mac Mini m4, camera is rtsp stream

**Client (please complete the following information, if applicable):**
 - Software: [e.g. Home app, NVR app, Alexa, Browser]
Home app
**Additional context**

**Comment by koush** [comment]
this is an mdns issue on your end.

**Comment by koush** [comment]
The M4 mini also seems to have general stability issues from other user reports. Not just with Scrypted either.

**Comment by kylewhirl** [comment]
Any instructions on how to fix it? mDNS is enabled on everything

**Comment by koush** [comment]
see troubleshooting guide.
