### ISSUE TITLE
HKSV no longer recording

### ISSUE THREAD

**Issue by farberm** [koush/scrypted#1648]
HKSV was previosuly working without any issue. Since 11/15 no longer any recordings.

Troubleshooting. I uninstalled and reinstalled all cameras and HK plugin
I restarted all Home Hubs

When I try and trigger an event this is what I get in the camera console log...

[HomeKit]: -hide_banner -analyzeduration 0 -probesize 512 -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 14519203 -dn -sn -vn -f rtp rtp://127.0.0.1:38987?pkt_size=400 -sdp_file pipe:4
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 9
[HomeKit]: scanning for idr start found: 28 1 9 24 7 8 6
[HomeKit]: idr start found: 28 5
[HomeKit]: handleStreamRequest { sessionID: 'b2c34b69-f269-4add-81bd-bc580524edb5', type: 'stop' }
[HomeKit]: streaming session killed, duration: 1s
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[HomeKit]: motion recording closed (error code: 6)
[Rebroadcast Plugin]: client connection timed out
[HomeKit]: motion recording starting
[HomeKit]: -hide_banner -analyzeduration 0 -probesize 1274641 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
[HomeKit]: motion recording started
[HomeKit]: motion recording error Error: stream ended: readLength end
[HomeKit]: motion recording finished
[HomeKit]: motion recording closed (error code: 6)
[Rebroadcast Plugin]: client connection timed out
[Rebroadcast Plugin]: client connection timed out

**Expected behavior**
I should see something in HKSV recorded. I also do not get any notification that motion has occurred in Notifications on iphone

**Server (please complete the following information):**
 - Synology Docker Scrypted v0.122

**Hardware Model (please complete the following information):**
 Dahua Camera loaded using Amcrest Plugin

**Client (please complete the following information, if applicable):**

**Comment by Vicelow** [comment]
Has there been any solution to this? I have the very same issue. Same error in the log:

 [HomeKit]: motion recording started
[HomeKit]: motion recording error Error: stream ended: readLength end
[HomeKit]: motion recording finished
[HomeKit]: motion recording closed (error code: 6)

It worked perfectly before…
