### ISSUE TITLE
OpenVINO Object Detection plugin load error Error on Unraid Docker

### ISSUE THREAD

**Issue by dianasta21** [koush/scrypted#1651]
**Describe the bug**
Hello, 
I'm using the unraid docker container. After upgrade to the latest unraid version 6.12.14, started getting the error below. Looks like there is an issue with the OpenVINO Object Detection plugin.

Scrypted Error Log:
-----------------------
e OpenVINO Object Detection @scrypted/openvino exited null SIGILL
e OpenVINO Object Detection plugin @scrypted/openvino unexpectedly exited, restarting in 60000ms
a OpenVINO Object Detection Plugin failed to load. View Console for more information.
alert {
  timestamp: 1732802163159,
  level: 'a',
  message: 'Plugin failed to load. View Console for more information.',
  path: '/device/66',
  title: 'OpenVINO Object Detection'
}
e OpenVINO Object Detection plugin load error Error: plugin disconnected
host:@scrypted/openvino
e OpenVINO Object Detection @scrypted/openvino close
client.sendDiscovery(255.255.255.255, [], 3)

client.sendDiscovery(255.255.255.255, [], 3)

Unraid Error Log:
-------------------
Nov 28 08:50:43 Tower kernel: traps: python3[22586] trap invalid opcode ip:152c38e4e9d7 sp:7ffc091b6ed0 error:0 in libopenvino_intel_npu_plugin.so[152c38e2f000+1f1000]
Nov 28 08:51:32 Tower kernel: traps: python3[25211] trap invalid opcode ip:14760104e9d7 sp:7fff0b5f2ac0 error:0 in libopenvino_intel_npu_plugin.so[14760102f000+1f1000]
Nov 28 08:51:47 Tower kernel: traps: python3[25957] trap invalid opcode ip:1484bc24e9d7 sp:7ffef33ab3c0 error:0 in libopenvino_intel_npu_plugin.so[1484bc22f000+1f1000]
Nov 28 08:52:36 Tower kernel: traps: python3[28290] trap invalid opcode ip:14c90da4e9d7 sp:7ffd816e0ec0 error:0 in libopenvino_intel_npu_plugin.so[14c90da2f000+1f1000]
Nov 28 08:52:51 Tower kernel: traps: python3[29024] trap invalid opcode ip:153578e4e9d7 sp:7ffdba377620 error:0 in libopenvino_intel_npu_plugin.so[153578e2f000+1f1000]
Nov 28 08:53:41 Tower kernel: traps: python3[31576] trap invalid opcode ip:1471d424e9d7 sp:7ffda33d54f0 error:0 in libopenvino_intel_npu_plugin.so[1471d422f000+1f1000]
Nov 28 08:53:55 Tower kernel: traps: python3[32210] trap invalid opcode ip:149d4ea4e9d7 sp:7ffeb2321ab0 error:0 in libopenvino_intel_npu_plugin.so[149d4ea2f000+1f1000]
Nov 28 08:54:45 Tower kernel: traps: python3[2849] trap invalid opcode ip:1463ac64e9d7 sp:7ffe5bea1b80 error:0 in libopenvino_intel_npu_plugin.so[1463ac62f000+1f1000]
Nov 28 08:54:59 Tower kernel: traps: python3[3675] trap invalid opcode ip:15179444e9d7 sp:7ffe993a4de0 error:0 in libopenvino_intel_npu_plugin.so[15179442f000+1f1000]
Nov 28 08:55:49 Tower kernel: traps: python3[6443] trap invalid opcode ip:14765144e9d7 sp:7ffefa78e280 error:0 in libopenvino_intel_npu_plugin.so[14765142f000+1f1000]
Nov 28 08:56:03 Tower kernel: traps: python3[7184] trap invalid opcode ip:150c3904e9d7 sp:7ffc9b276fc0 error:0 in libopenvino_intel_npu_plugin.so[150c3902f000+1f1000]

Thanks.

**Comment by koush** [comment]
Try using the beta tag plugjn

**Comment by dianasta21** [comment]
I tried that and still getting the errors, and is crashing. 
Is there any way to remove the plugin ? When I remove it it is still getting re-installed automatically. 


--------------------------------
linux x64 #1 SMP PREEMPT_DYNAMIC Thu Nov 21 15:54:38 PST 2024
server version: 0.122.0
plugin version: @scrypted/openvino 0.1.136
full
########################
11/28/2024, 10:54:25 AM
########################
python version: python3.10
interpreter: /usr/bin/python3
pip target: /server/volume/plugins/@scrypted/openvino/python3.10-Linux-x86_64-20240317
requirements.txt (up to date)
# openvino 2024.3.0 crashes on older CPU (J4105 and older) if level-zero is installed via apt.
# openvino 2024.2.0 and older crashes on arc dGPU.
openvino==2024.4.0
Pillow==10.3.0
opencv-python-headless==4.10.0.84

Available devices:

**Comment by dianasta21** [comment]
> what cpu id this

Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz (family: 0x6, model: 0x2c, stepping: 0x2)

**Comment by koush** [comment]
if you're not using nvr plugin, delete it and openvino.

**Comment by koush** [comment]
seems fixed with the openvino plugin update actually.

**Comment by dianasta21** [comment]
Thanks yes, I can confirm is just fixed 5 minutes ago, the latest release.

**Comment by koush** [comment]
had to roll the fix back. they broke NPU drivers with the update. you'll need to stay on the fixed version and disable auto updates. or use onnx plugin since your CPU is too old to function on openvino. can change detector in nvr settings.
