### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries when trying to install docker with compose

### ISSUE THREAD

**Issue by eagerbeaver86** [koush/scrypted#1653]
Using aarch64 

With docker compose script 

_mkdir -p ~/.scrypted
curl -s https://raw.githubusercontent.com/koush/scrypted/main/install/docker/install-scrypted-docker-compose.sh > ~/.scrypted/install-scrypted-docker-compose.sh 
sudo SERVICE_USER=$USER bash ~/.scrypted/install-scrypted-docker-compose.sh_

no matching manifest for linux/arm/v8 in the manifest list entries as result

Thanks for clarification

**Comment by bjia56** [comment]
`linux/arm/v8` looks like 32-bit docker running on 64-bit host. Make sure your host OS is 64-bit and your docker is also 64-bit.

**Comment by eagerbeaver86** [comment]
Docker version is 27.3.1, build ce12230
OS is 64 bit
