### ISSUE TITLE
Can't install ghcr.io/koush/scrypted:v0.120.0-jammy-full: 404

### ISSUE THREAD

**Issue by kousuiya** [koush/scrypted#1656]
Can't install ghcr.io/koush/scrypted:v0.120.0-jammy-full: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/koush/scrypted:v0.120.0-jammy-full/json: Not Found ("No such image: ghcr.io/koush/scrypted:v0.120.0-jammy-full")

**Comment by koush** [comment]
seems fine here.

**Comment by kousuiya** [comment]
Can I modify the downloaded version and how should I proceed
