### ISSUE TITLE
After updating all device groups show same stream and settings are missing.

### ISSUE THREAD

**Issue by joerikosters** [koush/scrypted#1658]
After I updated this Friday all my device groups started showing the same video stream.

As soon as I rolled back only the Scrypted Core to the previous version (from 0.3.87 back to 0.3.86) everything works as normal again.

Also "Settings > General > Select Device Interfaces" box inside device groups looks like it's missing under 0.3.87

**Comment by koush** [comment]
please recreate and see if it works. the groups work fine for me.

**Comment by chris9999** [comment]
Same problem for me

**Comment by koush** [comment]
screenshot the interface you are grouping

**Comment by chris9999** [comment]
Pics attached @
![IMG_3165](https://github.com/user-attachments/assets/a9b6b70b-9614-4c9f-99af-973cf338ada5)
![IMG_3166](https://github.com/user-attachments/assets/fe784908-cd8a-41ef-93af-7d0d3ab61c32)

**Comment by koush** [comment]
anything in core console or core plugin logs?

**Comment by wajonespress** [comment]
Same issue for me here. All cameras show the same image.

![Screen Sharing Picture 11 December 2024 at 12 53 31 pm AEDT](https://github.com/user-attachments/assets/124daeef-0985-45e6-b457-81eba5d8cd6d)

![Untitled](https://github.com/user-attachments/assets/a82f13ca-f8bb-41bc-ab73-3027831bfa4c)

![Screen Sharing Picture 11 December 2024 at 12 50 51 pm AEDT](https://github.com/user-attachments/assets/4984a0f5-cda6-4651-ad62-a138d83cd4b3)

darwin arm64 Darwin Kernel Version 23.6.0: Fri Jul  5 18:01:46 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T8112
server version: 0.122.0
plugin version: @scrypted/core 0.3.92
########################
12/11/2024, 1:09:59 PM
########################
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:63144
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:63161
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}

darwin arm64 Darwin Kernel Version 23.6.0: Fri Jul  5 18:01:46 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T8112
server version: 0.122.0
plugin version: @scrypted/core 0.3.92
########################
12/11/2024, 1:09:40 PM
########################
starting plugin @scrypted/core 7521
node modules /Users/warwickjones/.scrypted/volume/plugins/@scrypted/core/node20-darwin-arm64
plugin loaded
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:63144
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}
RPCResultError: connection closed.
@scrypted/core:127.0.0.1:63161
    at RpcPeer.kill (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc.ts:439:23)
    at Socket.onDisconnected (/Users/warwickjones/.scrypted/node_modules/@scrypted/server/src/rpc-serializer.ts:35:17)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12) {
  cause: undefined
}

**Comment by wajonespress** [comment]
This is the view inside HomeKit
![IMG_2007](https://github.com/user-attachments/assets/bef0f94c-3be6-4dc6-8598-dde574f360fe)

**Comment by joerikosters** [comment]
Today my core got autoupdated to 0.3.29 core and the problem returned.

I've made some screenshots, but they tell exactly the same as @wajonespress screenshots (ill commend them anyway)

I don't really know if you'd like some logs, what logs, and where to find them. So if you want them ill update again (rolled back to 0.3.86 again, it keeps on working) and send you the requested logs.

**Comment by joerikosters** [comment]
Screenshots of 0.3.92 (new version with issues):
<img width="1237" alt="Screenshot 2024-12-12 at 20 52 47" src="https://github.com/user-attachments/assets/5e3e89b4-318d-4509-bb7b-e1684f86368a" />
<img width="1431" alt="Screenshot 2024-12-12 at 20 53 33" src="https://github.com/user-attachments/assets/f87c8c9a-03fa-4ccb-b54c-a1c97ab1a345" />
<img width="1431" alt="Screenshot 2024-12-12 at 20 54 11" src="https://github.com/user-attachments/assets/e3fca248-2630-4b56-a491-e40628c92bd5" />

**Comment by joerikosters** [comment]
Screenshots after rolling back to older version (0.3.86)

<img width="1431" alt="Screenshot 2024-12-12 at 20 54 56" src="https://github.com/user-attachments/assets/aaf37b6c-e955-4941-a543-1daafac48749" />
<img width="1431" alt="Screenshot 2024-12-12 at 20 55 02" src="https://github.com/user-attachments/assets/45ed548f-fae6-49b3-9b42-1eb241c5e53e" />
<img width="1431" alt="Screenshot 2024-12-12 at 20 55 10" src="https://github.com/user-attachments/assets/a520a84b-a1c1-4b87-aa92-20b3604812dc" />

No changes in logs seem to appear when opening in homekit, so no extra screenshot.

**Comment by joerikosters** [comment]
Maybe useful (maybe not): a schematic of how I use device groups.

I use it make cameras available in 2 different homekit homes:
- scrypted load streams through the Unifi plugin
- every camera is part of 2 device groups: camera (except one, that is doorbell and combined with the MQTT message of an ESP32)
- 1 for first homekit home, 1 for second homekit home
- the device groups have the homekit plugin available
- this plugin is presenting every camera to 2 different homes as separate devices (accessory mode)

![tempImageok0nFW](https://github.com/user-attachments/assets/716d148c-70c9-4468-bdbc-b80a7f3bf793)

**Comment by MichlW** [comment]
I have exactly the same problem that any grouped camera shows the same video stream from my garden camera after one of the last scrypted update.
The single and not grouped RTSP camera device show the correct video stream.

**Comment by koush** [comment]
Ok so to confirm, this issue happens when using multiple camera groups? I was only testing with a single camera group.

**Comment by joerikosters** [comment]
Looks like it, I use 3 different cameras that are part of 6 different device groups.

**Comment by wajonespress** [comment]
I have four device groups, one for each IP camera.

It’s only device groups that are affected by the duplicate image, so there must be more than one to see a duplicate.
![IMG_2018](https://github.com/user-attachments/assets/a5fd280f-7724-4097-993b-f18b418fb138)

**Comment by koush** [comment]
fixed
