### ISSUE TITLE
createMotionSensor doesn't work after update MQTT Plugin

### ISSUE THREAD

**Issue by Balooforever** [koush/scrypted#1660]
# Github Issues are not a Support or Discussion Forum

Before opening an issue, view the device's Console logs in the Scrypted Management web interface.

**DO NOT OPEN ISSUES FOR ANY OF THE FOLLOWING:**

**Describe the bug**
After the MQTT plugin upgrade to 0.84, the script with "createMotionSensor" for doorbell doesn't work.

**Comment by koush** [comment]
fixed
