### ISSUE TITLE
Constant crash with G3 Instant

### ISSUE THREAD

**Issue by metalheadz** [koush/scrypted#17]
Hi! 

I just acquired a Cloud key gen 2 plus and a G3 Instant.

Everything is at the latest version, including iOS.

I added the camera to homekit to use with secure video and installed all the required plugins as described on the main page.

Im running scrypted on a raspberry pi 4.

Everthings works fine for about 2-3 hours and the process always crash and exit.

I want to help to get that resolved, just tell me what information/logs are needed!

Thanks!

**Comment by koush** [comment]
The only crash I've ever seen is when it is not running on node 16.
Please confirm.

**Comment by metalheadz** [comment]
Im running on node 14! Im updating right now and get back with results!
