### ISSUE TITLE
Always show current version number of plugin in plugin detail screen

### ISSUE THREAD

**Issue by jeffkibuule** [koush/scrypted#170]
Right now, I don't think it's possible to see the current version number of a plugin if there is an update. Given the current pace of development, it's hard to know how "out of date" you are when all plugins need to be updated.

Recommendation:
A new column at the end for "Update available" listing the new version number. If nothing, show "Up to date". The "Version" column with current version numbers should be permanent and remain unchanged.

For an additional bonus, above and beyond, record when a plugin was installed/last updated.

**Comment by koush** [comment]
leaving a reminder to myself to put an `(installed)` next to the current installed one in the dropdown.

**Comment by koush** [comment]
update core plugin and then this change will show up after reloading the page. might take a couple reloads. safari really likes to hang onto the cached PWAs.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/73924/153737766-02c80a9e-e1f3-4410-b6b8-c57a38f03905.png">
