### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by VB7749** [koush/scrypted#173]
in my logs

<img width="1028" alt="Screen Shot 2022-02-14 at 8 42 51 PM" src="https://user-images.githubusercontent.com/38964334/153977393-cbd6e0e4-64af-4406-abcf-d3b886ec0f43.png">

**Comment by VB7749** [comment]
<img width="1028" alt="Screen Shot 2022-02-14 at 8 42 51 PM" src="https://user-images.githubusercontent.com/38964334/153977235-9648703c-21f7-4213-8ede-6020fa80bcee.png">

**Comment by koush** [comment]
upgrade to bullseye on your pi
