### ISSUE TITLE
DAFANG ONVIF works, but without snapshot or motion detection.

### ISSUE THREAD

**Issue by JonyBCN** [koush/scrypted#177]
I have added a DAFANG camera (hacked) and the ONVIF plugin detects it and works without problems. The stream opens very fast. The configuration is as follows: H264 1920x108, MP3 audio, 2000kbps VBR.
 The only problem is that the motion detector doesn't seem to work and I never get refresh on the image unless I open the stream. I have another onvif camera that refreshes without problems every 10 seconds, just like a native Eufy from Homekit.

Any clue what I should touch to fix the problem?

**Comment by koush** [comment]
I'd asl on discord.
