### ISSUE TITLE
https

### ISSUE THREAD

**Issue by and217** [koush/scrypted#178]
scrypted    | Error: EISDIR: illegal operation on a directory, read
scrypted    |     at Object.readSync (node:fs:723:3)
scrypted    |     at tryReadSync (node:fs:433:20)
scrypted    |     at Object.readFileSync (node:fs:479:19)
scrypted    |     at start (/server/node_modules/@scrypted/server/src/scrypted-server
try to get custom certificate to work.  where's the problem is it json file is not correct?

**Comment by koush** [comment]
see the example in server/tests
