### ISSUE TITLE
Clearer snapshots

### ISSUE THREAD

**Issue by ads1230** [koush/scrypted#179]
Hey! The snapshots of my cameras connected through Scrypted on HomeKit are quite blurry compared to my native G2H's.

Is there a way/setting for clearer images? Currently I'm using the UniFi and pre-buffer plugins.

**Comment by koush** [comment]
can disable this with the snapshot plugin

**Comment by dmkpoznan** [comment]
@koush how can we change quality of snapshot? Locally image is as blurry as remotely.
