### ISSUE TITLE
can't open https://localhost:9443/

### ISSUE THREAD

**Issue by nicedc** [koush/scrypted#181]
following    Installation: Docker Synology NAS
 
this is my logs

> scrypted@1.0.0 serve-no-build
> node dist/scrypted-main.js

#############################################
Scrypted Server: https://localhost:9443/
#############################################
installing package @scrypted/core 0.0.197
downloaded tarball 5731716
parsing entry package/package.json
parsing entry package/README.md
parsing entry package/dist/main.nodejs.js.LICENSE.txt
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/README.md, package/dist/main.nodejs.js.LICENSE.txt, package/dist/plugin.zip
i undefined state change: providedInterfaces DeviceProvider,EngineIOHandler,HttpRequestHandler
i undefined state change: interfaces DeviceProvider,EngineIOHandler,HttpRequestHandler
i undefined state change: providerId 1
i undefined state change: providedName Scrypted Core
i undefined state change: providedType DeviceProvider
i undefined state change: type DeviceProvider
i undefined state change: name Scrypted Core
a undefined New Device Added.
alert {
  timestamp: 1645436963306,
  level: 'a',
  message: 'New Device Added.',
  path: '/device/1',
  title: undefined
}
i undefined loading @scrypted/core
i undefined pid 37
i undefined state change: providedInterfaces BufferConverter,DeviceProvider
i undefined state change: interfaces BufferConverter,DeviceProvider
i undefined state change: providerId 1
i undefined state change: providedName Scrypted Media Core
i undefined state change: providedType API
i undefined state change: type API
i undefined state change: name Scrypted Media Core
a undefined New Device Added.
alert {
  timestamp: 1645436964979,
  level: 'a',
  message: 'New Device Added.',
  path: '/device/2',
  title: undefined
}
invalidating on request
i undefined state change: providedInterfaces OnOff,Settings
i undefined state change: interfaces OnOff,Settings
i undefined state change: providerId 1
i undefined state change: providedName Autoupdate Plugins
i undefined state change: providedType Automation
i undefined state change: type Automation
i undefined state change: name Autoupdate Plugins
a undefined New Device Added.
alert {
  timestamp: 1645436964982,
  level: 'a',
  message: 'New Device Added.',
  path: '/device/3',
  title: undefined
}
invalidating on request
i undefined loaded @scrypted/core
null proxy 1

/server/src/plugin/plugin-device.ts:180
                return (await mixin.proxy)[method](...argArray);
                                          ^
TypeError: Cannot read properties of undefined (reading 'onRequest')
    at PluginDeviceProxyHandler.applyMixin (/server/src/plugin/plugin-device.ts:180:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm notice 
npm notice New major version of npm available! 7.24.0 -> 8.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.1
npm notice Run npm install -g npm@8.5.1 to update!
npm notice

**Comment by koush** [comment]
10443 is the new port. how old is this build?

**Comment by 0endive** [comment]
I am also having same issue with 10443 port. Also my container is on a reboot loop. 
CONTAINER ID   IMAGE                                                      COMMAND                  CREATED        STATUS                            PORTS     NAMES
544c263d327b   koush/scrypted                                             "docker-entrypoint.s…"   3 hours ago    Restarting (134) 33 seconds ago             sweet_heisenberg

**Comment by koush** [comment]
@williamchai please stop editing the wiki with outdated information.

**Comment by yonigold1** [comment]
im still having this issue is there any resolution?
