### ISSUE TITLE
Allow per camera snapshot source URL override w/ Synology

### ISSUE THREAD

**Issue by pinlawr** [koush/scrypted#183]
My cameras (Reolink) have a url that can be crafted to retrieve a single still image. I was using this with a different plugin on homebridge. The benefit is I can specify this URL and the still image is retrieved much faster than waiting for synology to respond with one, thus, the preview images load almost instantly. It comes directly from the camera, and with the right parameters it's a much smaller (file size) image and therefore loads faster.

It probably doesn't help, but the direct camera URL in this case looks like this:
http://X.X.X.X/cgi-bin/api.cgi?cmd=Snap&channel=0&user=USER&password=PASSWORD&width=1024&height=768

I would like the ability to specify a still image source URL per camera when using the Synology plugin. If the URL is not specified then I would want the plugin to retrieve a snapshot as it does now.

Thanks!

**Comment by koush** [comment]
![Uploading image.png…]()
