### ISSUE TITLE
Unreachable Camera Notifications

### ISSUE THREAD

**Issue by squishycat92** [koush/scrypted#185]
Hi, thank you so much for making this project!

However, I've noticed that the toggle "Notify When Camera Goes Offline" in HomeKit actually has no function if a camera goes offline. Instead, if the Scrypted container (or Docker host) goes offline, HomeKit reports that all cameras added through Scrypted are offline.

I was wondering if it was possible to implement a system where Scrypted would correctly report the status of each camera as offline and cause HomeKit to push a notification to user devices. Would such an implementation be possible?

**Comment by koush** [comment]
Yes, this is done, but it requires that the cameras are in accessory mode. This is in the homekit plugin beta.
