### ISSUE TITLE
opencv: "No valid frames decoded"

### ISSUE THREAD

**Issue by readybeginn** [koush/scrypted#188]
I have a Eufy c24 camera set up and working. It streams through Homekit without any issues using the rebroadcast plugin.

I noticed that motion alerts aren't working and it appears opencv is just giving up because it can't read the stream. The Eufy camera doesn't have a sub stream so it's trying to open the 1080 stream. Any thoughts?

Opencv log:

starting plugin @scrypted/opencv 0.0.43
python: python3.9
requirements.txt (up to date)
plugin
numpy>=1.16.2
PyGObject>=3.30.4
imutils>=0.5.0
detection starting @scrypted/opencv-14
Gstreamer pipeline:
  tcpclientsrc port=37885 host=127.0.0.1 ! tsdemux ! decodebin  ! queue leaky=upstream max-size-buffers=1 ! videoconvert name=videoconvert ! videoscale name=videoscale
            !  video/x-raw,format=I420,width=300,height=300,pixel-aspect-ratio=1/1 ! appsink name=OpenCVPlugin emit-signals=true max-buffers=1 drop=true sync=false
        
Error: gst-stream-error-quark: No valid frames decoded before end of stream (7): ../gst-libs/gst/video/gstvideodecoder.c(1246): gst_video_decoder_sink_event_default (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/v4l2h264dec:v4l2h264dec0:
no valid frames found

detection ended @scrypted/opencv-14

**Comment by koush** [comment]
Weird. you can try the PAM Diff plugin. That uses ffmpeg instead. 
Switching rebroadcast mode to RTSP may also work, instead it is having an issue trying to parse MPEG-TS.

**Comment by readybeginn** [comment]
Pam diff works but seems to be glitchy as well. Switching rebroadcast mode to RTSP produced the same error in the opencv console.

**Comment by koush** [comment]
guessing this is a camera feed quirk. if ffmpeg can't open it, nothing I can do.

**Comment by readybeginn** [comment]
I tried the Camera UI plugin which also uses ffmpeg. It works there so not sure where the issue lies.

**Comment by koush** [comment]
opencv is using v4l2h264dec which is hardware accelerated. Might be something there. ffmpeg/pam-diff uses software decoding by default.
