### ISSUE TITLE
Ring “Snapshot Unavailable”

### ISSUE THREAD

**Issue by codyc1515** [koush/scrypted#189]
Hi team

Anything I can check to figure out why I keep getting “Snapshot Unavailable” showing as the snapshot?

Streaming works okay. Just not the snapshot.

Cody

**Comment by codyc1515** [comment]
![CBDC8AB3-31A3-4E27-A542-C6A9B08A0FCB](https://user-images.githubusercontent.com/50791984/157933835-3a7c4915-af09-42d0-8ac4-7d305c1c761c.jpeg)

**Comment by codyc1515** [comment]
Also happens in HomeKit
![Uploading EE428451-623E-4299-BB37-019FEDC9532B.jpeg…]()

**Comment by codyc1515** [comment]
Also happens in HomeKit
![D47AD737-E424-42BC-ABA4-3B7D0B383478](https://user-images.githubusercontent.com/50791984/157934110-32c0b0ae-911e-48d2-9b87-1b5b66a2db5c.jpeg)

**Comment by koush** [comment]
Which ring

**Comment by koush** [comment]
And do you have the snapshot plugin installed?

**Comment by codyc1515** [comment]
Sorry, it's the Doorbell Pro. I'm about to get the Doorbell Pro 2 shortly. No - I wasn't aware of the Snapshot plug-in but will try this now.

**Comment by koush** [comment]
The snapshot handling in the stable release is not great. The snapshot plugin and the beta that will much of the issues around ring snapshots. the tldr is that slow snapshots hang homekit completely, and I show an error image if nothing is available in the cache, rather than do that.

**Comment by codyc1515** [comment]
Yeah I know ya gotta send the snapshot immediately but I’d have thought it’d be better to send an older snapshot than the “No image” one at least.

Are you saying I should be using the beta of the Snapshot plugin?

**Comment by koush** [comment]
the snapshot plugin does what you are saying. use the beta of the ring plugin and the stable snapshot plugin.

**Comment by koush** [comment]
snapshot plugin will also pull images from the live stream that goes through the scrypted a/v pipeline, because some ring cameras also block snapshots during viewing.

**Comment by codyc1515** [comment]
> the snapshot plugin does what you are saying. use the beta of the ring plugin and the stable snapshot plugin.

Sorry forgot to reply. It seems to be working very stably with the above.

As an aside, I noticed when using pre buffer on Ring that all event detection stops as the stream is held open. More an FYI. I don't think there is a workaround.

**Comment by koush** [comment]
yeah ring stops motion detection while live viewing.
