### ISSUE TITLE
Scrypted Server Update to 0.0.156 dosen´t work?!?

### ISSUE THREAD

**Issue by MatthiasTeichert** [koush/scrypted#190]
My setup is:
- pi4 with 64 raspbian OS (current version)
- docker (current version)
- scrypted Container (Server Version 0.0.155)
- watchtower Container
- Portainer Container
- plugins (Ring, Unifi, Rebroadcast & Snapshot)
- HomeKit Hub: AppleTV 4 with brand new iOS 15.4

In my first try to update Scrypted I followed the instructions from koush:
1. connect with terminal SSH pi@xxx.xxx.xxx.xxx
2. "# pull the image
docker pull koush/scrypted
#run the image, saving the database and configuration files in a subdirectory named "scrypted"
docker run \
  --network host \
  -d --restart unless-stopped \
  -v ~/.scrypted/volume:/server/volume koush/scrypted"

after that I get a Second "Koush-Container" but the scrypted server version is still 0.0.155

My second try was: 
1. delete Kosh-Container and Image (with Portainer)
2. connect with terminal SSH pi@xxx.xxx.xxx.xxx
3.. "# pull the image
docker pull koush/scrypted
#run the image, saving the database and configuration files in a subdirectory named "scrypted"
docker run \
  --network host \
  -d --restart unless-stopped \
  -v ~/.scrypted/volume:/server/volume koush/scrypted"

after that I get a new "Koush-Container" but the scrypted server version is still 0.0.155

Whats wrong?

Koush. please make the server-upodate-routine easier. maybe like the Plugin Update?

Big Thanks from  a Linux- and Docker Newbie,
Matthias

**Comment by koush** [comment]
docker builds are a bit behind the update notification
