### ISSUE TITLE
Support for Ecobee SmartCamera

### ISSUE THREAD

**Issue by diothar** [koush/scrypted#195]
From what I can tell, Ecobee does not expose rtsp or webrtc for their smart cameras. I use Home Assistant to create a “wallboard” on a fire tablet. To do this, I have to use a HomeKit Controller and then share back to my HomeKit Bridge. This works, but it kills all the HomeKit Secure Video functionality that I was hoping to get (and then not have to pay a subscription fee because I want storage to not be on Ecobee’s cloud. 

I came across Scrypted and asked in the discord, but nobody answered me. I see support for ecobee, but I think it’s just the smart thermostat. But if it does support the cameras, does it stream the feed so I could have the cameras show up using HomeKit secure video and then just be able to subscribe to some sort feed, like via webrtc or rtsp?

**Comment by miwagner1** [comment]
It is only the ecobee API which only covers the smart thermostat.

**Comment by diothar** [comment]
Yeah, I suspected that, but someone told me to check out Scrypted.  
As far as I can tell, there's no way to have an Ecobee Smart Camera added to homekit via homekit secure video and also make it available to home assistant so I can use them on a dashboard, right?  

Right now I have a homekit controller set up (which is similar to  homebridge, from what I understand) and that way they're exposed to home assistant because they think home assistant is homekit.  Then I share them with homekit via the homekit integration.  The issue with that is that the homekit controller on homekit doesn't function as a homekit secure video controller.

**Comment by koush** [comment]
I might add native homekit device support, been a lot of requests for this.

**Comment by diothar** [comment]
Would that mean I’d add the camera to HomeKit, then scrypted can share it with Home Assistant for my dashboards? If I can get the Ecobee Cameras to to  support HKSV and also be imported into Home Assistant, I’d donate the cost of 6 months of the Ecobee subscription to sponsor you. :-)

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/88
