### ISSUE TITLE
Dropbox to choose channel for ONVIF plugin disappeared in version 0.0.84 (unable to use plugin with DVR)

### ISSUE THREAD

**Issue by alexsantos89** [koush/scrypted#199]
Hi. 

First of all, thank you for this amazing software. 

I have a setup that I connect to 5 different cameras in the same DVR via ONVIF plugin choosing the correct channel from a dropbox in the plugin when I add a new device, but in the new version 0.0.84 that dropbox disappeared and I was not able to select the correct camera anymore (please see screenshot attached from version 0.0.83, the highlighted dropbox disappeared in the new version). 

Let me know if you need any more info!

Thanks!

![Screen Shot 2022-03-23 at 11 19 39 PM](https://user-images.githubusercontent.com/10471730/159829888-94fddc49-33d2-40a3-a916-a5b77d7396b0.png)

**Comment by koush** [comment]
can you not select the stream in homekit?

**Comment by alexsantos89** [comment]
The stream is available inside the homekit tab inside the ONVIF plug-in, but the drop-down menu disappeared in the Advanced tab. I did not test, but I can probably send the right stream to homekit, but inside scrypted itself I cannot watch the stream because I cannot select it.

**Comment by koush** [comment]
I added this back into the rebroadcast plugin. Check the prebuffer tab.
