### ISSUE TITLE
cant install without getting these errors

### ISSUE THREAD

**Issue by ArminAghayan** [koush/scrypted#2]
src/plugin/plugin-host.ts:24:13 - error TS2503: Cannot find namespace 'cluster'.

24     worker: cluster.Worker;
               ~~~~~~~

src/plugin/plugin-host.ts:192:47 - error TS7006: Parameter 'data' implicitly has an 'any' type.

192         this.worker.process.stdout.on('data', data => {
                                                  ~~~~

src/plugin/plugin-host.ts:195:47 - error TS7006: Parameter 'data' implicitly has an 'any' type.

195         this.worker.process.stderr.on('data', data => process.stderr.write(data));
                                                  ~~~~

src/plugin/plugin-host.ts:202:39 - error TS7006: Parameter 'code' implicitly has an 'any' type.

202         this.worker.on('exit', async (code, signal) => {
                                          ~~~~

src/plugin/plugin-host.ts:202:45 - error TS7006: Parameter 'signal' implicitly has an 'any' type.

202         this.worker.on('exit', async (code, signal) => {
                                                ~~~~~~

src/plugin/plugin-host.ts:206:33 - error TS7006: Parameter 'e' implicitly has an 'any' type.

206         this.worker.on('error', e => {
                                    ~

src/plugin/plugin-host.ts:210:35 - error TS7006: Parameter 'message' implicitly has an 'any' type.

210         this.worker.on('message', message => this.peer.handleMessage(message));
                                      ~~~~~~~

src/plugin/plugin-host.ts:214:54 - error TS7006: Parameter 'e' implicitly has an 'any' type.

214                 this.worker.send(message, undefined, e => {
                                                         ~

Found 8 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scrypted@1.0.0 build: `tsc --outDir dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the scrypted@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cc/.npm/_logs/2021-09-09T17_03_38_089Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scrypted@1.0.0 serve: `npm run build && node dist/scrypted-main.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the scrypted@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by JW-1000** [comment]
Same for me, Im on ubuntu 20

**Comment by koush** [comment]
node version? did you npm install beforehand? this seems odd.

**Comment by JW-1000** [comment]
node -v 

v10.19.0

**Comment by koush** [comment]
I've tested 14 and 16. I am unsure in node v10 supports cluster/worker, and whatnot.

**Comment by JW-1000** [comment]
installed v16 and it worked - thank you!!!
