### ISSUE TITLE
Can't log in through qnap docker installation

### ISSUE THREAD

**Issue by TWLR** [koush/scrypted#202]
The following code appears during the installation process:
由于错误错误而跳过转换器：无法解析MIME类型字符串“未定义”在新的MIMEType（/server/node_modules/whatwg-mimetype/lib/mime-type.js:15:13）在MediaManagerImpl.convert（/server/node_modules/@scrypted/server/src/plugin/media.ts:324:47）在MediaManagerImpl.convertMediaObjectToUrl（/server/node_modules/@scrypted/server/src/plugin/media.ts:237:32）在processTicksAndRejections（node:internal/process/task_queues:96:5）
i未定义的状态更改：从MimeType */*i未定义的状态更改：tMimeType text/x-insecure-local-urii未定义的状态更改：从MimeType */*i未定义的状态更改：tMimeType text/x-local-urii未定义的状态更改：从MimeType x-scrypted/x-scrypted-scheme-filei未定义的状态更改：tMimeType text/x-insecure-local-urii未定义的状态更改：从MimeType x-scrypted/x-scrypted-scheme-filei未定义的状态更改：tMimeType text/x-local-uri
显示以下代码：
拒绝请求 false undefined /endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=polling&t=N_3zS6x

**Comment by koush** [comment]
probably need cloud plugin.
