### ISSUE TITLE
Can't access Scrypted web GUI

### ISSUE THREAD

**Issue by Stroh37** [koush/scrypted#204]
I installed scrypted on my UDMP about a week ago using 

`mkdir /mnt/data/scrypted/volume`
`podman run \
  --network host \
    -d --restart always \
    -v /mnt/data/scrypted/volume:/server/volume koush/scrypted`

and everything had worked perfect. I ran into some trouble with another project and was forced to factory reset. Now I'm trying to install scrypted again and I get this output.

#######################################################    
  Scrypted Server (Local)   : https://localhost:10443/  
  Scrypted Server (Remote)  : https://104.6.248.65:10443/  
  Scrypted Server (Remote)  : https://2001:506:71e6:2e1::1:10443/  
Scrypted Server (Remote)  : https://fe80::8a71:b1ff:fe4e:6721:10443/   
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c5d:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c5e:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c5f:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c60:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c61:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c62:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c63:10443/  
Scrypted Server (Remote)  : https://fe80::7a45:58ff:fefb:6c64:10443/  
Version:       : 0.0.162
#######################################################
Chrome Users: You may need to type "thisisunsafe" into
              the window to bypass the warning. There
              may be no button to continue, type the
              letters "thisisunsafe" and it will proceed.
#######################################################
Scrypted insecure http service port: 30080
Ports can be changed with environment variables.
https: $SCRYPTED_SECURE_PORT
http : $SCRYPTED_INSECURE_PORT
Certificate can be modified via tls.createSecureContext options in
JSON file located at SCRYPTED_HTTPS_OPTIONS_FILE environment variable:
export SCRYPTED_HTTPS_OPTIONS_FILE=/path/to/options.json
https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions
#######################################################
Failed to listen on port 30080. It may be in use.
Use the environment variable SCRYPTED_INSECURE_PORT to change the port.
Error: listen EADDRINUSE: address already in use :::30080
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:42:12)
    at start (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:220:5)

I can't access gui through https://localhost:10443
The container also keeps stopping itself and restarting.

**Comment by koush** [comment]
hm port conflict, will fix.
