### ISSUE TITLE
Motion detection stopped working (macOS @ M1)

### ISSUE THREAD

**Issue by dmkpoznan** [koush/scrypted#206]
This error from "Video Analysis Plugin" is probably the main reason:

`[CameraName] failure retrieving stream [host:@scrypted/objectdetector
@scrypted/opencv:host
Traceback (most recent call last):
  File "/Users/username/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 305, in handleMessage
    value = await maybe_await(invoke(*args))
  File "/Users/username/.scrypted/node_modules/@scrypted/server/python/rpc.py", line 20, in maybe_await
    return await value
  File "/Users/username/.scrypted/volume/plugins/@scrypted/opencv/zip/1-7ac1f0194b6607438d2159909ed04cce.zip/detect/__init__.py", line 293, in detectObjects
    self.run_pipeline(detection_session, duration, src_size, videosrc)
  File "/Users/username/.scrypted/volume/plugins/@scrypted/opencv/zip/1-7ac1f0194b6607438d2159909ed04cce.zip/detect/__init__.py", line 371, in run_pipeline
    pipeline = run_pipeline(detection_session.loop, detection_session.future, self.create_user_callback(detection_session, duration),
  File "/Users/username/.scrypted/volume/plugins/@scrypted/opencv/zip/1-7ac1f0194b6607438d2159909ed04cce.zip/pipeline/__init__.py", line 246, in run_pipeline
    gst.parse_launch(pipeline)
  File "/Users/username/.scrypted/volume/plugins/@scrypted/opencv/zip/1-7ac1f0194b6607438d2159909ed04cce.zip/pipeline/__init__.py", line 40, in parse_launch
    self.attach_launch(Gst.parse_launch(pipeline))
gi.repository.GLib.GError: gst_parse_error: no element "tcpclientsrc" (1)
] {
  cause: undefined
}`

Reinstalling & reconfiguring did nothing.

**Comment by koush** [comment]
your gstreamer install is broken somehow.

**Comment by koush** [comment]
no, your installation is busted somehow and you're missing stuff from gst-plugins-bad. you might have multiple python paths or something.

**Comment by koush** [comment]
you can use pam diff which doesn't use gstreamer. I dont really want to diagnose local machine issues conflicts, outside of the scope of this project.

**Comment by dmkpoznan** [comment]
Totally understand that, but pam diff also is not working on Mac with m1 - it can't decode (ffmpeg) stream (h264). Every other plugin (snapshot, rebroadcast etc.) is working great.

**Comment by koush** [comment]
need a log of pam diff please

**Comment by koush** [comment]
tracking this with
https://github.com/koush/scrypted/issues/207

**Comment by dmkpoznan** [comment]
From PAM diff:

`ffmpeg exited
ffmpeg exited
ffmpeg exited
ffmpeg exited
ffmpeg exited
ffmpeg exited
ffmpeg exited
ffmpeg exited
[
  '-hide_banner',          '-loglevel',
  'error',                 '-hwaccel',
  'auto',                  '-analyzeduration',
  '0',                     '-probesize',
  '500000',                '-f',
  'mpegts',                '-i',
  'tcp://127.0.0.1:56264', '-an',
  '-dn',                   '-c:v',
  'pam',                   '-pix_fmt',
  'rgb24',                 '-f',
  'image2pipe',            '-vf',
  'fps=2,scale=640:360',   'pipe:3'
]
[
  '-hide_banner',          '-loglevel',
  'error',                 '-hwaccel',
  'auto',                  '-analyzeduration',
  '0',                     '-probesize',
  '500000',                '-f',
  'mpegts',                '-i',
  'tcp://127.0.0.1:56265', '-an',
  '-dn',                   '-c:v',
  'pam',                   '-pix_fmt',
  'rgb24',                 '-f',
  'image2pipe',            '-vf',
  'fps=2,scale=640:360',   'pipe:3'
]
[
  '-hide_banner',          '-loglevel',
  'error',                 '-hwaccel',
  'auto',                  '-analyzeduration',
  '0',                     '-probesize',
  '500000',                '-f',
  'mpegts',                '-i',
  'tcp://127.0.0.1:56266', '-an',
  '-dn',                   '-c:v',
  'pam',                   '-pix_fmt',
  'rgb24',                 '-f',
  'image2pipe',            '-vf',
  'fps=2,scale=640:360',   'pipe:3'
]
[
  '-hide_banner',          '-loglevel',
  'error',                 '-hwaccel',
  'auto',                  '-analyzeduration',
  '0',                     '-probesize',
  '500000',                '-f',
  'mpegts',                '-i',
  'tcp://127.0.0.1:56267', '-an',
  '-dn',                   '-c:v',
  'pam',                   '-pix_fmt',
  'rgb24',                 '-f',
  'image2pipe',            '-vf',
  'fps=2,scale=640:360',   'pipe:3'
]
    Last message repeated 1 times
[h264 @ 0x12f00d000] 
    Last message repeated 1 times
[h264 @ 0x12a80d000] 
[h264 @ 0x107017800] hardware accelerator failed to decode picture

[h264 @ 0x11a837200] hardware accelerator failed to decode picture

[h264 @ 0x13a888a00] hardware accelerator failed to decode picture

[h264 @ 0x12f01d800] hardware accelerator failed to decode picture

[h264 @ 0x107019600] hardware accelerator failed to decode picture

[h264 @ 0x11a818e00] hardware accelerator failed to decode picture

[h264 @ 0x13a889000] hardware accelerator failed to decode picture

[h264 @ 0x12f016400] hardware accelerator failed to decode picture

[h264 @ 0x11a819400] hardware accelerator failed to decode picture

[h264 @ 0x107019c00] hardware accelerator failed to decode picture

[h264 @ 0x13a81c400] hardware accelerator failed to decode picture

[h264 @ 0x12f018a00] hardware accelerator failed to decode picture

[h264 @ 0x11a819a00] hardware accelerator failed to decode picture

[h264 @ 0x10701a200] hardware accelerator failed to decode picture

[h264 @ 0x13a87ac00] hardware accelerator failed to decode picture

[h264 @ 0x12f019000] hardware accelerator failed to decode picture

[h264 @ 0x11a81a000] hardware accelerator failed to decode picture

[h264 @ 0x10701a800] hardware accelerator failed to decode picture

[h264 @ 0x13a87b200] hardware accelerator failed to decode picture

[h264 @ 0x12f029400] hardware accelerator failed to decode picture

[h264 @ 0x11a81a600] hardware accelerator failed to decode picture

[h264 @ 0x10701ae00] hardware accelerator failed to decode picture

[h264 @ 0x13a80ea00] hardware accelerator failed to decode picture

[h264 @ 0x12f029a00] hardware accelerator failed to decode picture

[h264 @ 0x11a81ac00] hardware accelerator failed to decode picture

[h264 @ 0x10701b400] hardware accelerator failed to decode picture

[h264 @ 0x13a80f000] hardware accelerator failed to decode picture

[h264 @ 0x12f02a000] hardware accelerator failed to decode picture

[h264 @ 0x11a81b200] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x10701ba00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a824200] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f02a600] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a81b800] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x10701c000] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a824800] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f02ac00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a837200] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x107017800] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a888a00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f01d800] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a818e00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x107019600] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a889000] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f016400] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a819400] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x107019c00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a81c400] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f018a00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a819a00] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x10701a200] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a87ac00] hardware accelerator failed to decode picture
Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f019000] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x11a81a000] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x10701a800] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x13a87b200] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred

[h264 @ 0x12f029400] hardware accelerator failed to decode picture

Error while decoding stream #0:0: Unknown error occurred
`

**Comment by koush** [comment]
[h264 @ 0x107017800] hardware accelerator failed to decode picture

well that's interesting, have you tried rebooting?

**Comment by dmkpoznan** [comment]
yes, twice - no success at all

**Comment by askjano** [comment]
from the discord channel:

[https://discord.com/channels/882329362295316500/894052368302354483/1071461098848518255](url)

lumino has a temporary fix that works
