### ISSUE TITLE
Unable to connect to UniFi Protect

### ISSUE THREAD

**Issue by ahrenstein** [koush/scrypted#209]
Hello,

I've gone as far as blowing away the entire scrypted side of things and reconfiguring from scratch.
I have verified the local user account on the UNVR has the same credentials I'm entering into scrypted, AND it is indeed an Administrator.

Scrypted Details:
```
scrypted: 0.0.165
@scrypted/unifi-protect: 0.0.107
```

UNVR Details:
```
Firmware: 2.3.16
Protect App: 1.21.4
```

Network Details:
```
The path between the two systems is wide open
```

Errors:
```
Invalid login credentials given. Please check your login and password.

refresh failed, trying again in 10 seconds.

Invalid login credentials given. Please check your login and password.

refresh failed, trying again in 10 seconds.

Invalid login credentials given. Please check your login and password.

refresh failed, trying again in 10 seconds.

Invalid login credentials given. Please check your login and password.

refresh failed, trying again in 10 seconds.
```

**Comment by koush** [comment]
ask for help on discord. this is probably a network issue with vlan or something.

**Comment by koush** [comment]
closed since I'm certain this is a user/network issue and not an actual bug.

**Comment by ahrenstein** [comment]
Thanks for pointing me to the right place.

For those that stumble across this in Google searches: The issue turned out to be a UniFi OS bug when restoring from a dead NVR to a new one, local accounts exist somewhere hidden, so when you create a new local account with the same username it doesn't work, and it never will.

Fix: Rename `scrypted` to `scrypted1` as the username for the local account.
