### ISSUE TITLE
Can't add Scrypted Home Automation to Google Home

### ISSUE THREAD

**Issue by tigsfan** [koush/scrypted#21]
When going to the Google Home app  → Setup Device → Works with Google → Scrypted Home Automation , I then login with my Google credentials, and get a notification that "Scrypted Home Automation is linked" followed by "Something went wrong. Try again.". 

I have confirmed that I am logged in to the Scrypted Cloud (API) plugin using my same Google credentials. I am on the latest docker version as well as the latest plugin version for both Google Home and Scrypted Cloud (as well as Core). 

![CleanShot 2021-09-23 at 16 46 21](https://user-images.githubusercontent.com/3330362/134581484-7c8d35ed-d42e-4744-be9b-9304d0b82d0b.png)

**Comment by koush** [comment]
Just ran into this myself, got a fix pending. Was authentication related.

**Comment by koush** [comment]
This should be fixed, please confirm

**Comment by tigsfan** [comment]
Confirmed issue is resolved. Fresh docker pull was required.
