### ISSUE TITLE
Having issues with HSV and face recognition 

### ISSUE THREAD

**Issue by aidenmitchell** [koush/scrypted#222]
I've followed the HSV instructions, but my iPhone only sends me "motion detected" alerts, none that specify what (person, animal, etc.) or face recognition, which is enabled in the Home app. Am I doing something wrong?

**Comment by koush** [comment]
I'm assuming the recordings actually work (which is why I'll be closing this issue): that's not something that is in the scope of this project. What apple is with the video is not within Scrypted's control. the recognition is done on their home hub device, not in Scripted.
