### ISSUE TITLE
device.info is broken

### ISSUE THREAD

**Issue by squishycat92** [koush/scrypted#227]
Hello,

It seems as if a recent update has completely broken the method of using `device.info` to set camera information. The REPL simply throws the following error, regardless of what is passed as input:
```
Uncaught:
Error: info can not be set. Use DeviceManager.onDevicesChanges or DeviceManager.onDeviceDiscovered to update the device description.
    at g.<anonymous> (/index.ts:138:25)
    at DeviceStateProxyHandler.set (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:120:22)
    at checkProperty (/server/node_modules/@scrypted/server/src/plugin/plugin-state-check.ts:13:15)
```

It seems as the method for changing device information has changed; however, I could not find any documentation on this. Could you please look into what could be happening? Thanks!

**Comment by koush** [comment]
yeah, it's a regression that @billyzoellers also mentioned, I'll roll it back.

**Comment by koush** [comment]
025b669e
