### ISSUE TITLE
Update Scrypted on Diet Pi

### ISSUE THREAD

**Issue by uspino2** [koush/scrypted#23]
Installed Scrypted on Diet PI (as a VM on Windows Hyper-V). Runs incredibly smooth, HomeKit cameras respond way better than in Hombridge and HSK is just an amazing job. My question is, how do I update Scrypted or the plugins once there are new versions or upgrades? I see no reference to that in the read me...

Also, any chance you can do a plugin  to turn Apple TV on or off as a switch in HomeKit?

Thanks!

**Comment by koush** [comment]
Plugins will prompt in the plugins section when there are upgrades. There's no autoupdates or notifications for the scrypted server yet. The docker images or git history are when you know there's a release. There will be regular releases every day, as it is an active project, with no "stable" release yet.
