### ISSUE TITLE
Server endpoints

### ISSUE THREAD

**Issue by ggravlingen** [koush/scrypted#230]
Hi,

I'm trying to write an add-on for the Home Assistant project based on this project. To make for a smooth experience for the users, I will use their ingress API which requires some NGINX voodoo. What I've managed so far is to setup and start the app based on your official Docker image. The redirect to `endpoint...` is handled correctly but I'm struggling a bit with the `/login` path and the `/endpoint/@scrypted/core/engine.io/api/` path. 

I'm not yet convinced that the problem with the `api`-path cannot be resolved using NGINX, but I'm note that sure about `/login`. Am I understanding the code correctly that it uses the address of the server to build the string? Would it be possible to rewrite it to use a relative path instead?

**Comment by koush** [comment]
> I'm not yet convinced that the problem with the api-path cannot be resolved using NGINX, but I'm note that sure about /login. Am I understanding the code correctly that it uses the address of the server to build the string? Would it be possible to rewrite it to use a relative path instead?

What code are you referring to?

**Comment by ggravlingen** [comment]
Is this where the path to the login endpoint is set?
https://github.com/koush/scrypted/blob/8b9778afb9b7cc1ad64fde23f85a8939eb75db8a/packages/cli/src/main.ts#L42

I need the URL to look like this (after NGINX has done its thing): `Request URL: http://localhost:7123/api/hassio_ingress/MxejfDp-8-fDnAK2sW4FY9psnkNgASl1mFFVW2k6eS8/login`

This is what I'm seeing: `http://localhost:7123/login` and the server path is my local dev environment for Home Assistant.

What happens when trying to login now is this:
![image](https://user-images.githubusercontent.com/21142447/164993188-8f9d8554-3f02-4e16-a0ca-29a92350c59e.png)

**Comment by koush** [comment]
No, that's the CLI tool. The web ui login happens here:
https://github.com/koush/scrypted/blob/8b9778afb9b7cc1ad64fde23f85a8939eb75db8a/plugins/core/ui/src/client.ts#L45

**Comment by koush** [comment]
And here:

https://github.com/koush/scrypted/blob/8b9778afb9b7cc1ad64fde23f85a8939eb75db8a/plugins/core/ui/src/App.vue#L309

**Comment by ggravlingen** [comment]
Thanks for getting back to me!

Given your answer, I've been pondering over why this doesn't work all day and after doing some testing here tonight it seems I had the correct NGINX-settings but experienced Docker caching issues. Sigh. The login page works now, and I was able to create an account.

I'm left with the API endpoint that doesn't seem to match my NGINX rule `sub_filter '/endpoint/@scrypted/' '%%ingress_entry%%/endpoint/@scrypted/';`. It doesn't quite make sence given that the address to the API seems to be following the similar pattern with `/endpoint/@scrypted/core/engine.io/api/`.

Is this where the API path is defined?
https://github.com/koush/scrypted/blob/e7753d2a8d70630773cb1e4f833e57e57e12958d/packages/client/src/index.ts#L68

**Comment by ggravlingen** [comment]
If I manually create the full link to the API´s end-point, it seems to be working. This is what is should look like after NGINX has done its processing: `http://localhost:7123/api/hassio_ingress/v1Dp9MxnNFhhSHS3h7GA_rW7hg-kc22DQuNj2wheLw8/endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=polling&t=O1X-cZN`

The part `/api/hassio_ingress/v1Dp9MxnNFhhSHS3h7GA_rW7hg-kc22DQuNj2wheLw8` is search/replaced by the `%%ingress_entry%%` string.

**Comment by koush** [comment]
https://github.com/koush/scrypted/blob/8b9778afb9b7cc1ad64fde23f85a8939eb75db8a/packages/client/src/index.ts#L68

**Comment by ggravlingen** [comment]
Thanks! Didn't have time to look tonight but will try tomorrow.

**Comment by ggravlingen** [comment]
Found some time tonight and I've got it working. Thanks again!
