### ISSUE TITLE
about 2 way audio

### ISSUE THREAD

**Issue by phoenixlin2007** [koush/scrypted#232]
I use raspberry pi4(camera module + wm8960 audio hat) as my rtsp camera.The video part works well, but I don't know much about the 2 way audio part. Is there any related document that I can refer to?

**Comment by seanzhang98** [comment]
I think currently only ONVIF cam supports 2 way audio, rtsp cams are not supported.

**Comment by peros550** [comment]
From a camera's vendor perspective, what is required so their product supports two way audio? Do they need to support it through the ONVIF specification? Could they just support it through RTSP?

**Comment by koush** [comment]
onvif yes
