### ISSUE TITLE
Docker container keeps restarting

### ISSUE THREAD

**Issue by Tellicious** [koush/scrypted#235]
Hi,
I just installed Scrypted as a Docker container on my RPi 4 using the commands provided here but am not able to get it running nor to access the GUI.

If I run “docker ps” I see the koush/scrypted container with status “restarting (134)” without any port and nothing is answering at port 10443. Regardless of how much I wait, it cannot get “Up”

Tried removing the image and re-pulling it but no luck

On the same RPi I’m running PiHole, Homebridge, UniFi Controller and Transmission server as well. Can it be maybe a port conflict with any of them?

**Comment by koush** [comment]
you're probably running on a buster host.
