### ISSUE TITLE
Homecam for HomeKit crash's Scrypted 

### ISSUE THREAD

**Issue by Tesla-P100FX** [koush/scrypted#237]
i am running a Raspberry Pi Scrypted Server(0.0.175) with Ring, FFMPG, Homekit , PAM and snapshot plug ins.   if you try to use Homecam for Homekit wither on an apple tv or phone it crashes Scrypted.  New to the platform so unsure what logs i should provide

**Comment by koush** [comment]
need a docker console log or something.
