### ISSUE TITLE
Amcrest Doorbell Support?

### ISSUE THREAD

**Issue by pageb018** [koush/scrypted#24]
First off, this project incredible. Using my Amcrest cameras with HomeKit secure video is fantastic.

I would hoping you could add support for doorbell, specially the Amcrest doorbells. 

Keep up the great work!

**Comment by pageb018** [comment]
I should specify that I mean adding to HomeKit as doorbell devices. I can currently add them doorbells as cameras.

**Comment by koush** [comment]
Should be easy. Hop into discord to help out.

**Comment by koalaeagle** [comment]
I am interested in this. I was thinking of picking up one of these doorbells.

**Comment by koush** [comment]
implemented

**Comment by pageb018** [comment]
Awesome!

Can I ask how it was implmented? I could already add the doorbell's as cameras, my question was more about adding them as doorbells. 

I believe homekit needs access to the push button event, although I could be wrong.

Happy to test, I have two AD410's.

**Comment by pageb018** [comment]
Ok. I see the updates and have enabled my two doorbells. 

However, while I see the option for doorbell press notifications, and have enabled them. They do not seem to work. I suspect this is due to scrypted having no access to the button press event. Not exactly sure how to solve this. 

When using the doorbell in Homekit via Home Assistant, I set up this project, 

https://github.com/dchesterton/amcrest2mqtt

and that allowed the doorbell to pass button presses to Home Assistant and then to HomeKit.

**Comment by koalaeagle** [comment]
That was fast progress! Without the button press events do you just receive motion events? Do you still receive button press events another way (perhaps Amcrest app)?

I tried to join the Discord but the link seems expired.

**Comment by pageb018** [comment]
> That was fast progress! Without the button press events do you just receive motion events? Do you still receive button press events another way (perhaps Amcrest app)?
> 
> I tried to join the Discord but the link seems expired.

The button presses are working! The only thing left is two-way talk. Which would just be incredible.

**Comment by koalaeagle** [comment]
> > That was fast progress! Without the button press events do you just receive motion events? Do you still receive button press events another way (perhaps Amcrest app)?
> > I tried to join the Discord but the link seems expired.
> 
> The button presses are working! The only thing left is two-way talk. Which would just be incredible.

That is excellent! Any idea if two way audio is on the roadmap or even a possibility?

**Comment by koalaeagle** [comment]
I went ahead and ordered an AD410. I will play around once it arrives!

**Comment by Kirorus** [comment]
I use this Amcrest plugin with Dahua VTO2211 and it work fine. I can receive motion and button press events. But I have problem with audio when use Rebroadcast Plugin.
Without Rebroadcast Plugin - I have audio in live stream and in saved clips (HomeKit Secure Video)
With Rebroadcast with COPY in transcoding - no audio in stream, but it work in recorded clips
With Transcode - no audio in stream, normal in clips
with PCM audio - I have audio in stream and in saved clips. But this audio is wrong. the sound is distorted.

Audio codec in my camera is pcm_s16be

**Comment by aae55555** [comment]
@koalaeagle  - did you manage to test the AD410? Does object/people detection work in Homekit? The option doesn't show up with my AD110, i'm assuming because that doorbell doesnt support it.

**Comment by willquill** [comment]
> @koalaeagle - did you manage to test the AD410? Does object/people detection work in Homekit? The option doesn't show up with my AD110, i'm assuming because that doorbell doesnt support it.

I'm not koalaeagle, but I just setup an AD110 with Scrypted, and yes - it does object/people detection with HomeKit. In iOS > Home app > tap the camera > tap settings icon > Notifications > enable Activity Notifications, and you can configure the settings for various types of motion (people, animals, vehicles, packages).

Also, you can go to iOS > Home app > tap the camera > tap settings icon > Face Recognition > enable, and then in the notifications you get, instead of saying, "Someone is at your door," it will tell you the person at your door if you've given them a name in your photo library.

**Comment by koalaeagle** [comment]
@ari-za yes, it has been working well. It should work fine for AD110 too, I see users in Discord with that model, along with supporting evidence from willquill. 

I have another older "Smarthome" lineup Amcrest camera that has similar functionality to AD110. Even though it is missing the person detection through Amcrest, that actually isn't relevant with scrypted. All we need for scrypted is the motion detection (has to be enabled btw), and during each motion event HomeKit will do processing for object/people detection (I believe done via the home hub device).

**Comment by koalaeagle** [comment]
I recommend jumping in the Discord if you are still stuck, it is quite an active and helpful group.

**Comment by eugr** [comment]
Does two-way audio work via HomeKit?

**Comment by willquill** [comment]
Yes it does!Sent from my iPhoneOn Sep 25, 2022, at 12:27 AM, eugr ***@***.***> wrote:﻿
Does two-way audio work via HomeKit?

**Comment by papcio84** [comment]
Guys, just installed scrypted and amcrest plugin and integrated by homekit. 2 issues i see:
1. Notifications are provided sporadically
2. Only one way audio is possible

i have dahua vto.
