### ISSUE TITLE
Scrypted causing issues in Unifi Protect

### ISSUE THREAD

**Issue by pctony** [koush/scrypted#249]
Hey folks, firstly want to say thanks for an awesome tool - it has been great.  

So.  I have been having issues for several weeks now, that I have been debugging with the help of the quite slow Unifi support team.   The issue manifests itself as this: 

![CameraIssues](https://user-images.githubusercontent.com/78299/169070065-c09d5ed0-a64c-4371-b54c-7eca789facfc.png)

This would happen to all my cameras, at exactly the same time regardless of them being PoE, Injected PoE, Wifi, etc.  Essentially the UNVR was the common factor in all of these issues.   Well, after 2 weeks of resetting my UNVR, re-adopting cameras, and so many other pointless steps we finally find issues related to RTSP. 

``` shell 
2022-05-08T17:29:03.687Z 3 :202:Accept - Inbound connection accepted: (Far: 192.168.1.163:54992; Near: 192.168.1.2:7441) CTCP(76) <-> TCP(162) <-> ISSL(163) <-> [RTSP(164)] 

2022-05-08T17:29:03.726Z 3 :459:SignalStreamRegistered - Stream ONP(62) with name `68D79AE552E0_0` from protocol RTSP(164) registered to origin application `evostreamms` 

2022-05-08T17:29:10.728Z 1 :194:PerformIO - Unsent output buffer size exceeds threshold 42022-05-08T17:29:10.728Z 1 :423:FeedDataTcp - Unable to send raw rtcp audio data 

2022-05-08T17:29:10.728Z 1 :293:SendRtp - Unable to feed data
```

As soon as I disabled scrypted.app all of the "camera disconnects" did not re-occur.   

Unifi OS: 2.4.8
Unifi Protect: 1.21.6

**Comment by koush** [comment]
This is a bug with Unifi Protect failing when the RTSP buffer fails. You can try using the HomeKit and rebroadcast betas, and setting your RTSP parser to FFMPEG UDP. This will just mask the issue though. This is ultimately a Unifi firmware bug.

**Comment by koush** [comment]
Incidentally you're the only one to ever report this (I've got ~10 cameras myself). But most people are running UDM or UDM pro. I have heard the UNVR is pretty flaky.

**Comment by pctony** [comment]
Interesting, I have 12 or 13 now (cameras that is).  Have been using the UNVR to spread the io load across several platters, and keep the load of the UDMP.

**Comment by koush** [comment]
https://www.reddit.com/r/UnifiProtect/comments/1awdtxi/rtsp_and_unifi_protect_a_warning/
