### ISSUE TITLE
Google Device Access plugin: Missing Token

### ISSUE THREAD

**Issue by GoWithitRoger** [koush/scrypted#25]
When setting up the Google Device Access plugin the login process seems to proceed as it should. But near the end it looks as though the browser is directed possibly an improper address for scripted, at https://home.scrypted.app/_punch/authed..., where a black white page with simply "not registered" is displayed.

I see in the [plugin documentation](https://www.npmjs.com/package/@scrypted/google-device-access) it mentions "If using a remote server, edit .vscode/settings.json to specify the IP Address of the Scrypted server." But this is all running on one computer.

**Comment by koush** [comment]
You'll also need the @scrypted/cloud plugin (search for cloud). Hop on discord if you have other questions
