### ISSUE TITLE
Settings All Blank

### ISSUE THREAD

**Issue by cheme75** [koush/scrypted#254]
Not sure why, but every screen I enter for the cams and plugins have blanks for settings - getting frustrated since I need to deaden the sensitivity for the motion detection - its windy so a good day to adjust sensitivity settings.

![Scrypted](https://user-images.githubusercontent.com/16415255/169655181-bc54a9dd-c366-4745-9d28-bb306c276682.jpg)

**Comment by koush** [comment]
try disabling pam Diff and opencv. sometimes is conflicting and crashing.

**Comment by cheme75** [comment]
> 

I turned off Pam. But then had OS and Firefox  updates so just rebooted. Return to UI and all normal again. Could not get any transpose=1 (or 2) to work in transcode settings. Gave up trying - too tired now. Still wondering if ffmpeg plugin might do it.
