### ISSUE TITLE
Ring Plugin Reqest

### ISSUE THREAD

**Issue by cjones813** [koush/scrypted#26]
Hey. Great work on this, its fantastic! Everything just works, I have moved everything over from homebridge and it was seamless!

One thing that I am missing that I can’t move from homebridge would be the ‘ring’ plugin. It would brilliant if you could add support for that. The homebridge ring plugin is great but I would prefer to have all my cameras showing on one dashboard and one method of feeding to homekit.

I have a few ring cameras and the doorbell. Is that something you could add in the future? Would it be easy to adapt the ring homebridge plugin to make it scrypted compatible?

Thanks!

**Comment by koush** [comment]
If you can DMZ a ring camera for me, I can try

**Comment by cjones813** [comment]
Hi @koush I think it would be via an api instead of direct access to the camera.

https://github.com/dgreif/ring

**Comment by koush** [comment]
Does the SIP access on the camera only work through the cloud?

**Comment by cjones813** [comment]
Yes unfortunately. No local network access to the camera. I have a camera here I could set up on a test account for you to have a play about with?

**Comment by cjones813** [comment]
With the homebridge plugin, you would enter the username and password for the ring account. This would then generate a access token 'key'. Paste the key into the homebridge config and it would automatically find all the cameras and doorbells on my ring account using the api.

**Comment by cjones813** [comment]
https://www.smarthomepoint.com/ring-doorbell-local-no-cloud/

That the above link gives examples of how it can be done. I think the sip calls can only be used via this api.

https://github.com/dgreif/ring

https://github.com/dgreif/ring-client-example

https://github.com/dgreif/ring/tree/master/examples

**Comment by Marfre888** [comment]
Demand for this will be insane.. eagerly waiting.. thank you for any time and effort you put into this..

**Comment by luluhoc** [comment]
This would be a game changer

**Comment by cyberhomie** [comment]
Eagerly waiting for this...

**Comment by koush** [comment]
If someone wants to give me their ring account credentials, I can try. Message me on discord.

**Comment by koush** [comment]
> https://www.smarthomepoint.com/ring-doorbell-local-no-cloud/
> 
> That the above link gives examples of how it can be done. I think the sip calls can only be used via this api.
> 
> https://github.com/dgreif/ring
> 
> https://github.com/dgreif/ring-client-example
> 
> https://github.com/dgreif/ring/tree/master/examples

looks doable.

**Comment by koush** [comment]
done. it's super rough but is now available.

https://github.com/koush/scrypted/tree/main/plugins/ring

![image](https://user-images.githubusercontent.com/73924/149871155-e9fcaee0-09c0-4089-aba9-576d64723fe2.png)

**Comment by koush** [comment]
please do not open any further ring bugs on this repository. I am sure there are a lot. join discord and report them directly in the #ring channel.
