### ISSUE TITLE
Scrypted Ring - Device won't stay deleted/Homekit disabled

### ISSUE THREAD

**Issue by brianjw** [koush/scrypted#267]
Hello,

I need the capability to hide specific device ID's or only show specific location ID's (like homebridge-ring). I recently transferred the cameras from homebridge ring to Scrypted and one of the first things I noticed was that a camera from a separate location was pulled in. 

I've tried to do a few things:
- I deleted the device. It gets automatically re-added after a reboot or after the Scrypted docker container updates.
- I kept the device but removed it from all Scrypted operations (Homekit, Prebuffer, etc). It appears to re-add itself to Homekit after some time (not sure what causes this). 

Nevertheless, a simple configuration option similar to what the homebridge plugin offers would solve this - Location ID filtering and/or Device ID filtering. 

Thanks for your help & keep up the great work on Scrypted!

**Comment by koush** [comment]
yes, just uncheck everything so its not synced to homekit. filtering is not done at the import level. it makes plugins unnecessarily complex.

**Comment by brianjw** [comment]
Ok, I have everything unchecked. It seems to potentially add itself back to Homekit after a while, but I will monitor it. Thanks for quick response!
