### ISSUE TITLE
Update Docker Container without losing Data (Synology Docker/Portainer)

### ISSUE THREAD

**Issue by lucas2350d** [koush/scrypted#269]
Hello, I wanted to update my Docker container to the latest version. For this I downloaded the latest image and then pressed reset in the settings (I read so on Reddit).
But after that everything was reset to factory defaults. How can I update the image without losing data?
Thanks a lot

**Comment by cheme75** [comment]
Disclaimer - I’m a new user and not an expert!  I have not yet had to update scrypted, just pluggins, but this update method is working well for my docker-Wyze-bridge. I’m using docker-compose. I created separate directories, like a “scrypted” directory I can get to easily where I put my yml file. I can then cd to that directory, run “docker-compose pull” to get latest update. Then “docker-compose up -d“ to recreate and run the container. There is also “docker image prune” to remove unused/old images. None of my settings have been lost yet. Within the ui, with watchtower running, pluggins will show if there’s an update. So far plug-in settings have remained after update. If you’re not using docker-compose, then try discord, seems more active for support.

**Comment by miwagner1** [comment]
You probably forgot to set a data volume for persistent storage.
