### ISSUE TITLE
Homekit App update interval scrypted:1min vs native: 10sec

### ISSUE THREAD

**Issue by bondskin** [koush/scrypted#270]
Not sure if this behaviour is intended or can be changed.

When I watch my cams in the Homekit app, the scrypted cams are updated / refreshed every 1min.
My native homekit cams are updated every 10sec.
![IMG_5387](https://user-images.githubusercontent.com/55050117/170954810-87b6f857-b863-4f00-b373-c0f8961f53e2.jpg)

**Comment by koush** [comment]
use accessory mode. home app bug.
