### ISSUE TITLE
Person and vehicle detection

### ISSUE THREAD

**Issue by crazyracer98** [koush/scrypted#277]
I think it would be nice to not only have hollistic motion detection using general image algorithms, but also stuff like person / human, animal and vehicle detection for advanced motion detection.

Example for human detection:
- https://thedatafrog.com/en/articles/human-detection-video/
- https://google.github.io/mediapipe/solutions/pose.html

Example for vehicle detection:
- https://kalebujordan.dev/real-time-vehicle-detection-using-python/

**Comment by koush** [comment]
use the tensor flow lite plugin. also supports coral tpu.

this can't be added to homekit. they do their own processing.
