### ISSUE TITLE
Slow ONVIF snapshot performance

### ISSUE THREAD

**Issue by IGx89** [koush/scrypted#28]
Hello! Really intrigued with your application and have been trying it out. One thing I noticed is that taking snapshots on my ONVIF camera (Dahua) is unusually slow: appears to take 2-10 seconds on average (running in a Docker container on a Synology DS220+, pulling a 4MP image). Looking over the code I noticed that the snapshot URI isn't cached, so every snapshot request appears to involve requesting both the snapshot URI and the image itself. I haven't had time to investigate actual request durations yet, but wanted to throw it out there as a potential (easy?) performance improvement to cache the snapshot URI.

An alternative solution could be a setting to override the snapshot URL, but for ONVIF that probably wouldn't be very useful for most people (since finding the right URL could be tricky).

Low priority -- if this annoys me enough and I decide to keep using this app, I may take this up as a good first PR as well :)

**Comment by koush** [comment]
fixed, thanks for the report

**Comment by koush** [comment]
plugin is updated too

**Comment by IGx89** [comment]
That has to be a record for fastest fix ever! Thanks a lot :). I'll try it out later today and let you know my experience!

**Comment by koush** [comment]
resolved similar issue with RTSP url as well.
