### ISSUE TITLE
Ring camera not response

### ISSUE THREAD

**Issue by ryadraws** [koush/scrypted#284]
I'm currently running ios16 which hasn't had any effect on scrypted to my knowledge. Yesterday, I tried to check my ring camera feed in the home app and I have a consistent no response message. The cameras are working as I can see them in the native ring app. Does anyone else have this issue or know how I can fix it? 

Thank you

**Comment by JeffGoldner** [comment]
I'm having lots of issues. ios15, latest server 0.1.7, ring plugins 0.82 and 0.80. Camera appears offline frequently, motion detection events almost never seen. I'm about to work backwards on the container versions.

**Comment by jctull** [comment]
There have been quite a few reports of this no discord. I was not getting useful logging to troubleshoot. If you are, the logs will be helpful in trying to resolve these problems. Most people have rolled back to 0.75 as it appears to not have this problem. If you have certain Ring devices, their support may have been added in versions >0.75.

**Comment by koush** [comment]
do you have motion events in the camera's events tab in scrypted? 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/73924/175784238-a6c7b2c9-e9aa-411f-8246-a9f833e93745.png">

**Comment by koush** [comment]
I am deleting comments unrelated to this bug. If you have issues with recordings, use a separate issue.

**Comment by koush** [comment]
If live streaming isn't working, read the HomeKit plugin readme for resolutions.
