### ISSUE TITLE
Add custom manufacturer and model characteristics into Homekit

### ISSUE THREAD

**Issue by 0xgrm** [koush/scrypted#285]
Hi,

Thanks a lot for this software. It runs fantastically with an old hacked Yi Home 1080p camera.
I would like to be able to change the manufacturer, model and serial number characteristics of the camera in Homekit.

It's absolutely not urgent, more of a cosmetic thing. :-)

**Comment by squishycat92** [comment]
This is already possible using the REPL, see #30.


Specifically, you should use the REPL to set the `device.info` properties, similarly to this:
```
device.info = {
    model: 'Yi Home 1080p Camera',
    manufacturer: 'Yi Technologies',
    version: 'Yi Hack',
    firmware: '1.0.0',
    serialNumber: '1234567890QWERTY'
}
```
A small note about the snippet above: you can set the software version of the camera, but this doesn't actually show in the Home app.

**Comment by 0xgrm** [comment]
Thank you for your answer, I am sorry I didn't see that earlier. That's very cool.

Keep up the good work!

**Comment by MichlW** [comment]
Thank you very much.
This should be documented in the Wiki or configurable through HomeKit Integration/Extension!
