### ISSUE TITLE
Container reboot loop

### ISSUE THREAD

**Issue by codyc1515** [koush/scrypted#286]
My container was on a reboot loop with latest build installed on Raspberry Pi 4 running latest Raspbian.

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
XXX koush/scrypted "docker-entrypoint.s…" 3 hours ago Restarting (134) 33 seconds ago scrypted

Checking the logs I could see this error repeatedly:

Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.

I then found this StackOverflow post https://stackoverflow.com/questions/69775057/docker-image-fails-to-run-on-raspberry-pi-with-strange-node-error which suggests to add --security-opt seccomp:unconfined to the container which worked for me.

Not sure what is the underlying cause.

**Comment by koush** [comment]
you're on buster, not bullseye.

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues?q=is%3Aissue+GetCurrentTimeInMicroseconds
