### ISSUE TITLE
Dashboard-Button missing

### ISSUE THREAD

**Issue by romeoalfa1975** [koush/scrypted#289]
I can't find the Dashboard-Button in the menu on the left.
<img width="334" alt="Bildschirmfoto 2022-06-23 um 11 56 05" src="https://user-images.githubusercontent.com/48555853/175272477-7955ffec-f65e-4e0e-b62b-7a3afdb8ea8e.png">

**Comment by cheme75** [comment]
It was removed in recent updates. Can’t recall exactly why - probably somewhere in the release notes.

**Comment by romeoalfa1975** [comment]
Thanks for the answer! Is there another way to display the camera image including the red rectangles for the moving objects?

**Comment by cheme75** [comment]
> Thanks for the answer! Is there another way to display the camera image including the red rectangles for the moving objects?

I'm not sure - I'm using wyze docker bridge to send the streams to scrypted and then view them in homekit on iphone. I've only started testing opencv for motion and do get motion notifications but I'm not seeing the motion taggiing rectangle in homekit - I think I probably have to get icloud+ and enable the AI detections. There may be other options, but I'm still learning myself.

**Comment by koush** [comment]
> Thanks for the answer! Is there another way to display the camera image including the red rectangles for the moving objects?

from the individual camera management yeah.
