### ISSUE TITLE
ONVIF: Allow using sub profile

### ISSUE THREAD

**Issue by IGx89** [koush/scrypted#29]
Currently the ONVIF plugin always uses the main profile. In my case that's not ideal, since my main profile is 4 MP which is too much bandwidth/resolution for streaming (such as HomeKit). In my case the third profile (subtype=2) is 1 MP (1280x720) which works much better. It would be nice to have an easy way to select that other profile to use instead, causing both the stream and the snapshot to switch to that resolution. I can override the stream URL as a workaround, though that still keeps my snapshot image as 4MP.

Again, low priority, mostly a nice-to-have.

**Comment by koush** [comment]
I was in the middle of this already actually, as it would bring it inline with Unifi support, where you can disable channels completely from use. This however is a stopgap.

I have been suggesting that people modify their streaming configurations on their cameras to be in line with HomeKit expectations. Ie, configure the main channel for 1080p, and the sub channel with something lower, like 480p.

HomeKit does video stream negotiation, and having several options all available will be necessary for future improvements when that support is built into the Scrypted side.

**Comment by koush** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/73924/135916130-d2fdb951-68be-415e-89e9-7802ddf587b0.png">

k done

**Comment by IGx89** [comment]
That would be pretty cool! I need my main stream at 4 MP due to wanting a high-quality continuous recording (done by NVR software) and my subchannels max out at 480p and 720p respectively (seems common for POE cameras) so that probably wouldn't work well for me, but it is an efficient way to do it. Ideally I'd run my main stream using h265 too, which HomeKit doesn't support, which would be another issue.

Ideal in my situation would be a Synology Surveillance Station plugin, but I don't think it would gain me personally much beyond the already excellent ONVIF plugin (beyond a faster snapshot image) -- it strangely doesn't seem to support trascoding video.

**Comment by IGx89** [comment]
Thanks a lot! Will test it out soon.

**Comment by IGx89** [comment]
Partly working. The `jpegSnapshot` method still is calling `getMainProfileToken`, ignoring the fact that I disabled the main media profile. It needs to use a non-disabled media profile.

**Comment by koush** [comment]
> Partly working. The `jpegSnapshot` method still is calling `getMainProfileToken`, ignoring the fact that I disabled the main media profile. It needs to use a non-disabled media profile.

k will fix that, on my onvif camera the snapshot urls resolved ot the same url, regardless of profile.

**Comment by koush** [comment]
k published

**Comment by IGx89** [comment]
Thank! The spec says "The JPEG settings (like resolution or quality) should be taken from the profile if suitable", so changing the media profile does indeed seem the correct thing to do. Sadly, it does appear that my camera functions like yours, still returning the main profile's snapshot even if another profile is used :(. Oh well!
