### ISSUE TITLE
ONVIF does not support TCP connection

### ISSUE THREAD

**Issue by Hye-Dev** [koush/scrypted#290]
ONVIF only supports http and not direct TCP connection, making it not compatible with some of my cameras.

**Comment by koush** [comment]
not sure what you mean

**Comment by Hye-Dev** [comment]
With ONVIF there's 3 protocols that can be used to connect. HTTP, a TCP port, or a UDP port. The ONVIF plugin appears to only support HTTP.

**Comment by koush** [comment]
Seems to be a limitation of the underlying library:
https://github.com/agsh/onvif
