### ISSUE TITLE
Can't get install script to run without errors, on fresh install. 

### ISSUE THREAD

**Issue by lagefrequentie** [koush/scrypted#294]
Hi all,

I keep on getting this error when running this script on a fresh install.
Hope that anybody knows whats going wrong and how to fix it.
Thanks in advanced,
regards
Bas

pi@raspberrypi:~ $ curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-dependencies-linux.sh | sudo SERVICE_USER=$USER bash
ignoring ARG BASE=16-bullseye
Installing nodejs repo

## Populating apt-get cache...

+ apt-get update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done
E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error executing command, exiting
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error during previous command.

![IMG_5366](https://user-images.githubusercontent.com/24866820/175804337-cb23f63c-1cc7-48fd-8561-ca2877e39dcb.jpg)

**Comment by koush** [comment]
pi os too old. need to be on bullseye.

**Comment by lagefrequentie** [comment]
2022-04-04-raspios-bullseye-arm64-lite.img this image is the image that is used.

**Comment by koush** [comment]
not sure what's wrong, your apt is busted.

**Comment by lagefrequentie** [comment]
got it running on synology via docker now.
tanks in advanced
