### ISSUE TITLE
2022-04-04-raspios-bullseye-arm64-lite.img is the image i used and i got nothing but errors.

### ISSUE THREAD

**Issue by lagefrequentie** [koush/scrypted#295]
Hi all,

I keep on getting this error when running this script on a fresh install. (image = 2022-04-04-raspios-bullseye-arm64-lite.img)
Hope that anybody knows whats going wrong and how to fix it.
Thanks in advanced,
regards
Bas

pi@raspberrypi:~ $ curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-dependencies-linux.sh | sudo SERVICE_USER=$USER bash
ignoring ARG BASE=16-bullseye
Installing nodejs repo
Installing the NodeSource Node.js 16.x repo...
Populating apt-get cache...

    apt-get update
    Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
    Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
    Reading package lists... Done
    E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
    N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
    E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
    N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
    Error executing command, exiting
    Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
    Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
    Reading package lists... Done
    E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
    N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
    E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
    N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
    Error during previous command.
![IMG_5366](https://user-images.githubusercontent.com/24866820/175828758-f3662a49-dc8a-4c1c-ad95-c8a56af22b44.jpg)

**Comment by koush** [comment]
not a scrypted issue.
