### ISSUE TITLE
Web interface blank after 0.1.11 update

### ISSUE THREAD

**Issue by jadomski** [koush/scrypted#298]
After upgrading to 0.1.11 the web interface does not show any items apart from the menu bars. I have attached a screenshot. Clicking on a menu item on the left hand side allows it to be selected, but nothing loads on the page. Tested with Safari and Firefox on multiple devices.

<img width="1505" alt="Screen Shot 2022-06-28 at 11 00 50 pm" src="https://user-images.githubusercontent.com/7396502/176185685-4d8e0832-c585-4b82-8ebc-b8b8d0ab90ac.png">

**Comment by koush** [comment]
can you access by ip instead of hostname, and update all plugins? then reload the page there a few times?

**Comment by koush** [comment]
Fixed by bumping min core version. this will sort itself out with a core update (or a server update that triggers a core update).
