### ISSUE TITLE
Cannot install on windows pc

### ISSUE THREAD

**Issue by benov84** [koush/scrypted#3]
I've got elifecycle error when trying to run server
Npm install completed successfully

**Comment by koush** [comment]
log please

**Comment by benov84** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle scrypted@1.0.0~preserve: scrypted@1.0.0
6 info lifecycle scrypted@1.0.0~serve: scrypted@1.0.0
7 verbose lifecycle scrypted@1.0.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle scrypted@1.0.0~serve: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Benov\Desktop\scrypted-main\server\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Benov\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Benov\AppData\Local\Programs\Python\Python37-32\;C:\Users\Benov\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Benov\AppData\Local\Programs\Python\Python39\;C:\Users\Benov\AppData\Local\Microsoft\WindowsApps;C:\Users\Benov\AppData\Local\Yarn\bin;C:\Users\Benov\AppData\Local\GitHubDesktop\bin;C:\Users\Benov\AppData\Roaming\npm
9 verbose lifecycle scrypted@1.0.0~serve: CWD: C:\Users\Benov\Desktop\scrypted-main\server
10 silly lifecycle scrypted@1.0.0~serve: Args: [ '/d /s /c', 'npm run build && node dist/scrypted-main.js' ]
11 silly lifecycle scrypted@1.0.0~serve: Returned: code: 1  signal: null
12 info lifecycle scrypted@1.0.0~serve: Failed to exec serve script
13 verbose stack Error: scrypted@1.0.0 serve: `npm run build && node dist/scrypted-main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid scrypted@1.0.0
15 verbose cwd C:\Users\Benov\Desktop\scrypted-main\server
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error scrypted@1.0.0 serve: `npm run build && node dist/scrypted-main.js`
22 error Exit status 1
23 error Failed at the scrypted@1.0.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by koush** [comment]
can you `git pull` and try again? windows isn't really supported, but I am able to run it on my windows machine.

**Comment by benov84** [comment]
unfortunately doesn't work

**Comment by koush** [comment]
Ran into this issue and I believe this was fixed.
