### ISSUE TITLE
Possibly Memory Leak

### ISSUE THREAD

**Issue by tomtom215** [koush/scrypted#300]
Hello,

I LOVE this application as it enables me to connect my Amcrest cameras to Homekit!

However I noticed it seems there is a memory leak that fills up my 128gb of ram every 1-2 days.

Setup:
- Docker Container - Latest (unraid)
- Amcrest, Homekit, Rebroadcast and Transcoding Plugins
- 2 connected cameras, no transcoding options (just Adjustable VBR selected by default)

Restating the container immediately frees up the ram

**Comment by koush** [comment]
Can you determine if restarting a specific plugin frees the memory. Each plugin is its own process.

**Comment by tomtom215** [comment]
Correct. To be specific I am running Unraid 6.9.2

**Comment by tomtom215** [comment]
Woke up this morning to full RAM again today. I reloaded each of the plug-ins via the UI but no memory freed up.

I did notice in the events and docker logs that the Rebroadcast plug-in seemed to have failed authorizing one of the cameras (even though it worked before and after a reboot).

This was the only error I saw anywhere, it was in the rebroadcast event logs and nothing changed:
`unhandledRejection Error: Operation Timed Out`

**Comment by koush** [comment]
Did you check which process was holding rhe memory?

**Comment by tomtom215** [comment]
Looks like it was the Rebroadcast plugin this morning. Sorry I don't have more logs as I running out the door for vacation. Reloading that plugin without bouncing the container freed up all of the ram

**Comment by diothar** [comment]
I have unraid and have noticed this as well.  What would you like for me to gather? 

I am going to be moving my scrypted deployment to the same mini pc that handles my avahi, but I could gather details from unraid before I kill the docker.

**Comment by koush** [comment]
I think I fixed this, please confirm.

**Comment by tomtom215** [comment]
I have not had any further problems since this comment. Closing now. Thanks again for your hard work!
