### ISSUE TITLE
Windows Local Installation Issue

### ISSUE THREAD

**Issue by simclancy** [koush/scrypted#301]
`You cannot call a method on a null-valued expression.
At line:1 char:1
+ $USER_HOME_ESCAPED = $env:HOME.replace('\', '\\')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull`

**Comment by koush** [comment]
can you try again, might be fixed

**Comment by simclancy** [comment]
> can you try again, might be fixed

Ok now it doesnt give me an error but i cant see if it is running, the site https://localhost:10443/ or replacing localhost with the actual host IP doesnt do anything.

**Comment by simclancy** [comment]
So i checked windows services and saw Scrypted there but its not running, and when i force it to run, it stops on its own, same thing after rebooting.

**Comment by koush** [comment]
The .scrypted/daemon folder in your user home directory will contain logs. Can you attach those.

**Comment by simclancy** [comment]
Hi, your latest revision fixed the issue, i apologize for not attaching the logs in time to help you out. Thanks anyway!

**Comment by koush** [comment]
> Hi, your latest revision fixed the issue, i apologize for not attaching the logs in time to help you out. Thanks anyway!

@simclancy incidentally, do you have VS Code installed?

**Comment by simclancy** [comment]
> > Hi, your latest revision fixed the issue, i apologize for not attaching the logs in time to help you out. Thanks anyway!
> 
> @simclancy incidentally, do you have Visual Studio installed?

Hi yes i do have VS Code

**Comment by koush** [comment]
Sorry, I mean visual studio, not vs code.
