### ISSUE TITLE
How to trigger a doorbell via HTTP request

### ISSUE THREAD

**Issue by Vizards** [koush/scrypted#302]
I'm moving HomeKit video camera from HomeBridge to Scrypted. The support for HomeKit Secure Video is very attractive for me.

In HomeBridge, I used a plugin named [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg) to create a virtual camera.  And I've implemented a doorbell using esp32 chip. the doorbell sent an HTTP request to HomeBridge to make the virtual camera's doorbell ring. But in Scrypted, I only found an implementation of receiving MQTT messages from a specific model of doorbell.

Can anyone add an instruction for:
1. How to send an HTTP request to Scrypted to make doorbell ringing?
2. Make my esp32 doorbell to send MQTT messages is realizable. If Scrypted can only accepts MQTT messages,  what is the format of the MQTT messages? 

Thanks in advance!

**Comment by koush** [comment]
You can use the dummy switch plugin to create a switch/sensor and Webhook plugin to trigger it. Call the turnOn method to trigger the dummy switch sensor, and have it auto reset.

**Comment by Vizards** [comment]
@koush 

Thanks for your help. I finally have successfully added a webhook based doorbell in Scrypted. I found that only WebHook plugin is enough. I created a new doorbell template based on the `switch-trigger-webhook.ts` template:

```javascript
class WebhookDoorbell implements HttpRequestHandler {
    timeout: any;

    async onRequest(request, response) {
        if (response) {
            response.send('ok');
        }
        device.binaryState = true;
        // reset the doorbell after 1 second.
        clearTimeout(this.timeout);
        this.timeout = setTimeout(() => device.binaryState = false, 1000);
    }
    binaryState() {
        return device.binaryState
    }
}

device.handleTypes(ScryptedInterface.BinarySensor);

endpointManager.getInsecurePublicLocalEndpoint(device.nativeId)
    .then(endpoint => console.log('doorbell webhook:', endpoint));

export default WebhookDoorbell;
```

After setting its type to sensor, I can integrate it to a new doorbell(camera) following the steps in the wiki. Then I got a camera with a doorbell. But when I turn on the camera in the Home App, HomeKit reports "a button has not been configured" (maybe different due to translation). Although I'm a little confused by the prompt, it works well. I appreciate it.

**Comment by koush** [comment]
Ah ok, yeah if you can code writing a script works too, and is much more customizable. Webhook plugin is the code-free way to do the same thing.

**Comment by koush** [comment]
> But when I turn on the camera in the Home App, HomeKit reports "a button has not been configured" (maybe different due to translation).
Scrypted adds a button that can be used to trigger homekit automations. You don't need to configure it if you don't need that.

**Comment by longzheng** [comment]
In case anyone else is looking for a tutorial on how to do this with the dummy switch and webhooks plugins

1. Install the `@scrypted/dummy-switch` plugin
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/484912/210941405-fc589a17-ce62-4956-8752-908c7699683c.png">

2. Install the `@scrypted/webhook` plugin
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/484912/210941317-19f9bd59-b77b-4166-bc09-68ed1ea71f02.png">

3. Open the "Dummy Switch Plugin" and click "Add new", name it "Doorbell" (or whatever you want to call it)
<img width="1941" alt="image" src="https://user-images.githubusercontent.com/484912/210941571-f8e6134f-1968-4677-9e98-5edd38449ecb.png">

4. Change the "Reset sensor" to 1 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/484912/210941606-ecc188a2-20ae-4563-b1f0-b9b26541914f.png">

5. Click "Extensions" and enable the "Webhook Plugin" extension 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/484912/210941691-721a6085-da32-44d3-a5bd-15a2c93520e0.png">

6. Click "Webhook" and select "OnOff" from the dropdown
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/484912/210941740-1836346f-fe00-4f06-9963-52029d2a5f3d.png">

7. Click the "Console" link to find the webhook URL
<img width="1983" alt="image" src="https://user-images.githubusercontent.com/484912/210941787-fb66cf9c-a793-4856-a6e9-dc383097d733.png">

In my case my webhook URL is `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd` so to turn it on I can use `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd/turnOn` to trigger it

8. Click on "Device Groups" in the sidebar and name it whatever you want your doorbell camera to be called
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/484912/210942009-a46cc276-e96b-474a-9ae2-72ae069749fb.png">

9. In "device interfaces", select your camera and the doorbell dummy switch you just created
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/484912/210942286-50138b61-3805-4a87-bdd1-3ffb33def320.png">

10. Click on "Edit" tab and set the "Type" as "Doorbell"
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/484912/210942363-eaa98cbd-57ed-47e8-b0a1-014ae000ce85.png">

11. Enable the "HomeKit" extension for this new grouped device (and disable the "Rebroadcast Plugin" if it's enabled)

**Comment by matbor** [comment]
@koush what is the method for doing this via mqtt? or do you need to use web hooks instead? Thanks.

**Comment by joerikosters** [comment]
@matbor something like this?

`
mqtt.subscribe({
    // this example expects the device to publish either ON or OFF text values
    // to the mqtt endpoint.
    'zigbee2mqtt/n39b_living_wall_button/action': value => {
        device.binaryState = true;
        setTimeout(() => { device.binaryState = false; }, 2000);
    },
    return device.binaryState
});
mqtt.handleTypes(ScryptedInterface.BinarySensor);
`

No clue if im doing it right, but it seems to work...

**Comment by joerikosters** [comment]
> @matbor something like this?
> 
> ```
> mqtt.subscribe({
>     // this example expects the device to publish either ON or OFF text values
>     // to the mqtt endpoint.
>     'zigbee2mqtt/n39b_living_wall_button/action': value => {
>         device.binaryState = true;
>         setTimeout(() => { device.binaryState = false; }, 2000);
>     },
>     return device.binaryState
> });
> mqtt.handleTypes(ScryptedInterface.BinarySensor);
> ```
> 
> No clue if im doing it right, but it seems to work...

Its a Ikea button that reacts to every message posted to its action (type of buttonpress)

It triggers on single press, double press and long press

**Comment by networkpotato** [comment]
> In case anyone else is looking for a tutorial on how to do this with the dummy switch and webhooks plugins
> 
> 1. Install the `@scrypted/dummy-switch` plugin
> 
> <img alt="image" width="1684" src="https://user-images.githubusercontent.com/484912/210941405-fc589a17-ce62-4956-8752-908c7699683c.png">
> 
> 2. Install the `@scrypted/webhook` plugin
> 
> <img alt="image" width="1661" src="https://user-images.githubusercontent.com/484912/210941317-19f9bd59-b77b-4166-bc09-68ed1ea71f02.png">
> 
> 3. Open the "Dummy Switch Plugin" and click "Add new", name it "Doorbell" (or whatever you want to call it)
> 
> <img alt="image" width="1941" src="https://user-images.githubusercontent.com/484912/210941571-f8e6134f-1968-4677-9e98-5edd38449ecb.png">
> 
> 4. Change the "Reset sensor" to 1
> 
> <img alt="image" width="1141" src="https://user-images.githubusercontent.com/484912/210941606-ecc188a2-20ae-4563-b1f0-b9b26541914f.png">
> 
> 5. Click "Extensions" and enable the "Webhook Plugin" extension
> 
> <img alt="image" width="1129" src="https://user-images.githubusercontent.com/484912/210941691-721a6085-da32-44d3-a5bd-15a2c93520e0.png">
> 
> 6. Click "Webhook" and select "OnOff" from the dropdown
> 
> <img alt="image" width="1155" src="https://user-images.githubusercontent.com/484912/210941740-1836346f-fe00-4f06-9963-52029d2a5f3d.png">
> 
> 7. Click the "Console" link to find the webhook URL
> 
> <img alt="image" width="1983" src="https://user-images.githubusercontent.com/484912/210941787-fb66cf9c-a793-4856-a6e9-dc383097d733.png">
> 
> In my case my webhook URL is `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd` so to turn it on I can use `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd/turnOn` to trigger it
> 
> 8. Go to the camera device you want to associate with the doorbell, in my case is "Intercom". Click on "Extensions" and then enable "Custom Doorbell Button".
> 
> ![image](https://private-user-images.githubusercontent.com/484912/287554102-3cce35a2-7f91-4d3a-894e-1f052b3e5afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDQwNTMsIm5iZiI6MTcwNDMwMzc1MywicGF0aCI6Ii80ODQ5MTIvMjg3NTU0MTAyLTNjY2UzNWEyLTdmOTEtNGQzYS04OTRlLTFmMDUyYjNlNWFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzQyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTc3MDI5NzhjODVhNzQ2YjhmYTQ3ZDBmNmQzYmJjMDZjZDFiNTA5ZmRjMTYzMjg1NTNiNGEyZGFiN2Y2YjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QMOr1rNoluMqLhjSU6WvPF0v7M8dHM3SBql1Lkgve9s)
> 
> 9. Click "Custom Doorbell Button" and select the dummy switch you created before (I named it "Doorbell")
> 
> ![image](https://private-user-images.githubusercontent.com/484912/287554152-12a8a6cd-0ad9-4c2f-bdb2-9ecf99fda39f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDQwNTMsIm5iZiI6MTcwNDMwMzc1MywicGF0aCI6Ii80ODQ5MTIvMjg3NTU0MTUyLTEyYThhNmNkLTBhZDktNGMyZi1iZGIyLTllY2Y5OWZkYTM5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzQyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGRlM2U4NGI2YzRmYjU4OTk4MDU0ODQzYmVhZGNiMjExMDMyMDA0OWM2MmJjY2JmZDM2NzdmN2NmOWE0YTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h6KHYJ5kDNr4vvi4AS54Aj4V6MeK-5WviyckkQ7o7Kc)
> 
> 10. Enable the "HomeKit" extension
> 11. Pair device with HomeKit
> 
> EDIT 4/12/2023: Updated instructions from "Device Group" method (deprecated) to newer "Custom Doorbell Button" method. [#988 (comment)](https://github.com/koush/scrypted/issues/988#issuecomment-1658530996)

Just followed your guide exactly. When triggering the Dummy Switch using webhook, I can see in the Scrypted management console that the button is triggered, but no doorbell notification in the Home app.

I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.

**Comment by longzheng** [comment]
> I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.

You don't want to add the switch to HomeKit directly.

You want to just add it to your existing camera/doorbell device using the "Custom Doorbell Button" extension, and then you only need to add the camera/doorbell to HomeKit.

<img width="1136" alt="image" src="https://github.com/koush/scrypted/assets/484912/39b47b6a-b291-4dcd-b2b4-1520b8947b7a">

**Comment by Write** [comment]
I have the same issue here, Camera is Exposed correctly trough HomeKit (I reset and repaired it just in case). I've correctly set the Custom Doorbell Button and still it doesn't show up as a doorbell in homekit but simply as camera with a motion sensor. Is it possibly related with having PAM DIff enabled or something ? Because I can see under the camera an "accessory" category with a motion sensor inside it.

**Comment by networkpotato** [comment]
> > I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.
> 
> You don't want to add the switch to HomeKit directly.
> 
> You want to just add it to your existing camera/doorbell device using the "Custom Doorbell Button" extension, and then you only need to add the camera/doorbell to HomeKit.
> 
> 
I also tried that, without any luck.

**Comment by longzheng** [comment]
> > > I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.
> 
> > 
> 
> > You don't want to add the switch to HomeKit directly.
> 
> > 
> 
> > You want to just add it to your existing camera/doorbell device using the "Custom Doorbell Button" extension, and then you only need to add the camera/doorbell to HomeKit.
> 
> > 
> 
> > 
> 
> I also tried that, without any luck.
> 
> 
> 
> 

Just confirming how are you verifying if it's working in HomeKit. The doorbell won't appear as a separate accessory, except there's only an additional setting in the camera notification settings for "Doorbell Notifications"

![image](https://github.com/koush/scrypted/assets/484912/99a4a017-3930-4032-8667-066955a0e506

**Comment by networkpotato** [comment]
> > > > I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.
> > 
> > 
> > > 
> > 
> > 
> > > You don't want to add the switch to HomeKit directly.
> > 
> > 
> > > 
> > 
> > 
> > > You want to just add it to your existing camera/doorbell device using the "Custom Doorbell Button" extension, and then you only need to add the camera/doorbell to HomeKit.
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > I also tried that, without any luck.
> 
> Just confirming how are you verifying if it's working in HomeKit. The doorbell won't appear as a separate accessory, except there's only an additional setting in the camera notification settings for "Doorbell Notifications"
> 
>
Yeah, that last toggle isn't there for me.
Like the guy above wrote, I only have one sensor show up in Home under the camera, and that is a motion sensor.

**Comment by longzheng** [comment]
> > > > > I have added the Dummy Switch to HomeKit and paired it, but it shows up as a switch and not a doorbell.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You don't want to add the switch to HomeKit directly.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You want to just add it to your existing camera/doorbell device using the "Custom Doorbell Button" extension, and then you only need to add the camera/doorbell to HomeKit.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > I also tried that, without any luck.
> 
> > 
> 
> > Just confirming how are you verifying if it's working in HomeKit. The doorbell won't appear as a separate accessory, except there's only an additional setting in the camera notification settings for "Doorbell Notifications"
> 
> > 
> 
> >
> 
> Yeah, that last toggle isn't there for me.
> 
> Like the guy above wrote, I only have one sensor show up in Home under the camera, and that is a motion sensor.
> 
> 
> 
> 

Ah no worries. 

But also confirming there's no additional sensor for the doorbell, I too only have a motion sensor for the camera.

**Comment by networkpotato** [comment]
So why isnt't the virtual doorbell attached to my camera in HomeKit, even though I have enabled the extension in the camera settings in Scrypted 🤔

**Comment by longzheng** [comment]
> So why isnt't the virtual doorbell attached to my camera in HomeKit, even though I have enabled the extension in the camera settings in Scrypted 🤔

Can you take screenshots of the different tabs for your camera device in Scrypted

<img width="633" alt="image" src="https://github.com/koush/scrypted/assets/484912/f4d52fb5-6bbd-4cc5-bce3-706d06cd3905">

<img width="645" alt="image" src="https://github.com/koush/scrypted/assets/484912/b555d849-84da-4a91-86a5-0e81e00d183b">

<img width="642" alt="image" src="https://github.com/koush/scrypted/assets/484912/66c90c3a-584a-4a9a-bd2d-bccf263037d1">

**Comment by networkpotato** [comment]
Looking at your screenshots, I just got it to work!

It didn't work because the camera device was set to type "Camera" and not "Doorbell". As soon as I changed it, it worked perfectly.

**Comment by longzheng** [comment]
> Looking at your screenshots, I just got it to work!
> 
> It didn't work because the camera device was set to type "Camera" and not "Doorbell". As soon as I changed it, it worked perfectly.

Doh. Sorry I missed that in my original instructions, I'll update now.

**Comment by networkpotato** [comment]
No worries, thank you for the help :)

**Comment by longzheng** [comment]
> I have the same issue here, Camera is Exposed correctly trough HomeKit (I reset and repaired it just in case). I've correctly set the Custom Doorbell Button and still it doesn't show up as a doorbell in homekit but simply as camera with a motion sensor. Is it possibly related with having PAM DIff enabled or something ? Because I can see under the camera an "accessory" category with a motion sensor inside it.

@Write I suspect you might have encountered the same issue. Make sure to change the device type from "Camera" to "Doorbell".

<img width="642" alt="image" src="https://github.com/koush/scrypted/assets/484912/dbe80659-118e-4dc6-87ef-062329174f1d">

**Comment by Write** [comment]
> > I have the same issue here, Camera is Exposed correctly trough HomeKit (I reset and repaired it just in case). I've correctly set the Custom Doorbell Button and still it doesn't show up as a doorbell in homekit but simply as camera with a motion sensor. Is it possibly related with having PAM DIff enabled or something ? Because I can see under the camera an "accessory" category with a motion sensor inside it.
> 
> @Write I suspect you might have encountered the same issue. Make sure to change the device type from "Camera" to "Doorbell".
> 
> <img alt="image" width="642" src="https://private-user-images.githubusercontent.com/484912/294138604-dbe80659-118e-4dc6-87ef-062329174f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODc5NTcsIm5iZiI6MTcwNDM4NzY1NywicGF0aCI6Ii80ODQ5MTIvMjk0MTM4NjA0LWRiZTgwNjU5LTExOGUtNGRjNi04N2VmLTA2MjMyOTE3NGYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNzAwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWU3NjhhZTBlYzMzOGFlZjNlM2FlMGVkZTZiMDMyMTM4N2Q2ZTgzODk0YWQ5MTQ2OGFmNDljMzIwZmUwMjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TRIKYOxBMZRtNJcVDMIODpLXz2UeYu1eucR1Jio_DE4">

Indeed that was the issue ! Now it works perfectly. Thanks a lot. Official doc definitely should be updated with this !.

**Comment by Write** [comment]
Does PAM Diff still records things after setting as Doorbell ? It's seems I don't have new records anymore after setting as Doorbell. I'm asking because I remember I couldn't use both PAM Diff + Webhook (but a webhook which act as a motion sensor motion)  in the past, hence why I'm asking.

**Comment by elhason** [comment]
@longzheng thank you for this as this tutorial got my motion notifications enabled in homekit now. However, the physical button press still isnt triggering any notification within homekit, just motion.  Do I need to do something further with the webhook URL that I am missing?

![Screenshot 2024-01-21 162419](https://github.com/koush/scrypted/assets/157321474/41179f70-ef6f-4280-85ab-ea09873302e5)

**Comment by longzheng** [comment]
> @longzheng thank you for this as this tutorial got my motion notifications enabled in homekit now. However, the physical button press still isnt triggering any notification within homekit, just motion. Do I need to do something further with the webhook URL that I am missing?

I would try two things
- check if pushing the physical button triggers the dummy switch (if not there might ben an issue with the webhooks)
- manually trigger the dummy switch and see if it triggers the HomeKit doorbell notification (if not there might be an issue HomeKit pairing, try removing and repairing the device)

**Comment by elhason** [comment]
> > @longzheng thank you for this as this tutorial got my motion notifications enabled in homekit now. However, the physical button press still isnt triggering any notification within homekit, just motion. Do I need to do something further with the webhook URL that I am missing?
> 
> I would try two things
> 
> * check if pushing the physical button triggers the dummy switch (if not there might ben an issue with the webhooks)
> * manually trigger the dummy switch and see if it triggers the HomeKit doorbell notification (if not there might be an issue HomeKit pairing, try removing and repairing the device)

Thanks! So when I posted originally, manually triggering the dummy switch was not triggering the notification, but I tested again now several times, and yes, indeed manually triggering the dummy switch either via scrypted or the one that appears in apple home triggers "someone rang the doorbell notification" now.

So my guess is a webhook issue?  Pressing the physical button does not trigger a notification.  I am leaning on a Lorex 2k doorbell battery operated and I am a complete noob in this space, just getting up to speed with this world.  Appreciate the help!

**Comment by latel** [comment]
> In case anyone else is looking for a tutorial on how to do this with the dummy switch and webhooks plugins
> 
> 1. Install the `@scrypted/dummy-switch` plugin
> 
> <img alt="image" width="1684" src="https://user-images.githubusercontent.com/484912/210941405-fc589a17-ce62-4956-8752-908c7699683c.png">
> 
> 2. Install the `@scrypted/webhook` plugin
> 
> <img alt="image" width="1661" src="https://user-images.githubusercontent.com/484912/210941317-19f9bd59-b77b-4166-bc09-68ed1ea71f02.png">
> 
> 3. Open the "Dummy Switch Plugin" and click "Add new", name it "Doorbell" (or whatever you want to call it)
> 
> <img alt="image" width="1941" src="https://user-images.githubusercontent.com/484912/210941571-f8e6134f-1968-4677-9e98-5edd38449ecb.png">
> 
> 4. Change the "Reset sensor" to 1
> 
> <img alt="image" width="1141" src="https://user-images.githubusercontent.com/484912/210941606-ecc188a2-20ae-4563-b1f0-b9b26541914f.png">
> 
> 5. Click "Extensions" and enable the "Webhook Plugin" extension
> 
> <img alt="image" width="1129" src="https://user-images.githubusercontent.com/484912/210941691-721a6085-da32-44d3-a5bd-15a2c93520e0.png">
> 
> 6. Click "Webhook" and select "OnOff" from the dropdown
> 
> <img alt="image" width="1155" src="https://user-images.githubusercontent.com/484912/210941740-1836346f-fe00-4f06-9963-52029d2a5f3d.png">
> 
> 7. Click the "Console" link to find the webhook URL
> 
> <img alt="image" width="1983" src="https://user-images.githubusercontent.com/484912/210941787-fb66cf9c-a793-4856-a6e9-dc383097d733.png">
> 
> In my case my webhook URL is `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd` so to turn it on I can use `https://192.168.1.2:10443/endpoint/@scrypted/webhook/public/31/956d0e3aaba757dd/turnOn` to trigger it
> 
> 8. Go to the camera device you want to associate with the doorbell, in my case is "Intercom". Click on "Extensions" and then enable "Custom Doorbell Button".
> 
> ![image](https://private-user-images.githubusercontent.com/484912/287554102-3cce35a2-7f91-4d3a-894e-1f052b3e5afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTk0NzEsIm5iZiI6MTcyODU1OTE3MSwicGF0aCI6Ii80ODQ5MTIvMjg3NTU0MTAyLTNjY2UzNWEyLTdmOTEtNGQzYS04OTRlLTFmMDUyYjNlNWFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTE1MGJlN2YyY2E3OWY4ODBhZjgxOTNjZTdkNTUxODdhOTcxOTFiY2IyYTBmMTNkY2I5MDQ0YzRmNTliYmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V8x8fR0nGioPOn_ADrfDq07lDe0s85BacJU4PNRLPAE)
> 
> 9. Click "Custom Doorbell Button" and select the dummy switch you created before (I named it "Doorbell")
> 
> ![image](https://private-user-images.githubusercontent.com/484912/287554152-12a8a6cd-0ad9-4c2f-bdb2-9ecf99fda39f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTk0NzEsIm5iZiI6MTcyODU1OTE3MSwicGF0aCI6Ii80ODQ5MTIvMjg3NTU0MTUyLTEyYThhNmNkLTBhZDktNGMyZi1iZGIyLTllY2Y5OWZkYTM5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWI2ZDc0YjFmYzI2OTg3MTkyYmJmNGU2NmExZGRkZmQxMmZkNDFiNmNiNmEyMWJkZjExYmY4NDcxNGE2ODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T0XQu9S6suoOS78NRjGdOYDhatUKuwGf23gJNw0xWtA)
> 
> 10. Click on "Edit" and change "Type" to "Doorbell"
> 
> ![image](https://private-user-images.githubusercontent.com/484912/294137639-f7c089ec-e331-4dd4-918c-73df4de002c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTk0NzEsIm5iZiI6MTcyODU1OTE3MSwicGF0aCI6Ii80ODQ5MTIvMjk0MTM3NjM5LWY3YzA4OWVjLWUzMzEtNGRkNC05MThjLTczZGY0ZGUwMDJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGQ1NWRiNTM1ZDMzNWQ3ZDNiZDJmNGIyN2EwOGZjM2U1ODQzNWFiMmY3OTMyODgzYzdmMmFmYWFhNjJjODg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sheqSesbBk3mr9GeISOWsWMCBYTaWcHOhiG8cQujQzs)
> 
> 11. Enable the "HomeKit" extension
> 
> ![image](https://private-user-images.githubusercontent.com/484912/294138042-2fee10be-8bf5-4dc4-ab13-470fbd0c3901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTk0NzEsIm5iZiI6MTcyODU1OTE3MSwicGF0aCI6Ii80ODQ5MTIvMjk0MTM4MDQyLTJmZWUxMGJlLThiZjUtNGRjNC1hYjEzLTQ3MGZiZDBjMzkwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTcyOWJiZmVmMjFlMTRhOTdiMjE0OGE4MTkwZjFkNzI1NDcwYjYzMTk2N2JkMjJmZGNiZmFjZGQ3ZDU2OTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dl2W4HrWYWZ2Cl9hCfgGjwe2IiDLniVIzpgsSSUaKuc)
> 
> 12. Pair device with HomeKit by clicking on "HomeKit", then "Pairing" and scan pairing QR code with iOS device
> 
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/484912/294138253-e4ce50e8-f39f-4643-9bb0-8dd957b3ec08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTk0NzEsIm5iZiI6MTcyODU1OTE3MSwicGF0aCI6Ii80ODQ5MTIvMjk0MTM4MjUzLWU0Y2U1MGU4LWYzOWYtNDY0My05YmIwLThkZDk1N2IzZWMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMTE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDMzOGQ4ZjEyNmYyZDg5MjA1NzNhMGViNTJmMDQwN2QzNzVlYTNmNjUwNDJjYjEwNDc3NzkxZjg5MDFmOGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gVg3XK49bZoGJqAG3COonwDbRXupvhp8JgU3XGVPkSI">
> EDIT 4/12/2023: Updated instructions from "Device Group" method (deprecated) to newer "Custom Doorbell Button" method. [#988 (comment)](https://github.com/koush/scrypted/issues/988#issuecomment-1658530996)
> 
> EDIT 4/1/2024: Added missing instruction about changing device type from "Camera" to "Doorbell".

I cannot see a video preview in the doorbell notification. however I can see it in the previous gouped devices way.
