### ISSUE TITLE
Windows Local Install Error

### ISSUE THREAD

**Issue by slunat** [koush/scrypted#303]
Getting npm errors when trying to install via the script in the Windows local install instructions. Running in powershell as admin. Even though it says its running at the end, the Scrypted service does not seem to actually exist and I dont get anything by going to the url for it. Powershell shows the following errors in install.

PS C:\WINDOWS\system32> iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-dependencies-win.ps1'))
Found Node.js [OpenJS.NodeJS] Version 18.4.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://nodejs.org/dist/v18.4.0/node-v18.4.0-x64.msi
  ██████████████████████████████  28.9 MB / 28.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Found Python 3 [Python.Python.3] Version 3.10.5150.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.python.org/ftp/python/3.10.5/python-3.10.5-amd64.exe
  ██████████████████████████████  27.3 MB / 27.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Requirement already satisfied: pip in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (22.1.2)
Requirement already satisfied: aiofiles in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (0.8.0)
Requirement already satisfied: debugpy in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (1.6.0)
Requirement already satisfied: typing_extensions in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (4.3.0)
Requirement already satisfied: typing in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (3.7.4.3)
Requirement already satisfied: opencv-python in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.14.5 in c:\users\sluna\appdata\local\programs\python\python310\lib\site-packages (from opencv-python) (1.23.0)
Node version mismatch, missing, or corrupt. Clearing node_modules.
running npm.cmd --prefix C:\Users\sluna\.scrypted install --production @scrypted/server@latest
npm WARN config production Use --omit=dev instead.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\sluna\\.scrypted\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\sluna\.scrypted\node_modules\ffmpeg-static'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\sluna\\.scrypted\\node_modules\\ffmpeg-static'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\sluna\.scrypted\node_modules\node-pty
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "C:\Users\sluna\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\sluna\.scrypted\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sluna\\.scrypted\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\sluna\.scrypted\node_modules\node-pty
npm ERR! gyp ERR! node -v v18.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sluna\AppData\Local\npm-cache\_logs\2022-07-02T19_39_10_463Z-debug-0.log
server installation successful: C:\Users\sluna\.scrypted

added 5 packages, removed 1 package, and audited 6 packages in 4s

3 vulnerabilities (2 moderate, 1 critical)

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Uninstall was skipped because process does not exist or could not be found.
Scrypted is now running at: https://localhost:10443/
Note that it is https and that you'll be asked to approve/ignore the website certificate.

**Comment by koush** [comment]
might need visual studio community installed. not sure. let me know if you find out.
