### ISSUE TITLE
"error retrieving onvif profiles Error: Wrong ONVIF SOAP response"

### ISSUE THREAD

**Issue by augustopaulogh** [koush/scrypted#304]
A couple of weeks ago, lost motion detection Events on ONVIF for my Veezoom camera. 
Getting error "error retrieving onvif profiles Error: Wrong ONVIF SOAP response". 
Veezoom web interface shows detections in log.

![Captura_de_ecra_2022-07-01_as_07 31 50](https://user-images.githubusercontent.com/47955358/177051833-2075da2b-7697-4189-ab04-c13296a0a29e.png)
![Captura_de_ecra_2022-07-01_as_07 28 24](https://user-images.githubusercontent.com/47955358/177051836-5e504af5-d2d5-4038-8bc5-7708b7b4b5ec.png)
![Captura_de_ecra_2022-07-01_as_07 28 02](https://user-images.githubusercontent.com/47955358/177051837-8eab40ba-90fd-4ede-9eb4-1278734963e6.png)
![Captura_de_ecra_2022-07-01_as_07 24 56](https://user-images.githubusercontent.com/47955358/177051838-adad4cf6-15da-471a-a1a9-484e0da5e6ce.png)
![Captura_de_ecra_2022-07-01_as_07 28 49](https://user-images.githubusercontent.com/47955358/177051839-35a790c9-c83c-4f3b-8aed-8be492307026.png)
[Scrypted_console_log.txt](https://github.com/koush/scrypted/files/9035279/Scrypted_console_log.txt)

**Comment by koush** [comment]
can you try rolling back a version or two on the onvif plugin

**Comment by koush** [comment]
try v86.

**Comment by augustopaulogh** [comment]
Sure, here you go.
[Onvif_0.0.86.txt](https://github.com/koush/scrypted/files/9060490/Onvif_0.0.86.txt)
No fields are read from this version, with Events panel reporting the same error message:
![Captura de ecrã 2022-07-07, às 05 54 23](https://user-images.githubusercontent.com/47955358/177694276-a1d84849-664a-40a7-9061-d2722f047d00.png)

**Comment by koush** [comment]
This seems to be a camera issue. try a firmware update. If you rolled back and it still doesn't work, that means our camera changed or the camera ip changed.

**Comment by augustopaulogh** [comment]
I've got the latest firmware version that also fixed the random loss of the camera's configured username/password and the NTP time settings:
![Captura de ecrã 2022-07-07, às 06 04 29](https://user-images.githubusercontent.com/47955358/177696819-ac0dfa36-64d4-4b92-88f1-7a695829ea1f.png)

Believed that the loss of events was prior to this firmware update.

I've got Vezzoom technical department actively supporting me, is there a specific Onvif technical query that you would like me to ask them?

**Comment by augustopaulogh** [comment]
@koush#5867, you were right, Veezoom removed Onvif functionality in last Firmware update 😠 . Their reply today:"Hi Paulo,
We remove the onvif options because it actually does not work at present. It will be added back when it is able to work in the future." 😬  ...
