### ISSUE TITLE
Amazon Alexa login issue

### ISSUE THREAD

**Issue by yieldhog** [koush/scrypted#308]
Hi -- great project, works awesome for my cameras+homekit!

I am having an issue installing the Alexa skill, steps:

- [x] Login to Scrypted cloud
- [x] Login to Alexa.amazon.com
- [x] Enable skill
- [x] Link via Amazon login

At this point, I get a new window pop-up with a redirect error from url https://pitangui.amazon.com/api/skill/link/M14OJJW3N35UJK?
```
{"httpRedirectLocation":"https://skills-store.amazon.com/api/skill/link/M14OJJW3N35UJK?code= xxxxx &token_type=Bearer"}
```

I am unable to enable the Alexa skill as a result -- using Safari browser

**Comment by koush** [comment]
this seems to be a bug in Alexa. you can copy the link you see there and open that in a browser to complete the login.
