### ISSUE TITLE
always packet loss at remote ontime streaming

### ISSUE THREAD

**Issue by jiajiayao** [koush/scrypted#314]
i use the rts camera in homekit to use hsv
the remote ontime streaming is not working 

the [Transcoding] is all on 
![image](https://user-images.githubusercontent.com/48589551/179891143-5c8bf12f-39c4-472c-9096-bdbb84f5d4ea.png)

the console in homekit plugin by test the camera[test_A]

[test_A] first forwarded opus packet received.
[test_A] received first audio packet
[test_B] motion fragment #39 sent. size: 932341
[test_A] packet loss 8
[test_A] packet loss 2
[test_C] motion fragment #73 sent. size: 1531633
[test_A] packet loss 5
[test_A] packet loss 6
[test_A] packet loss 8
[test_C] motion fragment #74 sent. size: 1510136
[test_A] packet loss 9
[test_B] motion fragment #40 sent. size: 1113104
[test_A] packet loss 13
[test_A] packet loss 16
[test_A] packet loss 17
[test_C] motion fragment #75 sent. size: 1499867
[test_C] motion fragment #76 sent. size: 1505649
[test_A] packet loss 20
[test_B] motion fragment #41 sent. size: 913123
[test_A] packet loss 52
[test_A] packet loss 53
[test_A] packet loss 54
[test_C] motion fragment #77 sent. size: 1488480
[test_A] packet loss 56
[test_A] packet loss 60
[test_C] motion fragment #78 sent. size: 1518750
[test_A] packet loss 74
[test_B] motion fragment #42 sent. size: 971246
[test_A] packet loss 77
[test_A] packet loss 78
[test_C] motion fragment #79 sent. size: 1504474
[test_C] motion fragment #8

**Comment by koush** [comment]
reduce your remote bandwidth in the rebroadcast plugin.
