### ISSUE TITLE
Home plugin not requesting stream on motion events

### ISSUE THREAD

**Issue by sobake** [koush/scrypted#315]
Using the Amcrest plugin on multiple cameras. I'm able to see the live stream in the Home app and the motion events in the event log in scrypted, but homekit never requests the stream and no recordings ever happen.

I logged out of iCloud, restarted my Apple TV that's acting as my hub and toggled recordings.. still no dice. Any ideas?

**Comment by koush** [comment]
all info is in the troubleshooting guide.
