### ISSUE TITLE
Cannot enable homekit when setting device or devicegroup as "doorbell"

### ISSUE THREAD

**Issue by Vinisz** [koush/scrypted#316]
Hi,

First, thanks for this great solution, works great with 4 camera's I own.
Next, I want to enable doorbell but, one step in your article/video I cannot achieve.
As soon as I set a device or devicegroup to "doorbell" , I can no longer enable "homekit" from the plugins (option just not there anymore) , as soon as I set it back to "camera" , the option re-appears.
Is this is bug or something well known ?

**Comment by SamTheGeek** [comment]
I'm having the same trouble. It seems that the Arlo doorbell implementation doesn't "look" like a doorbell to Scripted

**Comment by koush** [comment]
the device doesn't have a button implemented on it so its not a doorbell.

**Comment by Vinisz** [comment]
> the device doesn't have a button implemented on it so its not a compatible doorbell.

Not sure why you mention this, I do add a button and follow steps from your guide and video (which do not 100% match with each other) 
So, how can this be fixed ? just closing the issue does not really help to be honest

**Comment by koush** [comment]
this isn't a bug, you're looking for usage help. better off asking in discord. doorbell type needs a binary sensor interface to function in homekit, and that's why it doesn't make itself available if you simply change the type.

**Comment by koush** [comment]
works fine for me in any case 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/73924/180516102-b209e2dc-3a1a-4145-be35-794fc0c6f3ac.png">

**Comment by Vinisz** [comment]
Ah, you just said the magic word "binary sensor" is the trick (I added "switch") , thanks , looks ok now...
