### ISSUE TITLE
ONVIF event subscription drops out

### ISSUE THREAD

**Issue by cr3ative** [koush/scrypted#319]
Hiya, I'd like to help debug this one.

I keep finding that Scrypted is no longer pickup up ONVIF motion events from my cameras, which of course leads to no recordings.
If I restart the Scrypted container, everything comes back to life. 

I'm wondering if the event subscription is dropping but is not recovered automatically?

I've just restarted scrypted and this will probably happen again, so if I can help with logs in any way, let me know.

**Comment by koush** [comment]
try reloading the onvif plugin to see if that by itself resolves it

**Comment by cr3ative** [comment]
Yes, reloading the onvif plugin resolves it, events flow again right after.

**Comment by koush** [comment]
fixed
