### ISSUE TITLE
Hikvision plugin needs occasional reload for motion events to work

### ISSUE THREAD

**Issue by sobake** [koush/scrypted#320]
For some reason I have reload the plugin about once a day or more for the motion events to come through from the camera again. How do I troubleshoot this?

**Comment by koush** [comment]
what server installation method?

**Comment by sobake** [comment]
docker-compose on ubuntu server

**Comment by jadomski** [comment]
I have observed this to occur when the network connection between scrypted and the camera is lost, for example a cable is unplugged, a camera is rebooted, or a link is dropped

I am yet to observe the issue outside of these cases, but I can imagine other factors could come into play, such as wireless channel changes if there is any Wi-Fi link in play or a piece of network hardware in the chain is rebooted

**Comment by koush** [comment]
I'll take a look into timing out the listener connection

**Comment by jadomski** [comment]
To add to this - I have found if the Scrypted server comes online before the cameras do (i.e. in a power outage where my cameras take longer to boot than my rPi) then motion alerts are gone.

The usual process to reload the Hikvision plugin (or a Scrypted Docker update or system reboot) will bring the motion alerts back, but it's not ideal when away from home.

**Comment by koush** [comment]
There’s a beta plug-in where this is fixed I think

**Comment by koush** [comment]
fix

**Comment by jadomski** [comment]
would you mind providing some insight into how this has been resolved?

**Comment by koush** [comment]
check commits in the hikvision plugin

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/82f644990a3c1b5e3eb59b54514d0e777b28250b

**Comment by jadomski** [comment]
Thanks :)

**Comment by jadomski** [comment]
This issue seems to be back. I had to reboot my network switch which caused my cameras to lose power. I had waited 1hr but even then motion events no longer worked. After reloading the plug-in all motion alerts started working again.
