### ISSUE TITLE
Snapshot plugin fails loading

### ISSUE THREAD

**Issue by maxiido** [koush/scrypted#326]
After some days I noticed that I wont get any snapshot of my camera. Without changing anything the snapshot plugin now refuses to start with the error message "plugin failed to start Error: Cannot find module 'jimp'"
What is wrong here? I even completely removed scrypted and reinstalled everything but as soon as I install snapshot it refuses to start the plugin. Hope someone can help me.

**Comment by koush** [comment]
doesn't use jump anymore as of a recent release.
