### ISSUE TITLE
TAPO TPLINK Camera 401 unauthorized

### ISSUE THREAD

**Issue by mouth4war** [koush/scrypted#327]
It seems camera isnt working with BASIC authorization. 

> server version: 0.1.15
plugin version: @scrypted/rtsp 0.0.51
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: prebuffer session releasing if started
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: error retrieving getVideoStreamOptions TypeError: Cannot read properties of undefined (reading 'map')
[Rebroadcast Plugin]:     at Object.onGet (/src/stream-settings.ts:201:35)
[Rebroadcast Plugin]:     at process.onGet (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at se.push [as getSettings] (/common/src/settings.ts:114:15)
[Rebroadcast Plugin]:     at Ke.getMixinSettings (/src/main.ts:1387:14)
[Snapshot Plugin]: snapshotting active prebuffer
[Snapshot Plugin]: creating error image with background Snapshot Failed false
[Snapshot Plugin]: snapshotting active prebuffer
[Rebroadcast Plugin]: error retrieving getVideoStreamOptions TypeError: Cannot read properties of undefined (reading 'map')
[Rebroadcast Plugin]:     at Object.onGet (/src/stream-settings.ts:201:35)
[Rebroadcast Plugin]:     at process.onGet (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at se.push [as getSettings] (/common/src/settings.ts:114:15)
[Rebroadcast Plugin]:     at Ke.getMixinSettings (/src/main.ts:1387:14)
[Rebroadcast Plugin]: error retrieving getVideoStreamOptions TypeError: Cannot read properties of undefined (reading 'map')
[Rebroadcast Plugin]:     at Object.onGet (/src/stream-settings.ts:201:35)
[Rebroadcast Plugin]:     at process.onGet (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at se.push [as getSettings] (/common/src/settings.ts:114:15)
[Rebroadcast Plugin]:     at Ke.getMixinSettings (/src/main.ts:1387:14)
[WebRTC Plugin]: connectionStateChange connecting
[WebRTC Plugin]: iceConnectionStateChange checking
[WebRTC Plugin]: iceConnectionStateChange completed
[WebRTC Plugin]: connectionStateChange closed
[WebRTC Plugin]: iceConnectionStateChange closed
[WebRTC Plugin]: connectionStateChange failed
[WebRTC Plugin]: connectionStateChange connecting
[WebRTC Plugin]: iceConnectionStateChange checking
[WebRTC Plugin]: iceConnectionStateChange completed
[WebRTC Plugin]: connectionStateChange closed
[WebRTC Plugin]: iceConnectionStateChange closed
[WebRTC Plugin]: connectionStateChange failed
[Snapshot Plugin]: snapshotting active prebuffer
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: stream Stream 2 will be rebroadcast on demand.
[Rebroadcast Plugin]: Default Stream: channel0 Stream 1
[Rebroadcast Plugin]: rebroadcast mode: rtsp
rtsp stream url rtsp://192.168.31.110/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.31.110/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Jul 28 2022 13:47:35 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, GET_PARAMETER, SET_PARAMETER
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.31.110/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Jul 28 2022 13:47:35 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="a14cc26941913d82973e379a205310db"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.31.110/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YXNoaXNoOnJpZ29yNjY2
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Jul 28 2022 13:47:36 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="8d68512abd554afae006cceb5aacedf6"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsp://192.168.31.110/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YXNoaXNoOnJpZ29yNjY2
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session ended with error Error: auth failed
[Rebroadcast Plugin]:     at te.request (/common/src/rtsp-server.ts:466:23)
[Rebroadcast Plugin]:     at process.sdpResponse (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at session (/src/rtsp-session.ts:63:15)
[Rebroadcast Plugin]:     at qe.startPrebufferSession (/src/main.ts:715:9)
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds

Is there anything I can do to make this work? Steam is working in VLC just fine but not in scrypted

**Comment by mouth4war** [comment]
I'm able to add it in home assistant using Digest authorization. Can I get scrypted to use Digest?

**Comment by mouth4war** [comment]
ONVIF plugin worked finally. This camera has a terrible speaker and uses non-MPEG4 audio codec. Avoid for homekit

**Comment by koush** [comment]
any audio codec is fine

**Comment by 1aranzant** [comment]
Can't make my C320ws work with ONVIF either...
`ECONNREFUSED`

**Comment by mouth4war** [comment]
Onvif worked for me. You have to generate a new user from the app and use that.

**Comment by 1aranzant** [comment]
@mouth4war What do you mean by "generating a new user from the app"?  Thanks

**Comment by mk01** [comment]
@1aranzant 
open the Tapo app, go to Camera Settings -> Advanced Settings -> Camera Account. 
Back in scrypted use those credentials to add new "ONVIF" camera. Works perfectly with Tapo200, Tapo220 including motion events.

**Comment by Shadab995** [comment]
> ONVIF plugin worked finally. This camera has a terrible speaker and uses non-MPEG4 audio codec. Avoid for homekit

Can you please help me ? . how did you did the live streaming of it ?

**Comment by upamanyudas** [comment]
> ONVIF plugin worked finally. This camera has a terrible speaker and uses non-MPEG4 audio codec. Avoid for homekit

Could you please share how you made it work? Same problem on my end. works in VLC but not Scrypted. Cheers

**Comment by tataihono** [comment]
I also needed to reduce the password length. I tried 6 and it worked. Initially, I had it at 32 characters.

**Comment by sdwhwk** [comment]
I’m still getting Auth Failed with my C211’s with firmware 1.3.9 build 231019. For S@$! and giggles, I set the username:password for both to tester:123456 to no avail.

**Comment by gleep52** [comment]
WOW... so the Tapo warning about RTSP is that it has less security in that it won't have constant encryption, but then they won't allow a 12 digit password?  (I just tried, no specials just cap lower number 12 long).  *sighs*

**Comment by DanielLaberge** [comment]
For anyone finding this, I had this issue until I rebooted the camera after setting the Camera Account. I was then able to use a long password.
