### ISSUE TITLE
Battery drain in Ring Videodoorbell 2

### ISSUE THREAD

**Issue by Lui5Jacint0** [koush/scrypted#328]
I have just migrated my ring videodoorbell 2 from homebridge and i have noticed that my doorbell (hardwired) just got battery drain way too fast. is there any options to facilitate the number of screenshots it takes? i have an ipad wall mounted with screen on 24/7.

Thanks in advance

**Comment by koush** [comment]
I'd suggest not turning on secure video for battery cameras. there's no fix for this.
