### ISSUE TITLE
[feature request] Get notified when camera goes offline

### ISSUE THREAD

**Issue by gee-az** [koush/scrypted#329]
With HomeKit cameras in general there is the option get notifications when a camera goes offline.

I have this option enabled in HomeKit for an Amcrest PoE camera that I have added to Scrypted with the Amcrest plugin but I am not getting notications when I unplug it. Everything else works perfectly but I'd like to also get notifications when it goes offline and comes back online.

Is it possible to add this functionality or is it already possible through some configuration?

Thanks

**Comment by koush** [comment]
this feature was disabled because it was buggy

**Comment by gee-az** [comment]
I see. Any chance to bring it back new and improved? Or is it buggy on the HomeKit side?

Thanks

**Comment by koush** [comment]
I am not planning on bringing this feature back because the false positive case is catastrophic (camera is reachable but forced offline).
