### ISSUE TITLE
OpenCV Motion Detection Plugin failed to load. Console for more information.

### ISSUE THREAD

**Issue by lzy31179** [koush/scrypted#33]
I install tihis plugin on my mac but the plugin doesn't work and the console is empty

**Comment by lzy31179** [comment]
![image](https://user-images.githubusercontent.com/57745961/137239081-95e1a4bf-4d0b-4874-8b1c-852de99d83d8.png)

**Comment by lzy31179** [comment]
![image](https://user-images.githubusercontent.com/57745961/137239133-22e1ff03-0992-41d1-8270-3e4ad2d9642d.png)

**Comment by lzy31179** [comment]
I have installed copencv with homebrew,but it still did not work.What configuratio should I need to do？

**Comment by lzy31179** [comment]
Last login: Thu Oct 14 12:55:09 on ttys000
-bash: export: `/Users/jay/.bash_profile': not a valid identifier
Jays-iMac:~ jay$ brew install pkgconfig
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config

this thing is up to date....

**Comment by lzy31179** [comment]
Last login: Thu Oct 14 12:58:54 on ttys000
-bash: export: `/Users/jay/.bash_profile': not a valid identifier
Jays-iMac:~ jay$ brew install opencv
Warning: opencv 4.5.3_2 is already installed and up-to-date.
To reinstall 4.5.3_2, run:
  brew reinstall opencv
Jays-iMac:~ jay$

**Comment by koush** [comment]
can test:

```
% pkg-config opencv --libs
-L/usr/local/Cellar/opencv@3/3.4.15/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_highgui -lopencv_videoio -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core
```

**Comment by lzy31179** [comment]
OK,I will try it! Thank You!

**Comment by lzy31179** [comment]
Last login: Thu Oct 14 13:10:06 on ttys000
-bash: export: `/Users/jay/.bash_profile': not a valid identifier
Jays-iMac:~ jay$ % pkg-config opencv --libs
-bash: fg: %: no such job
Jays-iMac:~ jay$ -L/usr/local/Cellar/opencv@3/3.4.15/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_highgui -lopencv_videoio -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core
-bash: -L/usr/local/Cellar/opencv@3/3.4.15/lib: No such file or directory
Jays-iMac:~ jay$

**Comment by lzy31179** [comment]
I follow your instructions，but it still doesn't work。。。

**Comment by koush** [comment]
Jays-iMac:~ jay$ npm install opencv

that's wrong
you need to npm install in scrypted/server

**Comment by lzy31179** [comment]
OK,Thank You

**Comment by lzy31179** [comment]
plugin load error Error: Cannot find module '/Users/jay/Documents/homekit/scrypted/server/node_modules/@koush/opencv4nodejs/build/Release/opencv4nodejs'
Require stack:
- /Users/jay/Documents/homekit/scrypted/server/node_modules/@koush/opencv4nodejs/lib/cv.js
- /Users/jay/Documents/homekit/scrypted/server/node_modules/@koush/opencv4nodejs/lib/opencv4nodejs.js
- /Users/jay/Documents/homekit/scrypted/server/dist/plugin/plugin-remote.js
- /Users/jay/Documents/homekit/scrypted/server/dist/plugin/plugin-host.js
- /Users/jay/Documents/homekit/scrypted/server/dist/scrypted-main.js

**Comment by lzy31179** [comment]
I have install it in scrypted,But it show this
