### ISSUE TITLE
Hikvision Issues since updating

### ISSUE THREAD

**Issue by DoinitSideways** [koush/scrypted#330]
Hi All!

Love the app and thank you for your work.

on Sunday night I updated most of the plugins… (I rarely login… because if it works it works) i did it because I thought it had been a while.

however I have now lost motion alerts… the 10 second interval still works but the live view also doesn’t work remotely or at home on the main network. I’ve also now got an error saying my stream needs to be h264… but it is and always has been as it has been working flawlessly for months now.

my tech knowledge expands as far as restarting the container, rebooting the raspberry pi 4B and restarting my router…

could it be something within the updated hikvision plugon?

cheers
Josh

**Comment by koush** [comment]
need a console log. your server is likely out of date.

**Comment by koush** [comment]
please join the discord to submit a report, will be easier to diagnose

**Comment by DoinitSideways** [comment]
Must have been a setting issue. Just removed the whole hikvision setup and re done from scratch and it’s all working again.
