### ISSUE TITLE
Network error on login

### ISSUE THREAD

**Issue by Keith2920** [koush/scrypted#34]
Installed NPM on Mac and installed via terminal.  I can access the page and set up initially went fine.  When I closed the window, it caused the cameras to stop.  When I attempted to log back it states "network error".  Not sure if my best route is to start over completely or find a way to change the password... not exactly sure how to do either.

**Comment by RemuxZaph** [comment]
@Keith2920 how'd you fix the https redirect issue? I cleared the "Manage Website Data" in Safari, but now I can't even bring up Scrypted's dashboard...

**Comment by jiehanzheng** [comment]
@RemuxZaph - I ran into this and was able to resolve it by going to the bare URL without path (path=`/`), like `https://x.x.x.x:10443/`

**Comment by GeoffIX** [comment]
As with other solutions above, I found that my browser was objecting to authorisation. Going back to the base https request made the browser protection queries visible, allowing me to override them and proceed.
