### ISSUE TITLE
Ventura 13.0 Support

### ISSUE THREAD

**Issue by DarkKent00** [koush/scrypted#341]
Not an issue. just a question.

![NDT](https://user-images.githubusercontent.com/79189797/184492808-adb399fb-61bb-4ceb-bd0c-032c4da69a64.jpg)
![warning](https://user-images.githubusercontent.com/79189797/184492823-c1e0682d-4dfe-4c8c-af61-69d7a73b5a16.jpg)

**Comment by koush** [comment]
You need to follow the instructions shown  to install the dev tools. I run on Ventura myself.
