### ISSUE TITLE
Blurry snapshots

### ISSUE THREAD

**Issue by danTHAman152000** [koush/scrypted#343]
Scrypted running through my Home Assistant has been great. I have the issue where the snapshot of the video feed (that updates about every 11 seconds) appears blurry unless I load the video feed, which immediately loads crisp image. I read in a closed "Clearer snapshots" thread where you mentioned disabling a feature in the snapshot plugin, and that the issue was caused by being on a different network. I am actually on my same network, though. Any tips?

Thanks

**Comment by koush** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/73924/185755351-9364b683-c600-430d-8609-e44ee79000d6.png">


this option is in the beta plugin dropdown.

**Comment by koush** [comment]
be aware that this option will likely change, as overriding this behavior is not ideal for remote networks or thumbnails. I'll probably add a scaling factor rather than just maxing the resolution.

are you on unifi by chance?

**Comment by danTHAman152000** [comment]
Yeah UniFi.

**Comment by danTHAman152000** [comment]
is it 0.9.27 of the rebroadcast plugin? I installed it but didn’t see your screen shot. Thanks for your help.
