### ISSUE TITLE
Webhook on Hikvision camera not working

### ISSUE THREAD

**Issue by marvelloard** [koush/scrypted#347]
Hi,

I successfully added my Annke (Hikvision rebranded) cameras. Since motion detection on these cameras doesn't work directly, I need to use webhooks. So I created one, got a link in the console. If I open the link, I get "Not Found".

The console then shows:
Unknown method or property undefined

I'm afraid I can't get it working.

**Comment by koush** [comment]
use web hook and dummy switch.

**Comment by marvelloard** [comment]
Thanks but how?

**Comment by marvelloard** [comment]
Mail plugin works fine, using mail now. But created webhooks still result in Unknown method or property undefined
.
