### ISSUE TITLE
Upgrade not available

### ISSUE THREAD

**Issue by uspino2** [koush/scrypted#35]
I see some of the plugins have been upgraded in the last few days but I don't get the Upgrade button anymore at the Plugins page. My HomeKit plugin is at 0.0.80 but I see 0.0.95 is out. Has the upgrade process from main screen been phased out? What is the correct way to upgrade all system and components? Thanks.

**Comment by koush** [comment]
This was a bug, sorry! And it was fixed in the latest docker release (or you manually update core to fix the UI issue of it not showing updates).
