### ISSUE TITLE
Scrypted on macOS doesn’t start before login 

### ISSUE THREAD

**Issue by thairbutma** [koush/scrypted#353]
Hi! 
I installed scrypted on both of MacBook and a Mac mini I use as a server along with homebridge ( installed as a service ).
Unfortunately, every time I reboot the server , I’ll have to login for the scrypted app to come up ( unlike homebridge which starts working without needing to login ) 
Is it possible to have scrypted installed as a service too ? or any workaround for this issue?
Thank you !

**Comment by koush** [comment]
It is a user service account, so currently no, it requires login. It would need to be installed as a system service.

**Comment by thairbutma** [comment]
Thank you for your response !! I have set the macOS to auto login for now ..
Appreciate the effort made into this AMAZING app !! Hopefully this can be implemented in the future
