### ISSUE TITLE
Protect G4 Doorbell not triggering Homepod chime

### ISSUE THREAD

**Issue by danTHAman152000** [koush/scrypted#357]
When I ring my G4 Doorbell, I get notified on all my devices, including my Apple TV 4K, however no chime on my four Homepods (two mini, two OG). I installed a dummy Homebridge doorbell, and when this is triggered, the Homepod chimes work as normal. Any tips?

Thanks again for your continued support. It's unprecedented in my experience.

**Comment by koush** [comment]
This is an apple issue.
