### ISSUE TITLE
Snapshot Plugin / "plugin failed to start Error: Cannot find module 'jimp'"

### ISSUE THREAD

**Issue by bondskin** [koush/scrypted#358]
Dear all,

I am seeing this error message in regards of the Snapshot plugin and I am not able to find/install "jump" via the GUI.
Any hint how to fix this please?

> server version: 0.1.16
> plugin version: @scrypted/snapshot 0.0.30
> native dependencies (up to date). jimp
> plugin failed to start Error: Cannot find module 'jimp'
> Require stack:
> - /home/pi/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
> - /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
> - /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at params.require (/home/pi/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js:244:32)
>     at Object.2113 (/@scrypted/snapshot/main.nodejs.js:1:75761)
>     at __webpack_require__ (/@scrypted/snapshot/main.nodejs.js:1:78396)
>     at /@scrypted/snapshot/main.nodejs.js:1:84013
>     at /@scrypted/snapshot/main.nodejs.js:1:93566
>     at /@scrypted/snapshot/main.nodejs.js:1:93837 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/pi/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
>     '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
>     '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
>   ]
> }
>

**Comment by koush** [comment]
should be fixed with update just now. no longer using jump.
