### ISSUE TITLE
rtsp does not work

### ISSUE THREAD

**Issue by motogon** [koush/scrypted#36]
Hi 

rtsp does not work , I point the link rtsp://****:****@192.168.3.109:554/cam/realmonitor?channel=12&subtype=0 
( this link works fine in hoobs Camera Ui )

But in scrypted - no video ( black screen ) , no errors . 

![изображение](https://user-images.githubusercontent.com/12997195/138562387-7de9f04d-882f-4e33-8530-cd725dff029e.png)

Please advise what I do wrong?
Thanks

**Comment by kapps7** [comment]
Hi, did you have any luck this. I am having the same issue. Discord doesnt work, I cant contact you on it
