### ISSUE TITLE
Video clips don't display when accessing Scrypted via hostname

### ISSUE THREAD

**Issue by reneruiz** [koush/scrypted#367]
I noticed in the source code that Scrypted is rendering html as:
```
<video src="https://192.168.1.1:1234/somepath/clip.mp4" controls="controls" autoplay="autoplay"></video>
```

But that means videos don't display when I'm accessing Scrypted via `https://hostname.local:1234`. I'm hoping it's trivial for the app to switch to root-relative urls instead like:

```
<video src="/somepath/clip.mp4" controls="controls" autoplay="autoplay"></video>
```

**Comment by koush** [comment]
yeah should be trivial

**Comment by koush** [comment]
34c81557..f3f370d5
