### ISSUE TITLE
Import RTSP Camera in HomeKit as Doorbell

### ISSUE THREAD

**Issue by tonesto7** [koush/scrypted#37]
I want to start by saying what you have accomplished with cracking the HomeKit Secure Video is amazing.   I want to personally thank you for completing the missing piece for me to bring my Wyze Cameras in HomeKit with video recording.
I am the dev who created the Homebridge plugins for both SmartThings and Hubitat so I have a lot of experience with HomeKit.

I'm curious if it's possible to have your HomeKit plugin bring in devices marked as Doorbells into HomeKit as a doorbell?  
I have a Wyze Doorbell I would like to bring into HK.
I suppose since we don't have access to the doorbell button event it might be pointless but I'm curious nonetheless.

Thanks again for your time!

**Comment by koush** [comment]
Sure, join the discord. If you're a dev, I can help you get Wyze doorbell button events (hopefully depending on API availability) into Scrypted.
It's easy enough to change the device type to Doorbell, but without the doorbell event itself, it won't do anything.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/73924/139543413-4152f9a4-bb67-44d9-bfaa-e3e199a1beaf.png">

**Comment by tonesto7** [comment]
I forgot about this...  Eventhough, I know that I need button events for the doorbell when I set it as a doorbell it removes the Homekit plugin from that device.
