### ISSUE TITLE
Cannot Install on macOS

### ISSUE THREAD

**Issue by cschlittPHI** [koush/scrypted#373]
I keep getting the following error when trying to install on macOS:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/install-server - Not found
npm ERR! 404 
npm ERR! 404  'install-server@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I posted about this on [reddit](https://www.reddit.com/r/Scrypted/comments/wdmyv1/error_installing_on_macos/) but sadly nothing but others having the same issue.

Is there something I'm doing wrong?

**Comment by cschlittPHI** [comment]
This appears to be the problematic line: https://github.com/koush/scrypted/blob/main/docker/install-scrypted-dependencies-mac.sh#L94

**Comment by koush** [comment]
I suspect you have node_modules in your home directory. Let me see if I can fix this.

**Comment by koush** [comment]
can you get me the output of `brew --prefix node@18`

**Comment by aalmarshad** [comment]
I'm facing the same problem with Home Assistant Add-on. I deleted all the old container images and reinstall the add-on from the add-on store but the problem still exist. can you please update the image?
