### ISSUE TITLE
Database seems to corrupt easily if docker is not shutdown properly

### ISSUE THREAD

**Issue by skynet01** [koush/scrypted#374]
Hi there i noticed an issue if docker does not get shutdown properly or if the system loses power the database gets corrupted and Scrypted cant boot up. I keep getting these errors in console:

```
scrypted        | Terminated
scrypted        | OpenError: Corruption: no meta-nextfile entry in descriptor
scrypted        |     at /server/node_modules/levelup/lib/levelup.js:119:23
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        | OpenError: Corruption: no meta-nextfile entry in descriptor
scrypted        |     at /server/node_modules/levelup/lib/levelup.js:119:23
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        | OpenError: Corruption: no meta-nextfile entry in descriptor
scrypted        |     at /server/node_modules/levelup/lib/levelup.js:119:23
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
scrypted        |     at /server/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
```

This happened to me a few times within a week, once was when my mac updated and once when my docker crashed. Both times I had to restore the Scrypted config from backup. None of the other containers have this issue, is there anything that can be done to keep this from happening or maybe do some salvaging to that at least it can boot up properly.

**Comment by koush** [comment]
Docker on Mac? I sigterm/sigkill kill the process regularly and never run into this issue on mac. But it’s local install and not in docker.

**Comment by skynet01** [comment]
...Well actually the docker is installed on Ubuntu server that's running through Parallels on Mac mini m1 since Ubuntu server has better Arm support...  My point is that I doubt that I am the only one experiencing this issue :)

**Comment by koush** [comment]
level db is the same db used by chrome. it's pretty fault tolerant. this bug has been reported twice in the past year. I am inclined to think that this is an underlying issue with parallels + docker, and not flushing data to disk correctly on shutdown.

**Comment by skynet01** [comment]
Ah, good to know. Is there anything that can be done on my end to prevent this from happening (other then I guess not using parallels 😄) I can provide the db files that got corrupted. From the error it almost looks like something can be done were it gets around it? Maybe create blank metadata ... its one thing to loose the logs and super frustrating setting everything up again from scratch.

**Comment by koush** [comment]
No, this is really a question for the leveldb project.
