### ISSUE TITLE
ERR_CONNECTION_REFUSED on windows

### ISSUE THREAD

**Issue by hankinsoft** [koush/scrypted#377]
![Screen Shot 2022-09-14 at 11 35 14 AM](https://user-images.githubusercontent.com/3160528/190184637-46067e33-97f9-4d89-8709-4dea1657efaf.png)

Above screenshot shows the installation and the browser in the background with `ERR_CONNECTION_REFUSED` (refreshed after installation). Pressed 'Yes'/'Allow' on all prompts.

What details can provide to help figure this out?

**Comment by koush** [comment]
I believe there are logs in your `.scrypted` directory in user home. Can you find those? Let me know the exact path so I can document it. I don't have a Windows env here.

**Comment by hankinsoft** [comment]
I deleted the scrypted folder (C:\Users\<me>\.scrypted\), reinstalled NPM, rebooted, reinstalled scripted and everything started to work.
