### ISSUE TITLE
zsh: operation not permitted: /Users/jayliu/scrypted-main/server/scrypted-serve.sh

### ISSUE THREAD

**Issue by lzy31179** [koush/scrypted#38]
Hi @koush![image](https://user-images.githubusercontent.com/57745961/139563055-f860c28b-2529-4da3-a545-51dfcfbab753.png)![image](https://user-images.githubusercontent.com/57745961/139563084-d68e160c-8ffe-4268-8091-a9f7962df2f6.png)I have bought A new Mac mini(M1),but when I create a login script and run,it shows:
operation not permitted: /Users/jayliu/scrypted-main/server/scrypted-serve.sh
I have closed SIP but it didn't work,I don't know how to fix it.

**Comment by koush** [comment]
chmod +x that script.
