### ISSUE TITLE
Arlo plugin show 0% battery

### ISSUE THREAD

**Issue by sdugoten** [koush/scrypted#386]
![20220927_152050](https://user-images.githubusercontent.com/7108552/192552456-4627c588-f1e4-408c-b9ab-07b057f66942.jpg)

Using Arlo wired doorbell.   The doorbell always show 0%

**Comment by koush** [comment]
@bjia56

**Comment by bjia56** [comment]
What's the model ID for your doorbell?

**Comment by sdugoten** [comment]
I am using this wired doorbell from Arlo -->  AVD1001-100EUS

**Comment by sdugoten** [comment]
updated to Scrypted 0.33 and the doorbell no longer connect with the following error

[HomeKit]: HomeKit Connection ::ffff:10.0.1.98
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[HomeKit]: snapshot error Error: string is not a valid type. if you intended to send a url, use createMediaObjectFromUrl.
[HomeKit]:     at MediaManagerImpl.createMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:265:19)
[HomeKit]:     at MediaManagerImpl.ensureMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:229:25)
[HomeKit]:     at MediaManagerImpl.convertMediaObjectToBuffer (/server/node_modules/@scrypted/server/src/plugin/media.ts:247:76)
[HomeKit]:     at o (/src/types/camera/camera-snapshot.ts:29:43)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HomeKit]:     at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:98:22)
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[HomeKit]: snapshot error Error: string is not a valid type. if you intended to send a url, use createMediaObjectFromUrl.
[HomeKit]:     at MediaManagerImpl.createMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:265:19)
[HomeKit]:     at MediaManagerImpl.ensureMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:229:25)
[HomeKit]:     at MediaManagerImpl.convertMediaObjectToBuffer (/server/node_modules/@scrypted/server/src/plugin/media.ts:247:76)
[HomeKit]:     at o (/src/types/camera/camera-snapshot.ts:29:43)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HomeKit]:     at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:98:22)
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[WebRTC Plugin]: offer sdp v=0
[WebRTC Plugin]: o=- 6120189838816663398 2 IN IP4 127.0.0.1
[WebRTC Plugin]: s=-
[WebRTC Plugin]: t=0 0
[WebRTC Plugin]: a=group:BUNDLE 0 1
[WebRTC Plugin]: a=extmap-allow-mixed
[WebRTC Plugin]: a=msid-semantic: WMS
[WebRTC Plugin]: m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
[WebRTC Plugin]: c=IN IP4 0.0.0.0
[WebRTC Plugin]: a=rtcp:9 IN IP4 0.0.0.0
[WebRTC Plugin]: a=ice-ufrag:xs2g
[WebRTC Plugin]: a=ice-pwd:6jeFMJxqH4+5oAvjcmR9aSRD
[WebRTC Plugin]: a=ice-options:trickle
[WebRTC Plugin]: a=fingerprint:sha-256 EA:EF:93:6D:30:23:98:B8:3D:B7:9B:02:81:2C:AA:01:5E:EF:6A:CA:86:7F:18:22:19:00:80:FB:6D:A2:FD:BB
[WebRTC Plugin]: a=setup:actpass
[WebRTC Plugin]: a=mid:0
[WebRTC Plugin]: a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
[WebRTC Plugin]: a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
[WebRTC Plugin]: a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
[WebRTC Plugin]: a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
[WebRTC Plugin]: a=recvonly
[WebRTC Plugin]: a=rtcp-mux
[WebRTC Plugin]: a=rtpmap:111 opus/48000/2
[WebRTC Plugin]: a=rtcp-fb:111 transport-cc
[WebRTC Plugin]: a=fmtp:111 minptime=10;useinbandfec=1
[WebRTC Plugin]: a=rtpmap:63 red/48000/2
[WebRTC Plugin]: a=fmtp:63 111/111
[WebRTC Plugin]: a=rtpmap:103 ISAC/16000
[WebRTC Plugin]: a=rtpmap:104 ISAC/32000
[WebRTC Plugin]: a=rtpmap:9 G722/8000
[WebRTC Plugin]: a=rtpmap:0 PCMU/8000
[WebRTC Plugin]: a=rtpmap:8 PCMA/8000
[WebRTC Plugin]: a=rtpmap:106 CN/32000
[WebRTC Plugin]: a=rtpmap:105 CN/16000
[WebRTC Plugin]: a=rtpmap:13 CN/8000
[WebRTC Plugin]: a=rtpmap:110 telephone-event/48000
[WebRTC Plugin]: a=rtpmap:112 telephone-event/32000
[WebRTC Plugin]: a=rtpmap:113 telephone-event/16000
[WebRTC Plugin]: a=rtpmap:126 telephone-event/8000
[WebRTC Plugin]: m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 122 127 121 125 107 108 109 124 120 39 40 41 42 43 44 45 46 123 119 114 115 116 47
[WebRTC Plugin]: c=IN IP4 0.0.0.0
[WebRTC Plugin]: a=rtcp:9 IN IP4 0.0.0.0
[WebRTC Plugin]: a=ice-ufrag:xs2g
[WebRTC Plugin]: a=ice-pwd:6jeFMJxqH4+5oAvjcmR9aSRD
[WebRTC Plugin]: a=ice-options:trickle
[WebRTC Plugin]: a=fingerprint:sha-256 EA:EF:93:6D:30:23:98:B8:3D:B7:9B:02:81:2C:AA:01:5E:EF:6A:CA:86:7F:18:22:19:00:80:FB:6D:A2:FD:BB
[WebRTC Plugin]: a=setup:actpass
[WebRTC Plugin]: a=mid:1
[WebRTC Plugin]: a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
[WebRTC Plugin]: a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
[WebRTC Plugin]: a=extmap:13 urn:3gpp:video-orientation
[WebRTC Plugin]: a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
[WebRTC Plugin]: a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
[WebRTC Plugin]: a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
[WebRTC Plugin]: a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
[WebRTC Plugin]: a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
[WebRTC Plugin]: a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
[WebRTC Plugin]: a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
[WebRTC Plugin]: a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
[WebRTC Plugin]: a=recvonly
[WebRTC Plugin]: a=rtcp-mux
[WebRTC Plugin]: a=rtcp-rsize
[WebRTC Plugin]: a=rtpmap:96 VP8/90000
[WebRTC Plugin]: a=rtcp-fb:96 goog-remb
[WebRTC Plugin]: a=rtcp-fb:96 transport-cc
[WebRTC Plugin]: a=rtcp-fb:96 ccm fir
[WebRTC Plugin]: a=rtcp-fb:96 nack
[WebRTC Plugin]: a=rtcp-fb:96 nack pli
[WebRTC Plugin]: a=rtpmap:97 rtx/90000
[WebRTC Plugin]: a=fmtp:97 apt=96
[WebRTC Plugin]: a=rtpmap:98 VP9/90000
[WebRTC Plugin]: a=rtcp-fb:98 goog-remb
[WebRTC Plugin]: a=rtcp-fb:98 transport-cc
[WebRTC Plugin]: a=rtcp-fb:98 ccm fir
[WebRTC Plugin]: a=rtcp-fb:98 nack
[WebRTC Plugin]: a=rtcp-fb:98 nack pli
[WebRTC Plugin]: a=fmtp:98 profile-id=0
[WebRTC Plugin]: a=rtpmap:99 rtx/90000
[WebRTC Plugin]: a=fmtp:99 apt=98
[WebRTC Plugin]: a=rtpmap:100 VP9/90000
[WebRTC Plugin]: a=rtcp-fb:100 goog-remb
[WebRTC Plugin]: a=rtcp-fb:100 transport-cc
[WebRTC Plugin]: a=rtcp-fb:100 ccm fir
[WebRTC Plugin]: a=rtcp-fb:100 nack
[WebRTC Plugin]: a=rtcp-fb:100 nack pli
[WebRTC Plugin]: a=fmtp:100 profile-id=2
[WebRTC Plugin]: a=rtpmap:101 rtx/90000
[WebRTC Plugin]: a=fmtp:101 apt=100
[WebRTC Plugin]: a=rtpmap:35 VP9/90000
[WebRTC Plugin]: a=rtcp-fb:35 goog-remb
[WebRTC Plugin]: a=rtcp-fb:35 transport-cc
[WebRTC Plugin]: a=rtcp-fb:35 ccm fir
[WebRTC Plugin]: a=rtcp-fb:35 nack
[WebRTC Plugin]: a=rtcp-fb:35 nack pli
[WebRTC Plugin]: a=fmtp:35 profile-id=1
[WebRTC Plugin]: a=rtpmap:36 rtx/90000
[WebRTC Plugin]: a=fmtp:36 apt=35
[WebRTC Plugin]: a=rtpmap:37 VP9/90000
[WebRTC Plugin]: a=rtcp-fb:37 goog-remb
[WebRTC Plugin]: a=rtcp-fb:37 transport-cc
[WebRTC Plugin]: a=rtcp-fb:37 ccm fir
[WebRTC Plugin]: a=rtcp-fb:37 nack
[WebRTC Plugin]: a=rtcp-fb:37 nack pli
[WebRTC Plugin]: a=fmtp:37 profile-id=3
[WebRTC Plugin]: a=rtpmap:38 rtx/90000
[WebRTC Plugin]: a=fmtp:38 apt=37
[WebRTC Plugin]: a=rtpmap:102 H264/90000
[WebRTC Plugin]: a=rtcp-fb:102 goog-remb
[WebRTC Plugin]: a=rtcp-fb:102 transport-cc
[WebRTC Plugin]: a=rtcp-fb:102 ccm fir
[WebRTC Plugin]: a=rtcp-fb:102 nack
[WebRTC Plugin]: a=rtcp-fb:102 nack pli
[WebRTC Plugin]: a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
[WebRTC Plugin]: a=rtpmap:122 rtx/90000
[WebRTC Plugin]: a=fmtp:122 apt=102
[WebRTC Plugin]: a=rtpmap:127 H264/90000
[WebRTC Plugin]: a=rtcp-fb:127 goog-remb
[WebRTC Plugin]: a=rtcp-fb:127 transport-cc
[WebRTC Plugin]: a=rtcp-fb:127 ccm fir
[WebRTC Plugin]: a=rtcp-fb:127 nack
[WebRTC Plugin]: a=rtcp-fb:127 nack pli
[WebRTC Plugin]: a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
[WebRTC Plugin]: a=rtpmap:121 rtx/90000
[WebRTC Plugin]: a=fmtp:121 apt=127
[WebRTC Plugin]: a=rtpmap:125 H264/90000
[WebRTC Plugin]: a=rtcp-fb:125 goog-remb
[WebRTC Plugin]: a=rtcp-fb:125 transport-cc
[WebRTC Plugin]: a=rtcp-fb:125 ccm fir
[WebRTC Plugin]: a=rtcp-fb:125 nack
[WebRTC Plugin]: a=rtcp-fb:125 nack pli
[WebRTC Plugin]: a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
[WebRTC Plugin]: a=rtpmap:107 rtx/90000
[WebRTC Plugin]: a=fmtp:107 apt=125
[WebRTC Plugin]: a=rtpmap:108 H264/90000
[WebRTC Plugin]: a=rtcp-fb:108 goog-remb
[WebRTC Plugin]: a=rtcp-fb:108 transport-cc
[WebRTC Plugin]: a=rtcp-fb:108 ccm fir
[WebRTC Plugin]: a=rtcp-fb:108 nack
[WebRTC Plugin]: a=rtcp-fb:108 nack pli
[WebRTC Plugin]: a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
[WebRTC Plugin]: a=rtpmap:109 rtx/90000
[WebRTC Plugin]: a=fmtp:109 apt=108
[WebRTC Plugin]: a=rtpmap:124 H264/90000
[WebRTC Plugin]: a=rtcp-fb:124 goog-remb
[WebRTC Plugin]: a=rtcp-fb:124 transport-cc
[WebRTC Plugin]: a=rtcp-fb:124 ccm fir
[WebRTC Plugin]: a=rtcp-fb:124 nack
[WebRTC Plugin]: a=rtcp-fb:124 nack pli
[WebRTC Plugin]: a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
[WebRTC Plugin]: a=rtpmap:120 rtx/90000
[WebRTC Plugin]: a=fmtp:120 apt=124
[WebRTC Plugin]: a=rtpmap:39 H264/90000
[WebRTC Plugin]: a=rtcp-fb:39 goog-remb
[WebRTC Plugin]: a=rtcp-fb:39 transport-cc
[WebRTC Plugin]: a=rtcp-fb:39 ccm fir
[WebRTC Plugin]: a=rtcp-fb:39 nack
[WebRTC Plugin]: a=rtcp-fb:39 nack pli
[WebRTC Plugin]: a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
[WebRTC Plugin]: a=rtpmap:40 rtx/90000
[WebRTC Plugin]: a=fmtp:40 apt=39
[WebRTC Plugin]: a=rtpmap:41 H264/90000
[WebRTC Plugin]: a=rtcp-fb:41 goog-remb
[WebRTC Plugin]: a=rtcp-fb:41 transport-cc
[WebRTC Plugin]: a=rtcp-fb:41 ccm fir
[WebRTC Plugin]: a=rtcp-fb:41 nack
[WebRTC Plugin]: a=rtcp-fb:41 nack pli
[WebRTC Plugin]: a=fmtp:41 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=f4001f
[WebRTC Plugin]: a=rtpmap:42 rtx/90000
[WebRTC Plugin]: a=fmtp:42 apt=41
[WebRTC Plugin]: a=rtpmap:43 H264/90000
[WebRTC Plugin]: a=rtcp-fb:43 goog-remb
[WebRTC Plugin]: a=rtcp-fb:43 transport-cc
[WebRTC Plugin]: a=rtcp-fb:43 ccm fir
[WebRTC Plugin]: a=rtcp-fb:43 nack
[WebRTC Plugin]: a=rtcp-fb:43 nack pli
[WebRTC Plugin]: a=fmtp:43 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
[WebRTC Plugin]: a=rtpmap:44 rtx/90000
[WebRTC Plugin]: a=fmtp:44 apt=43
[WebRTC Plugin]: a=rtpmap:45 AV1/90000
[WebRTC Plugin]: a=rtcp-fb:45 goog-remb
[WebRTC Plugin]: a=rtcp-fb:45 transport-cc
[WebRTC Plugin]: a=rtcp-fb:45 ccm fir
[WebRTC Plugin]: a=rtcp-fb:45 nack
[WebRTC Plugin]: a=rtcp-fb:45 nack pli
[WebRTC Plugin]: a=rtpmap:46 rtx/90000
[WebRTC Plugin]: a=fmtp:46 apt=45
[WebRTC Plugin]: a=rtpmap:123 H264/90000
[WebRTC Plugin]: a=rtcp-fb:123 goog-remb
[WebRTC Plugin]: a=rtcp-fb:123 transport-cc
[WebRTC Plugin]: a=rtcp-fb:123 ccm fir
[WebRTC Plugin]: a=rtcp-fb:123 nack
[WebRTC Plugin]: a=rtcp-fb:123 nack pli
[WebRTC Plugin]: a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
[WebRTC Plugin]: a=rtpmap:119 rtx/90000
[WebRTC Plugin]: a=fmtp:119 apt=123
[WebRTC Plugin]: a=rtpmap:114 red/90000
[WebRTC Plugin]: a=rtpmap:115 rtx/90000
[WebRTC Plugin]: a=fmtp:115 apt=114
[WebRTC Plugin]: a=rtpmap:116 ulpfec/90000
[WebRTC Plugin]: a=rtpmap:47 flexfec-03/90000
[WebRTC Plugin]: a=rtcp-fb:47 goog-remb
[WebRTC Plugin]: a=rtcp-fb:47 transport-cc
[WebRTC Plugin]: a=fmtp:47 repair-window=10000000
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: sig change have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: sig change stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: answer sdp v=0
[WebRTC Plugin]: o=- 12214849 0 IN IP4 0.0.0.0
[WebRTC Plugin]: s=-
[WebRTC Plugin]: t=0 0
[WebRTC Plugin]: a=group:BUNDLE 0 1
[WebRTC Plugin]: a=extmap-allow-mixed
[WebRTC Plugin]: a=msid-semantic:WMS *
[WebRTC Plugin]: m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8
[WebRTC Plugin]: c=IN IP4 0.0.0.0
[WebRTC Plugin]: a=ice-ufrag:b4d2
[WebRTC Plugin]: a=ice-pwd:040efbc97f804e1e93fc7e
[WebRTC Plugin]: a=ice-options:trickle
[WebRTC Plugin]: a=fingerprint:sha-256 65:FC:3F:C4:4A:22:A0:55:E5:9E:2B:79:6F:59:4F:10:99:C6:37:1B:39:19:37:EE:75:52:73:31:07:C5:CE:00
[WebRTC Plugin]: a=setup:active
[WebRTC Plugin]: a=sendonly
[WebRTC Plugin]: a=mid:0
[WebRTC Plugin]: a=msid:c8e3eb4c-5611-4b16-90e8-b0cf47009a12 3bf9c8a0-643b-4d07-81d0-5fb267f88e58
[WebRTC Plugin]: a=rtcp:9 IN IP4 0.0.0.0
[WebRTC Plugin]: a=rtcp-mux
[WebRTC Plugin]: a=ssrc:3339474539 cname:752aee53-080a-492e-beb7-cfc34278a53d
[WebRTC Plugin]: a=rtpmap:111 opus/48000/2
[WebRTC Plugin]: a=rtcp-fb:111 transport-cc
[WebRTC Plugin]: a=fmtp:111 minptime=10;useinbandfec=1
[WebRTC Plugin]: a=rtpmap:0 PCMU/8000
[WebRTC Plugin]: a=rtpmap:8 PCMA/8000
[WebRTC Plugin]: m=video 9 UDP/TLS/RTP/SAVPF 102 127 125 108 124 39 41 43 123
[WebRTC Plugin]: c=IN IP4 0.0.0.0
[WebRTC Plugin]: a=ice-ufrag:b4d2
[WebRTC Plugin]: a=ice-pwd:040efbc97f804e1e93fc7e
[WebRTC Plugin]: a=ice-options:trickle
[WebRTC Plugin]: a=fingerprint:sha-256 65:FC:3F:C4:4A:22:A0:55:E5:9E:2B:79:6F:59:4F:10:99:C6:37:1B:39:19:37:EE:75:52:73:31:07:C5:CE:00
[WebRTC Plugin]: a=setup:active
[WebRTC Plugin]: a=sendonly
[WebRTC Plugin]: a=mid:1
[WebRTC Plugin]: a=msid:d75516ba-aa4f-4af9-9c77-e715181b8fa1 5df3b1d3-8417-4280-b48d-d9a34d7cf9ba
[WebRTC Plugin]: a=rtcp:9 IN IP4 0.0.0.0
[WebRTC Plugin]: a=rtcp-mux
[WebRTC Plugin]: a=ssrc:2706376465 cname:752aee53-080a-492e-beb7-cfc34278a53d
[WebRTC Plugin]: a=rtpmap:102 H264/90000
[WebRTC Plugin]: a=rtcp-fb:102 goog-remb
[WebRTC Plugin]: a=rtcp-fb:102 transport-cc
[WebRTC Plugin]: a=rtcp-fb:102 ccm fir
[WebRTC Plugin]: a=rtcp-fb:102 nack
[WebRTC Plugin]: a=rtcp-fb:102 nack pli
[WebRTC Plugin]: a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
[WebRTC Plugin]: a=rtpmap:127 H264/90000
[WebRTC Plugin]: a=rtcp-fb:127 goog-remb
[WebRTC Plugin]: a=rtcp-fb:127 transport-cc
[WebRTC Plugin]: a=rtcp-fb:127 ccm fir
[WebRTC Plugin]: a=rtcp-fb:127 nack
[WebRTC Plugin]: a=rtcp-fb:127 nack pli
[WebRTC Plugin]: a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
[WebRTC Plugin]: a=rtpmap:125 H264/90000
[WebRTC Plugin]: a=rtcp-fb:125 goog-remb
[WebRTC Plugin]: a=rtcp-fb:125 transport-cc
[WebRTC Plugin]: a=rtcp-fb:125 ccm fir
[WebRTC Plugin]: a=rtcp-fb:125 nack
[WebRTC Plugin]: a=rtcp-fb:125 nack pli
[WebRTC Plugin]: a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
[WebRTC Plugin]: a=rtpmap:108 H264/90000
[WebRTC Plugin]: a=rtcp-fb:108 goog-remb
[WebRTC Plugin]: a=rtcp-fb:108 transport-cc
[WebRTC Plugin]: a=rtcp-fb:108 ccm fir
[WebRTC Plugin]: a=rtcp-fb:108 nack
[WebRTC Plugin]: a=rtcp-fb:108 nack pli
[WebRTC Plugin]: a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
[WebRTC Plugin]: a=rtpmap:124 H264/90000
[WebRTC Plugin]: a=rtcp-fb:124 goog-remb
[WebRTC Plugin]: a=rtcp-fb:124 transport-cc
[WebRTC Plugin]: a=rtcp-fb:124 ccm fir
[WebRTC Plugin]: a=rtcp-fb:124 nack
[WebRTC Plugin]: a=rtcp-fb:124 nack pli
[WebRTC Plugin]: a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
[WebRTC Plugin]: a=rtpmap:39 H264/90000
[WebRTC Plugin]: a=rtcp-fb:39 goog-remb
[WebRTC Plugin]: a=rtcp-fb:39 transport-cc
[WebRTC Plugin]: a=rtcp-fb:39 ccm fir
[WebRTC Plugin]: a=rtcp-fb:39 nack
[WebRTC Plugin]: a=rtcp-fb:39 nack pli
[WebRTC Plugin]: a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
[WebRTC Plugin]: a=rtpmap:41 H264/90000
[WebRTC Plugin]: a=rtcp-fb:41 goog-remb
[WebRTC Plugin]: a=rtcp-fb:41 transport-cc
[WebRTC Plugin]: a=rtcp-fb:41 ccm fir
[WebRTC Plugin]: a=rtcp-fb:41 nack
[WebRTC Plugin]: a=rtcp-fb:41 nack pli
[WebRTC Plugin]: a=fmtp:41 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=f4001f
[WebRTC Plugin]: a=rtpmap:43 H264/90000
[WebRTC Plugin]: a=rtcp-fb:43 goog-remb
[WebRTC Plugin]: a=rtcp-fb:43 transport-cc
[WebRTC Plugin]: a=rtcp-fb:43 ccm fir
[WebRTC Plugin]: a=rtcp-fb:43 nack
[WebRTC Plugin]: a=rtcp-fb:43 nack pli
[WebRTC Plugin]: a=fmtp:43 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
[WebRTC Plugin]: a=rtpmap:123 H264/90000
[WebRTC Plugin]: a=rtcp-fb:123 goog-remb
[WebRTC Plugin]: a=rtcp-fb:123 transport-cc
[WebRTC Plugin]: a=rtcp-fb:123 ccm fir
[WebRTC Plugin]: a=rtcp-fb:123 nack
[WebRTC Plugin]: a=rtcp-fb:123 nack pli
[WebRTC Plugin]: a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: done waiting ice connected
[WebRTC Plugin]: ice transport ip { address: '10.0.1.2', port: 59707, turnServer: false }
[WebRTC Plugin]: Connection is local network: true
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: rebroadcast mode: rtsp
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsps://arlostreaming140-z1-prod.wowza.arlo.com:443/vzmodulelive/A54208KCA0774_1664995685827?egressToken=9293fd40_7706_4d43_8bd8_c957e6c358a3&userAgent=iOS&cameraId=A54208KCA0774_1664995685827&txnId=be!2d45d7be-5a2f-49c7-b998-f14b8a0f91f6 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN rtsps://arlostreaming140-z1-prod.wowza.arlo.com:443/vzmodulelive/A54208KCA0774_1664995685827?egressToken=9293fd40_7706_4d43_8bd8_c957e6c358a3&userAgent=iOS&cameraId=A54208KCA0774_1664995685827&txnId=be!2d45d7be-5a2f-49c7-b998-f14b8a0f91f6 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at TLSSocket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:113478)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:events:525:35)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at node:net:757:14
[Rebroadcast Plugin]:     at TCP.done (node:_tls_wrap:584:7)
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: sig change closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[HomeKit]: HomeKit Connection ::ffff:10.0.1.98
[Rebroadcast Plugin]: Selected stream Cloud RTSP
[HomeKit]: snapshot error Error: string is not a valid type. if you intended to send a url, use createMediaObjectFromUrl.
[HomeKit]:     at MediaManagerImpl.createMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:265:19)
[HomeKit]:     at MediaManagerImpl.ensureMediaObjectRemote (/server/node_modules/@scrypted/server/src/plugin/media.ts:229:25)
[HomeKit]:     at MediaManagerImpl.convertMediaObjectToBuffer (/server/node_modules/@scrypted/server/src/plugin/media.ts:247:76)
[HomeKit]:     at o (/src/types/camera/camera-snapshot.ts:29:43)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HomeKit]:     at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:98:22)
[HomeKit]: HomeKit Connection ::ffff:10.0.1.132
[Rebroadcast Plugin]: Selected stream Cloud RTSP

**Comment by sdugoten** [comment]
This is brand new instance of Scrypted 0.34 with completely new config, same error

[log.txt](https://github.com/koush/scrypted/files/9722938/log.txt)

**Comment by bjia56** [comment]
arlo plugin 0.3.3 should have removed the Battery interface from AVD1001 devices - can you please test?

**Comment by sdugoten** [comment]
confirm it is working now.

**Comment by sdugoten** [comment]
[https://i.imgur.com/L845jSc.jpeg](url)

i don't know what happen, but the battery 0% is back

**Comment by sdugoten** [comment]
![L845jSc](https://user-images.githubusercontent.com/7108552/201535292-eb5c16ea-1580-43a5-837b-6beb98546ccb.jpg)

**Comment by bjia56** [comment]
@sdugoten can you please see if 0.3.6 fixes this for you?

**Comment by sdugoten** [comment]
I guess the final issue with this plugin is that the webRTC plugin display the video from Arlo plugin is way smoother than when I see it on homekit on iphone.  Let me record some video and raise a new case for that
