### ISSUE TITLE
Abode cam support?

### ISSUE THREAD

**Issue by sdugoten** [koush/scrypted#387]
Wonder if any plugin support Abode cam?

https://goabode.co.uk/products/abode-cam?gclid=CjwKCAjw4c-ZBhAEEiwAZ105RWOQ1EeRdE6hHT0BpH-FQXzRlJQHrJR1yK2wE_ZAyvwklmbaQPz7iRoC308QAvD_BwE

**Comment by koush** [comment]
feel free to contribute one
