### ISSUE TITLE
Add http request for camera 

### ISSUE THREAD

**Issue by fennec622** [koush/scrypted#39]
Hi

I wan't to try very good project but i wan't to use camera from zoneminder not directly RTSP

I try to add directly HTTP adress to RTSP url but nothing

For have video with zoneminder you use http like that 

http://127.0.0.1/zm/cgi-bin/nph-zms?mode=jpeg&monitor=10&user=user&pass=pass

It's ok with ffmpeg -i 

IS it possible to add http video adress to plugin rtsp camera ? or make plugin http camera 

Thanks

**Comment by koush** [comment]
I could, but it would require a continual transcode to work with homekit secure video. I would not recommend it.

**Comment by fennec622** [comment]
Ok thanks works very good with Homebridge ffmpeg 

But no HSV 

thanks
