### ISSUE TITLE
Google Device Setup - "Something Went Wrong Error"

### ISSUE THREAD

**Issue by fkick** [koush/scrypted#397]
Hello,

I'm trying to get the Google Device Access plugin setup following the directions at https://github.com/koush/scrypted/blob/main/plugins/google-device-access/README.md

I'm able to get as far as step 42. but when I select my gmail address, I get a page that displays the error "Something Went Wrong, Please contact the developer of this app if the issue persists." and I'm unable to login to the gmail account.

Any thoughts?

Thanks

**Comment by koush** [comment]
No idea. The steps are all there, and Google makes this wonderfully complicated.

**Comment by Wh1t3Rose** [comment]
@fkick @koush did u ever solved this? Im also getting this. Highly considering selling my Google doorbell Cam

**Comment by fkick** [comment]
No, I have not gotten it to work with the newer wired doorbell
