### ISSUE TITLE
Ring Doorbell Stream not working - [Rebroadcast Plugin]: H264 oddity detected.

### ISSUE THREAD

**Issue by Sinthos** [koush/scrypted#399]
I tried to setup the ring doorbell plugin and homekit plugin but can't get the stream to load. It only shows a snapshot.
Also the detected resolution and bitrate seems odd: -10x16 @ 841 Kb/s
Settings are all at default, standalone mode is active, active integrations are: HomeKit, HomeKit Secure Video Local Copy, Rebroadcast Plugin

`[HomeKit]: destination address 192.168.xx.xx 49753 52865
[HomeKit]: source address 192.168.xx.xx 51721 39340
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: '460c805a-00d8-4b10-9997-29abf1c9d342',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3963578352,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 980772042,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: Will wait for initial RTCP packet. { isHomeHub: false, isLowBandwidth: false, hasHomeHub: false }
[HomeKit]: {
[HomeKit]:   dynamicBitrate: false,
[HomeKit]:   isLowBandwidth: false,
[HomeKit]:   isWatch: false,
[HomeKit]:   destination: 'local'
[HomeKit]: }
[Rebroadcast Plugin]: Selected stream SIP
[Rebroadcast Plugin]: SIP prebuffer session started
[Rebroadcast Plugin]: rebroadcast mode: rtsp
starting/refreshing stream
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://127.0.0.1:38732 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
ring sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 34.248.76.193
t=0 0
m=audio 41129 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:63372 IN IP4 34.248.76.193
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8x1V7d/bvFnqYhfcD3z8vadj2EhqBSR4Xbhzjcfe
a=ptime:20
m=video 58011 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:25758 IN IP4 34.248.76.193
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:LOczpTsbe+/HGqdYKluB2Ojlu3tg5rMrAcJBCgB1

proposed sdp v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:63372 IN IP4 34.248.76.193
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8x1V7d/bvFnqYhfcD3z8vadj2EhqBSR4Xbhzjcfe
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:25758 IN IP4 34.248.76.193
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:LOczpTsbe+/HGqdYKluB2Ojlu3tg5rMrAcJBCgB1

request headers OPTIONS rtsp://127.0.0.1:38732 RTSP/1.0
CSeq: 0
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
CSeq: 0

[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://127.0.0.1:38732 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
request headers DESCRIBE rtsp://127.0.0.1:38732 RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Content-Base: rtsp://127.0.0.1:38732
Content-Type: application/sdp
CSeq: 1
Content-Length: 540

response body v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4
s=Wantajobinstead?
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:63372 IN IP4 34.248.76.193
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8x1V7d/bvFnqYhfcD3z8vadj2EhqBSR4Xbhzjcfe
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:25758 IN IP4 34.248.76.193
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:LOczpTsbe+/HGqdYKluB2Ojlu3tg5rMrAcJBCgB1

[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Content-Base: rtsp://127.0.0.1:38732
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Content-Length: 540
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=Wantajobinstead? 1529310922 1529310923 IN IP4
[Rebroadcast Plugin]: s=Wantajobinstead?
[Rebroadcast Plugin]: c=IN IP4 127.0.0.1
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: m=audio 0 RTP/SAVPF 0
[Rebroadcast Plugin]: a=control:trackID=0
[Rebroadcast Plugin]: a=rtpmap:0 PCMU/8000
[Rebroadcast Plugin]: a=rtcp:63372 IN IP4 34.248.76.193
[Rebroadcast Plugin]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8x1V7d/bvFnqYhfcD3z8vadj2EhqBSR4Xbhzjcfe
[Rebroadcast Plugin]: a=ptime:20
[Rebroadcast Plugin]: m=video 0 RTP/SAVPF 99
[Rebroadcast Plugin]: a=control:trackID=1
[Rebroadcast Plugin]: a=rtpmap:99 H264/90000
[Rebroadcast Plugin]: a=fmtp:99 profile-level-id=42801F
[Rebroadcast Plugin]: a=rtcp:25758 IN IP4 34.248.76.193
[Rebroadcast Plugin]: a=rtcp-fb:99 nack
[Rebroadcast Plugin]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:LOczpTsbe+/HGqdYKluB2Ojlu3tg5rMrAcJBCgB1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://127.0.0.1:38732/trackID=0 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
request headers SETUP rtsp://127.0.0.1:38732/trackID=0 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2
User-Agent: Scrypted
response headers RTSP/1.0 200 OK
Session: 25d7163e
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2

[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Session: 25d7163e
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://127.0.0.1:38732/trackID=1 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Session: 25d7163e
[Rebroadcast Plugin]: 
request headers SETUP rtsp://127.0.0.1:38732/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3
User-Agent: Scrypted
Session: 25d7163e
response headers RTSP/1.0 200 OK
Session: 25d7163e
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3

[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Session: 25d7163e
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: Audio codec plugin reported vs detected mismatch pcm_mulaw undefined
[Rebroadcast Plugin]: Detected audio codec is not mp4/mpegts compatible. pcm_ulaw
[Rebroadcast Plugin]: refreshing media stream in 89116
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  PLAY rtsp://127.0.0.1:38732 RTSP/1.0
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Session: 25d7163e
[Rebroadcast Plugin]: 
request headers PLAY rtsp://127.0.0.1:38732 RTSP/1.0
Range: npt=0.000-
CSeq: 4
User-Agent: Scrypted
Session: 25d7163e
response headers RTSP/1.0 200 OK
RTP-Info: url=rtsp://127.0.0.1:38732/trackID=0,url=rtsp://127.0.0.1:38732/trackID=1
Range: npt=now-
Session: 25d7163e
CSeq: 4

[Rebroadcast Plugin]: sending prebuffer 4000
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: RTP-Info: url=rtsp://127.0.0.1:38732/trackID=0,url=rtsp://127.0.0.1:38732/trackID=1
[Rebroadcast Plugin]: Range: npt=now-
[Rebroadcast Plugin]: Session: 25d7163e
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: 
[HomeKit]: { tool: undefined, rtpSender: 'Default' }
[HomeKit]: H264 oddities are reported in the stream. Using FFmpeg.
[HomeKit]: Waiting for video RTCP packet before sending video.
[HomeKit]: Received first video RTCP packet.
[HomeKit]: -hide_banner -analyzeduration 0 -probesize 500000 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -an -sn -dn -vcodec copy -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params g5lK47AGvOkdrfUICt7otH512kXBYrSYcUEc252Q -payload_type 99 -ssrc 11778315 -f rtp srtp://192.168.xx.xx:49753?rtcpport=49753&pkt_size=1378 -vn -sn -dn -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 6327874 -f rtp rtp://127.0.0.1:58769?rtcpport=52865&pkt_size=400
[HomeKit]: packet loss 1
[Rebroadcast Plugin]: SIP active rebroadcast clients: 1
[Rebroadcast Plugin]: H264 oddity detected.
[Rebroadcast Plugin]: parsed bitstream sps { width: 20, height: 4 }
[Rebroadcast Plugin]: sending prebuffer 10000
[HomeKit]: Guessed Channel Layout for Input Stream #0.0 : mono
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:41506':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Wantajobinstead?
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: N/A
[HomeKit]:   Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[HomeKit]:   Stream #0:1: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 28.58 tbr, 90k tbn
[HomeKit]: Output #0, rtp, to 'srtp://192.168.xx.xx:49753?rtcpport=49753&pkt_size=1378':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Wantajobinstead?
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]:   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 28.58 tbr, 90k tbn
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: SDP:
[HomeKit]: v=0
[HomeKit]: o=- 0 0 IN IP4 127.0.0.1
[HomeKit]: s=Wantajobinstead?
[HomeKit]: t=0 0
[HomeKit]: a=tool:libavformat 59.16.100
[HomeKit]: m=video 49753 RTP/AVP 99
[HomeKit]: c=IN IP4 192.168.xx.xx
[HomeKit]: a=rtpmap:99 H264/90000
[HomeKit]: a=fmtp:99 packetization-mode=1; sprop-parameter-sets=Z2QAKKx2gHgCJ+XARAAAAwAEAAADAPA8IhG4,aO44gAA=; profile-level-id=640028
[HomeKit]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:g5lK47AGvOkdrfUICt7otH512kXBYrSYcUEc252Q
[HomeKit]: m=audio 58769 RTP/AVP 110
[HomeKit]: c=IN IP4 127.0.0.1
[HomeKit]: b=AS:24
[HomeKit]: a=rtpmap:110 opus/48000/2
[HomeKit]: first forwarded opus packet received.
[HomeKit]: received first audio packet
[Rebroadcast Plugin]: RTSP WRITE client closed.
`

**Comment by koush** [comment]
read the homekit troubleshooting guide.

**Comment by koush** [comment]
GitHub is an issue tracker, not a support forum.
