### ISSUE TITLE
ffmpeg-static doesn't exist for FreeBSD, but ffmpeg does

### ISSUE THREAD

**Issue by ascl00** [koush/scrypted#402]
I am using Scrypted on FreeBSD (well, TrueNAS actually), and it runs fine with a minor change... however I don't know enough about npm packaging to know how to do this properly. In short, I removed the dependency on ffmpeg-static, and added a path to the ffmpeg binary.
```
diff --git a/server/package.json b/server/package.json
index 659ffa51..792546ce 100644
--- a/server/package.json
+++ b/server/package.json
@@ -13,7 +13,6 @@
     "debug": "^4.3.1",
     "engine.io": "^6.2.0",
     "express": "^4.17.2",
-    "ffmpeg-static": "^5.1.0",
     "http-auth": "^4.1.9",
     "ip": "^1.1.8",
     "level": "^6.0.1",
diff --git a/server/src/plugin/media.ts b/server/src/plugin/media.ts
index 11535ad8..222c904d 100644
--- a/server/src/plugin/media.ts
+++ b/server/src/plugin/media.ts
@@ -1,6 +1,6 @@
 import { BufferConverter, DeviceManager, FFmpegInput, MediaManager, MediaObject, MediaObjectOptions, MediaStreamUrl, ScryptedInterface, ScryptedInterfaceProperty, ScryptedMimeTypes, ScryptedNativeId, SystemDeviceState, SystemManager } from"@scrypted/types";
 import axios from 'axios';
-import pathToFfmpeg from 'ffmpeg-static';
+var pathToFfmpeg='/usr/local/bin/ffmpeg';
 import fs from 'fs';
 import https from 'https';
 import mimeType from 'mime';
```

This is obviously not workable to commit, but at least allows it to run.

**Comment by koush** [comment]
you can use `SCRYPTED_FFMPEG_PATH` env variable to customize your ffmpeg.

**Comment by ascl00** [comment]
Neat thanks for that. Doesn't stop the package dependency issue I think?

**Comment by koush** [comment]
> Neat thanks for that. Doesn't stop the package dependency issue I think?

Does scrypted fail to start? It should work fine if ffmpeg-static fails to download the package.

**Comment by ascl00** [comment]
Failed to install dependencies without the package.json edit. 

Is it possible to make the dependency conditional?

**Comment by ascl00** [comment]
Just tested with a clean check out and the environment variable set. You are completely correct, parts of the dependency install fail, but scrypted runs just fine.

Thank you!

**Comment by carmanj** [comment]
@ascl00 Do you happen to have any more details about what it took to get Scrypted running on TrueNAS Core?

Thanks!
Justin

**Comment by ascl00** [comment]
I just checked out the source from git, made the changes in the PR, and ran npm install to get the dependencies and rpm run serve. Nothing special. Using the environment variable also worked but I had issues installing dependencies, so reverted to using this change. Quite possibly I'm holding it wrong, I'm not a nodejs expert at all.
