### ISSUE TITLE
Arlo wired doorbell AVD1001-100EUS no sound in homekit

### ISSUE THREAD

**Issue by sdugoten** [koush/scrypted#403]
Doorbell is Arlo AVD1001-100EUS

Both recorded and stream have no audio.  Video and HKSV works.  Have tried transcoding plugin with copy video transcode audio, no difference.  Since Arlo doorbell have built in homekit support, just no HKSV.  The provided homekit integration video have no issue on audio.

[log.txt](https://github.com/koush/scrypted/files/9795426/log.txt)

**Comment by mikesalz** [comment]
Same issue for me.  I have the Arlo Baby and Arlo Ultra system.  All had audio when directly connected to HomeKit, but none have audio using Scrypted.

**Comment by koush** [comment]
I think this might be the packaged ffmpeg not supporting some aac variants.

**Comment by mikesalz** [comment]
Thanks for the feedback @koush! Is this something that we as users can/should change on our end, or is this something that would have to be updated in the plugin?

**Comment by koush** [comment]
Can you tell me if you have audio in the scrypted web interface?

**Comment by sdugoten** [comment]
> Can you tell me if you have audio in the scrypted web interface?

no audio for me on scrypted web interface

**Comment by koush** [comment]
can you try changing your rebroadcast parser to ffmpeg (tcp)

**Comment by sdugoten** [comment]
![image](https://user-images.githubusercontent.com/7108552/198741328-5607045c-6390-4230-84b6-6375ac40c2f8.png)

on this screen, do I check all the checkbox here?

**Comment by sdugoten** [comment]
> can you try changing your rebroadcast parser to ffmpeg (tcp)

forgot to tag you in last reply, please see the image above

**Comment by koush** [comment]
no, that's not what I'm talking about. disable that.

**Comment by sdugoten** [comment]
![image](https://user-images.githubusercontent.com/7108552/198746206-9d02c7d3-b21f-4390-8106-c6b759e66698.png)

ok, this setting works.  Just enable FFmpeg (TCP), and not using transcoding.

**Comment by sdugoten** [comment]
> no, that's not what I'm talking about. don't use transcoding, disable it.

It works.  I guess the last question is... should I use accessory mode?

![image](https://user-images.githubusercontent.com/7108552/198746462-374255d7-f2ac-4cfa-8392-e3d4ffce8124.png)

**Comment by koush** [comment]
audio works with that setting?

**Comment by sdugoten** [comment]
> audio works with that ffmpeg tcp setting?

Yes, audio works with that ffmpeg tcp setting.  And these are the plugin I enabled

![image](https://user-images.githubusercontent.com/7108552/198747570-ede53aae-a4bb-4df4-b385-b4164649f2a4.png)

The only question I now have is that should I use bridge mode or accessory mode in the homekit setting, the image that I posted in my last message.

**Comment by mikesalz** [comment]
@koush Changing RTSP Parser to FFmpeg (TCP) worked for me as well.  Thank you for your help!

I have another unrelated question if you don't mind.  On all of my Arlo cameras and Ring doorbell, I get "Snapshot Failed" nearly every time I open the Home app.  It usually resolves itself after some time.  I have tried multiple variations of enabling/disabling Snapshots from Prebuffer, as well as changing Snapshot Mode to Never Wait and Timeout.  And I do have the snapshot plugin installed.  Any suggestions?

**Comment by koush** [comment]
I'm going to be removing ffmpeg parser. Please set it back to default and try the HomeKit ffmpeg sender instead.

**Comment by mikesalz** [comment]
Sorry, I just want to make sure I understand correctly.  You're asking to change the RTSP Parser back to Default?  And where would I select HomeKit ffmpeg?

**Comment by koush** [comment]
![image](https://user-images.githubusercontent.com/73924/198752647-4b6f4506-7f99-4e3a-a453-702e3b87ecfc.png)

Rtp sender

**Comment by mikesalz** [comment]
I changed RTP Sender from Scrypted to FFmpeg but that doesn't seem to help the Snapshot Failed issue.

![IMG_0169](https://user-images.githubusercontent.com/46855061/198755931-ee89ff8d-d507-4122-8b8d-790a815a9937.jpeg)

**Comment by koush** [comment]
Please stay on topic. This is about arlo audio.

**Comment by mikesalz** [comment]
Fair enough.  I can submit that as a separate issue/question.  As far as Arlo - As you suggested, I changed the RTSP Parser back to Default and changed the HomeKit RTP Sender from Scrypted to FFmpeg.  But doing that removed the audio again.

**Comment by koush** [comment]
Probably this issue. Working on a fix. https://github.com/mpv-player/mpv/issues/5669#issuecomment-932519409

**Comment by koush** [comment]
Might be fixed in beta homekit plugin.

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/eeff2f98249c6385a509f7304351dab4b8508857

**Comment by AndrewAdventure** [comment]
> https://github.com/koush/scrypted/commit/eeff2f98249c6385a509f7304351dab4b8508857

Hi. I'm using the latest version of scrypted/arlo, do i still need to follow above mods. Thanks in advance.
