### ISSUE TITLE
Alexa Skill can't be enabled

### ISSUE THREAD

**Issue by rvansoest** [koush/scrypted#404]
I changed my server this week and I try to reconnect to alexa as I disabled it fist because the camera's weren't updated. But I now get the following error "We were unable to link Scrypted Home Automation at this time.". Also i always get a redirect link where I have to copy paste a part to get further. {"httpRedirectLocation":"https://skills-store.amazon.com/api/skill/link/M14OJJW3N35UJK? ---etc.

**Comment by koush** [comment]
You may also need to delete and reinstall the cloud plugin (and log back into it), if you switched servers.

**Comment by rvansoest** [comment]
I removed it from the old server and reinstalled it on the new one. Still the same error. any other ideas?

**Comment by koush** [comment]
Oh if you just log in again into cloud it will change which server if points to.

**Comment by rvansoest** [comment]
I just removed the cloud plugin from my former server and the current. Installed it again on my server and now it works. Alexa skill linking is fixed to now. Thank you for helping me.

**Comment by koush** [comment]
Oh, I thought you had turned your former server off already. Currently it's one login per server, but I'll fix that sometime soon.

**Comment by rvansoest** [comment]
i turned it off but didn't remove the software and plugins.

**Comment by rvansoest** [comment]
That was problably the problem. When I removed it from the old server I was able to link the new one.
