### ISSUE TITLE
Imou support

### ISSUE THREAD

**Issue by drodmantras** [koush/scrypted#407]
Would it be possible to implement support for imou account, similar to arlo or ring so it would be porrible to show doorbells in scrypted?

**Comment by drodmantras** [comment]
But the imou cloud is not supported, it would be great addition if you could log in to imou account and get your devices listed and stream them through cloud since in some case as for example db60 linked to ds21 chime does not get ip fron the network but is streaming from the cloud via the chimes network.

**Comment by drodmantras** [comment]
Couls maybe be possible with this https://open.imoulife.com/book/http/device/live/summary.html and this https://open.imoulife.com/book/push/alarm.html

**Comment by koush** [comment]
I'm not accepting plugin requests. If someone wants to build something, they can.
