### ISSUE TITLE
No Doorbell Chime on HomePods with G4 Doorbell

### ISSUE THREAD

**Issue by alexiscordova** [koush/scrypted#409]
I recently noticed that despite the toggles being on, none of my HomePods are playing a chime when my G4 Doorbell rings. Just upgraded to iOS 16.1, latest versions of Scrypted, Unifi Plugin, and HomeKit plugins. I've power cycled the HomePods and my Synology (where Scrypted is installed) but still no chime. Any tips on debugging this?

**Comment by koush** [comment]
Use discord for support. This is an issue tracker for bugs.

**Comment by koush** [comment]
Usually an apple issue.
