### ISSUE TITLE
Native install on Synology armv7

### ISSUE THREAD

**Issue by gerarddvb** [koush/scrypted#412]
Hello,

I have a simple Synology DS218j (armada38x armv7) NAS that cannot run Docker.
Is there a way to install it without Docker?

oznu did this with homebridge some time ago, and it works really well.
I now use a raspberry pi only for Scrypted.
Would love to move Scrypted to the NAS.

**Comment by koush** [comment]
docker or the local linux installation instructions

**Comment by gerarddvb** [comment]
Local linux installation does not work, because APT does not work on DSM7 ARM Synology NAS.

```
G@Server:~$ curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-dependencies-linux.sh | sudo SERVICE_USER=$USER bash
Password: 
Stopping existing service if it is running...
Failed to stop scrypted.service: Unit scrypted.service not loaded.
ignoring FROM buildpack-deps:bullseye

## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
bash: apt-get: command not found
Error executing command, exiting
main: line 16: apt-get: command not found
Error during previous command.
G@Server:~$ 

```
