### ISSUE TITLE
Hikvision - Line Cross & Intrusion Detection Support

### ISSUE THREAD

**Issue by JohnClay** [koush/scrypted#413]
Exposing line cross and intrusion alerts as motion sensors would be very helpful.

It looks like the `linedetection` and `fielddetection` events are being used for these.
[alertStream w line and intrusion.txt](https://github.com/koush/scrypted/files/9913261/alertStream.w.line.and.intrusion.txt)

**Comment by vincedarley** [comment]
Would also find these very helpful. In case useful I noticed work in home-assistant that enables such support (https://www.home-assistant.io/integrations/hikvision/ ) 

Happy to share logs/details from my camera if useful.

**Comment by SirBigBits** [comment]
I have two Hikvision 2387 G2's and I'm using Intrusion detections just fine with Scrypted NVR.  I know that doesn't fix your issue.

**Comment by n1kDon** [comment]
I am using node red with the hikvision ultimate plugin to expose the raw camera events to mqtt. Maybe that would be a workaround for you.
