### ISSUE TITLE
Cloud camera packet loss never loads

### ISSUE THREAD

**Issue by robjampar** [koush/scrypted#415]
with a nest wired doorbell cloud camera, I've been getting

```
[HomeKit]: received first audio packet
[HomeKit]: packet loss 1
[HomeKit]: ffmpeg exited
```

and the stream never loads... but I don't think it's a network issue as my raspberry pi is wired via LAN and only has 1 cloud camera attached, and the camera is right next to an access point and has a great connection,

If I restart Scrypted it fixes and loads fine a couple times... and then the problem comes back

**Comment by robjampar** [comment]
i've attached log files below. 
To me it looks like when it works the "Rebroadcast" plugin tried to make a new connection to the stream, whereas when it fails the "Rebroadcast" reuses an existing connection (?)


[logs_success.txt](https://github.com/koush/scrypted/files/9920041/logs_success.txt)
[logs_fail.txt](https://github.com/koush/scrypted/files/9920042/logs_fail.txt)

**Comment by koush** [comment]
nest has inconsistent iframe intervals, disable rebroadcast.
