### ISSUE TITLE
nest drop cam

### ISSUE THREAD

**Issue by valiquette** [koush/scrypted#416]
After the last round of updates one camera an older nest drop cam has stopped working.
restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rebroadcast mode: rtsp
[Rebroadcast Plugin]: prebuffer session ended with error host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: @scrypted/google-device-access:host
[Rebroadcast Plugin]: Error: Request failed with status code 500
[Rebroadcast Plugin]:     at createError (/node_modules/axios/lib/core/createError.js:16:15)
[Rebroadcast Plugin]:     at settle (/node_modules/axios/lib/core/settle.js:17:12)
[Rebroadcast Plugin]:     at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
[Rebroadcast Plugin]:     at IncomingMessage.emit (node:events:525:35)
[Rebroadcast Plugin]:     at IncomingMessage.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at endReadableNT (node:internal/streams/readable:1358:12)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds

This error keeps repeating until 429s kick in.
all other cameras are fine.

**Comment by koush** [comment]
nest service error.
