### ISSUE TITLE
Very high temperature on Rpi 4

### ISSUE THREAD

**Issue by fade2metal** [koush/scrypted#42]
The OpenCv plugin brings the temperature of my rpi4 to higher than 80°C. (Only 2 cameras added)

Is there any chance to add support for a USB edge TPU?
If the edge tpu would be used for motion detection there wouldn’t be any temperature issue with the pi.

Btw.: really great project!!!
Thank you so much for bringing the chance to add Homekit secure video to 3rd party cams!

**Comment by koush** [comment]
Yeah the OpenCV plugin will do that. I can likely improve the performance of the opencv backend, but it's fairly low priority. What sort of cameras do you have that don't have a plugin that has built in motion detection?

**Comment by fade2metal** [comment]
My cameras are some from Accevo.
They have built in motion detection and I could use mail for motion sensor. But I don't want the cameras to have connection to the internet, my Firewall is blocking them because they connect to an unknown vpn cloud service.

I didn't find any other possibilities to get motion detection from those cameras.

Isn't there a version of OpenCV that support the google coral tpu?

Thank you so much for your very fast reply!

**Comment by koush** [comment]
Get the SMTP plugin. The plugin mail is entirely local. You will direct the mail at the scrypted server.
