### ISSUE TITLE
Add Reolink Doorbell Support for Reolink Plugin - pleazzzz :) 

### ISSUE THREAD

**Issue by skynet01** [koush/scrypted#421]
Reolink released a [POE and Wifi Doorbell](https://reolink.com/us/product/reolink-video-doorbell/). The Doorbell ding (referred to as Visitor) is published on ONVIF in the tns1:RuleEngine/MyRuleDetector/Visitor section. Can this be implemented on the Reolink plugin?

Here is a thread to the logs that helped implement this in a Home Assistant Reolink plugin: https://github.com/JimStar/reolink_cctv/discussions/43#discussioncomment-4036538
additional debug in this thread:
https://github.com/JimStar/reolink_cctv/issues/49

Additionally, a new firmware for POE Doorbell must be installed for this to work (wifi doorbell ships working out of the box). (New firmware also appears to be more stable and I don't have missed ONVIF motion notifications)

POE Reolink Doorbell - version: 1459_22102808: https://drive.google.com/file/d/1WH6tef5x4RfH9WcHQrxWWOadN049UjFH/view?usp=sharing
Wifi  Reolink Doorbell - version: 1459_22102806: https://drive.google.com/file/d/1WKDSj5dQX8ApbAMwzCwVI7g05dGGiusj/view?usp=sharing

Thank you so much!

**Comment by koush** [comment]
already done, it supports onvif.

**Comment by skynet01** [comment]
Got it, do I need to put tns1:RuleEngine/MyRuleDetector/Visitor into the message event? Just switching the device to doorbell doesn't make it work.

**Comment by nanosonde** [comment]
@skynet01 Does it also support ONVIF Profile-T two-way audio using RTSP backchannel?`

**Comment by skynet01** [comment]
As far as I know none of the Reolink cameras support Profile-T two-way audio

**Comment by nanosonde** [comment]
My hope was that they implemented this at least for the doorbell. 
I have already sent them a feature request a long time ago concerning profile-T and their other PoE-cameras. As you said: still no support.

At least here is some audio talkback code about the proprietary protocol of the reolink cameras.
https://github.com/thirtythreeforty/neolink/blob/master/src/talk/mod.rs

**Comment by skynet01** [comment]
I guess they do have Profile-T support for Reolink Doorbell according to this topic: https://community.reolink.com/topic/4465/onvif-profile-t-for-poe-doorbell

Would be nice to know what the Trigger topic is as tns1:RuleEngine/MyRuleDetector/Visitor does not work for the ONVIF scripted plugin 

![Screenshot 2022-11-16 at 11 47 56 AM](https://user-images.githubusercontent.com/8117544/202290091-3db2dd99-bcc5-47c5-b5ba-c2bad0f05d3e.jpg)

..and the Reolink Scrypted plugin has the option to set it as type Doorbell.. except that doesn't work and you won't be able to add it to homekit integration. That dropdown option should be removed and documentation added to the plugin that for Doorbell we should all use ONVIF plugin instead and what event Trigger to use.

**Comment by timvdsm** [comment]
Hi @skynet01 
Can you test it without the tns1 in front?
So only "RuleEngine/MyRuleDetector/Visitor"

**Comment by skynet01** [comment]
Yep I can confirm it works with just "RuleEngine/MyRuleDetector/Visitor" if you use the onvif plugin with the latest POE firmware

![image](https://user-images.githubusercontent.com/8117544/210650435-3a57e339-073e-4de3-a106-9cc9ae1399bb.png)
