### ISSUE TITLE
Can overriding the advertised server address be re-enabled for the HomeKit plugin?

### ISSUE THREAD

**Issue by ownaginatious** [koush/scrypted#429]
I'm currently running Scrypted under `docker-compose` in a fairly stripped down mode (i.e. just the `scrypted` container with bridged networking with a UI and HomeKit accessory port mapped through) on a VLAN separate from my main network.

I am using an `avahi` reflector on my `docker` host to pass the HomeKit mDNS records into my main network.

Everything works great, except the address being published in the HomeKit mDNS records is that of the `scrypted` container itself (i.e. its private address on the `docker` bridge). HomeAssistant allows overriding the address that's actually published with an `advertise_ip` setting, where you can instead have the mDNS records advertise the address your `docker` host exposes to your main network.

It looks like `HAP-NodeJS` does support similar functionality, as documented [here](https://github.com/homebridge/HAP-NodeJS/blob/d25600554e82a20905cd55c4eeefbf10487badbd/src/lib/Accessory.ts#L227), but it was commented out in the HomeKit plugin for some reason [here](https://github.com/koush/scrypted/blob/main/plugins/homekit/src/main.ts#L288).

Would it be possible to re-enable this, or was it causing problems?

**Comment by koush** [comment]
Yeah, I forget why it is commented out. I think I might need a separate setting for the advertisement vs the bind port.

**Comment by ownaginatious** [comment]
I found a workaround by using `macvlan` to directly expose the `docker` container to the VLAN and use an address within its subnet. I then punched a hole in the firewall to allow stuff in my regular LAN to talk to this particular address in my VLAN.

I looked through the code for `ciao` and unfortunately, it doesn't seem to support setting the advertised address (at least not in an explicit way), so I'm going to close this as it's not really an issue for this project and the workaround isn't too complicated.

I must add though: `scrypted` works wonderfully! I'm simply in awe of how fast this is compared to my previous HomeAssistant based solution. And with working 2-way audio out-of-the-box for my crappy Amcrest cameras. Wow!

Thanks for bringing this all together, @koush!

**Comment by koush** [comment]
I'm going to leave this open as a tracking issue.

**Comment by ownaginatious** [comment]
> So the setting doesn't work for ciao at all huh?

Whoops, I meant to say `HAP-NodeJS` (not `ciao`). I didn't try messing around with it, but I get the impression that it probably does work (i.e. setting `bind`) but the way `bind` can be interpreted is so confusingly overloaded that I think it would probably cause more problems than it would help by exposing it 😕

**Comment by koush** [comment]
the bind is used now
