### ISSUE TITLE
Can’t access camera stream from outside my wifi

### ISSUE THREAD

**Issue by ituri** [koush/scrypted#43]
Hi,

I’m really happy that I stumbled upon scrypted! I’m using it with two UniFi cameras and the rebroadcast plugin and I’m amazed by how fast playback starts once I open a camera stream in my home app. This setup is working much better than the UniFi-protect plugin for homebridge which I used before. 
One question though: I can’t open the stream when I’m not in my wifi. Are there any ports I need to forward or any other settings I have to consider?

Thanks!

**Comment by koush** [comment]
You will want to set your HomeKit Hub IP here, that is what is managing your external stream:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/73924/140622176-48a339bc-35a2-400b-975c-976af6191087.png">


Then use a lower resolution stream here:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/73924/140622181-17ea6462-a4f5-4445-a86c-5ef95280f60f.png">

**Comment by koush** [comment]
hop on discord if you have further issues.

**Comment by ituri** [comment]
Thank you, it's working now! 😊
