### ISSUE TITLE
Homekit devices no longer showing up in Home app

### ISSUE THREAD

**Issue by burntcookie90** [koush/scrypted#430]
After a recent docker update, my 3 Unifi cameras are no longer showing up in my Home app. I've reset the homekit pairing as well as fully repaired the bridge to the home app with no luck. The video feeds show in Scrypted without issue.

Versions:
```
Apple:
3x Apple TV: 16.1
Homepod Mini: 16.1
iOS: 16.0.3
```

```
Scrypted:
Scrypted: 0.3.8
Homekit Plugin: 1.1.55
Rebroadcast: 0.9.46
Scrypted Core: 0.1.51
Unifi Protect: 0.0.123
WebRTC: 0.0.99
```

```
Unifi:
Protect: 1.8.0
```

**Comment by koush** [comment]
Your cameras are in accessory mode, not bridge mode. You need to pair each camera, not the bridge. Apple deprecated bridge mode cameras (rather, they introduced a bug in this unsupported usage).
