### ISSUE TITLE
docker-compose script installs docker when SKIP_DOCKER_INSTALL=true

### ISSUE THREAD

**Issue by jadomski** [koush/scrypted#431]
When setting `export SKIP_DOCKER_INSTALL=true` and then running `curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-docker-compose.sh | sudo SERVICE_USER=$USER bash` the script still proceeds to install docker and the associated components even though it is designed not to. I have tested this across two Debian-based systems and the behaviour is the same across both.

**Comment by koush** [comment]
I see, I am guessing the export doesn't pass through to sudo.

**Comment by jadomski** [comment]
I tried `sudo export` but that comes back with `sudo: export: command not found`

Perhaps the script could accept an input variable to bypass docker installation instead?

**Comment by koush** [comment]
try `curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-docker-compose.sh  SKIP_DOCKER_INSTALL=true sudo SERVICE_USER=$USER bash`

**Comment by jadomski** [comment]
That almost does it, looks like we need to include the -E variable after the sudo command, like this:

`curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-docker-compose.sh | SKIP_DOCKER_INSTALL=true sudo -E SERVICE_USER=$USER bash`

I've updated https://github.com/koush/scrypted/wiki/Installation:-Docker-Compose-Linux to reflect this.
