### ISSUE TITLE
HKSV with Ezviz doorbell

### ISSUE THREAD

**Issue by Stetocasa** [koush/scrypted#439]
Hello, thanks for your fantastic job.
Is there any possibility to integrate this product to use in HomeKit with HKSV?
Thanks

![image](https://user-images.githubusercontent.com/70729310/203711465-bfec4d87-30d1-43e1-930b-509b95abf638.jpeg)

**Comment by koush** [comment]
if someone does it sure

**Comment by tda20300** [comment]
This thread was opened a long time ago, I wish it could be resumed and someone could launch a solution for those of us who have this camera, thank you very much for your work
