### ISSUE TITLE
HikVision Camera Controller Motion detection periodically stops working 

### ISSUE THREAD

**Issue by Ostromogilski** [koush/scrypted#44]
Every night, approximately after 3:30AM GMT+2 motion detection on cameras stop working until I reload HikVision Camera Controller plugin. Running Scrypted on RPi4 using Docker

**Comment by Ostromogilski** [comment]
I figuered out that is stops working exactly at 4:00 AM GMT+2. Don't know which process causes this. But It can be fixed with an automation which will reload  HikVision Camera Controller plugin. Could anyone help me with shell script to reload this plugin?
Tried 'nmp restart' but it  doesn't work.

**Comment by koush** [comment]
Can you check to see if reloading the rebroadcast plugin resolves this too?

**Comment by jonathanwilner** [comment]
I also have this error, using a HikVision NVR. Never knew what it was until I read this issue ! Thank you @Ostromogilski for filing it! Happy to also test things. I will also check re: the rebroadcast plugin.

**Comment by koush** [comment]
I believe the original issue may have been fixed. Please update your docker and plugins. If there's another issue, please file a new bug.

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/ed9de9c2de9733b29c43e6987daf0c8b07e3b31c#diff-5fe5ed9ec7ce3cf88595da0443f80a358ad7064196d608272bf485dac8808f23
