### ISSUE TITLE
Alexa skill cannot be enabled

### ISSUE THREAD

**Issue by autumnwalker** [koush/scrypted#440]
Brand new install of Scrypted - I've successfully configured the cloud plugin and the Alexa plugin. I can login to Scrypted from inside and outside my network.

When I attempt to load the Alexa Skill I get the pitangui.amazon.com httpReditecLocation screen. I saw another issue where the resolution was to copy + paste the redirect location URL into a browser window - but when I do that I get a message saying "we were unable to link Scrypted Home Automation at this time".

Thoughts?

**Comment by autumnwalker** [comment]
Able to work around by visiting this link on desktop computer: https://www.amazon.com/ClockworkMod-Scrypted-Home-Automation/dp/B09WHHD9VN/ref=sr_1_1?crid=7S908L4CJOK3&keywords=scrypted&qid=1669323767&s=digital-skills&sprefix=scrypte%2Calexa-skills%2C126&sr=1-1

Then pasting the URL from the resulting JSON blob in the address bar of the same browser window.

**Comment by koush** [comment]
fixed
