### ISSUE TITLE
TPLink Tapo C110 - 401 unauthorized

### ISSUE THREAD

**Issue by upamanyudas** [koush/scrypted#441]
Receiving the following error connecting to the camera through the OnVif plugin. The screen says snapshot failed, although the stream URL works on VLC. Any help appreciated.

>[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rebroadcast mode: rtsp
stream url rtsp://10.10.0.140:554/stream1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://10.10.0.140:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Thu, Nov 24 2022 23:50:14 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, GET_PARAMETER, SET_PARAMETER
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://10.10.0.140:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Thu, Nov 24 2022 23:50:14 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="119c19f14039bd9af8c450dca0266017"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://10.10.0.140:554/stream1 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic dXBhbWFueXU6UG9rZW1vbiU0MDIwMTU=
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Thu, Nov 24 2022 23:50:15 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-Link IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-Link IP-Camera", nonce="f1b432a17eb59df00e148ee8e5297d36"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message

**Comment by koush** [comment]
probably need to enable onvif authentication or add an onvif user.

**Comment by upamanyudas** [comment]
I've using using the onvif user to connect. And it seems to work since the motion events get detected. But I don't seem to get an image!

**Comment by koush** [comment]
Can you disable BASIC authentication. It seems to have two auth options.

**Comment by upamanyudas** [comment]
Sorry if it's a silly question, where do I disable the BASIC auth? I'm guessing somewhere in Scrypted? If you could direct me there, that'd be much appreciated.

**Comment by koush** [comment]
might be a tapo setting.

**Comment by upamanyudas** [comment]
I couldn't find it in the Tapo app. I don't think it's a Tapo setting. Still facing a similar problem. One more new piece info showed up in the console : 

><?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope                          ><SOAP-ENV:Header><wsa5:Action SOAP-ENV:mustUnderstand="true">http://www.onvif.org/ver10/events/wsdl/EventPortType/GetEventPropertiesResponse</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><tev:GetEventPropertiesResponse><tev:TopicNamespaceLocation>http://www.onvif.org/onvif/ver10/topics/topicns.xml</tev:TopicNamespaceLocation><wsnt:FixedTopicSet>true</wsnt:FixedTopicSet><wstop:TopicSet><tns1:RuleEngine><CellMotionDetector><Motion wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsMotion"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></Motion></CellMotionDetector><IntrusionDetector><Intrusion wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsIntrusion"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></Intrusion></IntrusionDetector><LineCrossDetector><LineCross wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsLineCross"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></LineCross></LineCrossDetector><PeopleDetector><People wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsPeople"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></People></PeopleDetector><TPSmartEventDetector><TPSmartEvent wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsTPSmartEvent"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></TPSmartEvent></TPSmartEventDetector></tns1:RuleEngine></wstop:TopicSet><wsnt:TopicExpressionDialect>http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet</wsnt:TopicExpressionDialect><wsnt:TopicExpressionDialect>http://docs.oasis-open.org/wsn/t-1/TopicExpression/Concrete</wsnt:TopicExpressionDialect><tev:MessageContentFilterDialect>http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter</tev:MessageContentFilterDialect><tev:MessageContentSchemaLocation>http://www.onvif.org/onvif/ver10/schema/onvif.xsd</tev:MessageContentSchemaLocation></tev:GetEventPropertiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by upamanyudas** [comment]
I couldn't find it in the Tapo app. I don't think it's a Tapo setting. Still facing a similar problem. One more new piece info showed up in the console :

><?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope                          ><SOAP-ENV:Header><wsa5:Action SOAP-ENV:mustUnderstand="true">http://www.onvif.org/ver10/events/wsdl/EventPortType/GetEventPropertiesResponse</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><tev:GetEventPropertiesResponse><tev:TopicNamespaceLocation>http://www.onvif.org/onvif/ver10/topics/topicns.xml</tev:TopicNamespaceLocation><wsnt:FixedTopicSet>true</wsnt:FixedTopicSet><wstop:TopicSet><tns1:RuleEngine><CellMotionDetector><Motion wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsMotion"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></Motion></CellMotionDetector><IntrusionDetector><Intrusion wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsIntrusion"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></Intrusion></IntrusionDetector><LineCrossDetector><LineCross wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsLineCross"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></LineCross></LineCrossDetector><PeopleDetector><People wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsPeople"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></People></PeopleDetector><TPSmartEventDetector><TPSmartEvent wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoSourceConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="tt:ReferenceToken" Name="VideoAnalyticsConfigurationToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Type="xsd:string" Name="Rule"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Type="xsd:boolean" Name="IsTPSmartEvent"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></TPSmartEvent></TPSmartEventDetector></tns1:RuleEngine></wstop:TopicSet><wsnt:TopicExpressionDialect>http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet</wsnt:TopicExpressionDialect><wsnt:TopicExpressionDialect>http://docs.oasis-open.org/wsn/t-1/TopicExpression/Concrete</wsnt:TopicExpressionDialect><tev:MessageContentFilterDialect>http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter</tev:MessageContentFilterDialect><tev:MessageContentSchemaLocation>http://www.onvif.org/onvif/ver10/schema/onvif.xsd</tev:MessageContentSchemaLocation></tev:GetEventPropertiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by nazgul6** [comment]
I just managed to set up C110 in Scrypted using the ONVIF plugin. You need to override HTTP port to 2020. Also, in the Tapo app, under the. camera's advanced settings, you need to set up a user name/password that you will use to connect (this only works when SD card recording is disabled).
