### ISSUE TITLE
Password reset.

### ISSUE THREAD

**Issue by TyagiShailesh** [koush/scrypted#443]
My password was stored in keychain so I'm sure I am entering the correct password but I am not able to login. It says user not found. Strange.  I saw https://github.com/koush/scrypted/wiki/Lost-Password-and-User-Reset but how do I do this on a docker container? I have a done a config optimization and it's goin to be a pain to do it allover again.

**Comment by koush** [comment]
this is a docker question. set it no container startup via the command line or compose file.
