### ISSUE TITLE
Install not working on Mac, problem with pycoral 2.0

### ISSUE THREAD

**Issue by drinkmorewaters** [koush/scrypted#452]
Trying to install on a MacBook and there is an issue with the install script when installing, it gets stuck at pycoral 2.0 then fails.

```Running: pip3 install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
ERROR: Could not find a version that satisfies the requirement pycoral~=2.0 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
ERROR: No matching distribution found for pycoral~=2.0
Error during previous command. Ignoring.
Installing Scrypted Launch Agent...
Running: mkdir -p /Users/nas/Library/LaunchAgents
Installing Scrypted...
Running: /usr/local/opt/node@18/bin/npx -y scrypted@latest install-server
/Users/nas/.scrypted/install-scrypted-dependencies-mac.sh: line 9: 21184 Illegal instruction: 4  $@
Error during previous command.
nas@NASs-MacBook```

**Comment by ownaginatious** [comment]
Looks like `bash` isn't interpreting `$@` correctly. I think I've seen this happen after a major macOS distribution upgrade (e.g. Monterey -> Ventura). Probably your dev binaries may need to be upgraded.

Try: `brew upgrade` and then run the installation again to see if it works this time.

**Comment by drinkmorewaters** [comment]
It was a brand new, fresh install of xcode, brew and other tooling, everything was upgraded. Just doesn't work.
