### ISSUE TITLE
Scrypted cloud login fails

### ISSUE THREAD

**Issue by drinkmorewaters** [koush/scrypted#453]
I have tried to signup using, apple, google and email and all auth ways fail, then a login is given and then it says "Username does not exist". It is the callback that seems fine for the login, then there is a loading symbol for the dashboard, then it logs out of the account and then there is only an email login screen.

![image](https://user-images.githubusercontent.com/41403831/205472969-66550ea4-9388-4500-be20-f6c5ba42c12a.png)

![image](https://user-images.githubusercontent.com/41403831/205472983-3672f2ae-7744-4bb7-8746-2fecd37cedf2.png)

![image](https://user-images.githubusercontent.com/41403831/205472987-407de355-b29e-4a15-88d4-75e381157a02.png)

**Comment by koush** [comment]
it worked. use your local login now.
