### ISSUE TITLE
In HomeKit, cameras go offline and then back online several times a day

### ISSUE THREAD

**Issue by mikesalz** [koush/scrypted#458]
All Scrypted cameras (varying brands) are going offline at the same time periodically, and then coming right back up.  I noticed a few people mentioning this on Discord as well, but I didn't see an official issue posted.

**Comment by koush** [comment]
99% sure this is an apple home hub issue cause this also happens on their official homekit cameras.

**Comment by koush** [comment]
can disable the notification since it isn't actually offline, just home hub switching or whatever.
