### ISSUE TITLE
Error while installing on macOS Big Sur - line 9: 40721 Illegal instruction: 4  $@

### ISSUE THREAD

**Issue by tibtiby** [koush/scrypted#459]
Clean Big Sur installed.
Installed Homebrew.
Everything went fine. Then, when I tried installing Scrypted I got:

Running: pip3 install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.3.1)
Running: pip3 install aiofiles debugpy typing_extensions typing opencv-python
Requirement already satisfied: aiofiles in /usr/local/lib/python3.10/site-packages (22.1.0)
Requirement already satisfied: debugpy in /usr/local/lib/python3.10/site-packages (1.6.4)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.10/site-packages (4.4.0)
Requirement already satisfied: typing in /usr/local/lib/python3.10/site-packages (3.7.4.3)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/site-packages (from opencv-python) (1.23.5)
Running: pip3 install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
**ERROR: Could not find a version that satisfies the requirement pycoral~=2.0 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
ERROR: No matching distribution found for pycoral~=2.0
Error during previous command. Ignoring.**
Installing Scrypted Launch Agent...
Running: mkdir -p /Users/main/Library/LaunchAgents
**Installing Scrypted...
Running: /usr/local/opt/node@18/bin/npx -y scrypted@latest install-server
/Users/main/.scrypted/install-scrypted-dependencies-mac.sh: line 9: 29562 Illegal instruction: 4 $@
Error during previous command.**
<img width="721" alt="Screenshot 2022-12-10 at 03 30 38" src="https://user-images.githubusercontent.com/33070044/206822043-8e51a913-c089-4fb7-a9bf-76972f2e7e43.png">

And nothing works. I installed pycoral, I installed tensorflow...nothing works. How the heck do you fix this?

**Comment by koush** [comment]
Probably an ancient Mac and brew tooling is failing. Get on ventura.

**Comment by tibtiby** [comment]
upgraded la Monterey, same issue.
works fine in Ubuntu.
so there is a problem on MacOS and I have seen a couple of other people over in the youtube comments section having the same problem…

**Comment by koush** [comment]
illegal instruction generally means old cpu, what model Mac is it

**Comment by tibtiby** [comment]
mac mini mid 2010, but when running Ubuntu, it can install locally, no problem.

**Comment by koush** [comment]
use ubuntu then
