### ISSUE TITLE
Unifi Streams/Recordings Won't Load

### ISSUE THREAD

**Issue by hm0486** [koush/scrypted#46]
Still images update every 10s, top right of each camera "block" shoes the red recording dot, activity notifications coming through, BUT when I open a camera to view stream and/or recordings, it just gets stuck loading and eventually says camera isn't responding.  Any ideas?

**Comment by paparapapapapa** [comment]
Same here with RTSP generic. After installation it was working flawlessly then this happens.

I tried to restart the host and to reinstall all the plugins (rtsp, opencv, rebroadcast and HomeKit) but nothing changed. Also, event recording works great and the streaming of events is fluid. Just real time stream doesn't work.

**Comment by koush** [comment]
Common issue with servers with multiple network interfaces (virtual ones, etc).

```
HomeKit Recordings are working but Live Streaming times out

This is a networking issue with multiple interfaces. This is the problem 100% of the time. Use the HomeKit Address Override setting, and set it to the IP Address of your ethernet manually. 
```

**Comment by paparapapapapa** [comment]
I tried the local installation, the Docker one, I tried to reboot the Apple TV, to disable the ffmpeg plugin in Homebridge and even to lower resolution and bitrate on the camera itself. Still the problem persist. My host has only one hardware LAN interface, Wi-Fi is disabled from the BIOS and afaik it has not a lot of virtual devices. Please give me some more hints. TY

**Comment by koush** [comment]
> Use the HomeKit Address Override setting, and set it to the IP Address of your ethernet manually.

**Comment by hm0486** [comment]
Apologies if I'm being dense here.  Are you saying to edit the "Bridge Address" under "Network" settings within the HomeKit plugin?  I had set that to the ethernet IP of my host and was still having this issue.  If it's helpful, I'm running Scrypted in Docker on a Raspberry Pi.

**Comment by koush** [comment]
> Apologies if I'm being dense here. Are you saying to edit the "Bridge Address" under "Network" settings within the HomeKit plugin? I had set that to the ethernet IP of my host and was still having this issue. If it's helpful, I'm running Scrypted in Docker on a Raspberry Pi.

Yes, that is correct. Can you get me a list of network interfaces for your pi as shown in the command line using ifconfig.

**Comment by hm0486** [comment]
br-3a5ef13028bb: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:58ff:fef5:902  prefixlen 64  scopeid 0x20<link>
        ether 02:42:58:f5:09:02  txqueuelen 0  (Ethernet)
        RX packets 72490  bytes 9971524 (9.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 76134  bytes 10908266 (10.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:d5:29:37:fc  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.218  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fd35:a502:9973:1:977f:ded5:17e4:9d1f  prefixlen 64  scopeid 0x0<global>
        inet6 fd5f:e157:e74c:1:8fbd:cc81:d6cf:424e  prefixlen 64  scopeid 0x0<global>
        inet6 fdfc:c93:4a9b:1:cede:a058:de6c:9886  prefixlen 64  scopeid 0x0<global>
        inet6 fd8b:ba0b:9245:3:1983:6ba4:5609:8e04  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::628b:e770:b33a:afe9  prefixlen 64  scopeid 0x20<link>
        inet6 fd1a:1bb6:a47d:3:b614:8386:69eb:23df  prefixlen 64  scopeid 0x0<global>
        inet6 fdab:a8cf:8536:1:b15f:e574:d22:bd48  prefixlen 64  scopeid 0x0<global>
        ether e4:5f:01:5d:5c:90  txqueuelen 1000  (Ethernet)
        RX packets 3468303  bytes 2142210263 (1.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2206837  bytes 723685974 (690.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 329263  bytes 341281379 (325.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 329263  bytes 341281379 (325.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth10add30: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.184.74  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::54ff:2dff:feab:6c02  prefixlen 64  scopeid 0x20<link>
        ether 56:ff:2d:ab:6c:02  txqueuelen 0  (Ethernet)
        RX packets 72490  bytes 10986384 (10.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 83953  bytes 13822293 (13.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by koush** [comment]
Let me see the docker command you used to run

**Comment by paparapapapapa** [comment]
In my case this is the output

`docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether redacted  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.5  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 redacted  prefixlen 64  scopeid 0x20<link>
        ether redacted  txqueuelen 1000  (Ethernet)
        RX packets 51004770  bytes 56239680262 (56.2 GB)
        RX errors 0  dropped 2449  overruns 0  frame 0
        TX packets 28926175  bytes 4661559237 (4.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xdc200000-dc220000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Loopback locale)
        RX packets 13090399  bytes 225690956268 (225.6 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13090399  bytes 225690956268 (225.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by hm0486** [comment]
docker pull koush/scrypted

docker run --privileged --network host -d --restart unless-stopped -e LD_LIBRARY_PATH=/opt/vc/lib -e SCRYPTED_FFMPEG_PATH_ENV_VARIABLE=SCRYPTED_RASPBIAN_FFMPEG_PATH -v /opt/vc:/opt/vc -v ~/.scrypted/volume:/server/volume koush/scrypted

That's straight from the terminal history, though I don't recall actually typing a chunk of that 2nd command.

**Comment by koush** [comment]
Can you screenshot the rebroadcast media information tab for the camera, will have codec information etc.

**Comment by hm0486** [comment]
![Screenshot 2021-11-15 141314](https://user-images.githubusercontent.com/71946294/141840344-7c7c60f7-32d9-4bce-aad7-9910ce1fe19a.png)

**Comment by paparapapapapa** [comment]
![Schermata 2021-11-16 alle 00 17 44](https://user-images.githubusercontent.com/56885560/141867818-e726b6bd-51ee-4991-91ae-e3e6d4a83117.png)

**Comment by koush** [comment]
> ![Schermata 2021-11-16 alle 00 17 44](https://user-images.githubusercontent.com/56885560/141867818-e726b6bd-51ee-4991-91ae-e3e6d4a83117.png)
> No way to change to 1920 on the camera, but it worked for a while at first.

Please open a separate issue. You've hijacked a Unifi bug here.

**Comment by koush** [comment]
@hm0486 Which unifi is this?

**Comment by paparapapapapa** [comment]
oh sorry, I overlooked the title and it seemed similar to my issue (I have a unifi dream machine as router)

**Comment by hm0486** [comment]
That particular grab is for a G4 Pro, but I also have a G4 Bullet and a Doorbell.  All running off a UDM-Pro and Protect version 1.19.2.

**Comment by koush** [comment]
Can you the disable rebroadcast and see if streaming works? Also join the discord #unifi-protect channel and I can help out further. need Console logs, etc.

**Comment by hm0486** [comment]
No luck with disabling rebroadcast.  In back and forth with Discord support trying to get login fixed, which will hopefully happen soon.  Here are the console logs after opening the camera to try to stream:

[Front Yard] using address override 192.168.0.218
[Front Yard] Front Yard streaming request {
  sessionID: '609c35fd-325c-4aab-88e4-a9440a8a8b4e',
  type: 'start',
  video: {
    profile: 1,
    level: 2,
    packetizationMode: 0,
    cvoId: undefined,
    width: 1280,
    height: 720,
    fps: 30,
    pt: 99,
    ssrc: 2375509516,
    max_bit_rate: 299,
    rtcp_interval: 0.5,
    mtu: 1378
  },
  audio: {
    codec: 'AAC-eld',
    channel: 1,
    bit_rate: 0,
    sample_rate: 24,
    packet_time: 30,
    pt: 110,
    ssrc: 2666959580,
    max_bit_rate: 24,
    rtcp_interval: 5,
    comfort_pt: 13,
    comfortNoiseEnabled: false
  }
}
[Front Yard] Front Yard fetching video stream
[Front Yard] Front Yard [
  '-hide_banner',
  '-rtsp_transport',
  'tcp',
  '-analyzeduration',
  '15000000',
  '-probesize',
  '100000000',
  '-reorder_queue_size',
  '1024',
  '-max_delay',
  '20000000',
  '-i',
  'rtsp://192.168.0.1:7447/syTQ8UCaWWBJRY0E',
  '-f',
  'lavfi',
  '-i',
  'anullsrc=cl=1',
  '-shortest',
  '-an',
  '-sn',
  '-dn',
  '-vcodec',
  'copy',
  '-payload_type',
  '99',
  '-ssrc',
  '7455206',
  '-f',
  'rtp',
  '-srtp_out_suite',
  'AES_CM_128_HMAC_SHA1_80',
  '-srtp_out_params',
  'iHf7ZlAuL9xa3FAear0JRuGsyw67j/eMHa1ZPK90',
  'srtp://192.168.0.41:59797?rtcpport=59797&pkt_size=564',
  '-vn',
  '-sn',
  '-dn',
  '-acodec',
  'libfdk_aac',
  '-profile:a',
  'aac_eld',
  '-flags',
  '+global_header',
  '-ar',
  '24k',
  '-b:a',
  '24k',
  '-ac',
  '1',
  '-payload_type',
  '110',
  '-ssrc',
  '12235130',
  '-srtp_out_suite',
  'AES_CM_128_HMAC_SHA1_80',
  '-srtp_out_params',
  'visO9vsT8PYPecq24RZ7zURZJURybo/2OzZ8U7VN',
  '-f',
  'rtp',
  'srtp://192.168.0.41:54045?rtcpport=54045&pkt_size=188'
]
[Front Yard] /raspbian/usr/local/bin/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory

[Front Yard] ffmpeg exited
[Front Yard] Front Yard streaming request { sessionID: '609c35fd-325c-4aab-88e4-a9440a8a8b4e', type: 'stop' }
[Front Yard] streaming session killed

**Comment by hm0486** [comment]
I re-installed Scrypted and that may have fixed things.  Will check back in if needed, but wanted to make sure you don't spend any more time on me for now.  You've already dedicated more than my fair share!  Thank you!
