### ISSUE TITLE
Feature Request: Motion detection using video bitrate

### ISSUE THREAD

**Issue by guoye-zhang** [koush/scrypted#464]
Hi,

I have a few Nest cameras that work poorly with HKSV since it does not post events when streaming, and I don't think it's feasible to run CV models constantly on a raspberry pi. However, I've noticed that whenever there is motion recorded by the camera, the video bitrate goes up significantly due to compression. Is it possible to infer motion from a spike in video bitrate? My understanding is that HKSV will do further recognition work after receiving motion events so false positives aren't a huge problem.

Scrypted has been working great for me and I really enjoy using it, thanks for all your hard work!

**Comment by koush** [comment]
not reliable
