### ISSUE TITLE
video clip downloaded file name gets an unwanted ? suffix

### ISSUE THREAD

**Issue by lvnilesh** [koush/scrypted#466]
Video clip downloaded file name gets an unwanted `?` suffix.

See this https://github.com/koush/scrypted/commit/f3f370d5e064cb0d3824ee6f9cf59f7ceec6ec71

For example:

Link should be:
```
https://scrypted.local.domain.com/endpoint/11/public/9da7234069767a1a6f9e4b972804615c3cba480ee71f458d614d0c6caf400fbf.mp4
```
Not this:
```
https://scrypted.local.domain.com/endpoint/11/public/9da7234069767a1a6f9e4b972804615c3cba480ee71f458d614d0c6caf400fbf.mp4?
```

**Comment by koush** [comment]
that's the query string separator. it's a legal url, even if there is nothing after it.

**Comment by lvnilesh** [comment]
Yes the URL is legal but the downloaded file name is `file.mp4?` whereas it should be `file.mp4`

**Comment by koush** [comment]
what browser

**Comment by lvnilesh** [comment]
safari on m1 mac

**Comment by lvnilesh** [comment]
seems ok with firefox

**Comment by koush** [comment]
oh it seems it is adding an extra question mark. the search property includes it already.

**Comment by koush** [comment]
f1339877
