### ISSUE TITLE
Arlo plugin: choppy video on Homekit while smooth on webRTC plugin

### ISSUE THREAD

**Issue by sdugoten** [koush/scrypted#467]
Here is the follow up issue on Arlo plugin.

I made two video clip which should explain it itself.  The WebRTC plugin can show the live video capture smoother, while the homekit on phone will show the live video looks choppy.

Here is the WebRTC version

https://user-images.githubusercontent.com/7108552/207548572-a832ada6-e36a-42d5-8152-f73378a3a732.mp4

Here is the homekit on iphone version

https://user-images.githubusercontent.com/7108552/207548349-1017980d-abd7-419a-b05b-b7516092f105.mp4

You can see car pass by on the road in the front.  You can see car is like having very low FPS when moving

**Comment by koush** [comment]
need a log but I am almost certain this is a home app issue. The video sender code is exactly the same between the two now.

**Comment by sdugoten** [comment]
> need a log but I am almost certain this is a home app issue. The video sender code is exactly the same between the two now.

[log.txt](https://github.com/koush/scrypted/files/10228929/log.txt)

**Comment by koush** [comment]
can you also verify this happens when there isn't a homekit recording happening at the same time?

**Comment by sdugoten** [comment]
> can you also verify this happens when there isn't a homekit recording happening at the same time?

No homekit recording when i was doing it.  Basically, anytime when I click on the doorbell video provided by Scrypted, it will be as choppy as you see in the video above.  One thing interesting tho, the "Arlo version" of the doorbell video in homekit does stream smoothly (the one that no HKSV provided).

**Comment by koush** [comment]
I can see it recording in the log.

**Comment by sdugoten** [comment]
> I can see it recording in the log.


https://user-images.githubusercontent.com/7108552/207676898-8d05428b-ab3e-44be-b178-247f33d687dc.mp4


This is the actual timeline for the doorbell today.  It was down the whole night, and you saw  the video i made in the first post was on 8:19am today.  You saw the video I posted just now, there is zero HKSV recording in the timeline.

**Comment by koush** [comment]
understood, this means that hksv is rejecting the video. the doorbell was recording to hksv in the log, feel free to take a look.

try disabling HKSV on the camera, and then streaming to see if that resolves the issue. I have a suspicion what the problem may be.

**Comment by sdugoten** [comment]
> understood, this means that hksv is rejecting the video. the doorbell was recording to hksv in the log, feel free to take a look.
> 
> try disabling HKSV on the camera, and then streaming to see if that resolves the issue. I have a suspicion what the problem may be.

I changed to streaming only.

![aaa](https://user-images.githubusercontent.com/7108552/207873104-26873081-a96b-47a9-ac90-70638ebc5866.jpg)





Video still show it's choppy.



https://user-images.githubusercontent.com/7108552/207873161-43f00d0e-0aa0-4298-a870-03e993b1a855.mp4




here is the log




[log2.txt](https://github.com/koush/scrypted/files/10237406/log2.txt)

**Comment by koush** [comment]
bad bitrate or codec or timestamps is my guess. not well compatible with homekit.
