### ISSUE TITLE
Issue with password reset!

### ISSUE THREAD

**Issue by recoi1er** [koush/scrypted#469]
I forgot my login so I tried the command from the link below but Terminal (on my Mac that Scrypted is directly installed on) shows no output and refreshing the page does not prompt me to create a new admin account just asks me to login in again!

 https://github.com/koush/scrypted/wiki/Lost-Password-and-User-Reset

**Comment by recoi1er** [comment]
@koush wanted to follow up on this!

**Comment by NeilAtHome** [comment]
I have the same issue.   Is there another way to reset the password, other than reinstalling (which I don’t want to do)

**Comment by recoi1er** [comment]
> I have the same issue. Is there another way to reset the password, other than reinstalling (which I don’t want to do)

Same, I don't want to have to set everything up again!

**Comment by recoi1er** [comment]
> I have the same issue. Is there another way to reset the password, other than reinstalling (which I don’t want to do)

Run the reinstall command if you used the script - after it reinstalled everything I was able to sign back in with the credentials I had been using before and everything was still intact

**Comment by koush** [comment]
The instructions were incorrect. They have been updated:

`touch ~/.scrypted/volume/reset-login`
