### ISSUE TITLE
Error setting recording option

### ISSUE THREAD

**Issue by junior466** [koush/scrypted#47]
When I try to set the recording option for my second Amcrest camera, I receive an error `There was an error updating the setting for this camera, please try again later`.

The logs shows the following:

        Nov 14 02:46:28 VM_ npx[6023]: Service exited. Restarting momentarily.
        Nov 14 02:46:34 VM_ npx[6109]: Failed to listen on port 10081. It may be in use.
        Nov 14 02:46:34 VM_ npx[6109]: Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
        Nov 14 02:46:34 VM_ npx[6109]: Error: listen EADDRINUSE: address already in use :::10081
        Nov 14 02:46:34 VM_ npx[6109]:     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
        Nov 14 02:46:34 VM_ npx[6109]:     at listenInCluster (node:net:1382:12)
        Nov 14 02:46:34 VM_ npx[6109]:     at Server.listen (node:net:1469:7)
        Nov 14 02:46:34 VM_ npx[6109]:     at listenServerPort (/home/USER/.scrypted/node_modules/@scrypted/server/src/scrypted-main.ts:43:12)
        Nov 14 02:46:34 VM_ npx[6109]:     at Object.<anonymous> (/home/USER/.scrypted/node_modules/@scrypted/server/src/scrypted-main.ts:100:5)
        Nov 14 02:46:34 VM_ npx[6109]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
        Nov 14 02:46:34 VM_ npx[6109]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        Nov 14 02:46:34 VM_ npx[6109]:     at Module.load (node:internal/modules/cjs/loader:981:32)
        Nov 14 02:46:34 VM_ npx[6109]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        Nov 14 02:46:34 VM_ npx[6109]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        Nov 14 02:46:34 VM_ npx[4844]: Service exited. Restarting momentarily.

**Comment by koush** [comment]
screenshot of the error?

**Comment by koush** [comment]
it also looks like your server has a port conflict, so you may be running it twice. or you have something else using that port. in any case, follow the instructions and change that port.

**Comment by junior466** [comment]
Thanks for the prompt reply. I am running Home Assistant's Homekit integration but after a reboot of the machine running scrypted, everything is now working. 

Could there be any issues if running both?

**Comment by koush** [comment]
There could be, unsure.
