### ISSUE TITLE
Reolink cgi URLs for 4k NVR models switched from http to https

### ISSUE THREAD

**Issue by krc1504** [koush/scrypted#473]
The current Reolink plug-in URLs to fetch snapshot and motion detection state are based on the http endpoint which was switched to https in the most recent firmware update for the 4k NVRs. 

The http URLs redirect to the web client login page. The https URLs provide the expected functionality.

**Comment by koush** [comment]
I think this is fixed. can you check 88d4022642b95e6655a5b925417c3afaead5b48b
