### ISSUE TITLE
Dahua VTO doorbell one way audio rtsp auth error

### ISSUE THREAD

**Issue by papcio84** [koush/scrypted#480]
Hello everyone, 
I am an amateur when it comes to IT but I love scrypted. The issue I am trying to solve is related to one way audio I have on Dahua vto and amcrest plugin. I want to use this doorbell at HomeKit. Everything works well except two way audio. I hear what my guest is saying in front door but he does not what I am saying. Just checked logs and it seems it is the issue with tsp authentication... not sure what does exactly means. Look at the logs below:\

[HomeKit]: HomeKit Connection fe80::1c90:2d77:24f0:3b9a%eth0
[HomeKit]: destination address 192.168.1.142 51652 60796
[HomeKit]: ===========================================================================
[HomeKit]: The Scrypted Server Address is not set in the Scrypted settings.
[HomeKit]: If there are issues streaming, set this address to your wired IP address manually.
[HomeKit]: More information can be found in the HomeKit Plugin README.
[HomeKit]: ===========================================================================
[HomeKit]: source address undefined 49088 44534
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: 'e2930465-cb62-488b-ad4a-00610ebf1c87',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3707498806,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 945624398,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: { isLowBandwidth: false, isWatch: false, destination: 'local' }
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: rebroadcast mode: rtsp
stream url rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0", algorithm="MD5", response="199060a22168a07e3f207f08f7a2fcf4"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Server: Rtsp Server/3.0
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, TEARDOWN, SET_PARAMETER, GET_PARAMETER
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0", algorithm="MD5", response="13cadd9bc534403fb1133ab7e7a3bfa4"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: x-Accept-Dynamic-Rate: 1
[Rebroadcast Plugin]: Content-Base: rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0/
[Rebroadcast Plugin]: Cache-Control: must-revalidate
[Rebroadcast Plugin]: Content-Length: 491
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=- 2252007297 2252007297 IN IP4 0.0.0.0
[Rebroadcast Plugin]: s=Media Server
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: a=control:*
[Rebroadcast Plugin]: a=packetization-supported:DH
[Rebroadcast Plugin]: a=rtppayload-supported:DH
[Rebroadcast Plugin]: a=range:npt=now-
[Rebroadcast Plugin]: m=video 0 RTP/AVP 96
[Rebroadcast Plugin]: a=control:trackID=0
[Rebroadcast Plugin]: a=framerate:25.000000
[Rebroadcast Plugin]: a=rtpmap:96 H264/90000
[Rebroadcast Plugin]: a=fmtp:96 packetization-mode=1;profile-level-id=42801E;sprop-parameter-sets=Z0KAHtoDIPSVIAAAAwAgAAAGTAgAHz+AAKi/3vfC8IhGoAA=,aM48gAA=
[Rebroadcast Plugin]: a=recvonly
[Rebroadcast Plugin]: m=audio 0 RTP/AVP 97
[Rebroadcast Plugin]: a=control:trackID=1
[Rebroadcast Plugin]: a=rtpmap:97 L16/16000
[Rebroadcast Plugin]: a=recvonly
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0/trackID=0 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0/trackID=0", algorithm="MD5", response="c6e95d141db02ef36bc82345562d5341"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: Session: 69124714610;timeout=60
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=21594288
[Rebroadcast Plugin]: x-Dynamic-Rate: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0/trackID=1 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0/trackID=1", algorithm="MD5", response="1f23cd9cd122a17663d6585bbb1b7eb9"
[Rebroadcast Plugin]: Session: 69124714610
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: Session: 69124714610;timeout=60
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3;ssrc=0FFE8FD2
[Rebroadcast Plugin]: x-Dynamic-Rate: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: parsed sdp sps { width: 800, height: 480 }
[Rebroadcast Plugin]: No audio stream detected.
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  PLAY rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: CSeq: 5
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="dba02a73f8512c2bebdef0ae14729ca8", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0%2F&channel=1&subtype=0", algorithm="MD5", response="e04b32f91df69e873e7defbe65902961"
[Rebroadcast Plugin]: Session: 69124714610
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sending prebuffer 4000
[HomeKit]: { tool: 'scrypted', rtpSender: 'Default' }
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 5
[Rebroadcast Plugin]: Session: 69124714610
[Rebroadcast Plugin]: Range: npt=0.000000-
[Rebroadcast Plugin]: RTP-Info: url=trackID=0;seq=17032;rtptime=17032,url=trackID=1;seq=36818;rtptime=36818
[Rebroadcast Plugin]: 
[HomeKit]: packet loss 1
[HomeKit]: rtsp/tcp h264
[HomeKit]: a/v h264 opus found h264 undefined
[HomeKit]: rtsp/tcp undefined
[HomeKit]: -hide_banner -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 5244612 -dn -sn -vn -f rtp rtp://127.0.0.1:58297?pkt_size=400 -sdp_file pipe:4
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[Rebroadcast Plugin]: Unable to find sync frame in rtsp prebuffer.
[Rebroadcast Plugin]: parsed bitstream sps { width: 800, height: 480 }
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 28 1
[HomeKit]: [rtsp @ 0x2cea930] method SETUP failed: 461 Unsupported Transport
[HomeKit]: Guessed Channel Layout for Input Stream #0.0 : mono
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:36097':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Media Server
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: 256 kb/s
[HomeKit]:   Stream #0:0: Audio: pcm_s16be, 16000 Hz, mono, s16, 256 kb/s
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (pcm_s16be (native) -> opus (libopus))
[HomeKit]: Press [q] to stop, [?] for help
[HomeKit]: Output #0, rtp, to 'rtp://127.0.0.1:58297?pkt_size=400':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Media Server
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: received first audio packet
[HomeKit]: scanning for idr start found: 28 1 24 7 8
[HomeKit]: idr start found: 28 5
[HomeKit]: Received first two way audio packet, starting intercom.
rtsp outgoing message
 OPTIONS rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif RTSP/1.0
CSeq: 0
User-Agent: Scrypted

rtsp incoming message
 RTSP/1.0 401 Unauthorized
CSeq: 0
WWW-Authenticate: Digest realm="Login to 5L01792PAZ30821", nonce="3697a161b3511aac3fb67d082bbbaf70"

rtsp outgoing message
 OPTIONS rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif RTSP/1.0
CSeq: 1
User-Agent: Scrypted
Authorization: Digest username="admin", realm="Login to 5L01792PAZ30821", nonce="3697a161b3511aac3fb67d082bbbaf70", uri="rtsp://192.168.1.210:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif", algorithm="MD5", response="99bb8c9b3e11397a62d0a7aab4ce63fd"

rtsp incoming message
 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to 5L01792PAZ30821", nonce="3697a161b3511aac3fb67d082bbbaf70"

[HomeKit]: intercom failed to start host:@scrypted/homekit
[HomeKit]: @scrypted/amcrest:host
[HomeKit]: Error: auth failed
[HomeKit]:     at j.request (/common/src/rtsp-server.ts:622:23)
[HomeKit]:     at process.ret (node:internal/process/task_queues:95:5)
[HomeKit]:     at j.console (/common/src/rtsp-server.ts:637:15)
[HomeKit]:     at G.startIntercom (/onvif/src/onvif-intercom.ts:84:51)
[HomeKit]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:561:37) {
[HomeKit]:   cause: undefined
[HomeKit]: }

**Comment by koush** [comment]
you may need to enable onvif on that camera.
