### ISSUE TITLE
Feature Request: Add attention icon on plugin screen

### ISSUE THREAD

**Issue by nberardi** [koush/scrypted#484]
As a developer I need to be able to alert users that an issue has occurred with the plugin that requires their attention (e.g. auth issue), and requires them to manually fix the issue.  

I would like to see at attention icon on the dashboard for the plugin, and a non-dismissible attention alert on the plugin screen.

**Comment by koush** [comment]
you can use this to create alerts in the UI for a specific device:

```ts
this.log.a(...)
```

Is that what you need?
