### ISSUE TITLE
HKSV Local Copy - how to add storage?

### ISSUE THREAD

**Issue by nazgul6** [koush/scrypted#486]
Hi. 

I see an option to ‘Add storage’, which asks for a Storage Key and Storage Value, but can’t seem to figure out how to use those/what they refer too. What goes into those fields? Is there a way to connect to a local SMB share perhaps?

Thanks!

**Comment by koush** [comment]
That button doesn't do what you think it does. HKSV local copy feature is a debug tool, not intended for local backup.
