### ISSUE TITLE
Failed installation: npm ERR! cb.apply is not a function

### ISSUE THREAD

**Issue by paparapapapapa** [koush/scrypted#49]
Hi, as per title my installation fails, at first as normal user and then with sudo. I'm on Ubuntu 20.04.3, Intel NUC i5. You can find details about error, versions and log in the output below:

`~$ node -v
v16.13.0
~$ npx -v
10.2.2
~$ npx scrypted serve
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ric/.npm/_logs/2021-11-14T16_05_14_240Z-debug.log
Installazione di [ 'scrypted@latest' ] fallita con codice 1
~$ cat /home/ric/.npm/_logs/2021-11-14T16_05_14_240Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'scrypted@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/home/ric/.npm/_npx/6416',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v16.13.0
4 verbose npm-session 6bf03c581657a826
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/scrypted 1630ms
8 http fetch GET 200 https://registry.npmjs.org/scrypted/-/scrypted-1.0.30.tgz 1123ms
9 silly pacote tag manifest for scrypted@latest fetched in 2789ms
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /usr/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
10 verbose stack     at FSReqCallback.oncomplete (node:fs:199:5)
11 verbose cwd /home/ric
12 verbose Linux 5.11.0-40-generic
13 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "scrypted@latest" "--global" "--prefix" "/home/ric/.npm/_npx/6416" "--loglevel" "error" "--json"
14 verbose node v16.13.0
15 verbose npm  v5.1.0
16 error cb.apply is not a function
17 verbose exit [ 1, true ]
~$ sudo npx scrypted serve
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-14T16_07_33_344Z-debug.log
Installazione di [ 'scrypted@latest' ] fallita con codice 1`

I followed your instructions, I just skipped the node.js repository installation because I already have it installed and I update it via Homebridge.

Thank you.

**Comment by koush** [comment]
try 
`npx scrypted serve@latest`

**Comment by paparapapapapa** [comment]
Ok not sure why but it worked. Thank you!

**Comment by koush** [comment]
You were on an old version that was failing to load, and this forced and update.
