### ISSUE TITLE
Ring Video Doorbell Pro 2 - No Video on Preview and Google Nest Hub, HomeKit works

### ISSUE THREAD

**Issue by Juweii** [koush/scrypted#491]
Hi all,
I have successfully added my new Ring Doorbell Pro 2 to Scrypted and am able to stream it successfully using HomeKit.
Tried to show it on my Google Nest Hub but just getting a black screen. My OVIF camera works on the Nest Hub, so the overall configuration and connection to the Google Cloud seems to work.
Also on the Doorbell device in scrypted I am unable to get a video with the preview - just a snapshot.

Settings:

Doorbell (Doorbell from Ring Provider):
[X] HomeKit (default settings)
[X] Google Home
[X] WebRTC Plugin

Google Home:
[X] Doorbell (Ring)
[X] Camera2 (OVIF)

Nest Hub (Chromecast plugin):
[X] WebRTC Plugin

Preview on the Doorbell
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/5314938/210769968-938e3307-f861-4443-a896-134aaf8dd19e.png">

Any ideas what I can try to get it work?

The console logs are showing a lot of jsons (Nest Hub device) and streaming data (Ring Doorbell), no readable error found.

**Comment by koush** [comment]
join discord and ask there please. not going to handle troubleshooting here.

**Comment by bkarakashev** [comment]
hey, @Juweii  did you manage to sort this issue out? I am having the same problem.

**Comment by Juweii** [comment]
No, unfortunately it doesn't. Also the Ring is not very reliable in HomeKit, it seems to be a challenge to implement the camera in another system than the Ring app.
