### ISSUE TITLE
Camera (re)ordering in NVR

### ISSUE THREAD

**Issue by codekoala** [koush/scrypted#492]
Is it possible to change the arrangement of cameras in the grid of the NVR interface? It appears my cameras are listed in the order I added them to Scrypted. I would like to be able to arrange them differently so there's a more fluid way to visually track someone/something on camera.

**Comment by koush** [comment]
> Is it possible to change the arrangement of cameras in the grid of the NVR interface? It appears my cameras are listed in the order I added them to Scrypted. I would like to be able to arrange them differently so there's a more fluid way to visually track someone/something on camera.

Yes, you can already (the settings exist in the management console), it's not exposed in the NVR UI itself. but it's coming as soon I finish up some additional server work.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/73924/210838490-458183af-6cd2-416e-a393-7b0849f35875.png">

I also highly recommend joining the discord, there' a dedicated channel for nvr users.

**Comment by codekoala** [comment]
Awesome, thank you for the quick response! I will hop on Discord to ask further questions like this :)

**Comment by koush** [comment]
Not sure if you noticed, but ordering and hiding is in now.

**Comment by codekoala** [comment]
Excellent! Thank you for following up here! I just updated the things and was able to do exactly what I wanted to with the camera ordering. Works wonderfully! Nice work!
