### ISSUE TITLE
Grouped Devices of with a group type of doorbell not available for HomeKit.

### ISSUE THREAD

**Issue by jmnovak50** [koush/scrypted#496]
I'm trying to follow the [readme](https://github.com/koush/scrypted/wiki/Do-It-Yourself-Doorbell) and I am trying to group a simple mqtt switch to a grouped device of doorbell.  I am noticing that HomeKit seems to appear for selection if I pick camera.  I'm not sure if this is intended behavior or if I'm doing something wrong?  Im guessing the rationale for grouping the switches/sensors so that, as doorbell they are tethered to the same device as one can do with a dummy switch?  Any help you can provide would be great!  Thank you!

**Comment by koush** [comment]
Need a BinarySensor, not a switch. Use Discussions or Discord for support please.
