### ISSUE TITLE
Unifi G5 Flex / recordings & detections not showing up in HKSV

### ISSUE THREAD

**Issue by bondskin** [koush/scrypted#497]
With my new G5 Flex (wired) I see motion and detection in Protect.

Events in scrypted are showing:

10:37:12 | e | unhandledRejection dataSend close
-- | -- | --
10:37:03 | e | uncaughtException Error: write EPIPE
10:33:25 | e | unhandledRejection dataSend close
10:33:24 | e | uncaughtException Error: write EPIPE
10:27:32 | e | unhandledRejection dataSend close
10:27:31 | e | uncaughtException Error: write EPIPE

**Comment by koush** [comment]
Github is not a support forum

**Comment by bondskin** [comment]
Dear @koush ,

Yes, sorry if my intention was misunderstood.
I noticed a different behaviour of G5 Flex vs G3 Instant using Scrypted und Unifi Protect with same settings etc
My intention was to highlight this observation.

best regards
Mike
