### ISSUE TITLE
Feature Request: 2-way audio through third party speaker

### ISSUE THREAD

**Issue by victor-vz** [koush/scrypted#499]
Scrypted worked like a charm so far. I especially love the option to connect old doorbells with RTSP cameras. As RTSP is only a video stream, I was wondering if it would be possible to connect a Wifi speaker to imitate native 2-way audio.

**Comment by koush** [comment]
This a hardware plugin request and I'm not accepting those as issues. Yes, it's possible, but you'll need to find someone to do it for the specific hardware you are talking about.
