### ISSUE TITLE
OpenCV causes huge syslog volume when used with Unifi-protect

### ISSUE THREAD

**Issue by bondskin** [koush/scrypted#504]
I have 1k log events per minute when I enable OpenCV (0.0.60) on my Scrypted (0.5.11) combined with Unifi-Protect (0.0.125)

Excerpt from syslog:

> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcPeer.handleMessageInternal (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:564:37) {
> Jan  8 12:33:17 raspberrypi npx[696]:   cause: undefined
> Jan  8 12:33:17 raspberrypi npx[696]: }
> Jan  8 12:33:17 raspberrypi npx[696]: unhandled rejection of RPC Result RPCResultError: api/@scrypted/core:engine.io: RpcPeer has been killed
> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcProxy.apply (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:135:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Proxy.<anonymous> (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:259:29)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.emit (node:events:525:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.log (/home/pi/.scrypted/node_modules/@scrypted/server/src/logger.ts:45:14)
> Jan  8 12:33:17 raspberrypi npx[696]:     at ScryptedStateManager.setPluginDeviceStateFromMixin (/home/pi/.scrypted/node_modules/@scrypted/server/src/state.ts:88:57)
> Jan  8 12:33:17 raspberrypi npx[696]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> Jan  8 12:33:17 raspberrypi npx[696]:     at PluginHostAPI.setState (/home/pi/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host-api.ts:113:9)
> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcPeer.handleMessageInternal (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:564:37) {
> Jan  8 12:33:17 raspberrypi npx[696]:   cause: undefined
> Jan  8 12:33:17 raspberrypi npx[696]: }
> Jan  8 12:33:17 raspberrypi npx[696]: unhandled rejection of RPC Result RPCResultError: api/@scrypted/core:engine.io: RpcPeer has been killed
> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcProxy.apply (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:135:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Proxy.<anonymous> (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:259:29)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.emit (node:events:525:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.log (/home/pi/.scrypted/node_modules/@scrypted/server/src/logger.ts:45:14)
> Jan  8 12:33:17 raspberrypi npx[696]:     at ScryptedStateManager.setPluginDeviceStateFromMixin (/home/pi/.scrypted/node_modules/@scrypted/server/src/state.ts:88:57)
> Jan  8 12:33:17 raspberrypi npx[696]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> Jan  8 12:33:17 raspberrypi npx[696]:     at PluginHostAPI.setState (/home/pi/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host-api.ts:113:9)
> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcPeer.handleMessageInternal (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:564:37) {
> Jan  8 12:33:17 raspberrypi npx[696]:   cause: undefined
> Jan  8 12:33:17 raspberrypi npx[696]: }
> Jan  8 12:33:17 raspberrypi npx[696]: unhandled rejection of RPC Result RPCResultError: api/@scrypted/core:engine.io: RpcPeer has been killed
> Jan  8 12:33:17 raspberrypi npx[696]:     at RpcProxy.apply (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:135:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Proxy.<anonymous> (/home/pi/.scrypted/node_modules/@scrypted/server/src/rpc.ts:259:29)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.emit (node:events:525:35)
> Jan  8 12:33:17 raspberrypi npx[696]:     at Logger.log (/home/pi/.scrypted/node_modules/@scrypted/server/src/logger.ts:45:14)
> Jan  8 12:33:17 raspberrypi npx[696]:     at ScryptedStateManager.setPluginDeviceStateFromMixin (/home/pi/.scrypted/node_modules/@scrypted/server/src/state.ts:88:57)
> Jan  8 12:33:17 raspberrypi npx[696]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 

Happy to share further details, if needed

**Comment by koush** [comment]
I think this is a dangling browser session or something. Does it go away if you close your browser windows?

**Comment by bondskin** [comment]
Hmmm. I don't think so. 
The scrypted instance runs on a Raspberry and the syslog was generated from there. 
I'll restart the Pi and watch if this helps

**Comment by bondskin** [comment]
Hi @koush ,

I have restarted scrypted and it calmed down the log events.
However, when motion is being detected, I see the following messages.
If this is just white noise, it's fine for me.

> Jan  9 09:57:56 raspberrypi npx[696]: [WatchGuard] rebroadcast error Error: rtsp read loop exited
> Jan  9 09:57:56 raspberrypi npx[696]:     at Object.T [as start] (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145113)
> Jan  9 09:57:56 raspberrypi npx[696]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> Jan  9 09:57:56 raspberrypi npx[696]: i WatchGuard online: false
> Jan  9 09:57:56 raspberrypi npx[696]: [WatchGuard] restarting prebuffer session in 5 seconds
> 

> Jan  9 09:59:44 raspberrypi npx[696]: [WatchGuard]
> Jan  9 09:59:44 raspberrypi npx[696]: [WatchGuard] parsed bitstream sps { width: 1920, height: 1080 }
> Jan  9 09:59:44 raspberrypi npx[696]: [Heimdall] motion fragment #9 sent. size: 162613
> Jan  9 09:59:44 raspberrypi npx[696]: update packet { isMotionDetected: false, motionDetectedAt: 1673254784218 }
> Jan  9 09:59:44 raspberrypi npx[696]: i Sentinel motionDetected: false
> Jan  9 09:59:45 raspberrypi npx[696]: unhandledRejection i [Error]
> Jan  9 09:59:45 raspberrypi npx[696]:     at Socket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:80054)
> Jan  9 09:59:45 raspberrypi npx[696]:     at Socket.emit (node:events:525:35)
> Jan  9 09:59:45 raspberrypi npx[696]:     at Socket.emit (node:domain:489:12)
> Jan  9 09:59:45 raspberrypi npx[696]:     at endReadableNT (node:internal/streams/readable:1359:12)
> Jan  9 09:59:45 raspberrypi npx[696]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Jan  9 09:59:45 raspberrypi npx[696]: [WatchGuard] Low active rebroadcast clients: 0
> Jan  9 09:59:46 raspberrypi npx[696]: [Heimdall] motion fragment #10 sent. size: 878290
> Jan  9 09:59:46 raspberrypi npx[696]: unhandledRejection dataSend close
> Jan  9 09:59:46 raspberrypi npx[696]: e HomeKit unhandledRejection dataSend close
> Jan  9 09:59:46 raspberrypi npx[696]: [Heimdall] motion fragment #11 sent. size: 120188
> Jan  9 09:59:46 raspberrypi npx[696]: i Heimdall motionDetected: false (mixin)
> Jan  9 09:59:46 raspberrypi npx[696]: [Heimdall] built in motion sensor ended motion, stopping video detection.
> Jan  9 09:59:46 raspberrypi npx[696]: i Heimdall motionDetected: false
> Jan  9 09:59:46 raspberrypi npx[696]: detection ended @scrypted/opencv-13
> Jan  9 09:59:46 raspberrypi npx[696]: detection ended @scrypted/opencv-13
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] motion fragment #12 sent. size: 160836
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] motion recording completed dataSend close
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] %s: %s mp4 recording 9.320s
> Jan  9 09:59:47 raspberrypi npx[696]: unhandledRejection i [Error]
> Jan  9 09:59:47 raspberrypi npx[696]:     at Socket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:80054)
> Jan  9 09:59:47 raspberrypi npx[696]:     at Socket.emit (node:events:525:35)
> Jan  9 09:59:47 raspberrypi npx[696]:     at Socket.emit (node:domain:489:12)
> Jan  9 09:59:47 raspberrypi npx[696]:     at endReadableNT (node:internal/streams/readable:1359:12)
> Jan  9 09:59:47 raspberrypi npx[696]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] Low active rebroadcast clients: 0
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] High active rebroadcast clients: 0
> Jan  9 09:59:47 raspberrypi npx[696]: [Heimdall] ffmpeg exited
> 

> Jan  9 10:00:01 raspberrypi npx[696]: [WatchGuard] motion fragment #16 sent. size: 345105
> Jan  9 10:00:01 raspberrypi npx[696]: i WatchGuard motionDetected: false (mixin)
> Jan  9 10:00:01 raspberrypi npx[696]: i Heimdall motionDetected: false (mixin)
> Jan  9 10:00:01 raspberrypi telegraf: latest file contains: 28486274 value
> Jan  9 10:00:01 raspberrypi npx[696]: i Watchdog motionDetected: false (mixin)
> Jan  9 10:00:01 raspberrypi npx[696]: i Heimdall motionDetected: false (mixin)
> Jan  9 10:00:01 raspberrypi npx[696]: i WatchGuard motionDetected: false (mixin)
> Jan  9 10:00:03 raspberrypi npx[696]: unhandledRejection Error: timeout waiting for client
> Jan  9 10:00:03 raspberrypi npx[696]:     at Timeout._onTimeout (/@scrypted/prebuffer-mixin/main.nodejs.js:1:154624)
> Jan  9 10:00:03 raspberrypi npx[696]:     at listOnTimeout (node:internal/timers:564:17)
> Jan  9 10:00:03 raspberrypi npx[696]:     at process.processTimers (node:internal/timers:507:7)
> Jan  9 10:00:03 raspberrypi npx[696]: unhandledRejection Error: timeout waiting for client
> Jan  9 10:00:03 raspberrypi npx[696]:     at Timeout._onTimeout (/@scrypted/prebuffer-mixin/main.nodejs.js:1:154624)
> Jan  9 10:00:03 raspberrypi npx[696]:     at listOnTimeout (node:internal/timers:564:17)
> Jan  9 10:00:03 raspberrypi npx[696]:     at process.processTimers (node:internal/timers:507:7)
> Jan  9 10:00:05 raspberrypi npx[696]: [WatchGuard] motion fragment #17 sent. size: 1042462
> Jan  9 10:00:05 raspberrypi npx[696]: [WatchGuard] motion recording completed dataSend close
> Jan  9 10:00:05 raspberrypi npx[696]: [WatchGuard] %s: %s mp4 recording 14.609s
> Jan  9 10:00:05 raspberrypi npx[696]: [WatchGuard] High active rebroadcast clients: 0
> Jan  9 10:00:05 raspberrypi npx[696]: [WatchGuard] ffmpeg exited
> Jan  9 10:00:07 raspberrypi npx[696]: unhandledRejection Error: timeout waiting for client
> Jan  9 10:00:07 raspberrypi npx[696]:     at Timeout._onTimeout (/@scrypted/prebuffer-mixin/main.nodejs.js:1:154624)
> Jan  9 10:00:07 raspberrypi npx[696]:     at listOnTimeout (node:internal/timers:564:17)
> Jan  9 10:00:07 raspberrypi npx[696]:     at process.processTimers (node:internal/timers:507:7)
> Jan  9 10:00:07 raspberrypi npx[696]: unhandledRejection Error: timeout waiting for client
> Jan  9 10:00:07 raspberrypi npx[696]:     at Timeout._onTimeout (/@scrypted/prebuffer-mixin/main.nodejs.js:1:154624)
> Jan  9 10:00:07 raspberrypi npx[696]:     at listOnTimeout (node:internal/timers:564:17)
> Jan  9 10:00:07 raspberrypi npx[696]:     at process.processTimers (node:internal/timers:507:7)
> Jan  9 10:00:10 raspberrypi npx[696]: update packet { bluetoothConnectionState: { signalQuality: 5, signalStrength: -88 } }
> Jan  9 10:00:10 raspberrypi npx[696]: i Watchdog motionDetected: false (mixin)
> Jan  9 10:00:11 raspberrypi npx[696]: i Heimdall motionDetected: false (mixin)
> Jan  9 10:00:11 raspberrypi npx[696]: i WatchGuard motionDetected: false (mixin)
> Jan  9 10:00:11 raspberrypi npx[696]: i Watchdog motionDetected: false (mixin)
> Jan  9 10:00:11 raspberrypi npx[696]: i WatchGuard motionDetected: false (mixin)
> Jan  9 10:00:11 raspberrypi npx[696]: i Heimdall motionDetected: false (mixin)

**Comment by koush** [comment]
I don't think that's an actual error, but I'll see if I can make opencv shut down more gracefully.

**Comment by koush** [comment]
opencv no longer manages video, bug is defunct.
