### ISSUE TITLE
Homekit plugin console log bug %s: %s mp4 recording

### ISSUE THREAD

**Issue by longzheng** [koush/scrypted#506]
I noticed a lot of these messages in the Homekit plugin console

```
[Front door] %s: %s mp4 recording 11.210s
[Front] %s: %s mp4 recording 14.278s
[Backyard] %s: %s mp4 recording 8.141s
```

The `%s` seems like a string replacement bug.

I found where this console message is being emitted from, it's the `console.time` in 

https://github.com/koush/scrypted/blob/a85ac600ebf4cdde4ea57af7078e7afe4557a8aa/plugins/homekit/src/types/camera/camera-recording.ts#L280

https://github.com/koush/scrypted/blob/a85ac600ebf4cdde4ea57af7078e7afe4557a8aa/plugins/homekit/src/types/camera/camera-recording.ts#L342

 but I didn't follow how the console prefix stuff works, I presume the bug is in there and how it works with `console.timeEnd`.

**Comment by koush** [comment]
removed that log
