### ISSUE TITLE
RTSP video stopped working overnight

### ISSUE THREAD

**Issue by paparapapapapa** [koush/scrypted#51]
Hi Koush, after the problems I outlined, last evening I decided to simply stop troubleshooting and to setup it all over again, removing all the images, containers, volumes and compose data.

Well, it didn't work at first. Like I said, just thumbnail update Avery like 10 seconds but no streaming at all (only in Scrypted itself). No error shoot at the console. I tried to re-enable IGMP snooping and mDNS broadcasting on my UDM, but this just made all of my HK stuff unreachable, so I turned them back off.

Then I put one more time the host IP address (v4) in the HomeKit plugin/Network mask like you said and restart just the plugin and it suddenly was working very well, both live and recordings streaming.

This morning without touching it is not working again, neither live nor recordings streaming.

Please let me know what info you need to troubleshoot. Thank you

**Comment by koush** [comment]
Does it work if you restart?

**Comment by paparapapapapa** [comment]
No, not even rebooting the host

**Comment by koush** [comment]
What kind of camera? Can you disable audio in scrypted camera's settings? Then reload the rebroadcast plugin.

**Comment by paparapapapapa** [comment]
Reolink RLC-410. 

Done, no luck doing that. 

I noticed key frame interval is set to 1.933, seems a lil odd…

**Comment by koush** [comment]
Think this is fixed. Handling stream termination and restarts now.
