### ISSUE TITLE
chromecast-view-camera.ts doesn't work

### ISSUE THREAD

**Issue by paulirish** [koush/scrypted#511]
(This isn't an urgent bug for me. TBH I may not reattempt for a few more months. I just wanted to report that I found what I believe are bugs.. :)

-------

I spent some time last weekend getting scrypted up and running. Really enjoyed it and also enjoyed exploring the codebase. really nice work.

My primary motivation for looking into scrypted is exactly [the `chromecast-view-camera` usecase](https://github.com/koush/scrypted/blob/main/plugins/core/fs/examples/chromecast-view-camera.ts), and tbh it was a total surprise to find the example code after i'd been tinkering for 45min. But I was very excited that this might be more straightforward than I'd assumed.

My (relevant) setup:
- 2 amcrest cameras
- synology survelliance station
- a chromecast

I don't have my full repro up right now.. so mostly capturing this from memory... 

Heres the general sequence of my experience: 

1. Got scrypted installed in docker on the synology nas
2. connected it to syn surv station + google home, which found all relevant devices
3. camera feeds look good. chromecast interaction probably worked.
4. find the chromecast-view-camera.ts copy it in. set the device names. console log to ensure the devices were correctly found.
5. But the chromecast doesnt respond
6. get scrypted installed/setup on my mac so I can debug it. (Wow I still don't totally understand what you did with managing the inspector protocol for all child processes, but ... really fascinating stuff :)
7. ended up changing a `NodeForkWorker` invocation to use `NodeThreadWorker` so I could breakpoint
8. **Bug 1.** saw I was getting a `no converter found` error.  it was from `x-local-uri` to `x-uri`.
9. I did see some things that suggested this might be autohandled, but I added this converter to plugin/media.ts just to be safe:

```ts
        this.builtinConverters.push({
            id: getBuiltinId(this.builtinConverters.length),
            name: 'Url-like to URL Converter',
            fromMimeType: ScryptedMimeTypes.LocalUrl, // x-local-uri .. // i kinda think this could be 'text/x*-uri maybe?
            toMimeType: ScryptedMimeTypes.Url, // x-uri
            async convert(data: Buffer, fromMimeType: string): Promise<Buffer> {
                return data;
            }
        });
```

10. That resolved the `no converter found` exception. 
11. **Bug 2**: once the chromecast plugin is invoked [we craft a url within `loadRTCSession()`](https://github.com/koush/scrypted/blob/f51ce5c7e9345920c3e59fe8e293c0ea1faffeed/plugins/chromecast/src/main.ts#L202). This URL didn't successfully load for me, when just using a browser. 
   - It was something like http://192.168.86.4:11080/endpoint/@scrypted/core/public/#/device/20 (Though i'm not sure.. I tried a few variations and lost the original)
   - When loading in a browser i got an error like "no endpoint available" or.. something. (Lost the exact string, sorry.) I got the sense it was from engineio and while this was a valid route, it couldn't successfully construct a response.
12. I got curious about what sort of media types the chromecast can successfully cast. I couldn't tell if this `loadRTCSession()` generated URL was a text/html page or some rtsp thing.
13. I debugged within the `castv2-client` module to see what it was sending to the cast target. (no surprise, It's just like how chromecast/main spells it out..): 

<img width="811" alt="image" src="https://user-images.githubusercontent.com/39191/212395595-68b7aa3f-d828-43de-91b6-05b66129e153.png">

14. I cloned `castv2-client` and made this little example to replicate the call on its own. 
15. **Bug 3**:  this media payload always ends up with LOAD_FAILED. (Whereas that [repo's bigbuckbunny example](https://github.com/thibauts/node-castv2-client/blob/master/examples/basic.js) works great for me). 
   - (I just now tried with a `contentId: 'http://example.com'` to see if any webpage cast will work, got the same LOAD_FAILED.)
   - I went into chromecast docs to see what contentTypes they accept and didn't find too much. My presumption is that the cast target don't recognize [the `text/x-local-uri` contentType](https://github.com/koush/scrypted/blob/f51ce5c7e9345920c3e59fe8e293c0ea1faffeed/plugins/chromecast/src/main.ts#L208), but.. I don't know for sure.
   - Also after a while of this casting trial-and-error my device (Chromecast w/ google tv) seemed to stop reacting. (I'm presuming some temporal abuse prevention kicked in, but who knows.)
16. That's about it!

FWIW, When I pick this up again I might dig into https://github.com/my-ugly-code/PiPupTransparent to get the camera feed on the TV. That'll skip dealing with chromecast, but .. surely will have its own challenges. In that setup though, I'd plan on using scrypted to provide a webpage with the camera feed or use the rtsp re-broadcast somehow. 

Anyway, I hope this report is useful! Cheers.

**Comment by koush** [comment]
Will answer these in separate comment as I roll through the feedback:

**Comment by koush** [comment]
> * get scrypted installed/setup on my mac so I can debug it. (Wow I still don't totally understand what you did with managing the inspector protocol for all child processes, but ... really fascinating stuff :)

You shouldn't need to ever debug the server, if that's how you attempted it. You can run/debug a plugin within an already running server. But yes, there's some stuff happening under the hood to manage plugins as workers and remote worker debugging. You don't need to restart the server to install/debug a new plugin.

**Comment by koush** [comment]
> * **Bug 1.** saw I was getting a `no converter found` error.  it was from `x-local-uri` to `x-uri`.

@paulirish Ah! That's the issue. Sorry, I need to make that a less confusing user facing error. Basically, Chromecast will NOT load insecure or self signed urls. So the Scrypted Cloud plugin is necessary to initiate the webrtc signaling session as well as proxy media that is sent to the Chromecast.

I'm fairly sure if you install the cloud plugin, you will be good to go.

**Comment by koush** [comment]
Fixed with 2efe46a8

**Comment by koush** [comment]
Confirmed issue was occurring with "no convertor". Alert is now shown.
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/73924/212416271-eecbcc61-7a39-482c-8fcb-c0067098a6b2.png">

**Comment by koush** [comment]
> In that setup though, I'd plan on using scrypted to provide a webpage with the camera feed or use the rtsp re-broadcast somehow.

https://demo.scrypted.app/#/demo

**Comment by koush** [comment]
e86569bc
