### ISSUE TITLE
Enhancement: package occupancy sensor on 2nd camera (g4 doorbell pro

### ISSUE THREAD

**Issue by sundar2012** [koush/scrypted#512]
Scrypted exposes both cameras within the Unifi g4 doorbell pro (main and downward facing package camera).  In HKSV, both cameras have full detection capabilities.  However, the occupancy sensor options within scrypted are only available for the main camera.  I’m requesting an enhancement to enable a package detection occupancy sensor for the package camera.  Thanks!

**Comment by sundar2012** [comment]
Note that this request probably requires issue #514 to be addressed first.

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/514
