### ISSUE TITLE
Amcrest camera not streaming when off local network

### ISSUE THREAD

**Issue by dmcguire29** [koush/scrypted#516]
Hi there,

I believe I have a set-up problem rather than a technical problem with the system. I have been using my Amcrest cameras direct on home bridge with the rtsp plug-in and all was working ok. I changed recently to Scrypted and much prefer the response when on my home wifi. All is working great (well 2 way Audio issue with doorbell to fix). My main issue is that I can't get any of the 3 Amcrest camera that I have to open when off my local network. I have tried multiple ways to resolve but can't seem to figure it out. I don't believe it is an issue with the native camera feed because it worked fine on homebridge / rtsp. Any tips or guidance on how I should configure this?

Thanks,
David

**Comment by koush** [comment]
You likely have your substream disabled. Join Discord for community support. This is a bug tracker.
