### ISSUE TITLE
Reolink  RLC 520 doesn't work with Reolink Plugin

### ISSUE THREAD

**Issue by GPL71** [koush/scrypted#518]
Just installed scrypted on raspberry (new SD hombridge and Docker + Scrypted)
Installed Reolink plugin and setted.
Installed Homekit plugin too
Camera model is RLC 520
Streaming is reachable by local IPcamera, and before of Scrypted RLC 520 was working with camera.ui like a charm.

Now camera frame in scrypted is black. 
All test to try set camera failed
Then I installed rtsp plugin and setted same string of camera.ui and now frame in scrypted is on and stream like a charm.

Why I'm not able use the Reolink plugin?
Could suggest me further tests?
Thank you

**Comment by koush** [comment]
enable and use Onvif. also search the discord. it is a known working camera.
