### ISSUE TITLE
onvif plugin: rtsp-client: PLAY and TEARDOWN requests shall contain "Require" field in case of backchannel audio

### ISSUE THREAD

**Issue by nanosonde** [koush/scrypted#520]
Hi!

According to the ONVIF backchannel example flows given here:
https://www.happytimesoft.com/knowledge/audio-back-channel.html

The`Require: www.onvif.org/ver20/backchannel` must always be included in the header field for all requests related to backchannel audio: DESCRIBE, SETUP, PLAY, TEARDOWN

See also: http://www.onvif.org/wp-content/uploads/2019/07/ONVIF_Audio_Backchannel_Client_Test_Specification_19.06.pdf
See chapter 5.4 step 7.

**Comment by koush** [comment]
Thanks, you experiencing a bug?

**Comment by nanosonde** [comment]
No, I did not experience a bug. I had just discovered this while experimenting with my new "SIPcam to ONVIF gateway" docker.

**Comment by nanosonde** [comment]
Thanks, the "Require" header is now there.
