### ISSUE TITLE
Snapshot distorted

### ISSUE THREAD

**Issue by Epic-F** [koush/scrypted#526]
Snapshot is distorted in both HomeKit and Scrypted web ui. Same problem when using the main and sub stream (prebufferd and non prebuffer). 
When I change a setting in the ONVIF plugin or start streaming the snapshot is back to normal again.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/4472243/213866435-2ce5562c-c965-4683-ba7f-f4f2c4276e36.png">

Camera's: Reolink 2 x E1 Pro, RCL-420 and RCL-520A (both wired and wifi). 

<img width="709" alt="Scherm­afbeelding 2023-01-21 om 13 02 34" src="https://user-images.githubusercontent.com/4472243/213866178-48f0e191-323f-4d40-84b7-6ad3b54976d5.png">

**Comment by koush** [comment]
camera bug.

**Comment by Epic-F** [comment]
It's not a camera bug. They work fine with any other NVR software.
