### ISSUE TITLE
Cloud plugin authentication

### ISSUE THREAD

**Issue by daniel-lo** [koush/scrypted#529]
Newbie alert!

I chose email authentication, use the confirmation link then it tries to conenct to server ...

"Setup Incomplete
Scrypted Cloud has not been set up for this email address. Install the Cloud plugin on the Scrypted Server and log in. "

Tried it a couple of times .. don't understand why I don't succeed.

**Comment by koush** [comment]
You need to log into the plugin. There's a login button in the plugin itself.

**Comment by daniel-lo** [comment]
@koush

This is exactly what I am complaining about .. I cannot authenticate in the plugin. Tried again ..

"Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)."

BTW .. GoogleAuth didn't work either.

**Comment by daniel-lo** [comment]
Seems to log-in now .. but should I see anything than a blank page when I do so?

https://home.scrypted.app/endpoint/@scrypted/core/public/

Hourglass in menu bar stopps after some time but page remains blank.

@koush

**Comment by koush** [comment]
screenshot?

**Comment by daniel-lo** [comment]
![1](https://user-images.githubusercontent.com/4311558/215312787-ee1dce84-35f5-4670-9ccf-9faa5c5236a0.png)
![2](https://user-images.githubusercontent.com/4311558/215312796-dc417f46-90d2-45bc-929d-d0eda2ce1af5.png)
![3](https://user-images.githubusercontent.com/4311558/215312797-44e821cc-5dbe-4a5d-86a3-401536d6b09d.png)
![4](https://user-images.githubusercontent.com/4311558/215312801-fc94c01a-1aa6-461d-b328-ce35991230b9.png)

Another try
![5](https://user-images.githubusercontent.com/4311558/215312809-c30b21c6-15c2-467e-8425-2232152add27.png)

**Comment by daniel-lo** [comment]
Alexa skill also cannot connect
