### ISSUE TITLE
Homekit Secure Video very short recordings

### ISSUE THREAD

**Issue by fade2metal** [koush/scrypted#53]
Hey koush,

is the recording length of the homekit secure video adjustable?
My other cameras that work directly with homekit are recording much longer videos (10-15sec) than the ones that are running with scrypted(5sec).

Is that length adjustable through your very great project or is that fixed in homekit itself?

**Comment by koush** [comment]
No, it's not. Make are you set your codec settings correctly in your camera's admin page. More information can be found in HomeKit Transcoding tab on the camera on what to set it to. That may be the issue.

**Comment by koush** [comment]
key frame interval needs to be 4 seconds. that's probably the issue.
