### ISSUE TITLE
Connection issues after install

### ISSUE THREAD

**Issue by BarberEngineering** [koush/scrypted#532]
Ran the script that installed docker on a fresh install of Fedora 37; Trying to connect to anything I've found fails

- https://localhost:10443
- https://ip:10443
- https://docker inside ip:11080

Things I've tried
- reboot
- rerun the script (skipping docker install version)
- in the .scrypted folder running docker-compose start or up

Only output is:

docker-compose start
Starting scrypted   ... done
Starting watchtower ... done

**Comment by koush** [comment]
check your docker output

**Comment by BarberEngineering** [comment]
docker logs? 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service setup: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service setup successfully started
s6-rc: info: service dbus: starting
s6-rc: info: service dbus successfully started
s6-rc: info: service avahi: starting
Starting dbus...
s6-rc: info: service avahi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#######################################################
Scrypted Volume           : /server/volume
Scrypted Server (Local)   : https://localhost:10443/

**Comment by BarberEngineering** [comment]
Guessing it has something to do with Fedora. Installed Ubuntu Jammy Jellyfish and everything worked as expected.

thanks for taking the time to respond and awesome work!
