### ISSUE TITLE
Ciao mDNS entries for HomeKit plugin disappear after 2 minutes

### ISSUE THREAD

**Issue by jeffjumper** [koush/scrypted#534]
I'm publishing 3 Ring floodlight cams and a Ring doorbell camera to HomeKit using ciao. I can pair/unpair/re-pair and view the cameras correctly with the Apple Home app on my phone so I know they're set up correctly and running. Using the Discovery app on my (Mac) laptop, I can see the following information is being published (this is for the Doorbell...the other 3 cams are similar):

<img width="324" alt="CiaoDoorbell" src="https://user-images.githubusercontent.com/47900427/214999197-09e4faf1-7eda-4f82-85e1-2d9862c2b0d3.png">

Everything works great...but only for 2 minutes. After that, all the mDNS entries disappear from the Discovery app and the Apple Home app can no longer connect to the cameras. It looks like ciao is crashing, maybe? But I don't see any errors about it in the Homekit plugin console. The docker container logs have a lot of errors but I can't tell if it's anything relevant.

[scrypted-homekit-plugin.log](https://github.com/koush/scrypted/files/10515067/scrypted-homekit-plugin.log)
[scrypted-container.log](https://github.com/koush/scrypted/files/10515096/scrypted-container.log)

If I reload the HomeKit plugin, the mDNS entries appear again and everything works for another 2 minutes before stopping.

The problem existed yesterday on the older versions of everything. I just updated the server and all the plugins to the latest versions but the problem remains.
<img width="563" alt="Screenshot 2023-01-26 at 9 50 06 PM" src="https://user-images.githubusercontent.com/47900427/214999820-c57145f3-df43-44fb-9936-ceaafeef5b59.png">

Let me know if I can provide you any more info.

**Comment by koush** [comment]
What's your server/install?
I'd try bonjour-hap instead.

**Comment by jeffjumper** [comment]
I've seen the same behavior on 2 different systems here. 1) an 8GB Pi4 running Ubuntu 22.04 LTS and 2) a Synology NAS. Both containers were set up using host networking and the volume info from your sample docker-compose file.

On the ubuntu pi I have avahi/dbus configured because I'm also running a homebridge instance that's configured for avahi and that works fine. So initially I tried to set Scrypted to use avahi but got these errors in the homekit plugin log:

```
unhandledRejection TypeError: Cannot read properties of undefined (reading 'httpServer')
    at logConnections (/src/hap-utils.ts:160:57)
    at YD.start (/src/main.ts:308:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[${this.displayName}] Selected "avahi" advertiser though it isn't available on the platform. Reverting to "bonjour-hap"
[${this.displayName}] Selected "avahi" advertiser though it isn't available on the platform. Reverting to "bonjour-hap"
[${this.displayName}] Selected "avahi" advertiser though it isn't available on the platform. Reverting to "bonjour-hap"
[${this.displayName}] Selected "avahi" advertiser though it isn't available on the platform. Reverting to "bonjour-hap"
[${this.displayName}] Selected "avahi" advertiser though it isn't available on the platform. Reverting to "bonjour-hap"

```

(btw, for testing the ciao problem I actually stopped avahi and the homebridge container on the ubuntu pi just to make sure it wasn't interfering.)

So with neither ciao nor avahi working, I did try bonjour-hap. That is mostly working except that I have a similar problem to what was reported here: https://github.com/koush/scrypted/issues/429

The mDNS records look like this:
<img width="399" alt="BonjourHAPDoorbell" src="https://user-images.githubusercontent.com/47900427/215101415-5c271abe-f4c2-4c93-900a-04be33b9b83a.png">

While Apple's Home app is able to figure out how to ignore those 172.x.x.x addresses, for some reason Home Assistant's HomeKit Controller integration gets stuck on them and refuses to connect to the Scrypted accessories. I submitted that issue to them here: https://github.com/home-assistant/core/issues/86750

So after 3 strikes, I was out ⚾️ and figured I'd write you to see if you had any ideas. Does avahi actually work somehow with some configuration I can use? Can I filter those local 172.x.x.x addresses from bonjour-hap? Or can you fix ciao somehow? I need one of these to work.

**Comment by koush** [comment]
To enable avahi in the container, you need to set this environment variable:

SCRYPTED_DOCKER_AVAHI

https://github.com/koush/scrypted/blob/main/docker/fs/etc/s6-overlay/s6-rc.d/avahi/run

**Comment by jeffjumper** [comment]
Adding that variable got avahi working in the container, so that's good. And it published the mDNS records similarly to how ciao did it...without putting the 172.x.x.x addresses for the local docker networks into the record.

[scrypted-container.log](https://github.com/koush/scrypted/files/10521710/scrypted-container.log)
[homekit-plugin.log](https://github.com/koush/scrypted/files/10521713/homekit-plugin.log)

But...I'm seeing the same behavior as with ciao where those records stop being publishing after 2 minutes or so...maybe a bit longer with avahi, but still happening. In that container log you can see I restarted the homekit plugin to make it work again for a bit.

Is it possible that something else (Scrypted or otherwise) is causing this to happen for both ciao and avahi? It's strange that bonjour-hap is unaffected by whatever this is (and it's the only one that puts the 172.x.x.x records in...related?). I noticed there are many, many errors in the container logs. Are they related? Things that say rpcpeer and mixins and whatever device 36 is which is apparently missing unexpectedly. Should I try to rebuild the container from scratch? Any suggestions on what else to check here?

One more new piece of information that may be helpful: the mDNS records actually come and go. I'm not sure how long before they come back, but I saw they were back and then gone shortly afterwards again. So maybe something is restarting whatever process is dying and then it dies again.

I appreciate your help on this!

**Comment by koush** [comment]
The errors are benign, it looks like you have a browser session acting up. It's on a page for a device that no longer exists. Been meaning to fix that bug.

**Comment by koush** [comment]
I suspect you have an mdns repeater or something on your network that times them out quickly. Disable IGMP snooping on your router. Or enable it if it's already off. Maybe that fixes it.

**Comment by jeffjumper** [comment]
I believe you've sussed it out. I found igmp snooping was enabled on my Synology mesh router and turned it off. Avahi has been stable for almost a half hour now. Thank you!

**Comment by koush** [comment]
I'd try ciao again.

**Comment by jeffjumper** [comment]
If I have any problems, I will. Thanks again!

**Comment by koush** [comment]
Ciao is the recommended default. Wouldn't use it if you don't have to.
