### ISSUE TITLE
HomeKit mDNS fails when there are lower MTU interfaces on server (such as WireGuard)

### ISSUE THREAD

**Issue by abuchanan920** [koush/scrypted#535]
I ran into a problem lately where my cameras weren't showing up. I'm seeing the following errors in the logs:
```
uncaughtException AssertionError [ERR_ASSERTION]: Probe query packet exceeds the mtu size (1442>1440). Can't split probe queries at the moment!
    at Function.createDNSQueryPackets (/src/coder/DNSPacket.ts:271:16)
    at f.sendQueryBroadcast (/src/MDNSServer.ts:256:31)
    at d.sendProbeRequest (/src/responder/Prober.ts:165:17)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}
```
When this error is in the logs, the cameras aren't found in the Home app (despite being visible within Scrypted) and I can't add a camera to the Home app.

The only interface on the server with a non-1500 MTU was the wireguard interface (wg0) which has a 1440 MTU by default due to required encapsulated headers. I shutdown wireguard and restarted the HomeKit plugin and the cameras came right up in the Home app. Alas, that isn't a permanent solution.

It DOES appear that the lower level ciao library allows you to pass in an interface (or list of interfaces) to use. That would solve the problem as I could just tell it to use the one interface that it SHOULD be using. 

See: https://github.com/homebridge/ciao/blob/master/src/MDNSServer.ts#L132 and https://github.com/homebridge/ciao/blob/657dfcc5a54d9ec5614300ff84e4e025320751c0/src/index.ts#L52

It is there that I lose the trail a bit so far... I'm not clear on where the responder is being set up for HomeKit. I'm not seeing it in Scrypted. Is it in another repo? A library that is being used?

I also would need to sort out how to add an option in Scrypted that gets passed down the stack.

Any help would be appreciated! Thanks!

**Comment by koush** [comment]
I think this might be it. https://github.com/koush/scrypted/blob/8e174842fa7673b84b5e46ff6ecc546f105ac79b/plugins/homekit/src/main.ts#L363

**Comment by abuchanan920** [comment]
It does indeed seem to be what I'm looking for. Looks like it was reverted a few months back for some reason?

**Comment by koush** [comment]
I can't recall why at the moment. Probably had some adverse effects.

**Comment by abuchanan920** [comment]
Digging into this a bit more...

Uncommenting the bind lines by themselves doesn't do anything because the value of addressOverride is always undefined.

Looking at the logic in getSettings https://github.com/koush/scrypted/blob/main/plugins/homekit/src/main.ts#L111 , it seems like it gets some addresses component (is this the similar address override setting on the Scrypted settings tab as opposed to the one in the HomeKit plugin?), and if it can get the component it then checks if the HomeKit address override is set. If so then it sets the overall setting to the homekit one (?) and then blanks out the homekit one. Otherwise it hides the HomeKit setting UI so you can't set one. So there is no path which allows you to wind up with that value set.

I suspect this is where the issue was when it was removed? Something seems amiss with the setting logic rather than the actual usage of it. As a user, I probably would have expected this logic to go in the opposite direction. If the overall address was set, use that for the HomeKit setting by default.

**Comment by koush** [comment]
oh right, the address override value is no longer used and defers to the server setting. try hard coding it manually and see if it fixes the issue.

if so, I will add it as an option.

**Comment by abuchanan920** [comment]
It indeed fixes my issue.

**Comment by koush** [comment]
try the beta plugin. https://github.com/koush/scrypted/commit/3cc3f494846289848275bda0a80ac3a284dd7981

**Comment by ptath** [comment]
Cameras became offline in HomeKit (about 9 hrs ago), found this thread.

Looks like after update HomeKit -> Settings -> mDns interfaces setup was reset

<img width="439" alt="Снимок экрана 2023-02-04 в 09 48 22" src="https://user-images.githubusercontent.com/397799/216751329-b07e4c6a-cce1-428a-b80e-3bf6c086898a.png">

Works fine after restoring it to "Server Address".

**Comment by koush** [comment]
Should be fixed. Was a few extraneous bugs.

**Comment by burntcookie90** [comment]
I seem to be running into this

Environment info:

Scrypted: v0.122.0
Homekit Plugin: 1.2.61
Unifi Protect Plugin: 0.0.164

```
mdns bind address undefined
Removed Recordings: 0: 0 bytes.
Retained Recordings: 0: 0 bytes.
uncaughtException AssertionError [ERR_ASSERTION]: Probe query packet exceeds the mtu size (1442>1440). Can't split probe queries at the moment!
    at Function.createDNSQueryPackets (/@scrypted/homekit/main.nodejs.js:2:639903)
    at p.sendQueryBroadcast (/@scrypted/homekit/main.nodejs.js:2:594461)
    at h.sendProbeRequest (/@scrypted/homekit/main.nodejs.js:2:668048)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}
```

<img width="571" alt="image" src="https://github.com/user-attachments/assets/ff91c477-3ee7-4ac0-af57-37235d703f75" />

**Comment by burntcookie90** [comment]
It looks like manually entering my server IP address into `mDNS Interfaces` fixes the issue
