### ISSUE TITLE
Suggestion: Remember me for login

### ISSUE THREAD

**Issue by sampotts** [koush/scrypted#538]
Firstly, thanks for an awesome piece of software. In my humble opinion, it would be even better still if there was an option to "remember me" when logging in. It seems to kick me out almost daily so not having to log in again would be fantastic.

**Comment by mikesalz** [comment]
This!!!!

**Comment by chrisevans1001** [comment]
The cookie length is 24 hours unless in the app. Would be good to extend this or be customisable.

**Comment by sampotts** [comment]
And silently, automatically attempt to reconnect. That's another pain point.

**Comment by chrisevans1001** [comment]
> And silently, automatically attempt to reconnect. That's another pain point.

agreed but for tracking purposes, probably easier if you submit a new issue for this one as they're distinct. :)

**Comment by sampotts** [comment]
For sure, will create another issue. Just noting it here since they're related, in my eyes at least.

**Comment by mikesalz** [comment]
@koush thoughts on this?  

Or giving the option to use http rather than https locally, so that Chrome won't bark at it being "not secure" which would all us to can save passwords in Chrome.

**Comment by bjia56** [comment]
fwiw there's an http port available at 11080

**Comment by mikesalz** [comment]
> fwiw there's an http port available at 11080

That is amazing!  I had no idea there was an http port available!  That is exactly what I needed.  Thank you @bjia56!
