### ISSUE TITLE
cloud plugin upnp connection unstable

### ISSUE THREAD

**Issue by daniel-lo** [koush/scrypted#540]
pictures say more than words:

![upnp_problems](https://user-images.githubusercontent.com/4311558/215484058-cb696791-3cda-49a3-9f67-162b43ce69ec.gif)

**Comment by koush** [comment]
need words, specifically the ones in the Console.

**Comment by daniel-lo** [comment]
https://ctxt.io/2/AAAQJ0v8Ew

**Comment by daniel-lo** [comment]
The bottom line is I keep losing active state for no obvious reason.

**Comment by daniel-lo** [comment]
I found an IP in the log file that was confusing and I found I had two devices listening to uPNP .. the wrong one seemed to be addressed. Now that I turned off listeing on that device I cannot enforce the error mentioned above .. hopefully it stays that way. I still get this warning .. but I think it is not important:
```(node:1158) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by koush** [comment]
your router is erroring out on the upnp request. use port forwarding instead.
