### ISSUE TITLE
ffmpeg error while loading shared libraries

### ISSUE THREAD

**Issue by OXOTH1K** [koush/scrypted#55]
I was make clean install on raspberry pi 4 with docker compose. When I'm starting to watch video from my camera on Home kit, I was see errors in logs:

```
[HIKVISION DS-2CD2132-I] /raspbian/usr/local/bin/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory


[HIKVISION DS-2CD2132-I] ffmpeg exited

uncaughtException Error: killed
    at ChildProcess.b (/common/src/ffmpeg-rebroadcast.ts:101:34)
    at ChildProcess.emit (node:events:402:35)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

e Rebroadcast Plugin uncaughtException Error: killed
```

**Comment by koush** [comment]
This might be the new raspbian, let me check. You can try removing the `SCRYPTED_FFMPEG_PATH_ENV_VARIABLE` bit from your docker run or docker compose file.

**Comment by koush** [comment]
I presume you also ran with the `privileged` flag?

**Comment by OXOTH1K** [comment]
> I presume you also ran with the `privileged` flag?

Yep. 

> This might be the new raspbian, let me check. You can try removing the `SCRYPTED_FFMPEG_PATH_ENV_VARIABLE` bit from your docker run or docker compose file.

Okay. I'll try today, thanks.

**Comment by koush** [comment]
> **UPD** Yes, it was worked for me!

Can you let me know what version of raspbain you are running?

**Comment by OXOTH1K** [comment]
Linux raspberrypi 5.10.63-v7l+

**Comment by koush** [comment]
This is an issue with the new raspbian lite, please look at the updated docker instructions for pi.
