### ISSUE TITLE
Web UI Has Newly-Introduced Layout Issues in Firefox

### ISSUE THREAD

**Issue by alexiscordova** [koush/scrypted#550]
After a recent upgrade, the layout of the web UI seems to have squished. After digging into the developer tools, it looks like `width: 100%` was either removed or is required for the `.v-sheet.v-card` classes. The issues don't occur in Chrome.

<img width="1747" alt="Screenshot 2023-02-08 at 8 35 44 AM" src="https://user-images.githubusercontent.com/1877250/218137091-2a8c5169-f6b0-4021-adef-65cdbe6a22dc.png">
<img width="1749" alt="Screenshot 2023-02-08 at 8 35 58 AM" src="https://user-images.githubusercontent.com/1877250/218137106-2605857c-6d2b-4a4e-8a77-6a958577abee.png">
<img width="1792" alt="Screenshot 2023-02-10 at 7 54 20 AM" src="https://user-images.githubusercontent.com/1877250/218137112-9799d818-08b7-4b7f-b042-37b2ee177d6f.png">

**Comment by koush** [comment]
Not seeing that here on Firefox? 
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/73924/218139155-11ff6e0c-12c0-4898-b099-f5d40ea7c950.png">

**Comment by alexiscordova** [comment]
Strange! I'll do some more research and get back to you.

**Comment by alexiscordova** [comment]
Found the issue, totally on my side. Apologies!
