### ISSUE TITLE
WebRTC plugin 0.1.30+ doesn't work offline

### ISSUE THREAD

**Issue by kiler129** [koush/scrypted#557]
As per [conversation on Discord](https://discord.com/channels/882329362295316500/882329362295316503/1075104329335312394) the WebRTC plugin since 0.1.30 no longer operates without the server having an internet connection. I was able to track the problem to this commit: https://github.com/koush/scrypted/commit/0d7115b9a11ae45d488c07d12c206da4f387bec7

Before this change the server attempted to reach to `142.250.112.127:19302` and after a few failed attempts it did load the stream in the WebUI. Since the commit mentioned above, the server tries to connect to `147.135.36.109:3478` and when it fails the following exception is logged:

```
scrypted  | unhandledRejection TypeError: Cannot read properties of undefined (reading 'getAttributeValue')
scrypted  |     at b.connectionMade [as connect] (/external/werift/packages/ice/src/turn/protocol.ts:165:22)
scrypted  |     at protocol (/external/werift/packages/ice/src/turn/protocol.ts:318:20)
scrypted  |     at t.Connection.candidates [as getComponentCandidates] (/external/werift/packages/ice/src/ice.ts:206:13)
scrypted  |     at t.Connection.gatherCandidates (/external/werift/packages/ice/src/ice.ts:112:15)
scrypted  |     at t.RTCIceGatherer.gather (/external/werift/packages/webrtc/src/transport/ice.ts:128:21)
scrypted  |     at async Promise.all (index 0)
scrypted  |     at I.setRemoteDescription (/external/werift/packages/webrtc/src/peerConnection.ts:978:33)
scrypted  |
scrypted  | e WebRTC Plugin unhandledRejection TypeError: Cannot read properties of undefined (reading 'getAttributeValue')
```

After that, the browser does not show the stream. A workaround is downgrading the WebRTC plugin to `0.1.29`, or removal of the lines 425-428 (added in the commit above) from `plugins/webrtc/src/main.ts`.

**Comment by koush** [comment]
fixed https://github.com/shinyoshiaki/werift-webrtc/pull/323
