### ISSUE TITLE
HomeKit device.info doesnt work anymore

### ISSUE THREAD

**Issue by MichlW** [koush/scrypted#558]
I'm on Scrypted 0.6.16 and tried to set the device.info parameters for my doorbell in REPL console of the corresponding device group.

Therefore I entered the following details:
```
device.info = {
    model: 'Yi Outdoor 1080p',
    manufacturer: 'Yi Technologies',
    version: 'Yi-Hack-V5 0.3.7',
    firmware: '0.3.7',
    serialNumber: 'xxx'
}
```
The infos can be read out by entering `device.info` in REPL console:
![image](https://user-images.githubusercontent.com/49558935/218853813-3f3a2c6b-877f-4ffe-90a5-5e3d2b8b2009.png)
But even after reloading the HomeKit plugin the details are not shown in Home app.

After restarting the scrypted container the settings are lost and device.info is empty.

Prior to my actual setup I used this successfully a few months ago.
What I am doing wrong?

**Comment by koush** [comment]
Someone else reported this as well. Does seemed to have stopped working.

**Comment by koush** [comment]
fixed

**Comment by Kienz** [comment]
I have Version 0.6.26 and it seems that it doesn't work for Device Groups (type doorbell). Can you confirm?

**Comment by MichlW** [comment]
I also have 0.6.26 and for now it works since the next version after my original post.

**Comment by Kienz** [comment]
After reloading it works!
