### ISSUE TITLE
Suggestion: Login via SSO / OpenID Connect

### ISSUE THREAD

**Issue by crazyracer98** [koush/scrypted#566]
Would it be possible to include a login option via SSO?
More specifically via OpenID Connect, so someone deploying scrypted could use e.g. Keycloak as an identity provider?
Maybe using something like passport (https://www.npmjs.com/package/passport) could be an option for this?

Many thanks in advance.

**Comment by koush** [comment]
it's possible to use the SCRYPTED_ADMIN_TOKEN and Auth headers to headers to do this now.

**Comment by ghaisasadvait** [comment]
how to setup the Auth headers via Authentik SSO? I could not find any docs for the auth headers

I am assuming setting my user in SCRYPTED_ADMIN_TOKEN would essentially login to that user irrespective of which use the Authentik provides? How to make sure that the Scrypted logs in to that specific Authentik user account ? (provided same username exists in scrypted)
