### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by mirkolenz** [koush/scrypted#569]
Hello,
first of all, thank you so much for all the effort you put into this project. For me, it works flawlessly and offers a great experience.

I would like to request a better release management for scrypted. On my home server, I run multiple containers with fixed versions to prevent accidental updates. Then, I use the GitHub watch feature for all of these repos to be notified if a new version is released. Scrypted is the only project where this does not work as new releases are not published using the GitHub Releases feature. Currently, I check the versions of the [Docker image](https://github.com/koush/scrypted/pkgs/container/scrypted) every morning, but that is quite tedious.

It would vastly improve my updating workflow if you could support the native GitHub releases. Thanks again!

**Comment by koush** [comment]
npm publish will generate GitHub releases now, which will contain an autogenerated changelog.

**Comment by mirkolenz** [comment]
Thank you so much, it works as expected. I already received an alert for v0.6.20. Have a nice weekend!
