### ISSUE TITLE
synology-ss webhook

### ISSUE THREAD

**Issue by seanzhang98** [koush/scrypted#57]
Hi, 
I tried to use synology-ss plugin and all the cam on my synology ss were imported. 
However, I tried to switch the 'Linked motion sensor' between 'Build-in motion sensor' and the sensor with the same name as the cam but no motion was triggered for both sensor. I can see the surveillance station can detect the motion on the surveillance station web interface.
Are there anything else need to be set up in the surveillance station or scrypted?
Best.

**Comment by koush** [comment]
@IGx89 there was some additional setup required here if I recall. Some web hooks?

**Comment by koush** [comment]
it looks like the web hook instructions are in the plugin already. please refer to them.

**Comment by IGx89** [comment]
Yeah, look for this under the devices for your cameras:

![image](https://user-images.githubusercontent.com/282698/143064836-f08c9944-16e7-4994-9091-7f52f5317ace.png)

You'll need to go into Surveillance Station and create a webhook alert rule for each camera, triggered upon motion detected. Here's what the action should look like:

![image](https://user-images.githubusercontent.com/282698/143064977-bac5818a-75bf-4704-ac9f-27da73e492a5.png)

Sorry that it takes so much manual effort to create motion alerts! I plan to automate the process eventually, if possible.

Let me know if that does the trick, and if you have any other questions! Glad to hear the import went well.

**Comment by seanzhang98** [comment]
Thank you! It is working now, amazing!
