### ISSUE TITLE
Install script broken

### ISSUE THREAD

**Issue by matsura8** [koush/scrypted#575]
Trying to install natively using 

 curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-docker-compose.sh | sudo SERVICE_USER=$USER bash

results in 

Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
Please answer yes or no. (y/n)
bash: line 34: syntax error near unexpected token `fi'

Running Debian 11 (Bullseye).

**Comment by koush** [comment]
where are you seeing this? this was fixed in the new instructions. Maybe something needs to be updated.
