### ISSUE TITLE
Install script points to an unsigned repository

### ISSUE THREAD

**Issue by grooverkm** [koush/scrypted#589]
Trying to install on Raspberry Pi with Docker, and I am running into this issue:

mkdir -p ~/.scrypted
curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-docker-compose.sh > ~/.scrypted/install-scrypted-docker-compose.sh 
sudo SERVICE_USER=$USER bash ~/.scrypted/install-scrypted-docker-compose.sh
Install Docker? (y/n) y
# Executing docker install script, commit: 66474034547a96caa0a25be56051ff8b726a1b28
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease' is not signed.

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by koush** [comment]
fixed. google gpg key was down yesterday.
