### ISSUE TITLE
HomeKit: ffmpeg process leak

### ISSUE THREAD

**Issue by statop** [koush/scrypted#59]
I have found a couple of ways to cause ffmpeg processes to be created and never killed -

- Via homekit, open a stream in home app and quickly close the stream.

- When the source times out in rebroadcast plugin, it retries with a new process, and doesn't kill old, and will create infinite processes

**Comment by koush** [comment]
Will fix this

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/6bb3c61b62a4eec99a76ff0fa0dc76bd96547131
