### ISSUE TITLE
Snapshot retrieval process from HomeKit produces the following error

### ISSUE THREAD

**Issue by jmnovak50** [koush/scrypted#590]
As HomeKit retrieves snapshot refreshes from camera receiving the following errors from Device:

[HomeKit]: HomeKit Connection 192.168.1.93
[HomeKit]: snapshot error TypeError: Cannot read properties of undefined (reading 'interfaces')
[HomeKit]:     at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:79:78)
[HomeKit]:     at snapshotThrottle (/src/types/camera/camera-snapshot.ts:23:20)
[HomeKit]:     at snapshotAll (/src/types/camera/camera-snapshot.ts:50:13)
[HomeKit]:     at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:76:13)
[HomeKit]:     at /external/HAP-NodeJS/src/lib/controller/CameraController.ts:651:23
[HomeKit]:     at new Promise (<anonymous>)
[HomeKit]:     at _t.handleSnapshotRequest (/external/HAP-NodeJS/src/lib/controller/CameraController.ts:635:12)
[HomeKit]:     at Wr.handleResource (/external/HAP-NodeJS/src/lib/Accessory.ts:1826:18)
[HomeKit]:     at Ue.emit (node:events:513:28)
[HomeKit]:     at Ue.emit (node:domain:489:12)

**Comment by koush** [comment]
I think this is due to a device deletion, and homekit plugin has not been reloaded yet.

**Comment by jmnovak50** [comment]
Ok!  Thank you for the quick response!  Have a great week!
