### ISSUE TITLE
Choosing "ignore" option in "Discovered Camera" dialogue has no effect

### ISSUE THREAD

**Issue by briangunderson** [koush/scrypted#593]
Dialog text reads : "A new camera was discovered on the network: aaa.bbb.ccc.ddd (IP of discovered camera)."

Options presented are "Ignore", "Later", and "Add".

The "Ignore" option does not seem to have any discernable effect. Clicking it neither causes the cameras to be ignored in future sessions nor does it dismiss the dialogue. 

Using chrome on Win11. Scrypted is hosted on Ubuntu using Docker. Nvidia GPU and Coral USB present. 6 Cameras in use, all Amcrest cams configured roughly to the specs outlined in Scrypted setup guide.
![2023-02-28 08_53_17-Scrypted Network Video Recorder](https://user-images.githubusercontent.com/1896394/221891256-a94e99a9-2d88-4f27-bab2-353af98b37e0.png)

**Comment by koush** [comment]
Thanks, fixed. Incidentally, this dialog should not be popping up for you at all, as it should be deduplicating cameras that can be imported in both onvif and the manufacturer plugin. Is your amcrest plugin up to date?
