### ISSUE TITLE
Stream from ring defect 

### ISSUE THREAD

**Issue by castrol84** [koush/scrypted#596]
Hello,
I have scrypted on a raspberry pi together with hoobs.

The two implemented ring cameras are showing half green screen in HomeKit 
![C70F08B8-09AA-4CFC-BB3A-85BB08B3170E](https://user-images.githubusercontent.com/126641495/222650681-630db973-4585-4915-a34e-99cc3c683925.png)
and are not sufficient. The cameras themselves are okay (working in ring app 100%). See screenshot attached.
What can be the problem and how to solve it?

**Comment by leedsalex** [comment]
this is due to packet loss, is your home hub wired or wireless?

**Comment by koush** [comment]
incomplete idr frame or packet loss, no fix available.
