### ISSUE TITLE
Receive events from object detection plugins.

### ISSUE THREAD

**Issue by jfrancis537** [koush/scrypted#597]
Is it possible to write a script or plugin that can receive object detection events from plugins like tensorflow-lite?

If so are there any examples?

**Comment by koush** [comment]
yes, use mqtt if you want to export them into something else. or you can write a script/plugin to do it as well. https://github.com/koush/scrypted/blob/main/packages/client/examples/detection.ts

**Comment by jfrancis537** [comment]
Thanks for the fast response!
