### ISSUE TITLE
Docker Support for Raspberry Pi

### ISSUE THREAD

**Issue by jsmecham** [koush/scrypted#6]
Docker image does not work on arm64 (i.e. Raspberry Pi).

> scrypted    | standard_init_linux.go:228: exec user process caused: exec format error

Is it possible to publish this for arm64 as well as amd64 et al?

**Comment by koush** [comment]
Hmm whoops. Let me take a look.

**Comment by koush** [comment]
Investigating now, I suspect its just changing something here, but I'm not super familiar with docker and pi to know the correct stuff without digging through docs.

https://github.com/koush/scrypted/blob/main/.github/workflows/docker.yml

**Comment by koush** [comment]
Ok, I've uploaded an arm64 image:
https://hub.docker.com/repository/registry-1.docker.io/koush/scrypted/tags?page=1&ordering=last_updated

The platforms can be modified in this action linked below, but I'm unsure if arm64 works for pi. I may need something else?
https://github.com/koush/scrypted/blob/main/.github/workflows/docker.yml#L42

**Comment by koush** [comment]
I'll set up my pi and take a look.

**Comment by jsmecham** [comment]
Awesome, I’ll try it in an hour or so and report back!

**Comment by silvercard23** [comment]
Interested in findings about installing it on raspberry pi docker!

**Comment by koush** [comment]
There’s an arm64 docker image up that you can try. Let me know.

**Comment by jsmecham** [comment]
Works! Thank you!
