### ISSUE TITLE
G4 Doorbell Pro Package Camera thumbnail same as main camera

### ISSUE THREAD

**Issue by jeffkibuule** [koush/scrypted#602]
I've had a G4 Doorbell Pro set up since last year with Scripted and it's worked great. There seems to be a recent regression however where the thumbnail for the package camera that points downward is the same as the main camera that points forward. After the camera is viewed as a livestream in the Home app on iOS, the thumbnail updates correctly. 

Main camera is the large thumbnail to the left, package camera is at the bottom. Notice the duplication.
<img width="1138" alt="Screenshot 2023-03-05 at 6 49 55 PM" src="https://user-images.githubusercontent.com/734509/223008685-6de3513e-643f-4e9a-a85f-4cb264a3e3a9.png">
I then click to view the package camera that points downward.
<img width="1138" alt="Screenshot 2023-03-05 at 6 50 01 PM" src="https://user-images.githubusercontent.com/734509/223008786-098d4130-fe0f-4616-9fa3-90eecea57b8c.png">
The thumbnail then correctly updates.
<img width="1138" alt="Screenshot 2023-03-05 at 6 50 06 PM" src="https://user-images.githubusercontent.com/734509/223008874-5441ac11-084e-4c16-9d76-17482943a91e.png">
This behavior also exists when viewed directly in Scrypted on the web.

**Comment by koush** [comment]
this is a known unifi protect bug and has been resolved in a beta I think

**Comment by koush** [comment]
you can work around this by using `snapshots from pre buffer` setting on that specific camera.
