### ISSUE TITLE
Feature Request : Modify login form input for browser autofill compatibility

### ISSUE THREAD

**Issue by briangunderson** [koush/scrypted#608]
I believe this is a simple change to the input tag. This would allow browsers to recognize the username and password fields as such, enabling password managers to automatically fill in the values for the user.

**Comment by GravityRZ** [comment]
this seems to working now. in my situation browser fills in admin and password automatically

**Comment by koush** [comment]
> I believe this is a simple change to the input tag. This would allow browsers to recognize the username and password fields as such, enabling password managers to automatically fill in the values for the user.

are you referring to scrypted management console or nvr app here?

**Comment by briangunderson** [comment]
Management Console (local)

**Comment by codyc1515** [comment]
Auto fill is now working for me in the local management console on iOS Safari since some time.

**Comment by koush** [comment]
> Management Console (local)

hm weird, has always worked for me on safari. what browser?

**Comment by briangunderson** [comment]
I'm not sure what mechanism each credential manager uses to "find" the
correct fields to automatically populate username/email/password/etc. I'm
using iCloud Passwords for Chrome on Windows 11 which works for just about
everything but Scrypted. It's not a big deal so please don't spend much
time on it; I just thought I'd pass it along in case it was affecting more
users than just me. Thanks!

**Comment by mikesalz** [comment]
I'm not sure how it seems to be working for some people and not others.  I am presented with this every time I go to the Management Console. Chrome on Mac.  I would LOVE to see this remember my user name and password.  Such a hassle to type it every time.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/46855061/235276233-8ea631cb-16d5-48af-8517-1afb2e9d3f8d.png">

**Comment by mikesalz** [comment]
> hm weird, has always worked for me on safari. what browser?

I just tried Safari - It does seem to work there.  But it does not work in Chrome.

**Comment by mikesalz** [comment]
Hmmm... Is it because Chrome does not think the page is secure?  I don't think you can create a certificate for an IP, right?  Can we access Scrypted via http rather than https when on a local network?

![image](https://github.com/koush/scrypted/assets/46855061/307bf3e2-05c8-4d92-8bcb-661d21252b6a)

**Comment by chris001** [comment]
It's a wildcard (match any host name or IP address), self-signed (therefore not secure), certificate.

**Comment by koush** [comment]
seems to be a browser issue with self signed certs. it works for me on chrome/safari.
