### ISSUE TITLE
Enable OpenCV for your RTSP camera causing 100% CPU usage - Raspberry Pi 4

### ISSUE THREAD

**Issue by Cha7lie** [koush/scrypted#61]
Using docker on a Pi 4, or installing manually. When enabling OpenCV for motion detection for HKSV, the Pi's cpu spikes and stays at 100% usage.

Removing the Open CV plugin drops the CPU usage to a normal level (5/10%). 

Is this expected behaviour or a bug? Other plugins used are HomeKit; RTSP Camera Controller; Rebroadcast Plugin; Scrypted Core

**Comment by koush** [comment]
Use the lowest resolution available stream. Also use hardware accelerated decode if possible.

**Comment by koush** [comment]
OpenCV is CPU intensive yes.
