### ISSUE TITLE
Homekit reporting repeatedly that "Home is offline"

### ISSUE THREAD

**Issue by champagnealexandre** [koush/scrypted#619]
I have just migrated from an Intel 2020 macbook pro to an M1 2022, and migrated Scrypted as documented by copying the "volume" folder. Everything works, except that I now have the problem in title.

I had no such problem on the old macbook. But now it seems that every time my new macbook goes to sleep—even for a few minutes—Scrypted gets taken down.

Any idea how can I investigate this?

**Comment by koush** [comment]
turn off sleep mode?

**Comment by champagnealexandre** [comment]
I just checked on my old macbook and the following option was turned on: Displays→Advanced→Prevent automatic sleep

So it seems like Scrypted only works properly when macOS isn’t sleeping automatically—I’m still a bit new to macOS services, didn’t know that.

Sorry for bothering!
