### ISSUE TITLE
still image missing in HomeKit doorbell notification

### ISSUE THREAD

**Issue by campbellbs** [koush/scrypted#623]
Hi,
I set up scrypted today to migrate my HomeKit doorbell from homebridge. Everything worked fine and I am really amazed about the performace and reliability. But there is one feature I am missing: the still image in the doorbell notification on my iPhone / MacBook.

The doorbell notification looks now like this:
<img width="414" alt="IMG_7397CC585689-1" src="https://user-images.githubusercontent.com/15308862/224853542-06fb054a-1b7b-4b21-aa23-60f5fdc8f7fe.png">

With homebridge it looked like this:
<img width="414" alt="IMG_E1BE5C03A05C-1" src="https://user-images.githubusercontent.com/15308862/224853566-97565c53-579d-48d8-ac4f-9ad4123d401f.png">

I did not find any possibility to configure this. Do you have any idea if this is possible or would this be a new feature? 

Thank you in advance

BR,
campbellbs

**Comment by campbellbs** [comment]
after 10 minutes it suddenly worked

**Comment by latel** [comment]
> after 10 minutes it suddenly worked

hey, is your images or video preview in homekit doorbell notification stable. I have this problem: https://github.com/koush/scrypted/issues/1610

**Comment by campbellbs** [comment]
> > after 10 minutes it suddenly worked
> 
> hey, is your images or video preview in homekit doorbell notification stable. I have this problem: #1610

Hey unfortunately it’s not 100% stable. I would say it’s a 50/50 thing if the preview image is contained or not in the notification but I stopped investing this in more detail since the whole thing seems to be based on some magic I don’t want to debug.
