### ISSUE TITLE
Onvif: configurable RTSP stream

### ISSUE THREAD

**Issue by neuhausf** [koush/scrypted#632]
I‘m using the onvif plugin for my Tapo C210, which works great. But I want to proxy the stream over rtsp-simple-server to offload the cam when using it in Home Assistant.

Is there a possibility to configure an alternative stream-URI - the rest (primary motion detection), should be untouched.

**Comment by koush** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/73924/225679574-ce281f77-e420-407a-8f06-6bd1de0180ba.png">
use the rtsp rebroadcast url.

**Comment by neuhausf** [comment]
I‘m using the onvif plugin because of the provided motion detection (which is great). So if you could add an override of the stream URL, that would be great. If too complicated, I understand 🙂

**Comment by koush** [comment]
you can use device groups to combine devices. no plan on allow overriding urls.
