### ISSUE TITLE
Ring plug-in issue with versions after 0.0.100

### ISSUE THREAD

**Issue by shababyousaf** [koush/scrypted#647]
I have had issues with the ring plug-in after version  0.0.100 ....both the releases after this version do not work for both my setups at 2 different addresses

if i rollback to version 0.0.100 all seems to be fine version 102 and 104 don't work for me on both setups

**Comment by mikesalz** [comment]
I am experiencing the same issue.  Rolling back to 0.0.100 works.  Not sure if this helps, but this is my log:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/46855061/226419933-9b403f41-a56d-4980-9fc0-ac90369805d8.png">

**Comment by kidinstinct** [comment]
Experiencing the same

**Comment by kidinstinct** [comment]
> FYI...the 105 beta is working for me now

confirmed

**Comment by keithajmani** [comment]
Confirming that the .105 beta worked for me as well -- Ring Pro DoorBell 2. Was having the same issues of intermittent failures, now appears all good.

**Comment by codyc1515** [comment]
I was also facing issues with these versions with the Ring Pro Doorbell 2 but agree that the latest version seems to have sorted this.

**Comment by koush** [comment]
@leedsalex this fixed in latest tag?
