### ISSUE TITLE
Hikvision 2 way audio via camera option

### ISSUE THREAD

**Issue by shababyousaf** [koush/scrypted#648]
some Hikvision cameras have built-in 2 way audio that works with the technology built in to the camera rather than the NVR support ....this doesn't seem to work and only one way Audio listen-in works only.

In the Hikvision app when 2 way audio is selected it gives you an option to select NVR or IP-Camera 

image attached for reference 
![IP-Camera](https://user-images.githubusercontent.com/59517413/226387732-0aa3d265-c0b5-4ad6-b752-28ab7e8144f3.jpg)

**Comment by koush** [comment]
no plans to introduce a native dependency. connect directly to the camera.
