### ISSUE TITLE
new scenario of deploy with Netatmo webcam and more...

### ISSUE THREAD

**Issue by pilot1981** [koush/scrypted#65]
Hi,
I would understand if I can/how I can use this scenario:
- n.1 outdoor webcam Netatmo Presence (it is already HSV compatibile, HA already can extract video flow) https://dev.netatmo.com/apidocumentation/security https://www.home-assistant.io/integrations/netatmo/ I am aware they use H.264 via HLS - https live streaming; Hypothetically it might be possible to use ffmpeg to convert the HLS stream to an RTSP stream. Or we can get this to work would be via the camera's JPEG snapshots, which should give you good quality but poor performance (low frames per second). 
- can I install scrypted SW on raspberry 3 bpi+ with HA or I can/have to use Apple Mac Mini with Mac OS X El Captain?
- which MQTT outoodr butto you can suggest?
- I can use external microphone/speaker to obtain bi-directional audio conversation in videocall of Homekit doorbell implementation?
-

**Comment by koush** [comment]
scrypted supports RTSP and uses webrtc for live streaming to the dashboard.
rpi 3 works fine
any mqtt button works
bidirectional audio is only supported on amcrest and unifi, but anyone can write a plugin for more.

**Comment by pilot1981** [comment]
I don’t find any UNIFI or AMCREST webcam IP67 with BI-directional audio…
