### ISSUE TITLE
Change HomeKit Device Icon

### ISSUE THREAD

**Issue by gh0sti** [koush/scrypted#654]
For some reason in home app I can't change the icon of the camera device. Other smart devices that are added can have their icon changed on what type of device it is. Both cameras from g4 doorbell pro can't  be changed.

**Comment by koush** [comment]
homekit issue

**Comment by gh0sti** [comment]
> homekit issue

Doesn't it depend on the manufacturer to allow the icon change? So wouldn't the bridge settings of scrypted allow us to tell homekit to change the icon of the camera in home app?

**Comment by codyc1515** [comment]
No
