### ISSUE TITLE
Q: Google Home two way audio?

### ISSUE THREAD

**Issue by pergolafabio** [koush/scrypted#658]
Hi, just a question, I don't use scrypted yet , but I see possibilities to add plugins for door intercoms...

If I expose the camera to Google home , can I use two way audio on the Google hub devices? Or is for stream only?

**Comment by koush** [comment]
yes

**Comment by pergolafabio** [comment]
Ok, gonna test it with Hikvision, I saw you implemented ISAPi for it

**Comment by pergolafabio** [comment]
And will the device be exposed as a camera entity? Or is it a intercom entity that you can answer?

**Comment by koush** [comment]
oh google home does not support intercoms at all, no. scrypted does. but you can create a dummy camera for the intercom.

**Comment by pergolafabio** [comment]
Yeah, but I want to speak and use two way audio on an Google hub device, but not sure if exposed cameras to Google support that, it's more a Google issue I think...

Also exposed cameras from Home Assistant are unable to use audio on it with the mic from the Google device

**Comment by pergolafabio** [comment]
Seems there is some "talk and listen" function, and also "announcement" , but probably only supporter on Nest devices

**Comment by pergolafabio** [comment]
1 last question @koush , are you using the camera trait to expose it to Google?
Seems there is also an doorbell trait :

https://developers.home.google.com/cloud-to-cloud/guides/doorbell

**Comment by milandzuris** [comment]
work 2way audio in Google Home or no?
