### ISSUE TITLE
Watchtower scope isn't actually set in docker-compose.yaml

### ISSUE THREAD

**Issue by gsfriedman** [koush/scrypted#662]
The file docker/docker-compose.yml does not correctly set the Watchtower monitoring scope.

According to Watchtower's docs, you need to not only set a scope label on the services to update (optionally including Watchtower itself), but you need to specify the scope to use as a command parameter. That's missing from scypted's yaml and the consequence is that there is no scope applied and scrypted's docker instance is competing with other instances.

The relevant Watchtower doc is here: https://containrrr.dev/watchtower/running-multiple-instances/

The fix is to add "--scope scrypted" to the command line in scrypted's docker compose so that it looks like this:

  command: --interval 3600 --cleanup --scope scrypted

I suspect that the author of the file thought that adding the scope label to the Watchtower service would cause it to monitor that scope but that's not what it does. Adding that label to the Watchtower service causes Watchtower to also monitor itself.

**Comment by gh0sti** [comment]
Issue 661 could probably merge with 662 to hopefully resolve this issue.

**Comment by gsfriedman** [comment]
Thanks for the quick fix!
