### ISSUE TITLE
Changed behaviour in Homekit: Intercom is started when live view is activated

### ISSUE THREAD

**Issue by nanosonde** [koush/scrypted#668]
Hi!

There is a changed in the behaviour of the Homekit Intercom for cameras with two-way audio.

In the past when opening the live view of such a camera, the intercom was not started automatically.
Instead, one had to press the "TALK" button in Homekit.

The new behaviour imposes a problem for SIP-like cameras: as soon as the intercom is started the doorbell gets called immediately and the other normal phones in the house stop ringing as the call was already picked up. 
So if the user decides - after viewing the live view of the doorbell - NOT to talk to the person in front of the door, other users in the house do not have the chance anymore to use the normal phone in the house to answer the call.

Was the behaviour accidently introduced or was it on purpose? If so, I would like to understand why...

**Comment by nanosonde** [comment]
I am using Version 0.7.33 with all plugins up-to-date.

**Comment by koush** [comment]
seems to be a homekit behavior change. 5a879863

**Comment by nanosonde** [comment]
Working. Thanks for restoring the old behaviour.
