### ISSUE TITLE
How do you login?

### ISSUE THREAD

**Issue by SemoTech** [koush/scrypted#67]
Forgive my ignorance, but I just installed SCRYPTED (v0.0.81) on a 2GB Pi 4B (already running Pi Lite w/ Homebridge & PiHole) and the install went fine. I am planning to use scrypted for Unifi Cameras on HomeKit to get Secure Video. 

After install and when navigating to **https://localhost:10443/** I get the login screen below.

![image](https://user-images.githubusercontent.com/1452100/143953396-ad9c633a-7e91-4e89-ba14-1e0dea813f51.png)

What username and password does it expect????

Thanks!

**Comment by julianrinaldi** [comment]
You set your own username and password here.

**Comment by SemoTech** [comment]
I tired that and I get this:

![image](https://user-images.githubusercontent.com/1452100/143955531-dad666a5-ddb0-4f96-9174-7e75c9c53bf1.png)

**Comment by SemoTech** [comment]
This seems to be due to the SSL certificate "localhost" installed by scrypted... It replaced my original one and is now causing refresh and access issues.

**Comment by koush** [comment]
that certificate is only used on a specific port, 10443. it will not interfere with anything else. if you changed your port forwarding, maybe something changed there. Scrypted does not use port 443.

**Comment by SemoTech** [comment]
> that certificate is only used on a specific port, 10443. it will not interfere with anything else. if you changed your port forwarding, maybe something changed there. Scrypted does not use port 443.

Understood @koush , homebridge uses 443 and scrypred 10443. However I am seeing the original cert I had loaded in homebridge still loading, but now showing the site as untrusted. And of course the scrypted cert "localhost" untrusted when accessed via 10443.

How does one change the cert scrypted uses?  Is there any tutorial for that? 
Maybe if they are both the same this will go away?

Thanks.

**Comment by koush** [comment]
What browser?

**Comment by SemoTech** [comment]
> 

Brave in MacOS Monterey

**Comment by SemoTech** [comment]
So the issue with the login not working has to do with the browser not reloading, due to the untrusted SSL "localhost" certificate.  How can I replace it?

**Comment by koush** [comment]
This may be a Brave bug with it not saving certificate per host/port combination. Try using safari.

**Comment by julianrinaldi** [comment]
I'm using Brave on Monterey and I don't have this issue.

**Comment by SemoTech** [comment]
Safari has same behavior as Brave. 

This issue did not exist until scrypted was installed...  The "locahlost" SSL it uses/installs is the issue.  How does one change it????
