### ISSUE TITLE
Group integrated camera always loads slower than standalone added in HomeKit 

### ISSUE THREAD

**Issue by jimsmt** [koush/scrypted#675]
Hi, first I want to thank you for this great project

I have a Hikvision 4K camera, added to Scrypted via ONVIF protocol, if I add this camera directly as a standalone device into HomeKit, it loads really fast, instantly, almost no any delay. But if I create a device group with a doorbell button,  the camera and some other motion sensors, then add the grouped video doorbell into HomeKit, it always take about 1 second to load the video stream, much slower than loading a standalone camera.

I checked the console for logs, everything seems the same and no problem at all. I tried enable and disable the Rebroadcast plugin for the camera and the grouped doorbell, didn't change anything

Any clue what cause the extra delay?

**Comment by koush** [comment]
need logs. make sure you are not rebroadcasting both the group and the actual device either.

**Comment by koush** [comment]
homekit secure video enabled camera takes longer to load because apple delays live stream to load all the video clips into the ui. known bug.

**Comment by gitgayhub** [comment]
I disabled HKSV for the grouped doorbell, started iPhone, loading time is still 1 sec
Then enabled HKSV for the standalone camera, restart iPhone, loading is still instant

Any clue?
