### ISSUE TITLE
RTSP: (M)JPEG over RTP - payload type 26: handle transcoding in scrypted automatically as required

### ISSUE THREAD

**Issue by nanosonde** [koush/scrypted#676]
Hi!

I have just setup the  gstreamer RTSP server of [sip2rtsp](https://github.com/nanosonde/sip2rtsp) to provide an MJPEG video stream via RTSP as the camera is only able to output MJPEG directly.

I can see the following in the logs: 

```
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rebroadcast mode: rtsp
stream url rtsp://10.10.10.70:19554/sip2rtsp-cam
[Rebroadcast Plugin]: -hide_banner -use_wallclock_as_timestamps 1 -rtsp_transport tcp -i rtsp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:41323/1b9b8e1e2ad3edee
[Rebroadcast Plugin]: exiting prebuffer session (released or restarted with new configuration)
[Rebroadcast Plugin]: Guessed Channel Layout for Input Stream #0.1 : mono
[Rebroadcast Plugin]: Input #0, rtsp, from 'rtsp://10.10.10.70:19554/sip2rtsp-cam':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     title           : Session streamed with GStreamer
[Rebroadcast Plugin]:     comment         : rtsp-server
[Rebroadcast Plugin]:   Duration: N/A, start: 1680274055.824422, bitrate: N/A
[Rebroadcast Plugin]:   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 90k tbr, 90k tbn
[Rebroadcast Plugin]: No audio stream detected.
[Rebroadcast Plugin]: Video codec is not h264. If there are errors, try changing your camera's encoder output.
[Rebroadcast Plugin]: prebuffer session started
[Rebroadcast Plugin]: Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[Rebroadcast Plugin]: Output #0, rtsp, to 'rtsp://127.0.0.1:41323/1b9b8e1e2ad3edee':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     title           : Session streamed with GStreamer
[Rebroadcast Plugin]:     comment         : rtsp-server
[Rebroadcast Plugin]:     encoder         : Lavf59.16.100
[Rebroadcast Plugin]: Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 90k tbr, 90k tbn
[Rebroadcast Plugin]:   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[Rebroadcast Plugin]: Stream mapping:
[Rebroadcast Plugin]:   Stream #0:0 -> #0:0 (copy)
[Rebroadcast Plugin]:   Stream #0:1 -> #0:1 (copy)
[Rebroadcast Plugin]: Press [q] to stop, [?] for help
[Rebroadcast Plugin]: frame=    1 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=  11x
[Rebroadcast Plugin]: video/audio detected, discarding further input
```

What would I like to achieve? Do as less transcoding as possible. 
So far I had configured the gstreamer RTSP server in sip2rtsp to transcode MJEG to H264 and then provide that to scrypted via the ONIV plugin.
Of course this introduces additional latency.

From the above logs it seems that scrpted seems to be mainly based on H264 internally.
Is there a chance to handle the described MJPEG scenario in a better and possibly automatic way?
FFmpeg supports MJPEG via RTSP.

**Comment by koush** [comment]
You can use the ffmpeg plugin probably? Scrypted doesn't care about the RTSP payload codecs at all within rebroadcast.

**Comment by nanosonde** [comment]
Mhmm. That would be an option for testing only.

However, as I described I would like to provide an RTSP MJPEG stream via ONVIF plugin which uses all the RTSP code from the RTSP plugin if understand that correctly.

For ONVIF profile S cameras, MJPEG via RTSP seems to be a mandatory feature. RTP payload type 26.
See 7.9 here: https://www.onvif.org/wp-content/uploads/2018/08/ONVIF_Profile_-S_Specification_v1-2.pdf
And 5.1.4 here: https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec-v241.pdf

**Comment by nanosonde** [comment]
Just saw that ONVIF profile T mandates at least H264 or H265.
So if you say that you only support profile T than this would be an argument to deny support of MJPEG as profile T does not mandate it anymore as profile S.

**Comment by nanosonde** [comment]
Ok, thanks for thinking about it.

I suggest that you extend the following sentence in the README of the ONVIF plugin: „ Cameras must support the ONVIF-T profile to receive motion events.“ with a description that older profiles like profile S are not supported if they only support the mandatory MJPEG codec for the video stream and not the optional H264 codec. Profile S is supporters if the video codec can be changed.
Otherwise the ONVIF plugin requires profile T. Not only because of events, but also because of the mandatory H264 codec.
