### ISSUE TITLE
Raspberry Pi updates to 64bit kernel and python-codecs plugin stops working 

### ISSUE THREAD

**Issue by koush** [koush/scrypted#678]
`python-codecs` will fail to install. This message will be visible in the console log:

```
Python machine vs architecture mismatch detected. Plugin installation may fail.
```

**Comment by koush** [comment]
This can be fixed by editing `/boot/config.txt` on the pi. Modify the `[pi4]` as follows to set `arm_64bit=0`:

```
[pi4]
arm_64bit=0
```

**Comment by jlg89** [comment]
I would assume that if the 64-bit kernel is active, you could uninstall 32-bit python and then install the 64-bit version. Would that be another fix, or are there additional gotchas?

**Comment by koush** [comment]
Seems very unlikely to work without issue. Whole system is a mess.
