### ISSUE TITLE
Stream from Scrypted to other applications

### ISSUE THREAD

**Issue by codyc1515** [koush/scrypted#683]
Is it possible to expose a stream from Scrypted, e.g. Ring Doorbell, to use in another system, e.g., Home Assistant? Tried looking through all the documentation and settings I can see but didn’t find anything.

**Comment by koush** [comment]
use the rtsp rebroadcast urls.

**Comment by koush** [comment]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/73924/229373315-bf591f16-f01b-438a-9555-17c4c79df9ec.png">

**Comment by koush** [comment]
nvr product also has low latency streaming cards. 
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/73924/229373414-cc083676-da06-45d9-9773-a0b4b19057b6.png">

**Comment by codyc1515** [comment]
Thanks. Rebroadcast method worked. How do I setup the cards? Doesn’t seem to be any documentation on this.
