### ISSUE TITLE
Adaptive Streaming settings appearing to be ignored.

### ISSUE THREAD

**Issue by SirBigBits** [koush/scrypted#687]
I currently have all my cameras unchecked in the Adaptive Streaming plugin, but when i'm viewing via nvr.scrypted.app, the initial stream is being compressed.  I have to change the Playback Quality to HIGH to force it to stream the main stream.

**Comment by koush** [comment]
this is default rebroadcast behavior for remote streaming, not adaptive streaming. adaptive streaming will downgrade local and remote connections further than their initial bitrate.
