### ISSUE TITLE
Abnormal high CPU usage for several minutes

### ISSUE THREAD

**Issue by champagnealexandre** [koush/scrypted#689]
Hi,

I’ve just been warned of high CPU usage, see screenshot. I can confirm the process shown is `npm exec scrypted serve`.

Logging in to the management console I see scrypted just notified that an update is available. Could this be related?

<img width="248" alt="image" src="https://user-images.githubusercontent.com/30211986/229842379-4abc4159-307b-4af1-9708-7860f3130ad4.png">

**Comment by koush** [comment]
that may just be the parent/root process. are you certain that's the actual process? there are many node processes started. 1 per plugin. can you take a screenshot of all your plugins?

**Comment by champagnealexandre** [comment]
I updated & restarted scrypted, has not happened since. I’ll investigate further if it happens again. Thanks.
