### ISSUE TITLE
Onvif with Tapoc100 camera: Two Way audio setting is saved in storage but not on UI 

### ISSUE THREAD

**Issue by vishuraogithub** [koush/scrypted#690]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/85231598/229852047-0ef73eb8-7625-475b-8901-c917ef8d8f48.png">

as a result, the Tapo Two Way Audio plugin isnt enabled to be added. 
This was working fine few version ago. 

Now, even with cameras that have the setting enabled, disabling and then trying to renable them fails.

**Comment by vishuraogithub** [comment]
https://github.com/koush/scrypted/commit/5028fb812d903c66a6130bd809bdd70752b65202 
fixed it i think. thanks.

**Comment by koush** [comment]
will require a server build.
