### ISSUE TITLE
Tapo Two way audio not working : exits with error 

### ISSUE THREAD

**Issue by vishuraogithub** [koush/scrypted#691]
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 539560017,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 1250484932,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: Will wait for initial RTCP packet. { isHomeHub: false, isLowBandwidth: false, hasHomeHub: false }
[HomeKit]: { isLowBandwidth: false, isWatch: false, destination: 'local' }
[HomeKit]: { tool: undefined, rtpSender: 'Default' }
[HomeKit]: Waiting for video RTCP packet before sending video.
[HomeKit]: packet loss 1
[HomeKit]: Received first video RTCP packet.
[HomeKit]: rtsp/tcp h264
[HomeKit]: a/v h264 opus found h264 undefined
[HomeKit]: rtsp/tcp pcm_alaw
[HomeKit]: -hide_banner -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 10055250 -dn -sn -vn -f rtp rtp://127.0.0.1:56289?pkt_size=400 -sdp_file pipe:4
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 24 7 8
[HomeKit]: idr start found: 28 5
[HomeKit]: [rtsp @ 000001a6c316c5c0] method SETUP failed: 461 Unsupported Transport
[HomeKit]: Guessed Channel Layout for Input Stream #0.0 : mono
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:56055':
[HomeKit]:   Metadata:
[HomeKit]:     title           :
[HomeKit]: Session streamed by "TP-LINK RTSP Server"
[HomeKit]:     comment         : stream1
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: 64 kb/s
[HomeKit]:   Stream #0:0: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (pcm_alaw (native) -> opus (libopus))
[HomeKit]: Press [q] to stop, [?] for help
[HomeKit]: Output #0, rtp, to 'rtp://127.0.0.1:56289?pkt_size=400':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Session streamed by "TP-LINK RTSP Server"
[HomeKit]:     comment         : stream1
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: received first audio packet
[HomeKit]: intercom failed to start RPCResultError: getaddrinfo ENOTFOUND undefined
[HomeKit]:     at Function.from (C:\node_modules\axios\dist\node\axios.cjs:825:14)
[HomeKit]:     at v.<anonymous> (C:\node_modules\axios\dist\node\axios.cjs:2973:25)
[HomeKit]:     at v.emit (node:events:513:28)
[HomeKit]:     at v.emit (node:domain:489:12)
[HomeKit]:     at ClientRequest.l.forEach.u.<computed> (C:\node_modules\follow-redirects\index.js:14:24)
[HomeKit]:     at ClientRequest.emit (node:events:513:28)
[HomeKit]:     at ClientRequest.emit (node:domain:489:12)
[HomeKit]:     at Socket.socketErrorListener (node:_http_client:502:9)
[HomeKit]:     at Socket.emit (node:events:513:28)
[HomeKit]:     at Socket.emit (node:domain:489:12)
[HomeKit]: @scrypted/tapo:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined

**Comment by vishuraogithub** [comment]
this works fine from browser: 


win32 x64 Windows 10 Pro
server version: 0.7.45
plugin version: @scrypted/onvif 0.0.118
########################
4/4/2023, 10:32:33 pm
########################
......
[Tapo Two Way Audio]: video codec/container not matched, transcoding: undefined
[Tapo Two Way Audio]: -hide_banner -rtsp_transport udp -i rtsp:[REDACTED] -vn -sn -dn -acodec pcm_alaw -ar 8000 -ac 1 -dn -sn -vn -f rtp rtp://127.0.0.1:53742? -sdp_file pipe:4
[Tapo Two Way Audio]: Input #0, rtsp, from 'rtsp://127.0.0.1:56733':
[Tapo Two Way Audio]:   Duration: N/A, start: 0.000000, bitrate: N/A
[Tapo Two Way Audio]: Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
[Tapo Two Way Audio]: Stream mapping:
[Tapo Two Way Audio]:   Stream #0:0 -> #0:0 (opus (native) -> pcm_alaw (native))
[Tapo Two Way Audio]: Press [q] to stop, [?] for help
[Tapo Two Way Audio]: Output #0, rtp, to 'rtp://127.0.0.1:53742?':
[Tapo Two Way Audio]:   Metadata:
[Tapo Two Way Audio]:     encoder         : Lavf59.16.100
[Tapo Two Way Audio]: Stream #0:0: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[Tapo Two Way Audio]:     Metadata:
[Tapo Two Way Audio]:       encoder         : Lavc59.18.100 pcm_alaw
[Tapo Two Way Audio]: size=       0kB time=00:00:00.01 bitrate=  81.8kbits/s speed=N/A
[Tapo Two Way Audio]: video/audio detected, discarding further input
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[Rebroadcast Plugin]: mainStream active rebroadcast clients: 0
[Tapo Two Way Audio]: ffmpeg exited
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: ice transport { ipv4: true, isPrivate: true, destinationId: '10.0.0.132' }
[WebRTC Plugin]: Connection is local network: true
[WebRTC Plugin]: done waiting ice connected
[Rebroadcast Plugin]: Selected stream mainStream
[Rebroadcast Plugin]: sending prebuffer 2001.25
[RTC Connection Bridge]: Client Stream Profile {
[RTC Connection Bridge]:   transcodeBaseline: false,
[RTC Connection Bridge]:   sessionSupportsH264High: true,
[RTC Connection Bridge]:   maximumCompatibilityMode: false,
[RTC Connection Bridge]:   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
[RTC Connection Bridge]:   capabilities: {
[RTC Connection Bridge]:     audio: { codecs: [Array], headerExtensions: [Array] },
[RTC Connection Bridge]:     video: { codecs: [Array], headerExtensions: [Array] }
[RTC Connection Bridge]:   },
[RTC Connection Bridge]:   screen: { devicePixelRatio: 2, width: 1440, height: 900 }
[RTC Connection Bridge]: }
[RTC Connection Bridge]: rtsp/tcp h264
[RTC Connection Bridge]: a/v h264 pcm_alaw found h264 pcm_alaw
[RTC Connection Bridge]: rtsp/tcp pcm_alaw
[Rebroadcast Plugin]: mainStream active rebroadcast clients: 1
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[RTC Connection Bridge]: bypassing ffmpeg, perfect codecs
[RTC Connection Bridge]: first video packet 794
[Tapo Two Way Audio]: video codec/container not matched, transcoding: undefined
[Tapo Two Way Audio]: -hide_banner -rtsp_transport udp -i rtsp:[REDACTED] -vn -sn -dn -acodec pcm_alaw -ar 8000 -ac 1 -dn -sn -vn -f rtp rtp://127.0.0.1:53750? -sdp_file pipe:4
[Tapo Two Way Audio]: Input #0, rtsp, from 'rtsp://127.0.0.1:56798':
[Tapo Two Way Audio]:   Duration: N/A, start: 0.000000, bitrate: N/A
[Tapo Two Way Audio]: Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
[Tapo Two Way Audio]: Stream mapping:
[Tapo Two Way Audio]:   Stream #0:0 -> #0:0 (opus (native) -> pcm_alaw (native))
[Tapo Two Way Audio]: Press [q] to stop, [?] for help
[Tapo Two Way Audio]: Output #0, rtp, to 'rtp://127.0.0.1:53750?':
[Tapo Two Way Audio]:   Metadata:
[Tapo Two Way Audio]:     encoder         : Lavf59.16.100
[Tapo Two Way Audio]: Stream #0:0: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[Tapo Two Way Audio]:     Metadata:
[Tapo Two Way Audio]:       encoder         : Lavc59.18.100 pcm_alaw
[Tapo Two Way Audio]: size=       0kB time=00:00:00.01 bitrate=  81.8kbits/s speed=N/A
[Tapo Two Way Audio]: video/audio detected, discarding further input
[Tapo Two Way Audio]: ffmpeg exited
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[Rebroadcast Plugin]: mainStream active rebroadcast clients: 0

**Comment by vishuraogithub** [comment]
while trying to fix the issue, added these many interfaces: 
["29#BinarySensor","51#Camera","51#Intercom","51#VideoCamera","51#VideoCameraConfiguration","51#mixin:@scrypted/homekit","51#mixin:@scrypted/prebuffer-mixin","51#AudioSensor","51#Online","51#RTCSignalingChannel","51#Settings"]


29 is dummy button, 51 being the onvif camera. 

now intercom works, but interfaces UI is lost. 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/85231598/229871030-7735ad2d-fbf4-4b20-8573-c1faeb5adc85.png">

**Comment by koush** [comment]
not sure what you were doing there. the ip was undefined for some reason in initial report,so setup looked incomplete. would delete and start over.
