### ISSUE TITLE
@scrypted/reolink Reolink E1 Zoom - No motion detection events

### ISSUE THREAD

**Issue by overrunner** [koush/scrypted#693]
Hello,

I am running Scrypted 0.7.45 with Plugin @scrypted/reolink 0.0.19 with a Reolink E1 Zoom with latest firmware.
It seems that the events for motion detection never arrive in Scrypted.
In parallel I have a home assistant installation (latest updates) with the default integration. There the E1 Zoom works fine including the events.
I already tried to reinstall plugins etc. - but I never receive in the console any event, nor shows the motion detector icon any motion.

**Comment by koush** [comment]
try onvif?
