### ISSUE TITLE
Login broken in v0.7.45

### ISSUE THREAD

**Issue by ThisIsQasim** [koush/scrypted#696]
I just installed the latest version via docker compose and was unable to sign up and login. Downgrading to `v0.7.43` allowed me to login

**Comment by koush** [comment]
browser console log please.

**Comment by ThisIsQasim** [comment]
I didn't see anything in the console log. Interestingly I was able to downgrade, signup, login and then successfully upgrade. Login continues to work after the upgrade. So apparently signup is broken and not the login.

**Comment by koush** [comment]
> I didn't see anything in the console log. Interestingly I was able to downgrade, signup, login and then successfully upgrade. Login continues to work after the upgrade. So apparently signup is broken and not the login.

understood, let me take a look.

**Comment by rehpa** [comment]
I have the same issue.  New install of 0.7.45 last night.  It let me set the password the first time going to the login page.  After that I wasn't able to log in.  

[scrypted_0.7.45_webconsole.log](https://github.com/koush/scrypted/files/11162368/scrypted_0.7.45_webconsole.log)
[server.log](https://github.com/koush/scrypted/files/11162383/server.log)

**Comment by jimfactor7** [comment]
I have the same login loop issue on a fresh install of 0.7.45.

**Comment by Rich-Chamberlain** [comment]
Restart the container and the login should work

**Comment by koush** [comment]
build with fix in progress.
