### ISSUE TITLE
@scrypted/reolink Reolink Wifi Doorbell - Two way audio support

### ISSUE THREAD

**Issue by DavithkbY** [koush/scrypted#699]
Now that reolink has released two way audio support on their official firmware, are there any plans to add two way audio for the doorbell in the scrypted plugin?

**Comment by vegedb** [comment]
@koush 
Any reason you closed this?
It was updated 4 days ago for the first time ever.

![image](https://user-images.githubusercontent.com/72070424/230555015-ef8d055f-8de9-4544-8e52-932bb2789c1f.png)

![image](https://user-images.githubusercontent.com/72070424/230554899-2919ab82-d595-4dcb-a55c-f2c5f28c453d.png)

**Comment by lifeng1994** [comment]
I have successfully talked through the ONVIF plugin.
