### ISSUE TITLE
Google Device Access: login button fails if scrypted cloud plugin is not installed.

### ISSUE THREAD

**Issue by forsethc** [koush/scrypted#70]
Said error (in file: app.5d98af88.js:1:74142; not that that's super helpful) 
```
Uncaught (in promise) TypeError: web:core: @scrypted/core:host: host:@scrypted/nest: Cannot read properties of null (reading 'getData')
Caused by: undefined
```

To reproduce:
1. Install the @scrypted/nest plugin
1. click "Login" on the settings page

Versions:
@scrypted/nest plugin: 0.0.13
scrypted: 0.0.81

**Comment by koush** [comment]
Install the @scrypted/cloud plugin too please. I think that's the issue.

**Comment by forsethc** [comment]
OK.  This issue was reported about `@scrypted/nest` not `@scrypted/google-device-access`, though neither work.

`@scrypted/nest` (which I now see is no longer in the repository so maybe it's been replaced and is no longer supported) -- this is still broken even when installing `@scrypted/cloud`

`@scrypted/google-device-access` -- when I click the login link here, I get a page at https://nestservices.google.com/partnerconnections with the message: 

```
Can’t link to Scrypted Home Automation

Please contact Vysor Inc if the issue persists
```

As for installing just the `@scrypted/cloud` plugin, I can login without a hostname provided but I still get the above error when trying to then login with `@scrypted/google-device-access`.

When I try to login with `@scrypted/cloud` _with_ a proper hostname, I get: 
```
Cannot GET /_punch/login
```

**Comment by Jack123uk** [comment]
I get the same issue and message when pressing login @forsethc did you find a fix for it? has anyone managed to get this plugin working? 

Thanks

**Comment by k10urzd** [comment]
I also have run into this issue. I attempted with an unraid docker install and installing it with docker-compose on a VM running Ubuntu 20.04 LTS. Same issue on both.

I installed the cloud plugin first, and was able to login to https://home.scrypted.app

I then tried logging into my Google Device Access plugin. I selected my account and was re-directed to the error message:
"Can’t link to Scrypted Home Automation
Please contact Vysor Inc if the issue persists"

**Comment by koush** [comment]
7c9adea..477faca

Fixed

**Comment by koush** [comment]
> I also have run into this issue. I attempted with an unraid docker install and installing it with docker-compose on a VM running Ubuntu 20.04 LTS. Same issue on both.
> 
> I installed the cloud plugin first, and was able to login to https://home.scrypted.app
> 
> I then tried logging into my Google Device Access plugin. I selected my account and was re-directed to the error message: "Can’t link to Scrypted Home Automation Please contact Vysor Inc if the issue persists"

this is a separate issue, you need to create your own google device access account. follow the home assistant instructions for an example.
