### ISSUE TITLE
Problem Ring Plugin

### ISSUE THREAD

**Issue by Ricox1975** [koush/scrypted#700]
The login with 2FA does not work. the green confirmation button is missing. Entering a verification code generated via the ring app also does not work.

Debian Bullseye
Scrypted 0.7.46
RingPlugin 0.0.108
Nodejs 18.5.0
NPM 9.5.0
Access to the ring is via Homebridge.

**Comment by koush** [comment]
green confirmation button hasn't been there for a year. use the save button.

**Comment by Ricox1975** [comment]
i use save button , i don't work
<img width="973" alt="Bildschirmfoto 2023-04-07 um 08 01 36" src="https://user-images.githubusercontent.com/52467622/230551045-82c38af2-478d-40fa-8c98-89e6d57efe2c.png">
