### ISSUE TITLE
No UniFi HomeKit Secure Video Cloud+ Recordings!

### ISSUE THREAD

**Issue by SemoTech** [koush/scrypted#71]
--- I did read and troubleshooted as per the Discord HomeKit-help channel, no luck! ----

This problem occurs on a fresh local npx install of @scrypted v0.0.81 on Pi 4B 2GB w/ Node.JS v16.13.0 & using Raspberry Lite + associated Unifi, HomeKit and ReBroadcast plugins using HTTPS on port 10443.

- Connected @Scrypted UniFi Plugin to my UDM-Pro with a fresh Local Admin account. Logs confirm all OK and interface shows all the cameras discovered and loaded.
- Confirmed all cameras are connected to both Unifi and ReBroadcast @scrypted plugins.
- Added @Scrypted homebridge into HomeKit (by QR Scan) and all cameras were detected by HomeKit and added one-by one, while I enabled Secure Video for all. For reference I am using the 2TB unlimited cameras Cloud+ Apple subscription. 
- Rebooted the HomeHub (ATV 4K w/ tvOS 15.1.1) for good measure. It resides hardwired on the same network and subnet as the Pi running @Scrypted.
- Confirmed all cameras appear in HomeKit on the ATV and show the "Live" view.

To test, I walked in front of 3 Unifi cameras and then checked @scrypted logs for motion events, and indeed they were triggered. Here is a @scrypted log snippet:

```
i G3i Entry state change: motionDetected true
i G3i FR state change: motionDetected true
i G3i Game Rm state change: motionDetected true
i G3i Entry state change: motionDetected false
i G3i FR state change: motionDetected false
i G3i Entry state change: motionDetected true
i G3i Game Rm state change: motionDetected false
i G3i Entry state change: motionDetected false
```

- Confirmed the UDM-Pro Protect App has also recorded all motion events and they all show up and can be played back in the Protect Dashboard.

I then accessed each of the cameras with Home App on iOS 15.1 and the live stream is working fine, _but there is no Cloud+ recording to review and no timeline bar under any of the the camera names_.  WHY???

- I even went back into HomeKit camera settings and setup/enabled an "Activity Zone" encompassing the entire cameras field of view, and also enabled notifications for "A Clip is Recorded", then again walked in front to try to trigger a HKSV recording, without luck. No notification appeared either.   

Thanks in advance!

**Comment by kevinwmerritt** [comment]
I was able to get a notification for motion only after setting up an activity zone for the one G4 Doorbell I've added to HomeKit via Scrypted.

I can't seem to get any clips recorded either despite "Allow Recording" being enabled when home and away.

**Comment by SemoTech** [comment]
@kevinwmerritt Sadly even after doing that I have no luck. Waiting on an Aqara native HK camera to confirm it’s not my network or Apple iCloud+ account. When I was running the Homebridge plug-in on the same Pi I was getting ATV4K notifications on my TV but since I started @Scrypted that’s not working either.

**Comment by kevinwmerritt** [comment]
> I was able to get a notification for motion only after setting up an activity zone for the one G4 Doorbell I've added to HomeKit via Scrypted.
> 
> I can't seem to get any clips recorded either despite "Allow Recording" being enabled when home and away.

Ok turns out it took a few hours but now there is a red circle instead of a blue circle on the camera preview in the Home app. Now I'm getting recordings from Apple. Seems there was a delay for recordings to kick in.

**Comment by SemoTech** [comment]
> > I was able to get a notification for motion only after setting up an activity zone for the one G4 Doorbell I've added to HomeKit via Scrypted.
> > I can't seem to get any clips recorded either despite "Allow Recording" being enabled when home and away.
> 
> Ok turns out it took a few hours but now there is a red circle instead of a blue circle on the camera preview in the Home app. Now I'm getting recordings from Apple. Seems there was a delay for recordings to kick in.

@kevinwmerritt Glad for you. Is this for the same G4 Doorbell, and do you still have the selected zone active?  Lastly, do you get a notification and video preview on your ATV when the doorbell is rung?

**Comment by koush** [comment]
I've addressed this issue in discord, user has a weird network setup.
