### ISSUE TITLE
Tapo two way audio not working in grouped devices

### ISSUE THREAD

**Issue by budisek** [koush/scrypted#711]
Hey, thanks a lot for great plugin in Scrypted.

I have made ONVIF camera (Tapo C320WS) with two way audio enabled and it works. When I add this to Homekit as standalone device I can see the button in it and I can send the voice through camera.

But when i create group of this same device and dummy doorbell then there is no button for send the sound. What am I doing wrong?

**Comment by koush** [comment]
Group the intercom
