### ISSUE TITLE
@Google Home / Nest Hub 2 Won't stop streaming after a minute

### ISSUE THREAD

**Issue by DavithkbY** [koush/scrypted#714]
When using the example script to trigger live video when my doorbell is pressed, everything works fine but the steam won't stop.
It'll stream indefinitly. 

The script: 

```const chromecast = systemManager.getDeviceByName<MediaPlayer & StartStop>('Woonkamer Hub');
const camera = systemManager.getDeviceByName<VideoCamera>('Deurbel');

class OpenDoorbellOnNestHub implements StartStop {
    timeout: any;

    async start() {
        device.running = true;
        const video = await camera.getVideoStream();
        await chromecast.load(video);

        // automatically stop the playback after 1 minute
        clearTimeout(this.timeout);
        this.timeout = setTimeout(() => this.stop(), 60000);
    }
    async stop() {
        device.running = false;
        return chromecast.stop();
    }
}

export default OpenDoorbellOnNestHub;
let open = new OpenDoorbellOnNestHub();
open.start();```

**Comment by DavithkbY** [comment]
So the workaround I am using currently is: 
1: Add google assistant sdk to home assisstant
2: Add an automation in home assistant that sends a text containing 'stop streaming' that is triggered by a webhook
3: Create an automation in scrypted with the above script, then a 35 seconds wait 'action', and then a shell script that calls the webhook to trigger the automation in home assistant. 

Would be nice if scrypted could just stop the stream so this workaround won't be needed :)

**Comment by sidamos** [comment]
I am having this issue with the current version of Scrypted, so it seems not to be fixed.
