### ISSUE TITLE
Bug: Automation javascript/shell empty when having both

### ISSUE THREAD

**Issue by DavithkbY** [koush/scrypted#715]
When having both javascript and shell in the same automation, one of them is blank but the automation does still work. You just can't edit the script afterwards.
Screen:
![image](https://user-images.githubusercontent.com/71630103/230903047-fec604c1-2745-4968-8362-e8448fcc2373.png)

**Comment by koush** [comment]
This is an issue with embedding multiple editors (Monaco) into the same page. They do not support this. Use a wait in the first script.

**Comment by DavithkbY** [comment]
> This is an issue with embedding multiple editors (Monaco) into the same page. They do not support this. Use a single script for everything.

The thing is, the script doesn’t get activated from the automation. Even when I manually press ‘start’ it won’t trigger it.

**Comment by DavithkbY** [comment]
@koush video of the scripts not working: 
https://www.veed.io/view/024484cb-4f61-4067-b1fb-6fcd919995bb?sharingWidget=true&panel=share
