### ISSUE TITLE
Support for restarting a plugin in Automations

### ISSUE THREAD

**Issue by wilsonjeff72** [koush/scrypted#720]
I'm finding my cams can randomly stop producing motion events.  I still don't know the cause but the fix seems to be to restart the RTSP Plugin.  Having to do this manually a couple times a day is painful.  

I would love the ability to have Automations do that for me but I don't see the option.  Maybe this is doable via Automations running a script but I don't know enough about how to set that up.

Current Automation "actions" available:

![image](https://user-images.githubusercontent.com/56868784/231982443-f131a39a-14b0-449a-9c43-90a93ab4f98f.png)

**Comment by koush** [comment]
Please open a bug for the actual issue, which is that the motion sensor stops working. Include a log.
