### ISSUE TITLE
Motion sensing intermittently stops working

### ISSUE THREAD

**Issue by wilsonjeff72** [koush/scrypted#723]
I'm finding my cams routinely and randomly stop producing motion events.  Sometimes it will stay active for over 12 hours, sometimes only a few hours.  The only way I've found to fix this is to restart the RTSP Camera Plugin.

Your help is greatly appreciated.

Setup details:

- Scrypted 0.7.53
- Wyze Cam v3 (firmware 4.36.10.4054)
- RTSP Camera Plugin 0.0.53
- OpenCV Motion Detection 0.0.74

Some images and logs are attached here.  You can see in this latest example it died at 11:16 AM (it is currently 2:38 PM as I type this).

![image](https://user-images.githubusercontent.com/56868784/232129467-cf53a4cb-7d73-451e-8f76-98ef4bad405d.png)

![image](https://user-images.githubusercontent.com/56868784/232128563-146e2f88-1b42-4b39-9fad-150536af82e2.png)

[log_porch-cam.txt](https://github.com/koush/scrypted/files/11236147/log_porch-cam.txt)
[log_opencv.txt](https://github.com/koush/scrypted/files/11236148/log_opencv.txt)

**Comment by wilsonjeff72** [comment]
I should also say I saw the same behavior when using PAM Diff, that's why I switched to OpenCV to see if it would help.  It seems better at sensing motion but I still have the issue of motion detection dying randomly.

And to be clear, it never fixes itself no matter how long I wait.

**Comment by koush** [comment]
> I should also say I saw the same behavior when using PAM Diff, that's why I switched to OpenCV to see if it would help. It seems better at sensing motion but I still have the issue of motion detection dying randomly.
> 
> And to be clear, it never fixes itself no matter how long I wait.

When its in a broken state, how many active motion detection sessions does video analysis report?

**Comment by koush** [comment]
provide a log from the python codecs plugin too please

**Comment by wilsonjeff72** [comment]
Ok I'll have to wait for it to fail again to check active motion sessions in the failed state.  When working it's 3.

Python Codecs log attached here.

[log_pythoncodecs.txt](https://github.com/koush/scrypted/files/11236288/log_pythoncodecs.txt)

![image](https://user-images.githubusercontent.com/56868784/232132639-a0254542-2da2-477f-af1e-3d34ea37bbd6.png)

**Comment by koush** [comment]
can you grab the video analysis plugin logs too?

**Comment by wilsonjeff72** [comment]
Sure: 
[log_videoanalysis.txt](https://github.com/koush/scrypted/files/11236693/log_videoanalysis.txt)

**Comment by koush** [comment]
Your video analysis version is old, please update. I think this is fixed.

**Comment by wilsonjeff72** [comment]
Ok, giving that a try now, thanks.

**Comment by koush** [comment]
Was this resolved?

**Comment by wilsonjeff72** [comment]
Maybe, 2 days now and it's been good
