### ISSUE TITLE
Mac Installation Problem 

### ISSUE THREAD

**Issue by tnayrb03** [koush/scrypted#725]
When running:

`mkdir -p ~/.scrypted
curl -s https://raw.githubusercontent.com/koush/scrypted/main/docker/install-scrypted-dependencies-mac.sh > ~/.scrypted/install-scrypted-dependencies-mac.sh 
bash ~/.scrypted/install-scrypted-dependencies-mac.sh`

I keep receiving an error of:
`Invalid response body while trying to fetch https://registry.npmjs.org/component-emitter: ENOENT: no such file or directory, rename '/Users/username/.npm/_cacache/tmp/312d80bc' -> '/Users/username/.npm/_cacache/content-v2/sha512/17/78/79a61a5881f84835cafe1fee5b2fb6c7eb5baa4d1fc841dd0327add4219e9a7937226ed58f4d8f7b7f12dd1c8e921bf7771cf8cdeaaa1f92ead57b494fee'`

`This is related to npm not being able to find a file.`

**Comment by koush** [comment]
probably an environment or permission issue. clear that npm directory.
