### ISSUE TITLE
Black Screen when trying to view feed on Android phone

### ISSUE THREAD

**Issue by Iceman248** [koush/scrypted#726]
Neither Chrome nor Vivaldi work, but actually just tried Fennec browser and it does work, so seems isolated to Chromium based mobile web browsers.

The camera feed view shows fine when I go to the device page but as soon as I tap on it to view the feed, it's just black, still shows the microphone icon but two-way audio does not work when it's black, but with Fennec I can see and hear it fine and 2-way audio does work. I even tried it incognito on both apps.

**Comment by koush** [comment]
What OS version?

**Comment by Iceman248** [comment]
Android 10

**Comment by Iceman248** [comment]
After Vivaldi update, I tried it again and the two-way audio does actually work. I noticed that I could hear audio even though I couldn't see anything, so it's just the video. But then I just tried it on Chrome again and everything worked. 🤔
