### ISSUE TITLE
snapshot error only on Mac

### ISSUE THREAD

**Issue by phgerin** [koush/scrypted#735]
Hello, only on Mac (no problem on linux), the snapshot plugin is trying to create a snapshot from ffmeg even with the setting disabled. 
The snapshot URL is working in a web browser or on scrypted/docker/linux

![image](https://user-images.githubusercontent.com/78903348/232467608-b692b4cd-74e1-49f7-aa98-4d800d74232f.png)

ffmpeg input to image conversion timed out.
[Rue] Snapshot failed Error: ffmpeg input to image conversion failed with exit code: 1, /Users/pgh/.scrypted/node_modules/ffmpeg-static/ffmpeg -hide_banner -y -i pipe:4 -filter_complex scale=-2:'min(240,ih)' -frames:v 1 -f image2 pipe:3
    at d (/src/ffmpeg-image-filter.ts:181:15)
    at process.picture (node:internal/process/task_queues:95:5)
    at data (/src/main.ts:302:21)
    at P.takePicture (/src/main.ts:335:13)
    at RpcPeer.handleMessageInternal (/Users/pgh/.scrypted/node_modules/@scrypted/server/src/rpc.ts:734:37)
[Rue] creating error image with background Snapshot Failed true

**Comment by bc2297** [comment]
I'm seeing this as well with homekit+unifi plugin with G4 doorbell pro, scripted on MacOS. only on the main stream. doorbell camera works as expected.
```[Snapshot Plugin]: Snapshot failed Error: ffmpeg input to image conversion failed with exit code: 1, /Users/brandonclarke/.scrypted/node_modules/ffmpeg-static/ffmpeg -hide_banner -y -i pipe:4 -filter_complex crop=iw*0.0064102564102564985:ih*0.0018825301204819164:iw*0.923076923076923:ih*0.03501506024096386 -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]:     at d (/src/ffmpeg-image-filter.ts:181:15)
[Snapshot Plugin]:     at process.picture (node:internal/process/task_queues:95:5)
[Snapshot Plugin]:     at data (/src/main.ts:300:17)
[Snapshot Plugin]:     at P.takePicture (/src/main.ts:335:13)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/Users/brandonclarke/.scrypted/node_modules/@scrypted/server/src/rpc.ts:747:37)
[Snapshot Plugin]: creating error image with background Snapshot Failed false```

**Comment by koush** [comment]
@phgerin enable snapshot debug logging to capture the ffmpeg error.

**Comment by bc2297** [comment]
> I'm seeing this as well with homekit+unifi plugin with G4 doorbell pro, scripted on MacOS. only on the main stream. doorbell camera works as expected.
> 
> ```
> [Snapshot Plugin]:     at d (/src/ffmpeg-image-filter.ts:181:15)
> [Snapshot Plugin]:     at process.picture (node:internal/process/task_queues:95:5)
> [Snapshot Plugin]:     at data (/src/main.ts:300:17)
> [Snapshot Plugin]:     at P.takePicture (/src/main.ts:335:13)
> [Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/Users/brandonclarke/.scrypted/node_modules/@scrypted/server/src/rpc.ts:747:37)
> [Snapshot Plugin]: creating error image with background Snapshot Failed false```
> ```

@koush solved my issue on discord. had somehow set a 2 pixel crop

**Comment by phgerin** [comment]
hello, here is the debug with one error. Not sure why my custom snapshot URL is ignored.
The snapshot from pre buffer is set to "disabled".

: -hide_banner -y -i pipe:[REDACTED] -filter_complex scale=-2:'min(240,ih)' -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]: Input #0, jpeg_pipe, from 'pipe:4':
[Snapshot Plugin]:   Duration: N/A, bitrate: N/A
[Snapshot Plugin]:   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080, 25 fps, 25 tbr, 25 tbn
[Snapshot Plugin]: Stream mapping:
[Snapshot Plugin]:   Stream #0:0 (mjpeg) -> scale:default
[Snapshot Plugin]:   scale:default -> Stream #0:0 (mjpeg)
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x138370000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x138380000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x138390000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x1383a0000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x1383b0000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x118018000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x118008000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x118028000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x128008000] [swscaler @ 0x118038000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: Output #0, image2, to 'pipe:3':
[Snapshot Plugin]:   Metadata:
[Snapshot Plugin]:     encoder         : Lavf59.16.100
[Snapshot Plugin]:   Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown, progressive), 426x240, q=2-31, 200 kb/s, 25 fps, 25 tbn
[Snapshot Plugin]:     Metadata:
[Snapshot Plugin]:       encoder         : Lavc59.18.100 mjpeg
[Snapshot Plugin]:     Side data:
[Snapshot Plugin]:       cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[Snapshot Plugin]: frame=    1 fps=0.0 q=4.8 size=N/A time=00:00:00.04 bitrate=N/A speed=N/A    
frame=    1 fps=0.0 q=4.8 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=4.31x
[Snapshot Plugin]: video/audio detected, discarding further input
[Snapshot Plugin]: ffmpeg exited
[Snapshot Plugin]: -hide_banner -y -i pipe:[REDACTED] -filter_complex scale=-2:'min(240,ih)' -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]: [jpeg_pipe @ 0x14d804080] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
[Snapshot Plugin]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[Snapshot Plugin]: Input #0, jpeg_pipe, from 'pipe:4':
[Snapshot Plugin]:   Duration: N/A, bitrate: N/A
[Snapshot Plugin]:   Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 fps, 25 tbr, 25 tbn
[Snapshot Plugin]: Stream mapping:
[Snapshot Plugin]:   Stream #0:0 (mjpeg) -> scale:default
[Snapshot Plugin]:   scale:default -> Stream #0:0 (mjpeg)
[Snapshot Plugin]: Cannot determine format of input stream 0:0 after EOF
[Snapshot Plugin]: Error marking filters as finished
[Snapshot Plugin]: Exiting normally, received signal 15.
[Snapshot Plugin]: ffmpeg exited
[Snapshot Plugin]: Snapshot failed Error: ffmpeg input to image conversion failed with exit code: 1, /Users/pgh/.scrypted/node_modules/ffmpeg-static/ffmpeg -hide_banner -y -i pipe:4 -filter_complex scale=-2:'min(240,ih)' -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]:     at d (/src/ffmpeg-image-filter.ts:181:15)
[Snapshot Plugin]:     at process.picture (node:internal/process/task_queues:95:5)
[Snapshot Plugin]:     at data (/src/main.ts:302:21)
[Snapshot Plugin]:     at P.takePicture (/src/main.ts:335:13)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/Users/pgh/.scrypted/node_modules/@scrypted/server/src/rpc.ts:747:37)
[Snapshot Plugin]: creating error image with background Snapshot Failed true
[Snapshot Plugin]: -hide_banner -y -i pipe:[REDACTED] -filter_complex eq=brightness=-0.2[snapshotBlur] ; [snapshotBlur] gblur=sigma=25[snapshotText] ; [snapshotText] drawtext=fontfile=/Users/pgh/.scrypted/volume/plugins/@scrypted/snapshot/zip/unzipped/fs/Lato-Bold.ttf:text='Snapshot Failed':fontcolor=white:fontsize=h/8:x=(w-text_w)/2:y=(h-text_h)/2 -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]: Input #0, jpeg_pipe, from 'pipe:4':
[Snapshot Plugin]:   Duration: N/A, bitrate: N/A
[Snapshot Plugin]: Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 426x240, 25 fps, 25 tbr, 25 tbn
[Snapshot Plugin]: Stream mapping:
[Snapshot Plugin]:   Stream #0:0 (mjpeg) -> eq:default
[Snapshot Plugin]:   drawtext:default -> Stream #0:0 (mjpeg)
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158048000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158058000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158068000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158078000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158088000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x158098000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x1580a8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x1580b8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158008000] [swscaler @ 0x1580c8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x158158000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x158168000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x158178000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x158188000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x158198000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x1581a8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x1581b8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x1581c8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x158148000] [swscaler @ 0x1581d8000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: Output #0, image2, to 'pipe:3':
[Snapshot Plugin]:   Metadata:
[Snapshot Plugin]:     encoder         : Lavf59.16.100
[Snapshot Plugin]: Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown, progressive), 426x240, q=2-31, 200 kb/s, 25 fps, 25 tbn
[Snapshot Plugin]:     Metadata:
[Snapshot Plugin]:       encoder         : Lavc59.18.100 mjpeg
[Snapshot Plugin]:     Side data:
[Snapshot Plugin]:       cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[Snapshot Plugin]: frame=    1 fps=0.0 q=3.9 size=N/A time=00:00:00.04 bitrate=N/A speed=N/A    
frame=    1 fps=0.0 q=3.9 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=7.63x    
[Snapshot Plugin]: video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Snapshot Plugin]: video/audio detected, discarding further input
[Snapshot Plugin]: ffmpeg exited
[Snapshot Plugin]: -hide_banner -y -i pipe:[REDACTED] -filter_complex scale=-2:'min(240,ih)' -frames:v 1 -f image2 pipe:3
[Snapshot Plugin]: Input #0, jpeg_pipe, from 'pipe:4':
[Snapshot Plugin]:   Duration: N/A, bitrate: N/A
[Snapshot Plugin]:   Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080,
[Snapshot Plugin]: 25 fps, 25 tbr, 25 tbn
[Snapshot Plugin]: Stream mapping:
[Snapshot Plugin]:   Stream #0:0 (mjpeg) -> scale:default
[Snapshot Plugin]:   scale:default -> Stream #0:0 (mjpeg)
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140308000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140318000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140328000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140338000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140348000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140358000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140368000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140378000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: [swscaler @ 0x160070000] [swscaler @ 0x140388000] deprecated pixel format used, make sure you did set range correctly
[Snapshot Plugin]: Output #0, image2, to 'pipe:3':
[Snapshot Plugin]:   Metadata:
[Snapshot Plugin]:     encoder         : Lavf59.16.100
[Snapshot Plugin]:   Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown, progressive), 426x240, q=2-31, 200 kb/s, 25 fps, 25 tbn
[Snapshot Plugin]:     Metadata:
[Snapshot Plugin]:       encoder         : Lavc59.18.100 mjpeg
[Snapshot Plugin]:     Side data:
[Snapshot Plugin]:       cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[Snapshot Plugin]: frame=    1 fps=0.0 q=4.8 size=N/A time=00:00:00.04 bitrate=N/A speed=N/A
[Snapshot Plugin]: video/audio detected, discarding further input
[Snapshot Plugin]: ffmpeg exited

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/2e9f618f6fb22c524aae9acf24b0a37d1d5c05cf
