### ISSUE TITLE
[bticino plugin]: unable to stream

### ISSUE THREAD

**Issue by talex-tnt** [koush/scrypted#737]
Hi!
it's a few days that I'm trying to get the bticino plugin working but with little luck :-(

The plugin itself looks pretty much working in the end, I'm able to expose the camera entity to homekit, as well as the door button (which works smoothly).. but there's no way I could get the streaming to work instead.

I have very little experience with Scrypted and streaming protocols in general and I'm getting kind of stuck..

Anyway, whenever I try to connect to the camera I get this error: 
[sdp @ 0x7fba2a9045c0] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
At least I'm guessing this could be the issue..
I've also tried to disable the Rebroadcast plugin (since it triggers some kind of rele' in the internal device whenever it connects to to the external one) but with no luck.
(btw I'm able to start and pickup call with linphone) 

Ah, I get the same issue both on macos and on the raspberry pi.

In any case, big thanks to @slyoldfox for developing this plugin. 
Thanks man. 

Here's the full log:

darwin x64 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64
server version: 0.7.76
plugin version: @scrypted/bticino 0.0.7
########################
4/17/2023, 6:57:34 PM
########################
https://192.168.178.22:10443/endpoint/25/public/ , endpoints: /pressed
https://192.168.178.22:10443/endpoint/26/public/ -> endpoints: /lock - /unlock - /unlocked - /locked
[HomeKit]: Device is in accessory mode and is online. HomeKit services are being published.
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: stream SIP will be rebroadcast on demand.
Checking answering machine, cameraId: 25
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
REGISTER sip:1935393.bs.iotleg.com SIP/2.0
To:  <sip:talex@1935393.bs.iotleg.com>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
Max-Forwards: 70
Call-ID: 911522
CSeq: 20 REGISTER
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Contact:  <sip:talex@192.168.178.22;transport=tcp>;+sip.instance="<urn:uuid:0dd585a1-8101-e512-f82633a5dc02aba2>"
Expires: 600
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK892752
Content-Length: 0

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 200 Registration successful
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK892752;rport=51163
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:talex@1935393.bs.iotleg.com>;tag=456jc61ZUUa2p
Call-ID: 911522
CSeq: 20 REGISTER
Contact:  <sip:talex@192.168.178.22:51163;transport=tcp>;+sip.instance="<urn:uuid:0dd585a1-8101-e512-f82633a5dc02aba2>";pub-gruu="sip:talex@1935393.bs.iotleg.com;gr=urn:uuid:0dd585a1-8101-e512-f82633a5dc02aba2",  <sip:192.168.178.22;transport=tls>,  <sip:talex@192.168.178.43:58796;transport=tcp>;+sip.instance="<urn:uuid:ced9c787-b5af-5403-f70a39eb697deaab>";pub-gruu="sip:talex@1935393.bs.iotleg.com;gr=urn:uuid:ced9c787-b5af-5403-f70a39eb697deaab", "TAlex" <sip:talex@192.168.178.22:49568;transport=tcp>;+sip.instance="<urn:uuid:36662a5d-f1ac-00c0-8a54-0d49654f0075>";+org.linphone.specs="lime";pub-gruu="sip:talex@1935393.bs.iotleg.com;gr=urn:uuid:36662a5d-f1ac-00c0-8a54-0d49654f0075"
Expires: 600
Server: Flexisip/1.0.12 (sofia-sip-nta/2.0)
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
MESSAGE sip:c300x@1935393.bs.iotleg.com SIP/2.0
To:  <sip:c300x@1935393.bs.iotleg.com>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
Max-Forwards: 70
Call-ID: 911522
CSeq: 21 MESSAGE
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: text/plain
Contact:  <sip:talex@192.168.178.22;transport=tcp>;expires=600
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK386330
Content-Length: 14

GetAswmStatus!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK386330;rport=51163
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>
Call-ID: 911522
CSeq: 21 MESSAGE
Server: Flexisip/1.0.12 (sofia-sip-nta/2.0)
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
MESSAGE sip:talex@192.168.178.22:51163;transport=tcp;gr=urn:uuid:0dd585a1-8101-e512-f82633a5dc02aba2 SIP/2.0
Via: SIP/2.0/TCP 192.168.178.23;rport;branch=z9hG4bK.N79ZyvjF0g9BtcjNSc0DtmrQUF;received=192.168.178.23
Via: SIP/2.0/TCP 127.0.0.1:54976;branch=z9hG4bK.2~Cd8MJzP;rport=54976
Max-Forwards: 69
From:  <sip:c300x@1935393.bs.iotleg.com>;tag=OEZOgkwy9
To:  <sip:talex@1935393.bs.iotleg.com>
Call-ID: FA3D0N~A8X
CSeq: 20 MESSAGE
Date: Mon, 17 Apr 2023 16:57:44 GMT
User-Agent: Unknown (belle-sip/1.6.3)
Supported: replaces, outbound
Content-Type: text/plain
Content-Length: 411

*#8**40*0*0*8688*1*25##;1|2|1631442776|1;2|2|1631945183|1;3|2|1632389662|1;4|2|1633451624|1;5|2|1637656540|1;6|2|1638648843|1;7|2|1642948413|1;8|2|1644144107|1;9|2|1649917188|1;10|2|1649951500|1;11|2|1654271766|1;12|2|1655925782|1;13|2|1657214823|1;14|2|1664950941|1;15|2|1667464704|1;16|2|1667464733|1;17|2|1670145712|1;18|2|1674029829|1;19|2|1674816687|1;20|2|1675000398|1;21|2|1677253937|1;22|2|1680353016|1;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.178.23;rport;branch=z9hG4bK.N79ZyvjF0g9BtcjNSc0DtmrQUF;received=192.168.178.23
Via: SIP/2.0/TCP 127.0.0.1:54976;branch=z9hG4bK.2~Cd8MJzP;rport=54976
To:  <sip:talex@1935393.bs.iotleg.com>
From:  <sip:c300x@1935393.bs.iotleg.com>;tag=OEZOgkwy9
Call-ID: FA3D0N~A8X
CSeq: 20 MESSAGE
Content-Length: 0

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK386330;rport=51163
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=QHhGDrT
Call-ID: 911522
CSeq: 21 MESSAGE
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[Snapshot Plugin]: creating error image with background Snapshot Failed false
[Snapshot Plugin]: Snapshot failed RPCResultError: The SIP doorbell camera does not provide snapshots. Install the Snapshot Plugin if snapshots are available via an URL.
[Snapshot Plugin]:     at _.takePicture (/plugin/..\src\bticino-camera.ts:124:15)
[Snapshot Plugin]:     at RpcPeer.handleMessageInternal (/Users/alex/gitarea/playground/scrypted/server/src/rpc.ts:738:66)
[Snapshot Plugin]:     at RpcPeer.handleMessage (/Users/alex/gitarea/playground/scrypted/server/src/rpc.ts:683:18)
[Snapshot Plugin]:     at process.<anonymous> (/Users/alex/gitarea/playground/scrypted/server/src/scrypted-plugin-main.ts:33:47)
[Snapshot Plugin]:     at process.emit (node:events:513:28)
[Snapshot Plugin]:     at process.emit (node:domain:489:12)
[Snapshot Plugin]:     at process.emit (/Users/alex/gitarea/playground/scrypted/server/node_modules/source-map-support/source-map-support.js:516:21)
[Snapshot Plugin]:     at emit (node:internal/child_process:937:14)
[Snapshot Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Snapshot Plugin]: @scrypted/bticino:host
[Snapshot Plugin]: host:@scrypted/snapshot {
[Snapshot Plugin]:   cause: undefined
[Snapshot Plugin]: }
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: ice transport { ipv4: true, isPrivate: true, destinationId: '192.168.178.22' }
[WebRTC Plugin]: Connection is local network: true
[WebRTC Plugin]: done waiting ice connected
[Rebroadcast Plugin]: Selected stream SIP
[Rebroadcast Plugin]: SIP prebuffer session started
[Rebroadcast Plugin]: rebroadcast mode: rtsp
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -f sdp -i tcp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:51174/aa5821c8491b1098
SipSession::start()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
INVITE sip:c300x@1935393.bs.iotleg.com SIP/2.0
To:  <sip:c300x@1935393.bs.iotleg.com>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
Max-Forwards: 70
Call-ID: 911522
CSeq: 22 INVITE
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Contact:  <sip:talex@192.168.178.22;transport=tcp>
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK322819
Content-Length: 459

v=0
o=talex 3747 461 IN IP4 192.168.178.22
s=ScryptedSipPlugin
c=IN IP4 192.168.178.22
t=0 0
a=DEVADDR:20
m=audio 65000 RTP/SAVP 110
a=rtpmap:110 speex/8000
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/qE7OPGKp9hVGALG2KcvKWyFEZfSSvm7bYVDjT8X
a=rtcp:49944
m=video 65002 RTP/SAVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/qE7OPGKp9hVGALG2KcvKWyFEZfSSvm7bYVDjT8X
a=recvonly
a=rtcp:60129

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK322819;rport=51163
Record-Route:  <sip:192.168.178.23:5060;transport=tcp;lr>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>
Call-ID: 911522
CSeq: 22 INVITE
Server: Flexisip/1.0.12 (sofia-sip-nta/2.0)
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK322819;rport=51163
Record-Route:  <sip:127.0.0.1:5060;transport=tcp;lr>,  <sip:192.168.178.23:5060;transport=tcp;lr>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=AD8po0j
Call-ID: 911522
CSeq: 22 INVITE
User-Agent: Unknown (belle-sip/1.6.3)
Supported: replaces, outbound
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK322819;rport=51163
Record-Route:  <sip:127.0.0.1:5060;transport=tcp;lr>,  <sip:192.168.178.23:5060;transport=tcp;lr>
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=AD8po0j
Call-ID: 911522
CSeq: 22 INVITE
Contact:  <sip:c300x@127.0.0.1:54976;transport=tcp;verified>;+sip.instance="<urn:uuid:30930d81-652e-4941-bf96-ff0fe54d15e1>"
User-Agent: Unknown (belle-sip/1.6.3)
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Supported: replaces, outbound
Content-Type: application/sdp
Content-Length: 418

v=0
o=c300x 2610 3638 IN IP4 127.0.0.1
s=Talk
c=IN IP4 192.168.178.23
t=0 0
m=audio 28836 RTP/SAVP 110
a=rtpmap:110 speex/8000
a=fmtp:110 vbr=on
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:aQ7oSvsoytb8wnMMadhmO2IDWO5sLPmLoB9LVlqr
m=video 5788 RTP/SAVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=sendonly
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:dwjc2Ig3vAe+jNli5WOSVmNijQjd14u/3QoTQyyR

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ACK sip:c300x@127.0.0.1:54976;transport=tcp;verified SIP/2.0
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=AD8po0j
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
Max-Forwards: 70
Call-ID: 911522
CSeq: 22 ACK
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK578452
Content-Length: 0

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Connecting to Bticino using STUN
Audio stream latched for Bticino, port: 49943
Video stream latched for Bticino, port: 60128
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[Rebroadcast Plugin]: [sdp @ 0x7fba2a9045c0] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
[Rebroadcast Plugin]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[Rebroadcast Plugin]: No audio stream detected.
[Rebroadcast Plugin]: refreshing media stream in 23466
[Rebroadcast Plugin]: Guessed Channel Layout for Input Stream #0.0 : mono
[Rebroadcast Plugin]: Input #0, sdp, from 'tcp://127.0.0.1:51173':
[Rebroadcast Plugin]:   Duration: N/A, bitrate: N/A
[Rebroadcast Plugin]:   Stream #0:0: Audio: speex, 8000 Hz, mono, flt
[Rebroadcast Plugin]:   Stream #0:1: Video: h264, none, 90k tbr, 90k tbn
[Rebroadcast Plugin]: Output #0, rtsp, to 'rtsp://127.0.0.1:51174/aa5821c8491b1098':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     encoder         : Lavf59.16.100
[Rebroadcast Plugin]:   Stream #0:0: Audio: speex, 8000 Hz, mono, flt
[Rebroadcast Plugin]: Stream mapping:
[Rebroadcast Plugin]:   Stream #0:0 -> #0:0 (copy)
[Rebroadcast Plugin]: Press [q] to stop, [?] for help
[Rebroadcast Plugin]: sending prebuffer 4000
[RTC Connection Bridge]: Client Stream Profile {
[RTC Connection Bridge]:   transcodeBaseline: false,
[RTC Connection Bridge]:   sessionSupportsH264High: true,
[RTC Connection Bridge]:   maximumCompatibilityMode: false,
[RTC Connection Bridge]:   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
[RTC Connection Bridge]:   capabilities: {
[RTC Connection Bridge]:     audio: { codecs: [Array], headerExtensions: [Array] },
[RTC Connection Bridge]:     video: { codecs: [Array], headerExtensions: [Array] }
[RTC Connection Bridge]:   },
[RTC Connection Bridge]:   screen: { devicePixelRatio: 2, width: 2560, height: 1440 }
[RTC Connection Bridge]: }
[Rebroadcast Plugin]: client connection error s [Error]
[Rebroadcast Plugin]:     at Socket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:81085)
[Rebroadcast Plugin]:     at Socket.emit (node:events:525:35)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at endReadableNT (node:internal/streams/readable:1359:12)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Rebroadcast Plugin]: SIP terminating rebroadcast due to inactivity
[Rebroadcast Plugin]: rebroadcast error Error: stream inactivity
[Rebroadcast Plugin]:     at Timeout._onTimeout (/@scrypted/prebuffer-mixin/main.nodejs.js:1:125121)
[Rebroadcast Plugin]:     at listOnTimeout (node:internal/timers:569:17)
[Rebroadcast Plugin]:     at process.processTimers (node:internal/timers:512:7)
[Rebroadcast Plugin]: tcp://127.0.0.1:51173: Operation timed out
[Rebroadcast Plugin]: size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: [q] command received. Exiting.
[Rebroadcast Plugin]: video/audio detected, discarding further input
Sending BYE...
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
BYE sip:c300x@127.0.0.1:54976;transport=tcp;verified SIP/2.0
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=AD8po0j
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
Max-Forwards: 70
Call-ID: 911522
CSeq: 23 BYE
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK549438
Content-Length: 0

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Rebroadcast Plugin]: ffmpeg exited
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.178.22:5060;branch=z9hG4bK549438;rport=51163
From:  <sip:talex@1935393.bs.iotleg.com>;tag=972454
To:  <sip:c300x@1935393.bs.iotleg.com>;tag=AD8po0j
Call-ID: 911522
CSeq: 23 BYE
User-Agent: Unknown (belle-sip/1.6.3)
Supported: replaces, outbound
Content-Length: 0

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
sip-call-session callEnded
sip-call-session callEnded: done

**Comment by slyoldfox** [comment]
@talex-tnt that is because the 0.0.7 version uses an intermediate piece of software running on the intercom. I failed to document that somewhere and only 1 other person is using it at this moment.

Join the #sip channel on discord and we'll try and help you through it (you'll still need root access to the system to deploy that).

**Comment by talex-tnt** [comment]
oh thanks! I would have spent days debugging and getting nowhere.. 
anyways, which discord server should I join?

**Comment by slyoldfox** [comment]
https://discord.gg/DcFzmBHYGq

**Comment by mrMiimo** [comment]
@talex-tnt we can close it, right? 
I think you managed to get it to work..

**Comment by talex-tnt** [comment]
Hi, yes with the extra server running in the intercom the stream is now working with version 0.0.7.
Without that, to get the stream working I had to downgrade to 0.0.5, but this version lacks other features.
Thanks guys.
