### ISSUE TITLE
Cannot get HKSV to work with a Wyze Cam using the RTSP firmware

### ISSUE THREAD

**Issue by JonathanRKing** [koush/scrypted#74]
I've followed all the steps here:
https://github.com/koush/scrypted/wiki/HomeKit-Secure-Video-camera

but the camera in the Home app doesn't show any recording options. I cannot figure out how to even troubleshoot it without a lot of trial and error. Is there anything in the Console that might indicate why the HomeKit isn't  supporting HKSR for the camera?

-jonathan

**Comment by JonathanRKing** [comment]
Well, trial and error seems to have helped. After reinstalling OpenCV and restarting the HomeKit plugin, things started working. I now have three Wyze Cams with the RTSP firmware on them detected by HomeKit to support HKSV.

THANK YOU koush for your work on this, I really appreciate it.

-jonathan

**Comment by mishakim** [comment]
Can you share your settings? I have the same issue -- initially, I followed the instructions, and got recording options, but no actual recording, because the motion detection wasn't doing anything. Now, I can't even choose OpenCV as an option on the cameras, and OpenCV doesn't list the cameras as available.

**Comment by koush** [comment]
> Can you share your settings? I have the same issue -- initially, I followed the instructions, and got recording options, but no actual recording, because the motion detection wasn't doing anything. Now, I can't even choose OpenCV as an option on the cameras, and OpenCV doesn't list the cameras as available.

Join discord and ask in the wyze channel. Clear everything out by deleting video analysis and opencv. Then reinstall video analysis and Pam diff.

**Comment by mishakim** [comment]
Thanks - that worked nicely. I'll come over to Discord with further questions.
