### ISSUE TITLE
Python Codec High CPU and Memory Utilization

### ISSUE THREAD

**Issue by jcannon23** [koush/scrypted#743]
The Python Codec is using a large amount of CPU and Memory resources and has been causing my machine to crash.

![image](https://user-images.githubusercontent.com/23659754/232868147-67174487-def8-4f72-8c58-8ab6a4e4004c.png)

**Comment by jcannon23** [comment]
I have 10 python processes running

**Comment by koush** [comment]
how many cameras?

**Comment by jcannon23** [comment]
7 cameras

**Comment by Roarrk** [comment]
Same issue here, this is shortly after a python codecs update that reset the cpu use. 6 cameras. 

![image](https://user-images.githubusercontent.com/10798354/233701115-a975996d-62a2-40a9-b3a5-2a6031f74eec.png)

**Comment by koush** [comment]
This is normal. All decoding is done by that plugin.

**Comment by madmax** [comment]
@koush I upgraded from 0.44 and there was almost no cpu usage, Now python is at 50% cpu all the time. 

<img width="2003" alt="image" src="https://user-images.githubusercontent.com/4486/235228815-453b5c73-1bb2-4baf-8f40-214fa0c7fc81.png">

**Comment by jcannon23** [comment]
Echo'ing @madmax, in prior releases, my CPU and memory utilization were much lower. This is a recent development.

**Comment by Roarrk** [comment]
Same here - was "down" to 30-50 cpu on some of the threads. After this last update I am getting several threads spiking intermittently at 150+ cpu and stalling the mac entirely.

**Comment by koush** [comment]
Please let me know which motion detector is being used.

**Comment by jcannon23** [comment]
@Koush PAM Diff Motion Detection

**Comment by koush** [comment]
I'll look into it at some point. Can try OpenCV instead. Or upgrade to the supported Scrypted (+optional NVR) app which has a custom GPU accelerated motion sensor. https://github.com/koush/nvr.scrypted.app/releases
