### ISSUE TITLE
v0.7.81 remote streams not loading

### ISSUE THREAD

**Issue by SirBigBits** [koush/scrypted#746]
after upgrading to 0.7.81, viewing streams (live and events) remotely just hangs on "Loading".   Let me know what logs you would like and i'll upload them.

**Comment by koush** [comment]
try close and reopen the iOS app to see if it persists. upload camera console logs.

**Comment by SirBigBits** [comment]
This is happening on my PC browser. The issue appears to be random but it's done it a few times in the past 30 minutes.  I'll get some logs shortly.

**Comment by koush** [comment]
check if reload page fixes it.

**Comment by SirBigBits** [comment]
Well Crap... i can't get it to do it now since i reported it.  Go figure.  I did notice on the WebRTC plugin that the "Use TURN Servers" option was checked..  no idea when that got checked or if it even should be checked based on it's description.

**Comment by koush** [comment]
That should be on yes

**Comment by SirBigBits** [comment]
ok. well if it happens again, i'll grab some logs. Thanks.

**Comment by SirBigBits** [comment]
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681534276414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681534276414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681935882042.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681534276414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681935882042.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681533916414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681533916414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936002042.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681533916414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936002042.rtsp'
[Rebroadcast Plugin]: }
########################
4/19/2023, 8:28:42 PM
########################
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681533376413.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681533376413.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936122043.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681533376413.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936122043.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681533256414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681533256414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936182045.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681533256414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936182045.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681533076414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681533076414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936242042.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681533076414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936242042.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681532836414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681532836414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936302043.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681532836414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936302043.rtsp'
[Rebroadcast Plugin]: }
########################
4/19/2023, 8:33:42 PM
########################
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681532416414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681532416414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936422046.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681532416414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936422046.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681532176414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681532176414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936482043.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681532176414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936482043.rtsp'
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681531276414/1681531936414.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681531276414/1681531936414.rtsp' -> '/video/scrypted-38/1681934801960/1681934801960/1681936542045.rtsp'] {
[Rebroadcast Plugin]:   errno: -2,
[Rebroadcast Plugin]:   code: 'ENOENT',
[Rebroadcast Plugin]:   syscall: 'rename',
[Rebroadcast Plugin]:   path: '/video/scrypted-37/1681524076405/1681531276414/1681531936414.rtsp',
[Rebroadcast Plugin]:   dest: '/video/scrypted-38/1681934801960/1681934801960/1681936542045.rtsp'
[Rebroadcast Plugin]: }

**Comment by SirBigBits** [comment]
![image](https://user-images.githubusercontent.com/129541321/233194201-28d83809-e1ae-4562-b383-74cf91b7138d.png)

See image,  Pending Results is not normal at the time it happens.

**Comment by SirBigBits** [comment]
Rebroadcast PLugin Logs at the same time:
[Back] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp' -> '/video/scrypted-65/1681936897849/1681936897849/1681937017853.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp',
  dest: '/video/scrypted-65/1681936897849/1681936897849/1681937017853.rtsp'
}
[Patio] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp' -> '/video/scrypted-63/1681936897812/1681936897812/1681937017821.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp',
  dest: '/video/scrypted-63/1681936897812/1681936897812/1681937017821.rtsp'
}
[Back] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp' -> '/video/scrypted-65.remote/1681936897851/1681936897851/1681937017859.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp',
  dest: '/video/scrypted-65.remote/1681936897851/1681936897851/1681937017859.rtsp'
}
[Patio] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp' -> '/video/scrypted-63.remote/1681936897814/1681936897814/1681937017834.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681538116415.rtsp',
  dest: '/video/scrypted-63.remote/1681936897814/1681936897814/1681937017834.rtsp'
}
[Back] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681538056413.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681538056413.rtsp' -> '/video/scrypted-65.low-resolution/1681936897852/1681936897852/1681937017861.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681538056413.rtsp',
  dest: '/video/scrypted-65.low-resolution/1681936897852/1681936897852/1681937017861.rtsp'
}
[driveway right] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp' -> '/video/scrypted-37.remote/1681936897794/1681936897794/1681937077801.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp',
  dest: '/video/scrypted-37.remote/1681936897794/1681936897794/1681937077801.rtsp'
}
[Back] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp' -> '/video/scrypted-65/1681936897849/1681936897849/1681937077854.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp',
  dest: '/video/scrypted-65/1681936897849/1681936897849/1681937077854.rtsp'
}
[Patio] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp' -> '/video/scrypted-63.remote/1681936897814/1681936897814/1681937077834.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp',
  dest: '/video/scrypted-63.remote/1681936897814/1681936897814/1681937077834.rtsp'
}
[Patio] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp' -> '/video/scrypted-63/1681936897812/1681936897812/1681937077821.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681537996412.rtsp',
  dest: '/video/scrypted-63/1681936897812/1681936897812/1681937077821.rtsp'
}
[Back] RTSP WRITE error during truncate file /video/scrypted-37/1681524076405/1681534936414/1681537936413.rtsp [Error: ENOENT: no such file or directory, rename '/video/scrypted-37/1681524076405/1681534936414/1681537936413.rtsp' -> '/video/scrypted-65.remote/1681936897851/1681936897851/1681937077914.rtsp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/video/scrypted-37/1681524076405/1681534936414/1681537936413.rtsp',
  dest: '/video/scrypted-65.remote/1681936897851/1681936897851/1681937077914.rtsp'

**Comment by SirBigBits** [comment]
Yes, but i've figured out if I go to the GEAR --> Versions --> and Reload, it fixes for that session.

**Comment by SirBigBits** [comment]
Koush.. I have Hikvision, Dahua, and one Amcrest (dahua, i know).  it happens on all them, so i don't think the issue is with the cameras.   I dont' know how many folks are using a Custom Domain setup behind an nginx reverse proxy, but that's when this issue started for me.

**Comment by koush** [comment]
this still an issue?

**Comment by SirBigBits** [comment]
No sir it is not. Thank you for your diligence.
