### ISSUE TITLE
Unifi Protect Smart Sensor exporting unused state to HomeKit

### ISSUE THREAD

**Issue by ohmantics** [koush/scrypted#750]
I have the leak and alarm sensors turned off. The plugin is still exporting them to HomeKit. HK then shows these states all the time. This is especially confusing for the alarm state as it appears by default as a contact sensor and is therefore visually indistinguishable from the door open sensor. (Until you open the door to figure it out and change the door one to be a door.)

It would be better to be able to either read the configuration from Protect and suppress the unused accessories or be able to toggle them in the Scrypted UI.

**Comment by ohmantics** [comment]
Alarm, humidity, light, motion, and temperature sensors all have an isEnabled flag. I don't see one for the leak sensor.

**Comment by koush** [comment]
use a device group to filter only the sensors you want.

**Comment by ohmantics** [comment]
Sorry, but I don't see how device groups helps here. A pointer to documentation would be great.
