### ISSUE TITLE
Auto Plugin Updates

### ISSUE THREAD

**Issue by ctrlcmdshft** [koush/scrypted#756]
The auto update plugins isnt working for me, not sure if it ever worked. Ive tried fresh install still not working. Is this an issue with anyone else?

**Comment by koush** [comment]
Known issue, will look at it shortly.

**Comment by koush** [comment]
can you screenshot your auto update plugins automation?

**Comment by koush** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/73924/234147317-ed4cb176-0a81-4f64-a94f-7dea7b382c96.png">

**Comment by ctrlcmdshft** [comment]
![firefox_1228](https://user-images.githubusercontent.com/61129128/234147668-31df045b-c8a3-498f-89b5-337601b5d7a5.jpg)
  no events anywhere

**Comment by koush** [comment]
click the events button, the middle button by console.

**Comment by ctrlcmdshft** [comment]
![image](https://user-images.githubusercontent.com/61129128/234152604-70b766b2-9bbd-4a1b-bfd1-c8dd6ef39642.png)

**Comment by ctrlcmdshft** [comment]
Closing as it is now working as intended.
