### ISSUE TITLE
Onvif buggy motion detection

### ISSUE THREAD

**Issue by ThisIsQasim** [koush/scrypted#758]
I have an onvif camera with buggy motion detection (at least buggy integration with HomeKit) so when a motion is detected the sensor keeps turning on and off. I saw that in the onvif plugin there is some implementation to handle this case https://github.com/koush/scrypted/blob/86042ec3fe646a046f6cfe995dcecf1e38ed66f3/plugins/onvif/src/main.ts#L262 but it isn't enabled by default. Would it be possible to make `MotionBuggy` option configurable along with the duration?

**Comment by koush** [comment]
use a dummy switch or automation or something to modify your motion sensor behavior.
