### ISSUE TITLE
I can't register for the cloud. What's wrong?

### ISSUE THREAD

**Issue by SpartanTech** [koush/scrypted#759]
I get this error when I use the scripted cloud plugin to register, I already registered by going to the website outside of the plug-in, but both registering and logging in within the plug gives me this error
![Screenshot_20230425_235203_Home Assistant](https://user-images.githubusercontent.com/3395163/234473058-d0bb640c-0e8f-42e2-b030-ebe1918bff3d.jpg)

**Comment by koush** [comment]
It looks like your browser is missing some crypto API for some reason? you running an adblocker?
