### ISSUE TITLE
ONVIF + HomeKit - stream loads, but very poor framerate

### ISSUE THREAD

**Issue by bdruth** [koush/scrypted#76]
Just getting started with `scrypted` - thx for all your work on this - been a long time homebridge user and this is just ... _wow_.

That said, I'm not seeing the same streaming behavior between scrypted and what I've had with my reolink & wyze cams from camera-ffmpeg, no transcoding. When loading the stream in the Home app, it's updating a frame every few to 10 seconds, maybe? The cameras have OSDs that show the time with second precision, so it's fairly easy to see that the stream isn't updating.

I'm running on a Pi 4 using the Docker Compose instructions. CPU isn't pegged while streaming or anything like that that I can see.

I'm using the ONVIF setup for both the Reolink and Wyze (via Dafang CFW). Happy to hack at this, as everything else hooked up _flawlessly_ - really impressed.

Anything I can try?

**Comment by koush** [comment]
hop on discord and I can help you out.

**Comment by koush** [comment]
my guess is that you're transcoding audio for some reason, and there's some syncing issues. you can try disabling audio on the camera in scrypted, and then reload the rebroadcast stream.

**Comment by koush** [comment]
Here's the setup for Wyze on Dafang: https://github.com/koush/scrypted/wiki/Wyze

**Comment by bdruth** [comment]
Haven't setup Discord on my new MBP, gimme a sec ...
