### ISSUE TITLE
Problem with opencv - ValueError: buffer is not large enought

### ISSUE THREAD

**Issue by aLAN-LDZ** [koush/scrypted#761]
Hi

i have this warning on console, maybe some of you know what to do with it:

[Video` Analysis Plugin]: Gstreamer + OpenCV Motion Detection
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 4000
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[Video Analysis Plugin]: Video Analysis ended with error [Traceback (most recent call last):
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 450, in handleMessage
[Video Analysis Plugin]:     value = await maybe_await(invoke(*args))
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 24, in maybe_await
[Video Analysis Plugin]:     return await value
[Video Analysis Plugin]:   File "/data/scrypted_data/plugins/@scrypted/opencv/zip/1-a3e678bdd423d7fe7bd6db13e465e67c.zip/detect/__init__.py", line 58, in generateObjectDetections
[Video Analysis Plugin]:     detected = await self.run_detection_videoframe(videoFrame, session)
[Video Analysis Plugin]:   File "/data/scrypted_data/plugins/@scrypted/opencv/zip/1-a3e678bdd423d7fe7bd6db13e465e67c.zip/opencv/__init__.py", line 249, in run_detection_videoframe
[Video Analysis Plugin]:     image = Image.frombuffer('L', (videoFrame.width, videoFrame.height), buffer)
[Video Analysis Plugin]:   File "/data/scrypted_data/plugins/@scrypted/opencv/python3.9-Linux-x86_64/lib/python3.9/site-packages/PIL/Image.py", line 2757, in frombuffer
[Video Analysis Plugin]:     im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
[Video Analysis Plugin]: ValueError: buffer is not large enough
[Video Analysis Plugin]: 
[Video Analysis Plugin]: cluster-server:@scrypted/objectdetector] {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: Video Analysis motion detection ended.
[Video Analysis Plugin]: Gstreamer + OpenCV Motion Detection

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/2609e301fe038633a216b7c1474ef4e7861630f8

**Comment by aLAN-LDZ** [comment]
@koush I'm very sorry to open it, but this fix means nothing to me. My stream is not gray it's standard RGB.
