### ISSUE TITLE
HomeKit sending main stream when away from home?

### ISSUE THREAD

**Issue by maxedmini** [koush/scrypted#768]
I have been having issues with unable to view camera live view in homekit when away from the home network it just shows loading, HKSV works most of the time and live view is perfect when on home network. After checking the logs it’s trying to send the main camera stream when trying to view from remote. I have set the sub stream to all the remote options in the camera setting but it always try’s to send the main stream. The only way to make it work is to set all streams to the sun stream then it works perfectly. 
Is there a way around this or a setting that’s incorrect 
Thanks

**Comment by koush** [comment]
Actually I know what's wrong.
Currently the method used to determine which stream to use is a best guess and only works when the remote connection is a cellular network. Being on remote wifi looks exactly the same as being on local wifi. The homekit plugin has no idea that the device is remote. Apple does not provide this information.

The adaptive bitrate feature in Scrypted NVR detects packet loss and automatically stiches/switches/transcodes streams to keep the stream up under all network conditions..

**Comment by nmcc1212** [comment]
when you say "Consider upgrading Scrypted" do you mean going from Scrypted to Scrypted NVR?

**Comment by lightingghost** [comment]
> Actually I know what's wrong. Currently the method used to determine which stream to use is a best guess and only works when the remote connection is a cellular network. Being on remote wifi looks exactly the same as being on local wifi. The homekit plugin has no idea that the device is remote. Apple does not provide this information.
> 
> The adaptive bitrate feature in Scrypted NVR detects packet loss and automatically stiches/switches/transcodes streams to keep the stream up under all network conditions. Consider upgrading Scrypted.

@koush Is the "adaptive bitrate" feature now available in Scrypted, or I have to purchase the Scrypted NVR plugin?
