### ISSUE TITLE
Reolink Camera Support Request

### ISSUE THREAD

**Issue by youngc01** [koush/scrypted#77]
Can you add rtmp support for 4K Reolink cams? They run in h265 rtsp, at 4k, which doesn’t work when I try to use. They also can run rtsp at 480. I would prefer a higher resolution than that. Do you have any suggestions? They also support 1080p, h264 over rtmp. I think this would be the best solution. There is a Reolink homeassistant plugin, that has all of these options implemented, maybe that could be a good base.

Thanks! Keep up the great work.

**Comment by koush** [comment]
Yes, I'll add general ffmpeg input support. Will try to get that done this weekend.

**Comment by youngc01** [comment]
@koush Awesome! Thanks. Have a nice weekend.

**Comment by youngc01** [comment]
@koush Hello thank you so much for creating ffmpeg plugin. I tried inputting my rtmp stream and it is not working. Here is my config in ffmpeg plugin on homebridge that works. Should I reformat the rtmp link for scrypted?

Thanks!

"name": "Sideyard",
                    "manufacturer": "Reolink",
                    "model": "RLC-410",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtmp://192.168.1.163/bcs/channel1_ext.bcs?channel=1&stream=1&user=admin&password=password -map 0 -an -dn -flags -global_header",
                        "stillImageSource": "-i http://192.168.1.163/cgi-bin/api.cgi?cmd=Snap&channel=1&rs=wuuPhkmUCeI9WG7C&user=admin&password=password”,
                        "maxStreams": 8,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 25,
                        "maxBitrate": 8192,
                        "forceMax": true,
                        "audio": true,
                        "debug": false

**Comment by koush** [comment]
can you join discord?
I think all you need is this:
`-i rtmp://192.168.1.163/bcs/channel1_ext.bcs?channel=1&stream=1&user=admin&password=password`

Though the rtmp url should also work in the rtsp plugin.
