### ISSUE TITLE
"502: Bad Gateway"

### ISSUE THREAD

**Issue by PabloGux** [koush/scrypted#781]
"Open Web UI" button results in a "502: Bad Gateway" server error all the time since the last update.

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Scrypted
Current version: 18-bullseye-full.s6-v0.12.0

I had two cameras configured and they are no longer producing HSV streams,

Log:
[CAM BY Patio] Video Analysis motion detection ended.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service avahi: stopping
s6-rc: info: service avahi successfully stopped
s6-rc: info: service dbus: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service dbus successfully stopped
s6-rc: info: service setup: stopping
s6-rc: info: service setup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
invalidating mixin 25 31
invalidating mixin 30 31
invalidating mixin 20 22
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 25 17
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 30 17
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 25 17
invalidating mixin 25 15
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 30 17
invalidating mixin 30 15

**Comment by PabloGux** [comment]
"Open Web UI" button results in a "502: Bad Gateway"  server error all the time since the last update.

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Scrypted
Current version: 18-bullseye-full.s6-v0.12.0

I had two cameras configured and they are no longer producing HSV streams,


Log: 
[CAM BY Patio] Video Analysis motion detection ended.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service avahi: stopping
s6-rc: info: service avahi successfully stopped
s6-rc: info: service dbus: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service dbus successfully stopped
s6-rc: info: service setup: stopping
s6-rc: info: service setup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
invalidating mixin 25 31
invalidating mixin 30 31
invalidating mixin 20 22
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 25 17
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 30 17
invalidating mixin 25 31
invalidating mixin 25 20
invalidating mixin 25 19
invalidating mixin 25 17
invalidating mixin 25 15
invalidating mixin 30 31
invalidating mixin 30 20
invalidating mixin 30 19
invalidating mixin 30 17
invalidating mixin 30 15

**Comment by koush** [comment]
take teh update? 
<img width="489" alt="image" src="https://github.com/koush/scrypted/assets/73924/f0af1d87-c491-4c29-a951-49897b907ace">

**Comment by PabloGux** [comment]
fixed with the update! for some reason it did not appear before. Thanks!
