### ISSUE TITLE
Rebroadcast restart causes stream to stall

### ISSUE THREAD

**Issue by AStoker** [koush/scrypted#782]
So, every day at 2am (docker time) the rebroadcast plugin restarts (https://github.com/koush/scrypted/blame/b49742204f0eb0e1a45fdd6eb16dcb497e581a74/plugins/prebuffer-mixin/src/main.ts#L1680). This causes active streams (like looking at the camera on a Google Hub) to freeze and completely stall out (it doesn't recover).

Our particular use of Scrypted is to have cameras as a baby monitor, so you can imagine that the camera suddenly not working anymore in the middle of the night is a bit of a pain.

I'm not sure the original reason why the restart was required. Locally testing it with the removed restart seems perfectly fine.
If the restart is required, it would be nice if we could at least set a configuration somewhere to determine when to restart. But in the mean time, come 2am every night, things just shut off.

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/909
