### ISSUE TITLE
Feature Request: variants for Home Assistant OS Addon for all docker tags?

### ISSUE THREAD

**Issue by ankushg** [koush/scrypted#785]
Would be great to get thin/lite/beta variants for he HA OS Addon :)

**Comment by koush** [comment]
No plans to do that. I'd rather work towards reducing the image size and getting dependencies on demand vs providing options that don't function with all plugins.

**Comment by koush** [comment]
It's straighforward now to point to a different docker tag though. The HA image is now simply the docker image.
