### ISSUE TITLE
Feature Request: Bind Audio from an external device to a camera within Scrypted

### ISSUE THREAD

**Issue by jerielsr** [koush/scrypted#789]
Feature Request for binding audio from an external source to a camera stream in Scrypted, to be passed to HomeKit. 

For example, setting up an ESP32 with a microphone, (not sure how to get it into Scrypted, but then link the audio from the ESP32 to a camera. Could this be done similarly to how Custom Motion Sensors / Custom Doorbells Buttons are linked to Camera for HomeKit?

**Comment by latel** [comment]
is it possible to implement two way audio this way using  ffmpeg camera?
