### ISSUE TITLE
Camera is using pcm_alaw audio. Enable Reencode Audio in Rebroadcast Settings Audio Configuration to suppress this alert.

### ISSUE THREAD

**Issue by codyc1515** [koush/scrypted#79]
I am getting this message

Camera is using pcm_alaw audio. Enable Reencode Audio in Rebroadcast Settings Audio Configuration to suppress this alert.

However when I go to the Rebroadcast Plugin there is no Audio Configuration or any configuration for that matter.

Where do I need to look for this setting?

**Comment by koush** [comment]
![Uploading image.png…]()

**Comment by koush** [comment]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/73924/144896913-970e9e83-176d-4d2c-b708-7ce641e01008.png">
