### ISSUE TITLE
Docker-Compose Automated Script completes in error

### ISSUE THREAD

**Issue by vmsman** [koush/scrypted#790]
In running the script in docker-compose, the installation completes with the following error on Ubuntu 22.04LTS Server instance.
```
[+] Running 2/3
 ✔ Network scrypted_default       Created                                                                         0.1s 
 ✔ Container scrypted-watchtower  Started                                                                        30.3s 
 ⠿ Container scrypted             Starting                                                                       30.3s 
Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory

```

Also, is there a documented method to changing the GUI Interface port number from 10443 to a user selected value?  Is there no interface for Hubitat users?  Is this meant as a replacement for Monocle-Gateway?   What is the recommended docker host configuration, since the installation fails on Ubuntu 22.04 LTS server with Docker?

**Comment by koush** [comment]
remove that line from the compose file, weird that it doesn't exist.

**Comment by gastonmorixe** [comment]
Same on rip 4

**Comment by viseshrp** [comment]
Same on an Intel Mac as well.
