### ISSUE TITLE
Tuya ip camera error 400 bad request on rtsp

### ISSUE THREAD

**Issue by blackwhitebear8** [koush/scrypted#791]
I want to connect my Tuya ip cameras to scrypted but they all seem to give back a rtsp 400 bad request error.
they are PEARL-Speed2S cams

this is what the console says:
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS SOME RTSP URL RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: 2023-05-13 23:11:15.545383098 +0000 UTC m=+165450.866295794
[Rebroadcast Plugin]: Public: [OPTIONS DESCRIBE SETUP TEARDOWN PLAY PAUSE RECORD GET_PARAMETER SET_PARAMETER]
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE SOME RTSP URL RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: 2023-05-13 23:11:15.55387986 +0000 UTC m=+165450.874792548
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="wework-2-eu.stream.iot-11.com", nonce="41ba1ae8c6dcc68e39c0461995083542"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE SOME RTSP URL RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="echo", realm="wework-2-eu.stream.iot-11.com", nonce="41ba1ae8c6dcc68e39c0461995083542", uri="SOME RTSP URL", algorithm="MD5", response="72bd95623f5fba56cfaec566cf696442"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: 2023-05-13 23:11:15.562342902 +0000 UTC m=+165450.883255642
[Rebroadcast Plugin]: Content-Base: SOME RTSP URL
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Content-Length: 560
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=- 1684019475503660 1 IN IP4 wework-2-eu.stream.iot-11.com
[Rebroadcast Plugin]: s=tuya stream
[Rebroadcast Plugin]: i=video stream
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: a=tool:Tuya stream media v1.0.0.1
[Rebroadcast Plugin]: a=type:broadcast
[Rebroadcast Plugin]: a=control:*
[Rebroadcast Plugin]: a=range:npt=0-
[Rebroadcast Plugin]: a=x-qt-text-nam:tuya stream
[Rebroadcast Plugin]: a=x-qt-text-inf:video stream
[Rebroadcast Plugin]: m=video 0 RTP/AVP 96
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: b=AS:500
[Rebroadcast Plugin]: a=rtpmap:96 H264/90000
[Rebroadcast Plugin]: a=cliprect:0,0,640,360
[Rebroadcast Plugin]: a=framesize:96 640-360
[Rebroadcast Plugin]: a=range:npt=now-
[Rebroadcast Plugin]: a=fmpt:96 packetization-mode=1;profile-level-id=42801E
[Rebroadcast Plugin]: a=control:track0
[Rebroadcast Plugin]: m=audio 0 RTP/AVP 97
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: a=rtpmap:97 PCMU/8000/1
[Rebroadcast Plugin]: a=range:npt=now-
[Rebroadcast Plugin]: a=control:track1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP SOME RTSP URL RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="echo", realm="wework-2-eu.stream.iot-11.com", nonce="41ba1ae8c6dcc68e39c0461995083542", uri="SOME RTSP URL", algorithm="MD5", response="86f56a82739afae8e4d182ccf378f8cc"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 400 Bad Request
[Rebroadcast Plugin]: Date: 2023-05-13 23:11:15.57439235 +0000 UTC m=+165450.895305042
[Rebroadcast Plugin]: Allow: [OPTIONS DESCRIBE SETUP TEARDOWN PLAY PAUSE RECORD GET_PARAMETER SET_PARAMETER]
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  TEARDOWN SOME RTSP URL RTSP/1.0
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Digest username="echo", realm="wework-2-eu.stream.iot-11.com", nonce="41ba1ae8c6dcc68e39c0461995083542", uri="SOME RTSP URL", algorithm="MD5", response="4708dff9bea7e3a2fe6cbd4c11728173"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session ended with error M [Error]: RTSP Error: RTSP/1.0 400 Bad Request
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:90015)
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at async t.RtspClient.setup (/@scrypted/prebuffer-mixin/main.nodejs.js:1:91026)
[Rebroadcast Plugin]:     at async P (/@scrypted/prebuffer-mixin/main.nodejs.js:1:142964)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143422)
[Rebroadcast Plugin]:     at async W.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:115783) {
[Rebroadcast Plugin]:   status: {
[Rebroadcast Plugin]:     line: 'RTSP/1.0 400 Bad Request',
[Rebroadcast Plugin]:     code: 400,
[Rebroadcast Plugin]:     version: 'RTSP/1.0',
[Rebroadcast Plugin]:     reason: 'Bad'
[Rebroadcast Plugin]:   }
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at TLSSocket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:141842)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:events:525:35)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at node:net:322:12
[Rebroadcast Plugin]:     at TCP.done (node:_tls_wrap:588:7)

Did i enter wrong tuya cloud credentials or? they seem to be the right ones tho.

**Comment by ChaoticBD** [comment]
have the same error.  tuya account connects well, got info about my camera and cant start my stream.
Device - Tuya wifi Ip box, all's ok while connecting by tuya app.

error with rebroadcast plugin: 
```
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsps://aws-tractor1.tuyaeu.com:443/v1/proxy/echo_show/209255c58dbe42ba9ac391f4bbd11364197f24e28b281a7f RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: cseq: 0
[Rebroadcast Plugin]: Public: DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, OPTIONS, ANNOUNCE, RECORD
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="aws-tractor1.tuyaeu.com",nonce="efaed15966a2dfa16da7d575b6c46bd5",opaque="ba546a0dd6058124dbea82b461a53895"stale=false,qop="auth",algorithm="MD5"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session ended with error t: E_MALFORMED_QUOTEDKEYVALUE (2, opaque="ba546a0dd6058124dbea82b461a53895"stale=false,qop="auth", 4): E_MALFORMED_QUOTEDKEYVALUE
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:4363
[Rebroadcast Plugin]:     at Array.map (<anonymous>)
[Rebroadcast Plugin]:     at t.parseHTTPHeadersQuotedKeyValueSet (/@scrypted/prebuffer-mixin/main.nodejs.js:1:4309)
[Rebroadcast Plugin]:     at t.RtspClient.createAuthorizationHeader (/@scrypted/prebuffer-mixin/main.nodejs.js:1:89058)
[Rebroadcast Plugin]:     at t.RtspClient.writeRequest (/@scrypted/prebuffer-mixin/main.nodejs.js:1:86806)
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:89745)
[Rebroadcast Plugin]:     at t.RtspClient.request (/@scrypted/prebuffer-mixin/main.nodejs.js:1:90137)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Rebroadcast Plugin]:     at async t.RtspClient.options (/@scrypted/prebuffer-mixin/main.nodejs.js:1:90236)
[Rebroadcast Plugin]:     at async t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:141921) {
[Rebroadcast Plugin]:   code: 'E_MALFORMED_QUOTEDKEYVALUE',
[Rebroadcast Plugin]:   params: [
[Rebroadcast Plugin]:     2,
[Rebroadcast Plugin]:     'opaque="ba546a0dd6058124dbea82b461a53895"stale=false,qop="auth"',
[Rebroadcast Plugin]:     4
[Rebroadcast Plugin]:   ],
[Rebroadcast Plugin]:   wrappedErrors: []
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at TLSSocket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:141761)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:events:525:35)
[Rebroadcast Plugin]:     at TLSSocket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at node:net:301:12
[Rebroadcast Plugin]:     at TCP.done (node:_tls_wrap:588:7)

```
and without it:
```
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: ice transport { ipv4: true, isPrivate: true, destinationId: '192.168.1.80' }
[WebRTC Plugin]: Connection is local network: true
[WebRTC Plugin]: done waiting ice connected
[RTC Connection Bridge]: Client Stream Profile {
[RTC Connection Bridge]:   transcodeBaseline: true,
[RTC Connection Bridge]:   sessionSupportsH264High: true,
[RTC Connection Bridge]:   maximumCompatibilityMode: true,
[RTC Connection Bridge]:   userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
[RTC Connection Bridge]:   capabilities: {
[RTC Connection Bridge]:     audio: { codecs: [Array], headerExtensions: [Array] },
[RTC Connection Bridge]:     video: { codecs: [Array], headerExtensions: [Array] }
[RTC Connection Bridge]:   },
[RTC Connection Bridge]:   screen: { devicePixelRatio: 1.125, width: 3072, height: 1728 }
[RTC Connection Bridge]: }
[RTC Connection Bridge]: video codec/container not matched, transcoding: undefined
[RTC Connection Bridge]: -hide_banner -rtsp_transport tcp -i rtsps:[REDACTED] -b:v 1000000 -bufsize 2000000 -maxrate 1000000 -r 15 -filter_complex scale='min(1280,iw)':-2 -profile:v baseline -preset ultrafast -g 60 -c:v libx264 -bf 0 -dn -sn -an -f rtp rtp://127.0.0.1:51205?pkt_size=1378 -acodec libopus -flags +global_header -ar 48k -b:a 40k -bufsize 96k -ac 2 -application lowdelay -dn -sn -vn -f rtp rtp://127.0.0.1:46501? -sdp_file pipe:4
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[RTC Connection Bridge]: ffmpeg exited
```

**Comment by blackwhitebear8** [comment]
the camera seems to work when i uninstall the rebroadcast plugin but then it is kinda useless as i cant intergrate it where i need it to.

**Comment by ChaoticBD** [comment]
> 

disable it on cam or uninstall from scrypted?

**Comment by blackwhitebear8** [comment]
i did completly uninstall it. i also noticed when setting the rtsp parser in the streams section to ffmpeg tcp that i will get a image not a stream? this image updates everytime i reopen the camera inside scripted.

**Comment by blackwhitebear8** [comment]
i added the transcoding extension. set stranscoding streams to local stream and decoder args to video4linux and now it seems to be working inside home assistant for me :).

**Comment by ChaoticBD** [comment]
i have only the black screen without picture after deleting rebroadcast

**Comment by lasharor** [comment]
I have the same issue with my Nest doorbell. Stopped working a couple of days ago. When I disable the rebroadcast plugin it seems to work. After I enable it again it doesnt work anymore.

**Comment by blackwhitebear8** [comment]
when i restart scrypted random cams give connection refused on rtsp streams they dont seem to want to work all at the same time no errors found in logs

**Comment by koush** [comment]
use ffmpeg tcp parser on rebroadcast

**Comment by ChaoticBD** [comment]
this response didnt help me - still see only the black screen but without any errors. perhaps its some specific feature/issue of camera
