### ISSUE TITLE
Feature Request: Auto switch between Management & Cameras

### ISSUE THREAD

**Issue by jtech007** [koush/scrypted#803]
Not sure of the functionality on other installs, but it would be more functional to automatically switch between the management console and the cameras when you click the Scrypted title in the top left corner of the window. Unless there are going to be other options added in the future that require the menu in between them, requiring another menu click for the only other option is redundant. Or have it as a user-definable option (slider, checkbox, etc.) if they want the social media links available to them instead of bookmarking them.

**Comment by koush** [comment]
Are you referring to the NVR?

**Comment by jtech007** [comment]
Hi Koush,

Yes. Going back to the login screen to switch between the two seems like an unneeded extra step, but maybe it's different on Windows or a Mac install? I'm using a docker instance on Unraid.

**Comment by koush** [comment]
Understood. Yes, the launcher can and does have other options available to be added to it. You can use the Add to Launcher extension to shortcuts.

**Comment by jtech007** [comment]
Ok, that makes sense. I didn't know about the extra functionality. Thanks!
