### ISSUE TITLE
How to use QuickSync?

### ISSUE THREAD

**Issue by Christofo** [koush/scrypted#81]
This is on a Synology DS920+ within Docker. I passed through the QuickSync encoder and executed the container with highest privileges. 

I need to transcode my cameras to work with HomeKit. I set the Encoder argument using the VAAPi preset:

`-c:v h264_vaapi -b:v ${request.video.max_bit_rate * 2}k`

Unfortunately this does not work. In the console output I see:

```
[HomeKit]: Unknown encoder 'h264_vaapi'
[HomeKit]: ffmpeg exited
```

I checked to make sure my QuickSync encoder is being seen within the docker container, it appears to be there:

```
root@scrypted:/# ls /dev/dri                                                                                                                                                  
card0  renderD128
```

I'm sure I'm just missing something simple here. Any suggestions?

**Comment by koush** [comment]
It may be that the ffmpeg I am including does not have h264_vaapi support compiled in. You can use the SCRYPTED_FFMPEG_PATH to point scrypted to your host ffmpeg binary. I'd suggest static compiling it.

**Comment by koush** [comment]
If you're within docker, you'll need to add another volume. Or, simply copy it to somewhere within the existing volume.

**Comment by koush** [comment]
I'd also suggest not encoding. Set your cameras to output to the proper h264 format.

**Comment by Christofo** [comment]
Thanks for the quick reply. I reconfigured my cameras so I don't have to encode. Coming from HomeBridge, i'm shocked at how fast Scrypted is. Thank you!
