### ISSUE TITLE
Memory usage climbing linearly, then resetting, after reset NVR events have disappeared

### ISSUE THREAD

**Issue by phindmarsh** [koush/scrypted#810]
I've just migrated my install from a Raspberry Pi 4 (2GB) to a VM hosted on Proxmox (with 8GB provisioned memory).

Its been up for a few days now and I noticed two things:
- Previously recorded NVR events seemed to be disappearing
- Memory usage seemed to be climbing linearly to just under the 8GB limit, then resetting down to 4GB or so, then climbing linearly again after an hour

After looking a bit closer it seems that the NVR events disappear right when the memory usage resets again. I have a camera that points at the road so the events are fairly frequent.

Any suggestions on what to monitor here to get more specifics on what might be happening?

<details><summary>Memory usage graph</summary>
<p>
<img width="970" alt="image" src="https://github.com/koush/scrypted/assets/344000/edb68f06-8e4e-41a4-b81d-4164e316d8c2">
</p>
</details> 

<details><summary>Process list from when usage is high</summary>
<p>

`ps aux --sort=-rss | numfmt --header --to=iec --field 5,6 --padding 6`

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      395986  1.9 12.5   2.1M   998K ?     Sl   08:11  14:22 python3 -u /server/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/python-codecs
root        7363  0.7  5.8    12M   465K ?     Sl   May18   9:43 node /server/node_modules/.bin/scrypted-serve
root        7396  1.2  5.5    12M   443K ?     Sl   May18  16:14 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/nvr
root      481279 22.8  3.7   1.8M   295K ?      Sl   14:00  91:32 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/prebuffer-mixin
root      537078 22.2  3.2   1.3M   256K ?      Sl   18:45  25:44 python3 -u /server/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/openvino
root      395951  0.3  2.4   1.4M   195K ?      Sl   08:11   2:51 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/webrtc
root        7395  0.4  2.3  1019K   190K ?      Sl   May18   5:58 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/homekit
root      395979  0.1  1.5   935K   120K ?       Sl   08:11   0:59 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/objectdetector
root      395968  0.0  1.4   810K   119K ?       Sl   08:11   0:45 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/snapshot
root        7374  0.1  1.4    11M   115K ?     Sl   May18   2:10 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/amcrest
root        7380  0.0  1.1    11M    93K ?      Sl   May18   0:18 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/cloud
root        7414  1.2  1.1   896K    89K ?        Sl   May18  16:31 python3 -u /server/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/opencv
root        7388  0.0  1.0   908K    82K ?        Sl   May18   0:35 /usr/bin/node /server/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/core
root         399  0.0  0.9   1.8M    78K ?       Ssl  May18   0:24 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      537079  0.1  0.7   449K    62K ?        Sl   18:45   0:07 python3 -u /server/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/tensorflow-lite
root        7351  0.0  0.5   706K    47K ?        Sl   May18   0:00 npm exec scrypted-serve
root         366  0.0  0.4   1.3M    39K ?       Ssl  May18   1:19 /usr/bin/containerd
root      585323  3.6  0.3    91K    24K ?        S    20:41   0:00 /server/node_modules/ffmpeg-static/ffmpeg -hide_banner -analyzeduration 0 -probesize 4346055 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp://127.0.0.1:41155/847d602e1cdb19f9 -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
root        6890  0.0  0.2   701K    18K ?        Ssl  May18   0:01 /watchtower --interval 3600 --cleanup --scope scrypted
root        7241  0.0  0.2   704K    17K ?        Sl   May18   0:09 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 142ff1b1f435a946de957b35bba5ebfbec7f76e1cf331c5e70252f90866bf559 -address /run/containerd/containerd.sock
root        6860  0.0  0.1   704K    16K ?        Sl   May18   0:03 /usr/bin/containerd-shim-runc-v2 -namespace moby -id a42fc4ad1cdd0dcff7f2c2bd1e2d269567b8cfeee53831f359d02a5beca6718b -address /run/containerd/containerd.sock
root         225  0.0  0.1    48K    15K ?        Ss   May18   0:00 /lib/systemd/systemd-journald
root        6836  0.0  0.1   1.2M    15K ?       Sl   May18   0:00 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 10444 -container-ip 172.18.0.2 -container-port 8080
root        6830  0.0  0.1   1.1M    13K ?       Sl   May18   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 10444 -container-ip 172.18.0.2 -container-port 8080
root      395994  0.0  0.1    15K    11K ?        S    08:12   0:00 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(15)
root           1  0.0  0.1    97K   9.5K ?        Ss   May18   0:01 /sbin/init
```

</p>
</details> 

<details><summary>Install details</summary>
<p>

Running on Debian 11 VM using docker-compose installer instructions from wiki, with database migrated from the Pi install (which was using Docker managed by Portainer).

- Scrypted version: 0.7.97
- 4x amcrest cameras
- NVR 
- Homekit

  | Name | Version | Plugin Package | PID
-- | -- | -- | -- | --
  | Amcrest Plugin | 0.0.122 | @scrypted/amcrest | 108
  | HomeKit | 1.2.25 | @scrypted/homekit | 129
  | OpenCV Motion Detection | 0.0.81 | @scrypted/opencv | 148
  | OpenVINO Object Detection | 0.1.18 | @scrypted/openvino | 526412
  | Python Codecs | 0.1.57 | @scrypted/python-codecs | 387047
  | Rebroadcast Plugin | 0.9.90 | @scrypted/prebuffer-mixin | 471326
  | Scrypted Cloud | 0.1.14 | @scrypted/cloud | 114
  | Scrypted Core | 0.1.128 | @scrypted/core | 122
  | Scrypted NVR | 0.1.145 | @scrypted/nvr | 130
  | Snapshot Plugin | 0.0.55 | @scrypted/snapshot | 387029
  | Tensorflow Lite Object Detection | 0.1.15 | @scrypted/tensorflow-lite | 526413
  | Video Analysis Plugin | 0.0.140 | @scrypted/objectdetector | 387040
  | WebRTC Plugin | 0.1.46 | @scrypted/webrtc | 387012

</p>
</details>

**Comment by koush** [comment]
Can you hop on Discord? I suspect this is due to the NVR volume having insufficient space or not being mapped properly.

**Comment by koush** [comment]
The memory usage thing is normal reporting by proxmox (and inaccurate since that's checking VM allocation and not VM usage). I do not think that is related.

**Comment by phindmarsh** [comment]
This turned out to be a big case of user error - when I migrated installs I didn't update the path the NVR storage is written to. This meant that the NVR was actually writing to a path within the container, which was only 30GB of space.
