### ISSUE TITLE
Alexa Integration not working

### ISSUE THREAD

**Issue by mjcocat** [koush/scrypted#811]
I am unable to get Alexa integration to work. I've setup Scrypted Cloud and the Alexa Skill. I am able to see the devices within Alexa, but unable start a video stream (from the app or Echo devices).

Scrypted Cloud:
`########################
5/19/2023, 5:33:06 PM
########################
Mapped port https://127.0.0.1:38232 to https://73.73.161.201:0
########################
5/19/2023, 5:46:54 PM
########################
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7oPw
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7oaN&sid=Ub_TcC5Z3vnhqioiAAAH
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7ogj&sid=Ub_TcC5Z3vnhqioiAAAH
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7o-b
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7p54&sid=KUeUOL_NIvACa-MkAAAI
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7pB4&sid=KUeUOL_NIvACa-MkAAAI
127.0.0.1 /web/component/alexa/endpoint
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.i (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.i (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.i (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
scrypted server connection ended: 7xpeblr847m
registered {
  success: true,
  sender_id: '827888101440',
  registration_id: 'dre0uqkuzus:APA9XXXXXh5C93st7PT6hg9qIt4tqk0z-zD93AQxUXXXXXXK1bOyJuy24bvaMeBSH4J4ZlhCssfsfsffmiPX9PIvf1pkqfFlUXR8YbzM0LxDmNeyXXXXKsbWmCCsO-u0TZWTSV4--H1pG',
  ip_address: '73.73.161.201'
}
scrypted server requested a connection: 0onqwb94a498
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7x_A
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7x_I
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/44/?EIO=4&transport=polling&t=OWr7x_E
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7y4y&sid=DsDaaKtNdB_auhkVAAAJ
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7y7_&sid=-w9Rbr8dds272040AAAK
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/44/?EIO=4&transport=polling&t=OWr7y8_&sid=lHVpzddxwcg6jizSgAAAL
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7yBV&sid=DsDG7dtNdB_auhkVAAAJ
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWr7yDO&sid=-w9Rbr8shs272040AAAK
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/44/?EIO=4&transport=polling&t=OWr7yFK&sid=lHVddHxwcg6jizSgAAAL
127.0.0.1 /web/component/alexa/endpoint
`

And from Alexa:

`received directive from alexa Alexa.RTCSessionController/InitiateSessionWithOffer {
  directive: {
    header: {
      messageId: '0667e572-45fa-40a0-b3bf-cb0fd07885dc',
      namespace: 'Alexa.RTCSessionController',
      name: 'InitiateSessionWithOffer',
      payloadVersion: '3',
      correlationToken: 'SUdTVEs6AAE6AAg6eyJpZCI6IjI0MzZkODc2LTEwOTctNDk3OS04YzEwLWY1MTY1MzI0MGVmMCIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLW5hLXAtNWE0LTQ2ODZmZDXlksjflsjflsjflsjSLFb24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiIxZjgxY2I2Zi02YmUyLTQ2ZTMtYmQ5MC00OTVjNmI4NDM5ZTIifQ=='
    },
    endpoint: { scope: [Object], endpointId: '43', cookie: {} },
    payload: {
      sessionId: 'b1d88cfd-3705-4916-acb2-a94b0b433d0d',
      offer: [Object]
    }
  }
}
response to alexa directive 200 {
  event: {
    header: {
      messageId: 'f31ba8f9-bfb7-43e6-8629-c207cbb066b0',
      namespace: 'Alexa.RTCSessionController',
      name: 'AnswerGeneratedForSession',
      payloadVersion: '3',
      correlationToken: 'SUdTVEs6AAE6AAg6eyJpZCI6IjI0MzZkODc2LTEwOTctNDk3OS04YzEwLWY1MTY1MzI0MGVmMCIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLW5hLXAtNWE0LTQ2ODZmZDXlksjflsjflsjflsjSLFb24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiIxZjgxY2I2Zi02YmUyLTQ2ZTMtYmQ5MC00OTVjNmI4NDM5ZTIifQ=='
    },
    endpoint: { scope: [Object], endpointId: '43', cookie: {} },
    payload: {
      sessionId: 'b1d88cfd-3705-4916-acb2-a94b0b433d0d',
      offer: [Object],
      answer: [Object]
    }
  },
  context: undefined
}
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: '5ffdac98-8ded-4a6c-b82f-44c9287eea63',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '39', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
undefined
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: '064b9dee-fcdd-4283-821a-a1aa832999ba',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '42', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
undefined
`

The Alexa endpoint shows as "undefined". I am not doing upnp or port forwarding.

**Comment by koush** [comment]
Where are you located?

**Comment by mjcocat** [comment]
United States / Illinois

**Comment by koush** [comment]
delete/reinstall the plugin update and see if it resolves.

**Comment by mjcocat** [comment]
Just to confirm, Alexa plugin, or Scrypted Cloud?

**Comment by mjcocat** [comment]
I reinstalled the Alexa plugin, I now show "api.amazonalexa.com" in the Alexa endpoint, but I am still unable to interact with the cameras. For example, I get "hmm, the camera is not responding" from an echo show. All of my cameras do show up in the Alexa app.

`linux x64 #42962 SMP Sat Apr 8 00:14:24 CST 2023
server version: 0.7.97
plugin version: @scrypted/alexa 0.2.5
full
########################
5/19/2023, 8:19:03 PM
########################
node modules /server/volume/plugins/@scrypted/alexa/node18-linux-x64-20230329
plugin loaded
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: '39636f10-295d-4c44-8319-fed3cc609fa9',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '43', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
received directive from alexa Alexa.RTCSessionController/InitiateSessionWithOffer {
  directive: {
    header: {
      messageId: '724cb897-4652-464f-a995-a895a2fa70de',
      namespace: 'Alexa.RTCSessionController',
      name: 'InitiateSessionWithOffer',
      payloadVersion: '3',
      correlationToken: 'SUdTVEs6AAE6AAg6eyJpZCI6ImRkNjFlMzhhLWZmMmEtNGI5Mi1hYmYyLTE4OTg4NDM2YmJjZCIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLW5hLXAtNWYyLTc4ZjcwYTc3Ld9ak22tMS5hbWF6b24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiI4OGU1MTJlYS1mZDRmLTQwZDItYTk5OS0yNjVkZWVjNDg0MjAifQ=='
    },
    endpoint: { scope: [Object], endpointId: '42', cookie: {} },
    payload: {
      sessionId: 'd09036c0-1c27-4f7b-82e3-8733d08bcfcf',
      offer: [Object]
    }
  }
}
response to alexa directive 200 {
  event: {
    header: {
      messageId: 'cd143e33-1173-4b59-a6a0-5156bcf5bd2b',
      namespace: 'Alexa.RTCSessionController',
      name: 'AnswerGeneratedForSession',
      payloadVersion: '3',
      correlationToken: 'SUdTVEs6AAE6AAg6eyJpZCI6ImRkNjFlMzhhLWZmMmEtNGI5Mi1hYmYyLTE4OTg4NDM2YmJjZCIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLW5hLXAtNWYyLTc4ZjcwYTc3Ld9ak22tMS5hbWF6b24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiI4OGU1MTJlYS1mZDRmLTQwZDItYTk5OS0yNjVkZWVjNDg0MjAifQ=='
    },
    endpoint: { scope: [Object], endpointId: '42', cookie: {} },
    payload: {
      sessionId: 'd09036c0-1c27-4f7b-82e3-8733d08bcfcf',
      offer: [Object],
      answer: [Object]
    }
  },
  context: undefined
}
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: 'af75ad9a-90c8-4c05-a650-2456f2c1777e',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '39', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: '0ddc4ff2-d102-4f13-8afa-33f754828542',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '42', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
event MotionSensor motionDetected Camera
send event to alexa {
  event: {
    header: {
      messageId: 'ceb7f74e-9243-4156-8a0f-d65797a80dfb',
      namespace: 'Alexa',
      name: 'ChangeReport',
      payloadVersion: '3'
    },
    endpoint: { endpointId: '43', scope: [Object] },
    payload: { change: [Object] }
  },
  context: { properties: [ [Object] ] }
}
`

====


########################
5/19/2023, 8:24:28 PM
########################
127.0.0.1 /web/component/alexa/endpoint
127.0.0.1 /web/component/alexa/endpoint
127.0.0.1 /web/component/alexa/endpoint
127.0.0.1 /web/component/alexa/endpoint
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/47/?EIO=4&transport=polling&t=OWriiSb
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/47/?EIO=4&transport=polling&t=OWriif2&sid=d9X0P5ScELIKO-zMAAcf
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/47/?EIO=4&transport=polling&t=OWriikr&sid=d9X0P5ScELIKO-zMAAcf
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWrikKS
127.0.0.1 /endpoint/@scrypted/core/engine.io/console/45/?EIO=4&transport=polling&t=OWrikQZ&sid=AUDUMVJex2sj-IkZAAcg
127.0.0.1 /web/component/Alexa/endpoint


BTW, thanks for the great software and the help here :)

**Comment by mjcocat** [comment]
BTW, this is a Docker implementation with the network set to "host" if that matters.

**Comment by MatiasLGonzalez** [comment]
I'm also facing this issue, using Scrypted Home Assistant Addon

**Comment by mjcocat** [comment]
FWIW, I was having issues with Scrypted Cloud, Monocle and the native Amcrest skill. I decided to focus my efforts on Monocle and after some extensive testing what I came to realize was the resolution on my main stream (which I had configured in Monocle) was too high. Once I set it to 1920x1080 (on a sub stream) and configured Monocle for the sub stream, it began working again. I'm assuming resolution was the issue on Scrypted Cloud and Amcrest Cloud too, but haven't confirmed.

**Comment by nberardi** [comment]
I am getting the same issue as well not.  The `Scrypted Cloud` has stopped forwarding requests for me.

**Comment by nberardi** [comment]
I restarted my raspberry pi, and it resolved the issue.  It appears the port on mine wasn't being released properly across restarts.

`
node modules /server/volume/plugins/@scrypted/cloud/node18-linux-arm64-20230329
plugin loaded
unhandledRejection Error: listen EADDRINUSE: address already in use 0.0.0.0:35709
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 35709
}
`
