### ISSUE TITLE
Tag images with compatible versioning for automation tools

### ISSUE THREAD

**Issue by onedr0p** [koush/scrypted#818]
Hi 👋🏼 

Scrypted currently using the  tagging scheme of `<nodejs-version>-<debian-release-name>-<type>-<version>` for docker tags.

I am wondering if this can be changed to something like:

`<version>-<debian-release-name>-<type>` so for example `v0.13.4-bookworm-full`. This is very close to semver style versioning with helps with automation. I am not sure how important the nodejs version is to include in the tagging scheme? Seems a bit verbose for the tags. Another option is to also just tag it in a semver compliant way e.g. `v0.13.4` and leave off the additional suffixes if you come to a standard on a single type of image

The main reason I am asking for this is that tools like [Renovate](https://github.com/renovatebot/renovate) or [Diun](https://github.com/crazy-max/diun) work a lot better for automating updating images in people Kubernetes clusters or docker-compose setups.

**Comment by jahanson** [comment]
I had been struggling with this for the past month and Renovate not updating this automatically anymore. It would make sense to take off the node version since we really don't have an option to switch versions anymore. If we make this more standard it'd make a lot more sense on what's going on without having to be read in to the custom versioning scheme.

**Comment by doonga** [comment]
This would be a welcome change. I'm also using Renovate for upgrades and having a more simple tag would ease setting up matching criteria for detecting version changes.

**Comment by koush** [comment]
v0.100.1-20-jammy-nvidia
v0.100.1-20-jammy-lite
v0.100.1-20-jammy-full

**Comment by koush** [comment]
v0.100.1-jammy-nvidia

v0.100.1-jammy-full

v0.100.1-jammy-lite
