### ISSUE TITLE
Update Home Assistant add-on for new releases

### ISSUE THREAD

**Issue by jsclayton** [koush/scrypted#819]
Since switching over to this official add-on from the [original](https://github.com/aegjoyce/ha-addons), I keep seeing Scrypted versions get higher while the add-on version stays the same. It looks like they had a Github automation to increment the version in `config.yaml` so that HA sees the update when it's pushed to the container registry. 

Could this repo add something similar? Thanks!

**Comment by koush** [comment]
The releases won't be in lock step across platform. I'll be disabling the notification in HA.
