### ISSUE TITLE
UniFi video stream stalls but audio stream continues on Google Home

### ISSUE THREAD

**Issue by anstosa** [koush/scrypted#822]
I have a persistent issue with long-running video streams on Google Home displays. Usually after at least an hour, the video will freeze but I'll still hear the audio. The video can only be recovered by re-triggering the stream.

**Version:** `0.23.0`

**Comment by koush** [comment]
probably a google home or connectivity issue. I run mine for hours at a time with no problems.

**Comment by hansenc0705** [comment]
I notice this issue as well on Google Home. You can still hear the Audio Stream but the video is frozen.
