### ISSUE TITLE
Rebroadcast audio codec prevents HomeKit recording, streaming works fine

### ISSUE THREAD

**Issue by maisun** [koush/scrypted#826]
Hi,

I noticed HomeKit recording stops working since a couple of weeks ago, I looked into the log and saw the error “Codec 'pcm_mulaw' (65542) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018) ”. 
However it only affects HomeKit recording, streaming (both local and remote) works flawlessly, and recording used to work without issue. In Scrypted I can see rebroadcast detect audio codec pcm_mulaw. I know aac works best but for some reason all my Hikvision cameras refuse to use aac codec.  
Initially I thought it was HomeKit issue, today I tried to downgrade Rebroadcast to lower versions, and I found the issue was introduced after 0.9.81 - with 0.9.81 recording works without any issue. 
Could it be a bug?

**Comment by koush** [comment]
check beta rebroadcast plugin

**Comment by maisun** [comment]
> check beta rebroadcast plugin

Hi @koush : thank you and I have tried robroadcast version 0.9.91 (latest beta), but looks like the same issue. Rollback to 0.9.81 it works again. The complete recording log in the console is attached:

`[Rebroadcast Plugin]: Selected stream Stream 2
[Rebroadcast Plugin]: sending prebuffer 10000
[HomeKit]: motion recording starting
[HomeKit]: -hide_banner -analyzeduration 0 -probesize 2170372 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
[HomeKit]: motion recording started
[Rebroadcast Plugin]: Stream 2 active rebroadcast clients: 1
[HomeKit]: Guessed Channel Layout for Input Stream #0.1 : mono
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:40029/9ddb70ed963a95a2':
[HomeKit]:   Metadata:
[HomeKit]:     title           : Media Presentation
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: N/A
[HomeKit]: Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1280x720, 25 fps, 25 tbr, 90k tbn
[HomeKit]:   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[HomeKit]: [aac_adtstoasc @ 0x63c5180] Codec 'pcm_mulaw' (65542) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018) 
[HomeKit]: Error initializing bitstream filter: aac_adtstoasc
[HomeKit]: Error initializing output stream 0:1 -- 
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (copy)
[HomeKit]:   Stream #0:1 -> #0:1 (copy)
[HomeKit]: Last message repeated 1 times
[Rebroadcast Plugin]: Stream 2 active rebroadcast clients: 0
[HomeKit]: motion recording completed Error
[HomeKit]: ffmpeg exited`

**Comment by koush** [comment]
published another beta, check again

**Comment by maisun** [comment]
> published another beta, check again

Hi @koush sorry to report 0.9.92 has exactly the same problem.

**Comment by koush** [comment]
new log please. it doesn't use the filter at all anymore in that new plugin.

**Comment by koush** [comment]
Get me a screenshot of your stream codecs too.

**Comment by maisun** [comment]
Hi @koush : sorry my bad after restarting the container it now works - I can confirm 0.9.92 fixes the issue.
