### ISSUE TITLE
pi camv2 ffmpeg command 

### ISSUE THREAD

**Issue by benmkw** [koush/scrypted#83]
I'm running a stock pi, with docker and original pi cam v2,

docker-compose
```yaml
version: '3.5'

services:
    scrypted:
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        network_mode: host
        volumes:
            - ~/.scrypted/volume:/server/volume
        devices:
            - /dev/video0:/dev/video0
```

ffmpeg arg `-f video4linux2 -input_format h264 -framerate 30 -i /dev/video0`

and get 

```
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -f video4linux2 -input_format h264 -framerate 30 -i /dev/video0 -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 tcp://127.0.0.1:18236 -vcodec copy -an -f mpegts tcp://127.0.0.1:26652
[Rebroadcast Plugin]: [video4linux2,v4l2 @ 0x253e5a0] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
[Rebroadcast Plugin]: /dev/video0: Invalid argument
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: killed
[Rebroadcast Plugin]:     at ChildProcess.O (/common/src/ffmpeg-rebroadcast.ts:110:34)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:402:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:475:12)
[Rebroadcast Plugin]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

only using `-i /dev/video0` results in 
```
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i /dev/video0 -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 tcp://127.0.0.1:36384 -vcodec copy -an -f mpegts tcp://127.0.0.1:13796
[Rebroadcast Plugin]: [video4linux2,v4l2 @ 0x2b8f550] ioctl(VIDIOC_G_PARM): Inappropriate ioctl for device
[Rebroadcast Plugin]: [video4linux2,v4l2 @ 0x2b8f550] Time per frame unknown
[Rebroadcast Plugin]: [video4linux2,v4l2 @ 0x2b8f550] Dequeued v4l2 buffer contains 8121344 bytes, but 8081920 were expected. Flags: 0x00002001.
[Rebroadcast Plugin]: Last message repeated 20 times
[Rebroadcast Plugin]: Input #0, video4linux2,v4l2, from '/dev/video0':
[Rebroadcast Plugin]:   Duration: N/A, start: 824.237233, bitrate: N/A
[Rebroadcast Plugin]: Stream #0:0: Video: rawvideo ([186]RG[8] / 0x84752BA), bayer_rggb8, 3280x2464,
[Rebroadcast Plugin]: 15 tbr, 1000k tbn, 1000k tbc
[Rebroadcast Plugin]: [mp4 @ 0x2b91f20] Could not find tag for codec rawvideo in stream #0, codec not currently supported in container
[Rebroadcast Plugin]: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
[Rebroadcast Plugin]: Stream mapping:
[Rebroadcast Plugin]:   Stream #0:0 -> #0:0 (copy)
[Rebroadcast Plugin]:   Stream #0:0 -> #1:0 (copy)
[Rebroadcast Plugin]: ok!
[Rebroadcast Plugin]: no audio detected.
[Rebroadcast Plugin]: video codec is not h264. If there are errors, try changing your camera's encoder output.
[Rebroadcast Plugin]: rebroadcast parse error Error: stream ended during read for minimum 8 bytes
```

The output of the pi cam needs to be converted to h264 as I understand but I did not find a way to do so for this project yet.

I'm wondering if it would be easier to use [libcamera](https://www.raspberrypi.com/documentation/accessories/camera.html#libcamera-vid) directly (e.g. [this](https://www.raspberrypi.com/documentation/accessories/camera.html#tcp) command works for streaming video) but did not find a mention of it in this project or an example of running the pi cam with ffmpeg.

**Comment by koush** [comment]
You won't be able to use the pi cam with rebroadcast. If you disable rebroadcast, the web dashboard and homekit (with transcoding enabled) should work.

**Comment by benmkw** [comment]
Ok I uninstalled rebroadcast but still fail to see how I can advise ffmpeg to acquire the video from /dev/video0 with the appropriate encoding, unfortunately libcamera-vid is not available in docker or else i would do something roughly like ffmpeg "$(libcamera-vid --code h264)".

If there isn't an obvious mistake/ solution I'll close this issue as it is more ffmpeg/ pi specific and probably out of scope for this repo.

**Comment by koush** [comment]
You can mount additional volumes into docker to do advanced stuff like this.

**Comment by benmkw** [comment]
for others to follow, I got this to work by installing the gstreamer plugin https://www.npmjs.com/package/@scrypted/gstreamer-camera and by using `libcamerasrc ! video/x-raw,framerate=(fraction)30/1, width=(int)1280, height=(int)960, interlace-mode=(string)progressive, colorimetry=(string)bt709,format=I420 ! v4l2convert name=videoconvert ! v4l2h264enc name=enc extra-controls=controls,video_bitrate=2000000,repeat_sequence_header=1 ! video/x-h264,profile=high,level=(string)4.2 ! h264parse` (from discord) and by installing `gstreamer1.0-libcamera` and installing scrypted without docker using the `scrypted/install/local/install-scrypted-dependencies-linux.sh` script
