### ISSUE TITLE
[Home Assistant OS] Scrypted is slow and crashes after a few minutes

### ISSUE THREAD

**Issue by ruudk** [koush/scrypted#837]
I'm not sure what's going wrong. I followed the [installation guide](https://github.com/koush/scrypted/wiki/Installation:-Home-Assistant-OS) and enabled the Homekit and Unifi integrations. The camera shows up in the Unifi plugin, not in Homekit.

After a few seconds/minutes, everything becomes extremely slow and eventually the add-on crashes. When I go to the Add-On overview and click the `Logs` tab I can only see the last ±40 lines. 

Sometimes my Home Assistant instance is completely frozen and I have to power cycle my Raspberry Pi 4 CM completely .

What's the best way to debug this?

**Comment by koush** [comment]
Probably low memory or HAOS issue or something. Works fine on normal PI on docker.

**Comment by ruudk** [comment]
So, we don't want to solve the issue or find out what causes it? We just assume it's low memory or HAOS issue... ok.....
