### ISSUE TITLE
Log in section not appearing 

### ISSUE THREAD

**Issue by balboafer** [koush/scrypted#839]
Hi! I’ve just installed the Arlo plug-in in scrypted but I’m not able to find the arlo account login section, but it sends me this error message in the console:
linux arm64 #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
server version: 0.23.0
plugin version: @scrypted/arlo 0.7.25
########################
01/06/2023, 17:12:20
########################
python version: python3.9
python prefix: /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64
Removing old dependencies: /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64
requirements.txt (outdated)
paho-mqtt==1.6.1
sseclient==0.0.22
aiohttp==3.8.4
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.1.1
cloudscraper==1.2.71
cryptography==38.0.4
async-timeout==4.0.2
--extra-index-url=https://www.piwheels.org/simple/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
/usr/bin/python3: No module named pip
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/home/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/home/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 617, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1

I’m kind of a newbie in this, so I’ll appreciate any help. 
I’m using raspberry pi4 with pi os 64 lite and scrypted.

**Comment by bjia56** [comment]
Your machine doesn't have python3 pip installed. I highly recommend uninstalling the local scrypted and use the Docker install instructions instead. Or, if you need to keep the local install, install a package such as python3-pip from your package manager

**Comment by balboafer** [comment]
Thank you for the fast response!! With package manager you mean from scrypted or where can I find it? Thank you again.

**Comment by bjia56** [comment]
`sudo apt install python3-pip`

**Comment by balboafer** [comment]
did it, installed, but the issue persists; now this is in console:
linux arm64 #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
server version: 0.23.0
plugin version: @scrypted/arlo 0.7.25
########################
01/06/2023, 17:50:23
########################
python version: python3.9
python prefix: /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64
Removing old dependencies: /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64
requirements.txt (outdated)
paho-mqtt==1.6.1
sseclient==0.0.22
aiohttp==3.8.4
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.1.1
cloudscraper==1.2.71
cryptography==38.0.4
async-timeout==4.0.2
--extra-index-url=https://www.piwheels.org/simple/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple/, https://bjia56.github.io/scrypted-arlo-go/
Collecting paho-mqtt==1.6.1
  Using cached https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-1.6.1-py3-none-any.whl (75 kB)
Collecting sseclient==0.0.22
  Using cached https://www.piwheels.org/simple/sseclient/sseclient-0.0.22-py3-none-any.whl (4.4 kB)
Collecting aiohttp==3.8.4
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.0 MB)
Collecting requests==2.28.2
  Downloading https://www.piwheels.org/simple/requests/requests-2.28.2-py3-none-any.whl (62 kB)
Collecting cachetools==5.3.0
  Downloading https://www.piwheels.org/simple/cachetools/cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting scrypted-arlo-go==0.1.1
  Downloading https://github.com/bjia56/scrypted-arlo-go/releases/download/v0.1.1/scrypted_arlo_go-0.1.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.8 MB)
Collecting cloudscraper==1.2.71
  Downloading https://www.piwheels.org/simple/cloudscraper/cloudscraper-1.2.71-py3-none-any.whl (99 kB)
Collecting cryptography==38.0.4
  Downloading cryptography-38.0.4-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
Collecting async-timeout==4.0.2
  Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
Collecting attrs>=17.3.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting aiosignal>=1.1.2
  Downloading https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (159 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (265 kB)
Collecting charset-normalizer<4.0,>=2.0
  Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (196 kB)
Collecting pyparsing>=2.4.7
  Downloading https://www.piwheels.org/simple/pyparsing/pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting requests-toolbelt>=0.9.1
  Downloading https://www.piwheels.org/simple/requests-toolbelt/requests_toolbelt-1.0.0-py2.py3-none-any.whl (51 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (448 kB)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/requirements.txt (line 4)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/requirements.txt (line 4)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from sseclient==0.0.22->-r /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/requirements.txt (line 2)) (1.16.0)
Collecting pycparser
  Downloading https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Installing collected packages: charset-normalizer, requests, pycparser, multidict, frozenlist, yarl, requests-toolbelt, pyparsing, cffi, attrs, async-timeout, aiosignal, sseclient, scrypted-arlo-go, paho-mqtt, cryptography, cloudscraper, cachetools, aiohttp
  WARNING: The script normalizer is installed in '/home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 cachetools-5.3.0 cffi-1.15.1 charset-normalizer-3.1.0 cloudscraper-1.2.71 cryptography-38.0.4 frozenlist-1.3.3 multidict-6.0.4 paho-mqtt-1.6.1 pycparser-2.21 pyparsing-3.0.9 requests-2.28.2 requests-toolbelt-1.0.0 scrypted-arlo-go-0.1.1 sseclient-0.0.22 yarl-1.9.2
pip install result 0
site-packages: /home/admin/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Linux-aarch64/lib/python3.9/site-packages
Setting plugin verbosity to Normal
Setting plugin transport to SSE

**Comment by bjia56** [comment]
That looks like the plugin loaded correctly. Anything different if you reload the page?

**Comment by balboafer** [comment]
Nop, still the same; i´ve unistalled the previous install, the restart scrypted and installed it again, but the issue persists.
Thank you.

**Comment by balboafer** [comment]
i think is enabled now, let's see...
