### ISSUE TITLE
Scrypted not listening locally on ipv4 on 5/22 docker image?

### ISSUE THREAD

**Issue by pcm1ke** [koush/scrypted#842]
Out of nowhere I can’t reach the scrypted web ui locally, despite the server ip being set to an ipv4 IP (192.168.2.6). If I check netstat port 10443 is only bound in ipv6 (which is not even used at my home). If it wasn’t for the cloud plug-in I wouldn’t be able to reach the web ui at all. I haven’t changed anything on my scrypted installation in months, but I do routinely update the stack in portainer. The latest image it’s using is from 5/22. How can I fix this issue so I don’t have to go through the cloud plug-in just to reach my scrypted installation locally?

Server 0.23.0, standard docker install just like the docs explain. 

Thanks in advance.

**Comment by koush** [comment]
The server listens on all addresses.

**Comment by pcm1ke** [comment]
It’s not binding to tcp4, only tcp6 and like I mentioned I haven’t changed anything?

**Comment by pcm1ke** [comment]
Sorry! I guess http:10080 got deprecated a long time ago and traefik was setup to connect there. I apologize!
