### ISSUE TITLE
Home Assistant: Can't login after initial setup - No Password

### ISSUE THREAD

**Issue by superpower10** [koush/scrypted#848]
I followed instructions and installed it in Home Assistant as an addon.

In Wiki it says user is "homeassistant" and configured with an random password. Great. 

### **_But where can I find this random password???_**

Its not in the LOG-File while booting.

**Comment by koush** [comment]
Access the add-on from the ingress url in the add-on page. No login is required.

**Comment by alsotoes** [comment]
Hi @koush, this issue shouldn't be closed, as the main question is unanswered.

This data is needed as the account administration redirects to 

https://<homeassistant_ip>l:10443/endpoint/@scrypted/core/public/#/device/41

And here, this data is needed.
-Alvaro

**Comment by koush** [comment]
you create a second admin user using automatic login. the automatic random password is inaccessible.
