### ISSUE TITLE
Nest Plugin not working

### ISSUE THREAD

**Issue by Jack123uk** [koush/scrypted#85]
Hey, just want to say a massive Thankyou for this platform, and been able to use HKSV.

Im trying to install the nest plugin but I keep getting an error. The plugin installs but cannot load. 
The error message is the console is this - 
starting plugin @scrypted/nest 0.0.13
failure loadZip TypeError: Cannot read properties of null (reading 'getData')
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:442:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:426:37)

If anyone can help that would be great.

Thanks

**Comment by koush** [comment]
The nest plugin is deprecated, since they deprecated that API. you want the google device access plugin.

**Comment by Jack123uk** [comment]
Thankyou @koush for your reply, really appreciate it.. I've install the Google device access plugin, but I can't seem to login. I also have Scrypted Cloud installed and logged in. 
is there any documentation on how to set up good device access plugin? 
Thanks
