### ISSUE TITLE
Ingress page not working after installation // Direct Access via port asks for credentials

### ISSUE THREAD

**Issue by FsxShader2012** [koush/scrypted#856]
Since #849 was closed without an actual solution i'm opening a new issue.

Using the direct link https://ip:10443 I now get a box asking for credentials, wich I don't have:

![image](https://github.com/koush/scrypted/assets/15424862/e57affcb-e48c-4325-beee-0ed5a782bb8c)

**Comment by koush** [comment]
as mentioned, this is a ha Ingress bug. I would try another browser. there is no account, because the ha ingress automatically logs in. you can only create the account from within the ingress, which you can't access.

**Comment by koush** [comment]
please do not open more issues. if you find a solution, post it on the previous issue. this is not a scrypted bug.

**Comment by FsxShader2012** [comment]
I found the problem. This is not a HA bug. The problem was my reverse nginx proxy. I had to define seperate locations for some of this add-ons ressources to get it to work.

For anyone also struggling with this issue, here's my nginx conf file:

```
    location / {
        proxy_pass http://My_IP:8123;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/websocket {
        proxy_pass http://My_IP:8123/api/websocket;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /endpoint/@scrypted {
        proxy_pass http://My_IP:8123/endpoint/@scrypted;
    }

    location /api/hassio_ingress/MkAFjI2mslGCB3Xa7Rca3QQic-t8C2Kcl2PnQArlg9k {
        proxy_pass http://My_IP:8123/api/hassio_ingress/MkAFjI2mslGCB3Xa7Rca3QQic-t8C2Kcl2PnQArlg9k;
    }
```
You must **only put the proxy_pass instructions** into these locations.
