### ISSUE TITLE
Tuya cloud camera not streaming

### ISSUE THREAD

**Issue by balboafer** [koush/scrypted#857]
Hello,

I have some experience with Scrypted already. I use it to integrate 1 ring doorbell, 2 ring cameras, 1 wyze v3 and 4 arlos into my HomeKit home. I was successfully able to integrate the Tuya into Scrypted, and how the Tuya camera is exposed to HomeKit and paired successfully, however the stream isn't working on the Scrypted management dashboard, or the Apple Home app. The stream is still working just fine in the Tuya app, so I know it isn't broken there. Any help would be appreciated it.

**Comment by koush** [comment]
use the ffmpeg tcp parser on the stream

**Comment by agborkowski** [comment]
yeah that works perfectly, w/o any additional configuration, just w8 little bit longer to ffmpeg starts transcoding and use snapshot ffmpeg prebuffer, I just worry about how to update the snapshot often

**Comment by balboafer** [comment]
Still not working; any thoughts?
