### ISSUE TITLE
Access image attachment from Mail (SMTP) Plugin?

### ISSUE THREAD

**Issue by gluedots** [koush/scrypted#86]
Thanks for the awesome project!

I've got a camera setup with the SMTP plugin to trigger a "doorbell" event in homekit and it's working great!
However, I believe my cam actually attaches an image to the email notification, is there any way to access and use that jpeg from the email attachment?

**Comment by koush** [comment]
homekit will request a snapshot from the camera or parse the video for a thumbnail, there's no way to make it use a specific image.
