### ISSUE TITLE
overlay error after latest update 0.39

### ISSUE THREAD

**Issue by gh0sti** [koush/scrypted#867]
/init: 37: exec: s6-overlay-suexec: Exec format error.

I used watchtower to update to latest build in portainer on my pi

**Comment by koush** [comment]
you're on pi buster I am guessing. need to be on bullseye. this has noted in the wiki for a year as a preinstall requirement.

**Comment by gh0sti** [comment]
I have been on bullseye

root@raspberrypi:/home/pi# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by gh0sti** [comment]
my pi is on 32bit though but I have scrypted running in portainer
