### ISSUE TITLE
Arlo Baby cameras - Always black screen

### ISSUE THREAD

**Issue by mikesalz** [koush/scrypted#872]
Are Arlo Baby cameras supported?  I have an Arlo base station with 3 cameras, and 2 separate Arlo Baby cameras.  The Arlo plugin pulls them all in to Scrypted.  The cameras connected to the base station work 100% correctly.  The Arlo Baby cameras load video clips, but live viewing is always a black screen.  Example below.

![image](https://github.com/koush/scrypted/assets/46855061/10f32ece-3a42-46b0-b062-87f62c1a7aea)

**Comment by bjia56** [comment]
It's possible that the arlo plugin is missing some events for the baby cameras. I recall they're set up slightly differently than others, but I don't actually have a baby camera to test.

Are you willing to share one with me so I can investigate and get it working? If so, I'd recommend setting one up in a storage area for privacy instead of one that's actually in a nursery.

**Comment by mikesalz** [comment]
Thanks for the quick response @bjia56 ! Sure, I can share one with you. What do you need me to do exactly?

**Comment by bjia56** [comment]
Actually before we get started on that, did you upgrade your Arlo account to use the new UI? You can tell by seeing if your first-party Arlo app shows a Dashboard tab on the bottom. Just wanted to check since sharing cameras can only be done for accounts on the same UI version -my accounts are all on the new UI so they won't successfully get requests sent from an account using the old UI.

**Comment by mikesalz** [comment]
Hmm... Based on your description I am still on the old UI.  And I wasn't presented with an option to upgrade...

![image](https://github.com/koush/scrypted/assets/46855061/fe16c76f-c4b1-449e-bcbf-16f94cc3d47d)

**Comment by bjia56** [comment]
If you're open to upgrading: https://community.arlo.com/t5/Arlo-Secure/Invited-friend-cannot-see-devices-on-their-dashboard-Arlo-Pro-2/m-p/1889396#M1813

Note that you will need to upgrade both your main account as well as the account you're using for Scrypted, otherwise the second account won't be able to see the cameras anymore. I've had mine running with the upgraded account and have seen no issues so it should be safe to do with regards to the Scrypted integration.

Once you've done that, please send an invite to share your camera to my email, with admin/manage permissions. My email can be found here: https://github.com/bjia56/scrypted-arlo-go/blob/master/scrypted_arlo_go/setup.py#L84

**Comment by mikesalz** [comment]
Well this is interesting.  It almost sounds like one of my Arlo Baby cameras is too old and not supported.  I'm a little afraid to upgrade because I don't want to lose that camera in the Arlo app.

![106406EF-F5C8-437D-AACB-20F3624A9A61](https://github.com/koush/scrypted/assets/46855061/8cd21693-7024-4d45-8bd6-a0d157110e2a)

**Comment by bjia56** [comment]
Hmm I see, ok no problem hold off on the upgrade for now. Let me see if I can find other unofficial documentation on the Arlo Baby cameras and guess what's missing.

**Comment by bjia56** [comment]
@mikesalz can you please try arlo plugin beta 0.7.32 and see if that works for the arlo baby? you'll need to install it via the plugin page's dropdown and select it individually since betas don't prompt for an upgrade

**Comment by mikesalz** [comment]
Hi @bjia56 - It looks like it is working!

**Comment by mikesalz** [comment]
I was able to add it to HomeKit, but I have a few observations:

- It is plugged in and fully charged, but it thinks the battery is 0%
- I have HomeKit configured to allow recording, but nothing is being recorded
- Video works, but there is no audio

**Comment by bjia56** [comment]
Great, that sounds like progress.
- The plugin doesn't really load new cameras' battery levels very well so it currently waits until Arlo sends an update before setting it. I'd say see if the battery stays at 0% overnight and if it's still there tomorrow, I can see if there's a different battery-related event for these cameras.
- Are motion events being delivered? You can check in the events tab (see below). I don't believe Homekit records 24/7, but only when there's an event trigger (and after it analyzes the stream to see if there's something worth recording).
- For missing audio, try enabling the Rebroadcast plugin and switch the parser to FFmpeg (TCP).

![image](https://github.com/koush/scrypted/assets/5090934/4a494346-8871-4f6f-bf60-e12892f81fef)

A few notes and recommendations:
- If you have the camera plugged in, an option is to tick the "Plugged In" checkbox and enable prebuffering on the camera (note it'll use extra internet bandwidth to stream it constantly through Arlo servers) - this should improve Homekit and streaming startup latency significantly. Once the battery level updates the prebuffer will start since it won't be active under 20%.
- Even without persistent streaming, the change I had to make to get video working is for the plugin to send keepalive heartbeats to the camera every minute or so (this is required by several other camera models as well). Unfortunately it means that the battery can drain a lot faster than if the camera is purely idle, but if you have it plugged in then it should be no problem.

**Comment by mikesalz** [comment]
Yes, definitely making progress! Responses below...


> * The plugin doesn't really load new cameras' battery levels very well so it currently waits until Arlo sends an update before setting it. I'd say see if the battery stays at 0% overnight and if it's still there tomorrow, I can see if there's a different battery-related event for these cameras.

I will check again tomorrow

> * Are motion events being delivered? You can check in the events tab (see below). 

Yes, I am seeing both motion and audio events, so that is promising.  

> I don't believe Homekit records 24/7, but only when there's an event trigger (and after it analyzes the stream to see if there's something worth recording).

You are correct - HomeKit does not record 24/7.  But it is configurable to record based on specific motions (people, pets, etc) or all motion.  I have it set to record on all motion. 

> * For missing audio, try enabling the Rebroadcast plugin and switch the parser to FFmpeg (TCP).

I added the Rebroadcast and enabled FFMpeg under HomeKit>RTP Sender.  Is this correct?  Still no sound, though.

> * If you have the camera plugged in, an option is to tick the "Plugged In" checkbox and enable prebuffering on the camera (note it'll use extra internet bandwidth to stream it constantly through Arlo servers) - this should improve Homekit and streaming startup latency significantly. Once the battery level updates the prebuffer will start since it won't be active under 20%.

Would this be Streams>Prebuffered Streams>Cloud RTSP?

> * Even without persistent streaming, the change I had to make to get video working is for the plugin to send keepalive heartbeats to the camera every minute or so (this is required by several other camera models as well). Unfortunately it means that the battery can drain a lot faster than if the camera is purely idle, but if you have it plugged in then it should be no problem.

Makes sense.  I have it plugged in so that's not an issue.

**Comment by bjia56** [comment]
> I added the Rebroadcast and enabled FFMpeg under HomeKit>RTP Sender. Is this correct? Still no sound, though.

Set RTSP parser here:
![image](https://github.com/koush/scrypted/assets/5090934/099ec9de-2abe-4054-9609-223a4107153a)

> Would this be Streams>Prebuffered Streams>Cloud RTSP?

Yep that's the one

**Comment by bjia56** [comment]
Unfortunately my troubleshooting skills for Homekit recording is very limited - if Scrypted is getting the motion/audio events, and able to pull the video stream, then Homekit should in theory be able to do the same to record.

**Comment by mikesalz** [comment]
Good news!  At some point last night after you helped me configure some changes, HomeKit Secure Video started recording.  I'm not sure which changes did it, but it works now. 

This morning I changed the RTSP Parser to FFmpeg, and now sound is working.

Also, the battery is at 100%.  So I think we are looking pretty good now!  Thanks again for all of your help!

**Comment by bjia56** [comment]
Great to hear!

**Comment by mikesalz** [comment]
I guess there is one more thing - The native HomeKit integration for that camera allows 2 way talk communication.  The Talk button is not showing up for the Scrypted Arlo Baby camera in HomeKit, but it does show up for the Arlo Base Station cameras.  Not a huge deal, but just wondering if you had any thoughts on that?

**Comment by bjia56** [comment]
Unfortunately two way audio for cameras not attached to a basestation is not yet fully working. Arlo uses a different protocol for basestation cameras and non-basestation cameras. I'm working on adding support for the non-basestation cameras but there's still some connectivity issues to resolve.

**Comment by mikesalz** [comment]
No worries.  That feature is pretty much at the bottom of my list.  Everything else is looking great so far!

**Comment by bjia56** [comment]
I'll also take a look at exposing the nightlight and sensor data into scrypted as well

**Comment by bjia56** [comment]
@mikesalz if you get the chance to help test, I just published 0.7.34 beta with the nightlight - can you verify if that shows up for you? it should show up as a separate scrypted device under the camera, but in homekit should be merged into the camera as a switch (similar to spotlights/floodlights on other arlo models)

**Comment by mikesalz** [comment]
Hi @bjia56 - I gave it a try, but all cameras fail to connect.  I tried restarting Scrypted twice, and they never came up.  When I reverted back to the current release, they started working again.

**Comment by bjia56** [comment]
Can you post what's in the console when the plugin starts up? There might be an error there. I probably made a mistake somewhere that's only showing up when there's an arlo baby in the list

**Comment by mikesalz** [comment]
Here it is...

> linux x64 #42962 SMP Mon May 29 14:38:23 CST 2023
> server version: 0.39.0
> plugin version: @scrypted/arlo 0.7.34
> full
> ########################
> 6/18/2023, 8:05:26 PM
> ########################
> python version: python3.10
> python prefix: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329
> Removing old dependencies: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329
> requirements.txt (outdated)
> paho-mqtt==1.6.1
> sseclient==0.0.22
> aiohttp==3.8.4
> requests==2.28.2
> cachetools==5.3.0
> scrypted-arlo-go==0.2.0
> cloudscraper==1.2.71
> async-timeout==4.0.2
> --extra-index-url=https://www.piwheels.org/simple/
> --extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
> --prefer-binary
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/, https://bjia56.github.io/scrypted-arlo-go/
> Collecting paho-mqtt==1.6.1 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 1))
>   Using cached https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-1.6.1-py3-none-any.whl (75 kB)
> Collecting sseclient==0.0.22 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 2))
>   Using cached https://www.piwheels.org/simple/sseclient/sseclient-0.0.22-py3-none-any.whl (4.4 kB)
> Collecting aiohttp==3.8.4 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
> Collecting requests==2.28.2 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 4))
>   Using cached https://www.piwheels.org/simple/requests/requests-2.28.2-py3-none-any.whl (62 kB)
> Collecting cachetools==5.3.0 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 5))
>   Using cached https://www.piwheels.org/simple/cachetools/cachetools-5.3.0-py3-none-any.whl (9.3 kB)
> Collecting scrypted-arlo-go==0.2.0 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 6))
>   Downloading https://github.com/bjia56/scrypted-arlo-go/releases/download/v0.2.0/scrypted_arlo_go-0.2.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 10.2 MB/s eta 0:00:00
> Collecting cloudscraper==1.2.71 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 7))
>   Using cached https://www.piwheels.org/simple/cloudscraper/cloudscraper-1.2.71-py3-none-any.whl (99 kB)
> Collecting async-timeout==4.0.2 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 8))
>   Using cached https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from sseclient==0.0.22->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 2)) (1.16.0)
> Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3)) (21.2.0)
> Collecting charset-normalizer<4.0,>=2.0 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
> Collecting multidict<7.0,>=4.5 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
> Collecting yarl<2.0,>=1.0 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
> Collecting frozenlist>=1.1.1 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
> Collecting aiosignal>=1.1.2 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 3))
>   Using cached https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
> Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 4)) (3.3)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 4)) (1.26.5)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 4)) (2020.6.20)
> Collecting requests-toolbelt>=0.9.1 (from cloudscraper==1.2.71->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 7))
>   Using cached https://www.piwheels.org/simple/requests-toolbelt/requests_toolbelt-1.0.0-py2.py3-none-any.whl (51 kB)
> Requirement already satisfied: pyparsing>=2.4.7 in /usr/lib/python3/dist-packages (from cloudscraper==1.2.71->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/requirements.txt (line 7)) (2.4.7)
> Installing collected packages: scrypted-arlo-go, paho-mqtt, multidict, frozenlist, charset-normalizer, cachetools, async-timeout, yarl, requests, aiosignal, sseclient, requests-toolbelt, aiohttp, cloudscraper
> Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 cachetools-5.3.0 charset-normalizer-3.1.0 cloudscraper-1.2.71 frozenlist-1.3.3 multidict-6.0.4 paho-mqtt-1.6.1 requests-2.28.2 requests-toolbelt-1.0.0 scrypted-arlo-go-0.2.0 sseclient-0.0.22 yarl-1.9.2
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> pip install result 0
> site-packages: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/local/lib/python3.10/dist-packages
> Setting plugin verbosity to Normal
> Setting plugin transport to SSE
> [Arlo Provider]: Trying connect to IMAP
> [Arlo Provider]: Connected to IMAP
> [Arlo Provider]: Starting IMAP refresh loop 140572608147808
> [Arlo Provider]: Performing IMAP login flow
> [Arlo Provider]: Trying to initialize Arlo client...
> [Arlo]: Using primary authentication host
> [Arlo Provider]: Initialized Arlo client, waiting for MFA code
> [Arlo Provider]: Checking IMAP for MFA codes
> [Arlo Provider]: No new emails found, will sleep and retry
> [Arlo Provider]: Cannot create device for nativeId 57K28ASP77A13, maybe it hasn't been loaded yet?
> [Arlo Provider]: Cannot create device for nativeId A2819777A0EBB, maybe it hasn't been loaded yet?
> [Arlo Provider]: Cannot create device for nativeId 568181S65B885, maybe it hasn't been loaded yet?
> [Arlo Provider]: Checking IMAP for MFA codes
> [Arlo Provider]: No new emails found, will sleep and retry
> [Arlo Provider]: Checking IMAP for MFA codes
> [Arlo Provider]: Found MFA code
> [Arlo Provider]: Completing Arlo MFA...
> [Arlo Provider]: Arlo MFA done
> [Arlo Provider]: Discovering devices...
> [Arlo Provider]: Discovered 1 basestations
> [Arlo]: SSE 140572608142768 connected
> [Arlo 568181S65B885]: Started logging server at localhost:36899
> [Arlo Provider]: ArloProvider.discover_devices raised an exception
> Traceback (most recent call last):
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/util.py", line 35, in wrapped
>     return await fn(*args, **kwargs)
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/provider.py", line 569, in discover_devices
>     return await self.discover_devices_impl()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/provider.py", line 646, in discover_devices_impl
>     child_manifests = device.get_builtin_child_device_manifests()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/camera.py", line 234, in get_builtin_child_device_manifests
>     light = self.get_or_create_light()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/camera.py", line 657, in get_or_create_light
>     self.light = ArloNightlight(light_id, self.arlo_device, self.provider, self)
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/spotlight.py", line 60, in __init__
>     super().__init__(nativeId=nativeId, arlo_device=arlo_device, arlo_basestation=arlo_device, provider=provider)
> TypeError: ArloSpotlight.__init__() missing 1 required positional argument: 'camera'
> Traceback (most recent call last):
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/provider.py", line 198, in do_arlo_setup
>     await self.discover_devices()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/util.py", line 35, in wrapped
>     return await fn(*args, **kwargs)
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/provider.py", line 569, in discover_devices
>     return await self.discover_devices_impl()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/provider.py", line 646, in discover_devices_impl
>     child_manifests = device.get_builtin_child_device_manifests()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/camera.py", line 234, in get_builtin_child_device_manifests
>     light = self.get_or_create_light()
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/camera.py", line 657, in get_or_create_light
>     self.light = ArloNightlight(light_id, self.arlo_device, self.provider, self)
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-2a0679bdae3b279f071b108595a9be79.zip/arlo_plugin/spotlight.py", line 60, in __init__
>     super().__init__(nativeId=nativeId, arlo_device=arlo_device, arlo_basestation=arlo_device, provider=provider)
> TypeError: ArloSpotlight.__init__() missing 1 required positional argument: 'camera'
>

**Comment by bjia56** [comment]
Thanks for that, I see what's wrong. There's some other issues as well that I'll need to investigate

**Comment by bjia56** [comment]
If you get a chance can you please test 0.7.35? I appreciate the help, hard to verify on my side without an actual arlo baby

**Comment by mikesalz** [comment]
You're very welcome! I appreciate your hard work on this!  The camera is working now, but I am not seeing any accessories in HomeKit.

**Comment by bjia56** [comment]
They should be in homekit via the scrypted bridge - can you check that the homekit extension is enabled for the light, and try restarting the homekit plugin afterwards?

**Comment by mikesalz** [comment]
I see it in the Scrypted UI under HomeKit and it is enabled.  It's just not actually showing up in HomeKit.  I even restarted my Scrypted container.

**Comment by bjia56** [comment]
Ah! I forgot how this worked - the lights on cameras are actually merged into the camera accessory when exposed to homekit. In homekit, if you go to the camera, there should be a button for nearby accessories - the switch should show up there. The camera settings within homekit should also let you show merged accessories as separate cards

**Comment by mikesalz** [comment]
Correct.  But the nightlight just isn't being pushed down to HomeKit for some reason.

For example, here is one of my Arlo Ultra cameras.  When you open the camera and go to the gear in HomeKit, you can can see there are light and motion accessories:

![FDBAB61E-C17F-485D-92E3-61C2D8A8FE80](https://github.com/koush/scrypted/assets/46855061/a0e6ef1a-bb78-4e36-a6c5-cd6a7078d4a5)


But with the Arlo Baby camera, there is only motion:

![05D793F5-5646-4DEC-A2F1-EBD3E55D8726_1_101_o](https://github.com/koush/scrypted/assets/46855061/a3d242ae-e84b-4699-aa1b-7cae84ec02c0)


Having said that... I don't know if you have had other requests to get the nightlight working, but the light on that camera is pretty useless.  I personally would never use it, and don't think it is worth your effort to get it into HomeKit.  I do appreciate the effort.  And if you still want to work on it, I am happy to help you test it out.  But I am very happy with the camera in the state you currently have it!

**Comment by bjia56** [comment]
Thanks for the info! I'm mostly trying to get it working for completeness. But yeah if it's not too important on your side then perhaps we can table this for later.
