### ISSUE TITLE
Support for cameras with HomeKit support (no HSV)

### ISSUE THREAD

**Issue by ads1230** [koush/scrypted#88]
Hey!

My cameras (a r l o) have a HomeKit add-on which only allows streaming, no HSV.
Would it be possible to add these cameras to Scrypted using this add-on, then rebroadcast it for HSV?

**Comment by koush** [comment]
yes

**Comment by ads1230** [comment]
Thanks for letting me know, but how? The scrypted HK plugin doesn't allow for you to add HK accessories to Scrypted, only the other way round.

**Comment by koush** [comment]
oh I misunderstood, no it cant do that

**Comment by codyc1515** [comment]
Arlo only streams from the cloud (same as Ring) so it seems unlikely that this may be supported. The next issue would be battery devices would run out of battery very quickly as they'd always be "streaming".

**Comment by ads1230** [comment]
> Arlo only streams from the cloud (same as Ring) so it seems unlikely that this may be supported. The next issue would be battery devices would run out of battery very quickly as they'd always be "streaming".

Ty both of you for noticing this thread.

Arlo has a HomeKit integration in their app which allows for basic streaming. I “assume” the stream through HK is local from the base.

Plugged in arlo’s continuously charge so battery life is not an issue.

**Comment by codyc1515** [comment]
I know that Home Assistant has a way to pair HomeKit accessories to it like you are describing. I'm not 100% sure but it's likely that HA gives you a RTSP stream out. If this is the case then you will be able to use the RTSP steam in Scrypted. Quite a bit of additional complexity and overhead however.

**Comment by koush** [comment]
ring was added. will look into HSV cameras, but that's not high priority

**Comment by codyc1515** [comment]
What do you mean Ring was added?

**Comment by WendelFelius** [comment]
Would love this for my Netatmo Doorbell too. They promised HKSV for a long time now, but no update yet...

**Comment by koush** [comment]
https://github.com/koush/scrypted/issues/195

**Comment by koush** [comment]
@codyc1515 @ads1230 arlo plugin has been contributed by @bjia56

**Comment by poluruc** [comment]
Any Eufy support pls?

**Comment by digitalbugs** [comment]
D-Link OMNA support pls?

**Comment by yieldhog** [comment]
Far beyond my capacity, but, I have used Eufy Security for Home Assistant and there is an npm available. Is this something that could be ported over?

https://www.npmjs.com/package/eufy-security-client

**Comment by koush** [comment]
closing this, as I won't be doing it.
