### ISSUE TITLE
Tuya plugin: Authorization failed

### ISSUE THREAD

**Issue by Dennis-NL** [koush/scrypted#880]
Keep getting the following message: Failed to log in with credentials. Please try again.
I have put all the credentials in correctly. Checked the api and works fine.
And yes i have devices connected!
Something wrong with the Tuya plugin?
![afbeelding](https://github.com/koush/scrypted/assets/43215753/2263341d-4a0d-4f93-bb1e-0a9f785729cb)

**Comment by Dennis-NL** [comment]
Response when calling the api:
![afbeelding](https://github.com/koush/scrypted/assets/43215753/2d9eb1b6-3232-4c74-8bef-156bce030769)

**Comment by koush** [comment]
need to renew your tuya account probably.
