### ISSUE TITLE
Two-Way audio isn’t available for ffmpeg-camera plugin

### ISSUE THREAD

**Issue by AlexOwl** [koush/scrypted#888]
Hello, I’m replacing fermax doorbell intercom with a custom made. I’m trying to achieve two-way audio intercom. I checked out commits of ffmpeg-camera and found that’s already been released before: 921cf0f and then it was commented in 516a748 without any explanation. If it doesn’t work for all users, can you please make it as beta feature

**Comment by koush** [comment]
it was confusing users. you can submit a ffmpeg speaker plugin using that code.

**Comment by chip131001** [comment]
Please provide a code example.
