### ISSUE TITLE
Google Home Plugin not working due to DNS issues in Avahi

### ISSUE THREAD

**Issue by MarcPow** [koush/scrypted#89]
starting plugin @scrypted/google-home 0.0.23
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
plugin successfully loaded
http://127.0.0.1:10080/endpoint/@scrypted/google-home/public/
uncaughtException Error: dns service error: unknown
    at new Advertisement (/server/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.createAdvertisement (/server/node_modules/mdns/lib/advertisement.js:64:10)
    at /src/main.ts:127:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: -65537
}

Using the following docker image 

pi@raspberrypi:~ $ docker pull koush/scrypted
Using default tag: latest
latest: Pulling from koush/scrypted
Digest: sha256:9896483f13523e256eb68e77cd0dda0db7c77f95c2309e5ffffc05608ad9f3ab
Status: Image is up to date for koush/scrypted:latest
docker.io/koush/scrypted:latest

**Comment by koush** [comment]
Will fix. This is actually benign and shouldn't cause it to fail. Need to guard for the error.

**Comment by MarcPow** [comment]
Out of curiosity: Is the advertisement actually unnecessary?  Wouldn't that Inhibit traffic back to Scripted?

**Comment by koush** [comment]
> Out of curiosity: Is the advertisement actually unnecessary? Wouldn't that Inhibit traffic back to Scrypted?

The advertisement is used for local fulfillment: google home can talk to scrypted directly over lan. This is often faster, and has the benefit of not using Scrypted's server.

**Comment by koush** [comment]
Fixed with bf3bec0
Uses ciao now, which has no native dependencies.

**Comment by MarcPow** [comment]
@koush 

#1 - Thank you.  Now, it seems to start up in console.
#2 - However, it doesn't seem to DO anything.  No device discovery, etc.  Also, when I click on the "Show public endpoint" or "Show private endpoint" links, I get "https://192.168.1.106:10443/endpoint/undefined/"

Are there any debug logs I can supply?

**Comment by koush** [comment]
This is the Google Home plugin which syncs scrypted devices with Google Home. It does not import Google devices. You want the Google Device Access plugin (which will pull in nest thermostats, cameras, etc).

**Comment by koush** [comment]
I'll add some documentation around the plugins. This is understandably confusing. Hop on discord if you have any questions. Syncing Nest devices is unfortunately non-trivial and the process is documented there (and should be in the readme).
