### ISSUE TITLE
Login requied after installing

### ISSUE THREAD

**Issue by DimChik2903** [koush/scrypted#898]
I installed Scrypted in portainer, from docker-compose.yml file, and when I open the address, they don’t offer me to create an account, but they immediately ask for a username and password. What could be the reason?

![image](https://github.com/koush/scrypted/assets/28841543/509fefa1-5bab-46e7-8b88-385b34cc7b37)

**Comment by koush** [comment]
Use wiki to reset login.

**Comment by DimChik2903** [comment]
When trying to connect to the container via the console, the container is restarted
![image](https://github.com/koush/scrypted/assets/28841543/85073856-a498-4175-a05a-1469245b7d56)
