### ISSUE TITLE
Support camera feeds for Amazon Alexa

### ISSUE THREAD

**Issue by erikankrom** [koush/scrypted#90]
Amazon Alexa support on Echo Devices would be great!  

See Monocle for a similar feature.  https://monoclecam.com/

**Comment by koush** [comment]
Alexa added support for webrtc, which is how the current Google Home and Chromecast support works already. the plumbing is all there, so it's a straightforward implementation at this point.

two issues:
I don't have an echo show.
need to get Alexa skill approval, and I'm uncertain what that entails.

**Comment by erikankrom** [comment]
Yes, it looks like the Alexa Skill Developer docs indicate WebRTC compatibility.  https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-camerastreamcontroller.html

I've never developed a skill myself, but it looks like the following doc details the process: https://developer.amazon.com/en-US/docs/alexa/devconsole/test-and-submit-your-skill.html

Is there a location where you accept donations for testing hardware like echo?

**Comment by koush** [comment]
I don't think I'll get around to doing this. If you want to build it, I am happy to provide guidance.

You can check this sample plugin out and open it in vscode. https://github.com/koush/scrypted-vscode-typescript

I actually already implemented the Alexa lambda proxy a few years ago, but the plugin is now defunct (when scrypted was an android app). It will need to be rewritten. The cloud portion is already done. I can stub out the plugin portion for you (so it receives the Amazon Alexa skill requests): ie, you'll be implementing the server in the plugin.
Alexa's http requests will be handled in the plugin itself. This is similar to how the Google Assistant plugin works. The plugin *is* the server.

https://github.com/koush/scrypted/blob/4f4093a0236f4824ec875c82f08672caacd96eea/plugins/google-home/src/main.ts#L515

**Comment by koush** [comment]
I'll need your email if you want access to the beta skill. After you are added, you can log in.

**Comment by koush** [comment]
ok camera feeds are in. waiting for Alexa skill approval now. https://github.com/koush/scrypted/tree/main/plugins/alexa

@erikankrom

**Comment by koush** [comment]
![Pasted_Image_3_23_22__10_15_AM](https://user-images.githubusercontent.com/73924/159760357-a2b02a33-0f49-43cc-882e-bd098784bed8.jpg)

**Comment by koush** [comment]
skill was approved

**Comment by chip131001** [comment]
i am from germany, how can i find the skill? The skill cannot be found in the Alexa app.

**Comment by koush** [comment]
currently only approved for English localizations, need to add it for other languages.

**Comment by chip131001** [comment]
> currently only approved for English localizations, need to add it for other languages.

When is a German localization planned? I would like to test.

**Comment by HolgerRichter** [comment]
Is there any chance / workaround using the alexa plugin of scrypted in Germany? Monocle is not working for me anymore. And scripted seems to be the best solution to get unifi protect rtsp video streams on echo show :-)

**Comment by NiccoStar86** [comment]
Hi @koush I am in Italy and would like to try the skill to expose the camera feeds to my Ecco Show 8. If you need help with the localization to then send the skill for review let me know ... I don't know what exactly needs to be done :) but if you need a "quality" check on translations, I'm available. Thank you for this great project!

**Comment by NicoTM77** [comment]
Same for Germany. If help is needed for German localization I am also available. I'd love to use scrypted with my Echo devices.
Also thank you for the great work @koush :)

**Comment by koush** [comment]
Yes, working through the Europe release right now.

**Comment by koush** [comment]
released worldwide

**Comment by NiccoStar86** [comment]
Hi @koush I saw that the Skill is not localized in Italian so it is not possible for me to install it. Is there any chance that it will be localized in Italian?  If you want help with the translation feel free to ask me! Thank you!

<img width="1491" alt="Screenshot 2023-01-19 alle 21 23 19" src="https://user-images.githubusercontent.com/7814756/213552390-d74562f9-ef70-4019-ae27-ba1c9035bd33.png">

**Comment by koush** [comment]
Alexa should be available in Italian, Japanese, and more countries now, Was missing some translations.

**Comment by NiccoStar86** [comment]
Hi @koush I confirm that the skill is now available for many more countries. Thank you!
