### ISSUE TITLE
Docker container scrypted keep restarting

### ISSUE THREAD

**Issue by IvaWonderbush** [koush/scrypted#900]
Docker logs of the scrypted container show the following constant error:

`/init: 37: exec: s6-overlay-suexec: Exec format error`

I've restarted the container but to no avail. Do I need to try a reinstall?

It's been running now for a few months, suddenly stopped.

**Comment by IvaWonderbush** [comment]
Nevermind, I was running 32bit. Thought I double checked that during installation.

**Comment by mdav43** [comment]
I had an existing image running but after restart this started happening on raspberry pi also. Haven't found a solution yet.
