### ISSUE TITLE
Can no longer install on Home Assistant OS

### ISSUE THREAD

**Issue by AleAlejandrok** [koush/scrypted#901]
When attempting to add the repo to the addons store this error appears

Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/koush/scrypted /data/addons/git/09e60fb6
  stderr: 'Cloning into '/data/addons/git/09e60fb6'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (244 bytes)
Submodule 'external/axios-digest-auth' (https://github.com/koush/axios-digest-auth) registered for path 'external/axios-digest-auth'
Submodule 'plugins/tensorflow/face-api.js' (https://github.com/koush/face-api.js) registered for path 'external/face-api.js'
Submodule 'external/ring-client-api' (https://github.com/koush/ring) registered for path 'external/ring-client-api'
Submodule 'external/scrypted-ffmpeg' (https://github.com/koush/scrypted-ffmpeg) registered for path 'external/scrypted-ffmpeg'
Submodule 'plugins/unifi-protect/src/unifi-protect' (https://github.com/koush/unifi-protect.git) registered for path 'external/unifi-protect'
Submodule 'external/werift' (https://github.com/koush/werift-webrtc) registered for path 'external/werift'
Submodule 'plugins/cloud/node-nat-upnp' (https://github.com/koush/node-nat-upnp.git) registered for path 'plugins/cloud/node-nat-upnp'
Submodule 'plugins/sample-cameraprovider' (https://github.com/koush/scrypted-sample-cameraprovider) registered for path 'plugins/sample-cameraprovider'
Submodule 'plugins/vscode-typescript' (https://github.com/koush/scrypted-vscode-typescript) registered for path 'plugins/vscode-typescript'
Submodule 'plugins/zwave/file-stream-rotator' (https://github.com/koush/file-stream-rotator.git) registered for path 'plugins/zwave/file-stream-rotator'
Submodule 'sdk/developer.scrypted.app' (https://github.com/koush/developer.scrypted.app) registered for path 'sdk/developer.scrypted.app'
Cloning into '/data/addons/git/09e60fb6/external/axios-digest-auth'...
Cloning into '/data/addons/git/09e60fb6/external/face-api.js'...
Cloning into '/data/addons/git/09e60fb6/external/ring-client-api'...
Cloning into '/data/addons/git/09e60fb6/external/scrypted-ffmpeg'...
Cloning into '/data/addons/git/09e60fb6/external/unifi-protect'...
Cloning into '/data/addons/git/09e60fb6/external/werift'...
Cloning into '/data/addons/git/09e60fb6/plugins/cloud/node-nat-upnp'...
Cloning into '/data/addons/git/09e60fb6/plugins/sample-cameraprovider'...
Cloning into '/data/addons/git/09e60fb6/plugins/vscode-typescript'...
Cloning into '/data/addons/git/09e60fb6/plugins/zwave/file-stream-rotator'...
Cloning into '/data/addons/git/09e60fb6/sdk/developer.scrypted.app'...
fatal: remote error: upload-pack: not our ref 2d3fac10c7d60126d5ef64ec6da80d17741566e1
fatal: Fetched in submodule path 'external/ring-client-api', but it did not contain 2d3fac10c7d60126d5ef64ec6da80d17741566e1. Direct fetching of that commit failed.
'

**Comment by koush** [comment]
fixed
