### ISSUE TITLE
Snapshot Plugin constantly times out

### ISSUE THREAD

**Issue by JudahBella** [koush/scrypted#904]
I've been struggling with this but can't seem to get it fixed. Wonder if it's a bug of some sort. Snapshot Plugin would try to create a snapshot, time out, then attempt to create a "Snapshot Timed Out" image, then proceed to _also_ time out. Essentially, it times out trying to generate a snapshot, and times out generating the snapshot error. 🤦‍♂️ 

I've tried every `Default Snapshot Channel`, every `Snapshots from Prebuffer`, tried `Override Snapshot URL`, all to no avail. 

Everything else works fine, ONVIF Camera Plugin, Tapo Camera Plugin, Rebroadcast Plugin, HomeKit.. the works. Prebuffering, two way audio, everything works fine. Only Snapshot Plugin is failing.

I'm running running version Scrypted 0.39.0 and snapshot@0.0.57. 

```
[Tapo C110] -hide_banner -y -f image2pipe -i pipe:[REDACTED] -filter_complex scale=-2:'min(720,ih)' -frames:v 1 -f image2 pipe:3
[Tapo C110] Snapshot failed r [Error]: Operation Timed Out
    at Timeout._onTimeout (/common/src/promise-utils.ts:53:20)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  promise: Promise { <pending> }
}
[Tapo C110] creating error image with background Snapshot Timed Out true
[Tapo C110] -hide_banner -y -f image2pipe -i pipe:[REDACTED] -filter_complex eq=brightness=-0.2[snapshotBlur] ; [snapshotBlur] gblur=sigma=25[snapshotText] ; [snapshotText] drawtext=fontfile=/server/volume/plugins/@scrypted/snapshot/zip/unzipped/fs/Lato-Bold.ttf:text='Snapshot Timed Out':fontcolor=white:fontsize=h/8:x=(w-text_w)/2:y=(h-text_h)/2 -frames:v 1 -f image2 pipe:3
[Tapo C110] ffmpeg exited
unhandledRejection r [Error]: Operation Timed Out
    at Timeout._onTimeout (/common/src/promise-utils.ts:53:20)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  promise: Promise { <pending> }
}
[Tapo C110] ffmpeg exited
```

EDIT: I notice in https://github.com/koush/scrypted/blob/7f4c8997b9adf78b1577d8389bea0a429871d0eb/plugins/snapshot/src/ffmpeg-image-filter.ts#L173 `timeoutFunction` is used, and searching the label I don't see it used anywhere else. It takes the `timeout` value from `FFmpegImageFilterOptions` or sets it to 10000. Is there any way to override the timeout? @koush 

EDITEDIT: I tried running `ffmpeg -h` from the Terminal, and it takes >10s to respond. Could this be the cause of the timeout?

EDITEDITEDIT: Solved the problem. I disabled resource limitation on the Scrypted container and the problem went away.

**Comment by adrianmihalko** [comment]
Maybe we have same problem?

https://github.com/koush/scrypted/issues/893

How did you disable resource limitation?
