### ISSUE TITLE
accessing the Scrypted management through Cloudflare Zerotrust

### ISSUE THREAD

**Issue by fuzzysb** [koush/scrypted#907]
I have a cloudflare zerotrust tunnel, and all my external egress goes via that route, I have a forwarding rule configured to the correct internal address on port 46573, and I can access the management server using that URL and no issues with TLS security etc.

I have chosen forwarding with a custom domain

but I get the following error when i choose test port forward from the Scrypted Cloud Settings pane. I dont get why?

![image](https://github.com/koush/scrypted/assets/16162689/81afa47b-a178-45df-b427-1c6b6324fb8b)

I also can access my management portal when going to https://home.scrypted.app/

but i cannot link with the alexa skill

I am using the Scrypted Homeassistant Addon.

**Comment by koush** [comment]
currently the request IP registering the server must match one of the IPs that the domain resolves to.

**Comment by Oloyemeji** [comment]
> currently the request IP registering the server must match one of the IPs that the domain resolves to.

koush, I'm sorry to reopen this issue but I'll appreciate your support.
I have the same cloudflare setup with fussysb and having the same "url hostname does not match requestor" message.

I have read your resolution response but it seems I do not understand what exactly what to do. 
Can you please explain how to match domain DNS IP to the IP of the registering server?

Thank you.

**Comment by fuzzysb** [comment]
What he is explaining is that a solution like ZeroTrust would never work as the external facing IP is different when using the ZeroTrust Tunnel. this is a limit on the Scrypted solution. I have instead of using ZeroTrust have created a NAT tool, but to better control access, i am using Wazuh to monitor access and have a rule to automatically block IP's when suspicious access is spotted. It is still more insecure than the CF ZeroTrust, but still gives me more security visibility than just opening and forgetting.

**Comment by Oloyemeji** [comment]
Thank you fuzzysb for your response, I think I got it now. I'll have to seek alternative route maybe your way again.
Koush, thanks for your great work.
