### ISSUE TITLE
HomeKit Secure Video stability

### ISSUE THREAD

**Issue by codyc1515** [koush/scrypted#91]
I have a number of certified HKSV cameras in my home which all work fine with zero issues. However my one Scrypted camera with HKSV seems to disconnect randomly and go online / offline. Any thoughts on things I can check?

**Comment by kingb2019** [comment]
Hi Cody, there are many unknown variables that could cause this. You need to provide more information if possible. Such as what hardware/OS is Scrypted running on? What are the hardware specs? Is the hardware sharing resources? What is the name/model of camera & video transmission media? What plugins are you using? When you are saying disconnect/offline/online is this a statement being made by pinging the camera, visually seeing the video stream start/stop,l or receiving push notifications? Are you seeing any video pixelation/smudging?

**Comment by baylanger** [comment]
Quick comment on this topic.

It'd be great if someone could write a script that collect hardware info, OS & app metrics, any OS/hardware error, logs stripped of username/password/private config/etc.

I'd do it but I'm new here and hoping I won't have this same issue.

@codyc1515 after a fresh restart of the process/reboot, how long does it take for scrypted to show a disconnect?  I'd hope that info is in the logs.  Trying to understand if it takes a "minimum" time before the first disconnect starts to show up.

**Comment by baylanger** [comment]
Does your camera supports ONVIF?  If so can you try using that protocol?  I couldn't find recent issues for that protocol, either not popular or it's more stable?

**Comment by codyc1515** [comment]
Hey guys.

Fairly typical setup with Raspberry Pi 4 (4GB). Also running Homebridge. Camera is TP-Link C200 using OnVif plug-in. When the issue happens you get a notification that the camera went offline and then when browsing to the camera in the Home app the camera shows as "This camera is not responding" in HomeKit.

![image](https://user-images.githubusercontent.com/50791984/147783798-b5ee6acf-8103-491f-9d35-e27f05c719f6.jpeg)

**Comment by koush** [comment]
Is this a local or docker install? You'll see that message if the scrypted server is crashing. It comes back online because it's restarting.

**Comment by codyc1515** [comment]
I don't recall 100% but I believe docker. Good point though. I will check it next time.

**Comment by codyc1515** [comment]
@koush Where can I find the HAP-NodeJS directory? It seems to be referencing the "project directory / external / HAP-NodeJS" folder but this is empty. I would like to make some changes to enhance the stability. I don't believe it is related to the work you have done directly but would like to test first before pushing them out.

**Comment by koush** [comment]
> @koush Where can I find the HAP-NodeJS directory? It seems to be referencing the "project directory / external / HAP-NodeJS" folder but this is empty. I would like to make some changes to enhance the stability. I don't believe it is related to the work you have done directly but would like to test first before pushing them out.

hop on discord and I can help you out.
probably need to `git submodule init` and `git submodule update`

**Comment by koush** [comment]
> I don't recall 100% but I believe docker. Good point though. I will check it next time.

just to be clear, the online/offline only happens if your scrypted server is unreachable by homekit. it doesn't sound like the server is crashing (I think you would have noticed the restarts?), so it's likely a network issue.
