### ISSUE TITLE
Is it possible to server Scrypted under a sub-path?

### ISSUE THREAD

**Issue by dannytech** [koush/scrypted#910]
Hi, trying to set up Scrypted using Podman on the same host that I'm running Frigate on. I'd like to put Scrypted behind a reverse proxy (Nginx) which is already serving Frigate, so that accessing https://example.com/ leads to Frigate (which works already) and https://example.com/scrypted/ leads to Scrypted (i.e. the login page would be available at https://example.com/scrypted/endpoint/@scrypted/core/public/#/). I did try to edit my Nginx config to send certain paths like `/endpoint/` to Scrypted, which partially works so far, but is far from ideal and means if any endpoints are added in the future I may need to modify the config. Is there any way to set the path which Scrypted should run under, which all other paths should be relative to? I didn't see any mention of such an option.

**Comment by koush** [comment]
Not really. Use a subdomain that resolves to the same ip and use nginx to route accordingly.
