### ISSUE TITLE
empty page with <404 page not found>

### ISSUE THREAD

**Issue by AM-ElZaher** [koush/scrypted#911]
after successful installation on docker using docker compose, when trying to access webpage using HTTP://vm_ip:10444 it shows an empty page with one line error message <404 page not found>, when trying https://vm_ip:10444 there is <cannot reach website> error

**Comment by koush** [comment]
https port 10443.

**Comment by AM-ElZaher** [comment]
> https port 10443.

but in the yml file it says
```
environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer SET_THIS_TO_SOME_RANDOM_TEXT
            - SCRYPTED_WEBHOOK_UPDATE=**http://localhost:10444**/v1/update
```
and after deployment <watchtower> is assigned an IP with port 10444, but the scripted container isn't assigned any ip
