### ISSUE TITLE
Doorbird Snapshot refresh is Slow and gives errors

### ISSUE THREAD

**Issue by Vicelow** [koush/scrypted#914]
Hi there,

Recently, Homekit (and also scrypted) take a long time to refresh the snapshot. It seems related to errors I see in the log. It used to work fast and snappy before.

	########################
6/27/2023, 4:51:49 AM
########################
[HomeKit]: HomeKit Connection 192.168.1.165
[Rebroadcast Plugin]: sending prebuffer 6000
[Snapshot Plugin]: Snapshot failed RPCResultError: Operation Timed Out
[Snapshot Plugin]:     at Timeout._onTimeout (/common/src/promise-utils.ts:53:20)
[Snapshot Plugin]:     at listOnTimeout (node:internal/timers:569:17)
[Snapshot Plugin]:     at processTimers (node:internal/timers:512:7)
[Snapshot Plugin]: @scrypted/snapshot:host
[Snapshot Plugin]: host:@scrypted/snapshot {
[Snapshot Plugin]:   cause: undefined
[Snapshot Plugin]: }
[Snapshot Plugin]: creating error image with background Snapshot Failed true
[HomeKit]: HomeKit Connection 192.168.1.165
[Rebroadcast Plugin]: sending prebuffer 6000
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[Rebroadcast Plugin]: client connection timed out
[Rebroadcast Plugin]: sending prebuffer 6000
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[Rebroadcast Plugin]: sending prebuffer 6000
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.

Many thanks
Vicelow

**Comment by koush** [comment]
resource restrictions on the container can cause this. ffmpeg times out.

**Comment by koush** [comment]
someone else reported this exact issue which I can't find at this moment.
