### ISSUE TITLE
Ring Plugin unhandledRejection HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by iReadTOS** [koush/scrypted#919]
Hi all,
I am using the latest version (0.0.116) of the Ring plugin. Up until this morning, this version of the plugin has been very stable and is working with HomeKit with zero delay. Now, once I login no devices appear or work in HomeKit. Looking at the logs, I see 401 errors after login. Can anyone advise on how I should proceed? 

Logs:

########################
7/1/2023, 4:08:22 PM
########################
login completed successfully with 2 factor code
login success, trying discovery
unhandledRejection HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/data/scrypted_data/plugins/@scrypted/ring/node18-linux-x64-20230608/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1688242102536,
    socket: 1688242102537,
    lookup: 1688242102537,
    connect: 1688242102564,
    secureConnect: 1688242102588,
    upload: 1688242102588,
    response: 1688242102682,
    end: 1688242102683,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 27,
      tls: 24,
      request: 0,
      firstByte: 94,
      download: 1,
      total: 147
    }
  }
}

**Comment by koush** [comment]
might be related to this, or wrong password. https://github.com/koush/scrypted/issues/878

**Comment by bwt615** [comment]
@koush I removed devices from the account to try and fix notifications, now I'm getting this, even after re-entering a 2FA code. Thoughts?

**Comment by chinedu40** [comment]
@bwt615 Delete the ring plugin and reinstalling solved this for me
