### ISSUE TITLE
Google Device Access setup undocumented

### ISSUE THREAD

**Issue by MarcPow** [koush/scrypted#92]
The Plug-in UX in the dashboard alludes to the excellent HomeAssistant setup documentation - which I already have setup and working with HA.

But when I try to reuse that with Scrypted, I get a Redirect URI invalid error.

—
More to the point, the whole process is undocumented, so I’m shooting in the dark :)

**Comment by koush** [comment]
Will do! It’s currently in a sticky post on discord. I am going to move everything into the plugin readmes which will then surface in the installed plugins in scrypted

**Comment by koush** [comment]
fixed 
![image](https://user-images.githubusercontent.com/73924/147628440-e8b2fa53-e4ea-4fec-82fe-ec1ea0af19e8.jpeg)
