### ISSUE TITLE
Ring issues - Continued

### ISSUE THREAD

**Issue by mikesalz** [koush/scrypted#925]
@koush I think you may have rushed to close another Ring issue.  For reference: https://github.com/koush/scrypted/issues/878

I followed the instructions and it did work at first.  But only for about 30 minutes.  Then the integration stopped connecting to Ring all together.  I re-entered my password and 2FA, and it started working again.  But only for another 30 minutes or so.

**Comment by koush** [comment]
Does reload plugin resolve it?

**Comment by mikesalz** [comment]
No, reloading the plugin does not help.  But I noticed this in the events:

![image](https://github.com/koush/scrypted/assets/46855061/2223956f-8cdb-47a3-8d1e-5b42aa5b3461)


I looked at the homebridge documentation regarding refresh tokens, but I don't see a way to incorporate it into Scrypted.  Do I need to add a refresh token to Scrypted?  And if so, how would I do that?

**Comment by mikesalz** [comment]
@koush Not sure if you saw my previous message.  It looks like I need a refresh token.  I think I figured out how to generate it correct:

![image](https://github.com/koush/scrypted/assets/46855061/4851c6cc-5aa9-4449-8da4-2420a66dd45f)

But I don't know what to do with it.  I read in a forum where someone suggested putting it in Storage.  I did the following and restarted, but still no luck:

![image](https://github.com/koush/scrypted/assets/46855061/3f963656-0688-462d-bcc8-aad4a22bc6e8)

Would you mind posting Scrypted-specific instructions for adding a refresh token?

**Comment by codyc1515** [comment]
The original issue isn't resolved. I got one or two notifications after clearing the history and thought it was solved but it's not.

**Comment by koush** [comment]
reopened original

**Comment by mikesalz** [comment]
@koush Thanks for reopening the original.  But I'm not sure if my current issue is directly related to that.  When I followed the directions for the homebridge troubleshooting, I removed all of my devices from the Ring app.  After that, I have only been able to connect to Ring in Scrypted for about 30 minutes at a time.  Then Scrypted just can't connect at all.  I generated a new Refresh Token and placed it under Storage, but I still get the below error.  Thoughts on how I can fix this?

```
linux x64 #42962 SMP Mon May 29 14:38:23 CST 2023
server version: 0.39.0
plugin version: @scrypted/ring 0.0.117
full
########################
7/5/2023, 1:36:59 PM
########################
node modules /server/volume/plugins/@scrypted/ring/node18-linux-x64-20230329
native dependencies (up to date). got socket.io-client
plugin loaded
login success, trying discovery
discovery failure Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at Tt.getGrantData (/external/ring-client-api/packages/ring-client-api/rest-client.ts:225:11)
    at Tt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:231:28)
    at Tt.getAuth (/external/ring-client-api/packages/ring-client-api/rest-client.ts:277:21)
```
