### ISSUE TITLE
Node.js[8]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.

### ISSUE THREAD

**Issue by scottrobertson** [koush/scrypted#93]
Trying to run via docker. This is the first time I have run it, and it's the latest image.

```
pi@raspberrypi:~/scrypted $ docker-compose up
Creating scrypted ... done
Attaching to scrypted
scrypted    | Node.js[8]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
scrypted    | Aborted (core dumped)
scrypted exited with code 134
```

**Comment by scottrobertson** [comment]
`koush/scrypted:16` works... RaspberryPi OS is up to date.

**Comment by koush** [comment]
> `koush/scrypted:16` works... RaspberryPi OS is up to date.

update to bullseye. this is a Pi OS bug.
https://issueexplorer.com/issue/louislam/uptime-kuma/372

I don't recommend using the :16 workaround, since opencv and other stuff will not work.
