### ISSUE TITLE
Doorbird HKSV recording are missing audio

### ISSUE THREAD

**Issue by Vicelow** [koush/scrypted#934]
Not sure if it's a bug or just that way it works / a parameter I didn't set, but for me, audio stream is missing in HKSV recordings. The live stream does have audio stream though...

**Comment by t1ll** [comment]
On the Scrypted Discord there is a discussion about this. 

This is what Tyraz wrote:

> I think that's how the doorbird works.
> The audio isn't part of the stream as far as I know and has to be received seperately.
> And iirc audio will also be canceled after some time.
> 
> I guess it's because Doorbird is a german company, and we have more strict privacy rules.
> 24/7 video recording is already problematic and you have to add signs about video recording on the entrance of your property.
> 
> Audio recording, which isn't blocked by walls etc. might be even more problematic.
> Might be the reason why they try to treat this more like a legacy doorbell with video and less like a surveillance camera.

Are you sure you are getting Audio in the stream without triggering the "Speak" mode first?

**Comment by Vicelow** [comment]
That's indeed the case - I get it when triggering speak mode. I was wondering then why it wouldn't also work in the recording if in principle there is audio available (my native HKSV cameras also work fine with audio...). Thanks for the explanation!

**Comment by koush** [comment]
Doorbird only operates in two way audio mode, per my understanding. I am not the plugin author.
