### ISSUE TITLE
Fail to load Arlo Plugin

### ISSUE THREAD

**Issue by deflao** [koush/scrypted#947]
Hello,
I've run into this problem since yesterday, I checked the console and this is what it said.
ERROR: Could not build wheels for curl-cffi, which is required to install pyproject.toml-based projects
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 634, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1

I'm a newbie on this so please help. Thank you.

**Comment by bjia56** [comment]
can you reload the plugin and grab the full set of console logs from the plugin with all the output? there should be a copy all button around the console window

**Comment by deflao** [comment]
Here you go:
linux arm #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
server version: 0.39.0
plugin version: @scrypted/arlo 0.8.7
full
########################
7/12/2023, 12:57:52 AM
########################
=============================================
Python machine vs architecture mismatch detected. Plugin installation may fail.
This issue occurs if a 32bit system was upgraded to a 64bit kernel.
Reverting to the 32bit kernel (or reflashing as native 64 bit is recommended.
https://github.com/koush/scrypted/issues/678
=============================================
python version: python3.10
python prefix: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608
Removing old dependencies: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608
requirements.txt (outdated)
paho-mqtt==1.6.1
sseclient==0.0.22
aiohttp==3.8.4
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.4.0
cloudscraper==1.2.71
curl-cffi==0.5.7; platform_machine != 'armv7l'
async-timeout==4.0.2
--extra-index-url=https://www.piwheels.org/simple/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/, https://bjia56.github.io/scrypted-arlo-go/
Collecting paho-mqtt==1.6.1 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-1.6.1-py3-none-any.whl (75 kB)
Collecting sseclient==0.0.22 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 2))
  Using cached https://www.piwheels.org/simple/sseclient/sseclient-0.0.22-py3-none-any.whl (4.4 kB)
Collecting aiohttp==3.8.4 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached aiohttp-3.8.4.tar.gz (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting requests==2.28.2 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 4))
  Using cached https://www.piwheels.org/simple/requests/requests-2.28.2-py3-none-any.whl (62 kB)
Collecting cachetools==5.3.0 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 5))
  Using cached https://www.piwheels.org/simple/cachetools/cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting scrypted-arlo-go==0.4.0 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 6))
  Downloading https://github.com/bjia56/scrypted-arlo-go/releases/download/v0.4.0/scrypted_arlo_go-0.4.0-cp310-cp310-manylinux_2_17_armv7l.manylinux2014_armv7l.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 11.1 MB/s eta 0:00:00
Collecting cloudscraper==1.2.71 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 7))
  Using cached https://www.piwheels.org/simple/cloudscraper/cloudscraper-1.2.71-py3-none-any.whl (99 kB)
Collecting curl-cffi==0.5.7 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 8))
  Using cached curl_cffi-0.5.7.tar.gz (27 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting async-timeout==4.0.2 (from -r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 9))
  Using cached https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from sseclient==0.0.22->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3)) (21.2.0)
Collecting charset-normalizer<4.0,>=2.0 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached https://www.piwheels.org/simple/charset-normalizer/charset_normalizer-3.2.0-py3-none-any.whl (46 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached multidict-6.0.4.tar.gz (51 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting yarl<2.0,>=1.0 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached yarl-1.9.2.tar.gz (184 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting frozenlist>=1.1.1 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached frozenlist-1.3.3.tar.gz (66 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting aiosignal>=1.1.2 (from aiohttp==3.8.4->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 3))
  Using cached https://www.piwheels.org/simple/aiosignal/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 4)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 4)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.28.2->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 4)) (2020.6.20)
Collecting requests-toolbelt>=0.9.1 (from cloudscraper==1.2.71->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 7))
  Using cached https://www.piwheels.org/simple/requests-toolbelt/requests_toolbelt-1.0.0-py2.py3-none-any.whl (51 kB)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/lib/python3/dist-packages (from cloudscraper==1.2.71->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 7)) (2.4.7)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from curl-cffi==0.5.7->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 8)) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12.0->curl-cffi==0.5.7->-r /server/volume/plugins/@scrypted/arlo/python3.10-Linux-aarch64-20230608/requirements.txt (line 8)) (2.21)
Building wheels for collected packages: aiohttp, curl-cffi, frozenlist, multidict, yarl
  Building wheel for aiohttp (pyproject.toml): started
  Building wheel for aiohttp (pyproject.toml): finished with status 'done'
  Created wheel for aiohttp: filename=aiohttp-3.8.4-cp310-cp310-linux_aarch64.whl size=905888 sha256=2a9d9d33c1a9b12c17d61e53d98c1a7f7c3031c13580f56f34c84c24a0888ab4
  Stored in directory: /root/.cache/pip/wheels/45/f9/f2/66c145c2f6d7b35277d17b15c7a875b85b5b69ab0f3b3fad38
  Building wheel for curl-cffi (pyproject.toml): started
  Building wheel for curl-cffi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for curl-cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      /tmp/pip-build-env-urinostm/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/curl_cffi
      copying curl_cffi/build.py -> build/lib.linux-aarch64-cpython-310/curl_cffi
      copying curl_cffi/__init__.py -> build/lib.linux-aarch64-cpython-310/curl_cffi
      copying curl_cffi/curl.py -> build/lib.linux-aarch64-cpython-310/curl_cffi
      copying curl_cffi/const.py -> build/lib.linux-aarch64-cpython-310/curl_cffi
      copying curl_cffi/aio.py -> build/lib.linux-aarch64-cpython-310/curl_cffi
      creating build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/errors.py -> build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/headers.py -> build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/session.py -> build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/__init__.py -> build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/cookies.py -> build/lib.linux-aarch64-cpython-310/curl_cffi/requests
      running egg_info
      writing curl_cffi.egg-info/PKG-INFO
      writing dependency_links to curl_cffi.egg-info/dependency_links.txt
      writing requirements to curl_cffi.egg-info/requires.txt
      writing top-level names to curl_cffi.egg-info/top_level.txt
      reading manifest file 'curl_cffi.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'curl_cffi/cacert.pem'
      warning: no files found matching 'curl_cffi/_wrapper.*'
      warning: no files found matching 'curl_cffi/include/curl/*'
      adding license file 'LICENSE'
      writing manifest file 'curl_cffi.egg-info/SOURCES.txt'
      /tmp/pip-build-env-urinostm/overlay/local/lib/python3.10/dist-packages/setuptools/command/build_py.py:201: _Warning: Package 'curl_cffi.ffi' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'curl_cffi.ffi' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'curl_cffi.ffi' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'curl_cffi.ffi' to be distributed and are
              already explicitly excluding 'curl_cffi.ffi' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      creating build/lib.linux-aarch64-cpython-310/curl_cffi/ffi
      copying curl_cffi/ffi/cdef.c -> build/lib.linux-aarch64-cpython-310/curl_cffi/ffi
      copying curl_cffi/ffi/shim.c -> build/lib.linux-aarch64-cpython-310/curl_cffi/ffi
      copying curl_cffi/ffi/shim.h -> build/lib.linux-aarch64-cpython-310/curl_cffi/ffi
      running build_ext
      generating cffi module 'build/temp.linux-aarch64-cpython-310/curl_cffi._wrapper.c'
      creating build/temp.linux-aarch64-cpython-310
      building 'curl_cffi._wrapper' extension
      creating build/temp.linux-aarch64-cpython-310/build
      creating build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/curl_cffi
      creating build/temp.linux-aarch64-cpython-310/curl_cffi/ffi
      arm-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Icurl_cffi/include -Icurl_cffi/ffi -I/usr/include/python3.10 -c build/temp.linux-aarch64-cpython-310/curl_cffi._wrapper.c -o build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310/curl_cffi._wrapper.o
      In file included from build/temp.linux-aarch64-cpython-310/curl_cffi._wrapper.c:570:
      curl_cffi/ffi/shim.h:5:10: fatal error: curl/curl.h: No such file or directory
          5 | #include "curl/curl.h"
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for curl-cffi
  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for frozenlist (pyproject.toml): finished with status 'done'
  Created wheel for frozenlist: filename=frozenlist-1.3.3-cp310-cp310-linux_aarch64.whl size=134810 sha256=38651c5a6e5f4f24812135bfb9476c3df9573e931f106dd5fee3195d1a3e3939
  Stored in directory: /root/.cache/pip/wheels/75/c0/b3/57ac2234203df002195d6d093179dc847a8694fb02fe1aefa8
  Building wheel for multidict (pyproject.toml): started
  Building wheel for multidict (pyproject.toml): finished with status 'done'
  Created wheel for multidict: filename=multidict-6.0.4-cp310-cp310-linux_aarch64.whl size=110121 sha256=67d8a82d106b17d58c7bc51f1c7810a0a70a9a20bd63d68c3879af3d62020101
  Stored in directory: /root/.cache/pip/wheels/d3/0f/ad/bd2376f99105cc211cfe25f50868fdbddedcf5bab5a699e47b
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'done'
  Created wheel for yarl: filename=yarl-1.9.2-cp310-cp310-linux_aarch64.whl size=211512 sha256=7fbb35c0fdcaf032d1b3ac00aae11e09c355901a386f60eef3445c403ed9ca00
  Stored in directory: /root/.cache/pip/wheels/66/b6/b8/1a4ac9b4227cd4212504cc12bf9147c30534b8d5416233fc92
Successfully built aiohttp frozenlist multidict yarl
Failed to build curl-cffi
ERROR: Could not build wheels for curl-cffi, which is required to install pyproject.toml-based projects
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 634, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1

**Comment by bjia56** [comment]
Thanks for the logs. As the first few lines suggest, there's an issue on your raspberry pi where it's running in 32 / 64 bit mixed mode. The recommended fix is documented in #678

**Comment by deflao** [comment]
Thank you. the plugin is loaded now. I'll monitor this for next couple days. I'll let you know if it happens again.
