### ISSUE TITLE
Runaway multiprocessing.resource_tracker spawns eat memory

### ISSUE THREAD

**Issue by mmichon** [koush/scrypted#948]
Continuation of #778.

Exhausts swap and requires me to reboot my 4GB RPi 4B every few days. I'm running Bullseye 32 bit.

![](https://user-images.githubusercontent.com/673622/252391233-b0a5f9b8-a2fe-4430-a41c-efe25ebacebd.png)

![](https://user-images.githubusercontent.com/673622/252391253-c3b69f56-86d5-4a46-b037-7b12bba224da.png)

<img width="1364" alt="Screenshot 2023-07-11 at 7 52 42 PM" src="https://github.com/koush/scrypted/assets/673622/21d7f066-9c72-4c89-8f1c-cd9ee837b6c9">

**Comment by koush** [comment]
Can you try opencv instead?

**Comment by mmichon** [comment]
> Can you try opencv instead?

Switched to opencv and it looks like memory consumption has flatlined. CPU is lower too, so I'll be keeping this config. Could be something about PAM diff.

<img width="556" alt="image" src="https://github.com/koush/scrypted/assets/673622/53844b53-d8fc-41b6-836a-c5f7c4118d8e">

**Comment by koush** [comment]
Yes, pam diff is not recommended or maintained.
