### ISSUE TITLE
Stream taking +20s to load or timeout. No HKSV recording happening

### ISSUE THREAD

**Issue by RuntyCascade** [koush/scrypted#95]
Stream is either taking a long time to start or it times out. (using older Nest Cams & Nest Hello)

> **HomeKit Live Streaming Timeout (Recordings maybe working)**
This is a networking issue with multiple interfaces. This is the problem 100% of the time. Use the HomeKit Address Override setting, and set it to the IP Address of your ethernet manually. If your camera is on a separate VLAN, try disabling that to see if that is the issue.

Not sure how to go about doing this, tried to change the IP (local IPv4) under network. That did not fix the issue. This RPi 3B is also running HomeBridge, and Scrytped is running within docker.

> **HomeKit Secure Video Not Recording**
If recordings dont work, it's generally because of a few reasons, follow the steps to determine where it is failing before asking for help:
5.If your camera is on a separate VLAN, try disabling that to see if that is the issue.

How do i disable VLAN?

**Comment by koush** [comment]
use discord please.

**Comment by koush** [comment]
this is not a bug, this is a network issue.
