### ISSUE TITLE
Docker for Windows needs -p 10443:10443 not 

### ISSUE THREAD

**Issue by makeSmartio** [koush/scrypted#957]
For me, and I have seen some questions on forums, I needed to remove  "--network host" and add "-p 10443:10443" to expose the port. Like this:

docker run -d   --name scrypted   -p 10443:10443  --restart unless-stopped   -v ~/.scrypted:/server/volume   koush/scrypted:latest

**Comment by koush** [comment]
docker on windows is not supported

**Comment by makeSmartio** [comment]
Ahh, good to know. Does it just not work? I have the web UI working but have not been able to add my cameras to HomeKit. Is MacOS supported? Thank you!!!

**Comment by bjia56** [comment]
Docker on Windows or Mac will run Linux in a VM, which means host networking does not work. It's possible to run scrypted and access the admin ui with the 10443 port mapping, however some plugins like homekit will not work properly without host networking.

Your best bet is to do the local install if using Windows or Mac.
