### ISSUE TITLE
Synology docker install - bad images links

### ISSUE THREAD

**Issue by baylanger** [koush/scrypted#96]
Multiple broken images ref. links here:
 
[wiki/Docker:-Synology-NAS](https://github.com/koush/scrypted/wiki/Docker:-Synology-NAS)

I don't have the time now to look into this myself right now.  Anyone else feel free to do so.

**Comment by jasonwaters** [comment]
fixed it for you.  the images host has an invalid or self-signed cert so i changed the references to just http.  fine for images IMO.
