### ISSUE TITLE
Camera not responding in Home app, but only for non-owners

### ISSUE THREAD

**Issue by wez** [koush/scrypted#964]
This is a weird issue; I recently configured a handful of cameras; a couple of reolink and a couple of amcrest cameras using their respective plugins.

I can see them and enable HKSV for them in the Home.app, and events like person detection work.

But only for me!  There are two other people with access to the home in the home app; one is an admin and the other is not.  Both of them can see the cameras in the list, but cannot see the stream or any stills from them; they just get a "camera is not responding" error message.

I've tried watching the console for the specific devices and I don't see anything happening when I try to access the camera from their devices.  It's as though they are not able to reach the scrypted instance.

Have you seen anything like this before?
Any thoughts on how to debug this?

**Comment by koush** [comment]
No idea, but this is an apple issue.
