### ISSUE TITLE
Runaway multiprocessing.resource_tracker spawns

### ISSUE THREAD

**Issue by mmichon** [koush/scrypted#965]
After switching from PAM Diff to OpenCV (#778), Scrypted is still spawning a bunch of `multiprocessing.resource_tracker` processes. Memory is being eaten slower, but it's still happening. 

<img width="978" alt="image" src="https://github.com/koush/scrypted/assets/673622/c524e73d-1626-4c77-99cb-3e7ea4905d1d">
(7/19 9am was restart)

**Comment by koush** [comment]
> I switched to Docker. This is still happening. Exhausts swap and requires me to reboot my 4GB RPi 4B every few days. I'm running Bullseye 32 bit.



> Almost certainly a local install environment issue. Either python or gstreamer. Can try using ffmpeg frame generator for the video pipeline. Scrypted no longer supports armvl7 on Raspbian (due to a mixed mode kernel/userspace issue).

> Install rasbpian lite 64 bit and use Docker.
