### ISSUE TITLE
Erstellung einer Verknüpfung per Web Station (Synology)

### ISSUE THREAD

**Issue by gerd2005** [koush/scrypted#970]
Hallo,
seit einiger Zeit gibt es den Container Manager. Mit diesem kann man leider nicht mehr einfache eine Verknüpfung auf dem Desktop erstellen, wie es mit dem Docker noch möglich war. Man muss nun die "Wen Station" installieren.

Bei dem Unifi-Controller sieht das dann bspw. so aus:
![image](https://github.com/koush/scrypted/assets/72799068/774e198d-e09e-4250-8b7a-b6bd251b1383)

Beim Scrypted fehlt die Einstellung mit dem "Webportal via Web Station".
![image](https://github.com/koush/scrypted/assets/72799068/ec3d4ba0-fda4-4a79-b34f-ebcbaa2cc80a)

Wie bekomme ich das hin, dass ich hierfür eine Verknüpfung auf dem Desktop erstellen kann?
Danke und viele Grüße
gerd

**Comment by koush** [comment]
not a Scrypted question
