### ISSUE TITLE
install the cloud plugin

### ISSUE THREAD

**Issue by VikramGoswami10** [koush/scrypted#973]
install the cloud plugin

_Originally posted by @koush in https://github.com/koush/scrypted/issues/967#issuecomment-1648115966_

![image](https://user-images.githubusercontent.com/138846163/255793385-9b2b3de4-2163-4d22-b490-de4d73a463ba.png)
i did , i install the plugin and from there only I was trying to login

**Comment by koush** [comment]
you need to click login in that screenshot. that is what registers the server. is that what you are trying to do?

**Comment by VikramGoswami10** [comment]
yes , i was clicking on the login

**Comment by VikramGoswami10** [comment]
after clicking login and entering my email and password , its redirecting me to the following page (screenshot), 
![image](https://github.com/koush/scrypted/assets/138846163/e3bb8114-e08d-424e-9554-e30df6a47849)
then entering plugin again the login is still there and i am still not logged in .

**Comment by VikramGoswami10** [comment]
can you tell me one thing , if I want to use scrypted plugin in the background and use it to stream video doorbell videos to alexa and google by giving user a choice to choose display device , can it be done ? 
if yes can you give some recommendations/suggestions as to how to do this ?
