### ISSUE TITLE
Update silently fails

### ISSUE THREAD

**Issue by chrisjshull** [koush/scrypted#978]
Under settings I see:

<img width="379" alt="image" src="https://github.com/koush/scrypted/assets/877679/cf874162-33fa-4202-b3b5-8174bdf49ad7">

But when I click through to update nothing happens. (I don't even know where to look for to see logs for this, sorry.)

Installed via docker compose.

**Comment by koush** [comment]
docker updates are behind, the notification is misleading. it's available now.
