### ISSUE TITLE
Uninstall Scrypted

### ISSUE THREAD

**Issue by rdlink123** [koush/scrypted#98]
Relative noob on Linux/Unix.  I recently updated my Intel Mac plex server where I am running Scrypted to an M1.  I used Time Machine to restore the old machine to the new one, but the terminal fails telling me that the install is expecting x86, but it needs x64.  Which makes sense.  So I need to uninstall Scrypted and reinstall.  Can you provide assistance with the commands?  Thanks.

**Comment by koush** [comment]
https://github.com/koush/scrypted/wiki/Uninstallation
