### ISSUE TITLE
Scrypted docker container is huge (4GB) - is that expected?

### ISSUE THREAD

**Issue by willyp713** [koush/scrypted#980]
My Scrypted container is nearly 4GB in size. I did map `/server/volume` to a different location with an env variable, so it isn't calculated in this screenshot.

<img width="922" alt="image" src="https://github.com/koush/scrypted/assets/21319282/7bdef816-27f5-4891-a08c-4966167c1575">

Is it expected that this is a huge container, or is there perhaps something wrong?

**Comment by koush** [comment]
Yes
