### ISSUE TITLE
Request: ability to "disable" a camera or plugin without deleting it

### ISSUE THREAD

**Issue by airdrummingfool** [koush/scrypted#984]
I have a Reolink doorbell camera that I've been playing with in Scrypted. I set it up in both the Reolink plugin and the ONVIF plugin to compare functionality, but I'm concerned that the camera can't handle both configurations with multiple streams and events, etc.

I think it would be very handy to have a "disable" option in the device settings (or even at the plugin level). This would allow me to keep both plugins configured, but only have one device running at a time. Right now in order to test different setups separately I have to delete the configurations in between tests, which makes it harder to switch back and forth to compare. This would also be useful e.g. for occasional-use cameras, e.g. something that is only set up when away on vacation (like an interior camera).

Anyways, thanks for this awesome platform, it makes my cameras and HKSV so much more useful!

**Comment by rbhr** [comment]
I came here to ask the same thing! This would be a great addition to the magic that is Scrypted.

**Comment by cesarvoggithub** [comment]
+1

**Comment by koush** [comment]
I think the best way to do this would be to set the device type to "Unknown" or something non-camera via the REPL.

`realDevice.setType('Unknown');`

This prevents other extensions like rebroadcast from pulling the stream.
