### ISSUE TITLE
Homekit plugin not selectable for Device Groups

### ISSUE THREAD

**Issue by DutchmanNL** [koush/scrypted#988]
Inspired by https://github.com/koush/scrypted/issues/302 I wanted to integrated a doorbell button, but options for HomeKit seems not be be available (anymore ?) for group devices ?

device groups test created
<img width="719" alt="Screenshot 2023-07-31 at 11 54 09" src="https://github.com/koush/scrypted/assets/7318445/c3caad5f-e53b-4581-8f0a-40e0b1ddf473">

added a dummy switch
<img width="808" alt="Screenshot 2023-07-31 at 11 55 03" src="https://github.com/koush/scrypted/assets/7318445/c5670281-561e-4834-b776-8c7d4534ee8c">

added the doorbell & dummy switch to the new device group
<img width="487" alt="Screenshot 2023-07-31 at 11 55 36" src="https://github.com/koush/scrypted/assets/7318445/4a898655-1dae-412c-8f15-9b176c1a076d">

selected doorbell as type
<img width="492" alt="Screenshot 2023-07-31 at 11 55 55" src="https://github.com/koush/scrypted/assets/7318445/efd670e8-b50b-48bb-839f-2f18403a3962">

No option to enable HomeKit extension
<img width="491" alt="Screenshot 2023-07-31 at 11 56 25" src="https://github.com/koush/scrypted/assets/7318445/1269aae6-1639-4478-9d54-cf2b194e9523">

all my cameras based on hikvision plugin & sinology surveillance work fine and have the HomeKit extension option available

**Comment by koush** [comment]
use dummy switch plugin and custom motion sensor.

**Comment by DutchmanNL** [comment]
> use dummy switch plugin and custom motion sensor. the homekit linked sensor was removed in favor of that.

Confirmed as working, thank you appreciated
