### ISSUE TITLE
Using special characters in passwords on Reolink devices breaks the connection

### ISSUE THREAD

**Issue by MrHollowPS** [koush/scrypted#990]
I have a reolink doorbell poe camera with a passwords that has special characters like (eg. ! # $ % ^). When using this user/password combination scrypted with display a black screen when trying to stream. Looking at the logs i can see that the password is changed in the URL to escape the special characters which breaks the login with Reolink so it doesn't work anymore.

The fix for this is to use a separate user with alphanumerical characters.

**Comment by koush** [comment]
Correct. This is documented in the camera setup docs. Many cameras do not handle properly escaped urls.
