### ISSUE TITLE
Request: Custom notifications per camera

### ISSUE THREAD

**Issue by gagy2** [koush/scrypted#994]
Could there be a way to enable / disable notifications on a camera basis depending on an event. 
Currently using the Scrypted NVR iOS Device (User-devicename) with an homekit extension so I can enable / disable notifications automatically when in my Geofence. 

Would like the option to Disable notifications on some cameras but keep it on others when Home, and enable it on all Cameras when Away for example.

**Comment by koush** [comment]
Some discussion here https://discord.com/channels/882329362295316500/933126942943739956/1136347669007179876

**Comment by koush** [comment]
```ts
// this is my iOS notifier id in scrypted.
const realNotifier = systemManager.getDeviceById<Notifier>('1352');

class PassthroughNotifier extends ScryptedDeviceBase implements OnOff, Notifier {
    async turnOff(): Promise<void> {
        this.on = false;
    }
    async turnOn(): Promise<void> {
        this.on = true;
    }

    sendNotification(title: string, options?: NotifierOptions, media?: string | MediaObject, icon?: string | MediaObject): Promise<void> {
        if (!this.on)
          return;
        return realNotifier.sendNotification(title, options, media, icon);
    }

}

export default PassthroughNotifier;
```

can be done with scripting like this.

support may be further improved or streamlined in the future to be easier to use, but this is the most flexible way to do it.
