### ISSUE TITLE
Homekit: Audio only after clicking on "Speak"

### ISSUE THREAD

**Issue by t1ll** [koush/scrypted#996]
Hi,

First of all a big thank you for Scrypted 🙏 It makes my Doorbird Camera so much better!

Unfortunately I'm having a strange issue with the audio in combination with Homekit when streaming:
- In Homekit the stream is always loading without audio (both mobile & desktop Home app)
- It's also not turning on when changing the volume
- When I hit "Speak" the audio finally turns on and stays on (this is true for most of the times; sometimes the speak button does not change anything [also not throwing any messages in the log in that case]
- Even after disabling Speak the audio stays
(the exact scenario above is what I logged and sharing in the log below)

**What i tried already separately and in combination (both without success):**
- I tried already switching the RTP sender from Scrypted to default
- I tried already disabling prebuffering for the default stream

**Maybe noteworthy:**
- The stream in the Scrypted UI always has audio

Do you have any idea what could be the problem? I see the _461 Unsupported Transport_ in the logs but I'm not sure if that is related to the problem. 

Any help is very much appreciated.

**LOGS:**

[HomeKit]: destination address 192.168.0.106 63195 53257
[HomeKit]: using address override 192.168.0.62
[HomeKit]: source address 192.168.0.62 60201 41130
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: '6cb0b1b4-487c-4211-896e-7a82982de99f',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3657308309,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 1602109310,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: Will wait for initial RTCP packet. { isHomeHub: false, isLowBandwidth: false, hasHomeHub: false }
[HomeKit]: { isLowBandwidth: false, isWatch: false, destination: 'local' }
[Rebroadcast Plugin]: Selected stream default
[Rebroadcast Plugin]: sending prebuffer 997.5
[HomeKit]: { tool: undefined, rtpSender: 'Scrypted' }
[HomeKit]: Waiting for video RTCP packet before sending video.
[HomeKit]: packet loss 1
[HomeKit]: Received first video RTCP packet.
[HomeKit]: rtsp/tcp h264
[HomeKit]: a/v h264 opus found h264 undefined
[HomeKit]: rtsp/tcp pcm_alaw
[Rebroadcast Plugin]: default active rebroadcast clients: 1
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[HomeKit]: -hide_banner -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 9740883 -dn -sn -vn -f rtp rtp://127.0.0.1:38108?pkt_size=400 -sdp_file pipe:4
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 24 7 8
[HomeKit]: idr start found: 28 5
[HomeKit]: [rtsp @ 0x55b93cbe00] method SETUP failed: 461 Unsupported Transport
[HomeKit]: Guessed Channel Layout for Input Stream #0.0 : mono
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:45561':
[HomeKit]:   Metadata:
[HomeKit]:     title           : RTSP/RTP stream from DoorBird
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: 64 kb/s
[HomeKit]:   Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (pcm_mulaw (native) -> opus (libopus))
[HomeKit]: Press [q] to stop, [?] for help
[HomeKit]: Output #0, rtp, to 'rtp://127.0.0.1:38108?pkt_size=400':
[HomeKit]:   Metadata:
[HomeKit]:     title           : RTSP/RTP stream from DoorBird
[HomeKit]:     encoder         : Lavf58.76.100
[HomeKit]:   Stream #0:0: Audio: opus, 24000 Hz, mono, s16, 24 kb/s
[HomeKit]:     Metadata:
[HomeKit]:       encoder         : Lavc58.134.100 libopus
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: received first audio packet
Doorbird: Starting audio receiver...
Doorbird: Starting audio transmitter...
Doorbird: audio transmitter started.
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

[rtsp @ 0x5572a0bc20] method SETUP failed: 461 Unsupported Transport

Input #0, rtsp, from 'rtsp://127.0.0.1:33223':
  Metadata:
    title           : HomeKit Audio Talkback
  Duration: N/A, start: 0.000000
, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (opus (libopus) -> pcm_mulaw (native))
Press [q] to stop, [?] for help

Output #0, mulaw, to 'pipe:3':
  Metadata:
    title           : HomeKit Audio Talkback
    encoder         : Lavf58.76.100

  Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.134.100 pcm_mulaw
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
[mulaw @ 0x55a6f3bc90] Estimating duration from bitrate, this may be inaccurate

Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, mulaw, from 'http://ghgtty0002:Vff9t37pHW@192.168.0.224:80/bha-api/audio-receive.cgi':
  Duration: 00:20:50.00, bitrate: 64 kb/s
  Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Output #0, mulaw, to 'pipe:3':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
Stream mapping:

  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help

size=       4kB time=00:00:00.53 bitrate=  66.4kbits/s speed=1.04x    
size=       8kB time=00:00:01.05 bitrate=  65.2kbits/s speed=1.02x    
size=      12kB time=00:00:01.57 bitrate=  64.8kbits/s speed=1.01x    
size=      16kB time=00:00:02.07 bitrate=  64.6kbits/s speed=1.01x    
size=      20kB time=00:00:02.57 bitrate=  64.5kbits/s speed=1.01x    
size=      24kB time=00:00:03.09 bitrate=  64.4kbits/s speed=1.01x    
[HomeKit]: handleStreamRequest { sessionID: '6cb0b1b4-487c-4211-896e-7a82982de99f', type: 'stop' }
[HomeKit]: streaming session killed, duration: 10s
[HomeKit]: Stopping intercom.
size=      27kB time=00:00:03.45 bitrate=  64.0kbits/s speed=0.496x    
size=      27kB time=00:00:03.45 bitrate=  64.0kbits/s speed=0.496x    
video:0kB audio:27kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

[Rebroadcast Plugin]: default active rebroadcast clients: 0
Doorbird: audio transmitter finished.
Doorbird: audio receiver ended.
Doorbird: Audio transmitter ended.
[HomeKit]: ffmpeg exited

**Comment by chip131001** [comment]
Hi,

I can observe the same behavior with me.

**Comment by t1ll** [comment]
apparently it is normal.

This is a reply from Thyraz in the Scrypted Discord:

> I think that's how the doorbird works.
> The audio isn't part of the stream as far as I know and has to be received seperately.
> And iirc audio will also be canceled after some time.
> 
> I guess it's because Doorbird is a german company, and we have more strict privacy rules.
> 24/7 video recording is already problematic and you have to add signs about video recording on the entrance of your property.
> 
> Audio recording, which isn't blocked by walls etc. might be even more problematic.
> Might be the reason why they try to treat this more like a legacy doorbell with video and less like a surveillance camera.
